### PR TITLE
Disputes: Prevent errors crashing the payment details page

### LINKED ISSUE #7371: Transaction details → wrap dispute details component in an ErrorBoundary to allow transaction details to render if a JS error occurs
If an unhandled error occurs with dispute details on the transaction details page, the entire transaction details header component fails to render.

We should wrap the dispute details in an `<ErrorBoundary />` to ensure that the transaction details render correctly in this case.

Screenshot of an unhandled JS error:

Image

### PR DESCRIPTION
**Pull request by brucealdridge**
Fixes #7371 

#### Changes proposed in this Pull Request

If an unhandled error occurs with dispute details on the transaction details page, the entire transaction details header component fails to render.

This PR adds an `<ErrorBoundary />` around the new dispute section on the transaction details page to ensure that the transaction details render correctly in this case.

**Before:**
Screenshot 2023-10-05 at 4 54 21 PM

**After:**
Screenshot 2023-10-05 at 4 54 48 PM

#### Testing instructions

* Alter the code so that an error is thrown. I added `throw new Error( 'This is a test error' );` inside `<DisputeSteps />`
* View the dispute details with and without this branch.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7378` or branch name `add/7371-dispute-details-error-boundary` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/7371-dispute-details-error-boundary) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 96b1eb863ff178d532e5466ea66ae818bca8dc08
- Build time: 2023-10-05 23:49:32 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/payment-details/summary/index.tsx [hunk 1]
```diff
@@ -51,6 +51,7 @@ import CancelAuthorizationButton from '../../components/cancel-authorization-but
 import { PaymentIntent } from '../../types/payment-intents';
 import DisputeAwaitingResponseDetails from '../dispute-details/dispute-awaiting-response-details';
 import DisputeResolutionFooter from '../dispute-details/dispute-resolution-footer';
+import ErrorBoundary from 'wcpay/components/error-boundary';
```
Comment (Jinksi) [inline client/payment-details/summary/index.tsx]: Incredibly minor nitpick that is probably pedantic and not useful: remove `wcpay/` from `components/error-boundary` import to be consistent with other component imports within this file.

```suggestion
import ErrorBoundary from 'components/error-boundary';
```

**Review by Jinksi — APPROVED** [review]
Nice one @brucealdridge!

I tested this with a potentially-realistic example and the `ErrorBoundary` allowed the transaction details to render.

I added `const testError = ( dispute as any ).issuer_evidence.evidence_type;` to the `DisputeAwaitingResponseDetails` component and received the following screenshot:

image
