### PR TITLE
Hide "Fraud Protection" menu when the user is not fully onboarded

### LINKED ISSUE #6907: Fraud protection menu item inside of Payments should not be accessible if no account is onboarded
### Describe the bug
The new item "Fraud protection" inside of the "Payments" parent item is displayed and accessible even without an onboarded account. This should not be the case and should only be displayed if an account is connected.

### To Reproduce

1. Delete your local account
3. Click on Payments
4. Click the 'Finish setup' button to start the onboarding process.
5. Go back to the store without finishing the onboarding process.
6. See "Fraud protection" under payments.
7. Click on it

### Screenshots
image

image

cc @Automattic/sigma

### PR DESCRIPTION
**Pull request by tpaksu**
Fixes #6907

### Changes proposed in this Pull Request

This PR adds an extra clause to the Stripe account connection check before adding the menu item. The problem is when the user starts onboarding, the Stripe account ID is created and attached to the blog, which makes `Account::is_stripe_connected()` return `true`, but the account is not fully onboarded. To fix it, we also need to test if `Account::is_stripe_account_valid` returns `true`.

#### Reproducing

* Create a JN site with the latest version of WooPayments
* Start onboarding to a new Stripe account, but click `Return to WooPayments` link before finishing it
* Check if the `Fraud Protection` menu is visible under `Payments`.

#### Testing the fix
* Create a new release ZIP from this branch, and upload it a new JN site (or directly click [this link](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6907-fraud-protection-menu-item-accessible-if-not-onboarded&woocommerce-payments-dev-tools) to create a new JN site using this branch code. 
* Test the above scenario again.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6978` or branch name `fix/6907-fraud-protection-menu-item-accessible-if-not-onboarded` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6907-fraud-protection-menu-item-accessible-if-not-onboarded) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: e72e2f368759cded071945691a38378774c7056a
- Build time: 2023-08-11 07:52:34 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by shendy-a8c — APPROVED** [review]
Looks good! I no longer see the 'Fraud protection' menu item when I'm half-onboarded.

File: includes/fraud-prevention/class-fraud-risk-tools.php [hunk 1]
```diff
@@ -82,7 +82,7 @@ public function init_advanced_settings_page() {
 			return;
 		}
 
-		if ( ! $this->payments_account->is_stripe_connected() ) {
+		if ( ! $this->payments_account->is_stripe_connected() || ! $this->payments_account->is_stripe_account_valid() ) {
```
Comment (ismaeldcom) [inline includes/fraud-prevention/class-fraud-risk-tools.php]: As `is_stripe_account_valid` calls `is_stripe_connected`, I think it's safe to just check for `is_stripe_account_valid`, right?

**Review by ismaeldcom — APPROVED** [review]
Thanks for the quick fix! Works as expected, I just left a tiny comment about the condition, but it's ready to go 🚀

File: includes/fraud-prevention/class-fraud-risk-tools.php (hunk 1 above)
Comment (tpaksu) [reply includes/fraud-prevention/class-fraud-risk-tools.php]: Yep, that makes sense. Didn't check the method content before adding it, removed it in [e72e2f3](https://github.com/Automattic/woocommerce-payments/pull/6978/commits/e72e2f368759cded071945691a38378774c7056a).
