### PR TITLE
Platform Checkout settings responsiveness

### LINKED ISSUE #4337: fix: platform checkout settings page
### Describe the bug

The platform checkout settings page is not responding well on mobile devices.

### To Reproduce

1. Go to the settings page
2. Ensure you have the platform checkout enabled for your site
3. Click on "Customize" for WooPay
Screen Shot 2022-06-09 at 5 23 29 PM
5. See error

### Actual behavior

The "Checkout appearance" title should appear on top of the section that allows to upload a logo (and not on top of the whole page).
Screen Shot 2022-06-09 at 5 15 59 PM

Notice behavior of other pages, for reference:
Screen Shot 2022-06-09 at 5 21 35 PM

The SVG for the preview is not responsive and it breaks mobile devices' behavior:
Screen Shot 2022-06-09 at 5 22 57 PM

### Expected behavior

- SVG for the checkout preview should be responsive
- Section title should appear at the top of the section

### PR DESCRIPTION
**Pull request by alefesouza**
Fixes #4337

#### Changes proposed in this Pull Request

* Makes the Platform Checkout settings preview SVG be responsive to work better on mobile devices.

#### Testing instructions

* Access WCPay settings.
* On Platform Checkout, click on `Customize`.
* Simulate a mobile device on browser DevTools.
* The page should not break and the sections should be better separated.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: changelog/fix-4337-platform-checkout-settings-responsive [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Platform Checkout settings responsive.
```
Comment (leonardola) [inline changelog/fix-4337-platform-checkout-settings-responsive:4]: Let's change this to `Platform Checkout settings responsiveness.`

File: client/settings/express-checkout-settings/platform-checkout-settings.js [hunk 2]
```diff
@@ -38,69 +38,84 @@ const PlatformCheckoutSettings = () => {
...
-						storeLogo={ platformCheckoutStoreLogo }
-					></PlatformCheckoutPreview>
-					<div className="platform-checkout-settings__preview-fade"></div>
-				</div>
-				<CardBody>
-					<div className="platform-checkout-settings__custom-message-wrapper">
-						<h4>
-							{ __(
-								'Store logo on checkout',
+			{ 'general' === section && (
```
Comment (leonardola) [inline client/settings/express-checkout-settings/platform-checkout-settings.js:41]: Maybe we should split this component into two others instead of using a conditional to return the section wanted. What do think?

**Review by leonardola — CHANGES_REQUESTED** [review]
I left a few comments about minor changes and a possible refactor

File: client/settings/express-checkout-settings/platform-checkout-settings.js (hunk 2 above)
Comment (alefesouza) [reply client/settings/express-checkout-settings/platform-checkout-settings.js:41]: It's the same approach already used on `Apple Pay / Google Pay` settings [here](https://github.com/Automattic/woocommerce-payments/blob/fix/4157-show-woopay-error-message/client/settings/express-checkout-settings/payment-request-settings.js#L161) and [here](https://github.com/Automattic/woocommerce-payments/blob/fix/4157-show-woopay-error-message/client/settings/express-checkout-settings/index.js#L51).

File: changelog/fix-4337-platform-checkout-settings-responsive (hunk 1 above)
Comment (alefesouza) [reply changelog/fix-4337-platform-checkout-settings-responsive]: Fixed on https://github.com/Automattic/woocommerce-payments/pull/4369/commits/0cde21f93b20d16f42f315f7b54bec4cdb79a692.

File: client/settings/express-checkout-settings/platform-checkout-settings.js (hunk 2 above)
Comment (leonardola) [reply client/settings/express-checkout-settings/platform-checkout-settings.js:41]: ok. That looks ugly to me. But as it's already a pattern let's keep it for now

**Review by leonardola — APPROVED** [review]
This LGTM. Let's :shipit:
