### PR TITLE
Fix - The "Finish Setup" button just reloads the setup page and doesn't redirect to Stripe onboarding.

### LINKED ISSUE #2288: Unable to Start Setup
The "Finish Setup" button just reloads the setup page and doesn't redirect to Stripe onboarding. The issue isn't present in 2.5.0 and only occurs on the `develop` branch since that release (I haven't investigated where the issue might have been introduced more than that).

image

There seems to be a problem with the URL escaping somewhere along the line. The button sends:
```
Array
(
    [page] => wc-admin
    [amp;path] => /payments/connect
    [amp;wcpay-connect] => 1
    [amp;_wpnonce] => 459eb0265d
)
```

Marking this as high priority because we need to have it fixed before the 2.6.0 release on Wednesday.

### PR DESCRIPTION
**Pull request by naman03malhotra**
Fixes #2288 

#### Changes proposed in this Pull Request
Fixed the redirecting for finish setup button on connect page.

#### Testing instructions
- switch to `fix/2288-fix-reload`.
- Now force onboard using the dev plugin and try clicking on finish setup, you should be redirected to stripe.
- Now switch your country to one of the non-supported countries ([see supported countries list](https://github.com/Automattic/woocommerce-payments/blob/add/694-onboarding-store-location-check/includes/class-wc-payments-utils.php#L178)).
- Now when you click on finish setup, a prompt should appear - now click on finish setup on the prompt - you should be redirected to stripe.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/admin/class-wc-payments-admin.php [hunk 1]
```diff
@@ -258,8 +258,8 @@ public function register_payments_scripts() {
 		delete_transient( WC_Payments_Account::ERROR_MESSAGE_TRANSIENT );
 
 		$wcpay_settings = [
+			'url'                   => WC_Payments_Account::get_connect_url(),
```
Comment (kalessil) [inline includes/admin/class-wc-payments-admin.php:261]: I'd suggest using `connectUrl` (as it was before my changes).

**Review by shendy-a8c — APPROVED** [review]
Looks good and it works.
