### PR TITLE
Hide WooPay button when logged out and subscriptions involved

### LINKED ISSUE #6131: WooPay not compatible with guest checkout in some cases
### Describe the bug
Checkout via WooPay's express checkout cannot be completed for logged out shoppers in the following cases:
- For checkouts involving Subscriptions products
- For checkouts when the `WooCommerce > Settings > Accounts & Privacy > Allow customers to place orders without an account` setting is disabled

### Expected behavior
To remediate, we should prioritize changes that hide incompatible WooPay features for logged out shoppers in the above conditions. These changes may include hiding features on the checkout, cart, and product pages.

### PR DESCRIPTION
**Pull request by reykjalin**
Fixes #6131 

## Changes proposed in this Pull Request

> **Note**
> "Subscription product" here refers to both WC Subscriptions products and WCPay Subscriptions products.

Do not show WooPay button when:

- The customer is not logged into the merchant store and a subscription product is in the cart.
- The customer is not logged into the merchant store and is looking at a subscription product page.
- The customer is not logged into the merchant store and the **WooCommerce → Accounts & Privacy → Allow customers to place orders without an account** setting is disabled.

| \ | Logged In | Logged Out |
|:---:|:---:|:---:|
| Product | image | image |
| Cart | image | image |
| Checkout | image | image |

## Testing instructions

> **Warning**
> The following testing instructions assume you have the WooPay button enabled everywhere it can possibly be:
>
> image

#### Doesn't see WooPay button on subscription product page

1. Create a **Simple Subscription** product if you haven't already.
2. Navigate to that product's page.
3. Make sure the WooPay button isn't visible.

Repeat the test with a **Variable Subscription** product.

#### Does see WooPay button on a non-subscription product page

1. Create a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Navigate to that product's page.
3. Make sure the WooPay button is visible.

Repeat the test with all non-subscription type products.

#### Doesn't see WooPay button on cart page when a subscription product is in the cart

1. Create a **Simple Subscription** product and a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Add that product to the cart.
3. Navigate to the **Cart** page.
4. Make sure the WooPay button isn't visible.
5. Add another non-subscription product to the cart and navigate back to the **Cart** page.
6. Make sure the WooPay button isn't visible.

Repeat the test with a **Variable Subscription** product and 2-3 different sets and amounts of subscription and non-subscription products.

Check with a mix of subscription and non-subscription products as well.

#### Does see WooPay button on cart page when all products in the cart are non-subscription products

1. Create a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Add any number of non-subscription products to the cart.
3. Navigate to the **Cart** page.
4. Make sure the WooPay button is visible.

#### Doesn't see WooPay button on checkout page when a subscription product is in the cart

1. Create a **Simple Subscription** product and a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Add that product to the cart.
3. Navigate to the **Checkout** page.
4. Make sure the WooPay button isn't visible.
5. Add another non-subscription product to the cart and navigate back to the **Checkout** page.
6. Make sure the WooPay button isn't visible.

Repeat the test with a **Variable Subscription** product and 2-3 different sets and amounts of subscription and non-subscription products.

Check with a mix of subscription and non-subscription products as well.

#### Does see WooPay button on checkout page when all products in the cart are non-subscription products

1. Create a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Add any number of non-subscription products to the cart.
3. Navigate to the **Checkout** page.
4. Make sure the WooPay button is visible.

#### Doesn't see WooPay button anywhere when the **WooCommerce → Accounts & Privacy → Allow customers to place orders without an account** setting is disabled

1. Go to **WooCommerce → Accounts & Privacy** and make sure the **Allow customers to place orders without an account** is disabled.
2. Navigate to any product page and make sure the WooPay button is not visible.
3. Add the product to the cart.
4. Navigate to the **Cart** page and make sure the WooPay button is not visible.
5. Navigate to the **Checkout** page and make sure the WooPay button is not visible.

Repeat steps 1-5 with different types of products, e.g. try with a simple product, simple subscription, and a variable product.

#### Does see WooPay button on a subscription product page

1. Create a **Simple Subscription** product if you haven't already.
7. Navigate to that product's page.
8. Make sure the WooPay button is visible.

Repeat the test with a **Variable Subscription** product.

#### Does see WooPay button on cart page when a subscription product is in the cart

1. Create a **Simple Subscription** product and a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Add that product to the cart.
3. Navigate to the **Cart** page.
9. Make sure the WooPay button isn't visible.
10. Add another non-subscription product to the cart and navigate back to the **Cart** page.
11. Make sure the WooPay button is visible.

Repeat the test with a **Variable Subscription** product and 2-3 different sets and amounts of subscription and non-subscription products.

Check with a mix of subscription and non-subscription products as well.

#### Does see WooPay button on checkout page when a subscription product is in the cart

1. Create a **Simple Subscription** product and a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Add that product to the cart.
3. Navigate to the **Checkout** page.
4. Make sure the WooPay button isn't visible.
6. Add another non-subscription product to the cart and navigate back to the **Checkout** page.
7. Make sure the WooPay button is visible.

Repeat the test with a **Variable Subscription** product and 2-3 different sets and amounts of subscription and non-subscription products.

Check with a mix of subscription and non-subscription products as well.

#### Does see WooPay button everywhere when the **WooCommerce → Accounts & Privacy → Allow customers to place orders without an account** setting is disabled

1. Go to **WooCommerce → Accounts & Privacy** and make sure the **Allow customers to place orders without an account** is disabled.
2. Navigate to any product page and make sure the WooPay button is visible.
3. Add the product to the cart.
4. Navigate to the **Cart** page and make sure the WooPay button is visible.
5. Navigate to the **Checkout** page and make sure the WooPay button is visible.

Repeat steps 1-5 with different types of products, e.g. try with a simple product, simple subscription, and a variable product.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6133` or branch name `add/woopay-unavailable-for-subscriptions-when-logged-out` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=add/woopay-unavailable-for-subscriptions-when-logged-out) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: c2b61b2f2c8fba6712e582317b0e3cf0e8cc4caf
- Build time: 2023-04-24 22:53:19 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by asumaran** [comment]
@reykjalin Button shows up for Variable Subscriptions. It only happens on the product page, though. 
image

File: includes/class-wc-payments-platform-checkout-button-handler.php [hunk 1]
```diff
@@ -623,4 +645,24 @@ private function get_product() {
...
+
+	/**
+	 * Returns true if the provided WC_Product is a subscription, false otherwise.
+	 *
+	 * @param WC_Product $product The product to check.
+	 *
+	 * @return bool  True if product is subscription, false otherwise.
+	 */
+	private function is_product_subscription( WC_Product $product ): bool {
+		return 'subscription' === $product->get_type() || 'subscription_variation' === $product->get_type();
```
Comment (asumaran) [inline includes/class-wc-payments-platform-checkout-button-handler.php]: We also need to consider `variable-subscription` here

**Review by asumaran — CHANGES_REQUESTED** [review]
Code looks good overall. I just left a comment for you @reykjalin

File: includes/class-wc-payments-platform-checkout-button-handler.php (hunk 1 above)
Comment (asumaran) [reply includes/class-wc-payments-platform-checkout-button-handler.php]: Where the `subscription_variation` product type comes from? I've tried creating a variable subscription with and without WC Subcriptions enabled both had `variable-subscription` as the product type.

Comment (reykjalin) [reply includes/class-wc-payments-platform-checkout-button-handler.php]: I got it from [the code in subscriptions core](https://github.com/Automattic/woocommerce-subscriptions-core/blob/a923da64ef4e5c4b7747fa81f4b496ca4dfb6298/includes/class-wc-product-subscription-variation.php#L64-L71) 🤔 

I just figured it was the type for the variable subscription type, but maybe I'm wrong? I'll keep it in and add `variable-subscription`, thanks for catching that!

Comment (reykjalin) [reply includes/class-wc-payments-platform-checkout-button-handler.php]: Fixed in c2b61b2f2c8fba6712e582317b0e3cf0e8cc4caf 🙌

**Review by asumaran — APPROVED** [review]
LGTM! 🚀
