### PR TITLE
Merge WC_REST_Payments_Payment_Intents_Create_Controller back into WC_REST_Payments_Payment_Intents_Controller

### LINKED ISSUE #7465: Revert changes made to workaround plugin update issue
### Describe the bug
Revert the changes made to introduce `WC_REST_Payments_Payment_Intents_Create_Controller` in order to workaround #7464 

### Actual behavior
Had to introduce `WC_REST_Payments_Payment_Intents_Create_Controller` to avoid any changes to existing controller `WC_REST_Payments_Payment_Intents_Controller `

### Expected behavior
Both APIs belong in `WC_REST_Payments_Payment_Intents_Controller ` 

### Additional context
Refer p1696877278872479-slack-CGGCLBN58

### PR DESCRIPTION
**Pull request by alopezari**
Fixes #7465.

There has been a recurring issue where WooPayments caused a fatal error after upgrading to a newer version if this new version introduced any change in the constructor from REST controller classes ([ref 1](https://github.com/Automattic/woocommerce-payments/issues/7464), [ref 2](https://wordpress.org/support/topic/error-after-latest-update-20/)).

There were some attempts of fixing this issue, including:
- A [workaround](https://github.com/Automattic/woocommerce-payments/pull/7447/) for one of these [issues](https://github.com/Automattic/woocommerce-payments/issues/7464) that should be [reverted](https://github.com/Automattic/woocommerce-payments/issues/7465) once a proper long-term and generic solution was in place.
- A fix in WooPayments that arrived in **v7.7.0** thanks to #8805.
- A fix in WooCommerce ([woocommerce/woocommerce#47704](https://github.com/woocommerce/woocommerce/pull/47704)) that arrived in **v9.2.0** in order to address [woocommerce/woocommerce#47266](https://github.com/woocommerce/woocommerce/issues/47266).

After testing multiple scenarios against this issue, we can conclude that the combination of both fixes in WooCommerce and WooPayments solved the problem, they do it even separately. Therefore, we're in a good position to action #7465 and revert the referenced code, merging `WC_REST_Payments_Payment_Intents_Create_Controller` back into `WC_REST_Payments_Payment_Intents_Controller`.

#### Changes proposed in this Pull Request
- Merged `WC_REST_Payments_Payment_Intents_Create_Controller` into `WC_REST_Payments_Payment_Intents_Controller`.
- Removed `WC_REST_Payments_Payment_Intents_Create_Controller`, replacing its usage with `WC_REST_Payments_Payment_Intents_Controller`.
- Updated unit tests accordingly.

##### Automated testing
* Make sure both unit and E2E tests passed on CI.

###### Setup for scenarios below
* Spin up a new test site with [Query Monitor](https://wordpress.org/plugins/query-monitor/) and [WooCommerce 9.1.4](https://github.com/woocommerce/woocommerce/releases/download/9.1.4/woocommerce.zip) (the latest version before the WooCommerce fix was included).
* Create a zip package from this branch with `npm run build:release`, move it to a safe path (as the release folder is cleared every time you generate a new zip) and rename it to something like `woocommerce-payments-test-1.zip`.
* Install the plugin from the previous step on the site you created earlier.
* Now apply this [patch](https://github.com/user-attachments/files/19112165/test.patch) to this branch by placing it in the root path of the repository and running `git apply test.patch`. It will add new arguments to constructors from a couple of REST controller classes.
* Create another zip from this branch including the new changes with `npm run build:release` and - again - move it to a safe path and rename it to something like `woocommerce-payments-test-2.zip`.

###### Scenario: No fatal errors are shown after updating WooPayments to a version that contains changes in REST controller's constructors
* Install `woocommerce-payments-test-2.zip` on the site you created in order to force an update to a version that contains changes in REST controller's constructors.
* Confirm the update.
* Make sure no fatal errors are shown.

###### Scenario: No fatal errors are shown after downgrading WooPayments to a version that contains changes in REST controller's constructors
* Make sure that `woocommerce-payments-test-2.zip` is installed.
* Now install `woocommerce-payments-test-1.zip` and confirm the downgrade.
* Make sure no fatal errors are shown.

###### Scenario: No fatal errors are shown after updating WooPayments to a version that contains changes in REST controller's constructors using the natural update flow from WordPress instead of uploading a zip
* Unzip `woocommerce-payments-test-2.zip`, open the file `woocomerce-payments.php`, update the `Version` value to `8.9.0`, save it and compress it again as `woocommerce-payments-test-3.zip`.
* Install `woocommerce-payments-test-3.zip`.
* Go to `/wp-admin/plugins.php` and notice that a suggestion to update plugin appears under `WooPayments`. Click it and confirm the update.
* Make sure the plugin is updated and no fatal errors are shown.

###### Scenario: No fatal errors are shown after doing bulk update of multiple plugins, including updating WooPayments to a version that contains changes in REST controller's constructors
* Make sure `woocommerce-payments-test-3.zip` is installed, otherwise, install it.
* Install an earlier version of another plugin, like [WooCommerce Stripe Gateway v9.1.1](https://github.com/woocommerce/woocommerce-gateway-stripe/releases/download/9.1.1/woocommerce-gateway-stripe.zip).
* Go to `/wp-admin/plugins.php` and notice that a suggestion to update plugin appears under `WooPayments` and `WooCommerce Stripe Gateway`.
* Select both plugins, then click `Bulk actions -> Update` and finally `Apply`.
* Make sure the plugins are updated and no fatal errors are shown.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10505` or branch name `update/payment-intents-controller-class` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/payment-intents-controller-class) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 8bf68a14f788a80b87a6921224315763149e1c30
- Build time: 2025-04-08 13:27:46 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by achyuthajoy — COMMENTED** [review]
@alopezari Thanks for working on this.

Since the Woo core issue was fixed in 9.2.0, should we hold off from merging this PR until the min supported WC version for WooPayments is 9.2.0 to be extra safe? Right now it's 7.6.0.

Let me know your thoughts. I understand that the current fix we have in place is more than enough to resolve this issue.

**Review by jessy-p — APPROVED** [review]
Thanks for working on this @alopezari 

Code changes look good and revert my [workaround](https://github.com/Automattic/woocommerce-payments/pull/7447) perfectly.

Noting that the original Proof of Concept for which this API was developed pcreKM-1Xt-p2 is not working now with latest WooPayments version. This fix is not the cause of the regression 👍

File: includes/admin/class-wc-rest-payments-payment-intents-controller.php [hunk 1]
```diff
@@ -39,6 +60,38 @@ public function register_routes() {
...
+			]
+		);
+	}
+
+	/**
+	 * WC_REST_Payments_Payment_Intents_Controller constructor.
+	 *
+	 * @param WC_Payments_API_Client   $api_client       WooCommerce Payments API client.
+	 * @param WC_Payment_Gateway_WCPay $gateway          WooCommerce Payments payment gateway.
+	 * @param OrderService             $order_service    The new order servie.
```
Comment (zmaglica) [inline includes/admin/class-wc-rest-payments-payment-intents-controller.php]:
```suggestion
	 * @param OrderService             $order_service    The new order service.
```

**Review by zmaglica — APPROVED** [review]
LGTM! Left one minor comment about typo.

**Comment by alopezari** [comment]
> Since the Woo core issue was fixed in 9.2.0, should we hold off from merging this PR until the min supported WC version for WooPayments is 9.2.0 to be extra safe? Right now it's 7.6.0.

That's a great question, I also reflected on this before creating the PR.

The testing instructions from this PR are designed to use WooCommerce 9.1.4 (the latest version before the Woo Core fix) so that you can check how WooPayments would behave in the trickiest scenario, precisely the one you mentioned.

I've done a quick test were I've removed the WooPayments fix added in [#8805](https://github.com/Automattic/woocommerce-payments/pull/8805) - but with the reverted changes from this PR, always running in the Woo Core version without the fix - and I could check the issue was reproduced, which is expected. However, I couldn't reproduce the issue when using a the WooPayments fix + this revert. I've also checked that the fix from #8805 covers all `init_rest_apis` functions.

This makes me think that we would be safe even in those WooCommerce versions earlier than 9.2.0 (i.e. without the WooCommerce fix). However, **I'd like to encourage everyone reviewing this PR to perform the tests from the testing instructions and even explore other testing scenarios they might come up with, in case I missed anything.**

Thank you @achyuthajoy!

File: includes/admin/class-wc-rest-payments-payment-intents-controller.php (hunk 1 above)
Comment (alopezari) [reply includes/admin/class-wc-rest-payments-payment-intents-controller.php]: Good catch, will fix it. Thanks @zmaglica!

**Comment by alopezari** [comment]
Thanks for reviewing the changes @jessy-p!

> Noting that the original Proof of Concept for which this API was developed pcreKM-1Xt-p2 is not working now with latest WooPayments version. This fix is not the cause of the regression 👍

Thanks for the heads up! Just to confirm, this issue is reproducible in the latest WooPayments version without the changes from this PR, right?

**Review by marcinbot — APPROVED** [review]

File: includes/admin/class-wc-rest-payments-payment-intents-controller.php (hunk 1 above)
Comment (alopezari) [reply includes/admin/class-wc-rest-payments-payment-intents-controller.php]: Fixed in [b644d86](https://github.com/Automattic/woocommerce-payments/pull/10505/commits/b644d86207cb7e69a8dbec90d84e22eeb67fa552).

**Comment by alopezari** [comment]
Hi @achyuthajoy, @jessy-p, @zmaglica, @marcinbot!

Did anyone run through the testing instructions or performed any other testing activity over this PR? I'm planning to merge it but wanted to confirm this first. Thanks!
