### PR TITLE
Fix Dispute Notice for Klarna Inquiry.

### LINKED ISSUE #9918: Review inquiry response flow and adjust so works well for Klarna inquiries, which don't allow a merchant response
Previous title: Merchants may be confused when viewing Klarna Inquiries due to inability to respond 

### Description

Best practice for regular inquiries is for merchant to respond (i.e. challenge or accept). Our flow was designed with this in mind. However, Klarna inquiries cannot be responded to. Stripe ignores evidence submitted for Klarna inquiries. i.e. not supported by Stripe, and likely (@haszari assumes!) not supported in Klarna either. 

The goal of this issue is to tweak/adjust the inquiry flow & UI to work well for Klarna disputes (i.e. customise it for Klarna). This could be achieved by e.g. adjusting wording in a few places, updating docs (etc). 

The ability to submit evidence was removed in #9741 - i.e. the respond button was hidden/removed. 

- #9741

- Merchants may be confused as to why the button to `Submit Evidence` is missing that is available for other disputes/inquiries.

- The `DisputeNotice` component mentions that the inquiry can be challenged. 
Image

The goal of this issue is to ensure that the overall flow for Klarna inquiries works nicely and is clear to merchants (there may be other things we can tweak, alongside the notice wording). See previous PR comments for [discussion](https://github.com/Automattic/woocommerce-payments/pull/9741#issuecomment-2531201682). 

### Testing instructions

* Complete an order simulating a Klarna Inquiry.
  * Using dev-mode, pay for an order using Klarna with email address `customer+disputed-return@email.us`
* View the relevant transaction as the merchant.
* See the `DisputeNotice` that mentions the inquiry can be challenged 
* See that the `Submit Evidence` button is missing

### Dev notes

Source of the notice.
https://github.com/Automattic/woocommerce-payments/blob/07c1a1f97117eae4644a646ba29733acce59239b/client/payment-details/dispute-details/dispute-notice.tsx#L48-L52

### PR DESCRIPTION
**Pull request by jessy-p**
Fixes #9918 

The current dispute notice was common for all inquiries and  mentions that inquiries can be challenged, which is not true for Klarna. See more discussion on the issue. 

#### Changes proposed in this Pull Request

Corrected the dispute notice in case of Klarna inquiry to provide better information to the merchant.
image

#### Testing instructions
 
Klarna inquiries cannot be triggered in the test environment. Make this code modification in your local to test the changes and copy from this PR.
- Trigger a [normal card inquiry](https://docs.stripe.com/testing#disputes) and view the dispute details page.
- Hardcode `klarna` as the `paymentMethod` [here](https://github.com/Automattic/woocommerce-payments/blob/b83c74b05c7ed9cdf4c95b8d1231df7883db62e6/client/payment-details/summary/index.tsx#L643)
```
<DisputeAwaitingResponseDetails
	dispute={ charge.dispute }
	customer={ charge.billing_details }
	chargeCreated={ charge.created }
	orderUrl={ charge.order?.url }
	paymentMethod={
		'klarna'
	}
```

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10540` or branch name `fix/9918-dispute-notice-klarna-inquiry` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9918-dispute-notice-klarna-inquiry) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 38f53d01d1f5a752da43a463d76e907a5d32fe92
- Build time: 2025-03-13 21:08:03 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/payment-details/dispute-details/dispute-notice.tsx [hunk 1]
```diff
@@ -20,11 +21,13 @@ import { isInquiry } from 'wcpay/disputes/utils';
 interface DisputeNoticeProps {
 	dispute: Dispute;
 	isUrgent: boolean;
+	paymentMethod: string | null;
```
Comment (Jinksi) [inline client/payment-details/dispute-details/dispute-notice.tsx:23]: 💭 thought to make types more explicit here: it would be great if this was a union type and accept only strings we've already defined in this type:

https://github.com/Automattic/woocommerce-payments/blob/75c35b249175c99213febd02604cc114cc768742/client/types/payment-methods.d.ts/#L9-L23

```ts
export type PaymentMethod =
	| 'affirm'
	| 'afterpay_clearpay'
	| 'au_becs_debit'
	| 'bancontact'
	| 'card'
	| 'card_present'
	| 'eps'
	| 'klarna'
	| 'grabpay'
	| 'giropay'
	| 'ideal'
	| 'p24'
	| 'sepa_debit'
	| 'sofort';
```

This might mean changing the parent component props interface, so could be out of scope of this PR.

File: client/payment-details/dispute-details/dispute-notice.tsx [hunk 2]
```diff
@@ -70,6 +84,13 @@ const DisputeNotice: React.FC< DisputeNoticeProps > = ( {
 							href={ learnMoreDocsUrl }
 						/>
 					),
+					link: (
```
Comment (Jinksi) [inline client/payment-details/dispute-details/dispute-notice.tsx]: 💭 minor suggestion to clarify the difference with `a` and why it is needed: `inlineLink`?

File: client/payment-details/dispute-details/dispute-notice.tsx [hunk 3]
```diff
@@ -70,6 +84,13 @@ const DisputeNotice: React.FC< DisputeNoticeProps > = ( {
...
+						<Link
+							href={ learnMoreDocsUrl }
+							target="_blank"
+							type="external"
```
Comment (Jinksi) [inline client/payment-details/dispute-details/dispute-notice.tsx]: We can add a `noopener` and `noreferrer` for external links as a security measure. Although modern browsers automatically apply these for `target="_blank" links`, [MDN still recommend it](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#security_and_privacy) and it remains common practice in this codebase.

```suggestion
							type="external"
							rel="noopener noreferrer"
```

**Review by Jinksi — APPROVED** [review]
Nice one @jessy-p 🤝

✅ I've tested this by hardcoding `'klarna'` as the `paymentMethod` prop and see the new notice content.

image

✅ The text is helpful to explain what a Klarna inquiry can mean and what action the merchant might want to take.

✅ The link to public docs correctly takes me to [this page and section on Klarna Inquiries](https://woocommerce.com/document/woopayments/payment-methods/buy-now-pay-later/#klarna-inquiries-returns).

I've left some minor comments for your consideration that are not blocking merge.

**Comment by aheckler** [comment]
@jessy-p Looking at this again, can we tweak the text?

Before:

> Klarna inquiries may simply mean that the customer is trying to return their item(s). You can issue a refund to close it without a dispute fee, or leave it open for 21 days, after which it will become a dispute. Please see this document for more information.

Desired:

> Klarna inquiries may mean that the customer is trying to return their item(s). Please see this document for more information.

**Comment by jessy-p** [comment]
@aheckler 
1. image

OR

2. image

The former is more inline with existing notices
image

File: client/payment-details/dispute-details/dispute-notice.tsx (hunk 2 above)
Comment (jessy-p) [reply client/payment-details/dispute-details/dispute-notice.tsx]: The class on the ExternalLink was causing a newline that I did not need, and I wrongly attributed it to ExternalLink. With the new message and formatting, I've switched back to using the existing `a` and `ExternalLink`

File: client/payment-details/dispute-details/dispute-notice.tsx (hunk 3 above)
Comment (jessy-p) [reply client/payment-details/dispute-details/dispute-notice.tsx]: Fixed automatically when I switched back to `ExternalLink` 👍

**Comment by jessy-p** [comment]
> 1. 
> OR
> 
> 2.

Discussed with @aheckler  and picked 1. It has also simplified the code.

File: client/payment-details/dispute-details/dispute-notice.tsx (hunk 1 above)
Comment (jessy-p) [reply client/payment-details/dispute-details/dispute-notice.tsx:23]: Yes we need to change directly accessing `charge.payment_method_details?.type` over [here](https://github.com/Automattic/woocommerce-payments/blob/b83c74b05c7ed9cdf4c95b8d1231df7883db62e6/client/payment-details/summary/index.tsx#L643) and instead map to PaymentMethod type. So might be better to create a separate issue for this.

File: client/payment-details/dispute-details/dispute-notice.tsx [hunk 4]
```diff
@@ -52,6 +54,16 @@ const DisputeNotice: React.FC< DisputeNoticeProps > = ( {
 		);
 		learnMoreDocsUrl =
 			'https://woocommerce.com/document/woopayments/fraud-and-disputes/managing-disputes/#inquiries';
+
+		if ( paymentMethod === 'klarna' ) {
+			noticeText = __(
+				'Klarna inquiries may mean that the customer is trying to return their item(s). ' +
+					'<a>Please see this document for more information</a>',
```
Comment (Jinksi) [inline client/payment-details/dispute-details/dispute-notice.tsx:61]: I've made a tiny change, removed the `.` at the end of the link, to make it consistent with other dispute notices.

Update after 28129244dd5e6403f9601ff16ca3c2fd1bb656b6:

image

Other dispute notices:


image


image

Comment (jessy-p) [reply client/payment-details/dispute-details/dispute-notice.tsx:61]: Thank you!
