### PR TITLE
fix: multi-currency confirmation modal ui

### LINKED ISSUE #8206: Remove currency tooltip layout is broken
### Describe the bug

When removing a currency from one's store, a tooltip appears warning store owners that doing so will disable certain payment methods that require this currency to be present. The layout of this tooltip looks very messy and is inconsistent with other tooltips presented in WooPayments settings.

Broken layout on remove currency tooltip
_Uh oh, what happened here_

Note that in the above image the padding on the header is missing, padding on the body looks inadequate, and the padding between payment method names and their icons is also missing. For comparison, here is another tooltip that appears when removing payment methods from WooPayment settings: notice how much nicer it looks. 

Nicer tooltip when removing payment methods
_That's more like it_

Here is a comparison of the inconsistent padding between these tooltips.

Padding on acceptable tooltip
_Padding on header and body is 24px_

Padding on inacceptable tooltip
_Padding on header is 0px, padding on body is 16px_

It would be great if we could make the padding and layout on the latter tooltip neater and more consistent with its former relative. Here are a few incongruencies that I noticed.

- Header/body padding is different.
- Header and content font-size is different.
- Payment method name is not weighted bold.
- Currency name is not weighted bold in the footer, whereas it is weighted bold near the head of the content.
- Main currency icon is smaller (this might be fine as is, since there is more content in the body in the currency tooltip).

Here is a quick knock-up I made, which I think would already be a great improvement.

Fixing the currency tooltip
_A small step in the right direction_

CC @pierorocca & @nikkivias for feedback on the above suggested improvements. Note that I also removed the outline around the payment method icons, which I think looks a little neater and is more consistent with how these icons are displayed at checkout where the icon is also paired with its title-text label. 

### To Reproduce

1. Ensure you have multiple currencies enabled, as well as payment methods that depend on them.
2. Navigate to the Multi-currency tab (**WooCommerce > Settings > Multi-currency**).
3. Remove a currency upon which an enabled payment method depends.
4. Notice the aforementioned hideous tooltip.
5. Cringe internally.

### Actual behavior

A wild and wonky tooltip appears.

### Screenshots

See above

### Expected behavior

A nice and neat tooltip should appear with consistent styling to other related tooltips that we present to users.

### Desktop (please complete the following information):

* OS: [e.g. iOS] Any
* Browser [e.g. chrome, safari]: Any
* Version [e.g. 22]: Latest

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6] Any
* OS: [e.g. iOS8.1] Any
* Browser [e.g. stock browser, safari]: Any
* Version [e.g. 22]: Latest

### Additional context

N/A

### PR DESCRIPTION
**Pull request by frosso**
Fixes https://github.com/Automattic/woocommerce-payments/issues/8206

#### Changes proposed in this Pull Request

Fixing the UI/alignment of some of the elements for the confirmation modal displayed in the multi-currency settings.
Aligning with

#### Testing instructions

- Go to the multi-currency settings at http://wcpay.test/wp-admin/admin.php?page=wc-settings&tab=wcpay_multi_currency
- Add a currency, e.g.: Euro (if you don't have existing ones)
- Remove the currency via the trash icon
- The modal should appear
- The UI of the modal should be more in line with the one of existing modals

Before:
Screenshot 2024-02-16 at 4 24 19 PM

After:
Screenshot 2024-02-16 at 4 19 25 PM

Other examples:
Screenshot 2024-02-16 at 4 19 35 PM
Screenshot 2024-02-16 at 4 19 44 PM

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: client/multi-currency/multi-currency-settings/enabled-currencies-list/delete-button.js [hunk 1]
```diff
@@ -108,11 +99,10 @@ const DeleteButton = ( { code, label, symbol, onClick, className } ) => {
 					</p>
 					<ul>
 						{ dependentPaymentMethods.map( ( paymentMethod ) => (
-							<li key={ 'pm-icon-wrapper-' + paymentMethod }>
+							<li key={ paymentMethod }>
```
Comment (frosso) [inline client/multi-currency/multi-currency-settings/enabled-currencies-list/delete-button.js:101]: The value of the key doesn't matter

File: client/multi-currency/multi-currency-settings/enabled-currencies-list/style.scss [hunk 2]
```diff
@@ -196,21 +196,6 @@
 
 .wcpay-confirmation-modal.wcpay-confirmation-modal.enabled-currency-delete-modal {
 	max-width: 495px;
-	.components-modal__header {
```
Comment (frosso) [inline client/multi-currency/multi-currency-settings/enabled-currencies-list/style.scss:199]: Removed these styles, which are not necessary anymore and deviate from the other modals/dialogs.

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8217` or branch name `fix/multi-currency-confirmation-modal-ui` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/multi-currency-confirmation-modal-ui) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 5ff5a3c3cf9ad36f82cfc28a499f86ceadac0c1e
- Build time: 2024-02-16 15:39:21 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by timur27 — APPROVED** [review]
Looks good and tests well 👍 Thanks Francesco, let's merge it.
