### PR TITLE
Ensure order attribution inputs are not removed when shortcode cart is updated

### LINKED ISSUE #9001: Tokenized PRB - Unknown origin field for orders placed after shortcode cart update
### Describe the bug

For PRB orders placed via the cart page after the cart totals have changed, the Origin displayed in the list of orders in the admin is `unknown`. The origin is collected from the `wc-order-attribution-inputs` element on the page. While this element is present and populated on the initial page load, it's currently situated in a location that is removed from the page when the cart totals update.

The element is added [here](https://github.com/Automattic/woocommerce-payments/blob/aac2f270fa282260326e5dc0677c80fed23353b3/includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php#L154), inside the `display_express_checkout_buttons()` function. This ensures that the element is present everywhere the PRB is displayed. The problem is that, on the cart page, the PRB is hooked in via [the `woocommerce_proceed_to_checkout` hook](https://github.com/Automattic/woocommerce-payments/blob/aac2f270fa282260326e5dc0677c80fed23353b3/includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php#L103) and everything in that location is removed from the page when the shortcode cart is updated. When the `wc-order-attribution-inputs` element is added back, it's fields no longer contain any data.

Using a different hook for the `wc-order-attribution-inputs` element on the cart page should take care of this.

### To Reproduce

1. Enable the "Enable Cart-Token implementation for PRBs" flag in your dev tools
2. Add a product to the cart
3. Visit the cart page
4. Update the item quantity and click update cart
5. Place an order via the PRB
6. Navigate to WooCommerce > Orders and notice that the Origin field is `unknown` for that order.

### Actual behavior

The origin is unknown for orders placed via the PRB after cart totals have been updated.

### Screenshots

See the end of the video [here](https://github.com/Automattic/woocommerce-payments/pull/8891#pullrequestreview-2124397374).

### Expected behavior

Orders placed via the PRB on the cart page should display the correct origin.

### Additional context

https://github.com/Automattic/woocommerce-payments/pull/8891#pullrequestreview-2124397374

### PR DESCRIPTION
**Pull request by mdmoore**
Fixes #9001 

#### Changes proposed in this Pull Request
This ensures the `wc-order-attribution-inputs` element isn't removed from the page when the shortcode cart is updated. It's this element that provides the data to populate the Origin field inside WooCommerce orders. This change will solve the problem of the Origin being reported as Unknown on orders placed after the cart has been refreshed.

#### Testing instructions

1. Enable the "Enable Cart-Token implementation for PRBs" flag in your dev tools
2. Add a product to the cart
3. Visit the cart page
4. Update the item quantity and click update cart
5. Place an order via the PRB
6. Navigate to WooCommerce > Orders and check that the Origin field is not `unknown`

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9038` or branch name `9001-tokenized-prb-order-origin` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=9001-tokenized-prb-order-origin) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 7069fc0b6e408367b0a347d9aa56e4bc66fe9edd
- Build time: 2024-07-09 16:11:21 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php [hunk 1]
```diff
@@ -103,6 +124,11 @@ public function init() {
 			add_action( 'woocommerce_proceed_to_checkout', [ $this, 'display_express_checkout_buttons' ], 21 );
 			add_action( 'woocommerce_checkout_before_customer_details', [ $this, 'display_express_checkout_buttons' ], 1 );
 			add_action( 'woocommerce_pay_order_before_payment', [ $this, 'display_express_checkout_buttons' ], 1 );
+
+			add_action( 'woocommerce_after_add_to_cart_form', [ $this, 'add_order_attribution_inputs' ], 1 );
+			add_action( 'woocommerce_after_cart', [ $this, 'add_order_attribution_inputs' ], 1 );
+			add_action( 'woocommerce_checkout_before_customer_details', [ $this, 'add_order_attribution_inputs' ], 1 );
+			add_action( 'woocommerce_pay_order_before_payment', [ $this, 'add_order_attribution_inputs' ], 1 );
```
Comment (FangedParakeet) [inline includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php]: It appears that we have added hooks twice in this `init` function for `woocommerce_after_add_to_cart_form`, `woocommerce_checkout_before_customer_details`, and `woocommerce_pay_order_before_payment`. Can we combine any of these into a single action, instead of attaching separate hooks? 

If the former is not preferred or possible, it appears that `add_order_attribution_inputs()` is dependent on `display_express_checkout_buttons()` having been fired first, otherwise `should_show_woopay`, `should_show_payment_request`, and `should_show_express_checkout_button` will not yet have been defined. Should we change the priority on the `add_order_attribution_inputs` actions to ensure that this is fired after `display_express_checkout_buttons` or are we able to set those three variables inside this class's constructor? 🤔

Comment (mdmoore) [reply includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php]: I was originally thinking the `woocommerce_after_cart` action fired before the `woocommerce_proceeed_to_checkout` action but it doesn't. So there's no need for duplicating the hooks since `woocommerce_after_cart` can be called within `display_express_checkout_buttons`. Much cleaner solution in [a022d92](https://github.com/Automattic/woocommerce-payments/pull/9038/commits/a022d92a80d764ad12021ec057e7c18292fd930e).

File: includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php [hunk 2]
```diff
@@ -150,14 +150,31 @@ public function display_express_checkout_buttons() {
...
 				$this->payment_request_button_handler->display_payment_request_button_html();
 			}
+
+			if ( ! is_cart() ) {
+				?>
+				<wc-order-attribution-inputs id="wcpay-express-checkout__order-attribution-inputs"></wc-order-attribution-inputs>
+				<?php
+			} else {
+				add_action( 'woocommerce_after_cart', [ $this, 'add_order_attribution_inputs' ], 1 );
+			}
```
Comment (FangedParakeet) [inline includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php]:
```suggestion
			if ( is_cart() ) {
				add_action( 'woocommerce_after_cart', [ $this, 'add_order_attribution_inputs' ], 1 );
			} else {
				?>
				<wc-order-attribution-inputs id="wcpay-express-checkout__order-attribution-inputs"></wc-order-attribution-inputs>
				<?php
			}
```

This is a very pedantic suggestion, so feel free to ignore it 😅, but I feel like this is a bit clearer.

Also, while I'm at it with the pedantic suggestions, could we not do something like the below to avoid one line of duplication? 🤔 

 ```suggestion
			if ( is_cart() ) {
				add_action( 'woocommerce_after_cart', [ $this, 'add_order_attribution_inputs' ], 1 );
			} else {
				$this->add_order_attribution_inputs();
			}
```

**Review by FangedParakeet — COMMENTED** [review]
Changes here look really straight-forward and from the PDP, shortcode cart, and shortcode checkout I was able to get the correct Origin on all of my orders. 🎉 

However, from both the blocks cart and blocks checkout I was still able to produce an "Unknown" origin on my completed orders. 😢 Is that expected, @mdmoore, or would you consider this outside the scope of this issue, since it will probably require a separate fix? 🤔

File: includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php (hunk 2 above)
Comment (mdmoore) [reply includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php]: >However, from both the blocks cart and blocks checkout I was still able to produce an "Unknown" origin on my completed orders. 😢 Is that expected, @mdmoore, or would you consider this outside the scope of this issue, since it will probably require a separate fix? 🤔

Just noting that we discussed this earlier and the [PRB tokenized cart on block-based cart and checkout](https://github.com/Automattic/woocommerce-payments/issues/8527) hasn't been implemented yet. If order attributes  isn't covered with that implementation, we could create another issue to handle it.

I like the suggestions above. Changes in [7069fc0](https://github.com/Automattic/woocommerce-payments/pull/9038/commits/7069fc0b6e408367b0a347d9aa56e4bc66fe9edd)

**Review by FangedParakeet — APPROVED** [review]
Thanks for the minor changes! Code LGTM and is working as expected. :shipit:
