### PR TITLE
Filter out error messages that shouldn't be displayed to customers

### LINKED ISSUE #470: Scope merchant-facing payment errors to admin context
In at least some cases, errors pertaining and addressed to merchants are being shown to customers.

Currently reproducible by attempting to make a payment on an unverified account. (Test cases listed [here](https://stripe.com/docs/connect/testing).) The customer is shown an error: "Your account cannot currently make charges. _[…]_"

In this case, we may want to attempt to identify errors as merchant account-related, and log or otherwise present the error in the dashboard, but show a generic error on the front-end.

Related to https://github.com/Automattic/woocommerce-payments/issues/469

### PR DESCRIPTION
**Pull request by ricardo**
Fixes #470

I think this change is positive as it doesn't display errors that don't pertain to customers, but at the same time it might be harder for store admins to debug issues, as they will need to rely only on logs and order notes, when these apply.

#### Changes proposed in this Pull Request

Stripe recommends only displaying card errors to customers - [Ref](https://stripe.com/docs/api/errors#errors-message).

In this PR, we're adding the `type` attribute that Stripe provides to the `API_Exception` class, so that we can filter out other API errors that don't pertain to customers.

#### Testing instructions

* Try paying with a [test card](https://stripe.com/docs/testing) which returns a customer-facing error (e.g `4000000000000069`) and notice a "card expired" error is displayed.
* To test a Stripe API (merchant-facing) error, try breaking the request from the code (e.g changing the currency to an invalid one e.g `xyz` in `process_payment_for_order` in `class-wc-payment-gateway-wcpay.php` and notice a generic error message is displayed. Try doing the same in trunk and notice a Stripe error about invalid currency is displayed.
* The above should also work for cards added from the my account page, where there's a WC notice in case any errors are thrown.

#### Caveats
* For the non-UPE block checkout, this doesn't apply as we're currently throwing generic error messages at all times due to #2803.
* For UPE payments, the same behavior should apply, but it won't add an order note nor fail the order due to #2702.
* For other payment methods like SEPA, SOFORT and Giropay, we're using the same utility function, but user-facing errors will never be displayed from Stripe directly to users due to the nature of these payment methods (ref p1629994061002400-slack-C9976E5MJ).

-------------------

- [x] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by ricardo** [comment]
It looks like the Stripe errors are not localized, so they probably shouldn't be displayed directly to customers.

**Comment by reykjalin** [comment]
@ricardo Aren't they localized through the locale option passed to the [Stripe Element](https://stripe.com/docs/js/elements_object/create)? It's really surprising to me that they wouldn't be localized if we do that 🤔

File: includes/class-wc-payments-utils.php [hunk 1]
```diff
@@ -477,4 +479,31 @@ public static function convert_to_stripe_locale( string $locale ): string {
...
+	 * @return string
+	 */
+	public static function get_filtered_error_message( Exception $e ) {
+		$error_message = method_exists( $e, 'getLocalizedMessage' ) ? $e->getLocalizedMessage() : $e->getMessage();
+
+		// These notices can be shown when placing an order or adding a new payment method, so we aim for
+		// more generic messages instead of specific order/payment messages when the API Exception is redacted.
+		if ( $e instanceof Connection_Exception ) {
+			$error_message = __( 'There was an error while processing this request. If you continue to see this notice, please contact the admin.', 'woocommerce-payments' );
+		} elseif ( $e instanceof API_Exception && 'wcpay_bad_request' === $e->get_error_code() ) {
```
Comment (dechov) [inline includes/class-wc-payments-utils.php:501]: Do you think we should filter other (or all) WCPay server error codes too? The only example I have in mind is if the account (hypothetically) isn't found when calling `/intentions`.

**Review by dechov — COMMENTED** [review]
Looks great – need to do some testing but left some initial comments.

File: includes/payment-methods/class-upe-payment-gateway.php [hunk 2]
```diff
@@ -776,7 +776,7 @@ public function save_upe_appearance_ajax() {
 			wp_send_json_error(
 				[
 					'error' => [
-						'message' => $e->getMessage(),
+						'message' => WC_Payments_Utils::get_filtered_error_message( $e ),
```
[the remark this answers is not in the document]
Comment (dechov) [reply includes/payment-methods/class-upe-payment-gateway.php:779]: Ah, nevermind – [it isn't](https://github.com/Automattic/woocommerce-payments/blob/4e430435919b5bd307b15810be228385fe0b6f0e/client/checkout/classic/upe.js#L282).

File: includes/class-wc-payments-utils.php (hunk 1 above)
Comment (ricardo) [reply includes/class-wc-payments-utils.php:501]: > Do you think we should filter other (or all) WCPay server error codes too?

@dechov I quickly looked into the `/intentions` request and it seems like it should throw an `API_Exception`, which should be filtered out by [this line](https://github.com/Automattic/woocommerce-payments/pull/2502/files#diff-fdf97bb0bd6043ee97d2ab4f058059c59d2b7173a076398fe8441824dc7b5e35R503).

But I see there are a few other API Exceptions that wouldn't be filtered out in `class-wc-payments-api-client.php`. Perhaps we could filter all API Exceptions and only display the `card_error` ones?

File: includes/exceptions/class-api-exception.php [hunk 3]
```diff
@@ -43,4 +52,13 @@ public function __construct( $message, $error_code, $http_code, $code = 0, $prev
 	public function get_http_code() {
 		return $this->http_code;
 	}
+
+	/**
+	 * Returns the error type attribute from the server.
+	 *
+	 * @return string Error type, for example 'api_error' or 'card_error'.
```
[the remark this answers is not in the document]
Comment (ricardo) [reply includes/exceptions/class-api-exception.php]: Nice catch! Fixed in feea09e856e5155b8cd4233f5b71437766554ca7

File: includes/class-wc-payments-utils.php (hunk 1 above)
Comment (dechov) [reply includes/class-wc-payments-utils.php:501]: That line only filters out exceptions that have a `type`, which (correct me if I'm wrong) is specific to Stripe's error responses and which we still aren't adding to the exception (i.e. leaving it `null`) in most cases.

I'd be fine with leaving it for a later PR or issue if you'd prefer, since the errors originating from WCPay server aren't specifically documented as customer-facing (if ever) or not, like the ones originating from Stripe are, so it might need more consideration.

Comment (ricardo) [reply includes/class-wc-payments-utils.php:501]: > That line only filters out exceptions that have a `type`

That's correct.

Not all WCPay server errors would be filtered out. For that I think we would need to scope those errors from the server, which would be easier to do from a server PR.

@dechov what about creating a follow up issue for #470 noting that we need to check all custom errors thrown by the server and then filter out the ones that are not supposed to be displayed to customers? This might require a server and another client PR.

Comment (dechov) [reply includes/class-wc-payments-utils.php:501]: Sounds fine to me – I guess technically we could just add `type` to the server errors.

Comment (ricardo) [reply includes/class-wc-payments-utils.php:501]: 1174-gh-Automattic/woocommerce-payments-server

I created a server issue as a spike to first check if there are any cases where we'd like to filter out error messages, and then propose a way to differentiate these errors. Adding a `type` is a good idea, I added to the issue.

**Review by dechov — APPROVED** [review]
Code changes look good and test well with provided instructions 👍 

This will report errors originating from Stripe in a way that's consistent with their intended audience (according to Stripe's docs) 😌
