### PR TITLE
Catch error when validating checkout fields

### LINKED ISSUE #6230: Payment method error when completing checkout with missing payment information
### Describe the bug

With the split-UPE deferred intent enabled, if we hit "Place order" to complete a checkout while a required payment field is missing, the checkout fields will rightly display an error state, but an additional error message will be added to the top of the page stating, "paymentMethodObject.paymentMethod is undefined." We would like to remove this second error. 

This is mentioned originally over [here](https://github.com/Automattic/woocommerce-payments/pull/5869#discussion_r1185502823), but this essentially occurs because while completing a checkout if [the `validateElements` function](https://github.com/Automattic/woocommerce-payments/blob/poc/deferred-upe-intent-creation/client/checkout/classic/upe-deferred-intent-creation/stripe-checkout.js#L204) uncovers an error, we do not immediately exit from the `checkout()` function, so `createStripePaymentMethod()` will proceed and fail, because the payment information is not valid to create a new payment method. 

We need to restructure the flow of logic here, so that we exit this function early, if Stripe elements relates an error in the submitted payment information.

### To Reproduce

1. Ensure "Enable Split UPE checkout with deferred intent creation" is checked in your WCPay Dev Tools and ensure WooPay is deselected in your WCPay settings, so that the CC gateway uses the UPE instead of the legacy card element.
2. Add an item to cart and proceed to shortcode checkout.
3. This is easiest to do with the CC gateway, since with the other additional LPMs that have payment information options, this field is preloaded with something, so I'm not sure how to produce an error state using them. However, with the credit card gateway, you need only to select "Use a new payment method", leave all the fields blank, and then hit "Place order".
4. Notice that the empty payment fields light up in red--which is what we want--but the page scrolls up and another cryptic message is left at the top of the page declaring, "paymentMethodObject.paymentMethod is undefined." This is not what we want.

### Actual behavior

With the split-UPE deferred intent enabled, if we hit "Place order" to complete a checkout while a required payment field is missing, the checkout fields will rightly display an error state, but an additional error message will be added to the top of the page stating, "paymentMethodObject.paymentMethod is undefined." 

### Screenshots

Screenshot displaying error states
_Top error state should not appear, bottom one should remain_

### Expected behavior

With the split-UPE deferred intent enabled, if we hit "Place order" to complete a checkout while a required payment field is missing, the checkout fields will rightly display an error state, and that's all.

### Desktop (please complete the following information):

Yes.

### Smartphone (please complete the following information):

Yes.

### Additional context

https://github.com/Automattic/woocommerce-payments/pull/5869#discussion_r1185502823

### PR DESCRIPTION
**Pull request by mdmoore**
Fixes #6230 

#### Changes proposed in this Pull Request

When checking out with deferred intent UPE, credit card field validation occurs upon form submission. If an error occurs during validation, we don't exit from the `checkout()` function and `createStripePaymentMethod()` still runs and fails. This PR catches errors that occur during validation and exits the `checkout()` function, preventing `createStripePaymentMethod()` from running, ultimately preventing the cryptic error notice and message described in #6230.

#### Testing instructions

1. Ensure "Enable Split UPE checkout with deferred intent creation" is checked in your WCPay Dev Tools and ensure WooPay is deselected in your WCPay settings, so that the CC gateway uses the UPE instead of the legacy card element.
2. Add an item to cart and proceed to shortcode checkout.
3. With the credit card gateway, select "Use a new payment method", leave all the fields blank, and then hit "Place order".
4. Notice that the empty payment fields light up in red--which is what we want--but the page no longer scrolls up to reveal another cryptic message at the top of the page declaring, "paymentMethodObject.paymentMethod is undefined." or "Cannot read properties of undefined (reading 'id')".

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6262` or branch name `fix/6230-prevent-redundant-checkout-error` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6230-prevent-redundant-checkout-error) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 56ffd72fbf53dab5d87a1c0bac48f4e203a1c4f3
- Build time: 2023-05-15 23:37:14 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/checkout/classic/upe-deferred-intent-creation/stripe-checkout.js [hunk 1]
```diff
@@ -201,21 +203,29 @@ export const checkout = ( api, jQueryForm, paymentMethodType ) => {
...
+					hasCheckoutCompleted = true;
+					submitForm( jQueryForm );
+				} )
+				.catch( ( error ) => {
+					jQueryForm.removeClass( 'processing' ).unblock();
+					showErrorCheckout( error.message );
+				} );
+		} catch ( err ) {
+			return false;
+		}
```
Comment (FangedParakeet) [inline client/checkout/classic/upe-deferred-intent-creation/stripe-checkout.js]:
```suggestion
		try {
			await validateElements( elements, jQueryForm );

			const paymentMethodObject = await createStripePaymentMethod( api, elements );

			appendFingerprintInputToForm( jQueryForm, fingerprint );
			appendPaymentMethodIdToForm(
				jQueryForm,
				paymentMethodObject.paymentMethod.id
			);
			hasCheckoutCompleted = true;
			submitForm( jQueryForm );
		} catch ( err ) {
			jQueryForm.removeClass( 'processing' ).unblock();
			showErrorCheckout( error.message );
		}
```
I feel like we could consolidate these two `catch` blocks into one, since they both basically do the same thing. If we remove the `showErrorCheckout` call from `validateElements`, we can use this `catch` block to perform that action, since we rethrow the `Error` anyways. This seems a little cleaner to me, but let me know if you think otherwise!

Also, I think the `return false` in this `catch` block is redundant, because the function will always return `false` anyways.

Comment (mdmoore) [reply client/checkout/classic/upe-deferred-intent-creation/stripe-checkout.js]: Ah, yep this is cleaner indeed. Thanks for the suggestion! Done in https://github.com/Automattic/woocommerce-payments/pull/6262/commits/f5b121e0fe494880dd81f995b31a00ceded88b36.

File: client/checkout/classic/upe-deferred-intent-creation/stripe-checkout.js [hunk 2]
```diff
@@ -64,12 +64,13 @@ function blockUI( jQueryForm ) {
  *
  * @param {Object} elements The Stripe elements object to be validated.
  * @param {Object} jQueryForm The jQuery object for the form being validated.
+ * @return {Promise} Promise for the checkout submission.
  */
 function validateElements( elements, jQueryForm ) {
-	elements.submit().then( ( result ) => {
+	return elements.submit().then( ( result ) => {
 		if ( result.error ) {
 			jQueryForm.removeClass( 'processing' ).unblock();
```
Comment (FangedParakeet) [inline client/checkout/classic/upe-deferred-intent-creation/stripe-checkout.js]:
```suggestion
```
Think we can remove this too, now that it'll be handled in the other `catch` block. 👍

Comment (mdmoore) [reply client/checkout/classic/upe-deferred-intent-creation/stripe-checkout.js]: I missed that! Thanks for catching it. Removed in https://github.com/Automattic/woocommerce-payments/pull/6262/commits/6151283ef672c351509da085b0551b17e485a6cb

**Review by FangedParakeet — APPROVED** [review]
LGTM! Cheers for making all my minute amends. 🙌 🚢
