### PR TITLE
Express checkout on the Pay for Order page

### LINKED ISSUE #4220: Express Checkout Buttons Missing on Pay for Order screen
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

When following the `Customer payment page` link from an unpaid order to the `Pay for order` checkout page, no Express Checkout buttons are offered by either Stripe or WooCommerce Payments. 

This is true for Google Pay and Apple Pay. 

However, they do appear on the normal checkout page with the same product. 

### Expected behavior

Because they appear on the normal checkout page, I would expect to see the Express Checkout buttons on the Pay for Order checkout page as well. 

### Actual behavior

The buttons do not appear. 

### Steps to reproduce

1. Activate Express Checkouts for either Stripe or WooCommerce Payments
2. Add a product to the cart, proceed to checkout and see Express Checkout buttons on the checkout page. 
3. Next, create a manual order
4. Copy the `Customer Payment Page` link from the order. 
5. Open a new Private/Incognito tab and visit the link
6. See the `Pay for Order` page, but without the Express Checkout buttons. 

<details>
<summary>
Tap for ### WordPress Environment
</summary>
`
### WordPress Environment ###

WordPress address (URL): https://woo.tst
Site address (URL): https://woo.tst
WC Version: 6.3.1
REST API Version: ✔ 6.3.1
WC Blocks Version: ✔ 6.9.0
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.2.1
Log Directory Writable: ✔
WP Version: 5.9.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.28
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.82.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.34-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.3.1
WC Database Prefix: wp_
Total Database Size: 14.75MB
Database Data Size: 9.87MB
Database Index Size: 4.88MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.39MB + Index: 0.44MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.20MB + Index: 0.14MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gp_glossaries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gp_glossary_entries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gp_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gp_originals: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gp_permissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gp_projects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gp_translations: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_gp_translation_sets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.03MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 1.48MB + Index: 0.80MB + Engine InnoDB
wp_posts: Data: 0.22MB + Index: 0.09MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoco_order_errors: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 126
aw_workflow: 3
event_ticket: 4
follow_up_email: 2
nav_menu_item: 8
oembed_cache: 4
page: 19
post: 2
product: 65
product_variation: 35
revision: 41
shop_coupon: 4
shop_order: 95
shop_subscription: 6
wc_booking: 11
wc_order_status: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Jetpack: by Automattic – 10.8-a.9.2
WooCommerce Stripe Gateway: by WooCommerce – 6.3.0
WooCommerce Payments: by Automattic – 3.9.0
WooCommerce PayPal Payments: by WooCommerce – 1.7.0
WooCommerce: by Automattic – 6.3.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.0.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: CA
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: –
Webhook status: –
Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: ✔
Used PayPal Checkout plugin: ✔

### WooCommerce Payments ###

Version: 3.9.0
Connected to WPCOM: Yes
Blog ID: 167752461
Account ID: acct_1Jysip2H9KWIXo0t

### Action Scheduler ###

Complete: 604
Oldest: 2022-03-23 03:04:03 -0400
Newest: 2022-03-29 03:12:11 -0400

Pending: 9
Oldest: 2022-03-29 03:20:47 -0400
Newest: 2022-04-09 05:56:03 -0400

Failed: 2
Oldest: 2020-03-26 01:54:28 -0400
Newest: 2021-11-11 09:16:08 -0500

### Status report information ###

Generated at: 2022-03-29 03:19:54 -04:00
`
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by RadoslavGeorgiev**
Fixes #4220 

#### Changes proposed in this Pull Request

> **Note:**
> WooCommerce 6.6.0 is required to test this PR, as there was no hook to display the button in earlier versions.
> Either use an up-to-date core version, or check out the code from [this PR](https://github.com/woocommerce/woocommerce/pull/33078).

> **Note 2:**
> I could not get ApplePay to work on my machine on a local, tunneled, or sandbox test site. I assume the Payment Request API should already cover everything, as it works in Chrome.

Adds support for payment request buttons (Apple Pay and Google Pay) to the Pay for Order page.

After the initial exploration, it turned out that this does not require a temporary cart and/or checkout object, as we expected. Although the payment request process allows shipping and billing fields to be edited, as we do during standard checkout, we decided to disable those edits when paying for orders. This behavior follows the standard Pay for Order flow, where the only available action is to just pay for the order.

Once the decision was made to only allow payments through the payment request process, the rest of the code got relatively simplified:

- JS changes mostly include some refactors in order to use most of the same functions, which were used on checkout. The only notable change here is [how the process is initialized on the Pay for Order page](https://github.com/Automattic/woocommerce-payments/pull/4264/files#diff-3b09c95dc3e8c6f0dd75f523bc8fccba95d8308a909d8641c5248c92134b2cacR468-R482).
- On the PHP side, all changes are contained within `includes/class-wc-payments-payment-request-button-handler.php`:
    - [`display_pay_for_order_page_html()`](https://github.com/Automattic/woocommerce-payments/pull/4264/files#diff-01da8e7c10c31988f0205e9327a25bcaaf64e6485c6d391912b68dc66d808353R309) loads all line items and totals for the payment request. Here everything is added as a simple line item, as none of those values would be dynamic once the dialog is loaded.
    - [`ajax_pay_for_order()`](https://github.com/Automattic/woocommerce-payments/pull/4264/files#diff-01da8e7c10c31988f0205e9327a25bcaaf64e6485c6d391912b68dc66d808353R1124) handles the payment. The code here is adapted for payment request AJAX calls, but follows the core code for the pay for order page. In the end, with the right POST fields, we just need to use `$gateway->process_payment()` only with the order ID as a parameter.

Here is how the page should look like (note the numbers/total):

image

And the same data in the dialog:

image

#### Testing instructions

Create two orders:

1. Complete checkout with an order, open it in `wp-admin`, and change the status to `pending` (Pending payment).
2. Manually go to `wp-admin` / WooCommerce / Orders / Add New and create an order, assigning it to a customer. There you can add all sorts of product, taxes, fees, shipping, etc. Some of those fields would be harder/more time consuming to populate if you were to use settings or extensions.

With the same user logged in, and in a browser which supports express checkout (Chrome/Safari):

1. Open My Account > Orders > Click the `Pay` button.
2. Observe the displayed line items and totals.
3. Click the payment request button.
4. Verify that the dialog contains the same values as the ones on the page.
5. Complete the payment, and make sure that the order is now `processing`, and has all the necessary notes.

I'd also recommend simulating errors in the back-end, in order to make sure that they are properly reaching the front-end.

### CODE REVIEW

**Comment by RadoslavGeorgiev** [comment]
Added [a commit](https://github.com/Automattic/woocommerce-payments/pull/4264/commits/e8a546c526e3c96fc3e2fced7be60490dc5915e8), which changes Shipping to be a simple line item instead of an actual shipping option:

shipping-item

**Comment by jessy-p** [comment]
Followed the testing instructions and works fine.

**Comment by RadoslavGeorgiev** [comment]
@jessy-p is this an approval?

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 1]
```diff
@@ -369,7 +436,7 @@ public function get_normalized_postal_code( $postcode, $country ) {
 	 *
 	 * @return  void
 	 */
-	public function add_order_meta( $order_id, $posted_data ) {
+	public function add_order_meta( $order_id, $posted_data = null ) {
```
Comment (zmaglica) [inline includes/class-wc-payments-payment-request-button-handler.php:439]: Can we delete this `$posted_data`?

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 2]
```diff
@@ -1038,6 +1116,66 @@ public function ajax_add_to_cart() {
...
+			// Set up an environment, similar to core checkout.
+			wc_maybe_define_constant( 'WOOCOMMERCE_CHECKOUT', true );
+			wc_set_time_limit( 0 );
+
+			// Load the order.
+			$order_id = intval( $_POST['order'] );
+			$this->add_order_meta( $order_id );
+			$order = wc_get_order( $order_id );
+
+			if ( ! is_a( $order, WC_Order::class ) ) {
```
Comment (zmaglica) [inline includes/class-wc-payments-payment-request-button-handler.php:1146]: Maybe we can move this check before `$this->add_order_meta( $order_id );` function to prevent strange behaviors in the codebase

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 3]
```diff
@@ -1038,6 +1116,66 @@ public function ajax_add_to_cart() {
...
+				throw new Exception( __( 'Invalid order!', 'woocommerce-payments' ) );
+			}
+
+			if ( ! $order->needs_payment() ) {
+				throw new Exception( __( 'This order does not require payment!', 'woocommerce-payments' ) );
```
Comment (zmaglica) [inline includes/class-wc-payments-payment-request-button-handler.php:1151]: Same as previous comment.

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 4]
```diff
@@ -1038,6 +1116,66 @@ public function ajax_add_to_cart() {
...
 
+	/**
+	 * Handles payment requests on the Pay for Order page.
+	 *
+	 * @throws Exception All exceptions are handled within the method.
+	 */
+	public function ajax_pay_for_order() {
+		check_ajax_referer( 'pay_for_order' );
+
+		if (
```
[the remark this answers is not in the document]
Comment (RadoslavGeorgiev) [reply includes/class-wc-payments-payment-request-button-handler.php:1134]: > I assume that we should return an error response if this statement is false. Am I correct?
My assumption was that if the request does not contain the necessary fields (no verification if anything exists at this point), it probably doesn't originate from the proper place and the response format does not really matter. Anyhow, there is a properly formatted JSON along an error HTTP code.

> Also, WordPress request validation can be used to perform validation instead of using it like this. It will be more clear IMHO.
What do you mean by WordPress request validation? [Core docs](https://developer.wordpress.org/plugins/security/data-validation/#built-in-php-functions) describe that for basic stuff like this, we should use PHP functions.

> Moreover, $_POST['payment_method'] and $_POST['wcpay-payment-method']is sent via POST, but it is never used in this function. Is there a reason behind it?

`payment_method` is used here to verify that this is a WCPay request. `wcpay-payment-method` is one of the few request parameters here, and is later used by the gateway's `process_payment` method.

File: includes/class-wc-payments-payment-request-button-handler.php (hunk 1 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-payments-payment-request-button-handler.php]: Done in https://github.com/Automattic/woocommerce-payments/pull/4264/commits/4ccb5ccfaaa505de2aa0eac8dccaa8e0fe2fa312

File: includes/class-wc-payments-payment-request-button-handler.php (hunk 2 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-payments-payment-request-button-handler.php:1157]: Done in https://github.com/Automattic/woocommerce-payments/pull/4264/commits/54aadd28ed5b128424e317aa65a5a0e4c5169c9b

File: includes/class-wc-payments-payment-request-button-handler.php (hunk 3 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-payments-payment-request-button-handler.php:1162]: Done in https://github.com/Automattic/woocommerce-payments/pull/4264/commits/54aadd28ed5b128424e317aa65a5a0e4c5169c9b

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 5]
```diff
@@ -1038,6 +1116,66 @@ public function ajax_add_to_cart() {
...
+			// process_payment() should only return `success` or throw an exception.
+			if ( ! is_array( $result ) || ! isset( $result['result'] ) || 'success' !== $result['result'] || ! isset( $result['redirect'] ) ) {
+				throw new Exception( __( 'Unable to determine payment success.', 'woocommerce-payments' ) );
+			}
+
+			// Include the order ID in the result.
+			$result['order_id'] = $order_id;
+
+			// Respond with the result.
+			wp_send_json( apply_filters( 'woocommerce_payment_successful_result', $result, $order_id ) );
```
[the remark this answers is not in the document]
Comment (RadoslavGeorgiev) [reply includes/class-wc-payments-payment-request-button-handler.php]: Makes sense. Done in https://github.com/Automattic/woocommerce-payments/pull/4264/commits/40b9a3e245da6a2fd3ba37e417ed30cb1ef1c4fa

**Comment by RadoslavGeorgiev** [comment]
@zmaglica I've addressed your feedback and the PR is ready for another review round.

**Review by zmaglica — APPROVED** [review]

**Comment by Modern-Memories** [comment]
Awesome it looks like we are close to a beta please let me know if you wane me to test it in my website .

**Comment by cmaskaler** [comment]
Hi, when will this fix be finished?

**Comment by htdat** [comment]
Hi @cmaskaler, this has been finished since WooCommerce Payments 4.6.0 (released on 2022-08-18):

https://github.com/Automattic/woocommerce-payments/blob/0a23fe927da47c745b594ce232f333ae2bd72473/changelog.txt#L358-L359
