### PR TITLE
Fix fatal issue if enabled currencies db option is set as string.

### LINKED ISSUE #2710: If `wcpay_multi_currency_enabled_currencies` gets set as an empty string it causes fatal errors
If `wcpay_multi_currency_enabled_currencies` gets set as an empty string it causes fatal errors. This shouldn't happen, but it's been reported in a forum thread: https://wordpress.org/support/topic/critical-error-after-installing-multi-currency/

To replicate:
1. Go into your `wp_options` table and delete the `option_value` for `wcpay_multi_currency_enabled_currencies`.
2. If you don't have this option, create a new row with `wcpay_multi_currency_enabled_currencies` as the `option_value`.
2. View any page on the site to receive the error.

### PR DESCRIPTION
**Pull request by jessepearson**
Fixes #2710 

#### Changes proposed in this Pull Request

* Check that `wcpay_multi_currency_enabled_currencies` option returns an array, and if not, make it an empty array.
* The reason for making an empty array is that we've never set this option as anything other than array, so we wouldn't know how to read any string entered.
* Check that currency cache returned from db is an array before checking for array values.

#### Testing instructions

1. Go into your `wp_options` table and delete the `option_value` for `wcpay_multi_currency_enabled_currencies`.
2. If you don't have this option, create a new row with `wcpay_multi_currency_enabled_currencies` as the `option_value`.
2. View any page on the site, no error should be received.
3. Navigate to WooCommerce > Settings > Multi-Currency, the store currency should show as the only enabled currency.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by tpaksu — APPROVED** [review]
I've tested it, wrote `taha` to the option_value of `wcpay_multi_currency_enabled_currencies` key, doesn't produce any fatal errors, but the string value remains as `taha` on subsequent calls. It won't matter because the only place it's fetched from the database seems to be that place. If someone directly tries to get and use it, then they should also add checks for the result, so looks enough for me to solve problems related to this issue. Tests are also passing. So :shipit:!

File: includes/multi-currency/MultiCurrency.php [hunk 1]
```diff
@@ -455,6 +455,7 @@ private function initialize_available_currencies() {
 	private function initialize_enabled_currencies() {
 		$available_currencies     = $this->get_available_currencies();
```
Comment (marcinbot) [inline includes/multi-currency/MultiCurrency.php:456]: Should we also make sure that `get_available_currencies` always returns an array, maybe inside of the `get_available_currencies` function body, just in case?

Comment (tpaksu) [reply includes/multi-currency/MultiCurrency.php:444]: I think you've missed that, the function already has to return an array, or it'll throw an error, it has a return type declaration: https://github.com/Automattic/woocommerce-payments/blob/36b512ad21373783aaeb646f509b66703e19e96b/includes/multi-currency/MultiCurrency.php#L511-L513

Comment (jessepearson) [reply includes/multi-currency/MultiCurrency.php:444]: Right, I think he was referring to checking to make sure it was an array in the method itself so that it always returns an array instead of throwing an error.

Comment (tpaksu) [reply includes/multi-currency/MultiCurrency.php:444]: Oh, yes, that must be it.
