### PR TITLE
Fix fee amount not showing negative value in transactions CSV

### LINKED ISSUE #3657: [GlobalStep] "Fees" column values are different in the downloaded CSV file for the transaction table.
## Bug Description:
"Fees" column values are different in the downloaded CSV file for the transaction table.

## Environment:
Woocommerce Version : WooCommerce 6.1.0
WooCommerce  Payments  3.6.0-test-3
WordPress version: v5.8.3

PC:
Windows 10
Chrome(Version 97.0.4692.71) 
Firefox(Version 96.0.1)
Mac OS:
Safari: v14.1.2

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Upload and activate theWooCommerce Payments - v3.6.0-test-3 plugin.
1. Complete the setup wizard.
1. Add some products.
1. Go to frontend and purchase some products with WooCommerce payments.
1. Go to WP admin, Payments->Transactions.
1. Click on download icon.
1. Observe that "Fees" column values are different in the downloaded CSV file for the transaction table..

## Actual Result:
"Fees" column values are different in the downloaded CSV file for the transaction table.

## Expected Result:
"Fees" column values should be same as the downloaded CSV file for the transaction table.

## Screenshot:

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

### WordPress Environment ###

WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.27

`
### WordPress Environment ###

WC Version: 6.1.0
REST API Version: ✔ 6.1.0
WC Blocks Version: ✔ 6.5.1
Action Scheduler Version: ✔ 3.4.0
WC Admin Version: ✔ 3.0.3
Log Directory Writable: ✔
WP Version: 5.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.52 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.27
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.0
WC Database Prefix: wp_
Total Database Size: 7.24MB
Database Data Size: 5.29MB
Database Index Size: 1.95MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.48MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.41MB + Index: 0.41MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 10
post: 2
product: 26
product_variation: 7
revision: 4
shop_coupon: 1
shop_order: 64
shop_order_refund: 6
shop_subscription: 18

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.8.2
Code Snippets: by Code Snippets Pro – 2.14.3
Companion Plugin: by Osk – 1.21
WooCommerce Payments: by Automattic – 3.6.0-test-3
WooCommerce: by Automattic – 6.1.0

### Inactive Plugins (6) ###

Akismet Anti-Spam: by Automattic – 4.2.1
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 10.5
WooCommerce Blocks: by Automattic – 6.7.1
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Subscriptions: by WooCommerce – 3.1.6

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://autonomous-kinkajou.jurassic.ninja
Subscription Statuses: wc-cancelled: 1
wc-active: 17

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 17
wc-cancelled: 1

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
tokenization
add_payment_method

### WooCommerce Payments ###

Version: 3.6.0-test-3
Connected to WPCOM: Yes
Blog ID: 201865612
Account ID: acct_1KJBW62EtjO2SGtr

### Action Scheduler ###

Complete: 351
Oldest: 2022-01-18 07:10:48 +0000
Newest: 2022-01-18 12:09:25 +0000

Pending: 21
Oldest: 2022-01-18 15:19:49 +0000
Newest: 2022-04-18 13:13:37 +0000

Canceled: 1
Oldest: 2022-01-18 08:40:37 +0000
Newest: 2022-01-18 08:40:37 +0000

### Status report information ###

Generated at: 2022-01-18 15:18:55 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #3657 

#### Changes proposed in this Pull Request

Fixes a bug where the fee amount in the downloaded CSV does not have the same value as the fee amount column in the Transactions list. In the downloaded CSV, the fee amount is displayed as a positive number, but it should be displayed as a negative number.

**Before:**
149965942-9b60c9da-bfdf-480f-9e95-80a960f981df

**After:**

Screen Shot 2022-01-18 at 16 38 34

#### Testing instructions

1. Go to frontend and purchase some products with WooCommerce payments.
2. Go to WP admin, Payments->Transactions.
3. Click on download icon.
4. Observe that "Fees" column values are different in the downloaded CSV file for the transaction table..

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) : [Testing Instuctions](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions-for-WC-Payments-3.6.0#fix-for-fees-column-values-are-different-in-the-downloaded-csv-file-for-the-transaction-table)

### CODE REVIEW

**Comment by anu-rock** [comment]
@mgascam Thanks for fixing the negative sign. But I see in the screenshot that all negative values have an extra `'` at the start. This seems to be a regression as it was fixed earlier in #1881.

**Review by kalessil — APPROVED** [review]
LGTM! 

Also please add entries to changelog (changelog.txt, readme.txt) and check failing JS tests.

**Comment by kalessil** [comment]
@anu-rock: the PR you are referencing seems to be merged but later reverted.

**Comment by mgascam** [comment]
> #1881

**Comment by mgascam** [comment]
Thanks @anu-rock and @kalessil I'll have a look at the issue of the extra `'`.

File: client/transactions/list/test/index.tsx [hunk 1]
```diff
@@ -555,10 +555,12 @@ describe( 'Transactions list', () => {
 				)
 			).not.toBe( -1 ); // amount
 			expect(
-				getUnformattedAmount( displayFirstTransaction[ 3 ] ).indexOf(
```
Comment (mgascam) [inline client/transactions/list/test/index.tsx:558]: I had to change the approach of this assertion. If the fee amount is a float, in the list it is displayed as '$0.50' whereas in the CSV it is formatted as '0.5' (note the absence of trail zero). We can get rid of the currency using the `getUnformattedAmount` function, that returns '0.50' in this example. To overcome this, I decided to convert '0.50' and '0.5' to Number.
Please let me know if you think there is better way to do this.

File: client/transactions/list/test/index.tsx [hunk 2]
```diff
@@ -555,10 +555,12 @@ describe( 'Transactions list', () => {
...
-					csvFirstTransaction[ 4 ]
+				-Number( getUnformattedAmount( displayFirstTransaction[ 3 ] ) )
```
Comment (mgascam) [inline client/transactions/list/test/index.tsx:558]: In this particular test this is asserting that -Number('0.50') === Number('-0.5')

**Review by kalessil — APPROVED** [review]
LGTM!
