### PR TITLE
Fix monthly deposit schedule displayed incorrectly as '3rd' or '31st' when schedule set to 'Last day of the month'

### LINKED ISSUE #5616: [Deposits UI] Monthly deposit schedule displayed incorrectly as the '3rd' when schedule set to 'Last day of the month'
### Describe the bug

The monthly deposit schedule is incorrectly displaying as the '3rd' on the **Payments → Overview** screen when the schedule has been set to 'Last day of the month'.

### To Reproduce

1. Go to **Payments → Settings**
2. Set the deposit schedule to **Last day of the month**
4. Go to **Payments → Overview**
5. Notice that the deposit schedule is displayed as "Deposits set to monthly on the 3rd."

### Actual behavior

The deposit schedule is displayed as "Deposits set to monthly on the 3rd." on the **Payments → Overview** screen when the merchant has selected "Last day of the month".

### Screenshots

Deposit schedule in **Payments → Settings**.
image

Deposit schedule as displayed on **Payments → Overview**.
image

### Expected behavior

The deposit schedule should be displayed as "Deposits set to monthly on the last day of the month." on the **Payments → Overview** screen when the merchant has selected "Last day of the month".

### Desktop (please complete the following information):

* OS: macOS 13.2.1
* Browser: Firefox developer edition 
* Version: 111.0b4

### LINKED ISSUE #5662: Deposits overview shows wrong deposit timing information
### Describe the bug

If I have my deposit schedule set to **Monthly > Last day of the month**, but then I look at the **Payments > Overview** page, it says "Deposits set to monthly on the 31st." This could potentially be confusing, as not all months have 31 days.

### To Reproduce

1. WC + WC Pay test site + Stripe account set up.
2. Under Payments > Settings, set the deposit schedule to the last day of each month.
3. Go to Payments > Overview.
4. Observe:

Screenshot taken on 2023-03-01 at 15 45 18 UTC@2x

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #5616
Fixes #5662

#### Changes proposed in this Pull Request

This PR correctly renders the monthly deposit schedule as `monthly on the last day of the month` on the **Payments → Overview** screen when the schedule has been set to 'Last day of the month'.

image

Logic for determining the monthly anchor label was used across 2 files ([1](https://github.com/Automattic/woocommerce-payments/blob/8085bf0057dc1e7c5453a7cdfd3d6be2a883daa0/client/deposits/utils/index.js/#L77-L87), [2](https://github.com/Automattic/woocommerce-payments/blob/8085bf0057dc1e7c5453a7cdfd3d6be2a883daa0/client/settings/deposits/index.js/#L39-L72)), therefore I've combined this logic into the `getDepositMonthlyAnchorLabel` function:

https://github.com/Automattic/woocommerce-payments/blob/eec5e7874dd0be58b9fb7010c1130b57007f1e4c/client/deposits/utils/index.js#L51-L54

#### Testing instructions

1. Go to **Payments → Settings**.
2. Set the deposit schedule to **Last day of the month** and click save. Also ensure all select input options are rendered correctly (1st-28th + 'Last day of the month').

   image

4. Go to **Payments → Overview**.
5. Check that the deposit schedule is displayed as "Deposits set to monthly on the last day of the month."
6. Repeat steps 2-5 with various `daily`, `weekly` and `monthly` schedules, ensuring that the expected label is displayed on the **Payments → Overview** screen.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times.
- [x] Covered with tests **Yes**
- [x] Tested on mobile **Yes**

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: client/settings/deposits/index.js [hunk 1]
```diff
@@ -36,40 +37,14 @@ const daysOfWeek = [
...
-		label: __( 'Last day of the month', 'woocommerce-payments' ),
-		value: 31,
-	},
-];
+	...Array.from( { length: 28 }, ( _, i ) => i + 1 ),
+	31,
+].map( ( anchor ) => ( {
+	value: anchor,
+	label: getDepositMonthlyAnchorLabel( { monthlyAnchor: anchor } ),
+} ) );
```
Comment (Jinksi) [inline client/settings/deposits/index.js:47]: This is more concise and DRY (uses `getDepositMonthlyAnchorLabel` utility function) than the existing hard-coded labels. It also reduces the number of translations required.

Ive added a code comment above to add some context as it is harder to reason about at a glance.

**Comment by james-allan** [comment]
Changes look good to me. :) 

I noticed during testing that it wasn't showing the issue you originally reported in #5616 - specifically that you saw is say the 3rd. In my tests, it said "Deposits set to monthly on the 31st". 


Screenshot 2023-03-02 at 2 17 23 pm

This is likely because you noted the issue in February and February doesn't have a 31st.

**Review by james-allan — APPROVED** [review]

**Comment by Jinksi** [comment]
> This is likely because you noted the issue in February and February doesn't have a 31st.

@james-allan 😝 lucky I was testing this in Feb, we mightn't have noticed for another year!

**Comment by james-allan** [comment]
Just noting that I've updated the PR description to also include https://github.com/Automattic/woocommerce-payments/issues/5662 in it's list of fixed issues.
