### PR TITLE
Handle rejected capability status

### LINKED ISSUE #7449: If Afterpay/Clearpay rejects the merchant, "More information needed" still shows in Payments > Settings
### Describe the bug
When a WCPay merchant is unable to offer Afterpay/Clearpay due to a rejected status like `rejected.unsupported_business`, the chip will read `More information needed`. 

If they follow the instructions outlined in our docs [here](https://woocommerce.com/document/woopayments/payment-methods/buy-now-pay-later/#contact-support), they will not be able to provide any additional information.

### To Reproduce

I have no idea how to reproduce. I suspect that we can...

1. Create a WCPay account.
2. Ask Stripe to reject _just_ Afterpay/Clearpay.
3. Navigate to Payments > Settings.
4. See the `More information needed` chip.

### Actual behavior

If a merchant cannot use Afterpay/Clearpay due to rejection, they are still asked to provide more information—but they cannot provide that information as expected.

### Screenshots

Markup on 2023-10-10 at 19:13:23

Markup on 2023-10-10 at 19:15:54

Event log for `evt_1NsCi4Fsnquk42sRqjqklfUX`:

```
{
  "object": {
    "id": ["afterpay_clearpay_payments"]([REDACTED]),
    "object": "capability",
    "account": "[REDACTED]",
    "future_requirements": {
      "alternatives": [
      ],
      "current_deadline": null,
      "currently_due": [
      ],
      "disabled_reason": null,
      "errors": [
      ],
      "eventually_due": [
      ],
      "past_due": [
      ],
      "pending_verification": [
      ]
    },
    "requested": true,
    "requested_at": 1695054795,
    "requirements": {
      "alternatives": [
      ],
      "current_deadline": null,
      "currently_due": [
      ],
      "disabled_reason": "rejected.unsupported_business",
      "errors": [
      ],
      "eventually_due": [
      ],
      "past_due": [
      ],
      "pending_verification": [
      ]
    },
    "status": "inactive"
  },
  "previous_attributes": {
    "requirements": {
      "disabled_reason": null
    },
    "status": "active"
  }
}
```

### Expected behavior

We should likely treat this like rejections for other APMs, like P24, and render a chip that directs the merchant to contact support.

### Additional context

7123991-zen

### PR DESCRIPTION
**Pull request by KarlisJ**
Fixes #7449 

#### Changes proposed in this Pull Request

Handles a new `rejected` capability status in the settings screen by displaying correct badge and tooltip text.

Note: The text in tooltip is not final. 

#### Testing instructions

- Use 4091-gh-Automattic/woocommerce-payments-server
- Open `payment` -> `settings` 
- observe that Klarna has the badge and tooltip 

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7586` or branch name `fix/7449-handle-rejected-pm-capability-status` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7449-handle-rejected-pm-capability-status) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 3a1d78af123d46d5a87b1c9ed29e8f306a4614d3
- Build time: 2023-11-06 10:46:55 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/components/payment-methods-list/payment-method.tsx [hunk 1]
```diff
@@ -173,6 +182,33 @@ const PaymentMethod = ( {
...
+						// eslint-disable-next-line jsx-a11y/anchor-has-content
+						<a
+							target="_blank"
+							rel="noreferrer"
+							title={ __(
+								'Contact Support',
+								'woocommerce-payments'
+							) }
+							href={
+								'https://woocommerce.com/document/woopayments/TODO/correct-link'
```
Comment (dmvrtx) [inline client/components/payment-methods-list/payment-method.tsx]: Reminder to update it before merging.

**Review by dmvrtx — APPROVED** [review]
Code-wise looks good. Visually also good, although it took an effort to trick payment method into `rejected` status.

**Review by kalessil — COMMENTED** [review]
Looks good!

Two questions:
- are there any tests on client for rendering the statuses?
- is server-side change compatible with older version of the client?

**Comment by KarlisJ** [comment]
@kalessil 
> are there any tests on client for rendering the statuses?

I'll add tests once we are aligned on the approach. So far this was treated as WIP.

> is server-side change compatible with older version of the client?

That's a great question. I tested and seems that existing code can't handle the changes in the server as expected so we'll need to do a client_version check in the server.

**Comment by KarlisJ** [comment]
@kalessil There are only unit tests that assert the functionality of label and tooltips being shown (uses dummy `foobar` style values).

We should have tests for the logic of what's the content of the label/tooltip. But right know gathering together various conversations about them, I have a feeling there's not a clear consensus on how we want to handle them. With that, I think investing now in tests for that wouldn't be wise. 

WDYT?

**Comment by kalessil** [comment]
@KarlisJ: gotcha, let's not over-invest. I'm ok to limit us with only `uses dummy foobar style values` test case for new label.

**Review by kalessil — APPROVED** [review]
LGTM (code review only)! Like how simple it turned to be!

**Review by mgascam — APPROVED** [review]
