### PR TITLE
fix: tokenized ECE to honor woocommerce_tax_display_cart

### LINKED ISSUE #10623: ECE to honor "WooCommerce > Tax > Display prices during cart & checkout" setting
### Describe the bug

The ECE is not honoring the "WooCommerce > Tax > Display prices during cart & checkout" setting set by the merchant. When the "Display prices during cart and checkout" setting is set to "Including Tax", the ECE will show the prices in the summary view *without* taxes included.

This happens for items summary, but also for shipping selection.

The block-based and shortcode-based checkouts will instead show the prices *with* the tax, based on the selected setting.

### To Reproduce

1. As a merchant, navigate to "WooCommerce > Tax > Display prices during cart & checkout"
2. Select "Including Tax"
3. As a merchant, ensure you have "US-CA" tax rates set
4. As a merchant, ensure you have a shipping rate
5. As a merchant, ensure you have GooglePay/ApplePay set up
6. As a customer, add a physical product to the cart
7. Click on the GooglePay/ApplePay button
8. Click on the "(i)" icon next to the price

### Actual behavior

Ensure the prices are displayed including tax, without the "Tax" line item, if the "Display prices during cart and checkout" setting is set to "Including Tax".

### Screenshots

Notice the discrepancy:

Image

Image

Image

### Expected behavior

Prices in the GooglePay/ApplePay dialogs should be displayed including tax, if the setting is enabled for the checkout pages.
Since the GooglePay/ApplePay dialogs are "like" a checkout experience, the prices should be displayed with the tax within the dialogs themselves, even if the dialog was triggered from a product page.

### Additional context

p1742822484693559-slack-C3NCP7ZJ6

### PR DESCRIPTION
**Pull request by frosso**
Fixes https://github.com/Automattic/woocommerce-payments/issues/10623
Fixes WOOPMNT-4883

#### Changes proposed in this Pull Request

Ensuring that the Tokenized ECE will start honoring the "Display prices during cart and checkout" setting.

The effect is as follows:

<details><summary>1️⃣  When "Display prices during cart and checkout" is set as "Excluding tax" (default)</summary>
<p>

Screenshot 2025-04-01 at 10 38 31 AM
Screenshot 2025-04-01 at 11 37 07 AM
Screenshot 2025-04-01 at 11 37 02 AM

Also notice that the individual shipping options in the payment sheet are displayed without tax:
Screenshot 2025-04-01 at 10 38 00 AM

</p>
</details> 

<details><summary>2️⃣   When "Display prices during cart and checkout" is set as "Including tax"</summary>
<p>

Screenshot 2025-04-01 at 10 35 11 AM

Notice that the shipping rates shows the price in its selection, and the tax line item is not displayed in the payment sheet summary
Screenshot 2025-04-01 at 11 36 13 AM
Screenshot 2025-04-01 at 11 36 22 AM

Also notice that the individual shipping options in the payment sheet are displayed with tax:
Screenshot 2025-04-01 at 10 34 39 AM

</p>
</details> 

#### Testing instructions

> [!NOTE]
> I'd suggest testing with some products added to the cart, so that you can just change the setting 

**Baseline**
- As a merchant, ensure you have Google Pay/Apple Pay enabled
- As a merchant, ensure you have a coupon like `10off`, which sets 10% off (just to test it in the line items)
- As a customer, add some products to the cart
- Navigate to either the block-based or shortcode-based cart page (the implementation will be identical)
- Apply the `10off` coupon

1️⃣ Test 1: "Display prices during cart and checkout" is set as "Excluding tax"
- As a merchant, navigate to WooCommerce > Settings > Tax
- Set the "Display prices during cart and checkout" to "Excluding tax" (which should be the default behavior on your store)
- As a customer, refresh the cart page from the previous step
- Click on the Google Pay/Apple Pay button
- The payment sheet should appear
- Unless there are discrepancies with the totals, you should be able to inspect the line items, the Tax line item should appear
- Dismiss the payment sheet
- Apply the `10off` coupon
- Click on the Google Pay/Apple Pay button
- The payment sheet should appear
- Unless there are discrepancies with the totals, you should be able to inspect the line items, the "Tax" and "Discount" line items should appear

2️⃣  Test 2: "Display prices during cart and checkout" is set as "Including tax"
- As a merchant, navigate to WooCommerce > Settings > Tax
- Set the "Display prices during cart and checkout" to "Including tax"
- As a customer, refresh the cart page from the previous step
- Click on the Google Pay/Apple Pay button
- The payment sheet should appear
- Unless there are discrepancies with the totals, you should be able to inspect the line items, the Tax line item should not be preset
- Dismiss the payment sheet
- Apply the `10off` coupon
- Click on the Google Pay/Apple Pay button
- The payment sheet should appear
- Unless there are discrepancies with the totals, you should be able to inspect the line items, the "Tax" line item should not be present, and the "Discount" line item be present, including the tax amount

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10662` or branch name `fix/tokenized-ece-to-honor-tax-display` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/tokenized-ece-to-honor-tax-display) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 8adf9e3d0f15398f86eded3cd46d691cd9536711
- Build time: 2025-04-03 09:36:03 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/tokenized-express-checkout/transformers/wc-to-stripe.js [hunk 1]
```diff
@@ -78,25 +86,71 @@ export const transformCartDataForDisplayItems = ( rawCartData ) => {
...
+			amount: transformPrice(
+				displayPriceIncludingTax
+					? shippingAmount +
+							parseInt(
+								cartData.totals.total_shipping_tax || '0',
+								10
+							)
+					: shippingAmount,
+				cartData.totals
+			),
```
Comment (frosso) [inline client/tokenized-express-checkout/transformers/wc-to-stripe.js:104]: I initially thought of having a utility function for this. But then, I noticed that WC Core performs the same check in multiple areas, so I thought it might not be necessary 🤷 

https://github.com/woocommerce/woocommerce/blob/f4d80351eda1dab106db285827cf99ae5432103f/plugins/woocommerce/client/blocks/assets/js/blocks/checkout/inner-blocks/checkout-shipping-methods-block/block.tsx#L39-L41

https://github.com/woocommerce/woocommerce/blob/f4d80351eda1dab106db285827cf99ae5432103f/plugins/woocommerce/client/blocks/assets/js/base/components/cart-checkout/shipping-rates-control-package/render-package-rate-option.tsx#L20-L25

**Review by tpaksu — APPROVED** [review]
Thanks for fixing this, it works as described in the PR description, the prices shown on both areas are consistent. 

Tested it with 6.00$ cart, 1.00$ shipping rate and applied a 15% discount coupon using Google Pay (couldn't test ApplePay because it's not enabled in Turkey). 

Here are the results: 

# Prices displayed excluding tax: 

## Coupon not applied

### Cart totals
image

### Google Pay totals
image

## Coupon applied

### Cart totals
image

### Google Pay totals
image

# Prices displayed including tax: 

## Coupon not applied

### Cart totals
image

### Google Pay totals
image

## Coupon applied

### Cart totals
image

### Google Pay totals
image

ship it
