### PR TITLE
Don't copy product ID when duplicating subscription product

### LINKED ISSUE #2944: Duplicating a product in the admin product list table creates a 2:1 WC - Stripe product
### Describe the bug

If you duplicate a WC subscription product it creates a 2:1 WC product to Stripe product link and results in syncing issues. 

### To Reproduce

1. Checkout the latest `feature/stripe_billing` branch.
1. Create a subscription product
   - A corresponding product will be created in Stripe.
2. On the **Products** admin screen, click the duplicate link. https://d.pr/i/y6AftH
2. In the Stripe dashboard, note that no extra product was created for this product. If you view the product in the dashboard it will have the same price and product IDs. 

Screen Shot 2021-09-20 at 3 35 42 pm

### Actual behavior

When duplicating a product, the WC Pay product IDs are being copied to the duplicate item. If you edit one of those products, the price in Stripe is updated and the old one is archived but that isn't copied over to the other product and so trying to purchase it will lead to an inactive price object being used.

### Expected behavior

When duplicating products we will need to make sure the duplicate product gets its own ID or at the very least we don't copy the product IDs during that process. 

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by brianyu28**
Fixes #2944

#### Changes proposed in this Pull Request

Previously, duplicating a subscription product would retain the same `_wcpay_product_id`, which meant one product on Stripe would be linked to two products in WooCommerce. Editing one of the products would invalidate the price on the other product and lead to an error during purchase ("There was a problem creating your subscription. Please try again or contact us for assistance.") This PR fixes this by excluding the meta field `_wcpay_product_id` from being copied during duplication.

#### Testing instructions

* Create a new subscription product. Check the database to see what the product's `_wcpay_product_id` value is in the `wp_postmeta` table.
* On the **Products > All Products** admin screen, click "Duplicate" beneath the original subscription product. Change the subscription price and click "Update."
* Check the database again and notice that both products should have different `_wcpay_product_id` values.
* Check the Stripe dashboard, note that both products should be listed there: one for the original product, and one for the duplicate.
* Make a sample purchase for either  subscription product and verify that the correct price is charged and "Sign up now" doesn't trigger an error.

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 1]
```diff
@@ -149,6 +150,17 @@ public static function has_wcpay_product_id( WC_Product $product ) : string {
...
 	}
 
+	/**
+	 * Prevents duplicate _wcpay_product_id when duplicating a subscription product.
+	 *
+	 * @param array $meta_keys The keys to exclude from the duplicate.
+	 * @return array Keys to exclude, including _wcpay_product_id.
+	 */
+	public static function exclude_meta_wcpay_product_id( $meta_keys ) {
+		$meta_keys[] = self::PRODUCT_ID_KEY;
```
Comment (aprea) [inline includes/subscriptions/class-wc-payments-product-service.php:160]: I noticed the following metadata is retained with duplicating subscription products:
- `self::PRODUCT_HASH_KEY` (`'_wcpay_product_hash'`)
- `self::PRICE_HASH_KEY` (`'_wcpay_product_price_hash'`)
- `self::PRICE_ID_KEY` (`'_wcpay_product_price_id'`)

Should we also exclude these?

Comment (james-allan) [reply includes/subscriptions/class-wc-payments-product-service.php:160]: yeah, we should exclude all the product IDs and hashes. 

In #3088 we're introducing keys for `_live` and `_test` so I'm not sure how we want to handle that. Merge this PR, rebase @mattallan's PR and then update them there? Or merge Matt's, rebase this branch and then update them here.
