### PR TITLE
Sanitize option key for subscription

### LINKED ISSUE #4259: Tax rate name is not sanitized when saving to DB part of an order
First reported by @aheckler 

### Describe the bug

Tax rate name (example `Tax for climate`) isn't sanitized when saved part of a sale/order.

### To Reproduce

1. Turn taxes on for a WC store
2. Add a new tax with a name containing spaces. For example ('Tax for climate') 
3. Apply the tax to a WC Pay subscriptions product (or leave it on all store products)
4. Purchase the product with the tax applied to it
5. Verify the `wp_options` table. There should be a new option called `_wcpay_product_id_test_tax for climate` (contains spaces)

### Actual behavior

The tax name is saved as it is to the options table

### Expected behavior

Tax name should be "sanitized" or at least spaces should be replaced with `_`.

### Desktop (please complete the following information):

* OS: macOS
* Browser Chrome
* Version 100.x

### PR DESCRIPTION
**Pull request by nagpai**
Replace spaces with underscores between words in option key names for sub products.

Fixes #4259 

#### Changes proposed in this Pull Request
Sanitize Subscription product option key name before they are saved in DB

Option keys, for example, tax names, are saved as `_wcpay_product_id_Tax name`  instead of `_wcpay_product_id_tax_name`. The PR replaces spaces with underscores, and makes the option name in all small case, before it gets concatenated and saved in the database. 

#### Testing instructions

* Turn taxes on for a WC store
* Add a new tax with a name containing spaces. For example ('Tax for climate')
* Apply the tax to a WC Pay subscriptions product (or leave it on all store products)
* Purchase the product with the tax applied to it
* Verify the wp_options table. There should be a new option called `_wcpay_product_id_test_tax_for_climate` (contains name of the tax with underscore instead of spaces)

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (Not applicable)

Post merge
- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : (QA Testing Not Applicable)
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable. - (Not applicable)
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable. - (Not applicable)

### CODE REVIEW

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 1]
```diff
@@ -128,11 +128,12 @@ public function get_wcpay_product_id( WC_Product $product, $test_mode = null ) :
 	 * return string       The item's WCPay product id.
 	 */
 	public function get_wcpay_product_id_for_item( string $type ) : string {
-		if ( ! get_option( self::get_wcpay_product_id_option() . '_' . $type ) ) {
-			$this->create_product_for_item_type( $type );
+		$sanitized_type = str_replace( ' ', '_', trim( strtolower( $type ) ) );
```
Comment (elazzabi) [inline includes/subscriptions/class-wc-payments-product-service.php:131]: This will effectively remove all spaces and replace them with `_`, I wonder if that's the only thing we want to do? ie, are there any other things we want to sanitize? Maybe `+`, `%` or other special characters...

Also, can we re-use some of the existing Woo functionality? The `sanitize_key()` function for example.

**Review by elazzabi — COMMENTED** [review]
Thank you for working on this!

I left a comment about the sanitization process

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 1 above)
Comment (anu-rock) [reply includes/subscriptions/class-wc-payments-product-service.php:131]: A great start, @nagpai! :)

I was having thoughts similar to @elazzabi just now after looking at it more carefully. `sanitize_key` is purpose-built for scenarios like this and ensures no extraneous characters are present in the target string.

Going by its [source code](https://core.trac.wordpress.org/browser/tags/6.0/src/wp-includes/formatting.php#L2154), looks like it will remove even spaces. Although that might result in reduced readability compared to what you've done, it's a reasonable tradeoff.

Comment (nagpai) [reply includes/subscriptions/class-wc-payments-product-service.php:131]: Thank you @elazzabi and @anu-rock ! I had tried the `sanitize_key()` function earlier and passed that since it was removing the spaces and affecting reliability. Thanks to the reminder here about excluding any other special characters though! 

I think the solution here would be to first replace the spaces with underscores, and then run that through `sanitize_key`. I will test this and place for further review here 👍

**Review by nagpai — COMMENTED** [review]
I accidentally clicked the `Update branch` button. It ended up pushing the commit. Sorry. It is blocked thankfully!

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 1 above)
Comment (anu-rock) [reply includes/subscriptions/class-wc-payments-product-service.php:131]: > I think the solution here would be to first replace the spaces with underscores

We may skip this entirely. Why do you think readability is important here?

Comment (nagpai) [reply includes/subscriptions/class-wc-payments-product-service.php]: > We may skip this entirely. Why do you think readability is important here?

My gut feel was if someone searches the db, they would look for `tax_with_spaces` instead of `taxwithspaces`. Coming to think of it if they look for `%spaces%` they will still find it. 

I missed reading your comment and for now I have passed the existing `$sanitized_type` formula through `sanitize_key()`.  Let me know if you would want me to keep it simple and move it to just `sanitize_key()` without bothering about underscores.

**Review by nagpai — COMMENTED** [review]
On testing this commit, the tax name `Nagesh @#$%* Tax` resulted in a db option key name of `_wcpay_product_id_test_nagesh__tax`

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 2]
```diff
@@ -128,11 +128,12 @@ public function get_wcpay_product_id( WC_Product $product, $test_mode = null ) :
 	 * return string       The item's WCPay product id.
 	 */
 	public function get_wcpay_product_id_for_item( string $type ) : string {
-		if ( ! get_option( self::get_wcpay_product_id_option() . '_' . $type ) ) {
-			$this->create_product_for_item_type( $type );
+		$sanitized_type = sanitize_key( str_replace( ' ', '_', trim( strtolower( $type ) ) ) );
```
Comment (kalessil) [inline includes/subscriptions/class-wc-payments-product-service.php:131]: A micro-optimisation suggession: `strtolower( trim( $type ) )`

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 3]
```diff
@@ -128,11 +128,12 @@ public function get_wcpay_product_id( WC_Product $product, $test_mode = null ) :
...
+		if ( ! get_option( self::get_wcpay_product_id_option() . '_' . $sanitized_type ) ) {
+			$this->create_product_for_item_type( $sanitized_type );
 		}
 
-		return get_option( self::get_wcpay_product_id_option() . '_' . $type );
+		return get_option( self::get_wcpay_product_id_option() . '_' . $sanitized_type );
```
Comment (kalessil) [inline includes/subscriptions/class-wc-payments-product-service.php:136]: Also `self::get_wcpay_product_id_option() . '_' . $sanitized_type` can be a local variable - another micro optimization.

**Review by kalessil — CHANGES_REQUESTED** [review]
Yay, the first PR! I left a couple of hints + I'd love to see UTs introduced for this method. Thanks!

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 3 above)
Comment (nagpai) [reply includes/subscriptions/class-wc-payments-product-service.php]: Thanks for sharing this opportunity to make the code cleaner following DRY! I saved this as a local variable `$option_key_name`. I hope this looks fine?

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 2 above)
Comment (nagpai) [reply includes/subscriptions/class-wc-payments-product-service.php]: Thanks for reviewing, and those very helpful early learnings for me. I have made the changes in the update 
https://github.com/Automattic/woocommerce-payments/pull/4496/commits/a891e1437fe8adf3adeb5ee77684d58acf24c453#

I have unit tests planned for this. Being the first time, I am taking a bit longer to bring it in :D

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 3 above)
Comment (kalessil) [reply includes/subscriptions/class-wc-payments-product-service.php]: Yep, looks good!

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 4]
```diff
@@ -128,11 +128,22 @@ public function get_wcpay_product_id( WC_Product $product, $test_mode = null ) :
...
 
-		return get_option( self::get_wcpay_product_id_option() . '_' . $type );
+	/**
+	 * Sanitize option key string to replace space with underscore, and remove special characters.
+	 *
+	 * @param string $type Non sanitized input.
+	 * return string       Sanitized output.
+	 */
+	public static function sanitize_option_key( string $type ) {
+		return sanitize_key( str_replace( ' ', '_', strtolower( trim( $type ) ) ) );
```
Comment (anu-rock) [inline includes/subscriptions/class-wc-payments-product-service.php:146]: `sanitize_key` will also [apply strtolower](https://github.com/WordPress/wordpress-develop/blob/6.0/src/wp-includes/formatting.php#L2158). We can remove our explicit use of it.

File: tests/unit/subscriptions/test-class-wc-payments-product-service.php [hunk 5]
```diff
@@ -274,9 +274,7 @@ public function test_get_wcpay_product_id() {
 		$this->assertSame( $mock_product_id, $this->product_service->get_wcpay_product_id( $this->mock_product ) );
 	}
 
-	/**
```
Comment (anu-rock) [inline tests/unit/subscriptions/test-class-wc-payments-product-service.php:277]: Looks like this got removed accidentally?

File: tests/unit/subscriptions/test-class-wc-payments-product-service.php [hunk 6]
```diff
@@ -286,13 +284,26 @@ public function test_get_wcpay_product_id_option() {
...
+		$this->mock_api_client->expects( $this->once() )
+		->method( 'create_product' )
+		->willReturn(
+			[
+				'wcpay_product_id' => 'product_id_test123',
+				'wcpay_price_id'   => 'price_test123',
+			]
+		);
+
+		// If type is 'Test Tax *&^ name', the result should be _wcpay_product_id_live_test_tax__name.
```
Comment (anu-rock) [inline tests/unit/subscriptions/test-class-wc-payments-product-service.php:300]: I like this comment here 👍

File: tests/unit/subscriptions/test-class-wc-payments-product-service.php [hunk 7]
```diff
@@ -286,13 +284,26 @@ public function test_get_wcpay_product_id_option() {
...
+		$test_type = 'Test Tax *&^ name';
+		$this->product_service->get_wcpay_product_id_for_item( $test_type );
+
+		$this->assertSame( 'test_tax__name', WC_Payments_Product_Service::sanitize_option_key( $test_type ) );
```
Comment (anu-rock) [inline tests/unit/subscriptions/test-class-wc-payments-product-service.php:304]: This should go in a separate test dedicated to `sanitize_option_key` :)

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 8]
```diff
@@ -128,11 +128,22 @@ public function get_wcpay_product_id( WC_Product $product, $test_mode = null ) :
...
 		}
+		return get_option( $option_key_name );
+	}
 
-		return get_option( self::get_wcpay_product_id_option() . '_' . $type );
+	/**
+	 * Sanitize option key string to replace space with underscore, and remove special characters.
+	 *
+	 * @param string $type Non sanitized input.
+	 * return string       Sanitized output.
```
[the remark this answers is not in the document]
Comment (nagpai) [reply includes/subscriptions/class-wc-payments-product-service.php:143]: Ah. Looks like I copied it from [Line 128](https://github.com/automattic/woocommerce-payments/blob/083c42d6f2644fe3eee107e76f386931aff9a663/includes/subscriptions/class-wc-payments-product-service.php#L128). I will fix both. Thanks for catching this 🙏

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 4 above)
Comment (nagpai) [reply includes/subscriptions/class-wc-payments-product-service.php:146]: Thanks for sharing the reference! I will remove the `strtolower` from my line, since it is already taken care of by `sanitize_key`

Comment (nagpai) [reply includes/subscriptions/class-wc-payments-product-service.php]: Fixed here https://github.com/Automattic/woocommerce-payments/pull/4496/commits/9c3f75c0d55c429575811709930442123a648c34

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 8 above)
[the remark this answers is not in the document]
Comment (nagpai) [reply includes/subscriptions/class-wc-payments-product-service.php]: Fixed here 
https://github.com/Automattic/woocommerce-payments/pull/4496/commits/9c3f75c0d55c429575811709930442123a648c34

File: tests/unit/subscriptions/test-class-wc-payments-product-service.php (hunk 5 above)
Comment (nagpai) [reply tests/unit/subscriptions/test-class-wc-payments-product-service.php]: Thanks for catching that! . I have added it back - https://github.com/Automattic/woocommerce-payments/pull/4496/commits/4ef7523e175471d595ff3fc949c865ebbdd04425

File: tests/unit/subscriptions/test-class-wc-payments-product-service.php (hunk 6 above)
Comment (nagpai) [reply tests/unit/subscriptions/test-class-wc-payments-product-service.php:302]: Thank you :)

File: tests/unit/subscriptions/test-class-wc-payments-product-service.php (hunk 7 above)
Comment (nagpai) [reply tests/unit/subscriptions/test-class-wc-payments-product-service.php]: Thanks for the reference! I have fixed it here - https://github.com/Automattic/woocommerce-payments/pull/4496/commits/4ef7523e175471d595ff3fc949c865ebbdd04425

File: tests/unit/subscriptions/test-class-wc-payments-product-service.php [hunk 9]
```diff
@@ -286,13 +286,32 @@ public function test_get_wcpay_product_id_option() {
...
+		$this->product_service->get_wcpay_product_id_for_item( $test_type );
+
+		$this->assertFalse( get_option( '_wcpay_product_id_live_Test Tax *&^ name' ) );
+		$this->assertSame( 'product_id_test123', get_option( '_wcpay_product_id_live_test_tax__name' ) );
+	}
+
+	/**
+	 * Tests for WC_Payments_Product_Service::sanitize_option_key()
+	 */
+	public function test_sanitize_option_key() {
```
Comment (kalessil) [inline tests/unit/subscriptions/test-class-wc-payments-product-service.php:313]: IMO we can drop this test case, as `test_get_wcpay_product_id_for_item` covers the logic.

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 8 above)
[the remark this answers is not in the document]
Comment (anu-rock) [reply includes/subscriptions/class-wc-payments-product-service.php]: Thank you 👍

**Review by anu-rock — APPROVED** [review]
The revised code is looking all good. Cheers for your first approval 🎉 

There's an open comment from @kalessil regarding redundant test case. We may want to address it before merging the PR.

File: tests/unit/subscriptions/test-class-wc-payments-product-service.php (hunk 9 above)
Comment (nagpai) [reply tests/unit/subscriptions/test-class-wc-payments-product-service.php]: @kalessil - I have removed the redundant test case, just now, here https://github.com/Automattic/woocommerce-payments/pull/4496/commits/e792fc0b78e0f64068513d65fe0e3ef4c8bc5d18

Let me know if this looks good to merge. Thanks :)

**Review by kalessil — APPROVED** [review]
LGTM!
