### PR TITLE
Display failure message on order received page for failed orders

### LINKED ISSUE #10508: Display order failure notice on Order Received page
### Describe the bug

Currently, visiting the Order Received page for a failed order will display generic message that the order was received.

### To Reproduce

1. Fail an order
2. Visit an order received page for that order - http://localhost:8082/checkout/order-received/{order_id}
3. Notice the text is "Thank you. Your order has been received."

### Actual behavior

Visiting the Order Received page for a failed order will display generic message that the order was received.

### Expected behavior

The Order Received page should note that the order has failed and include a link to try checkout out again.

### PR DESCRIPTION
**Pull request by mdmoore**
Fixes #10508 

#### Changes proposed in this Pull Request

Currently, if the Order Received page is viewed for a failed order, a generic "Thank you. Your order has been received." message is displayed. This PR changes that message to, "Unfortunately, your order has failed. Please try checking out again." with a link to return to checkout.

This issue came out of the need to indicate payment failures for payment methods that redirect from third-party pages, like WeChat Pay in test mode.

#### Testing instructions

* Fail an order order with a card payment. Changing the order status on a previous order is fine.
* Visit the Order Received page - http://localhost:8082/checkout/order-received/{order_id}
* The text should be "Unfortunately, your order has failed. Please try checking out again."
* Follow steps [here](https://github.com/Automattic/woocommerce-payments/pull/10442) to enable WeChat Pay if needed
* Place an order with WeChat Pay
* Fail the order on the third-party page
* When redirected, the text should be "Unfortunately, your order has failed. Please try checking out again."
-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: includes/class-wc-payments-order-success-page.php [hunk 1]
```diff
@@ -255,6 +258,59 @@ private function format_addtional_thankyou_order_received_text( string $addition
...
+
+		$should_show_failure = false;
+
+		// Check order status first to avoid unnecessary API calls.
+		if ( $order->has_status( Order_Status::FAILED ) ) {
+			$should_show_failure = true;
+		} elseif ( ! empty( $intent_id ) && ! empty( $payment_method_type ) && in_array( $payment_method_type, Payment_Method::REDIRECT_PAYMENT_METHODS, true ) ) {
+			// For redirect-based payment methods that haven't been marked as failed yet, check the intent status.
+			// Add a small delay to allow the intent to be updated.
+			sleep( 1 );
```
Comment (mdmoore) [inline includes/class-wc-payments-order-success-page.php:302]: Without some delay here, the intent hasn't yet been updated with the new status and error.

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10554` or branch name `10508-order-received-failure-notice` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=10508-order-received-failure-notice) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 22fc769883e0f0586cd8cb40b0ac6757f23c32a6
- Build time: 2025-03-14 15:58:33 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payments-order-success-page.php [hunk 2]
```diff
@@ -255,6 +258,59 @@ private function format_addtional_thankyou_order_received_text( string $addition
...
+
+			$intent        = Get_Intention::create( $intent_id );
+			$intent        = $intent->send();
+			$intent_status = $intent->get_status();
+
```
Comment (mdmoore) [inline includes/class-wc-payments-order-success-page.php:307]: The order status for some payment methods, like WeChat Pay, is updated via AJAX and the order hasn't yet updated by the time the `woocommerce_thankyou_order_received_text` runs. Getting the error status from the intent seems to be the best way.

Comment (danielmx-dev) [reply includes/class-wc-payments-order-success-page.php:307]: Can we avoid the intent request and poll for the order status? Something like this (pseudocode):
```
while (retries left) {
  check order status (make sure the value is refetch from the DB, not the cache)
  if (failed) show_error = true; break;
  if (no longer needs payment) break;
 sleep
 retries++
}
```

File: includes/class-wc-payments-order-success-page.php [hunk 3]
```diff
@@ -255,6 +258,59 @@ private function format_addtional_thankyou_order_received_text( string $addition
...
+		// Strip the gateway ID prefix from the payment method.
+		$payment_method_type = str_replace( WC_Payment_Gateway_WCPay::GATEWAY_ID . '_', '', $payment_method );
+
+		$should_show_failure = false;
+
+		// Check order status first to avoid unnecessary API calls.
+		if ( $order->has_status( Order_Status::FAILED ) ) {
+			$should_show_failure = true;
+		} elseif ( ! empty( $intent_id ) && ! empty( $payment_method_type ) && in_array( $payment_method_type, Payment_Method::REDIRECT_PAYMENT_METHODS, true ) ) {
```
Comment (danielmx-dev) [inline includes/class-wc-payments-order-success-page.php:299]: Should we also check if `$order->needs_payment()` before doing any of this?

File: includes/class-wc-payments-order-success-page.php [hunk 4]
```diff
@@ -255,6 +258,59 @@ private function format_addtional_thankyou_order_received_text( string $addition
...
+
+		if ( ! $order ) {
+			return $text;
+		}
+
+		$intent_id      = $order->get_meta( '_intent_id', true );
+		$payment_method = $order->get_payment_method();
+
+		// Strip the gateway ID prefix from the payment method.
+		$payment_method_type = str_replace( WC_Payment_Gateway_WCPay::GATEWAY_ID . '_', '', $payment_method );
```
Comment (danielmx-dev) [inline includes/class-wc-payments-order-success-page.php:292]: Before removing the GATEWAY_ID can we first validate that the payment method used indeed has that prefix so we can avoid acting on orders using other gateways ?

File: includes/class-wc-payments-order-success-page.php (hunk 2 above)
Comment (mdmoore) [reply includes/class-wc-payments-order-success-page.php:307]: This works also, but I'm not sure it's faster. I've tried it here: [c73fafa](https://github.com/Automattic/woocommerce-payments/pull/10554/commits/c73fafa66fbe2f49283f420d1810cf52cae3fb83). The number of retries seems arbitrary but 6 seemed to be the sweet spot in my local testing. Let me know what you think.

Comment (danielmx-dev) [reply includes/class-wc-payments-order-success-page.php:307]: Yes, it seems that the results are not very consistent, I'm also surprised it takes that long to update the order, in my case the 6 retries were not enough. 

I think we have two options here:
1. Poll less times, but if the order still needs payment maybe provide a custom message that says that the process hasn't completed and ask the user to refresh the page (or go a step further and move the polling to the frontend, although that would definitely increase the scope significantly).
2. Restore the get intent approach (but maybe keep the polling mechanism with less retries?)

Although I like not having to make requests to the server, I think (2)  may give us more efficient results?

File: includes/class-wc-payments-order-success-page.php [hunk 5]
```diff
@@ -255,6 +258,70 @@ private function format_addtional_thankyou_order_received_text( string $addition
...
+	 */
+	public function replace_order_received_text_for_failed_orders( $text ) {
+		global $wp;
+
+		$order_id = absint( $wp->query_vars['order-received'] );
+		$order    = wc_get_order( $order_id );
+
+		if ( ! $order ||
+			! $order->needs_payment() ||
+			0 !== strpos( $order->get_payment_method(), WC_Payment_Gateway_WCPay::GATEWAY_ID )
```
Comment (danielmx-dev) [inline includes/class-wc-payments-order-success-page.php:283]: I think the `REDIRECT_PAYMENT_METHODS` check should be restored, just to make sure this doesn't causes any conflicts with vouchers (e.g. multibanco).

File: includes/class-wc-payments-order-success-page.php (hunk 3 above)
Comment (mdmoore) [reply includes/class-wc-payments-order-success-page.php:299]: Yes, this is a good idea to avoid the polling when it's not needed. Added in [c73fafa](https://github.com/Automattic/woocommerce-payments/pull/10554/commits/c73fafa66fbe2f49283f420d1810cf52cae3fb83).

File: includes/class-wc-payments-order-success-page.php (hunk 4 above)
Comment (mdmoore) [reply includes/class-wc-payments-order-success-page.php:292]: Also a good idea. Added in [7b0b5ff](https://github.com/Automattic/woocommerce-payments/pull/10554/commits/7b0b5ff032a255096bbd36fa1459ee19bb05de2c).

File: includes/class-wc-payments-order-success-page.php (hunk 5 above)
Comment (danielmx-dev) [reply includes/class-wc-payments-order-success-page.php:283]: Nevermind, I don't think this comment is accurate, since multibanco should set the order to `on-hold`, and only `failed` and `pending` orders will return true when `needs_payment` is called. https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-order.php#L1788

File: includes/class-wc-payments-order-success-page.php (hunk 2 above)
Comment (mdmoore) [reply includes/class-wc-payments-order-success-page.php:307]: If I understand, option 2 proposes to keep the current polling mechanism with, say 3 retries, then move to the get intent approach if polling fails to capture the status update? If so, that sounds fine to me.

Comment (danielmx-dev) [reply includes/class-wc-payments-order-success-page.php:307]: For option two I actually meant to remove the order status polling and only poll the intents with a few retries. As the order status has proven to be way slower (I think the slowness is because the order is updated by an AJAX call performed by the original checkout page, so that's an additional roundtrip besides all the additional processing done by the endpoint)

Comment (mdmoore) [reply includes/class-wc-payments-order-success-page.php:307]: Got it! We can go with that. Though I was seeing consistent results using a short delay before checking the intent. Were you getting different results and think polling is necessary?

File: includes/class-wc-payments-order-success-page.php (hunk 5 above)
Comment (mdmoore) [reply includes/class-wc-payments-order-success-page.php:283]: Ah ok. Thanks for checking and clarifying!

File: includes/class-wc-payments-order-success-page.php (hunk 2 above)
Comment (danielmx-dev) [reply includes/class-wc-payments-order-success-page.php:307]: I thought of it more like a failsafe measure but we can remove it to keep things simple and just add the short delay at the beginning. In the future it may make sense to revisit option (1), so I think it's fine if for now we keep things straightforward, IMO.

Comment (mdmoore) [reply includes/class-wc-payments-order-success-page.php:307]: Sounds good. For now, this should only affect a single payment method and only in test mode. But option 1 sounds like a good path to take should we ever need to revisit it.

**Comment by danielmx-dev** [comment]
The changes work well, however the message below the heading is a bit confusing, but I don't think there's a way to hide it or change it, is it?

image

If this is expected and we are ok with it please let me know so I can approve the PR.

**Review by danielmx-dev — APPROVED** [review]
Works well, the notice is now gone:
image

I also verified that the regular order received page is not affected negatively by this change
image

**Comment by mdmoore** [comment]
That's unfortunate. I hadn't seen this messaging coming from the blocks order confirmation implementation. The message is displayed because there's no order key in the URL

>I don't think there's a way to hide it or change it, is it?

There isn't. Even if the text were filterable, it looks like there's a bug in blocks that is displaying 2 messages. For example, here's an order with WooPayments disabled: 

Screenshot 2025-03-14 at 11 51 23 AM

I think in this case, hiding the blocks text is the best way to go. I can report the issue in blocks as well as request some filters be added to these confirmation strings. Many strings are already filterable in [Status.php](https://github.com/woocommerce/woocommerce/blob/3f5f8fd80610a52a1f53fc17a11d4c90d6715c85/plugins/woocommerce/src/Blocks/BlockTypes/OrderConfirmation/Status.php#L75) via the `woocommerce_thankyou_order_received_text` filter.

Another option would be to skip this change on block themes, but I think just hiding the duplicate text for this case is fine.
