### PR TITLE
Optimise memory usage when formatting logger entries

### LINKED ISSUE #10201: Test failure on `WC - latest | wcpay - merchant` - `Order > Partial refund`
### Description
`Order > Partial refund › should refund a single line item` in [`merchant-orders-partial-refund.spec.js`](https://github.com/Automattic/woocommerce-payments/blob/3d8846a52d2cf3ad988a26134b5b3ecac2110dba/tests/e2e/specs/wcpay/merchant/merchant-orders-partial-refund.spec.js#L203-L205) has been failing consistently since [this PR](https://github.com/Automattic/woocommerce-payments/pull/9853).

**Output from the test failure**:
```
Order > Partial refund › should refund a single line item

    TimeoutError: Element li.woocommerce-timeline-item (text: "A payment of $5.00 was successfully refunded.") not found
    Waiting failed: 3000ms exceeded
```

### Additional context
It looks like the test is expecting that text in the Timeline section, but it's empty in the screenshot. Screenshot is in the test assets.

Also, when I test this locally, the Timeline has the currency after the amount while the test is not expecting that to be there.

Image

### Priority
Medium-low

### Reason why this e2e test is broken

> [!Important]
> Please, ensure when closing this issue (PR fix) that only one `e2e: broken` label is added and it is accurate.
> - [ ] I confirmed there's only one `e2e: broken` label in this issue and it is accurate.

### PR DESCRIPTION
**Pull request by dmvrtx**
Fixes #10201 

#### Changes proposed in this Pull Request

Optimizations to the memory consumption when formatting a logger entry:

 - Reduce number of stacked function calls
 - Unset entries once those are formatted for the logging

#### Testing instructions

* All E2E tests should complete successfully.
* Manual run of "E2E Tests - All" workflow can be found [here](https://github.com/Automattic/woocommerce-payments/actions/runs/12912242716). Reported tests were successful for this branch.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10216` or branch name `dev/10021-logging-memory-optimisations` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=dev/10021-logging-memory-optimisations) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 4764fe637432a3d05b9bc43d8974f0aa71701d23
- Build time: 2025-01-22 16:27:46 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: src/Internal/LoggerContext.php [hunk 1]
```diff
@@ -124,23 +124,17 @@ public function filter_log_entry( $entry, $context ): string {
...
+		$log_entry       = array_shift( $entries );
+		while ( null !== $log_entry ) {
+			foreach ( explode( "\n", $log_entry ) as $line ) {
+				$formatted_lines[] = $line_prefix . $line;
+			}
+			unset( $log_entry );
+			$log_entry = array_shift( $entries );
+		}
+
+		return implode( "\n", $formatted_lines );
```
Comment (RadoslavGeorgiev) [inline src/Internal/LoggerContext.php:137]: Personally, I prefer to avoid `while` loops if an iterator is available. In this case, a simple `foreach` loop should do the trick. Even if there is context here, the `$entries` array should be quite short, so this seems overoptimized, especially considering that `array_shift` will modify the array every time.

```suggestion
		$formatted_lines = [];
		foreach ( $entries as $log_entry ) {
			foreach ( explode( "\n", $log_entry ) as $line ) {
				$formatted_lines[] = $line_prefix . $line;
			}
		}
		return implode( "\n", $formatted_lines );
```

For me, the decreased number of anonymous functions created, combined with much fewer `sprintf()` calls, should be more than sufficient.

Comment (dmvrtx) [reply src/Internal/LoggerContext.php:137]: `foreach` was my first choice. But I had to add an `unset` because I caught a memory overflow on my local setup when testing a complex transactions page. This eliminated the option of using `foreach` 😞

Comment (RadoslavGeorgiev) [reply src/Internal/LoggerContext.php:137]: Huh, could it be that you were still using `sprintf()` for the whole prefix? I'm really surprised that PHP would not collect the `foreach()` garbage. Anyhow, let's unblock others, we could experiment with this later.

**Review by RadoslavGeorgiev — APPROVED** [review]
Thanks for the quick reaction! :shipit:
