### PR TITLE
Stripe appearance API fixes, and checkout logo updates

### LINKED ISSUE #5502: Multiple UPE - Improve design of UPE elements at checkout.
### Describe the bug

This issue is to resolve inconsistencies and design flaws noted in our first round of internal testing. Please refer to this comment for more details -> paJDYF-6WA-p2#comment-15823

> For Giropay, the “After submission…” text appears inside this white box, which is inconsistent with the rest of the methods.

giropay selected
_We already know giropay is selected!_

I'm not sure that Stripe currently offers us the ability to resolve this, but it doesn't hurt to have a look and find out! I don't think I can see anything specifically mentioning that this might be possible to customise in [Stripe's documentation](https://stripe.com/docs/elements/appearance-api), so we may need to reach out to Stripe for more information on this issue.

> Between the usual checkout form and the dropdown inside some of the payment methods, we have two styles of dropdown menus.

Two different dropdowns
_A tale of two dropdowns_

[Stripe does give us some control to customise dropdown styles](https://stripe.com/docs/elements/appearance-api?platform=web#dropdown), so it's possible that this could be achieved. Although, I assume this will be very challenging for custom WC themes, where the classes of custom dropdown elements are not consistent enough for us to scrape and parse CSS styles. 

> This might be something for legal to look at, but this paragraph under the SEPA method seems odd, since no other methods have anything like this.

SEPA mandate
_Wordy SEPA mandate_

This mandate is presented by Stripe; however, I believe it was our intention to only present these terms when a user is about to save their payment information at checkout. Please can we check whether we have the ability to remove this mandate: if so, we should only reveal the mandate when it is truly appropriate. 

> The P24 logo looks a bit odd considering it’s the only one without a background color of some sort. Even a white rectangular background would help set it off against the page background, similar to the logos above it.

p24 logo
_Unpretty P24 logo_

Please consult with design to see if we can get a more consistent logo for P24 or if this current logo is required. 

### To Reproduce

All of these issues are visible in the split UPE shortcode checkout with additional payment methods enabled and currency set to EUR.

### Actual behavior

See above.

### Screenshots

See above. 

### Expected behavior

It doesn't do bad, but look good.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

paJDYF-6WA-p2#comment-15823

### LINKED ISSUE #8094: Additional Payment Methods have text that cannot be updated via a setting or CSS - String = #payment-method-message.StripeElement
### Describe the bug

When using WooPayments and additonal payment methods, such as Afterpay, there is no way to update the text that is visble on product pages, as well as the cart. These are embedded via an iframe element, thus cannot be changed via CSS. 

Element: `#payment-method-message.StripeElement`

### To Reproduce

1. Create a site with a black or dark background.
2. Enable Afterpay and Affirm in WooPayments.

### Actual behavior

1. On a product page, the text is not readable for the Afterpay message.
2. On the checkout page, any CSS targeted to the iframe element is used, but only for Affirm. 

### Screenshots

Product page: 
image

Checkout page:
affirm_checkout

### Expected behavior

A neat element within WooPayments settings where the colour of the text can be selected, such as you can do with Express Payment options, in each having a setting for the them to be Dark, Light or Outline.

### Desktop (please complete the following information):

* OS: macOS Sonoma 14.1.1
* Browser: Chrome
* Version: 121.0.6167.85

### Additional context

Related ticket(s)
- 7643656-zen

### PR DESCRIPTION
**Pull request by FangedParakeet**
Fixes #8094 
Fixes #5502 

#### Changes proposed in this Pull Request

# Logo updates and checkout appearances amends

This PR adds multiple amends to our implementation of [Stripe's Elements Appearance API](https://docs.stripe.com/elements/appearance-api?platform=web) to improve display of payment gateways at checkout. The appearance API accepts an array of properties describing styling of elements within the payment elements. To compute these styles from the current theme, we add hidden inputs to the page, scrape their CSS styles, and pass the results to Stripe. The changes in this PR mainly concern inconsistent font styling, illegible text on dark themes, and unstyled block elements. 

This PR also adds new logos for Afterpay, Affirm, and Klarna; and additionally fixes the sizes of these icons at checkout and ensures that the sizes of these logos follow brand guidelines.

Additionally, there is a long-standing bug on the blocks checkout, where selecting a payment gateway will cause the page to jump-scroll unexpectedly upwards. This is due to us previously focussing on hidden elements in order to compute styles of the element when the focus state is triggered. I have removed this section of code entirely, because it is enormously detrimental to checkout functionality and has little impact on how the payment elements fields are actually displayed. 

#### Testing instructions

1. Check payment method logos in the payment settings: logos should be consistently sized and have no spacing between the logo and its outline.
2. Check the payment gateways at shortcode and blocks checkout. You may need to ensure the computed styles refresh by changing the theme or forcing the [shortcode](https://github.com/Automattic/woocommerce-payments/blob/fix/8094-appearance-api-amends-and-design-fixes/client/checkout/classic/payment-processing.js#L49) or [blocks](https://github.com/Automattic/woocommerce-payments/blob/fix/8094-appearance-api-amends-and-design-fixes/client/checkout/blocks/payment-elements.js#L34) styles to recompute. Check light themes, dark themes, any themes and ensure that all fields are legible and consistently styled. 
3. Check the console and ensure that the appearances API does not send any warnings for errors in the API parameters. 

See #8094 to find before/after screenshots for these changes. 

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8230` or branch name `fix/8094-appearance-api-amends-and-design-fixes` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8094-appearance-api-amends-and-design-fixes) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 8650a98ba7339a1b3cfe9f8987aa393f9d400f61
- Build time: 2024-02-29 20:51:09 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payments-checkout.php [hunk 1]
```diff
@@ -211,18 +211,18 @@ public function get_payment_fields_js_config() {
...
+		$payment_fields['gatewayId']                  = WC_Payment_Gateway_WCPay::GATEWAY_ID;
+		$payment_fields['isCheckout']                 = is_checkout();
+		$payment_fields['paymentMethodsConfig']       = $this->get_enabled_payment_method_config();
+		$payment_fields['testMode']                   = WC_Payments::mode()->is_test();
+		$payment_fields['upeAppearance']              = get_transient( WC_Payment_Gateway_WCPay::UPE_APPEARANCE_TRANSIENT );
+		$payment_fields['wcBlocksUPEAppearance']      = get_transient( WC_Payment_Gateway_WCPay::WC_BLOCKS_UPE_APPEARANCE_TRANSIENT );
+		$payment_fields['cartContainsSubscription']   = $this->gateway->is_subscription_item_in_cart();
+		$payment_fields['currency']                   = get_woocommerce_currency();
+		$cart_total                                   = ( WC()->cart ? WC()->cart->get_total( '' ) : 0 );
+		$payment_fields['cartTotal']                  = WC_Payments_Utils::prepare_amount( $cart_total, get_woocommerce_currency() );
```
Comment (brettshumaker) [inline includes/class-wc-payments-checkout.php]: Check these whitespace changes. I don't _think_ they're needed.

File: includes/class-wc-payment-gateway-wcpay.php [hunk 2]
```diff
@@ -3920,9 +3922,11 @@ public function save_upe_appearance_ajax() {
 			$appearance = apply_filters( 'wcpay_upe_appearance', $appearance, $is_blocks_checkout );
 
 			$appearance_transient = $is_blocks_checkout ? self::WC_BLOCKS_UPE_APPEARANCE_TRANSIENT : self::UPE_APPEARANCE_TRANSIENT;
+			$appearance_theme_transient = $is_blocks_checkout ? self::WC_BLOCKS_UPE_APPEARANCE_THEME_TRANSIENT : self::UPE_APPEARANCE_THEME_TRANSIENT;
```
Comment (brettshumaker) [inline includes/class-wc-payment-gateway-wcpay.php:3931]: PHP linter is complaining about the `=` not being aligned here.

File: includes/payment-methods/class-upe-payment-method.php [hunk 3]
```diff
@@ -241,6 +248,15 @@ public function get_icon( string $account_country = null ) {
 		return isset( $this->icon_url ) ? $this->icon_url : '';
 	}
 
+	/**
+	 * Returns icon to use on dark themes.
+	 *
```
Comment (brettshumaker) [inline includes/payment-methods/class-upe-payment-method.php:253]: PHP linter wants a doc comment for the `$account_country` param.

**Review by brettshumaker — CHANGES_REQUESTED** [review]
This all seems to be working well for me. I see the updated images and the dark/light mode affirm logos are changing like they should.

Left a few notes on the PHP linter being unhappy.

File: client/checkout/upe-styles/index.js [hunk 4]
```diff
@@ -21,18 +28,33 @@ const appearanceSelectors = {
...
+			'form.checkout',
+			'body',
+		],
 	},
 	blocksCheckout: {
 		appendTarget: '#billing.wc-block-components-address-form',
 		upeThemeInputSelector: '#billing-first_name',
-		upeThemeLabelSelector: '.wc-block-components-text-input label',
+		upeThemeLabelSelector:
+			'.wc-block-components-checkout-step__description',
```
Comment (FangedParakeet) [inline client/checkout/upe-styles/index.js:44]: This computes label styles from the description text (green) instead of the inset label text (red), which stands out better on the page background

Checkout label style basis
_Red old, green new_

File: client/checkout/upe-styles/index.js [hunk 5]
```diff
@@ -234,27 +257,23 @@ const hiddenElementsForUPE = {
...
 	if ( ! document.querySelector( selector ) ) {
 		return {};
 	}
 
 	const validProperties = upeRestrictedProperties[ upeElement ];
 
 	const elem = document.querySelector( selector );
-	if ( focus ) {
-		elem.focus();
-	}
```
Comment (FangedParakeet) [inline client/checkout/upe-styles/index.js:247]: This caused the page to jump upwards to the hidden input on the blocks checkout when the focus state is triggered. I found that the computed styles for the focus state were not tremendously significant, so I removed them entirely. We can depend on Stripe's defaults for the focus state instead. 🤷

File: client/checkout/upe-styles/index.js [hunk 6]
```diff
@@ -234,27 +257,23 @@ const hiddenElementsForUPE = {
...
 
 	const filteredStyles = {};
-
 	for ( let i = 0; i < styles.length; i++ ) {
 		const camelCase = dashedToCamelCase( styles[ i ] );
 		if ( validProperties.includes( camelCase ) ) {
-			filteredStyles[ camelCase ] = styles.getPropertyValue(
-				styles[ i ]
+			filteredStyles[ camelCase ] = maybeConvertRGBAtoRGB(
+				styles.getPropertyValue( styles[ i ] )
```
Comment (FangedParakeet) [inline client/checkout/upe-styles/index.js:283]: AFAICT, Stripe only allows `rgba` colours with transparency for border outlines; otherwise the appearances API will ignore them and present a warning in the console.

File: client/checkout/upe-styles/upe-styles.js [hunk 7]
```diff
@@ -72,6 +72,10 @@ const upeSupportedProperties = {
 	],
 	'.TabIcon': [ ...paddingColorProps ],
 	'.TabLabel': [ ...paddingColorProps, ...textFontTransitionProps ],
+	'.Block': [
+		...paddingColorProps.slice( 1 ), // Remove color
+		...borderOutlineBackgroundProps.slice( 1 ), // Remove backgroundColor
```
Comment (FangedParakeet) [inline client/checkout/upe-styles/upe-styles.js:77]: `color` and `backgroundColor` are not supported for the `.Block` element.

File: includes/class-wc-payments-checkout.php (hunk 1 above)
Comment (FangedParakeet) [reply includes/class-wc-payments-checkout.php]: These should be fixed now. For some reason, the PHP linter isn't flashing on my local editor. 😠 Ma b.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 2 above)
Comment (FangedParakeet) [reply includes/class-wc-payment-gateway-wcpay.php:3931]: This should also be resolved now after a merge. 👍

File: includes/payment-methods/class-upe-payment-method.php (hunk 3 above)
Comment (FangedParakeet) [reply includes/payment-methods/class-upe-payment-method.php:253]: Fixed in e69f2320c4fc7effb4ebba2cab5fbd442b0d96a5. 👍

File: client/checkout/upe-styles/index.js [hunk 8]
```diff
@@ -348,12 +362,31 @@ export const getAppearance = ( isBlocksCheckout = false ) => {
...
 	};
 
+	const blockRules = getFieldStyles(
+		selectors.upeThemeLabelSelector,
+		'.Block'
+	);
+	blockRules.backgroundColor = 'none';
+
+	const globalRules = {
+		colorBackground: 'none',
```
Comment (FangedParakeet) [inline client/checkout/upe-styles/index.js]: These fields will actually throw a warning in the console stating the following...

> [Stripe.js] stripe.elements(): invalid variable value "none" provided to "colorBackground"; "colorBackground" accepts a valid HEX, rgb(), or hsl() CSS color.

...but despite this it still works and I cannot figure out another way to tell Stripe that I don't want any background colour.

If you set any colour to this value, then payment elements for methods like Affirm and giropay will have a coloured box around them, which we do not want. You cannot set a transparent colour and my own function, `getBackgroundColor`, is not reliable enough to _always_ find the exact colour background for the payment method container. 

Ignoring this parameter entirely will also incur a coloured box background, since Stripe will use its default value instead, which looks particularly unattractive on the `night` theme.

Block background colour box
_See this stupid faint grey box that I never want to see again_

File: client/checkout/upe-styles/utils.js [hunk 9]
```diff
@@ -90,3 +89,64 @@ export const generateOutlineStyle = (
...
+};
+
+/**
+ * Determines whether background color is light or dark.
+ *
+ * @param {string} color CSS color value.
+ * @return {boolean} True, if background is light; false, if background is dark.
+ */
+export const isColorLight = ( color ) => {
+	return tinycolor( color ).getBrightness() > 125;
```
Comment (FangedParakeet) [inline client/checkout/upe-styles/utils.js:151]: I just noticed that we are already importing this `tinycolor` library at the top of this file, with a [`getBrightness` function](https://www.npmjs.com/package/tinycolor2#getbrightness) that appears to use [the same equation](https://www.w3.org/TR/AERT/#color-contrast) that I was manually performing prior. Reduced the value to check from 127.5 to 125, since [here](https://www.w3.org/TR/AERT/#color-contrast) it is stated...

> The rage[sic.] for color brightness difference is 125. The range for color difference is 500.

File: client/checkout/upe-styles/index.js [hunk 10]
```diff
@@ -366,7 +370,6 @@ export const getAppearance = ( isBlocksCheckout = false ) => {
 		selectors.upeThemeLabelSelector,
 		'.Block'
 	);
-	blockRules.backgroundColor = 'none';
 
 	const globalRules = {
 		colorBackground: 'none',
```
Comment (brettshumaker) [inline client/checkout/upe-styles/index.js]: I think we still need to remove this as I'm still getting console warnings about this invalid value.

Comment (FangedParakeet) [reply client/checkout/upe-styles/index.js]: Removed this and replaced it with my own trusty `getBackgroundColor` function reinforced with some additional background selectors. This is now working consistently for me with no console warnings, no timeouts, and no blursed boxes. 🙌

**Review by brettshumaker — APPROVED** [review]
Thanks for all the back and forth on this one. I think we've arrived at a pretty solid solution. 👍
