### PR TITLE
Prevent exceptions from WC_Payments_Account::get_cached_account_data

### LINKED ISSUE #551: WCPay UI disappears entirely when account info can't be fetched
"Payments" appears not to show up in the sidebar nav at all if account is connected but account information can't be fetched.

Tested by disconnecting WCPay server and clearing account cache via WCPay Dev Tools. (It shows up again if forcing disconnected state.)

Is there a better way we can treat this case, at least with an error message on the Payments screen perhaps?

### LINKED ISSUE #1162: WC_Payments_Account->get_fees call crashes wp-admin upon install
When clicking 'activate' on WooCommerce Payments in the 'plugins' -> 'installed' portion of the CMS, it crashes the entire CMS immediately.  Afterward the entire CMS shows the error message below, making the site useless until I ftp in and manually sudo -r rm the plugin directory.   I'm not sure why this is even loaded on the basic wp-admin page, causing and error but it is. 

```
Error message: 
Fatal error: Uncaught WCPay\Exceptions\API_Exception: Error: Sorry, you cannot access this resource. in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php:992 Stack trace: #0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php(894): WC_Payments_API_Client->extract_response_body(Array) #1 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php(620): WC_Payments_API_Client->request(Array, 'accounts', 'GET') #2 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-account.php(532): WC_Payments_API_Client->get_account_data() #3 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-account.php(186): WC_Payments_Account->get_cached_account_data() #4 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugin in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php on line 992
```

Code causing the expection:
includes/class-wc-payments-account.php line 186

```
/**
	 * Gets the current account fees for rendering on the settings page.
	 *
	 * @return array        Fees.
	 * @throws API_Exception Bubbles up from get_cached_account_data.
	 */
	public function get_fees() {
		$account = $this->get_cached_account_data();
		return isset( $account['fees'] ) ? $account['fees'] : [];
	}
```
Updates on workarounds tried:
1. I've upgraded wordpress and all plugins:
    a. WooCommerce: 4.8.0
    b. WooCommerce Shipping & Tax: 1.25.4
    c. Wordpress: 5.6

2. I've also done the DB updates for WooCommerce and Wordpress.
3. I've added the tag `define( 'WP_ENVIRONMENT_TYPE', 'staging' );` to my wp-config.php

Still no change.

### PR DESCRIPTION
**Pull request by vbelolapotkov**
Fixes #551 
Fixes #1162 

#### Changes proposed in this Pull Request

* Update `get_cached_account_data` to prevent throwing exceptions and return explicit `false` when there are issues with fetching data from the server.
* Update `get_cached_account_data` usage to accommodate changes.

#### Testing instructions

Changes need to be tested in two modes.

1. When server works correctly. Need to check that plugin works as expected especially for the following flows:

* Redirects to connect page when there is no account.
* Onboarding / connecting new account.

2. When server connection is broken (use instructions from #1129 to break the server):

On master the site blows up.
On this branch:

* Before clearing cache account status should appear on settings page.
* After clearing cache:
* `Payments` menus should remain in the sidebar.
* Settings page should display error for account status.
* Checkout should not offer WC Pay as payment method.

-------------------

- [ ] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/class-wc-payments-account.php [hunk 1]
```diff
@@ -182,8 +182,12 @@ public function get_statement_descriptor() {
 	 * @throws API_Exception Bubbles up from get_cached_account_data.
```
Comment (luizreis) [inline includes/class-wc-payments-account.php:182]: Should we remove this comment now that an API_Exception won't bubble up?

**Review by luizreis — APPROVED** [review]
Works well, great catch! I left a nitpicky comment on the doc comments for that function, but I'm already approving the PR. We can :shipit: once that's resolved 🚀

File: includes/class-wc-payments-account.php (hunk 1 above)
Comment (vbelolapotkov) [reply includes/class-wc-payments-account.php:182]: Hm, that comment makes me think whether we should catch this or not. And quick search revealed some other places where `get_cached_account_data` not wrapped 🤔

@luizreis how do you think, should we wrap them as well? If so, could you please finish it because I'm at the end of shift today and AFK tomorrow?

File: includes/class-wc-payments-account.php [hunk 2]
```diff
@@ -182,8 +182,12 @@ public function get_statement_descriptor() {
...
 	 */
 	public function get_fees() {
-		$account = $this->get_cached_account_data();
-		return isset( $account['fees'] ) ? $account['fees'] : [];
+		try {
+			$account = $this->get_cached_account_data();
+			return isset( $account['fees'] ) ? $account['fees'] : [];
+		} catch ( API_Exception $e ) {
```
Comment (kalessil) [inline includes/class-wc-payments-account.php:188]: What do you think about adding a log entry for this case?

File: includes/class-wc-payments-account.php (hunk 1 above)
Comment (luizreis) [reply includes/class-wc-payments-account.php:182]: I think the issue with this call is that it's used when localizing a script, so even if the gateway is not initialized properly it would throw the error and crash the entire site. Do you think it makes sense to catch it at the moment it's used instead of inside the function?

Comment (vbelolapotkov) [reply includes/class-wc-payments-account.php:182]: That's a fair point. I have a solution which will fix #551 as well :) Will ship today.

**Comment by vbelolapotkov** [comment]
The scope of this PR has changed and it touches some critical paths so more thorough review and testing is needed @luizreis, @DanReyLop could you please take a look or let me know if you don't have enough time for this one :) ?

File: includes/class-wc-payments-account.php [hunk 3]
```diff
@@ -551,7 +538,9 @@ private function get_cached_account_data() {
 				$account = [];
 				set_transient( self::ON_BOARDING_DISABLED_TRANSIENT, true, 2 * HOUR_IN_SECONDS );
 			} else {
-				throw $e;
+				// Failed to retrieve account data. Exception is logged in http client.
```
Comment (shendy-a8c) [inline includes/class-wc-payments-account.php:541]: Is it OK not to log exception here?

**Review by shendy-a8c — COMMENTED** [review]
I see there might be unexpected changed behaviour by [this line of code](https://github.com/Automattic/woocommerce-payments/blob/fix/get-fees-exception/includes/class-wc-payments-customer-service.php#L313).

On master, when wcpay server is not reachable, this line will get bubbled up uncaught exception from `get_is_live()`.
On this branch, `$account_is_live` will be true.

I'm not sure what `maybe_migrate_deprecated_customer()` does exactly and if when wcpay server is not reachable, `$account_is_live` is fine to be true.

There are changed behaviour here too:
- [handle_tos_accepted() threw exception and now it doesn't](https://github.com/Automattic/woocommerce-payments/blob/fix/get-fees-exception/includes/admin/class-wc-rest-payments-tos-controller.php#L132)
- [webhook handler threw exception and now it doesn't](https://github.com/Automattic/woocommerce-payments/blob/fix/get-fees-exception/includes/admin/class-wc-rest-payments-webhook-controller.php#L118)

**Comment by DanReyLop** [comment]
> I'm not sure what maybe_migrate_deprecated_customer() does exactly and if when wcpay server is not reachable, $account_is_live is fine to be true.

It's fine. As the comment in `maybe_migrate_deprecated_customer` says, it's better to assume the account is live. Worst-case-scenario: your account is test-only, and there are customer objects still using the legacy ID key. If the server is unreachable, then the customer IDs will be set as "live". They won't work, but in this scenario you're using a test-only WCPay account, so you're probably a developer/builder, so those "customers" will probably be dummy test users. No big deal.

> handle_tos_accepted() threw exception and now it doesn't
> webhook handler threw exception and now it doesn't

The main thing `refresh_account_data` does is remove the transient (thus forcing the account data to be re-fecthed from the server). The fact that it also immediately refetches the account data is just an optimization. It's fine if it fails silently. It's much better than a site crash :)

**Review by DanReyLop — APPROVED** [review]
This is definitely an improvement and should go into the next release, no question.

I found during my testing that, if I make the server blow up, loading the Settings page triggers 10 HTTP requests to the server. That adds up. What do you think about adding a flag or something so `get_cached_account_data` doesn't try to reach the server multiple times in the same request, at the very least?

^^ That's not a deal-breaker, and can definitely be implemented in a future PR. This PR is ready to ship.

**Comment by vbelolapotkov** [comment]
Thanks for reviewing it @DanReyLop !

> I found during my testing that, if I make the server blow up, loading the Settings page triggers 10 HTTP requests to the server. That adds up. What do you think about adding a flag or something so get_cached_account_data doesn't try to reach the server multiple times in the same request, at the very least?

That's a great point! Created https://github.com/Automattic/woocommerce-payments/issues/1164 for this.

File: includes/class-wc-payments-account.php (hunk 3 above)
Comment (vbelolapotkov) [reply includes/class-wc-payments-account.php:541]: Yes, it is. As the comment says the exception is already logged in other place :)

Comment (shendy-a8c) [reply includes/class-wc-payments-account.php:541]: OMG. I miss that comment big time.
