### PR TITLE
Fix syntax for advanced filters in WC 7.8 and over

### LINKED ISSUE #6533: Advanced filters throw an error
### Describe the bug

Clicking on Transactions > Advanced Filters results in unexpected response

### To Reproduce

1. Go to Payments > Transactions
2. Click on Advanced Filters

### Expected behavior

Advanced filters should work

### Desktop (please complete the following information):

* OS: MacOS 13,4
* Browser Firefox
* Version 115.0b4

### Additional context
[6409605-zen](6409605-zd-woothemes)

### PR DESCRIPTION
**Pull request by daquinons**
Fixes #6533 

#### Changes proposed in this Pull Request
This change allows Advanced Filters to be compatible with the newly introduced syntax in WC 7.8 https://github.com/woocommerce/woocommerce/pull/37967

It introduces a check for the WC version and picks the right format depending if WC is less than 7.8 or not, in order to make it backward compatible.

Because the string is part of the translation function, it needs to be literal, so more elegant approaches with string concatenation were not available for this.

**### Testing instructions**
- Install WooCommerce 7.8 or bigger
- Go to Transactions
- All the advanced filters should be functional and displayed without any error
- Go to Deposits
- All the advanced filters should be functional and displayed without any error
- Go to Disputes
- All the advanced filters should be functional and displayed without any error
- Go to Documents (enable it in Dev tools if not appearing)
- All the advanced filters should be functional and displayed without any error

- Install [WP Rollback](https://wordpress.org/plugins/wp-rollback/)
- Rollback WooCommerce to any version under 7.8 (7.7, for example)
- Go to Transactions
- All the advanced filters should be functional and displayed without any error
- Go to Deposits
- All the advanced filters should be functional and displayed without any error
- Go to Disputes
- All the advanced filters should be functional and displayed without any error
- Go to Documents (enable it in Dev tools if not appearing)
- All the advanced filters should be functional and displayed without any error

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6617` or branch name `hotfix/6533-advanced-filters-error` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=hotfix/6533-advanced-filters-error) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 86b3b9b2c84b2579924fbc8824757323fa6b7e4c
- Build time: 2023-06-29 09:43:33 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/transactions/filters/config.ts [hunk 1]
```diff
@@ -125,12 +126,22 @@ export const getFilters = (
 export const getAdvancedFilters = (
 	customerCurrencyOptions?: TransactionsFilterEntryType[]
 ): any => {
+	// TODO: Remove this and all the checks once we drop support of WooCommerce 7.7 and below.
+	const wooCommerceVersionString = getSetting( 'wcVersion' );
```
Comment (naman03malhotra) [inline client/transactions/filters/config.ts:130]: Will this, in any case, will return `null` or `undefined`?

Comment (daquinons) [reply client/transactions/filters/config.ts:130]: I don't think WCPay can run without WC installed, so I don't think so :) Still, this is a temporary solution that we'll be able to drop once we drop support for 7.7

**Review by dmallory42 — APPROVED** [review]
LGTM, works as expected on both WC7.8 and older versions.

We should make a follow up issue to look into handling this in a more generic way in future and to update the tests (because I used a slightly hacky fix to get them working). 

The only other thing is the changelog should be updated before merging.

Thanks for working on this!
