### PR TITLE
Fix for E2E error caused by analytics updates

### LINKED ISSUE #4478: Installing & activating the latest develop on a new store throws JS errors
### Describe the bug
On a new store, when the latest `develop` version of WooCommerce Payments is installed & activated, the following JS error is displayed while accessing WooCommerce Settings page. This also caused the recent E2E tests to fail since 19 July, 2022.

Screenshot

The error seems to be a regression from https://github.com/Automattic/woocommerce-payments/pull/4441 and @dmallory42 is looking into it.

### To Reproduce
1. Setup a new test site with WooCommerce.
2. Build a new release of WooCommerce Payments from `develop` branch.
3. Upload the created release & activate it.
4. Go to WooCommerce -> Settings and notice the error message shared above on browser console.

### PR DESCRIPTION
**Pull request by dmallory42**
Fixes #4478 

#### Changes proposed in this Pull Request

- Fix for an error occurring on the settings page introduced in #4441.

#### Testing instructions

- Go to `WooCommerce > Settings` and verify there are no console errors and the page works as expected.
- Go to `Analytics > Orders`, change the `Show` dropdown to `Advanced filters` and add the `Customer Currency` advanced filter. Check that the list is populated (it should contain any customer currencies ever used on your store to complete an order.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: changelog/fix-e2e-analytics [hunk 1]
```diff
@@ -0,0 +1,5 @@
+Significance: patch
+Type: dev
+Comment: Fix only relates to E2E tests.
```
Comment (achyuthajoy) [inline changelog/fix-e2e-analytics:3]: @dmallory42 Just noting that this is not exactly a fix for failing E2E tests. As the issue mentioned, it's present on a new WooCommerce store with the latest `develop` of WooCommerce Payments, even without on-boarding.

File: client/multi-currency-analytics/index.js [hunk 2]
```diff
@@ -5,9 +5,13 @@
...
 import { __ } from '@wordpress/i18n';
 
-const customerCurrencies = wcSettings.customerCurrencies.sort( ( a, b ) => {
-	return a.label < b.label ? -1 : 1;
-} );
+const getCustomerCurrencies = () => {
+	return (
+		wcSettings.customerCurrencies.sort( ( a, b ) => {
+			return a.label < b.label ? -1 : 1;
+		} ) ?? []
```
Comment (achyuthajoy) [inline client/multi-currency-analytics/index.js:12]: @dmallory42 I've tried testing the PR on my JN test site and encountered the following (not sure whether it's related to the current change).

1. Created 2 orders on the test site, one with USD & the other with EURO.
2. Under Analytics -> Orders, I am able to see both the orders with the correct currency
3. Under Advanced Filters -> Customer currency, I'm not seeing the option to choose a currency. Could be related to passing an empty array here?

Screenshot

**Review by achyuthajoy — COMMENTED** [review]
@dmallory42 I've left a couple of comments. Let me know if you have any questions :)

File: client/multi-currency-analytics/index.js (hunk 2 above)
Comment (dmallory42) [reply client/multi-currency-analytics/index.js:12]: This could be related to catching - there can be a short delay (5 mins) between a currency being used for the first time and displaying in the analytics section. Could you check again to ensure this isn't the case here?

I will also update the logic so the store default currency is always on the list even when no orders have been made on the store, since this feels a bit more like the expected behaviour.

File: changelog/fix-e2e-analytics (hunk 1 above)
Comment (dmallory42) [reply changelog/fix-e2e-analytics:3]: Good point. I didn't mention the error because thankfully the E2E tests caught it before it was released, so it was never customer-facing. However I can add it to the changelog if you think it is still worth mentioning?

Comment (achyuthajoy) [reply changelog/fix-e2e-analytics:3]: I think it's worth mentioning because devs can quickly check what the change is about :)

File: client/multi-currency-analytics/index.js (hunk 2 above)
Comment (achyuthajoy) [reply client/multi-currency-analytics/index.js:12]: Yeah, it was caching. I am able to see the currency drop-down now.

Comment (dmallory42) [reply client/multi-currency-analytics/index.js:12]: Awesome, good to know. 👍

File: changelog/fix-e2e-analytics (hunk 1 above)
Comment (dmallory42) [reply changelog/fix-e2e-analytics]: Updated in b1351fba. :)

File: client/multi-currency-analytics/index.js (hunk 2 above)
Comment (dmallory42) [reply client/multi-currency-analytics/index.js:12]: Created a follow-up issue to always show the default currency: https://github.com/Automattic/woocommerce-payments/issues/4479 🙂

**Review by achyuthajoy — APPROVED** [review]
@dmallory42 Changes look good to me 🚢 

Can confirm that the console error doesn't appear anymore. However, E2E tests are failing since WC test versions needs to be updated. I'll be adding a PR for that shortly.

And thanks for your quick work on this.
