### PR TITLE
Fix React error when the Express Checkout's container element is not found.

### LINKED ISSUE #9419: Express Checkout Block not working with WooPayments 8.2.0
When using the Express Checkout Block in a Template, customers do not see Apple Pay or Google Pay on the Cart or Checkout pages.

Signing in as an Admin shows the following error on the checkout page instead of the Express Checkout options:

> There was an error registering the payment method with id 'woocommerce_payments_express_checkout': Error: Minified React error #299; visit https://reactjs.org/docs/error-decoder.html?invariant=299 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Markup 2024-09-11 at 16 20 52

----

If you replace the Checkout Blocks in the Template with the `[woocommerce_checkout]` shortcode, the Express Checkout buttons work as expected, so it appears to be something very specific to the Express Checkout Block.

Markup 2024-09-11 at 16 25 42

----

Internal conversation: p1726089909689609/1726089797.882259-slack-CGGCLBN58

### PR DESCRIPTION
**Pull request by asumaran**
Fixes https://github.com/Automattic/woocommerce-payments/issues/9419

### Changes proposed in this Pull Request

Since the `the_content` filter is never triggered when the checkout page is assigned a block-based template, the elements we were printing as containers for the buttons used to check the availability of ApplePay/GooglePay payment methods were not rendered. As a result, React failed to mount the button because the containers didn’t exist.

We’re changing the approach by creating the container dynamically and appending it to the page using JavaScript. This ensures the buttons are rendered in both cases, whether using a standard theme or a block-based theme.

### Why is it happening?

When a page uses a block-based template, it includes the `template-canvas.php` file as base ([ref](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/template-canvas.php)), which prints the HTML generated from the block template. Notably, this file never calls `the_content()`. (This the [block template](https://gist.github.com/asumaran/c2880283978339421d43800ede07a50d) the site that reported the issue was using). – As side note, @reykjalin' [fix](https://github.com/Automattic/woocommerce-payments/pull/9424) works because this file [do call](https://github.com/WordPress/wordpress-develop/blob/47122105f20624e5a6b8ed151d732157f2f2605c/src/wp-includes/template-canvas.php#L25) `wp_footer()`, which applies the `wp_footer` action ([ref](https://github.com/WordPress/wordpress-develop/blob/47122105f20624e5a6b8ed151d732157f2f2605c/src/wp-includes/general-template.php#L3080)).

However, when using a regular theme, the checkout block is rendered as part of the page content. In themes, the page content is printed using `the_content()` ([ref](https://developer.wordpress.org/reference/functions/the_content/)), which applies the `the_content` filter ([ref](https://github.com/WordPress/wordpress-develop/blob/47122105f20624e5a6b8ed151d732157f2f2605c/src/wp-includes/post-template.php#L256)).

Unfortunately, to render the elements that would be used as containers for the buttons used to check the availability of payment methods, this `the_content` filter was used, which is not always called. We should have used the `wp_footer` action or perhaps used JS to create the element.

### Testing instructions

**To reproduce the bug**

* **Log in as as admin** – The error is shown only for admins.
* Switch to the `develop` branch.
* Install the following theme [what-theme.zip](https://github.com/user-attachments/files/16981278/what-theme.zip)
* Create a shortcode-based checkout page if you don't have one already
  * Add the "Classic Checkout" block or add the `[woocommerce_checkout]` using the shortcode block.
  * Assign the `page-checkout` template to it.
* Go to store and add a product to the cart.
* Go to the newly created page.
* ❌ You'll observe the React error.

**To confirm the fix**
- Switch to this branch `as-fix-react-error-container-not-found`
- Repeat the previous steps.
- There shouldn't be any error displayed.
- ✅ Express Checkout buttons should be displayed.
- Log out from the store.
- Refresh the Checkout page.
- ✅ Express Checkout buttons should be displayed.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9420` or branch name `as-fix-react-error-container-not-found` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=as-fix-react-error-container-not-found) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b158cc56aee57e1fe81ab9c6911795ada20c4396
- Build time: 2024-09-12 21:23:09 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js [hunk 1]
```diff
@@ -15,11 +15,11 @@ import { getUPEConfig } from 'wcpay/utils/checkout';
...
 export const checkPaymentMethodIsAvailable = memoize(
 	( paymentMethod, cart, resolve ) => {
-		const root = ReactDOM.createRoot(
-			document.getElementById(
-				`express-checkout-check-availability-container-${ paymentMethod }`
-			)
-		);
+		// Create the DIV container on the fly
+		const containerlEl = document.createElement( 'div' );
+		document.querySelector( 'body' ).appendChild( containerlEl );
```
Comment (reykjalin) [inline client/express-checkout/utils/checkPaymentMethodIsAvailable.js]: If we're going to create the div like this we may want to add some attributes to it that make it invisible, especially for screen readers.

Probably something like

```js
containerEl.style.opacity = 0;
containerEl.style.height = 0;
conatinerEl.ariaHidden = true;
```

That's roughly similar to the previous approach of setting the opacity and height to 0, although that approach does not set the aria-hidden attribute.

Comment (asumaran) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js]: Yes I agree, CSS Styles were added here [f62431b](https://github.com/Automattic/woocommerce-payments/pull/9420/commits/f62431bf4c8a98b0a9431681241f4a120c0da7aa)

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js [hunk 2]
```diff
@@ -15,11 +15,24 @@ import { getUPEConfig } from 'wcpay/utils/checkout';
 
 export const checkPaymentMethodIsAvailable = memoize(
 	( paymentMethod, cart, resolve ) => {
-		const root = ReactDOM.createRoot(
-			document.getElementById(
-				`express-checkout-check-availability-container-${ paymentMethod }`
-			)
-		);
+		// Create the DIV container on the fly
+		const containerlEl = document.createElement( 'div' );
```
Comment (bborman22) [inline client/express-checkout/utils/checkPaymentMethodIsAvailable.js]: One minor fix here on the spelling, I believe should be `containerEl` (no extra l between container and El).

**Review by bborman22 — APPROVED** [review]
I've tested this fix with the original Blocks Canvas theme provided over Slack, the Tsubaki theme, the provided What Theme, and Storefront. I tested these on Chrome, Safari, and Firefox (to confirm that the Express Checkout box gets properly hidden still). And I checked on product, cart, and checkout pages. I didn't see any issues in my testing and confirmed both CC, GPay, and Apple Pay all worked to complete the checkout. I'll note that all this testing happened on a JN site as well.

I had one small note about spelling and **I'd like to get at least one other approval** and review on both this approach and confirmation of it working as expected across different environments.

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js (hunk 2 above)
Comment (asumaran) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js]: done [c564b30](https://github.com/Automattic/woocommerce-payments/pull/9420/commits/c564b30d69abb7a2d62e5e5b9996fa1d49e05676)

**Comment by pierorocca** [comment]
@senadir @alexflorisca @ralucaStan tagging you all for awareness in case this scenario comes up with other 3P gateways that are implementing express checkout buttons. Please feel free to sanity check this solution. Thank you.

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js [hunk 3]
```diff
@@ -15,11 +15,24 @@ import { getUPEConfig } from 'wcpay/utils/checkout';
...
+		containerEl.style.padding = '0';
+		containerEl.style.position = 'absolute';
+		containerEl.style.width = '0';
+		containerEl.style.float = 'left';
+		containerEl.style.opacity = '0';
+		containerEl.style.pointerEvents = 'none';
+
+		document.querySelector( 'body' ).appendChild( containerEl );
+
+		const root = ReactDOM.createRoot( containerEl );
```
Comment (ricardo) [inline client/express-checkout/utils/checkPaymentMethodIsAvailable.js]: I also tested this with only:

```js
containerEl.style.display = 'none';
```

And it worked as expected. With `display: none`, the element shouldn't have any pointer events and shouldn't take up any space.

We might not need to keep the element technically visible by setting other properties to `0`, but perhaps I could be missing something?

The current approach also LGTM, the only downside is that it's slightly more complex and the element is still "visible" in the DOM, including for assistive technologies, although temporarily.

cc @bborman22

**Review by ricardo — APPROVED** [review]
@asumaran we should probably rebase this PR from `trunk` so it's easier for the release DRI to include in the patch release.

Review: Tested this in Safari and Chrome with Storefront, What Theme and Block Canvas.

- ✅ Reproduced the bug:

Bug

- ✅ Confirmed the fix:

Fix

Fix

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js (hunk 3 above)
Comment (asumaran) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js]: I guess it doesn't matter if the button doesn't end up rendering as long as we have the `onReady` event to be called with the info we need.

Comment (bborman22) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js]: > the only downside is that it's slightly more complex and the element is still "visible" in the DOM, including for assistive technologies

Great catch! I missed the `ariaHidden` not being set. I think at a minimum that should be set. Display none is certainly simpler, just wondering if there are some gotchas there as we don't use it in other places we create a hidden div? [ref1](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/upe-styles/index.js#L219) [ref2](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/woopay/connect/woopay-connect-iframe.js#L72) with the second ref using an iframe as one possible explanation.

Comment (ricardo) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js]: I believe it would depend mostly on Stripe, e.g. if it checks for any layout measurements of the root element, or if the contents are technically visible.

Both approaches seem to work though, so I don't have a strong preference, but I agree with @bborman22 we should probably set `containerEl.setAttribute( 'aria-hidden', 'true' );` if not using `display: none`.

Comment (asumaran) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js]: I've updated the PR with the suggestion. [70191f7](https://github.com/Automattic/woocommerce-payments/pull/9420/commits/70191f780d294900cbf3cc0acf9169f1aca44717) – I've tested with regular and block-based theme. With Safari, Google Chrome, and Firefox.

**Review by bborman22 — APPROVED** [review]
I ran through a similar set of tests as before and found no issues with the display none approach! I also gave some additional testing to the shortcode checkout as well with no issues.

LGTM! Again just want to get two approvals on this with the new approach as well.

**Review by ricardo — APPROVED** [review]
LGTM and tests well.

I also ran through a similar set of tests and the button worked as expected.
