### PR TITLE
fix: attribute selection from PDPs with tokenized ECE

### LINKED ISSUE #10303: Tokenized ECE not able to parse selected variation w/ "Variation Swatches for WooCommerce"
### Describe the bug

Internally reported here: p1738743947909059/1738707211.859139-slack-CGGCLBN58

[The "Variation Swatches for WooCommerce" plugin](https://wordpress.org/plugins/woo-variation-swatches/) alters the site's markup for the variations, causing the ECE to not be able to parse the selected variation on a product page.

This causes a Store API `add-to-cart` call made with incorrect values causing it to fail with `woocommerce_rest_variation_id_from_variation_data`, preventing the product from being able to check out within the scope of the ECE dialog.

Image

The product can still be added to the cart via the "Add to cart" button.

ECE on cart & checkout pages remains unaffected.

### To Reproduce

- Install the plugin
- Ensure you have GooglePay/ApplePay enabled
- Click on the GooglePay/ApplePay button
- Observe the `add-to-cart` call result

### Expected behavior

Product pages using "Variation Swatches for WooCommerce" can still add the product to the cart.

### PR DESCRIPTION
**Pull request by frosso**
Fixes https://github.com/Automattic/woocommerce-payments/issues/10303

#### Changes proposed in this Pull Request

Plugins like ["Variation Swatches for WooCommerce"](https://wordpress.org/plugins/woo-variation-swatches/) might alter the page's HTML structure, causing the ECE to not be able to parse the selected variation on a product page.

When such thing occurs, the `POST cart/add-item` call fails to get the product prices when the all the product variation attributes are selected.
Screenshot 2025-02-05 at 9 23 54 AM

#### Testing instructions

- Ensure you have GooglePay/ApplePay enabled in your WooPayments settings
- Ensure you have the "Enable Cart-Token implementation for ECE" flag enabled in your WCPay Dev settings
- Create a variable product with at least one variable attribute
- Go to the product page
- Select the variable attributes
- Click on the GooglePay/ApplePay button, and the dialog appears
- No errors should occur - you should also be able to check out

Repeat the above steps with the ["Variation Swatches for WooCommerce"](https://wordpress.org/plugins/woo-variation-swatches/) plugin.
Repeat the above steps with [these changes](https://github.com/woocommerce/woocommerce/pull/55317/files) to your local `wp-content/plugins/woocommerce/src/StoreApi/Utilities/CartController.php` file.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10306` or branch name `fix/tokenized-ece-attribute-selection` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/tokenized-ece-attribute-selection) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: d555708e778552ed5de8729295c019cee3226fd7
- Build time: 2025-02-13 15:35:55 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/tokenized-express-checkout/compatibility/wc-product-page.js [hunk 1]
```diff
@@ -37,14 +37,16 @@ addFilter(
 	'wcpay.express-checkout.cart-add-item',
 	'automattic/wcpay/express-checkout',
 	( productData ) => {
-		const $variationInformation = jQuery( '.single_variation_wrap' );
-		if ( ! $variationInformation.length ) {
+		const variationInformation = document.querySelector(
```
Comment (frosso) [inline client/tokenized-express-checkout/compatibility/wc-product-page.js:40]: I moved away from the jQuery selectors and switched to vanilla JS selectors, so that testing would be more reliable and easier (without having to mock jQuery)

**Review by brettshumaker — APPROVED** [review]
This tests well for me and I was able to use tokenized ECE to checkout with a variable product with special characters in the attribute and value. I also appreciate the jquery conversion 🙏 

👍
