### PR TITLE
Fix duplicate account onboarding requests

### LINKED ISSUE #2825: Prevent duplicate requests to onboarding init
### Describe the bug

I'm not quite sure how this is being reproduced in production, but a few users are being able to perform multiple requests to `onboarding/init`, which is causing a notice in the server where there's either account ID mismatch when redirected back from onboarding, or there's an idempotency key error.

The appears to happen rarely, so I suppose this has to do with a different client behavior from different entry points to the onboarding endpoint.

### Expected behavior

We should not allow concurrent requests originated from the same client to the onboarding endpoint.

### PR DESCRIPTION
**Pull request by ricardo**
Fixes #2825

#### Changes proposed in this Pull Request

Disabling the "Finish setup" button isn't enough to prevent multiple onboarding requests, as we've been seeing in production (1143-gh-Automattic/woocommerce-payments-server).

This PR adds a quickly expiring transient to create an "onboarding started" state and avoid simultaneous onboarding requests.

A different approach of switching the onboarding request from `GET` to `POST` was considered, but we wouldn't be able to redirect from Jetpack to Stripe's KYC directly without the user triggering another `POST`. Unless we need to submit other data from the onboarding page to Stripe's KYC, I think the transient approach is better for the time being.

#### Testing instructions

1. Make sure you're not onboarded in WCPay.
2. In the onboarding page, open the "Finish setup" link in a new tab and then click it in the current tab.
3. Notice you can't get redirected more than once in 10 seconds.

-------------------

- [x] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/class-wc-payments-account.php [hunk 1]
```diff
@@ -539,6 +540,16 @@ private function get_oauth_return_url( $wcpay_connect_from ) {
 	 * @param string $wcpay_connect_from - where the user should be returned to after connecting.
 	 */
 	private function init_stripe_oauth( $wcpay_connect_from ) {
+		if ( get_transient( self::ON_BOARDING_STARTED_TRANSIENT ) ) {
+			$this->redirect_to_onboarding_page(
+				__( 'There was a duplicate attempt to redirect you to Stripe. Please wait a few seconds and try again.', 'woocommerce-payments' )
```
Comment (dechov) [inline includes/class-wc-payments-account.php:545]: We don't explicitly mention the redirect to Stripe before this, so we might want to just generalize that to "duplicate attempt to initiate account setup" or something like that.

**Review by dechov — COMMENTED** [review]
Nice & simple change makes sense and works well.

What do you think of deleting the transient after `get_oauth_data`, since we know at that point that it's safe to repeat the request? That way, we might not need to say "wait a few seconds" on a subsequent request since the first request is somewhat likely to have completed by then or very soon after (though I'm OK with leaving it if you prefer).

**Review by dechov — APPROVED** [review]
