### PR TITLE
Fix test mode notice to match Page width

### LINKED ISSUE #641: Test admin notice: Make it match the width of the content on the screen
New direction:

@dechov [discussed](https://github.com/Automattic/woocommerce-payments/issues/641#issuecomment-726456162) with @LevinMedia once more, and it sounds like the best would be if it stayed as it is now but matched the width of the page content below it. I expect we'll want to do that by rendering inside of <Page>. Marking it as Good First Issue since that makes it a much simpler change, depending on familiarity with React perhaps.

### PR DESCRIPTION
**Pull request by ricardo**
Fixes #641

#### Changes proposed in this Pull Request

* Refactor test notice into a regular component.
* Add test notice to all pages.
* Refactor test-mode-notice tests.

#### Testing instructions

* Make sure you have dev mode enabled.
* Navigate to the following pages, and check if the test notice matches the width of the content below it:
  * Payments > Deposits
  * Payments > Deposits > Deposit Details
  * Payments > Transactions
  * Payments > Transactions > Payment Details
  * Payments > Disputes
  * Payments > Disputes > Dispute Details
  * Payments > Disputes > Challenge Dispute

#### Screenshots

Before:

before

After:

after

-------------------

- [x] Covered with tests
- [x] Added changelog entry.

### CODE REVIEW

File: client/components/test-mode-notice/index.js [hunk 1]
```diff
@@ -98,38 +98,16 @@ export const getNoticeMessage = ( topic ) => {
...
 
-/**
- * Returns a Notice element with the appropriate message based on the topic provided.
- *
- * @param {string} topic The notice topic, also represents a page, e.g. 'transactions'.
- *
- * @returns {Notice} The notice element containing the appropriate message.
- */
-export const getNotice = ( topic ) => {
+export const TestNotice = ( { topic } ) => {
```
Comment (reykjalin) [inline client/components/test-mode-notice/index.js:101]: Let's call this `TestModeNotice`. I don't really expect we'll add another `TestXNotice`, but just let's be extra clear just in case: this is about test mode.

**Review by reykjalin — CHANGES_REQUESTED** [review]
Excellent work on this PR! 🥇 

As we've discussed I agree with your approach of removing the HOC; it would be unpleasant to use since we've now moved the call to the notice inside our `<Page>` components.

Let's just fix the unit tests to not use `withTestModeNotice` anymore and we should be all good to go! 👏 I expect there will be some tests you can simply remove since we're no longer testing a HOC, and instead just testing a plain component 🙂

**Comment by reykjalin** [comment]
Oh, I should also mention that this tests really well when browsing the pages; the notice looks good everywhere 👏

File: client/components/test-mode-notice/test/index.js [hunk 2]
```diff
@@ -92,89 +91,15 @@ describe( 'Test mode notification', () => {
...
-				className="wcpay-test-mode-notice"
-				status="warning"
-				isDismissible={ false }
-			>
-				{ getNoticeMessage( topic ) }
-			</Notice>
-		);
-
-		expect( getNotice( topic ) ).toStrictEqual( expected );
-	} );
```
Comment (reykjalin) [inline client/components/test-mode-notice/test/index.js:107]: I think we should keep this test; just set `isInTestMode` to return true via `isInTestMode.mockReturnValue( true )`.

In addition to that we should add a new test verifying that no notice is returned when `isInTestMode` returns `false`. Something along the lines of:

```js
isInTestMode.mockReturnValue( false );
expect( <TestModeNotice topic={ /* choose any topic here */ } /> ).toBeUndefined(); // .toBeNull() maybe?
```

File: client/components/test-mode-notice/test/index.js [hunk 3]
```diff
@@ -92,89 +91,15 @@ describe( 'Test mode notification', () => {
...
-
 	test.each( topicsWithTestMode )(
-		'Simple component is wrapped correctly',
+		'Component is rendered correctly according to test mode',
```
Comment (reykjalin) [inline client/components/test-mode-notice/test/index.js:95]: I think `Component is rendered correctly` is a better description here 🙂 . The "according to test mode" is implied in stating that the component renders correctly.

**Review by reykjalin — CHANGES_REQUESTED** [review]
Thank you for updating the tests!

I think we need to make a slight adjustment and add 1 new test (see comments), but otherwise this is looking great!

**Review by reykjalin — APPROVED** [review]
Looking good! Let's go ahead and merge 🎉 🚀
