### PR TITLE
Fix setting options on non-production environments

### LINKED ISSUE #6961: Custom options support was removed from non-production environments on WooCommerce 7.9.0+
### Describe the bug

We are using the deprecated `updateOptions` to update options directly from the client side, but due to [this change on WooCommerce](https://github.com/woocommerce/woocommerce/blob/a2adac35db93800f4c87d9531a9bb38d3c626e4e/plugins/woocommerce/src/Admin/API/Options.php#L111), it is no longer possible to use the `updateOptions` API as it returns false for non-production environments on WooCommerce 7.9.0+.

The lack of permissions breaks the functionalities that depend on that API, returning the following error when interacting with it:
```json
{
    "code": "woocommerce_rest_cannot_update",
    "message": "Sorry, you cannot manage these options.",
    "data": {
        "status": 403
    }
}
```

Example URL:  http://localhost:8082/wp-json/wc-admin/options?_locale=user

Here is the list of the files that use this API:
- [fraud-risk-tools-banner/index.tsx#L22](https://github.com/Automattic/woocommerce-payments/blob/develop/client/components/fraud-risk-tools-banner/index.tsx#L22)
- [additional-methods-setup/upe-preview-methods-selector/setup-complete-task.js#L78](https://github.com/Automattic/woocommerce-payments/blob/develop/client/additional-methods-setup/upe-preview-methods-selector/setup-complete-task.js#L78)
- [multi-currency-setup/tasks/setup-complete-task/index.js#L24](https://github.com/Automattic/woocommerce-payments/blob/develop/client/multi-currency-setup/tasks/setup-complete-task/index.js#L24)
- [overview/task-list/index.js#L19](https://github.com/Automattic/woocommerce-payments/blob/develop/client/overview/task-list/index.js#L19)
- [settings/fraud-protection/tour/index.tsx#L53](https://github.com/Automattic/woocommerce-payments/blob/develop/client/settings/fraud-protection/tour/index.tsx#L53)
- [payment-methods/capability-request/capability-request-notice.tsx#L118](https://github.com/Automattic/woocommerce-payments/blob/develop/client/payment-methods/capability-request/capability-request-notice.tsx#L118)

### To Reproduce

1. Upgrade WooCommerce to 7.9.0+
2. Open the developer console
3. Go to the **Payments** page on your test site (`/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Foverview`)
4. You should see some 403 errors
5. Click on the "Dismiss" button from the FRT Discoverability Banner

image

6. Refresh the page
7. The FRT Discoverability banner will be visible again due to this issue

### Expected behavior

- The FRT Discoverability Banner shouldn't be visible anymore after clicking on the "Dismiss" button

### Additional context

p1690987421187229-slack-C01B8KNUYSW

### PR DESCRIPTION
**Pull request by allie500**
Fixes #6961 

#### Changes proposed in this Pull Request

Custom options support was removed from non-production environments on WooCommerce 7.9.0+. As a result, when making POST requests to the Woo Core Options API via the `updateOptions` function on the frontend of a non-production environment, a 403 response was returned.

This PR fixes the issue by leveraging the [`woocommerce_rest_api_option_permissions` filter](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/API/Options.php#L149) available in the Options API. The PR includes all eight options currently used by frontend `updateOptions` calls in an array that is then merged with the Woo core permissions array via the aforementioned filter.

#### Testing instructions

* Check out this branch.
* All tests should pass.
* Make sure the following two options are deleted from your local client: 
  * `wcpay_frt_discover_banner_settings`
  * `wcpay_fraud_protection_welcome_tour_dismissed`
* Apply the following patch to dump the filtered Woo core option permissions array to `debug.log`: [pr7483.patch](https://github.com/Automattic/woocommerce-payments/files/13394632/pr7483.patch)
* Open your browser inspector and click on the Network tab.
* Navigate to Payments > Overview.
* In the browser inspector network tab look for a request to `options?_locale=user`.
  * The request should have a 200 response.
  * The request payload should be: `{"wcpay_frt_discover_banner_settings": "{\"dontShowAgain\":false}"}`
* Now check your local client's `debug.log` file. You should see the `$permissions` array in the file. Confirm that the following eight options are at the bottom of the array:
  * `wcpay_frt_discover_banner_settings`
  * `wcpay_multi_currency_setup_completed`
  * `woocommerce_dismissed_todo_tasks`
  * `woocommerce_remind_me_later_todo_tasks`
  * `woocommerce_deleted_todo_tasks`
  * `wcpay_fraud_protection_welcome_tour_dismissed`
  * `wcpay_capability_request_dismissed_notices`
  * `wcpay_onboarding_eligibility_modal_dismissed`
* Now, back on the Payments > Overview page, click the Learn More button on the _Enhanced fraud protection for your store_ banner.
* The site should redirect to the Payments > Settings page, then auto-scroll to the bottom of the page and show a welcome tour modal. Click the X in the top right corner to dismiss the modal. 
* Check the browser inspector network tab for a request to `options?_locale=user`.
  * The request should have a 200 response.
  * The request payload should be: `{"wcpay_fraud_protection_welcome_tour_dismissed": true}`
* Now navigate back to Payments > Overview, and click the Dismiss button on the _Enhanced fraud protection for your store_ banner.
* In the browser inspector network tab look for a request to `options?_locale=user`.
  * The request should have a 200 response.
  * The request payload should be: `{"wcpay_frt_discover_banner_settings": "{\"dontShowAgain\":true}"}`
* Lastly, visit the client site dashboard, then return to the Payments > Overview page. The _Enhanced fraud protection for your store_ banner should not render.

No additional unit tests were added to cover this callback method as there are no tests for any of the hook callbacks registered in the `init()` method in `includes/class-wc-payments.php`.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7483` or branch name `fix/6961-setting-options-non-prod-envs` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/6961-setting-options-non-prod-envs) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: cd207d1c6677155aedb511089a175bf4f359d04d
- Build time: 2023-11-17 19:46:07 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by allie500** [comment]
Closing this PR as the immediate fix requires a PR on Woo core.

**Comment by allie500** [comment]
Re-opening as we have a core filter that we can hook into from the client to add our options to the permissions array.

File: includes/class-wc-payments.php [hunk 1]
```diff
@@ -1673,6 +1674,36 @@ public static function enqueue_dev_runtime_scripts() {
...
 
+	/**
+	 * Adds WCPay options to Woo Core option allow list.
+	 *
+	 * @param   array $permissions Array containing the permissions.
+	 *
+	 * @return  array              An array containing the modified permissions.
+	 */
+	public static function add_wcpay_options_to_woocommerce_permissions_list( $permissions ) {
+		$wcpay_permissions_list = [
```
Comment (jessepearson) [inline includes/class-wc-payments.php]: What do you think about doing something like this?

```
$wcpay_permissions_list = array_fill_keys(
			[
				'wcpay_frt_discover_banner_settings',
				'wcpay_multi_currency_setup_completed',
				'woocommerce_dismissed_todo_tasks',
				'woocommerce_remind_me_later_todo_tasks',
				'woocommerce_deleted_todo_tasks',
				'wcpay_fraud_protection_welcome_tour_dismissed',
				'wcpay_capability_request_dismissed_notices',
				'wcpay_onboarding_eligibility_modal_dismissed',
			],
			true
		);
```

Comment (allie500) [reply includes/class-wc-payments.php]: I have the `array_fill_keys` in the conditional below. Would you want to move it up into the `$wcpay_permissions_list` variable assignment so we only call it once?

Comment (allie500) [reply includes/class-wc-payments.php]: I've made this change in https://github.com/Automattic/woocommerce-payments/pull/7483/commits/242dc27042ae7a9d519fb7b194f05997152bba1c.

File: includes/class-wc-payments.php [hunk 2]
```diff
@@ -1673,6 +1674,40 @@ public static function enqueue_dev_runtime_scripts() {
...
+				'woocommerce_remind_me_later_todo_tasks',
+				'woocommerce_deleted_todo_tasks',
+				'wcpay_fraud_protection_welcome_tour_dismissed',
+				'wcpay_capability_request_dismissed_notices',
+				'wcpay_onboarding_eligibility_modal_dismissed',
+			],
+			true
+		);
+
+		if ( is_array( $permissions ) ) {
```
Comment (eduardoumpierre) [inline includes/class-wc-payments.php:1699]: **Non-blocking:** What do you think about simplifying the logic? I think we can remove the `$permissions` bit from this logic without compromising readability.

```suggestion
		if ( is_array( $permissions ) ) {
			return array_merge(
				$permissions,
				$wcpay_permissions_list
			);
		}
		
		return $wcpay_permissions_list;
```

File: changelog/fix-6961-setting-options-non-prod-envs [hunk 3]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: dev
+
+Adds WCPay options to Woo Core option allow list to avoid 403 responses from Options API when geting and updating options in non-prod env.
```
Comment (eduardoumpierre) [inline changelog/fix-6961-setting-options-non-prod-envs]: There is a small typo on `getting`.

```suggestion
Adds WCPay options to Woo Core option allow list to avoid 403 responses from Options API when getting and updating options in non-prod env.
```

**Review by eduardoumpierre — APPROVED** [review]
I followed the testing instructions and it worked as expected.

I left two comments:
- A small typo on the changelog file
- A suggestion on how we could simplify a bit the permissions code

Thanks for researching and fixing this issue! I'm pre-approving this PR 🚀

File: includes/class-wc-payments.php (hunk 2 above)
Comment (allie500) [reply includes/class-wc-payments.php:1699]: I like it. I agree that it doesn't compromise readability. I've implemented it in https://github.com/Automattic/woocommerce-payments/pull/7483/commits/cd207d1c6677155aedb511089a175bf4f359d04d.

File: changelog/fix-6961-setting-options-non-prod-envs (hunk 3 above)
Comment (allie500) [reply changelog/fix-6961-setting-options-non-prod-envs]: Thank you for catching that! I've fixed it in https://github.com/Automattic/woocommerce-payments/pull/7483/commits/cd207d1c6677155aedb511089a175bf4f359d04d

File: includes/class-wc-payments.php (hunk 2 above)
Comment (allie500) [reply includes/class-wc-payments.php:1699]: I also meant to mention that I re-tested it and everything works as expected.

**Comment by glagonikas** [comment]
@allie500 @eduardoumpierre the `woocommerce_rest_api_option_permissions` hook is deprecated on WC v8.3 see here https://github.com/woocommerce/woocommerce/blob/8.3.1/plugins/woocommerce/src/Admin/API/Options.php#L149

This change results in notices like the below flooding our logs
> PHP Deprecated:  Hook woocommerce_rest_api_option_permissions is deprecated since version 6.3.0 with no alternative available. in /home/gruum/public_html/wp-includes/functions.php on line 6031

**Comment by allie500** [comment]
Hi @glagonikas! Thanks for the ping. We are aware that the Options API is deprecated, and the resulting deprecation log. We had to use the hook due to [this change](https://github.com/woocommerce/woocommerce/blob/8.3.1/plugins/woocommerce/src/Admin/API/Options.php#L110) introduced in https://github.com/woocommerce/woocommerce/pull/38388 that prevented options updates in non-production environments.

We discussed this with a few Woo core members and since there is no current replacement for the deprecated Options API, our only option was to use the `woocommerce_rest_api_option_permissions` hook to be able to update options in non-production environments.

**Comment by glagonikas** [comment]
hi @allie500 ok, but ours is a production environment and we're getting those notices flooding our logs.

Seems to originate from those

/wp-json/wc-admin/options?options=woocommerce_allow_tracking&_locale=user
/wp-json/wc-admin/options?options=woocommerce_admin_transient_notices_queue%2Cwoocommerce_admin_install_timestamp&_locale=user

**Comment by allie500** [comment]
> hi @allie500 ok, but ours is a production environment and we're getting those notices flooding our logs.
> 
> Seems to originate from those
> 
> /wp-json/wc-admin/options?options=woocommerce_allow_tracking&_locale=user /wp-json/wc-admin/options?options=woocommerce_admin_transient_notices_queue%2Cwoocommerce_admin_install_timestamp&_locale=user

Thanks for the update. These logs should only be printed if you have `WP_DEBUG` defined. I'm assuming you do on your production environment to be getting these logs.

The two options you shared were not added to the permissions array in this PR. These are the options added in this PR:

https://github.com/Automattic/woocommerce-payments/pull/7483/files#diff-57ee486c4a3ba4bae478eb31255c9a968b5b4eccd04b27f512e4003440d6f821R1687-R1694 

`woocommerce_allow_tracking`  and `woocommerce_admin_transient_notices_queue` were added in this WooCommerce Admin PR:
 https://github.com/woocommerce/woocommerce-admin/pull/8279/

Lastly, you may be able to add a custom function to your theme's function file to control what severity is logged. I found [this example](https://wordpress.stackexchange.com/a/400787) on Stack Exchange which may be helpful. Obviously, test anything extensively in non-prod before deploying to production.

**Comment by glagonikas** [comment]
> The two options you shared were not added to the permissions array in this PR. These are the options added in this PR:
https://github.com/Automattic/woocommerce-payments/pull/7483/files#diff-57ee486c4a3ba4bae478eb31255c9a968b5b4eccd04b27f512e4003440d6f821R1687-R1694
> woocommerce_allow_tracking and woocommerce_admin_transient_notices_queue were added in this WooCommerce Admin PR:
https://github.com/woocommerce/woocommerce-admin/pull/8279

I'm not sure what you mean by that? The notice clearly states that it's caused by `woocommerce_rest_api_option_permissions` and this PR is the only one that uses this hook here https://github.com/Automattic/woocommerce-payments/pull/7483/files#diff-57ee486c4a3ba4bae478eb31255c9a968b5b4eccd04b27f512e4003440d6f821R594

> Lastly, you may be able to add a custom function to your theme's function file to control what severity is logged. I found [this example](https://wordpress.stackexchange.com/a/400787) on Stack Exchange which may be helpful. Obviously, test anything extensively in non-prod before deploying to production.

Are you suggesting that we need to turn off some or all errors and hide potential issues under the carpet?

All the logs are there for a reason and even though the site might work fine today, there are no guarantees it'll work the same indefinitely.

Deprecated errors, in particular, are there to **prevent** developers from using those functions, because they will eventually be removed and the code will break. Deciding to use a function that you know is deprecated, is terrible practice and you should reconsider this approach.

In the meantime, you should figure out why those warnings started appearing **on a live/production site** after upgrading to v6.9.0 and were not present on the previous version.

**Comment by allie500** [comment]
Thanks for the feedback. As I mentioned, we discussed this with Woo core and since there is no replacement for the deprecated Options API, the only fix in the short term is to use it until Woo core provides a replacement. If you'd like, you can open an issue in Woo core to raise you concern about it and suggest a replacement for the deprecated API.
