### PR TITLE
Payments settings improvements

### LINKED ISSUE #8246: Disable all payment methods if an account is in a non-approved state
### Describe the bug

When onboarding a WooPayments account that was pending approval, APMs (like all three BNPL options) could still be enabled.

> If a merchant onboards and their account is still pending verification, their experience can be pretty fragmented depending on how quickly they begin navigating the WooPayments settings.
> 
> For example, viewing Payments > Settings immediately after onboarding shows that card payments are disabled, but all other payment methods are available.
> 
> However, checking back a bit later shows that cards and BNPL offerings are all disabled — but not other APMs.

While I could enable these APMs as an admin, they were not offered on checkout because of the account's status.

### To Reproduce

1. Onboard WooPayments in such a way that an account still needs to be approved.
2. Navigate to **Payments > Settings** prior to approval.
3. Note that some APMs (specifically BNPLs in my test) can be enabled.
4. Enable these APMs.
5. Try to make a purchase using the enabled APMs.
6. You will be unable to due to the account's pending status.

### Actual behavior

If a WooPayments account is still pending approval, a merchant can enable some APMs while the account is unable to accept payments.

### Screenshots

image

### Expected behavior

All payment methods are immediately disabled if an account is in a non-approved state.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context
Related to pbUcTB-447-p2#inconsistent-settings-when-account-pending-verification

### PR DESCRIPTION
**Pull request by timur27**
Closes https://github.com/Automattic/woocommerce-payments/issues/8246
The ACs for https://github.com/Automattic/woocommerce-payments/issues/8246 are essentially listed in https://github.com/Automattic/woocommerce-payments/issues/8246#issuecomment-1988771222.

#### Changes proposed in this Pull Request
This PR removes the spinner when checking the payment method on the Settings page (the spinner was there only to meet design expectations. Confirmed in [this discussion.](https://a8c.slack.com/archives/C01B8KNUYSW/p1710935261397159)

This PR also updates payment method statuses if they were updated after clicking the `Save settings` button. This means that merchants don't necessarily need to refresh the page to see the update.

#### Testing instructions

> Note: if you are able to set up your Stripe account in the way that it returns the capabilities you expect for testing, feel free to skip 1️⃣ and 2️⃣. For more inspiration, see https://github.com/Automattic/woocommerce-payments/issues/8246#issuecomment-1986347089

##### Payment methods checkbox has no spinner
* Enable any payment method in the settings page and confirm that the checkbox is enabled immediately without delay
* After enabling, save settings, refresh the page, and confirm that the payment method is still enabled
* Choose any payment method which has requirements to meet and confirm that after checking the checkbox, the activation modal window is enabled. Example:
    * disable `ideal` in Settings
    * 1️⃣ before [this line](https://github.com/Automattic/woocommerce-payments-server/blob/trunk/server/wp-content/rest-api-plugins/endpoints/wcpay/stripe/class-stripe-account.php#L306) in server, add `$this->account_data['capability_requirements']['ideal_payments'][] = 'business_profile.support_email';`, clear account cache
    * navigate to settings, check the iDEAL checkbox and confirm that the activation modal window is displayed

##### Payment methods list updates after saving settings without the need to refresh the page
* 2️⃣  modify [this line](https://github.com/Automattic/woocommerce-payments/pull/8428/files#diff-ca94d508b6d48cbc251483ca45da16a08991d4afd1d0f6c95c4e21baf398fdb2R566) with the following code
```php
		$res = $this->get_settings();
		$res->data['payment_method_statuses']['bancontact_payments'] = [
			'status' => 'rejected',
			'requirements' => 'business_profile.support_email'
		];
```
* navigate to settings, enable Bancontact, save settings and confirm that Bancontact status changed to `Rejected` without refreshing the page

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8428` or branch name `settings/updates-improvements` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=settings/updates-improvements) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: c18a5099bb7650eebcb650a97db3ce9073236a2c
- Build time: 2024-03-26 10:57:47 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
Comment (timur27) [inline client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js:1]: I think that this task is not part of the flow anymore. I will confirm it and remove it separately.

**Review by frosso — COMMENTED** [review]
The changes are providing an excellent improvement, great idea!

One thing I'd like to note as an implementation alternative: I noticed the change in `client/settings/save-settings-section/index.js` that updates the data store within the component. In order to do so, you also needed to change the implementation of the `useGetPaymentMethodStatuses` and the implementation (and return value) of the `saveSettings` action.
But with this, you're relying on the `client/settings/save-settings-section/index.js` component's body to do the update, and the `usePaymentMethodStatuses` is now a hook that can _technically_ also update the `payment_method_statuses` settings key (even tho this settings key doesn't have a related UI element).

By implementing this change on the `saveSettings` action, you can avoid modifying `useGetPaymentMethodStatuses` (and all the related test/component changes), and you can also avoid relying on the `client/settings/save-settings-section/index.js` component to do the update:

```js
		yield updateIsSavingSettings( true, null );

		const response = yield apiFetch( {
			path: `${ NAMESPACE }/settings`,
			method: 'post',
			data: settings,
		} );

		yield updateSettingsValues( {
			payment_method_statuses: response.data.payment_method_statuses,
		} );

		yield dispatch( 'core/notices' ).createSuccessNotice(
			__( 'Settings saved.', 'woocommerce-payments' )
		);
```

What do you think of this alternative?

**Comment by timur27** [comment]
@frosso Love the suggestion, I applied it because it's definitely the better way of doing things! Thanks!

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php [hunk 1]
```diff
@@ -350,7 +361,7 @@ public function test_update_settings_returns_error_on_non_bool_is_wcpay_enabled_
 		$this->assertEquals( 400, $response->get_status() );
 	}
 
-	public function test_timur_testing() {
```
Comment (frosso) [inline tests/unit/admin/test-class-wc-rest-payments-settings-controller.php:353]: Didn't notice this earlier :D you don't want to have a test in the codebase with your name on it anymore? :D

File: client/data/settings/test/actions.js [hunk 2]
```diff
@@ -57,30 +60,63 @@ describe( 'Settings actions tests', () => {
...
+
+			// Simulate the response from the apiFetch call and proceed to the next yield
+			// Since the actual fetching process is mocked, pass the apiResponse to the next saveGenerator step directly
+			next = saveGenerator.next( apiResponse );
+			expect( next.value ).toEqual(
+				updateSettingsValues( {
+					payment_method_statuses:
+						apiResponse.data.payment_method_statuses,
+				} )
+			);
```
Comment (frosso) [inline client/data/settings/test/actions.js]: Could we use the value, instead of exporting `updateSettingsValues`?
Or, as an alternative, should we rename `updateSettingsValues` to something else (like __internal_updateSettingsValues`), to "discourage" someone from using it?

```suggestion
			expect( next.value ).toEqual( {
				type: 'SET_SETTINGS_VALUES',
				payload: {
					payment_method_statuses:
						apiResponse.data.payment_method_statuses,
				},
			} );
```

**Review by frosso — APPROVED** [review]
Thanks for the changes! One small note on `client/data/settings/test/actions.js` - just because I'm not sure if we should export `updateSettingsValues`.

File: client/data/settings/test/actions.js (hunk 2 above)
Comment (timur27) [reply client/data/settings/test/actions.js]: Makes total sense to avoid exporting `updateSettingsValues`, applied!

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php (hunk 1 above)
Comment (timur27) [reply tests/unit/admin/test-class-wc-rest-payments-settings-controller.php:353]: 🙈 my bad!

**Review by frosso — APPROVED** [review]
Thanks so much for the changes and your patience, Timur!

**Comment by timur27** [comment]
Thank _you_ @frosso !
