### PR TITLE
fix: GB postcode matching w/ GooglePay/ApplePay

### LINKED ISSUE #10633: Google Pay orders will always select the pickup address if wildcard zipcode shipping zone available
### Describe the bug

When two shipping zones are configured—one with specific wildcard postcode restrictions and another covering the same region without postcode restrictions—the system fails to match the more specific zone. Instead, it applies the more general zone, even when the address clearly matches the restricted wildcard pattern. 

If an order is placed with the wrong shipping method,  Google Pay orders will always select the pickup address, even when selecting to ship it.

### To Reproduce

You need to switch to the legacy local Up method before testing this.

- You need to set up two UK shipping zones. The first one with restricted wildcard zipcodes and the second want to cover rest of the UK. 

Image

- First, set up shipping for UK but with the below wild card zipcodes:

```
BN1 1*
BN1 2*
BN1 3*
BN1 4*
BN1 5*
BN1 6*
BN1 7*
BN1 8*
BN2 0*
BN2 1*
BN2 2*
BN2 3*
BN2 4*
BN2 5*
BN2 9*
BN3 1*
BN3 2*
BN3 3*
BN3 4*
BN3 5*
BN3 6*
BN3 7*
BN3 8*
```

- Next, set up shipping for the UK but no restriction this time: 

Image

- Now, use the following zipcode to place an order using Gpay: BN1 2PA, and check the shipping output

- As per our restriction, the zip code should satisfy the first shipping zone (The one with the wildcard restriction). Therefore, the expected output should be:

Local Pickup = Free
Local Delivery = 4.5

Instead the, the system is giving output form the second shipping zone:

Local Pickup 2 = Free
UK Delivery = 7.5

### Actual behavior

If there’s just the wildcard zipcode shipping zone available, Google Pay orders will always select the pickup address even selecting to ship it.

### Expected behavior
In an ideal scenario, the shipping output should align with the shipping configuration regardless of the payment method.

### Additional context
Slack discussion: p1741703377030399-slack-C7U3Y3VMY

### PR DESCRIPTION
**Pull request by frosso**
Fixes #10633
Fixes WOOPMNT-4888

#### Changes proposed in this Pull Request

See paJDYF-hzH-p2 for a full explanation.

#### Testing instructions

- As a merchant, navigate to WooCommerce > Settings > Shipping
- Create a new shipping zone, call it "UK - Local area"
  - Enter "United Kingdom" and "BN3 0*" and "BN3 2*" for the Zone Regions
  - Add a "Local pickup" and "Local delivery" methods
  - Save
Screenshot 2025-06-13 at 10 12 36 AM

- Create a new shipping zone, call it "UK - general"
  - Enter "United Kingrom" for the "Zone regions" (no postcode restriction)
  - Add a flat rate shipping method
  - Save
Screenshot 2025-06-13 at 10 09 01 AM

- Publish your site with ngrok/jurassic ninja
- As a customer, navigate to the published (via ngrok/jurassic ninja) product page of a physical product with Safari (Google Pay won't always redact the address, at least in test mode)
- Click on the Apple Pay button (Google Pay won't always redact the address)
- Ensure you have this address selected: `65 Church Rd, Brighton and Hove, Hove BN3 2BD, United Kingdom`
- You should see "local pickup" methods, and not the flat rate

Screenshot 2025-06-13 at 10 11 24 AM

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10847` or branch name `fix/gb-postcode-matching` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/gb-postcode-matching) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: aa654e6963655676466041bff5627a49cc4cb92f
- Build time: 2025-06-16 15:52:57 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by rtio — COMMENTED** [review]
code lgtm, testing in a bit

**Review by rtio — APPROVED** [review]
tested and works as described

File: includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php [hunk 1]
```diff
@@ -454,14 +454,31 @@ private function transform_ece_address_postcode_data( $address ) {
...
+			// they consist of two main parts: the "outward code" and the "inward code".
+			// the "outward code" has a variable length, between two and four characters.
+			// the "inward code" always has 3 characters.
+			// Google Pay/Apple Pay might redact GB postcode units to just the "outward code".
+			// but WC Core expects a full postcode unit to return shipping rates.
+			// since we can't interfere with the rate calculation,
+			// we are padding the (redacted) outward code with `0`s to have a full length postcode unit,
+			// to be used for shipping rates calculations.
+			// Replaces a redacted `N1C` string with something like `N1C000`.
+			return substr( $cleaned_postcode . '000', 0, 7 );
```
Comment (dmvrtx) [inline includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php]: Since the previous check has us left with `$cleaned_postcode` of 4 or fewer characters, do we need `substr` here?

**Review by dmvrtx — APPROVED** [review]
Logically looks good, but since I haven't got Google Pay and Apple Pay is a mess when setting up an address in a different country, I couldn't test it fully.

File: includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php (hunk 1 above)
Comment (frosso) [reply includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php]: You're right. I didn't think that since I was already checking the length being greater than 5, there was no need to return the substring. Adding the three `0`s would always return a string of maximum length `7`.

I modified it in aa654e696 . 

Now that I think about it, I could also have just padded the `$cleaned_postcode` and returned the `substr(..., 0, 7)`.
I'm leaving it like this to avoid modifying too many comments, but happy to go either way :)

Comment (dmvrtx) [reply includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php]: In that case, the only change would be going from `\s+` in regexp to `[^A-Za-z0-9]+` 🤣
