### PR TITLE
Fail upload when dispute evidence goes over limit

### LINKED ISSUE #559: Communicate dispute evidence size limit to merchant
According to my testing, if the files in an evidence submission add up to more than 4.5 MB or so, the form then fails to submit or save, with Stripe's error saying:

> The files you've attached to this dispute as evidence will exceed the limit for a dispute's total size. Try using smaller files as evidence. Hint: if you've attached images, you might want to try providing them in lower resolutions.

We should make sure the reason for failure is clear to the merchant (see https://github.com/Automattic/woocommerce-payments/issues/555), but this likely isn't enough to ensure a good UX here, since the merchant could proceed to make quite a bit of progress on the form – with an arbitrary number of files – and then would be prevented from saving any of it.

It would be nice to somehow make the merchant aware of this limit before they manually attempt to save, but I **couldn't find such a limit documented**. Currently, a file upload could succeed as long as it is under the 8 MB limit for those, but approaching this limit would seem to immediately put it over the total evidence limit, without any indication of a problem until saving.

### PR DESCRIPTION
**Pull request by jessy-p**
Fixes #559 

#### Changes proposed in this Pull Request

- keep track of the file sizes of the dispute evidence
- fail the upload that puts the total size over limit and show an error message to the merchant 

#### Testing instructions

- Check out with a dispute test card (e.g. 4000000000000259)
- Navigate to the Payments » Disputes » Dispute Details » Challenge Dispute screen for the new dispute
- Upload files one after the other.
- Upload a file that puts the combined size over 4.5 MB
- Verify that the file upload fails and failure reason is displayed

Screenshot 2021-06-04 at 6 27 07 PM

**Notes**
- The check fails if you upload files in parallel which puts the combined size over 4.5 MB. In this case, the form will be submitted but the Stripe error fails the upload.
- Dispute evidence limit on Stripe is 5 MB according to thread p1586212168010800-slack-C9976E5MJ, but on practical testing, it seems to be 4.5 MB. To avoid a scenario where this check allows the upload, but Stripe fails it on submission, 4.5 MB is implemented.
- Unit tests could not be implemented for this code as the doUpload method could not be tested.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

File: client/disputes/evidence/index.js [hunk 1]
```diff
@@ -407,14 +407,39 @@ export default ( { query } ) => {
...
 	};
 
+	const fileSizeExceeded = ( latestFileSize ) => {
+		const fileSizes = dispute.fileSize
+			? Object.values( dispute.fileSize )
+			: [];
+		const totalFileSize =
+			fileSizes.reduce( ( acc, fileSize ) => acc + fileSize, 0 ) +
+			latestFileSize;
+		if ( 4500000 < totalFileSize ) {
```
Comment (dmvrtx) [inline client/disputes/evidence/index.js:421]: Let's avoid using [magic numbers](https://www.pluralsight.com/tech-blog/avoiding-magic-numbers/) here and move 4500000 into a constant/variable with a speaking name, e.g. `disputeUploadSizeLimitInBytes`

**Review by dmvrtx — CHANGES_REQUESTED** [review]
Other than a minor request looks good to me 🙂 Good work!

**Review by dmvrtx — APPROVED** [review]
Approved 🚀
