### PR TITLE
fix: save platform checkout info on blocks

### LINKED ISSUE #7203: WooPay "Save my info" causes JS error on blocks checkout
### Describe the bug

Clicking the "save my info" to save a WooPay user, causes JS error in customer's JS console, preventing the checkout from completing.
The only solution I could find is to refresh the page and _not_ check the "save my info" checkbox.

### To Reproduce

- Ensure your website has WooPay enabled at checkout
- Add items to your cart
- Go to the blocks checkout page
- Fill in the info
- Make sure you're not using a WooPay customer address
- Check the "save my information for a faster and secure checkout" checkbox
- Click "place order"
- JS error appears in console

```
You specified "never" for fields.billing_details.phone when creating the payment Element, but did not pass params.payment_method_data.billing_details.phone when calling stripe.createPaymentMethod(). If you opt out of collecting data via the payment Element using the fields option, the data must be passed in when calling stripe.createPaymentMethod().
```

### Actual behavior

Customer is not allowed to check out

### Screenshots

When the checkbox is checked:

When the checkbox is not checked:

### Expected behavior

Customer should be allowed to check out and save info on WooPay

### Additional context

I could test this reliably with any UPE flavor.
I thought the issue was related to the phone input field being removed from the DOM, but that's not the case.
The issue doesn't affect shortcode checkout.

```[tasklist]
### Tasks
- [ ] Add "Save my info" steps to GS critical flows
```

### PR DESCRIPTION
**Pull request by frosso**
Fixes https://github.com/Automattic/woocommerce-payments/issues/7203

#### Changes proposed in this Pull Request

Removing some logic related to checkout blocks that doesn't seem to be relevant anymore, and that instead is creating a bug where the billing phone number is wiped out when WooPay's "save my info" box is checked on the blocks checkout.

#### Testing instructions

- Ensure you are using one of the UPE variations (Deferred Intent UPE is good to test with, since it'll become the default)
- Add some product(s) to your cart
- Go to the blocks checkout page
- Fill in the checkout fields, but don't enter the phone number in the "main" checkout form
- Click "Save my info" to save the info on WooPay
- Enter the phone number for WooPay (it shouldn't be filled in, since you didn't enter it in the previous step)
- Place the order
- Ensure that the customer is created on WooPay with the correct phone number (you'll need the webhooks working for this), and that the order is created in the backend without the phone number
- Log out, now attempt to do the same steps with a different email address, but fill in the phone number in the "main" checkout form
- Click "Save my info" to save the info on WooPay, but, just for fun, use a different phone number
- Place the order
- Ensure that the customer is created on WooPay with the correct phone number, and that the order is created in the backend with the correct phone number

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7204` or branch name `fix/save-customer-info-checkout` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/save-customer-info-checkout) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 1ec1dc35cb3395695b42352f2dd75fc16973ed7a
- Build time: 2023-09-20 17:56:54 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/components/woopay/save-user/checkout-page-save-user.js [hunk 1]
```diff
@@ -93,23 +87,9 @@ const CheckoutPageSaveUser = ( { isBlocksCheckout } ) => {
...
 			} ).then( () => {
 				setUserDataSent( ! shouldClearData );
-				// Cart returned from `extensionCartUpdate` clears these as these fields are not sent to backend by blocks when added.
-				// Setting them explicitly here to the previous user input.
-				cart.setShippingAddress( {
-					phone: shippingPhone,
-				} );
-				cart.setBillingAddress( {
-					phone: billingPhone,
-				} );
```
Comment (frosso) [inline client/components/woopay/save-user/checkout-page-save-user.js:103]: I noticed that one of the root causes for this issue is that the "billing" phone gets wiped out if the "billing same as shipping" is checked and the WooPay phone is entered (see video).

<details>
<summary>Video recording</summary>

https://github.com/Automattic/woocommerce-payments/assets/273592/2840337d-0ee8-4e37-ac2d-29a10d752405

</details>


But removing these calls still seems to be correctly setting shipping & billing phone to the backend and to Stripe. So, it seems to me that these calls have become redundant and can be removed, since they're now causing issues.

**Review by gpressutto5 — APPROVED** [review]
It works as expected, but I noticed something that I don't think is related to this PR so I'm going to approve it.

image

Even when using a phone in the shipping address and checking "Use same address for billing", the phone is only saved to the billing address. Is this expected?

**Comment by frosso** [comment]
> Even when using a phone in the shipping address and checking "Use same address for billing", the phone is only saved to the billing address. Is this expected?

@gpressutto5 thanks for looking! I thought I tested the scenario you outlined - I'll take a look tomorrow, thanks for raising it 👍

**Comment by frosso** [comment]
Chatted with the team, prioritizing getting this fixed and merging, I'll fix the phone copy behavior in a future pr
