### PR TITLE
fix: memoization of checkPaymentMethodIsAvailable

### LINKED ISSUE #10426: Improve efficiency in refreshing payment method verification with Stripe for ECE
This is a good point. I was looking at it but haven't included it into this PR. I think that caching itself is a pretty nice addition because otherwise, like you're mentioning, we will be making unnecessary third-party Stripe requests too often.

There is indeed a potential issue because at the moment, `memoize` uses the entire `cart` object for cache key generation, which doesn't work well for object comparison and could lead to improper cache hits/misses.

By making the cache key more specific with only the relevant fields that affect the payment method availability:

```js
export const checkPaymentMethodIsAvailable = memoize(
	( paymentMethod, cart ) => {...},
	( paymentMethod, cart ) => {
		return JSON.stringify({
			paymentMethod,
			total_price: cart.cartTotals.total_price,
			country: cart.billingAddress?.country
		});
	}
);
```

we will ensure it runs on some specific updates. But for this, we'd need to know what fields are relevant in our context, e.g. if billing country change should trigger reviewing ece availability. I think we can open a follow up issue, if we consider this worth diving into further.

_Originally posted by @frosso in p1731690532882659-slack-C01BZUL57SQ & @timur27 in https://github.com/Automattic/woocommerce-payments/pull/9927#discussion_r1883659009_

### PR DESCRIPTION
**Pull request by frosso**
Fixes WOOPMNT-4805
Fixes #10426

#### Changes proposed in this Pull Request

The `checkPaymentMethodIsAvailable` was not correctly memoized.
- The `lodash` implementation of `memoize` only uses the first function argument as the cache key and it has a cache size of `1`, which means:
  - if `checkPaymentMethodIsAvailable` was called with `checkPaymentMethodIsAvailable( 'applePay` )` and then with `checkPaymentMethodIsAvailable( 'googlePay')` and `checkPaymentMethodIsAvailable( 'applePay' )`, the first memoized value was discarded
  - the other arguments (like the cart contents) were completely discarded as part of the cache key

Which made the memoization useless.

In these changes:
- I'm ensuring the functions are memoized by payment methods: `applePay` and `googlePay` memoized values are separate
- I'm ensuring that the cart contents are part of the memoization keys
- I'm ensuring that WCPayAPI is no longer re-created
- I converted the files to TS
- I created some tests

#### Testing instructions

This `checkPaymentMethodIsAvailable` function is only use on the block-based checkout page.
So you need to have products in the cart, and the block-based checkout available.

- As a customer, add some physical products to the cart
- Navigate to a block-based checkout page on the site
- Ensure that the Google Pay and/or Apple Pay buttons are rendered at the top of the page
Screenshot 2025-06-06 at 1 54 56 AM
Screenshot 2025-06-06 at 1 53 51 AM

- To simulate the buttons being unavailable, you can add $1M+ worth of products to the cart, in that case the buttons shouldn't render and the whole "express checkout" section at checkout should collapse:
Screenshot 2025-06-06 at 1 57 28 AM

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10829` or branch name `fix/check-payment-method-availability-memoization-cache` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/check-payment-method-availability-memoization-cache) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 43d46e72b81e66991714c722260b93439094da72
- Build time: 2025-06-06 13:45:09 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/express-checkout/blocks/index.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ export const expressCheckoutElementApplePay = ( api ) => ( {
 			return false;
 		}
 
-		return checkPaymentMethodIsAvailable( 'applePay', cart );
```
Comment (frosso) [inline client/express-checkout/blocks/index.js:42]: Providing `api` as an additional argument, so this function doesn't have to create a new instance of it.

**Review by dmvrtx — APPROVED** [review]
Good work on converting the code to TypeScript. Tests well. I had an unreproducible glitch where only Google Pay was visible in Safari. On the page reload, both Apple Pay and Google Pay were visible and remained so even in private browsing mode.

**Comment by frosso** [comment]
> I had an unreproducible glitch where only Google Pay was visible in Safari

Thank you for pointing that out! Let me double check I didn't miss anything

**Comment by frosso** [comment]
Have been testing, but I can't reproduce it. I'm going to assume it was a temporary glitch 🤷

**Comment by dmvrtx** [comment]
Yeah, let's see if GlobalStep testing catches anything, because on my side it could be related to the freshly recreated sandbox account and its capabilities.
