### PR TITLE
Display notice when clicking the WooPay button if variable product selection is incomplete

### LINKED ISSUE #7616: Variable product can be purchased without choosing variations with WooPay button on product page
### Describe the bug

When on a product page with the WooPay express button enabled, it is possible to purchase a variable product even when variations have not been selected. This would be a problem for merchants, because they would not know what variation was ordered.
### To Reproduce

1. Enable WooPay express checkout button on product page
2. Visit a page with a variable product and do not select any variations
3. Click the WooPay button and it will take you to WooPay checkout

### Actual behavior

The WooPay button continues to checkout without choosing variations for a variable product

### Expected behavior

A message should appear that lets the shopper know what they need to do - select variations - and prevents checkout. An example of this can be found on a Blocks product page. More info [here](https://github.com/Automattic/woocommerce-payments/issues/6634#issuecomment-1791431592).

### Additional context

Related to #6634 and #7158

### PR DESCRIPTION
**Pull request by ricardo**
Fixes #7616

#### Changes proposed in this Pull Request

- Fixes a regression after multiple callbacks were added to the WooPay `onClick` handler.
- Implements the same behavior from the [PRBs](https://github.com/Automattic/woocommerce-payments/blob/691e3424a363c4621182a3e80f2a203c57acb472/client/payment-request/index.js#L371) to check for the "Add to cart" button state, independent of external event listeners. This approach is more generic and should be compatible with all extensions.

#### Testing instructions

**Variable products**
1. As a merchant, create a variable product.
2. Enable the WooPay express checkout button on the product page.
3. As a shopper, navigate to the variable product page.
4. Without any variation selection, try to click the WooPay button.
5. Ensure an alert is displayed with `Please select some product options before adding this product to your cart.`.
6. Select all variations.
7. Click the WooPay button again.
8. Ensure you're redirected to the WooPay checkout.
9. Ensure the right product was added to the cart and that the checkout works as expected.

**Ensuring no regression: Mix and match**

Please follow the instructions from https://github.com/Automattic/woocommerce-payments/pull/7364.

**Ensuring no regression: Product bundles**

Please follow the instructions from https://github.com/Automattic/woocommerce-payments/pull/7158.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7735` or branch name `fix/7616-variable-product-notice` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7616-variable-product-notice) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 79e53b0b4076ac2e272b5a7252c160770bd38c50
- Build time: 2023-11-22 19:23:56 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/checkout/woopay/express-button/woopay-express-checkout-button.js [hunk 1]
```diff
@@ -84,14 +82,77 @@ export const WoopayExpressCheckoutButton = ( {
...
+			} else if (
+				addToCartButton.classList.contains(
+					'wc-variation-selection-needed'
+				)
+			) {
+				window.alert(
+					window?.wc_add_to_cart_variation_params
+						?.i18n_make_a_selection_text ||
+						__(
+							'Please select some product options before adding this product to your cart.',
```
Comment (rafaelzaleski) [inline client/checkout/woopay/express-button/woopay-express-checkout-button.js]: Is this message approved by the design team? Since it's guiding users to the payment screen rather than adding items to the cart, clarity is key. Perhaps a concise alternative like `Configure your product options to proceed to payment.` would more accurately reflect the user action. What do you think?

Also, I find the use of window alerts a bit unconventional, but I see it's consistent with other PRBs. So, let's stick with it for now for consistency's sake 🤷🏻‍♂️.

**Review by rafaelzaleski — CHANGES_REQUESTED** [review]
✅ Variable products
✅ Ensuring no regression: Mix and match
❌ Ensuring no regression: Product bundles

I got the following error in a product bundle consisting of 1 variable product and 1 regular product:
```
Uncaught TypeError: Cannot read properties of null (reading 'stop')
    at initWoopayRef.current (woopay-express-checkout-button.js:274:39)
    at onClick (woopay-express-checkout-button.js:436:37)
    at HTMLUnknownElement.callCallback (react-dom.js?ver=18.2.0:4151:16)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=18.2.0:4200:18)
    at invokeGuardedCallback (react-dom.js?ver=18.2.0:4264:33)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.js?ver=18.2.0:4278:27)
    at executeDispatch (react-dom.js?ver=18.2.0:9051:5)
    at processDispatchQueueItemsInOrder (react-dom.js?ver=18.2.0:9083:9)
    at processDispatchQueue (react-dom.js?ver=18.2.0:9096:7)
    at dispatchEventsForPlugins (react-dom.js?ver=18.2.0:9107:5)
```

File: client/checkout/woopay/express-button/woopay-express-checkout-button.js (hunk 1 above)
Comment (ricardo) [reply client/checkout/woopay/express-button/woopay-express-checkout-button.js]: > Is this message approved by the design team?

Actually, this isn't out of nowhere. It's the same text from `window.wc_add_to_cart_variation_params.i18n_make_a_selection_text`, but a fallback in case the variable is not defined for some reason. Also, the other PRB use the same text.

The behavior should be the same before this PR which fixes a regression, but I agree with the point that "adding to cart" is not exactly the right action 👍. I will ask in the issue.

> Also, I find the use of window alerts a bit unconventional

I feel the same, but it's more of a Woo Core [default behavior](https://github.com/woocommerce/woocommerce/blob/8.0.1/plugins/woocommerce/client/legacy/js/frontend/add-to-cart-variation.js#L130) and design issue which is more complex to change than it looks (see https://github.com/Automattic/woocommerce-payments/issues/6634#issuecomment-1680322978).

**Comment by ricardo** [comment]
> ❌ Ensuring no regression: Product bundles

Good catch. I was able to reproduce, but it doesn't happen always.

The error is also thrown in `trunk`, so not a regression, but I'm investigating 👀.

**Comment by rafaelzaleski** [comment]
> The error is also thrown in trunk, so not a regression, but I'm investigating 👀.

If you can't find a quick fix for this issue, I suggest we proceed with merging the PR in its current state. However, let's make sure to open a new issue to address this specific problem.

**Comment by ricardo** [comment]
@rafaelzaleski I changed the alert message for WooPay and other PRBs based on this: https://github.com/Automattic/woocommerce-payments/issues/7616#issuecomment-1820387123. Can you give it another look?

> If you can't find a quick fix for this issue, I suggest we proceed with merging the PR in its current state. However, let's make sure to open a new issue to address this specific problem.

Regarding this issue, it's because [`listenForCartChanges`](https://github.com/Automattic/woocommerce-payments/blob/d1c2092b5f890a6bf54fa80e61ebb0c5fee1bc6a/client/checkout/woopay/express-button/woopay-express-checkout-button.js#L32) was `null`. A simple fix would be to check if `stop`/`start` is defined before [calling it](https://github.com/Automattic/woocommerce-payments/blob/d1c2092b5f890a6bf54fa80e61ebb0c5fee1bc6a/client/checkout/woopay/express-button/woopay-express-checkout-button.js#L265), but I'd like to understand the consequences of skipping this call before applying that fix or have steps to reproduce in order to create an issue.

On Friday I was able to reproduce the error a couple times, but now I'm not being able to reproduce it anymore. Can you try again? I'm trying to identify when this happens. I tried throttling my Network, checking out an old commit, but nothing did it.

**Comment by ricardo** [comment]
I was able to reproduce it again and apparently there was some race condition where the event had been already fired by the time `listenForCartChanges` should be defined. So I implemented the equivalent in plain JS (https://github.com/Automattic/woocommerce-payments/pull/7735/commits/b382912c4eed588a5d26763bcb8b558103e3272e) and it seems to work now.

**Review by rafaelzaleski — APPROVED** [review]
**Test results:**

✅ Variable products
✅ Mix and match
✅ Product bundles

Great work on the product bundle fixes. The code looks good. 🚀🚀
