### PR TITLE
Removing unnecessary check against server response

### LINKED ISSUE #4699: Internal E2E tests failing due to unneeded key existence check
### Describe the bug

Internal end to end tests are failing due to a newly updated check against `deposits.status` in the account status. Previously this check referenced `deposits_status`. 

https://github.com/Automattic/woocommerce-payments/blob/3ec6d887b5ed77e8f764fe30c316228a61c61410/includes/class-wc-payments-account.php#L185

https://github.com/Automattic/woocommerce-payments/blob/7360a79851af3f93034ea989c1846462f2ffef54/includes/class-wc-payments-account.php#L185

Reviewing the server response shows that if `payments_enabled` is returned, the full expected response is also returned making this check unnecessary.

### Additional context
p1662388714071439-slack-CGGCLBN58

### PR DESCRIPTION
**Pull request by brucealdridge**
Fixes #4699

#### Changes proposed in this Pull Request

Removed unnecessary check for `deposit.status` / `deposit_status` on response from server. As this key always exists when the other conditions are met.

Whenever the `payments_enabled` key is returned from the server, the deposit status is also returned.

#### Testing instructions

* Check that when `payments_enabled` is returned from the server that `deposits.status` or `deposits_status` is returned.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: includes/class-wc-payments-account.php [hunk 1]
```diff
@@ -180,9 +180,7 @@ public function get_account_status_data() {
 			];
 		}
 
-		if ( ! isset( $account['status'] )
-			|| ! isset( $account['payments_enabled'] )
-			|| ! isset( $account['deposits']['status'] ) ) {
+		if ( ! isset( $account['status'], $account['payments_enabled'] ) ) {
```
Comment (mattallan) [inline includes/class-wc-payments-account.php:183]: This is probably pretty minor but using `! isset( $a, b )` is changing our original logic.
This is line is now equivalent to `! isset( $account['status'] ) && ! isset( $account['payments_enabled'] )` but previously we had `||`

Comment (mattallan) [reply includes/class-wc-payments-account.php:183]: Based on this test code (props @brucealdridge), my understanding was incorrect and these are equivalent.

**Review by mattallan — APPROVED** [review]
Thanks @brucealdridge this PR LGTM.

File: includes/class-wc-payments-account.php (hunk 1 above)
Comment (brucealdridge) [reply includes/class-wc-payments-account.php:183]: Just to close the loop on this, the logic was [confirmed](https://3v4l.org/r6i6h) to behave as expected.
