### PR TITLE
Save the generated customer id using session cookie for non logged in users

### LINKED ISSUE #2716: Not logged in users get failed payment after a failed payment attempt
We are generating for them a new customer id every time we make a payment. When making a failed payment with credit card and repeating it without refreshing, there is an error when attaching a new customer id to an existing payment intent.

We need to save the first time generated customer id in a session, so we can reuse it.

### PR DESCRIPTION
**Pull request by daquinons**
Fixes #2716 

#### Changes proposed in this Pull Request

Save the generated customer id using session cookie for non logged in users

Right now everytime a payment is executed we are creating a new customer id for every attempt a non logged in user does. Apart from being not practical, it was creating issues when attempting a failed payment if you were not logged in.

This PR solves that saving the customer id in the session cookie, so if a user is non logged in (id 0) and has an existing customer id, we can use that to continue payment intents.

#### Testing instructions

- Log out
- add items to cart and go to check out
- Use `4000000000000002` and see a card declined error
- Click on "Place Order" again without refreshing
- See the card declined error

Before this fix, after the second attempt would display this error
Screenshot 2021-08-12 at 13 38 25

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -892,6 +892,8 @@ protected function manage_customer_details_for_order( $order ) {
 		if ( null === $customer_id ) {
 			// Create a new customer.
 			$customer_id = $this->customer_service->create_customer_for_user( $user, $customer_data );
+			// Save the customer id in the session for non logged in users to reuse it in payments.
+			WC()->session->set( 'customer_id', $customer_id );
```
Comment (marcinbot) [inline includes/class-wc-payment-gateway-wcpay.php:896]: Let's make sure the property name is unique, something like `woocommerce_payments_customer_id`.

Comment (daquinons) [reply includes/class-wc-payment-gateway-wcpay.php]: Done! I've also added a test 👍

**Review by marcinbot — APPROVED** [review]
:shipit:
