### PR TITLE
Do not open the email input iframe when there is no wcpay as payment method

### LINKED ISSUE #7684: Should not redirect to WooPay checkout page when WC Bookings require confirmation
### Describe the bug
On the Blocks checkout page, we should not redirect to the WooPay checkout page when WC Bookings require confirmation.

### To Reproduce
1. Install and activate WC Bookings plugin
2. Check the "Requires confirmation?" box
3. As a logged-in customer, go through the purchasing process and go to the Blocks checkout page
4. See, we redirect to WooPay and skip the merchant confirmation process.

### Actual behavior
When the WC Bookings product requires confirmation, on the Blocks checkout page, we redirect to the WooPay checkout page and skip the merchant confirmation process.

### Screenshots

https://github.com/Automattic/woocommerce-payments/assets/56378160/e3ee160a-f0ea-4420-ba80-56960b1d96fb

### Expected behavior
When the WC Bookings product requires confirmation, on the Blocks checkout page, we should not redirect to the WooPay checkout page.

### LINKED ISSUE #8053: WC Pre-Orders pay later should not redirect to WooPay for existing users
### Describe the bug

When testing the pay later Pre-Orders product with an existing user email, on the blocks checkout page, the WooPay iframe would pop up but doesn't redirect shopper to the WooPay checkout page.

### To Reproduce

1. Install and activate WC Pre-Orders plugin
2. Create a pre-order product and pick `upon release` for `When to charge`
3. As an existing shopper, add the product to the cart and go to the checkout page
4. See the WooPay iframe pop up, use test code and doesn't redirect to the WooPay checkout page

### Actual behavior
The WooPay iframe would pop up but doesn't redirect shoppers to the WooPay checkout page.

### Screenshots / Video

https://github.com/Automattic/woocommerce-payments/assets/56378160/a510dc71-08cd-4c95-8176-8472d72416d4

### Expected behavior
If the product set to upon release(pay later) then the WooPay iframe should not pop up

### PR DESCRIPTION
**Pull request by hsingyuc**
Fixes #7684 
Fixes #8053 

#### Changes proposed in this Pull Request
In this PR, we check the available payment methods on the checkout page.  If there's no `woocommerce-payments`, we don't open the login session iframe.

#### Videos
https://github.com/Automattic/woocommerce-payments/assets/56378160/2bbdee20-6060-4341-88a4-b8bc60f73505

https://github.com/Automattic/woocommerce-payments/assets/56378160/712f0ff0-57ef-49ff-bf1d-994eed288358

https://github.com/Automattic/woocommerce-payments/assets/56378160/78e99e5d-1dc3-4195-89c7-6669da36b97f

https://github.com/Automattic/woocommerce-payments/assets/56378160/2eebfad0-0a90-49e2-b131-5b308685146b

#### Testing instructions
*Test with WooCommerce Bookings*
1. Install and activate the WC Bookings plugin
2. Check the "Requires confirmation?" box
3. Use an existing WooPay shopper email on the checkout page
4. The login session iframe should not be opened

*Test with WooCommerce Pre-Orders*
1. Install and activate the WC Pre-Orders plugin
2. Under the product data meta -> Pre-orders, select when to charge to `Upon release`
3. Use an existing WooPay shopper email on the checkout page
4. The login session iframe should not be opened

*

-------------------

- [X] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8116` or branch name `fix/open-email-input-iframe-when-no-wcpay` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/open-email-input-iframe-when-no-wcpay) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b7ccd51e76d37e9f4d4268da77d92ad50a6b499b
- Build time: 2024-02-13 03:49:00 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/woopay/class-woopay-session.php [hunk 1]
```diff
@@ -408,7 +408,7 @@ private static function get_init_session_request( $order_id = null, $key = null,
 		// This uses the same logic as the Checkout block in hydrate_from_api to get the cart and checkout data.
 		$cart_data = ! $is_pay_for_order
 			? rest_preload_api_request( [], '/wc/store/v1/cart' )['/wc/store/v1/cart']['body']
-			: rest_preload_api_request( [], "/wc/store/v1/order/{$order_id}?key={$key}&billing_email={$billing_email}" )[ "/wc/store/v1/order/{$order_id}?key={$key}&billing_email={$billing_email}" ]['body'];
+			: rest_preload_api_request( [], "/wc/store/v1/order/" . urlencode( $order_id ) . "?key=" . urlencode( $key ) . "&billing_email=" . urlencode( $billing_email ) )[ "/wc/store/v1/order/" . urlencode( $order_id ) . "?key=" . urlencode( $key ) . "&billing_email=" . urlencode( $billing_email ) ]['body'];
```
Comment (malithsen) [inline includes/woopay/class-woopay-session.php]: Are these changes related to the fix?

**Review by malithsen — APPROVED** [review]
Looks good and tests well, approving. e2e failures doesn't seem relevant to this PR. Just one question on urlencode changes.

File: includes/woopay/class-woopay-session.php (hunk 1 above)
Comment (hsingyuc) [reply includes/woopay/class-woopay-session.php]: They are not.  Thank you! 😅

**Comment by rafaelzaleski** [comment]
The `wc/store/payment` endpoint ([link](https://github.com/Automattic/woocommerce-payments/blob/9e98720f82da1ef96994567c71ed521efcdfa857/client/checkout/woopay/email-input-iframe.js#L620)) is accessible only within the checkout block context. In the shortcode checkout, it returns an empty object, leading to the user redirection condition being false (`hasWCPayPaymentMethod = false`).
