### PR TITLE
Fix unused parameter phpcs sniffs in checkout classes

### LINKED ISSUE #8657: Checkout: Fix unused parameter phpcs sniffs
Part of #8436.

## Description

Remove the `VariableAnalysis.CodeAnalysis.VariableAnalysis` exclude from `phpcs.xml.dist` and fix the issues reported when running `npm run lint:php` in the following files:

* `includes/payment-methods/class-afterpay-payment-method.php`
* `includes/express-checkout/class-wc-payments-express-checkout-button-helper.php`
* `includes/payment-methods/class-upe-payment-method.php`
* `includes/class-wc-payments-payment-request-button-handler.php`

## Suggested fixes:

* When a variable is truly unused, such as in filter functions where a parameter isn’t needed, prepend `$_unused_` to the variable name. For example `$order` &rarr; `$_unused_order`.
* If a variable is not necessary, remove it.
* When a parent class/interface doesn’t use a parameter but child classes _do_, use an inline `// phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable`.

### PR DESCRIPTION
**Pull request by timur27**
Fixes https://github.com/Automattic/woocommerce-payments/issues/8657

#### Changes proposed in this Pull Request
This PR fixes the unused parameter sniffs from PHPCS, occurring in the checkout classes.

#### Testing instructions
* run `npm run lint:php` and confirm that none of the below files are listed in the error report

```php
includes/payment-methods/class-afterpay-payment-method.php
includes/express-checkout/class-wc-payments-express-checkout-button-helper.php
includes/payment-methods/class-upe-payment-method.php
includes/class-wc-payments-payment-request-button-handler.php
```

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8955` or branch name `fix/unused-param-phpcs-sniffs` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/unused-param-phpcs-sniffs) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: cafbd9226a356ff367c99a661ee71f716807353f
- Build time: 2024-06-13 15:16:11 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/payment-methods/class-afterpay-payment-method.php [hunk 1]
```diff
@@ -72,8 +72,10 @@ public function __construct( $token_service ) {
 	 * Returns payment method title.
 	 *
 	 * @param string|null $account_country Country of merchants account.
-	 * @param array|false $payment_details Optional payment details from charge object.
+	 * @param array|false $payment_details Payment details from charge object. Not used by this class.
 	 * @return string|null
+	 *
+	 * @phpcs:disable VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable
 	 */
 	public function get_title( string $account_country = null, $payment_details = false ) {
```
Comment (timur27) [inline includes/payment-methods/class-afterpay-payment-method.php:80]: https://github.com/Automattic/woocommerce-payments/issues/8657 suggests we apply the inline only in the parent classes that have unused variables, but this child class [outputs `ParamNameMismatch` phpcs error](https://github.com/Automattic/woocommerce-payments/actions/runs/9501032020/job/26185593016?pr=8955) if we resolve the problem through renaming the variable to `$unused_payment_details`, so I used the inline comment here as well.

**Review by mdmoore — APPROVED** [review]
LGTM - Thanks Timur!

File: includes/payment-methods/class-afterpay-payment-method.php (hunk 1 above)
Comment (reykjalin) [inline includes/payment-methods/class-afterpay-payment-method.php:80]: Is this class inherited somewhere? If not, the recommended fix here would be to prepend `$_unused_` to the variable name instead of using a phpcs ignore:

```suggestion
	 * @param array|false $payment_details Optional payment details from charge object.
	 * @param array|false $_unused_payment_details Payment details from charge object. Not used by this class.
	 * @return string|null
	 */
	public function get_title( string $account_country = null, $_unused_payment_details = false ) {
```

This also applies to the other 2 ignores added in this PR.

**Review by reykjalin — COMMENTED** [review]
I noticed that we may not have applied the suggested changes for the unused parameters in this PR 🤔

**Comment by mdmoore** [comment]
> I noticed that we may not have applied the suggested changes for the unused parameters in this PR 🤔

I think this is what @timur27 was referring to [here](https://github.com/Automattic/woocommerce-payments/pull/8955#discussion_r1638396764) with running into `ParamNameMismatch`. Would that just be a matter of updating the param name as well?

File: includes/payment-methods/class-afterpay-payment-method.php (hunk 1 above)
Comment (timur27) [reply includes/payment-methods/class-afterpay-payment-method.php:80]: @reykjalin As per https://github.com/Automattic/woocommerce-payments/pull/8955/files#r1638396764, prepending the variable name with `$_unused` leads to [the `ParamNameMismatch`](https://github.com/Automattic/woocommerce-payments/actions/runs/9501032020/job/26185593016?pr=8955) which in turn can be fixed by another suppression but doesn't seem to be worth it, so I applied the ignore.


> This also applies to the other 2 ignores added in this PR.

If you're referring to `get_title` and `get_icon`, both methods are located in `includes/payment-methods/class-upe-payment-method.php` which is inherited by payment method classes, so the ignores were applied here as per instructions. 


Let me know your thoughts, thanks!

Comment (reykjalin) [reply includes/payment-methods/class-afterpay-payment-method.php:80]: Hmmm, I don't think it matters if the doc comment is changed to be `$_unused_<var_name>` tbh, and that would fix that lint failure. I'll modify my suggestion to demonstrate 👍 

> If you're referring to `get_title` and `get_icon`, both methods are located in `includes/payment-methods/class-upe-payment-method.php` which is inherited by payment method classes, so the ignores were applied here as per instructions.

Awesome, just wanted to make sure, thank you!

**Comment by reykjalin** [comment]
> Would that just be a matter of updating the param name as well?

The doc comment parameter name, [yes](https://github.com/Automattic/woocommerce-payments/pull/8955#discussion_r1639028557). **EDIT:** Actually [no](https://github.com/Automattic/woocommerce-payments/pull/8955#discussion_r1639029769), because this is a Psalm failure 🥴

File: includes/payment-methods/class-afterpay-payment-method.php (hunk 1 above)
Comment (reykjalin) [reply includes/payment-methods/class-afterpay-payment-method.php:80]: oh, wait no that's a Psalm failure! Huh, didn't think about that. Let's keep this as is for now, I'll open an issue to track how we address this.

Comment (reykjalin) [reply includes/payment-methods/class-afterpay-payment-method.php:80]: I've opened https://github.com/Automattic/woocommerce-payments/issues/8956 to track this and added instructions to use phpcs ignores for child classes to all the remaining issue descriptions 👍

Comment (marcinbot) [reply includes/payment-methods/class-afterpay-payment-method.php:80]: I think the problem here is that this is an overridden method and the param names should ideally stay the same as in the parent.

The solution is not to rely on inheritance here (a bigger problem than a single PR, I know) not to configure Psalm to ignore errors :)
