### PR TITLE
Fix tests for WP 6.1

### LINKED ISSUE #5042: Pull request checks are failing after release of WordPress 6.1
### Describe the bug
The following pull request checks started failing shortly after the release of WordPress 6.1.

- [Compatibility - WC, WP and PHP](https://github.com/Automattic/woocommerce-payments/blob/develop/.github/workflows/compatibility.yml)
- [Code coverage](https://github.com/Automattic/woocommerce-payments/blob/develop/.github/workflows/coverage.yml)
- [PHP linting and tests](https://github.com/Automattic/woocommerce-payments/blob/develop/.github/workflows/php-lint-test.yml)

Example errors:

```
1) WC_REST_Payments_Settings_Controller_Test::test_get_settings_request_returns_status_code_200
Undefined property: WC_REST_Payments_Settings_Controller_Test::$mock_token_service

/home/runner/work/woocommerce-payments/woocommerce-payments/tests/unit/admin/test-class-wc-rest-payments-settings-controller.php:131
/home/runner/work/woocommerce-payments/woocommerce-payments/vendor/yoast/phpunit-polyfills/src/TestCases/TestCasePHPUnitGte8.php:56

2) WC_REST_Payments_Settings_Controller_Test::test_get_settings_returns_enabled_payment_method_ids
Undefined property: WC_REST_Payments_Settings_Controller_Test::$mock_token_service

/home/runner/work/woocommerce-payments/woocommerce-payments/tests/unit/admin/test-class-wc-rest-payments-settings-controller.php:131
/home/runner/work/woocommerce-payments/woocommerce-payments/vendor/yoast/phpunit-polyfills/src/TestCases/TestCasePHPUnitGte8.php:56

3) WC_REST_Payments_Settings_Controller_Test::test_get_settings_returns_available_payment_method_ids
Undefined property: WC_REST_Payments_Settings_Controller_Test::$mock_token_service
```

Example test failures:

```
1) WC_Payments_Webhook_Processing_Service_Test::test_payment_intent_successful_and_completes_order
Unexpected incorrect usage notice for WP_Object_Cache::delete.
Cache key must be integer or non-empty string, NULL given. (This message was added in version 6.1.0.)
Failed asserting that an array is empty.

/tmp/wordpress-tests-lib/includes/abstract-testcase.php:615
/tmp/wordpress-tests-lib/includes/abstract-testcase.php:627
/home/runner/work/woocommerce-payments/woocommerce-payments/vendor/yoast/phpunit-polyfills/src/TestCases/TestCasePHPUnitGte8.php:80

2) WC_Payments_Webhook_Processing_Service_Test::test_payment_intent_successful_and_completes_order_without_intent_id
Unexpected incorrect usage notice for WP_Object_Cache::delete.
Cache key must be integer or non-empty string, NULL given. (This message was added in version 6.1.0.)
Failed asserting that an array is empty.

/tmp/wordpress-tests-lib/includes/abstract-testcase.php:615
/tmp/wordpress-tests-lib/includes/abstract-testcase.php:627
/home/runner/work/woocommerce-payments/woocommerce-payments/vendor/yoast/phpunit-polyfills/src/TestCases/TestCasePHPUnitGte8.php:80

3) WC_Payments_Webhook_Processing_Service_Test::test_payment_intent_successful_when_retrying
Unexpected incorrect usage notice for WP_Object_Cache::delete.
Cache key must be integer or non-empty string, NULL given. (This message was added in version 6.1.0.)
Failed asserting that an array is empty.

/tmp/wordpress-tests-lib/includes/abstract-testcase.php:615
/tmp/wordpress-tests-lib/includes/abstract-testcase.php:627
/home/runner/work/woocommerce-payments/woocommerce-payments/vendor/yoast/phpunit-polyfills/src/TestCases/TestCasePHPUnitGte8.php:80
```

### To Reproduce

1. Branch off `develop`.
2. Commit some code.
3. Push your changes.
4. Create a pull request.
5. Observe the compatibility, code coverage and PHP linting and tests pull request checks fail.

### Actual behavior
Pull request checks fail when testing against WordPress 6.1.

### Screenshots

Screen Shot 2022-11-03 at 3 00 46 pm

### Expected behavior
Pull request checks pass as expected when testing against WordPress 6.1.

### Additional context
Discussed in Slack here p1667353741152329-slack-CGGCLBN58

### PR DESCRIPTION
**Pull request by RadoslavGeorgiev**
Fixes #5042

#### Changes proposed in this Pull Request

- Add [missing props](https://github.com/Automattic/woocommerce-payments/pull/5049/commits/b9fef9083dac4b56c549f56a422b5cbdbdc67ee2) to `WC_Payment_Gateway_WCPay_Test` to make the `test_capture_charge_metadata` work within the test (seems to be moved over from another one).
- Make sure that [mock orders return an ID](https://github.com/Automattic/woocommerce-payments/pull/5049/commits/d5b7b6d8cb1d80f110825fcca6f0345f07b00244) for `Webhook_Processing_Service`. This way we're not using null values for `wp_cache_*` methods. This way https://core.trac.wordpress.org/ticket/56198 will not cause errors.
- `WC_REST_Payments_Settings_Controller_Test` was missing the `$mock_token_service` mock, which was required for most of the tests in the file.

#### Testing instructions

All tests should pass.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times.

### CODE REVIEW

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php [hunk 1]
```diff
@@ -101,6 +108,7 @@ public function set_up() {
 		$action_scheduler_service = new WC_Payments_Action_Scheduler_Service( $this->mock_api_client );
 		$mock_rate_limiter        = $this->createMock( Session_Rate_Limiter::class );
 		$order_service            = new WC_Payments_Order_Service( $this->mock_api_client );
+		$this->mock_token_service = $this->createMock( 'WC_Payments_Token_Service' );
```
Comment (achyuthajoy) [inline tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: Should we create a mock here @RadoslavGeorgiev. I see the `token_service` is initialized on line 107? Can we use that instead of mocking the class again?

Comment (RadoslavGeorgiev) [reply tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: Fixed in https://github.com/Automattic/woocommerce-payments/pull/5049/commits/6a0d761ed6969771c7f4d5fa33aa8258757d0962

**Review by achyuthajoy — APPROVED** [review]
LGTM 🚢
