### PR TITLE
Sending payment_method_update_data param to intent API

### LINKED ISSUE #5951: Saved Payment Methods retain old address details, which can fail ZIP checks
### Describe the bug

If a customer saves a payment method to their account, the ZIP code provided when that payment method is saved is seemingly tied to that saved payment method. 

If a customer...
- Proceeds through checkout using a saved payment method but adds a different ZIP/postal code.
- Updates their address for subscription products via **My Account > Addresses** flow.

...the updated address information, including ZIP/postal code is not sent to Stripe. As a result, if a customer moves and tries to use a previously saved Payment Method, this will block the payment due to ZIP Check errors.

### To Reproduce

1. Make a purchase and save the payment method. Note the ZIP/postal code used at checkout.
2. Check the Stripe dashboard for this payment.
3. Make another purchase using a different address, but use the saved payment method. 
4. Check the Stripe dashboard and note that the payment made in step 3 uses the same ZIP/postal code in step 1.
5. Install/activate [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038) and create a subscription product (if one doesn't already exist).
6. Purchase a subscription product using the saved payment method from step 1. Note the ZIP/postal code used at checkout.
7. Check the Stripe dashboard for the parent order. If using the saved payment method from step 1, the order in the Stripe dashboard will not have the updated billing address information.
8. Navigate to **My Account > Addresses** and change the billing address for the account.
9. Check `Update the Billing Address used for all future renewals of my active subscriptions (optional)` and save the settings.
10. Trigger a renewal for the subscription purchased in step 5 via scheduled actions or the early renewal flow.
11. Check the Stripe dashboard and note that the renewal order from step 9 uses the same ZIP/postal code in step 1.

### Actual behavior
If a customer moves and changes the address information at their bank, their orders will fail if the customer:
- tries to use a saved payment method for a new purchase.
- has an active subscription.

### Expected behavior
There should be an easy and accessible way for a customer to update the address associated with saved payment methods.

### Workaround
The customer can go through the checkout flow, add a new card, and save that as a payment method. They can delete the old saved payment method at **My Account > Payment Methods**, and if they have active subscriptions, they can make this new payment method the default.

**However**, this is a clunky and haphazard workaround. If a customer uses this workaround and adds the same card to their account with the correct address details, there is no way for them to know which of the cards on file is associated with the correct address.

### Additional context
See p1672937255481699-slack-CGGCLBN58 and p1680539873882779-slack-C03EE4CPPK5 for some initial digging and discussion.

Assigning `priority: high` because this has been an issue for some time and has a history of affecting HVMs.

### LINKED ISSUE #8158: When updating a saved payment method, its line 2 isn't updated when the new value is empty
### Describe the bug

When updating the billing address of a saved payment method, the old value of line2 persists when its new value is an empty string.

### To Reproduce

1. Log in as a shopper, add a product to the cart, and go to the checkout page
2. Use the following address as the billing one
```
28224 Chandra Overpass
Unit 2
Port Janean
New Mexico, 50908, United States
```
3. Enter a new payment method, like `4242424242424242`
4. Check off "Save payment information to my account for future purchases" and place the order
5. Go to the Stripe dashboard page for the customer and locate the saved payment method
7. Notice that line2 of the billing address says "Unit 2". All good
image

8. Go to the checkout page again
9. Empty line2 from the billing address by deleting the "Unit 2" string. Change line1 to "123 new street"
10. Select the same saved card and place the order
11. Run the [scheduled action](http://localhost:8082/wp-admin/tools.php?page=action-scheduler) with the hook `wcpay_update_saved_payment_method` for the last order 
12. Go to the Stripe dashboard page for the customer and locate the saved payment method
image

### Actual behavior
The line2 property of the billing address for the payment method isn't updated.

### Expected behavior
I'd expect the line2 of the billing address to be empty when the latest value for this property is empty.

### Additional context

We retrieve the value for the billing address in `WC_Payments_Utils::get_billing_details_from_order()`. We're filtering out empty values for the billing address [here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-utils.php#L361). The line2 doesn't exist in the array we submit to Stripe via [WC_Payments_Customer_Service::update_payment_method_with_billing_details_from_order()](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-customer-service.php#L279-L296)

### PR DESCRIPTION
**Pull request by gpressutto5**
Fixes #5951
Fixes #8158

#### Changes proposed in this Pull Request

- Replaced `get_billing_details_from_order()` usage with `$order_service->get_billing_data_from_order()` so we can use `WC()` as it is not in Utils.
- Updated `$order_service->get_billing_data_from_order()` logic similar to how it was done before 7.5.2, but uses the Country method instead of the Checkout method to get the available fields.
- Sets `get_fees` return type to `array` to fix an error in tests `array_keys() expects parameter 1 to be array` in `includes/class-wc-payment-gateway-wcpay.php:3946`.
- Sets `get_account_default_currency` return type to `string` to fix a similar error.

##### Sending payment_method_update_data param to intent API

1. Make sure your server is running the branch from the PR above
1. Place an order saving a new card with a billing address
1. Place an order using the saved card from the previous step but using a new billing address
1. Check the intents in Stripe dashboard and ensure it used the new billing address in the second payment

##### Avoid updating billing details for legacy card objects

``` 
💡 To create the legacy card object for your account, send the following request while inserting your customer ID, account ID and test API key

curl https://api.stripe.com/v1/customers/${customer_id}/sources \
-u ${test_api_key}: \
-H "Stripe-Account:${acct_id}" \
```
* Ensure that you have the saved payment method on your store which is legacy card from the request above
* On this branch, purchase a subscription with this saved payment method, confirm the successful purchase 
* Revert the fix commit, navigate to subscription details, process renewal, confirm that the error message is the same as in https://github.com/Automattic/woocommerce-payments/issues/8405
* Remove the revert so that the fix is in place
* In the failed order details options, choose `Retry renewal payment`
* Navigate to subscription details, process renewal and confirm the renewal was successful this time

##### Remove filtering of billing address details

1. Make a purchase saving a card using a billing address with address line 2.
2. Make a new purchase using the saved card from before but with an empty line 2.
3. Check Stripe dashboard. The second address should not have line 2.

##### Filtering billing details from order based on checkout fields

1. Create a simple subscription product
3. Install [Checkout Field Editor](https://woo.com/products/woocommerce-checkout-field-editor/?aff=10486&cid=1131038)
4. Remove all billing fields except ZIP code, email, and first/last name
5. Purchase a subscription via shortcode checkout (CFE is not compatible with the checkout block)
7. Process a renewal by running the woocommerce_scheduled_subscription_payment hook in the action scheduler.
8. The renewal should work

##### Subscription renewals can fail due to "meta_exists() on null" action scheduler error

> ❗ Important

Follow the reproduction steps from #8678 using WooPayments 7.5.1 and ensure you can reproduce the error, then switch to this branch and ensure it doesn't fail.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8720` or branch name `update-billing-address-saved-card` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update-billing-address-saved-card) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: f25dd7ca312efbc4f6b749bdcc714c495fe273ee
- Build time: 2024-05-06 11:41:25 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/admin/class-wc-rest-payments-charges-controller.php [hunk 1]
```diff
@@ -22,6 +22,27 @@ class WC_REST_Payments_Charges_Controller extends WC_Payments_REST_Controller {
...
+	private $order_service;
+
+	/**
+	 * Constructor.
+	 *
+	 * @param WC_Payments_API_Client    $api_client    WooCommerce Payments API client.
+	 * @param WC_Payments_Order_Service $order_service Order service.
+	 */
+	public function __construct(
+		WC_Payments_API_Client $api_client,
```
Comment (timur27) [inline includes/admin/class-wc-rest-payments-charges-controller.php]: Thanks for adding it to the constructor so that it's in line with its initialization in `class-wc-payments.php`!

I wonder if we can go ahead and remove dependency to the static `WC_Payments` method [[here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/admin/class-wc-rest-payments-charges-controller.php#L105)] and [[here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/admin/class-wc-rest-payments-charges-controller.php#L122)] by replacing them with the `$this->api_client` which will be acquired from the parent `WC_Payments_REST_Controller`. Let me know your thoughts 😊

File: includes/class-wc-payments-order-service.php [hunk 2]
```diff
@@ -891,30 +891,39 @@ public function get_shipping_data_from_order( WC_Order $order ): array {
...
+		$billing_fields       = array_keys( WC()->countries->get_address_fields( $order->get_billing_country() ) );
+		$address_field_to_key = [
+			'billing_city'      => 'city',
+			'billing_country'   => 'country',
+			'billing_address_1' => 'line1',
+			'billing_address_2' => 'line2',
+			'billing_postcode'  => 'postal_code',
+			'billing_state'     => 'state',
 		];
+		$field_to_key         = [
```
Comment (timur27) [inline includes/class-wc-payments-order-service.php:909]: Nitpick: since `$address_field_to_key` clearly indicates that it maps address fields, having this array name reflect its keys as well might potentially ease up the readability of this chunk of code, what do you think? 

```suggestion
		$contact_field_to_key         = [
```

File: includes/class-wc-payments.php [hunk 3]
```diff
@@ -984,7 +984,7 @@ public static function init_rest_api() {
 		$disputes_controller->register_routes();
 
 		include_once WCPAY_ABSPATH . 'includes/admin/class-wc-rest-payments-charges-controller.php';
-		$charges_controller = new WC_REST_Payments_Charges_Controller( self::$api_client );
+		$charges_controller = new WC_REST_Payments_Charges_Controller( self::$api_client, self::$order_service );
```
Comment (timur27) [inline includes/class-wc-payments.php]: This (reasonable) change will unfortunately lead to 

```
Uncaught ArgumentCountError: Too few arguments to function WC_REST_Payments_Charges_Controller::__construct(), 1 passed in /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php on line 976 and exactly 2 expected
```

during plugin update because of https://github.com/Automattic/woocommerce-payments/issues/7464. I believe we'd need to find a way to avoid this injection unless https://github.com/Automattic/woocommerce-payments/issues/7464 is fixed.

File: includes/class-wc-payment-gateway-wcpay.php [hunk 4]
```diff
@@ -1432,6 +1419,16 @@ public function process_payment_for_order( $cart, $payment_information, $schedul
...
+				// If we are not hitting the API for the intent, we need to update the saved payment method ourselves.
+				$this->action_scheduler_service->schedule_job(
+					time(),
+					self::UPDATE_SAVED_PAYMENT_METHOD,
+					[
+						'payment_method' => $payment_information->get_payment_method(),
+						'order_id'       => $order->get_id(),
+						'is_test_mode'   => WC_Payments::mode()->is_test(),
+					]
+				);
```
Comment (timur27) [inline includes/class-wc-payment-gateway-wcpay.php:1460]: Nice move here to avoid entering the `is_using_saved_payment_method()` flow twice 🚀

File: includes/class-wc-payment-gateway-wcpay.php [hunk 5]
```diff
@@ -1514,6 +1511,16 @@ public function process_payment_for_order( $cart, $payment_information, $schedul
 				$request->set_payment_methods( $payment_methods );
 				$request->set_cvc_confirmation( $payment_information->get_cvc_confirmation() );
 				$request->set_hook_args( $payment_information );
+				if ( $payment_information->is_using_saved_payment_method() ) {
+					$billing_details = $this->order_service->get_billing_data_from_order( $order );
+
+					$is_legacy_card_object = strpos( $payment_information->get_payment_method() ?? '', 'card_' ) === 0;
```
Comment (timur27) [inline includes/class-wc-payment-gateway-wcpay.php]: There's [one more legacy object prefix](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/core/server/request/class-create-intention.php#L57-L58): `src`. We discussed (p1713444646409719/1713424263.940689-slack-CU6SYV31A) the need to add this to the previous solution, but it was reverted. 

Since we're re-adding it now, would it be a good moment to skip checking `src_` objects as well?

**Review by timur27 — COMMENTED** [review]
Thanks @gpressutto5! I tested half of the areas and will continue testing today. In the meantime, I'm leaving a few comments, thanks!

File: includes/class-wc-payments-order-service.php (hunk 2 above)
Comment (gpressutto5) [reply includes/class-wc-payments-order-service.php:909]: `$context_field_to_key` describes it better because the fields are related to contact, but I think that's just a coincidence. My reasoning was that these are fields placed in the first level of the array, and the other fields are placed under `'billing' => [ ... ] `.

**Review by timur27 — APPROVED** [review]
Thanks for all the quick changes @gpressutto5! I went through the testing steps once again and everything is functional: 

* Sending payment_method_update_data param to intent API ✅ 
* Avoid updating billing details for legacy card objects ✅ 
* Remove filtering of billing address details ✅ 
* Filtering billing details from order based on checkout fields ✅ 
    * The test was successful but I'd like to confirm with you one thing: the scheduler action run ended up creating an order which required a manual payment, so I went to the _Pay for order_ page and made a payment through shortcode checkout (where some billing checkout fields were removed as per test instructions). Is it how you think the process should look like? It ended up with a successful payment. 
* Subscription renewals can fail due to "meta_exists() on null" action scheduler error
    * I can confirm this isn't happening anymore! I was able to reproduce the error with `7.5.1` three times, switched to this branch and couldn't reproduce anymore [[successful renewal order here](https://github.com/Automattic/woocommerce-payments/assets/22319444/dd958ba3-9968-4e7d-b5f8-b7738cc68fd8)]! Thank you!

**Review by timur27 — COMMENTED** [review]
@gpressutto5 I know you worked around the controller injection to avoid fatals on plugin update. I'm just seeing the fatal now when updating from `7.5.3` to `update-billing-address-saved-card` and I'm curious whether you can reproduce it?

image

**Comment by gpressutto5** [comment]
This was resolved in #8794
