### PR TITLE
Wait for Stripe js to load before using it

### LINKED ISSUE #9709: Handling of Stripe JS with GDPR & minifier plugins
### Describe the bug

The checkout button is missing in mobile view on the WooCommerce site when using WooPayments with the Cookiebot plugin enabled. The issue appears to stem from the Cookiebot plugin altering the loading behavior of the Stripe JavaScript. Specifically, Cookiebot changes the `<script>` type of Stripe’s script from `text/javascript` to `text/plain` due to cookie consent settings, which prevents Stripe from loading correctly, thereby causing WooPayments elements not to display on checkout.

### To Reproduce

1. Enable the Cookiebot plugin (for example)
2.  Go to the WooCommerce checkout page
1. Check if the WooPayments checkout button and Stripe elements are visible.
1. Open the browser console to observe errors.

### Actual behavior

In mobile view, the checkout button is missing on the WooCommerce checkout page. The console displays the following error:

```js
blocks-checkout.js?ver=8.2.2:2 Uncaught (in promise) Error: Invalid prop `stripe` supplied to `Elements`. We recommend using the `loadStripe` utility from `@stripe/stripe-js`.
```

Additionally, attempting to manually initialize Stripe in the console returns:

```js
ReferenceError: Stripe is not defined
```

Inspecting the page source reveals that the Stripe script is enqueued with `type="text/plain"` instead of `type="text/javascript"`, likely due to Cookiebot’s handling of cookie consent.
https://plugins.trac.wordpress.org/browser/cookiebot/trunk/src/lib/helper.php#L151

### Expected behavior

The WooPayments checkout button and Stripe payment fields should load and be fully functional on the checkout page in mobile view, without requiring additional manual actions. The Stripe JavaScript should load without interference from Cookiebot

### Additional context

Potential solution ideas include leveraging [JavaScript Proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to detect when `Stripe` is added to the `window` object and then triggering the initialization of WooPayments.

p1727770367173279-slack-CGGCLBN58
p1722007079535099-slack-CU6SYV31A

### PR DESCRIPTION
**Pull request by danielmx-dev**
Fixes #9709

#### Changes proposed in this Pull Request

* Change the `WCPayAPI#getStripe` method from synchronous to asynchronous. This allow us to wait for Stripe.js to load in scenarios where the script download may be delayed due to third party plugins that ask for user's consent (see details in #9709).

#### Testing instructions

* Enable the Cookiebot plugin
  * Configure it using the settings from [this comment](https://github.com/Automattic/woocommerce-payments/issues/9709#issuecomment-2483779586).
  * By default, the plugin may not block stripe-js in your site. To force it you'll need to do the following changes:
    * Use "Manual cookie-blocking mode" in the Cookiebot settings (WP Admin).
    * Update `Script_Loader_Tag::__construct` in the plugin code to always set the `script_loader_tag` filter.
    * Add the following line to the end of `Cookiebot_Addons::build_container` in the plugin code: `$this->container->get( 'Script_Loader_Tag_Interface' )->add_tag( 'stripe', array( 'marketing', 'statistics' ) );`
* Enable Express Checkout (Google Pay/Apple Pay) and one of the BNPL payment methods.

**Before**
* Go to the WooCommerce checkout page. Do not accept the cookie banner.
* WooPayments, Express Checkout, and BNPL PMME elements are all missing.
* The following error (or something similar, referring to an issue with the data type of stripe) should appear in the console: `ReferenceError: Stripe is not defined`
* If you accept the consent banner, the problem persists. Until you reload the page the problem goes away. 
* Clear the consent cookie to continue testing: `document.cookie =  'CookieConsent=; Path=/;';`
* The same happens for Classic Checkout, Cart and Product Pages.

After: 
* Go to the WooCommerce checkout page. Do not accept the cookie banner.
* WooPayments, Express Checkout, and BNPL PMME elements are all missing/loading.
* Accept the consent.
* The elements now should load without having to reload the page.
* Clear the cookie and repeat the process in Classic Checkout, Cart (Blocks and Classic), Product Pages, Add Payment Method, Pay for Order.

#### Regression Testing

Disable Cookiebot and verify that the same pages (Blocks/Classic Checkout, Cart (Blocks and Classic), Product Pages.) continue working as expected.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9770` or branch name `fix/9709-load-stripe-asynchronously` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9709-load-stripe-asynchronously) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 639293470ff8c158854d51ddf27d48e37d2a33d9
- Build time: 2024-11-26 15:36:29 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by mdmoore — COMMENTED** [review]
This was testing well with the initial test cases. When I attempted to test Pay for Order, I noticed the credit card form wasn't loading. Testing further while logged in, it seems Stripe JS isn't being loaded other pages like Checkout and Cart either. This is likely related to the the hardcoded changes in the Cookiebot plugin combined with the fact that the banner doesn't appear when logged in (so cookies can't be accepted), but I want to double check with you on this and whether you've been able to test while logged in?

**Comment by danielmx-dev** [comment]
> This was testing well with the initial test cases. When I attempted to test Pay for Order, I noticed the credit card form wasn't loading. Testing further while logged in, it seems Stripe JS isn't being loaded other pages like Checkout and Cart either. This is likely related to the the hardcoded changes in the Cookiebot plugin combined with the fact that the banner doesn't appear when logged in (so cookies can't be accepted), but I want to double check with you on this and whether you've been able to test while logged in?

I assume it may be related to this setting ? `Cookiebot CMP on front-end while logged in`

image

However, I'm not able to replicate the issue with the setting On or Off. I would assume that if the banner doesn't show up then the script shouldn't be blocked.

**Review by mdmoore — APPROVED** [review]
>I assume it may be related to this setting ? Cookiebot CMP on front-end while logged in

Yeah that did the trick for displaying the banner. With that setting off, Stripe.js never loads for logged in users in my testing. I know you're unable to reproduce it, so maybe it's something with my settings. Do you think this is something to be concerned about? If not, this has my approval.

**Comment by danielmx-dev** [comment]
> Yeah that did the trick for displaying the banner. With that setting off, Stripe.js never loads for logged in users in my testing. I know you're unable to reproduce it, so maybe it's something with my settings. Do you think this is something to be concerned about? If not, this has my approval.

What happens if you test the faulty scenario on develop? Although the behavior of the Cookiebot is concerning, I don't think the changes in this PR make the situation worse, if another plugin is just blocking our dependencies there's little we can do about it.

File: client/tokenized-express-checkout/index.js [hunk 1]
```diff
@@ -531,43 +532,35 @@ jQuery( ( $ ) => {
...
-								),
-								requestPhone:
-									getExpressCheckoutData( 'checkout' )
-										?.needs_payer_phone ?? false,
-								displayItems: transformCartDataForDisplayItems(
-									cartData
-								),
-							} );
-						}
+				const cartData = await getCartApiHandler().getCart();
```
Comment (frosso) [inline client/tokenized-express-checkout/index.js:535]: This change introduced a difference in how errors are handled.

Before the change, any errors by `getCart()` weren't propagated, and they could have just generated a warning in the console.

Now, there is no `try`/`catch`, so any errors from `getCart()` are being propagated and will lead to a termination of the execution.

@danielmx-dev let me know your thoughts - I reverted this in https://github.com/Automattic/woocommerce-payments/pull/9849

File: client/checkout/api/index.js [hunk 2]
```diff
@@ -51,20 +51,36 @@ export default class WCPayAPI {
...
+			await new Promise( ( resolve ) =>
+				setTimeout( resolve, waitInterval )
+			);
+			currentWaitTime += waitInterval;
+			if ( currentWaitTime > maxWaitTime ) {
+				throw new Error( 'Stripe object not found' );
+			}
+		}
+		return this.__getStripe( forceAccountRequest );
+	}
```
Comment (frosso) [inline client/checkout/api/index.js:75]: While commenting on the `try`/`catch` below, I noticed this implementation: I was wondering if you had considered leveraging [JavaScript Proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to detect when `Stripe` is added to the `window` object, rather than using a timeout in a loop.

I was also wondering if you had considered raising the error in a more user-friendly fashion, like in the payment method box, to allow the customer to review the cookies consent.
