### PR TITLE
Fix: Hide payment methods with domestic transactions restrictions (Klarna, Affirm, Afterpay) when conditions are not met

### LINKED ISSUE #8718: [Klarna] Error on non-domestic transactions for shoppers from supported countries
### Describe the bug

When the shopper is from a country supported by Klarna and the transaction isn't a domestic one, the following error gets displayed:

| Checkout error | Stripe error |
|--------|--------|
|  |  acct_1NsqFlFlHoxiQPiO / req_fKLp2r0WYVzA1A?t=1714078733 | 

This error seems to be related to Klarna only accepting domestic transactions, with the [exception of the EEA, UK, and Switzerland](https://docs.stripe.com/payments/klarna#:~:text=If%20you%E2%80%99re%20based%20in%20the%20EEA%2C%20UK%2C%20or%20Switzerland).

We already hide Klarna for unsupported customer countries, but we're not handling the domestic transaction restriction.

### To Reproduce

1. Connect your store to a Stripe account from a Klarna-supported country, like the US
2. Enable Klarna
3. As a shopper, add a product to your cart and proceed to checkout
4. As the billing country, select one different from the one your Stripe account is from, like UK
5. Place the order
6. Notice error mentioned above is displayed and that the payment can't be completed

### Actual behavior

The order can't be placed when using Klarna, even though it's displayed as an available payment method.

### Expected behavior

As a shopper, I'd expect Klarna not to be displayed if it's not available. Or maybe to have a less generic error message.

### Additional context

For reference, we're also seeing this behavior in the Stripe extension. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3096

### PR DESCRIPTION
**Pull request by danielmx-dev**
Fixes #8718

#### Changes proposed in this Pull Request

This PR performs a similar fix as the one performed here https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3108, the same PR description also applies here:

> Customers paying with Klarna, Affirm and Afterpay/Clearpay have specific cross border restrictions they must adhere to. ie Customers can only purchase from the same country the Stripe account is located. eg AU to AU. The one exception to this is Klarna where customers and merchants located in the European Economic Area (EEA) + the UK and Switzerland can also transact. eg a customer in the UK can transact with a merchant in Germany.
>
> This is documented in Stripe docs:
>
> https://docs.stripe.com/payments/klarna
> https://docs.stripe.com/payments/afterpay-clearpay
> https://docs.stripe.com/payments/affirm
> This PR implements this restriction by ensuring that the payment method is only enabled on checkout if the transaction is considered domestic using their respective ruleset.

The only significant difference in this PR, is that we also perform a currency check for Klarna and EEA/UK/CH purchases in order to validate that the presentment currency matches the customer's country. This prevents, for example, showing Klarna when the customer country is Spain (_ES_) but the currency is set to _GBP_, since Spain's domestic currency is _EUR_ (even if both currencies are technically supported).

##### Scenarios

Use these provided scenarios along with the instructions to validate the expected result. Please note that this list of scenarios is not exhaustive, but should cover the most significant combinations.

|  Payment Method | WooPayments<br/>Account Country | Store Currency | Customer Country | Visible during<br/>checkout |
|--------|--------|--------|--------|--------|
| Affirm / Afterpay | US | USD | US | ✅ |
| Affirm / Afterpay | US | CAD | US | ❌|
| Affirm / Afterpay | US | USD | CA | ❌ |
| Klarna | US | USD | US | ✅ |
| Klarna | US | CAD | US | ❌ |
| Klarna | US | USD | CA | ❌ |
| Klarna | BE* | EUR | BE* | ✅ |
| Klarna | BE* | GBP | BE* | ❌ |
| Klarna | BE* | EUR | ES | ✅ |

_*Note: You can replace Belgium (BE) with any of the countries in [this list](https://github.com/Automattic/woocommerce-payments/blob/fix/8718-restrict-klarna-non-domestic-transactions/includes/payment-methods/class-klarna-payment-method.php#L51-L84) (except Spain) to achieve the same results._

* Prerequisite: Using a WooPayments account onboarded using the scenario's **WooPayments Account Country**.
* Enable the **Payment Method** in the WooPayments settings.
* Set the **Store Currency** in the customer's My Account page or via the URL's query string `?currency=<Store Currency>`
* Add items to your cart worth for at least 50.00 in the current currency (some payment methods require minimum amounts).
* Go to checkout
* Change the country to **Customer Country**
* Based on the scenario, the **Payment Method**  should be **Visible during checkout** or not.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8980` or branch name `fix/8718-restrict-klarna-non-domestic-transactions` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8718-restrict-klarna-non-domestic-transactions) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9343e12b06b0218317ba1f4824b83c3239e04f2c
- Build time: 2024-06-20 13:37:09 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: tests/unit/payment-methods/test-class-klarna-payment-method.php [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+					Country_Code::AUSTRIA,
+					Country_Code::BELGIUM,
+					Country_Code::FINLAND,
+					Country_Code::GERMANY,
+					Country_Code::IRELAND,
+					Country_Code::ITALY,
+					Country_Code::NETHERLANDS,
+					Country_Code::SPAIN,
+				],
+			],
```
Comment (danielmx-dev) [inline tests/unit/payment-methods/test-class-klarna-payment-method.php:138]: Although this is a valid scenario, currently there is not way to manually test it due to the limitations described here https://github.com/Automattic/woocommerce-payments/issues/8718#issuecomment-2176846641 Which should be addressed as part of a new issue.

**Review by brettshumaker — APPROVED** [review]
Thanks for getting this fixed!
