### PR TITLE
Negative balance deposit notice will only show when total balance is below 0

### LINKED ISSUE #6941: `Deposits may be interrupted while your WooPayments balance remains negative` message erroneously shown for instant payouts merchants
### Describe the bug
When an instant deposit is initiated, there's a transfer for the instant deposit fee.

This can produce a negative `Available funds` balance at **Payments > Overview.** This will trigger the following notice on the same page in the `Deposits` card...

```
Deposits may be interrupted while your WooPayments balance remains negative.
```

...even though the negative `Available funds` balance is countered by a positive `Pending funds` balance.

### To Reproduce
I haven't reproduced this personally yet, but theoretically:

1. Purchase goods/services.
2. Trigger an instant deposit.
3. Check the `Deposits` card.
4. Notice the message about the negative balance.

### Actual behavior
Instant Deposits is a feature of WooPayments, and the transfer associated with it can erroneously display that an account has a negative balance temporarily. This can lead to confusion for merchants.

### Screenshots

Markup on 2023-08-06 at 15:08:30

### Expected behavior

This information is pulled directly from the Stripe dashboard and should be temporary while funds are moved around. However, I think that the negative balance notice here should only show if `Available funds` + `Pending funds` < `0`. Currently, the message appears to only rely on the `Available funds` balance.

### Additional context

6614021-zen

### PR DESCRIPTION
**Pull request by brucealdridge**
Fixes #6941 

#### Background
If a merchant initiates an Instant Deposit, the merchant can be left in a place where available funds are below $0 and the pending funds are above $0.

image

WooPayments charges a fee for instant deposits. In the case above, $2.44 is the fee which has been paid out of the available balance, leading to the negative value (which before the instant deposit was $0.) The pending balance of $2.44 is the remainder left after the Instant deposit. 

#### Changes proposed in this Pull Request

> Deposits may be interrupted while your WooPayments balance remains

A BannerNotice that shows when the merchants balance is negative only takes into account the available balance. This PR updates this logic to take into account the total (pending+available) balance.

#### Testing instructions

* Make sure instant deposits are enabled (I forced this by enabling `instant_deposits_eligible` on the server.)
* Start with a 0 total balance.
* Purchase a cart worth around $100 (to stay within the instant deposit limits.)
* Initiate an instant deposit
* Confirm that available and pending balances total to $0.
* With this change, the banner notice will not show.

Screenshot 2024-02-02 at 2 45 22 PM
Screenshot 2024-02-02 at 2 45 31 PM

-------------------

- [x] Run `npm run changelog`
- [x] Covered with tests.
- [x] Tested on mobile - does not apply

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8117` or branch name `fix/6941-warning-for-negative-balance` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/6941-warning-for-negative-balance) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 2eabbaefa76eb282885480ad9117c6d9195ce73c
- Build time: 2024-02-06 21:31:26 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: changelog/fix-6941-warning-for-negative-balance [hunk 1]
```diff
@@ -0,0 +1,5 @@
+Significance: patch
+Type: fix
+Comment: Negative balance notice will only show when total balance is below 0.
```
Comment (haszari) [inline changelog/fix-6941-warning-for-negative-balance]: I think it would be clearer to name the bug head on. E.g. something like "Fixed a bug where the 'deposits paused while balance is negative' notice was erroneously shown after an instant deposit".

File: client/components/deposits-overview/index.tsx [hunk 2]
```diff
@@ -49,9 +49,10 @@ const DepositsOverview: React.FC = () => {
 
 	const availableFunds = overview?.available?.amount ?? 0;
 	const pendingFunds = overview?.pending?.amount ?? 0;
+	const totalFunds = availableFunds + pendingFunds;
```
Comment (haszari) [inline client/components/deposits-overview/index.tsx:54]: Interesting to see this `Total balance` concept emerging in the code!

- #8070

File: client/components/deposits-overview/index.tsx [hunk 3]
```diff
@@ -49,9 +49,10 @@ const DepositsOverview: React.FC = () => {
...
 
-	// If the available balance is negative, deposits may be paused.
-	const isNegativeBalanceDepositsPaused = availableFunds < 0;
+	// If the total balance is negative, deposits may be paused.
+	const isNegativeBalanceDepositsPaused = totalFunds < 0;
```
Comment (haszari) [inline client/components/deposits-overview/index.tsx:61]: Simple fix! Though… is it possible that a merchant could have deposits paused because their available balance is negative (large recent dispute/refund) yet with a positive total balance due to large recent purchases in pending? If so we might need to take care.

**Review by haszari — APPROVED** [review]
Looks good, I have not yet tested because my site is not eligible for instant (too many recent disputes!).

I _think_ the logic is fine here but there is a chance this could miss a case where deposits are actually paused. Not sure if that's likely or much of a risk, but might be worth exploring to be sure.

File: client/components/deposits-overview/index.tsx (hunk 3 above)
Comment (brucealdridge) [reply client/components/deposits-overview/index.tsx:61]: > Though… is it possible that a merchant could have deposits paused because their available balance is negative (large recent dispute/refund) yet with a positive total balance due to large recent purchases in pending?

If this was the case. Pending would move to Available within a few days restoring the available balance and the standard copy would suffice ie `Available funds are automatically dispatched every day`

File: changelog/fix-6941-warning-for-negative-balance (hunk 1 above)
Comment (brucealdridge) [reply changelog/fix-6941-warning-for-negative-balance]: Updated.

File: changelog/fix-6941-warning-for-negative-balance [hunk 4]
```diff
@@ -0,0 +1,5 @@
+Significance: patch
+Type: fix
+Comment: Fixed a bug where the 'deposits paused while balance is negative' notice was erroneously shown after an instant deposit.
```
Comment (Jinksi) [inline changelog/fix-6941-warning-for-negative-balance]: Is this intentionally a "placeholder" changelog entry, or should it be a user-facing changelog entry?

Comment (brucealdridge) [reply changelog/fix-6941-warning-for-negative-balance]: TIL regarding user-facing changelogs. I always just use best judgement. Updated in https://github.com/Automattic/woocommerce-payments/pull/8117/commits/24975379bc7a6fa1752def09b12e02c1c467986c, thanks.

File: client/components/deposits-overview/index.tsx (hunk 3 above)
Comment (haszari) [reply client/components/deposits-overview/index.tsx:61]: Sounds good to me :)

File: changelog/fix-6941-warning-for-negative-balance (hunk 4 above)
Comment (Jinksi) [reply changelog/fix-6941-warning-for-negative-balance]: User-facing is also just how I approach it, unsure if there are specific guidelines for this 🙈
