### PR TITLE
Fix QIT warning in WooPay session endpoint

### LINKED ISSUE #8732: [QIT] Warning in `class-wc-rest-woopay-session-controller.php`
### Context

This warning was caught during the release cycle after running the QIT tests against the `develop` branch. This was introduced by #8645.

### Message

> The use of function wp_set_current_user() is discouraged

### Source

> Generic.PHP.ForbiddenFunctions.Discouraged

### File

[includes/admin/class-wc-rest-woopay-session-controller.php:63](https://github.com/Automattic/woocommerce-payments/blob/3c6bba13c5340c5ea0927fb621c76cba32554a1c/includes/admin/class-wc-rest-woopay-session-controller.php#L63)

### PR DESCRIPTION
**Pull request by cesarcosta99**
Fixes #8732.

#### Changes proposed in this Pull Request

This PR tweaks the WooPay session REST endpoint by replacing a `wp_set_current_user` approach with an existent approach designed specifically for WooPay.

#### Testing instructions

**Pre-requisites**

1. Ensure the WooPay direct checkout flow is enabled: `npm run wp option update _wcpay_feature_woopay_direct_checkout 1`.
2. As a customer, log in into WooPay, if needed.
3. As a customer, log in into WooPayments, if needed.

**Test: current approach to note current user and customer**

1. Checkout to `develop` branch.
2. Ensure you have third party cookies disabled in your browser.
    2.1. Alternatively, you can comment [this line](https://github.com/Automattic/woocommerce-payments/blob/e217e54410c471816dd168bdca512ead31ec6f9f/client/checkout/woopay/direct-checkout/index.js#L28). But if you're going down this path you'll need to build the assets: `npm run build:client`.
4. Navigate to the merchant site, add an item to the cart and navigate to the cart.
5. Enable the debugger on WooPayments and add a breakpoint to [this line](https://github.com/Automattic/woocommerce-payments/blob/414fb3dc993351c16b70b02ced17df4dd2deaaaf/includes/woopay/class-woopay-session.php#L407).
6. Click on the **Proceed to checkout** button.
7. When you hit the breakpoint, note the user ID and customer ID.
8. After hitting play on the debugger, you should land on the WooPay checkout page.

**Test: determine current user approach works as expected**

1. Checkout to this branch.
2. Ensure you have third party cookies disabled in your browser.
    2.1. Alternatively, you can comment [this line](https://github.com/Automattic/woocommerce-payments/blob/e217e54410c471816dd168bdca512ead31ec6f9f/client/checkout/woopay/direct-checkout/index.js#L28). But if you're going down this path you'll need to build the assets: `npm run build:client`.
3. Navigate to the merchant site, add an item to the cart and navigate to the cart.
4. Enable the debugger on WooPayments and add a breakpoint to [this line](https://github.com/Automattic/woocommerce-payments/blob/414fb3dc993351c16b70b02ced17df4dd2deaaaf/includes/woopay/class-woopay-session.php#L407).
5. Click on the **Proceed to checkout** button.
6. When you hit the breakpoint, verify the user ID and customer ID are the same you noted in step 6 in the previous test.
7. After hitting play on the debugger, you should land on the WooPay checkout page.

**Test: QIT warning has been fixed**

1. Setup [QIT tests](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/qit/README.md#setup-and-running), if needed.
2. Run `npm run test:qit`.
3. [Analyze the results](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/qit/README.md#analysing-results) and make sure the warning reported in #8732 is gone.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8760` or branch name `fix/8732-qit-warning` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8732-qit-warning) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 980a5b6d1d9a4a5ea61a6f506e71f4d1c39b7ce1
- Build time: 2024-05-02 15:38:00 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/admin/class-wc-rest-woopay-session-controller.php [hunk 1]
```diff
@@ -89,31 +78,6 @@ public function check_permission() {
 		return $this->is_request_from_woopay() && $this->has_valid_request_signature();
```
Comment (bborman22) [inline includes/admin/class-wc-rest-woopay-session-controller.php:78]: These checks are redundant now, but considering leaving them in as they are low-cost and would prevent accidentally removing them from another place and leaving this open. It also satisfies the goal of having defined check permissions. Let me know what you think though about this redundancy?

**Review by bborman22 — APPROVED** [review]
I was able to test this in a few ways and confirmed that it all worked as expected. Some of the ways I tested this:

- Confirmed that adding the URL to the woopay session list allowed it to process the `determine_current_user_for_woopay` using the Cart Token.
- Confirmed that within `get_init_session_request` the same `$customer_id` was returned for each session through multiple attempts as well as through using Direct Checkout, Express Checkout, or OTP modal.
- Confirmed that when testing from the sandbox the `has_valid_request_signature` was properly verifying or failing the requests.

This seems like a strong move to centralize this logic in one place and removes the warning about a dangerous function and instead uses the more recommended `determine_current_user` filter. 

Overall, everything tested well for me. I had one note about redundancy that you can share your opinion on, but it's not a blocker in my opinion.

File: includes/admin/class-wc-rest-woopay-session-controller.php (hunk 1 above)
Comment (cesarcosta99) [reply includes/admin/class-wc-rest-woopay-session-controller.php:78]: I agree with everything you said. This is now redundant, but better be redundant and safe than taking an unnecessary risk of leaving it open, especially with this redundancy being low-cost.
