### PR TITLE
BNPL - Fix error adding variable product to cart in some themes

### LINKED ISSUE #6819: [6.2.0] Invalid value for paymentMethodMessaging.update() when attempting to configure a variable product with the Flatsome theme active
### Describe the bug
When using [the Flatsome theme](https://flatsome3.uxthemes.com/) while WooPayments 6.2.0 is active, variable products cannot be added to the cart. Doing so produces an error notice when adding the product to the cart:

```
Please select some product options before adding this product to your cart.
```

After selecting all available variables—but before attempting to add the product to the cart—a JavaScript error is thrown in the console:

```
Uncaught IntegrationError: Invalid value for paymentMethodMessaging.update(): amount should be a positive amount in the currency's subunit. You specified: NaN.
    at ne (?ver=3.0:1:144524)
    at re (?ver=3.0:1:144596)
    at ?ver=3.0:1:186667
    at et (?ver=3.0:1:186693)
    at Object.update (?ver=3.0:1:217483)
    at t.<anonymous> (?ver=3.0:1:277609)
    at t.update (?ver=3.0:1:64872)
    at HTMLDivElement.<anonymous> (??-eJyNkMFqAzEMRH+oWqeHJumh9FOCaqmOUtvaWNqY/fvupgQCIVDQRWjmMaM+QtTqXD2MeUpSLcziR+iqUUvhFhm62DGLeUAzdgunZc4Tt3n4k8aehyJ1ONlLf8Tdke4A3+0qo4BE4AoRm8MFm6CL1v/hYMS5LDcLtKYbm9IUHYgdJdsTP/6IFfZwkBpvC9zSPPEk1ZQZ1h9ITQZYCZCuPb4myRSSYwK+rFkWxGf5eN3u33e7zeZt+wu4d4ZI:3:1530)
    at HTMLDivElement.dispatch (jquery.min.js?ver=3.6.4:2:43184)
    at y.handle (jquery.min.js?ver=3.6.4:2:41168)
```

This error is thrown on selection, and the selection event is not firing as a result.

Reverting to 6.1.1 resolves this issue. Given that reverting resolves the issue and the popularity of Flatsome, I'm opening this issue :)

**Note**: Reverting to Woo 7.8.0 or disabling multi-currency did not resolve the issue. Changing to a different theme does resolve the issue.

### To Reproduce

1. Install/activate Flatsome.
2. Install/activate WooPayments 6.2.0.
3. Create a variable product.
4. Attempt to add the product created in step 3 to the cart.
5. See errors.
6. Revert to WooPayments 6.1.1.
7. Repeat step 4.
8. The product will be successfully added to the cart.

### Actual behavior
While WooPayments 6.2.0 and the Flatsome theme are active, customers cannot add variable products to the cart because the selection event is not firing.

### Screenshots
Markup on 2023-07-19 at 19:56:43

### Expected behavior
WooPayments 6.2.0 + Flatsome allows variable products to be added to the cart without issue.

### Additional context
Discussion: p1689800687243289-slack-C3NCP7ZJ6

Initial reports: 
6556641-zen
6556849-zen
6557129-zen

### PR DESCRIPTION
**Pull request by nagpai**
Fixes #6819 

#### Changes proposed in this Pull Request

* Prevent the error in some themes, like Flatsome, that blocks adding of variable product to cart by targeting and reading the quantity div correctly.
* Prevent the BNPL Payment Messaging element from rendering when BNPL payment methods are turned off or not available. 

#### Testing instructions

* Check out this branch on WCPay client
* Make sure you have Afterpay and Affirm are both disabled on the test site, to begin with.
* Install Flatsome theme on your test site
* Browse to the product page of a variable product
* Select some variation and try adding it to the cart
* Try with a different quantity too
* In each of the case you should not see any errors - neither popups, nor any errors in the browser console
* Within the browser console, browse the HTML code of the page. You **should not** see a div with id `payment-method-message`
* Repeat the steps with Affirm and Afterpay enabled
* As expected, you should see relevant offers depending on what product variation and quantity you select

##### Optional testing tip 

This is a tip to visually see if the messaging element is hooked, and hence if `payment-method-message` is rendered. 

Within `WP Admin > Appearance > Customize >> Additional CSS` add this CSS snippet: 

```
#payment-method-message {
    background-color: yellow;
    min-height: 30px;
}
```
Make sure you remove this snippet after testing!

If you checkout to a different branch including `develop` at the moment, and keep BNPL methods disabled, you will see a yellow patch indicating that the messaging hook is active.  
image

If you checkout this branch, you will not see it, since this branch prevents the messaging hook from getting inserted if there are no BNPL methods enabled.  
image

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6845` or branch name `fix/6819-afterpay-variable-product-messaging-on-flatsome` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6819-afterpay-variable-product-messaging-on-flatsome) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b8145e7aa944ca848b9fb1fa2ccab04036342a00
- Build time: 2023-07-24 20:21:09 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payments.php [hunk 1]
```diff
@@ -561,6 +559,16 @@ public static function init() {
 
 		self::maybe_display_express_checkout_buttons();
 
+		// Insert the Stripe Payment Messaging Element only if there is at least one BNPL method enabled.
+		$activated_bnpl_payment_methods = array_intersect(
+			Payment_Method::BNPL_METHODS,
+			self::get_gateway()->get_upe_enabled_payment_method_ids()
+		);
+
+		if ( ! empty( $activated_bnpl_payment_methods ) ) {
```
Comment (kalessil) [inline includes/class-wc-payments.php]: `if ( [] !== $activated_bnpl_payment_methods )` would be a better fit for out strict types conventions.

File: includes/class-wc-payments.php [hunk 2]
```diff
@@ -561,6 +559,16 @@ public static function init() {
 
 		self::maybe_display_express_checkout_buttons();
 
+		// Insert the Stripe Payment Messaging Element only if there is at least one BNPL method enabled.
+		$activated_bnpl_payment_methods = array_intersect(
+			Payment_Method::BNPL_METHODS,
+			self::get_gateway()->get_upe_enabled_payment_method_ids()
+		);
+
```
Comment (kalessil) [inline includes/class-wc-payments.php]: To keep things logically bundled, it's better to drop this empty line.

File: includes/constants/class-payment-method.php [hunk 3]
```diff
@@ -39,4 +39,9 @@ class Payment_Method extends Base_Constant {
 		self::CARD_PRESENT,
 		self::INTERAC_PRESENT,
 	];
+
+	const BNPL_METHODS = [
```
Comment (kalessil) [inline includes/constants/class-payment-method.php]: That's a nice change. Let's change the name to `BNPL_PAYMENT_METHODS` - it sounds a bit better in this specific case.

File: includes/class-wc-payments.php [hunk 4]
```diff
@@ -561,6 +559,16 @@ public static function init() {
 
 		self::maybe_display_express_checkout_buttons();
 
+		// Insert the Stripe Payment Messaging Element only if there is at least one BNPL method enabled.
+		$activated_bnpl_payment_methods = array_intersect(
```
Comment (kalessil) [inline includes/class-wc-payments.php]: Given the context, the naming should be `enabled_bnpl_payment_methods` - because of `howget_upe_enabled_payment_method_ids` is named.

File: includes/class-wc-payments-payment-method-messaging-element.php [hunk 5]
```diff
@@ -48,16 +48,16 @@ public function __construct( WC_Payments_Account $account, $gateway ) {
...
+		$currency_code      = get_woocommerce_currency();
+		$store_country      = WC()->countries->get_base_country();
+		$billing_country    = WC()->customer->get_billing_country();
 		$product_variations = [
 			'base_product' => [
 				'amount'   => WC_Payments_Utils::prepare_amount( $product->get_price(), $currency_code ),
 				'currency' => $currency_code,
 			],
 		];
+
```
Comment (kalessil) [inline includes/class-wc-payments-payment-method-messaging-element.php]: Re-grouping `product_variations` in this case is not making sense, it logically belongs to foreach-construct.

**Review by kalessil — CHANGES_REQUESTED** [review]

File: includes/class-wc-payments.php (hunk 1 above)
Comment (nagpai) [reply includes/class-wc-payments.php]: Thanks for the early review 🙌 

I have removed this here - 8275876

File: includes/class-wc-payments.php (hunk 2 above)
Comment (nagpai) [reply includes/class-wc-payments.php]: Sure. I have removed it here - 8275876

File: includes/constants/class-payment-method.php (hunk 3 above)
Comment (nagpai) [reply includes/constants/class-payment-method.php]: Thank you! I have renamed it. 8275876

File: includes/class-wc-payments.php (hunk 4 above)
Comment (nagpai) [reply includes/class-wc-payments.php]: That makes sense. Earlier somewhere I got confused with `enabled` meaning enabled at Stripe vs that on the site. But things are clear now. I have renamed this! - 8275876

File: includes/class-wc-payments-payment-method-messaging-element.php (hunk 5 above)
Comment (nagpai) [reply includes/class-wc-payments-payment-method-messaging-element.php]: That makes sense. I have regrouped this with the foreach-construct since they are logically connected. 8275876

**Review by kalessil — APPROVED** [review]
LGTM (code review only).

**Review by mgascam — APPROVED** [review]
LGTM!
✅ Code looks good, I liked the suggestion to use CSS to test the presence of the block.
✅ Followed testing instructions and works as expected. No errors thrown to the console and products get added to the cart
