### PR TITLE
Fix multi-currency autoload issue when plugin gets updated

### LINKED ISSUE #9676: [GlobalStep] PHP Fatal error appears after updating the WooPayment plugin to 8.5.0-test-2 version.
### Describe the bug
PHP Fatal error appears after updating the WooPayment plugin to 8.5.0-test-2 version.

### Environment:
Woocommerce Version: WooCommerce  9.4.0-rc.2
WooCommerce Payments: 8.5.0-test-2
WordPress version: v6.7-RC2

PC:
Windows 10,
Chrome(Version 130.0.6723.92)
Firefox (Version 132.0.1)

### Steps To Reproduce:
1. Create any test site.
2. Install and activate all the required plugins.
3. Install and activate the Woocommerce version 9.4.0-rc.2 plugins.
4. Install the latest stable version of WooCommerce Payments via WP-ADMIN -> Plugins page.
5. Complete WooCommerce Payments KYC flow.
6. Go to WP-ADMIN -> Plugins & click on Upload Plugin to upload the testing package(i.e.8.5.0-test-2 version).
7. Observe that, PHP Fatal error appears after updating the WooPayment plugin to 8.5.0-test-2 version.

### Instruction Link:
https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#plugin-update-via-plugins-page

### Actual behavior
PHP Fatal error appears after updating the WooPayment plugin to 8.5.0-test-2 version.

### Expected behavior
WooPayment plugin(8.5.0-test-2 version) should be updated successfully without any errors.

### Screenshots
Image

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.4.0-rc.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7-RC2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.30
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.10.1
OpenSSL/3.0.14

SUHOSIN Installed: –
MySQL Version: 10.11.9-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 2
revision: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Code Snippets: by Code Snippets Pro – 3.6.5.1
Query Monitor: by John Blackbourn – 3.16.4
WooPayments: by WooCommerce – 8.5.0-test-2
WooCommerce: by Automattic – 9.4.0-rc.2
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.6.1

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 300 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/error.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/srv/htdocs/wp-content/plugins/woocommerce/templates/block-notices/success.php


### WooPayments ###

Version: 8.5.0-test-2
Connected to WPCOM: Yes
WPCOM Blog ID: 238714765
Account ID: acct_1QHm4uCSAHSKSD8L
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Enabled (product,cart,checkout)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-11-06 12:39:23 +00:00
Options: ✔
Notes: 58
Onboarding: skipped

### Action Scheduler ###

Complete: 5
Oldest: 2024-11-05 12:39:43 +0000
Newest: 2024-11-05 12:51:18 +0000

Pending: 1
Oldest: 2024-11-06 12:39:43 +0000
Newest: 2024-11-06 12:39:43 +0000


### Status report information ###

Generated at: 2024-11-05 14:01:40 +00:00
```
</details>

### PR DESCRIPTION
**Pull request by ricardo**
Fixes #9676

#### Changes proposed in this Pull Request

This issue happens because of the caveat explained in [this comment](https://github.com/Automattic/jetpack/issues/35348#issuecomment-2457621556):
1. The Jetpack autoloader loads the multi-currency module.
2. The upgrade process begins.
3. The multi-currency paths change.
4. The upgrade process finishes.
5. The `woocommerce_get_settings_pages` [hook](https://github.com/Automattic/woocommerce-payments/blob/b670b857d338bd9b3234583c44422b71b3c07d68/includes/multi-currency/MultiCurrency.php#L224) is called and the callback function fails to resolve `Settings`.

For this reason and to avoid other potential risks, we're moving the multi-currency PHP source files back to their original paths.

This is an intermediary step until we rename the module's namespace and decouple it further from the gateway.

We are also adding a [`did_action( 'upgrader_process_complete' )`](https://github.com/Automattic/woocommerce-payments/blob/cccd63e468e90d2dee538f2d8f99523fe3b89104/includes/multi-currency/MultiCurrency.php#L368) to prevent the same issue from happening in the future.

#### Testing instructions

**Test: Reproduce the issue and validate fix**

Note: Remember to install the Query Monitor plugin to be able to see the error on JN.
Note<sub>ii</sub>: Remember to remove WooPayments and reinstall it from WPORG before repeating the test.

Follow instructions in #9676.

Run `npm run build:release` and upload the contents from `/release/woocommerce-payments` from `develop` and from this branch to reproduce and later to ensure the issue is fixed.

**Test: Ensure the issue won't repeat in future upgrades**

To ensure the same error won't happen in future releases, we should simulate an autoloaded path change by changing the current plugin and uploading a build from `develop`:

1. From this branch, run `npm run build:release` and upload a zip from `/release/woocommerce-payments`.
2. Switch to `develop`, run the `build:release` script and upload a zip on top of the previous one.
3. Ensure the issue is not reproducible thanks to [`did_action( 'upgrader_process_complete' )`](https://github.com/Automattic/woocommerce-payments/blob/cccd63e468e90d2dee538f2d8f99523fe3b89104/includes/multi-currency/MultiCurrency.php#L368) from this branch.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9681` or branch name `fix/9676-multi-currency-autoload` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9676-multi-currency-autoload) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: bbe3b0e9d47ea5c6800cfbaa6254a74b57021535
- Build time: 2024-11-07 05:29:21 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/multi-currency/MultiCurrency.php [hunk 1]
```diff
@@ -364,6 +364,11 @@ public function init_settings_pages( $settings_pages ): array {
 			return $settings_pages;
 		}
 
+		// Due to autoloader limitations, we shouldn't initiate MCCY settings if the plugin was just upgraded: https://github.com/Automattic/woocommerce-payments/issues/9676.
```
Comment (lovo-h) [inline includes/multi-currency/MultiCurrency.php]: Nit: Should we split this line into two, for readability:
```suggestion
		// Due to autoloader limitations, we shouldn't initiate MCCY settings if the plugin was just upgraded:
		// https://github.com/Automattic/woocommerce-payments/issues/9676.
```

File: webpack/shared.js [hunk 2]
```diff
@@ -115,14 +115,14 @@ module.exports = {
 		extensions: [ '.ts', '.tsx', '.json', '.js', '.jsx' ],
 		modules: [
 			path.join( process.cwd(), 'client' ),
-			path.join( process.cwd(), 'multi-currency', 'client' ),
+			path.join( process.cwd(), 'includes/multi-currency', 'client' ),
```
Comment (lovo-h) [inline webpack/shared.js]: Nit: This could also be the following:
```javascript
path.join( process.cwd(), 'includes/multi-currency/client' ),
```

File: webpack/shared.js [hunk 3]
```diff
@@ -115,14 +115,14 @@ module.exports = {
...
 			'node_modules',
 		],
 		alias: {
 			assets: path.resolve( process.cwd(), 'assets' ),
 			'multi-currency': path.resolve(
 				process.cwd(),
-				'multi-currency',
+				'includes/multi-currency',
```
Comment (lovo-h) [inline webpack/shared.js]: Nit: This could also be the following:
```javascript
path.join( process.cwd(), 'includes/multi-currency/client' ),
```

File: tasks/release.js [hunk 4]
```diff
@@ -43,9 +43,8 @@ rm( 'dist/*.map' );
 // copy the directories to the release folder
 cp( '-Rf', filesToCopy, targetFolder );
 
-// copy the multi-currency files
-mkdir( '-p', targetFolder + '/multi-currency' );
-cp( '-R', 'multi-currency/src', targetFolder + '/multi-currency/src' );
+// remove the multi-currency/client source files
```
Comment (lovo-h) [inline tasks/release.js]: I was wondering why previously we were copying from `multi-currency/src` to `release/woocommerce-payments/multi-currency/src` and now we are just deleting the `/includes/multi-currency/client`.

Should we add a note explaining why we removed this directory (e.g. `/includes/multi-currency/client`)? What do you think about adding the following?
```
Note: The '/includes/multi-currency/client' directory is removed because
`/includes/multi-currency/*` are server-side files. Furthermore, the `./client` directory is
already included in the `dist` directory during the `npm run build:client` step.
```

**Review by lovo-h — CHANGES_REQUESTED** [review]
Nice work! Code changes look good and test well.

There were just a few comments we should take care of before merging.

**Test Instructions**
* 🟢 Test: Reproduce the issue and validate fix.
* 🟢 Test: Ensure the issue won't repeat in future upgrades.

File: webpack/shared.js (hunk 2 above)
Comment (ricardo) [reply webpack/shared.js]: Good call. Fixed in https://github.com/Automattic/woocommerce-payments/pull/9681/commits/e9d01c6b9755b07d72305e5c8ff4d50e1bb0f386.

File: tasks/release.js (hunk 4 above)
Comment (ricardo) [reply tasks/release.js]: > I was wondering why previously we were copying from multi-currency/src to release/woocommerce-payments/multi-currency/src and now we are just deleting the /includes/multi-currency/client.

This is because `includes` gets copied entirely [here](https://github.com/Automattic/woocommerce-payments/blob/bbe3b0e9d47ea5c6800cfbaa6254a74b57021535/tasks/release.js#L18), so instead of copying `multi-currency` from root and then deleting `multi-currency/client` we were simply copying `multi-currency/src`.

I agree this deserves better clarification, so I added a comment from your suggestion in https://github.com/Automattic/woocommerce-payments/pull/9681/commits/bbe3b0e9d47ea5c6800cfbaa6254a74b57021535.

**Review by lovo-h — APPROVED** [review]
The latest changes LGTM :shipit:
