### PR TITLE
Prevent challenging Klarna inquiries

### LINKED ISSUE #9703: Evidence submitted for Klarna Inquiries is ignored by Stripe
### Describe the bug

In WooPayments, we allow evidence submission for Klarna inquires, but this evidence is not considered by Stripe/Klarna. Evidence submission should be disabled for Klarna inquiries and copy should be added to help the merchants respond appropriately.

Available options for responding to Klarna Inquires
- Refund the payment
- Communicate with the customer to resolve the issue
- Wait for the inquiry to become a dispute to submit evidence.

### Changes required

Image

- [Email body copy](https://github.com/Automattic/woocommerce-payments/blob/bc057e7fc13716a1a26022f2c1e675b81994af0b/client/payment-details/dispute-details/dispute-steps.tsx#L196-L201) could be refined (Email the customer link)
  - `you disputed a $<amount> charge`. The customer likely has no knowledge of "dispute" may have initiated a "return"
  - Suggests `calling the number on the back of your card`
- [Remove](https://github.com/Automattic/woocommerce-payments/blob/bc057e7fc13716a1a26022f2c1e675b81994af0b/client/payment-details/dispute-details/dispute-steps.tsx#L243-L246) `Submit evidence <submitEvidenceIcon/> or ` 

It would be helpful to add some additional copy about the Klarna dispute process. @aheckler is it worth adding something to the docs that we can link to?

### Additional context

pdjTHR-3qO-p2#comment-6397

### PR DESCRIPTION
**Pull request by brucealdridge**
Fixes #9703 

#### Changes proposed in this Pull Request

Evidence submitted for Klarna inquiries are ignored by Stripe. This PR removes the ability to submit evidence for Klarna inquiries.

Changes for Klarna Inquiries:
 - "Submit Evidence" button hidden
 - Steps to respond updated to remove reference to "Submit Evidence" 
 - "Email the customer" mailto link updated to remove references to disputes in email body.

It's worth noting that submitting evidence is not blocked, the merchant can still manually navigate to `/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fdisputes%2Fchallenge&id=<dispute_id>` to challenge the inquiry. While it would be possible to prevent this I opted for the simple approach. If we decided to prevent access to this page, API calls should also be blocked by the same logic. 

**Before**

image

**After**

image

**Email Copy Changes**
```diff
Hello <name>,

-We noticed that on <inquiry date>, you disputed a <amount> charge on <purchase date>. We wanted to contact you to make sure everything was all right with your purchase and see if there's anything else we can do to resolve any problems you might have had.
+We noticed that on <inquiry date>, you raised a question with your payment provider about a <amount> charge made on <purchase date>. We wanted to reach out to ensure everything is all right with your purchase and to see if there’s anything we can do to resolve any problems you might have had.

-Alternatively, if the dispute was a mistake, you can easily withdraw it by calling the number on the back of your card. Thank you so much - we appreciate your business and look forward to working with you.
+Alternatively, if this was a mistake please contact your payment provider to resolve it. Thank you so much - we appreciate your business and look forward to working with you.
```

**Email Copy**

Screenshot 2024-11-18 at 5 13 50 PM

#### Testing instructions

1. Enable Klarna as an alternate payment method in WooPayments
2. Purchase a cart using Klarna with the customer email address `customer+disputed-return@email.us`
3. Visit `WooPayments > Disputes` and click on the newly created Klarna Inquiry (this may take a few minutes to show up)
4. Confirm `Submit Evidence` does not show up.
5. Click "Email the customer" to confirm the mailto copy doesn't mention disputes.

#### Other Considerations

The `DisputeNotice` component has not been updated. There is a bit of a contradiction between the notice and the docs

image

> You can challenge their claim if you believe it’s invalid. Not responding will result in an automatic loss - `DisputeNotice`

>  Card issuers can convert inquiries to disputes at their discretion - [WooPayments Docs](https://woocommerce.com/document/woopayments/fraud-and-disputes/managing-disputes/#inquiries:~:text=Card%20issuers%20can%20convert%20inquiries%20to%20disputes%20at%20their%20discretion)

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9741` or branch name `fix/9703-klarna-inquiries` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9703-klarna-inquiries) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 2725bb94aa94bd973fa4b7cc8f0c2e251d639832
- Build time: 2024-11-20 00:12:24 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by nagpai** [comment]
#### Manual test

Manual tests check well. 

✅ Confirm Submit Evidence does not show up.



✅ Click "Email the customer" to confirm the mailto copy doesn't mention disputes.

image

File: client/payment-details/dispute-details/dispute-steps.tsx [hunk 1]
```diff
@@ -195,8 +197,8 @@ export const InquirySteps: React.FC< Props > = ( {
 			// Translators: %1$s is the customer name, %2$s is the dispute date, %3$s is the dispute amount with currency-code e.g. $15 USD, %4$s is the charge date.
 			__(
 				`Hello %1$s,\n\n` +
-					`We noticed that on %2$s, you disputed a %3$s charge on %4$s. We wanted to contact you to make sure everything was all right with your purchase and see if there's anything else we can do to resolve any problems you might have had.\n\n` +
-					`Alternatively, if the dispute was a mistake, you can easily withdraw it by calling the number on the back of your card. Thank you so much - we appreciate your business and look forward to working with you.`,
+					`We noticed that on %2$s, you raised a question with your payment provider about a %3$s charge made on %4$s. We wanted to reach out to ensure everything is all right with your purchase and to see if there’s anything we can do to resolve any problems you might have had.\n\n` +
+					`Alternatively, if this was a mistake please contact your payment provider to resolve it. Thank you so much - we appreciate your business and look forward to working with you.`,
```
Comment (nagpai) [inline client/payment-details/dispute-details/dispute-steps.tsx]: A small grammar suggestion - add a comma after `mistake`: 

```suggestion
					`Alternatively, if this was a mistake, please contact your payment provider to resolve it. Thank you so much - we appreciate your business and look forward to working with you.`,
```

File: client/payment-details/dispute-details/dispute-awaiting-response-details.tsx [hunk 2]
```diff
@@ -204,6 +206,10 @@ const DisputeAwaitingResponseDetails: React.FC< Props > = ( {
 		isDisputeAcceptRequestPending,
 	} );
 
+	const isDefendable = ! (
```
Comment (nagpai) [inline client/payment-details/dispute-details/dispute-awaiting-response-details.tsx:209]: It is a good idea to call it `isDefendable` instead of `isKlarnaInquiry`. Since at a later date if there are any other new conditions, the logic can be added here. Makes it reusable.

**Review by nagpai — APPROVED** [review]
The code changes look good, and the manual tests check out very well too. 

I have left a minor grammatical suggestion. It looks good to go!

**Comment by haszari** [comment]
Couple of thoughts (non blocking / not urgent) …

> "Submit Evidence" button hidden
Steps to respond updated to remove reference to "Submit Evidence"
"Email the customer" mailto link updated to remove references to disputes in email body.

Since the UI is changing quite a bit, I think it's worth sharing this with design/product to get feedback – @rogermattic  @souravdebnath1986 . Hiding buttons can be considered a bad pattern, because it combines inconsistent UI with lack of info/explanation – TLDR the merchant might not know why the button has disappeared. Or indeed a future developer/tester might think this is a bug! [This smashing article is a good overview](https://www.smashingmagazine.com/2024/05/hidden-vs-disabled-ux/) (it is complex, of course!)

> Submitting evidence is not blocked, the merchant can still manually navigate to /wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fdisputes%2Fchallenge&id=<dispute_id> to challenge the inquiry. While it would be possible to prevent this I opted for the simple approach. If we decided to prevent access to this page, API calls should also be blocked by the same logic.

Sounds reasonable (adjust the UI but don't block the capability). 

For the server API, I think we should consider returning an error, to clearly indicate "this ain't gonna work".

**Comment by haszari** [comment]
> The DisputeNotice component has not been updated. There is a bit of a contradiction between the notice and the docs

Indeed! @brucealdridge - can you log a new issue to fix the notice wording? We can also use that issue to work through any other ux changes (see above comment) to make this clear and straightforward for merchants.

**Comment by rogermattic** [comment]
Thanks @haszari for pinging me here!
> Since the UI is changing quite a bit, I think it's worth sharing this with design/product to get feedback – @rogermattic @souravdebnath1986 . Hiding buttons can be considered a bad pattern, because it combines inconsistent UI with lack of info/explanation – TLDR the merchant might not know why the button has disappeared. Or indeed a future developer/tester might think this is a bug!

100% I think we can be more transparent about this. I'll explore what info we can provide to the user. 
 
> Indeed! @brucealdridge - can you log a new issue to fix the notice wording? We can also use that issue to work through any other ux changes (see above comment) to make this clear and straightforward for merchants.

+1 on this! Once we have a new issue, feel free to ping me so I can add my comments there. I won’t be able to explore potential solutions before the end of this year, but hopefully early 2025! :) )

**Comment by brucealdridge** [comment]
I've created an issue to tidy up the copy.

https://github.com/Automattic/woocommerce-payments/issues/9918

**Comment by haszari** [comment]
Thanks @brucealdridge ! We can use that issue to work through the user experience concerns mentioned above – the notice wording is part of it. @rogermattic can you add your feedback there too?

- https://github.com/Automattic/woocommerce-payments/issues/9918
 
@brucealdridge if you have a moment, would be good to broaden the issue a little, add some of the insights / feedback from the discussion here. That way whoever works on this can fix it holistically (prevent accidental tunnel vision).

**Comment by rogermattic** [comment]
Hey! I added my comment in the #9918 thanks for the ping @haszari !

With the full context now (I hope 😅) I wonder if this part of the UI is not too confusing:

Screenshot 2025-01-09 at 12 09 21

Considering this is not a dispute initially, I wonder if we should change the headings too. 

`Dispute amount`, `Disputed on` seem to suggest it's a dispute. Maybe we could consider changing the headings to:

	1.	Dispute Amount → Inquiry Amount
	2.	Disputed On → Inquiry Opened
	3.	Respond By → Action Needed By

I also wonder what is displayed there under the `Reason`?
