### PR TITLE
Payment Request: Fix shipping calculation for UK and CA postal codes with Apple Pay

### LINKED ISSUE #1525: Payment Request: Fix UK and CA shipping zones + redacted postal codes from Apple Pay
Apparently, Apple Pay has changed its rules for UK and CA postal codes and is now returning the first 4 characters instead of only the first 3. I'm in contact with their support and I still need to get confirmation from them, but if that's the case, we can properly fix the long lived issue in 1198-gh-woocommerce/woocommerce-gateway-stripe, instead of just showing a warning that it may not work with 4+ characters postal codes, as proposed in #1430

There's also a problem when calculating shipping options while passing a redacted UK postal code specifically. The `woocommerce_validate_postcode` filter which is used to ignore the postal code validation for the UK and Canada doesn't seem to be working.

### PR DESCRIPTION
**Pull request by ricardo**
Fixes #1525

For privacy reasons, Apple Pay redacts the postal code when calculating shipping options and displays only the first 3 characters for Canada and the first 4 characters for UK postal codes. The full postal code is submitted once the order is placed.

There was a bug with UK postal codes specifically, due to the [way WC validates UK postal codes](https://github.com/woocommerce/woocommerce/blob/ec77c3bcc985f26c97b962e53d8f9fb9d355c3cf/includes/class-wc-validation.php#L132), that was preventing it to display wildcard shipping zones when the postal code was redacted from Apple Pay.

#### Changes proposed in this Pull Request

- Fix the UK issue by filling the redacted postal code with `*`, so WC can calculate the shipping options based on up to 4 characters shipping zones.
- Remove the `woocommerce_validate_postcode` filter, which was used when calculating shipping options.

#### Testing instructions

- Ensure you have `Payment Request Button` enabled in Payments > Settings, and your base country is `US`.
- Ensure your site is served over HTTPS and is publicly accessible.
- Ensure you have a real card added to your Apple Wallet.
- Add a wildcard shipping zone with the following postal code in the UK: `LN10*`. Add a flat rate of $1 to it.
- Go to a product page with shipping in Safari and click the "Buy with Apple Pay" button.
- Add a new shipping address in the United Kingdom with a random city, state and street number, add `LN10 6SH` as the postal code.
- Notice the flat rate of $1 gets added.
- If you try with a postal code of `LN11 6SH`, it should not work.
- For shipping zones in Canada, the same behavior should apply, but you can add only up to 3 characters shipping zones, e.g: `T5T*`. - This is due to the Apple Pay privacy limitation.

-------------------

- [ ] Added changelog entry - does not apply, the feature was not released in the UK and CA yet.
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 1]
```diff
@@ -294,37 +292,27 @@ public function filter_gateway_title( $title, $id ) {
...
-		$payment_request_type = isset( $_POST['payment_request_type'] ) ? wc_clean( wp_unslash( $_POST['payment_request_type'] ) ) : ''; // phpcs:ignore WordPress.Security.NonceVerification
-
-		if ( 'apple_pay' !== $payment_request_type ) {
-			return $valid;
-		}
-
+	public function get_normalized_postal_code( $postcode, $country ) {
 		/**
-		 * Currently Apple Pay truncates postal codes from UK and Canada to first 3 characters
+		 * Currently Apple Pay truncates postal codes from UK and Canada to first 3-4 characters
```
Comment (diegocurbelo) [inline includes/class-wc-payments-payment-request-button-handler.php:302]: It's not clear from the comment how many characters for each country, it's actually 4 for the UK and 3 for Canada

```suggestion
		 * Currently, Apple Pay truncates the UK and Canadian postal codes to the first 4 and 3 characters respectively
```

**Review by diegocurbelo — APPROVED** [review]
LGTM 🚢 

@ricardo Feel free to ignore the comment change I suggested, maybe just swapping UK and Canada is clear enough.

**Comment by christopherdarling** [comment]
The above fix doesn't seem to work with zone postcode filters in the below format. The data received back from Apple is `AB1` as part of this change, Woocommerce changes this to `AB1****`

**Zone A:**
`AB1 *`
`AB2 *`

**Zone B:**
No postcode filters - whole of UK

Although the postcode AB1 should match Zone A, the shipping methods for Zone B are displayed


Preempting that a suggestion would be to move to `AB1*` format, the issue is that we don't want to ship to `AB10 1AB` which is why the space is there.

**Comment by majikandy** [comment]
I am experiencing the exact same issue as @christopherdarling but a further point to note is that it also applies to single first letter postcodes like

N1 *
E1 *

The space being essential to block  postcodes like 

N19 1BB
E17 1BB

But to allow

N1 1BB
E1 1BB

N1 and E1 postcodes are getting changed into N1**** and E1**** as they come through which don't match any of the wildcard strings 

As mentioned by @christopherdarling you can't just use N1* or E1* in the shipping zone because N19*** and E17**** coming from Apple Pay would get matched and the customer would be able to chose an option that is only valid for N1 and E1.

The scenario is a "free local hand delivery" by an artisan supplier who will deliver locally, but isn't going to go all the way out to an N19 or E17 postcode but doesn't mind N1 and E1.

Is the injection of stars accidentally trimming off the space from Apple Pay on the assumption that the space isn't important?
