### PR TITLE
Prevent potential fatal in multi-currency widget markup getter

### LINKED ISSUE #10220: Multi-currency fatals are ranked high on Atomic sites
When reviewing [this dashboard on Grafana](https://mc.a8c.com/grafana/d/o7i4CqH4z/wc-pay-additional?orgId=1&from=now-7d&to=now&timezone=utc&var-hvm_blogID=$__all&var-tag_value=&var-log_level=critical-error&var-log_level=error&var-atomic_logs_severity=$__all&var-Filters=), I saw multi-currency errors are very prominent:

Image

It looks like this is the relevant error:
```
PHP Fatal error: Uncaught TypeError: spl_object_hash(): Argument #1 ($object) must be of type object, null given in /wordpress/plugins/woocommerce-payments/8.8.0/includes/multi-currency/MultiCurrency.php:526 Stack trace: #0 /wordpress/plugins/woocommerce-payments/8.8.0/includes/multi-currency/MultiCurrency.php(526): spl_object_hash(NULL) #1 /wordpress/plugins/woocommerce-payments/8.8.0/includes/multi-currency/StorefrontIntegration.php(77): WCPay\MultiCurrency\MultiCurrency->get_switcher_widget_markup(Array, Array) #2 /wordpress/core/6.7.1/wp-includes/class-wp-hook.php(324): WCPay\MultiCurrency\StorefrontIntegration->modify_breadcrumb_defaults(Array) #3 /wordpress/core/6.7.1/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array) #4 /wordpress/plugins/woocommerce/9.6.0/includes/wc-template-functions.php(2500): apply_filters('woocommerce_bre...', Array) #5 /wordpress/core/6.7.1/wp-includes/class-wp-hook.php(324): woocommerce_breadcrumb('') #6 /wordpress/core/6.7.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #7 /wordpress/core/6.7.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #8 /wordpress/themes/storefront/4.6.1/header.php(60): do_action('storefront_befo...') #9 /wordpress/core/6.7.1/wp-includes/template.php(810): require_once('/wordpress/them...') #10 /wordpress/core/6.7.1/wp-includes/template.php(745): load_template('/wordpress/them...', true, Array) #11 /wordpress/core/6.7.1/wp-includes/general-template.php(48): locate_template(Array, true, true, Array) #12 /wordpress/themes/storefront/4.6.1/404.php(8): get_header() #13 /wordpress/core/6.7.1/wp-includes/template-loader.php(106): include('/wordpress/them...') #14 /wordpress/core/6.7.1/wp-blog-header.php(19): require_once('/wordpress/core...') #15 /wordpress/core/6.7.1/index.php(17): require('/wordpress/core...') #16 {main} thrown in /wordpress/plugins/woocommerce-payments/8.8.0/includes/multi-currency/MultiCurrency.php on line 526

```

(Related issue also opened for WooPay)

### PR DESCRIPTION
**Pull request by cesarcosta99**
Fixes #10220.

#### Changes proposed in this Pull Request

This addresses a potential fatal that might happen in the multi-currency widget markup getter when the widget instance is `null`. This fatal is impacting Atomic sites only and based on the logs and this thread p1738351484913529-slack-C01BZUL57SQ, our theory is that this is happening in automated requests only. I haven't been able to reproduce the issue myself.

#### Testing instructions

**Setup**

1. As a merchant, ensure your site theme is Storefront.
2. Navigate to **WooCommerce > Settings > Multi-currency** and ensure **Add a currency switcher to the Storefront theme on breadcrumb section** is enabled.

**Reproduce the issue**

1. Checkout to `develop`.
2. Add `return null;` early in [get_currency_switcher_widget()](https://github.com/Automattic/woocommerce-payments/blob/30e1c14084bcad388b9306a13db0cbbe178d453a/includes/multi-currency/MultiCurrency.php).
3. Visit the store and see the fatal error indicated in the issue:
`Fatal error: Uncaught TypeError: spl_object_hash(): Argument #1 ($object) must be of type object, null given`

**Test: Ensure no fatal error is triggered**

1. Checkout to this branch.
2. Keep the early return you added in step 2 above.
3. Refresh the page.
4. You should not see any errors and page should load successfully. Note, however, that the currency switcher widget is no longer displayed in the breadcrumb.

**Regression test: Ensure currency switcher widget is displayed as expected**

1. Remove the early return you added in step 2 above.
2. Refresh the page.
3. You should not see any errors and page should load successfully. The currency switcher widget should be rendered in the breadcrumb and should be working as expected.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10291` or branch name `fix/10220-multi-currency-widget-markup-getter` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/10220-multi-currency-widget-markup-getter) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 49aa9ef90ca6fe524bfdb8058c4800d933ad7671
- Build time: 2025-02-05 22:35:13 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/multi-currency/MultiCurrency.php [hunk 1]
```diff
@@ -522,8 +522,15 @@ public function get_switcher_widget_markup( array $instance = [], array $args =
 		 * call the_widget, you need to have the name of the widget, so we get the instance and hash to use.
 		 */
 		ob_start();
+
+		$currency_switcher_widget = $this->get_currency_switcher_widget();
+
+		if ( ! is_object( $currency_switcher_widget ) ) {
+			return ob_get_clean();
```
Comment (asumaran) [inline includes/multi-currency/MultiCurrency.php:536]: Since this shouldn’t happen, maybe it’s good to add a log here so we can trace it, possibly figure out how it’s being reproduced, and fix it later?

**Review by asumaran — APPROVED** [review]
Tests as expected and code looks good. I only left a non-blocking comment for you @cesarcosta99.

File: includes/multi-currency/MultiCurrency.php (hunk 1 above)
Comment (cesarcosta99) [reply includes/multi-currency/MultiCurrency.php:536]: Good idea, added in 75783ab.

You can test it by running **Test: Ensure no fatal error is triggered** again and the log will be included in the `woopayments-multi-currency-{date}` file in **WooCommerce > Status > Logs**.

**Review by asumaran — APPROVED** [review]
