### PR TITLE
Validate required billing fields using data from objects instead of checking the labels

### LINKED ISSUE #9447: Classic checkout js broken with custom templates
### Describe the bug

#8502 introduced a change in the handling of the classic checkout that might break the form for custom templates.

In Newspack, we have a 2-step modal checkout experience that doesn't render the billing fields in the standard way when in the payment section. Instead, it renders them in hidden inputs because they have been previously edited.

Because the inputs are not inside a `.form-row`, the `$formRow.classList.contains()` call will cause a js crash and break the form submission. We're tweaking our strategy in https://github.com/Automattic/newspack-blocks/pull/1883, but it would probably be a good idea to check if that node exists before the validation.

### PR DESCRIPTION
**Pull request by danielmx-dev**
Fixes #9447

#### Changes proposed in this Pull Request

* Changes the structure of `enabledBillingFields` from `string[]` to a map of `{ <fieldName: string>: {required: boolean} }`
* Uses the same approach as WooCommerce core to determine the address requirements based on the selected billing country.
* Use data objects instead of checking the DOM elements to determine if a field is required. This approach was previously implemented by https://github.com/Automattic/woocommerce-payments/pull/8502

#### Testing instructions

**Postal code required**
* Add a product to your cart.
* Proceed to the shortcode checkout.
* Ship to any address in US.
* Leave the postcode empty.
* Attempt to pay for the order with a new card.
* You shouldn't be allowed to submit the order since the Postal Code is **required**.
* Fill the postcode.
* You should be allowed to submit the order.

**Postal code optional**
* Add a product to your cart.
* Proceed to the shortcode checkout.
* Ship to any address in HK.
* Leave the postcode empty (as it is optional).
* Attempt to pay for the order with a new card.
* You shouldn be allowed to submit the order since the Postal Code is **optional**.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9707` or branch name `fix/9447-validate-required-fields-using-objects` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9447-validate-required-fields-using-objects) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: ebdad5c0b63927a0549d26a2708bfe7b792541fb
- Build time: 2024-11-14 16:09:41 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by danielmx-dev** [comment]
Currently there are no tests for this feature, I'll see if it's possible to add them, but the approach should be ready for review.

File: client/checkout/classic/event-handlers.js [hunk 1]
```diff
@@ -267,16 +277,35 @@ jQuery( function ( $ ) {
...
+					const fieldSettings = jQuery.extend(
+						true,
+						{},
+						locale.default[ key ],
+						locale[ country ][ key ]
+					);
+					isRequired = fieldSettings.required;
+				} else {
+					isRequired = enabledBillingFields[ fieldName ]?.required;
+				}
```
Comment (frosso) [inline client/checkout/classic/event-handlers.js]: The initialization of `isRequired` could be simplified like this, since it'll always be overwritten by the `else` statement:
```suggestion
				let isRequired = enabledBillingFields[ fieldName ]?.required;

				if ( country && locale && fieldName !== 'billing_email' ) {
					const key = fieldName.replace( 'billing_', '' );
					const fieldSettings = jQuery.extend(
						true,
						{},
						locale.default[ key ],
						locale[ country ][ key ]
					);
					isRequired = fieldSettings.required;
				}
```

File: client/checkout/classic/event-handlers.js [hunk 2]
```diff
@@ -267,16 +277,35 @@ jQuery( function ( $ ) {
...
+
+				if ( country && locale && fieldName !== 'billing_email' ) {
+					const key = fieldName.replace( 'billing_', '' );
+					const fieldSettings = jQuery.extend(
+						true,
+						{},
+						locale.default[ key ],
+						locale[ country ][ key ]
+					);
+					isRequired = fieldSettings.required;
```
Comment (frosso) [inline client/checkout/classic/event-handlers.js]: I'm wondering about the use of `jQuery.extend`, in this scenario.
More specifically, I am wondering why deep cloning into an object, and then grabbing only the `required` attribute from it.

Could the same be achieved by this, without the overhead of cloning the objects?
```suggestion
					isRequired = locale[country][key]?.required ?? locale.default[key]?.required;
```

**Review by frosso — COMMENTED** [review]
The approach looks good, I tested it on My account/Pay-for-order/shortcode checkout.
I have some questions/suggestions about possibly refactoring the checks in `billingFieldsToValidate.find(...)`.

File: client/checkout/classic/event-handlers.js (hunk 2 above)
Comment (danielmx-dev) [reply client/checkout/classic/event-handlers.js]: Thanks for the suggestions, I applied both.

**Review by frosso — APPROVED** [review]
Thank you for the changes! :shipit: feel free to add any tests, if you are able to (in reference to https://github.com/Automattic/woocommerce-payments/pull/9707#issuecomment-2471386844 )
