### PR TITLE
fixed bug that would not allow customers using firefox to be redirect to WooPay

### LINKED ISSUE #5110: Customer does not get redirected to WooPay on firefox sometimes
Sometimes firefox triggers the pageshow event before we add a listener to it. When that happens the [checks to automatically](https://github.com/Automattic/woocommerce-payments/blob/4ddc395b079548dba886cb1946ca69f1d2cb0df8/client/checkout/platform-checkout/email-input-iframe.js#L454-L486) redirect the customer do not run.

If the customer changes the email address it does not show the OTP modal because the flag hasCheckedLoginSession is set to false.

### PR DESCRIPTION
**Pull request by leonardola**
Fixes #5110

#### Changes proposed in this Pull Request
This PR fixes an error that would not allow customer to be auto redirected to WooPay on firefox. 
It also allow the customer to be redirected/log in to WooPay again by changing the email after clicking the back button.

While working on this one I found this bug #5113 

#### Testing instructions
- Test on Firefox and Chrome 
- Add a product to your cart and checkout using WooPay
- When you get to the WooPay checkout click the WooPay back button
- Make sure you do **not** get redirected back to WooPay
- Reload the page make sure you do get redirecte
- Click the browser back button
- Make sure you do **not** get redirected back to WooPay
- Remove and type again the last character of your email
- Make sure you do get redirected to WooPay
- Go back again and this time type another WooPay account email
- Make sure the OTP modal shows up

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: client/checkout/platform-checkout/email-input-iframe.js [hunk 1]
```diff
@@ -631,4 +603,28 @@ export const handlePlatformCheckoutEmailInput = async (
...
+		let { pathname } = window.location;
+
+		if ( '' !== searchParams.toString() ) {
+			pathname += '?' + searchParams.toString();
+		}
+
+		history.replaceState( null, null, pathname );
+
+		// Safari needs to close iframe with this.
+		closeIframe( false );
```
Comment (alefesouza) [inline client/checkout/platform-checkout/email-input-iframe.js:628]: The `closeIframe` function here prevents the SMS OTP to be shown after going back from Safari as you mentioned on #5113, adding `closeLoginSessionIframe();` at the end of this code should resolve this problem.

**Review by alefesouza — APPROVED** [review]
Great work! Just added a comment about the Safari issue you found.

File: client/checkout/platform-checkout/email-input-iframe.js (hunk 1 above)
Comment (leonardola) [reply client/checkout/platform-checkout/email-input-iframe.js:628]: That does not seem to fix it. I tried to add a listener to popstate and beforeunload but they are not triggered
