### PR TITLE
Retrieve error message for the Stripe Billing subscription renewal failure

### LINKED ISSUE #10001: [Stipe Billing] When a renewal invoice fails, fetch the reason for failure from the charge object and attach it as a note on the renewal order.
### Description

Slack thread: p1732528751864649-slack-C7U3Y3VMY

For standard subscription renewals, when the payment fails, an order note is added to the renewal order to explain why the payment failed. For Stripe Billing subscriptions, we currently don't add any reason for failure to the renewal order - this can result in confusion to the merchant.

Failed renewal order with Stripe Billing:
Image

Failed renewal with WooPayments:
Image

Stripe Billing failed renewals are handled by our [`handle_invoice_payment_failed()`](https://github.com/Automattic/woocommerce-payments/blob/1f857c7e2212110f317502e48c91af8d0c730352/includes/subscriptions/class-wc-payments-subscriptions-event-handler.php#L209) function which is attached to the `invoice.payment_failed` webhook event.

This function doesn't add any order notes to explain why the invoice failed failed. We just create a pending renewal order and then call `$subscription->payment_failed()` which marks this latest renewal as failed.

Looking at the [`invoice.payment_failed` event payload](https://docs.stripe.com/api/invoices/object), it doesn't seem to come with any reason for the failure.

In order to attach the reason, we will need to update our `handle_invoice_payment_failed()` function to first fetch the charge object from Stripe using the charge ID found on invoice object and then attach the reason to the new renewal order.

### Testing instructions

1. Install and activate the latest WooCommerce Subscriptions extension.
2. Enable Stripe Billing subscriptions in **Payments > Settings**Image and be sure to have Webhooks setup.
3. Create a simple subscription product if you do not have one already.
4. Purchase the subscription product and confirm it's a Stripe Billing subscription by going to the Edit Subscription page and looking for the `sub_XXX` ID: Image
5. Update this subscriptions payment method to a failing card: `4000000000000341`
6. Visit this subscription from the Stripe Dashboard and use the Simulation tool to advance the time to be after the first expected renewal date: Image
7. View the new renewal order in Woo and confirm the order is failed and related subscription is on-hold.
8. Notice the renewal order has a note for the status transition to failed, but no reason for why.

### PR DESCRIPTION
**Pull request by dmvrtx**
Fixes #10001 
Fixes WOOPMNT-4601

#### Changes proposed in this Pull Request

During processing of the `invoice.payment_failed` event, which indicates a failure to collect payment for a Stripe Billing subscription, try to retrieve a related `Charge` object and get details about the failure to inform the merchant.

#### Testing instructions

 * Set up a test store in the US with the WooCommerce Subscriptions. Create a subscription product.
 * Activate `Enable Stripe Billing for future subscriptions` in the Advanced section of the WooPayments Settings.
 * Purchase a subscription product. Check in the WooCommerce > Subscriptions that it is a Stripe Billing subscription:

image

 * Open the Stripe dashboard and find the subscription.
 * On the Stripe dashboard, click on a subscription customer and update payment methods to contain only card `4000000000000341`, which fails a renewal. Mark it as default payment method.

image
 
>[!NOTE]
>Update payment method on the Stripe dashboard and not in the store. There is an error that will convert subscription into the WooCommerce subscription if payment method is updated to card from the "Change subscription" page in the store.

 * Go back to the subscription page on the Stripe dashboard and use the time simulation tool to advance time beyond the next renewal date.

image

 * Open the subscription page as a merchant. There should be an order note with a failure message:

image

 * Open the renewal order. It should contain failure details and a status change:

image

>[!TIP]
>Once testing is done, open the Stripe Dashboard under a merchant's account, head to "Subscriptions" and open "Test times". Use the "..." menu to finish the simulation.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10679` or branch name `woopmnt-4601-stipe-billing-when-a-renewal-invoice-fails-fetch-the-reason` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=woopmnt-4601-stipe-billing-when-a-renewal-invoice-fails-fetch-the-reason) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 052964781da635c07b6625fb9a61d0a4a0c31be7
- Build time: 2025-04-04 17:55:02 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/subscriptions/class-wc-payments-subscriptions-event-handler.php [hunk 1]
```diff
@@ -244,8 +264,36 @@ public function handle_invoice_payment_failed( array $body ) {
...
+						'Payment for the order failed with the following message: "%1$s" and failure code <code>%2$s</code>',
+						'woocommerce-payments'
+					),
+					$error_details,
+					$error_code
+				)
+			);
+		} else {
+			// Translators: %d Number of failed renewal attempts.
+			$subscription->add_order_note( sprintf( _n( 'WCPay subscription renewal attempt %d failed.', 'WCPay subscription renewal attempt %d failed.', $attempts, 'woocommerce-payments' ), $attempts ) );
```
Comment (frosso) [inline includes/subscriptions/class-wc-payments-subscriptions-event-handler.php:295]: Would it make sense to refer to the plugin's name, here? Or are there other instances where we refer to `WCPay` in the notes?
```suggestion
						'WooPayments subscription renewal attempt %1$d failed with the following message "%2$s" and failure code <code>%3$s</code>',
						'WooPayments subscription renewal attempt %1$d failed with the following message "%2$s" and failure code <code>%3$s</code>',
						$attempts,
						'woocommerce-payments'
					),
					$attempts,
					$error_details,
					$error_code
				)
			);
			$order->add_order_note(
				sprintf(
					// Translators: %1$s contains failure message. %2$s contains error code.
					__(
						'Payment for the order failed with the following message: "%1$s" and failure code <code>%2$s</code>',
						'woocommerce-payments'
					),
					$error_details,
					$error_code
				)
			);
		} else {
			// Translators: %d Number of failed renewal attempts.
			$subscription->add_order_note( sprintf( _n( 'WooPayments subscription renewal attempt %d failed.', 'WooPayments subscription renewal attempt %d failed.', $attempts, 'woocommerce-payments' ), $attempts ) );
```

**Comment by frosso** [comment]
Taking a look

**Review by frosso — APPROVED** [review]
Sorry for the delay here, it took me multiple tries to finally get the expected result, since I wasn't familiar with the feature :D 

Screenshot 2025-04-07 at 1 11 54 PM

The only note I have is that I edited the subscription's details, instead of editing the payment methods associated to the customer.

I just added a very minor optional suggestion about the order note - looking good otherwise!

File: includes/subscriptions/class-wc-payments-subscriptions-event-handler.php (hunk 1 above)
Comment (dmvrtx) [reply includes/subscriptions/class-wc-payments-subscriptions-event-handler.php:295]: I wanted to change the name, but `grep` found a few other usages across the plugin codebase, so I opted to make it a separate change, instead of extending scope of this pull request.

Comment (frosso) [reply includes/subscriptions/class-wc-payments-subscriptions-event-handler.php:295]: Ah, I see - there's also occurrences like:
```php
$subscription->add_order_note( __( 'Suspended WCPay Subscription because subscription status changed to on-hold.', 'woocommerce-payments' ) );
$subscription->add_order_note( __( 'The subscription\'s next payment date has been updated to match WCPay server.', 'woocommerce-payments' ) );
$subscription->add_order_note( __( 'Suspended WCPay Subscription in invoice.upcoming webhook handler because subscription next_payment date is 0.', 'woocommerce-payments' ) );
```

All good 👍
