### PR TITLE
Fix incorrect payment method title

### LINKED ISSUE #7272: WooPayments conflicting with cash on delivery at order confirmation page
### Describe the bug

WooPayments conflicting with cash on delivery at order confirmation page, showing that you paid with Credit/Debit card instead of Cash On Delivery

### To Reproduce

1.  Enable Cash On Delivery and WooPayments
2. Checkout with any product at your store, make sure to select Cash On Delivery as payment method
3. Check the Order Confirmation page, which payment method is listed there

### Actual behavior

Take a look at the screenshot below. You'll notice that if you choose Cash On Delivery as your payment method during checkout with WooPayments active, the order confirmation will show Credit/Debit card as the payment method. We understand how this can be confusing. Even though the customer didn't use a credit card, it might make some customers think they did instead of paying with cash on delivery.

### Screenshots
https://d.pr/i/KAuQLj

### Expected behavior

Order confirmation display cash on delivery as the payment method in case you paid with cash on delivery.

### Desktop (please complete the following information):

* OS: MacOS Ventura 13.5.2
* Browser: Chrome 
* Version: 116.0.5845.187

### Additional context

[Ticket](https://a8c.zendesk.com/agent/tickets/7075204)

### LINKED ISSUE #7273: 6.5.0 broke payment_method_title in API, value always ignored
### Describe the bug

When creating an order using the WooCommerce API, if either `status=processing` or `set_paid=true` is included in the request, any value of `payment_method_title` is ignored and will default to "Credit card / debit card".

This seem to be a regression in a recent update because I have some automation that relies on this and it recently broke.

**Request**
```
curl --location --request POST '<site-root>/wp-json/wc/v3/orders?payment_method=bacs&payment_method_title=Direct%20bank%20transfer&status=processing' \
```

**Result**
```
...
    "payment_method": "bacs",
    "payment_method_title": "Credit card / debit card",
...
```

### Expected behavior

The value of `payment_method_title` should always be respected and persisted.

### Actual behavior

The value of `payment_method_title` is lost.

### Steps to reproduce

1. Run the cURL command below

```
curl --location --request POST '<site-root>/wp-json/wc/v3/orders?payment_method=bacs&payment_method_title=Direct%20bank%20transfer&status=processing' \
```

Worked on 6.4.2, broken on 6.5.0

### PR DESCRIPTION
**Pull request by mdmoore**
Fixes #7272
Fixes #7273 

#### Changes proposed in this Pull Request

This prevents the payment method title from being updated for non-WooPayments gateways and limits those updates to the Legacy UPE gateway.

#### Testing instructions

- Enable Cash On Delivery and WooPayments
- As a customer, add any product to the cart
- Select Cash On Delivery as payment method
- Checkout
- On the Order Confirmation page, ensure the correct payment method title is set

Before:

After:

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7285` or branch name `fix/7272-incorrect-payment-method-title` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7272-incorrect-payment-method-title) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 10a8fc44d6a09a14ab21ae74a2c259ac20f375c8
- Build time: 2023-09-26 14:00:23 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/payment-methods/class-upe-payment-gateway.php [hunk 1]
```diff
@@ -1171,13 +1171,21 @@ public function maybe_filter_gateway_title( $title, $id ) {
 	 * @return void
 	 */
 	public function set_payment_method_title_for_email( $order ) {
+		$payment_gateway = wc_get_payment_gateway_by_order( $order );
+
+		if ( self::GATEWAY_ID !== $payment_gateway->id || ! WC_Payments_Features::is_upe_legacy_enabled() ) {
```
Comment (frosso) [inline includes/payment-methods/class-upe-payment-gateway.php]: It looks like [`wc_get_payment_gateway_by_order` could return `false`](https://github.com/woocommerce/woocommerce/blob/bf80b7a5341be3adcfeae6322408789b37995f71/plugins/woocommerce/includes/wc-order-functions.php#L819), making `$payment_gateway->id` throw an error.

Before checking for the gateway's attribute, could we ensure that `$payment_gateway` is not `empty`?

**Review by frosso — CHANGES_REQUESTED** [review]

**Review by frosso — APPROVED** [review]
I think this will help us fix the issue, thank you! What testing opportunities do you think could be implemented?

File: includes/payment-methods/class-upe-payment-gateway.php [hunk 2]
```diff
@@ -1171,13 +1171,21 @@ public function maybe_filter_gateway_title( $title, $id ) {
 	 * @return void
 	 */
 	public function set_payment_method_title_for_email( $order ) {
+		$payment_gateway = wc_get_payment_gateway_by_order( $order );
+
+		if ( ! empty( $payment_gateway ) && self::GATEWAY_ID !== $payment_gateway->id || ! WC_Payments_Features::is_upe_legacy_enabled() ) {
```
Comment (timur27) [inline includes/payment-methods/class-upe-payment-gateway.php:1176]: @mdmoore I was passing by as I'm currently reviewing [tests for this enhancement](https://github.com/Automattic/woocommerce-payments/pull/7331). With filtering out any UPE type other than legacy UPE, we only allow legacy UPE gateways to update the email's payment method title. Effectively, deferred intent creation UPE now inserts "Credit card / debit card" in the email, vs "Visa debit card" in legacy UPE. Not sure what the requirements are and overall this change might be considered ok, but I wanted to flag this because previously (for `6.1.0 - 6.5.0`), both UPEs were showing _Visa debit card_. 

Thus, for deferred UPE users starting `6.5.1`, the email title differs from what they saw previously, and this group will be increased starting `6.6.0`, when all the legacy UPE stores will be switched to the deferred UPE.

Comment (mdmoore) [reply includes/payment-methods/class-upe-payment-gateway.php:1176]: Thanks for bringing this up. [This function was introduced](https://github.com/Automattic/woocommerce-payments/pull/6351) to ensure that `Popular Payment Methods` did not appear in emails as the payment method. My understanding was that the `Popular Payment Methods` payment method title is only set for Legacy UPE. This was my reason for limiting this change to Legacy UPE with hopes that we could likely remove this function down the line. Are you aware of other UPEs that will set the gateway title to `Popular Payment Methods`?

 >deferred intent creation UPE now inserts "Credit card / debit card" in the email, vs "Visa debit card" in legacy UPE.

I think prior to the above mentioned PR(#6351), `Credit card / debit card` always appeared. As a side effect of that PR, the card network and card type were used instead. This explains why now only Legacy UPE is displaying the network and card type as other UPE types are now back to the previous behavior. I'm also not sure of the desired behavior. Once we find out we can ensure consistency.

Comment (timur27) [reply includes/payment-methods/class-upe-payment-gateway.php:1176]: Your argumentation makes total sense and I totally understand your approach, @mdmoore! The current difference between UPEs is fine for me and I'll proceed to review tests with the assumption that we keep everything as is and, as it turns out, remove this logic once we migrate everyone to deferred intent UPE, but in case we feel it needs further alignment - feel free to follow this up and I'm always there for you to review if any further changes will be needed in the future. 👍
