### PR TITLE
Ensure shortcode renders for Privacy Policy & Terms of Service

### LINKED ISSUE #7600: Shortcode does not render in the WooPay Checkout preview
### Describe the bug

When the shortcodes `[privacy_policy_link]` and `[terms_of_service_link]` are added to the **Policies and custom text** input box, they do not get rendered into links. Instead, the shortcode itself appears.

### To Reproduce

* As a merchant, ensure a Privacy Policy and Terms of Service page are linked.
* Navigate to **WooCommerce > Settings > Payments > WooPayments > WooPay > Checkout appearance**.
* Update the **Policies and custom text** so that it includes the following shortcodes: `[privacy_policy_link]` and `[terms_of_service_link]`.
* Observe that the WooPay checkout preview displays the literal shortcodes, as opposed to displaying the respective link.

### Actual behavior

The literal shortcode renders in the WooPay checkout preview when shortcodes are added to the **Policies and custom text**.

### Screenshots

image

### Expected behavior

A link should render in the WooPay checkout preview when shortcodes are added to the **Policies and custom text**.

### PR DESCRIPTION
**Pull request by lovo-h**
Fixes #7600

#### Changes proposed in this Pull Request

This PR allows the following shortcodes to be rendered in the WooPay Checkout preview: `[privacy_policy]` and `[terms]`. 

It should also be noted that the shortcodes have been renamed from `[privacy_policy_link]` to `[privacy_policy]` and `[terms_of_service_link]` to `[terms]`. These changes were made in order to have a consistent naming across WooPayments and WooCommerce.

https://github.com/Automattic/woocommerce-payments/assets/6844516/454f8673-557d-42f7-9bcf-37bc5b22533c

#### Testing instructions

**Test: Ensure the Privacy Policy and Terms of Service links appear in WooPay checkout**
* As a customer, navigate to the merchant shop, add an item to the cart, and proceed to WooPay checkout.
* Ensure that the **Policies and custom test** appear in the WooPay checkout page. 
* Ensure the Privacy Policy and Terms of Service links work as intended.

**Test: Ensure shortcode is rendered to look like a link, in the preview**
* As a merchant, ensure a Privacy Policy and Terms of Service page are linked.
* Navigate to **WooCommerce > Settings > Payments > WooPayments > WooPay > Checkout appearance**.
* Update the **Policies and custom text** so that it includes the following shortcodes: `[privacy_policy]` and `[terms]`.
* Ensure the shortcodes are rendered and appear as links. Also, ensure that they are not interactive/clickable.

**Regression test: Ensure other elements are not rendered in the preview**
* Update the **Policies and custom text** so that it includes other shortcodes, HTML elements, JS script, etc. 
* Ensure these other elements are not rendered.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by lovo-h** [comment]
@nikkivias, given that this is a preview, should merchants be able to click on the Privacy Policy and Terms of Service links and be navigated to the respective link? Or should it just appear like they are links but not be interactive?

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7601` or branch name `fix/7600-woopay-checkout-shortcode-rendering` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7600-woopay-checkout-shortcode-rendering) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9000f57eaacce0c948c36c269693942d5da7e807
- Build time: 2023-11-06 19:19:03 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by nikivias** [comment]
Hey @lovo-h good question. Because this is serves as a preview, we should remove any and all kind of interactions

File: client/settings/express-checkout-settings/woopay-preview.js [hunk 1]
```diff
@@ -107,7 +108,36 @@ const CheckoutButton = ( { height } ) => {
 
 export default ( { storeName, storeLogo, customMessage, ...props } ) => {
 	const { style, ...restProps } = props;
-	const trimmedCustomMessage = ( customMessage || '' ).trim();
+
+	const preparedCustomMessage = useMemo( () => {
```
Comment (cesarcosta99) [inline client/settings/express-checkout-settings/woopay-preview.js:151]: We may want to tweak this function because HTML elements are not being escaped in the preview:

image

Though, they're being escaped at the WooPay checkout 👍 

image

**Review by cesarcosta99 — CHANGES_REQUESTED** [review]
Code changes look good, and most of my tests passed.

- Test: Ensure the Privacy Policy and Terms of Service links appear in WooPay checkout ✅ 
- Test: Ensure shortcode is rendered to look like a link, in the preview ✅ 
- Regression test: Ensure other elements are not rendered in the preview ❌

Another issue I bumped into, that is unrelated to this PR, is when the ToS or Privacy Policy page is a draft (unpublished). At the checkout preview it looks OK, the text is rendered but not like a link. However, at the WooPay checkout, the link is rendered and lead to the correct permalink, but we got a 404 error. We may want to create an issue for it to figure what's the expected behavior should be.

File: includes/woopay/class-woopay-session.php [hunk 2]
```diff
@@ -633,10 +633,10 @@ private static function get_formatted_custom_message() {
 		$custom_message = WC_Payments::get_gateway()->get_option( 'platform_checkout_custom_message' );
 
 		$replacement_map = [
-			'[terms_of_service_link]' => wc_terms_and_conditions_page_id() ?
+			'[terms]'          => wc_terms_and_conditions_page_id() ?
```
Comment (frosso) [inline includes/woopay/class-woopay-session.php]: How do these changes affect merchants that already saved their settings with the previous `[terms_of_service_link]` and `[privacy_policy_link]` values?

Comment (lovo-h) [reply includes/woopay/class-woopay-session.php]: Great observation. Added backwards compatibility in [58ba364](https://github.com/Automattic/woocommerce-payments/pull/7601/commits/58ba364cc8f263158ef55e7fc430b1a77f7d9459). 

I also added a mechanism to migrate these shortcodes, as they get updated.

File: client/settings/express-checkout-settings/woopay-preview.js (hunk 1 above)
Comment (lovo-h) [reply client/settings/express-checkout-settings/woopay-preview.js:151]: We discussed this over Slack and agreed that these elements are being escaped, but in order to match the actual implementation, they should not appear in the preview at all. I agree that the preview should look as similar to the implementation as possible. Fixed in [0194e9e](https://github.com/Automattic/woocommerce-payments/pull/7601/commits/0194e9ef2e2266e61310585b25b8d9a107d13fa4) and [7fce67e](https://github.com/Automattic/woocommerce-payments/pull/7601/commits/7fce67ef64e5979e14180de2ef86c5ea1387874b).

File: client/settings/express-checkout-settings/woopay-preview.js [hunk 3]
```diff
@@ -105,9 +109,62 @@ const CheckoutButton = ( { height } ) => {
...
+		let rawCustomMessage = ( customMessage || '' ).trim();
+
+		if ( rawCustomMessage ) {
+			rawCustomMessage = sanitizeHtmlForPreview( rawCustomMessage );
+			rawCustomMessage = rawCustomMessage.replace(
+				/\[(terms|terms_of_service_link)\]/g,
+				'<span class="preview-layout__shortcode-link">Terms of Service</span>'
+			);
+			rawCustomMessage = rawCustomMessage.replace(
+				/\[(privacy_policy|privacy_policy_link)\]/g,
```
Comment (cesarcosta99) [inline client/settings/express-checkout-settings/woopay-preview.js:161]: We can optimize the regular expressions like the following:

```suggestion
				/\[terms(_of_service_link)*\]/g,
				'<span class="preview-layout__shortcode-link">Terms of Service</span>'
			);
			rawCustomMessage = rawCustomMessage.replace(
				/\[privacy_policy(_link)*\]/g,
```

**Review by cesarcosta99 — APPROVED** [review]
Thanks for addressing the changes! LGTM 👍 

- Test: Ensure the Privacy Policy and Terms of Service links appear in WooPay checkout ✅ 
- Test: Ensure shortcode is rendered to look like a link, in the preview ✅ 
- Regression test: Ensure other elements are not rendered in the preview ✅ 

I left a tiny nitpick suggestion, but feel free to ignore it 😎

File: client/settings/express-checkout-settings/woopay-preview.js (hunk 3 above)
Comment (lovo-h) [reply client/settings/express-checkout-settings/woopay-preview.js:161]: Good call. I like that your version is less verbose. 

But in this case, having the entire term appear will make it easier to find when doing a global search, which I anticipate we will need to do in the future when we phase out the old shortcodes (e.g. `[terms_of_service_link]` and `[privacy_policy_link]`).
