### PR TITLE
Fix error sorting the Uncaptured table using Capture by column

### LINKED ISSUE #5184: Sort by Capture by column of Uncaptured transactions table causes an error
### Describe the bug

Sort by Capture by column of Uncaptured transactions table causes an error

### To Reproduce

1. As a merchant, Enable 'Issue an authorization on checkout...' option in `WP Admin > Payments > Settings`
2. As a shopper, purchase some orders using the normal card flow.

1. Go to `WP Admin > Payments > Transactions` and click on Uncaptured tab
3. Click on 'Capture by' column header to sort the table

### Actual behavior

A notification appears 'Error retrieving uncaptured transactions.' 
The content of the table is empty.
In the Network tab of Developer Tools there's a 500 error for the GET request to `wp-json/wc/v3/payments/authorizations?page=1&pagesize=25&sort=capture_by&direction=desc&_locale=user` with this response:
`{"code":"wcpay_bad_request","message":"Error: Unknown sort present in query: ","data":null}`

### Expected behavior

No errors thrown.

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #5184

#### Changes proposed in this Pull Request

This change fixes an error in the Uncaptured transactions table, when the table is sorted clicking on the Capture by column.
The error is caused by a 500 response from the endpoint, because 'capture_by' is not a valid sorting field in the API, since it is a value calculated in the front end, derived from the 'created' field.

To solve the issue, I am rewriting the orderby field in the resolver to 'created', in case the 'capture_by' field is specified. This has the same effect, and does not cause an error in the API endpoint.

#### Testing instructions

* As a merchant, enable 'Issue an authorization at checkout...' in `Payments > Settings`
* As a shopper, purchase at least 2 orders.
* As a merchant, to go Payments > Transactions and click on Uncaptured tab.
* Check that the table is sorted when clicking on Capture by column and no errors are thrown.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: client/transactions/uncaptured/index.tsx [hunk 1]
```diff
@@ -55,10 +55,8 @@ const getColumns = (): Column[] =>
 			screenReaderLabel: __( 'Capture by', 'woocommerce-payments' ),
 			required: true,
 			isLeftAligned: true,
-			defaultOrder: 'desc',
```
Comment (mgascam) [inline client/transactions/uncaptured/index.tsx:58]: According to [docs](https://github.com/woocommerce/woocommerce-admin/tree/main/packages/components/src/table#headers-structure), `defaultOrder` and `defaultSort` can only be assigned to one column.

**Review by kalessil — APPROVED** [review]
LGTM and tests well!
