### PR TITLE
Fix ECE exception when payment fails

### LINKED ISSUE #9990: ECE/GooglePay/ApplePay JS error when payment fails from backend
### Describe the bug

I observed this both in the non-tokenized and the tokenized ECE.

When the backend fails a payment, we call the `paymentFailed( { reason: 'fail' } )` method: 

https://github.com/Automattic/woocommerce-payments/blob/cf6d2c1f5de1df9d60c9f040757fd35a79525b35/client/express-checkout/blocks/hooks/use-express-checkout.js#L49

https://github.com/Automattic/woocommerce-payments/blob/cf6d2c1f5de1df9d60c9f040757fd35a79525b35/client/express-checkout/index.js#L109

When this is triggered, a JS error occurs in the console:
```
v3/?ver=3.0:1 Uncaught (in promise) IntegrationError: Unexpected call to paymentFailed(). Ensure you are either submitting a payment or calling paymentFailed() once per expressCheckout Element confirm event.
    at v3/?ver=3.0:1:355551
(anonymous) @ v3/?ver=3.0:1
Promise.then
paymentFailed @ v3/?ver=3.0:1
abortPayment @ index.js:109
onConfirmHandler @ event-handlers.js:106
await in onConfirmHandler
eval @ index.js:335
(anonymous) @ v3/?ver=3.0:1
s._emit @ v3/?ver=3.0:1
a._emitEvent @ v3/?ver=3.0:1
N @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
s._emit @ v3/?ver=3.0:1
_handleMessage @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
```

### To Reproduce

1. Modify the backend to fail the payment, or modify the JS to trigger this conditional: https://github.com/Automattic/woocommerce-payments/blob/cf6d2c1f5de1df9d60c9f040757fd35a79525b35/client/express-checkout/event-handlers.js#L86-L86
  - (or, alternatively, use a failed card if you can) 
2. Ensure you have GooglePay/ApplePay enabled
3. Navigate to a product page
4. Click on the GooglePay/ApplePay button
5. Attempt to pay
6. JS error appears in the console

### Screenshots

The screenshot shows the reCaptcha plugins failing, but I can reproduce it also without said plugin.
Image

### Expected behavior

No JS error should appear when a payment fails.
It seems that we're calling `paymentFailed()` incorrectly.

### PR DESCRIPTION
**Pull request by cesarcosta99**
Fixes #9990.

#### Changes proposed in this Pull Request

This PR removes the `payment.paymentFailed` call when aborting the ECE payment. I went with this approach because it looks like we're mistakenly calling that function.

The error message ("Ensure you are either submitting a payment or calling paymentFailed() once per confirm event") indicates an integration error. I confirmed we're calling that function just once, and I've simulated errors before and after confirming the intent, and in all cases the exception was generated.

According to the [documentation](https://docs.stripe.com/js/elements_object/express_checkout_element_confirm_event), we're only supposed to call this before calling `stripe.confirmPayment`, but we don't use that API, we process payments through intents in the backend. That makes me conclude we have an integration error because we're using different APIs, and the only solution is to remove that call, which has no effect.

#### Testing instructions

**Setup**

1. Checkout to this branch.
2. Run `npm run build:client`.

**Regression test: Ensure ECE still works as expected**

1. As a shopper, pay for any kind of product with ECE (Google Pay/Apple Pay).
4. Confirm payment is successful.

**Test: Ensure ECE fails gracefully**

1. Modify [the backend](https://github.com/Automattic/woocommerce-payments/blob/009bc4416b6a3d74efe68e79b7ae2c5195d43531/includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php#L70) to fail the payment, or modify [the JS](https://github.com/Automattic/woocommerce-payments/blob/cf6d2c1f5de1df9d60c9f040757fd35a79525b35/client/express-checkout/event-handlers.js#L87) to simulate an error.
2. Confirm all the following:
- Error message is correctly displayed in the frontend.
- No JS errors in the console.
- No Stripe intent is created and confirmed (if you modify the backend, make sure it's before the processing).

**Test: Ensure tokenized ECE works as expected**

1. As a merchant, go to the WCPay Dev Tools.
2. Enable the Cart-Token implementation for ECE feature flag and save.
5. Repeat both tests above, they must show the same results.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10048` or branch name `fix/9990-payment-failed-exception` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9990-payment-failed-exception) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 93ed0233e7d36551c8bd43d3f91908f4c40185fd
- Build time: 2025-01-03 14:54:37 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/express-checkout/index.js [hunk 1]
```diff
@@ -102,11 +102,9 @@ jQuery( ( $ ) => {
 		/**
 		 * Abort the payment and display error messages.
 		 *
-		 * @param {PaymentResponse} payment Payment response instance.
-		 * @param {string} message Error message to display.
+		 * @param {string}  message Error message to display.
 		 */
-		abortPayment: ( payment, message ) => {
-			payment.paymentFailed( { reason: 'fail' } );
+		abortPayment: async ( message ) => {
```
Comment (asumaran) [inline client/express-checkout/index.js]: Why was the `async` keyword added here? I don’t see any asynchronous operations being performed inside this method.

**Review by asumaran — CHANGES_REQUESTED** [review]
LGTM! Tests as expected. JS error is gone. Just left a minor comment for you @cesarcosta99

File: client/express-checkout/index.js (hunk 1 above)
Comment (cesarcosta99) [reply client/express-checkout/index.js]: Most likely it was a leftover, thanks for catching it. Fixed in 93ed023.

**Review by asumaran — APPROVED** [review]
