### PR TITLE
Provide correct WPCOM language code as locale when requesting CSV exports

### LINKED ISSUE #10149: CSV export email messages for `pt_BR`, `zh_CN`, `zh_TW` fall back to `en_US`, instead of using user language
Email notifications for CSV exports for the following supported languages pt_BR, zh_CN, zh_TW fall back to English.

### To Reproduce

1. Browse to `WP Admin -> Users -> Profile`
2. Change the profile language to any of the languages above.
3. Run a CSV export of transactions, payouts or disputes, making sure you have more than a single pagination to trigger a server export
4. Check the language of the email triggered, and the CSV contents. It should be in user language but is provided in US English.

Detailed observations here https://github.com/Automattic/woocommerce-payments/pull/10003#pullrequestreview-2548796735

### Additional context
* The server uses dash-separated locales e.g. pt-br, zh-cn, zh-TW
* WordPress core at the client side, uses locale in the format pt_BR, zh_CN etc.
* We have a [utility function `convert_to_server_locale()`](https://github.com/Automattic/woocommerce-payments/blob/147621d7d93b143b90908f66a6988da324f68946/includes/class-wc-payments-utils.php#L1287-L1322) that roughly converts the WordPress core locale type to the server supported dash-separated locales. 
* The CSV export POST request params incorrectly include the locale `en_US`. This is [likely](https://github.com/Automattic/woocommerce-payments/issues/10149#issuecomment-2591046482) a bug that occurs when the request query params are prepared in [convert_to_server_locale()](https://github.com/Automattic/woocommerce-payments/blob/147621d7d93b143b90908f66a6988da324f68946/includes/class-wc-payments-utils.php#L1287-L1322).
* The issue was found while creating the PR - #10003

### PR DESCRIPTION
**Pull request by Jinksi**
Resolves #10149
Fixes WOOPMNT-4685

### Changes proposed in this Pull Request

Transact-platform-server (WPCOM) uses different language codes for translations than WordPress. Rather than `language_country` (`en_US`), wpcom language codes are _mostly_ just `language` (`en`). Some wpcom language codes are represented as `language-region`, e.g. `pt-br` for Portugese (Brazil) (see [translate.wordpress.com](https://translate.wordpress.com/projects/wpcom/pt-br/default/?filters%5Bterm%5D=wcpay&filters%5Bterm_scope%5D=scope_references&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)).

When requesting CSV exports, region-specific language codes were not working correctly, as reported in #10149.

This PR fixes this by:
* Fixing `convert_to_server_locale`:
	* Correctly convert WP locales to wpcom-compatible language codes, in particular, region-specific languages.
	* Reducing the list of hard-coded language codes to only region-specific languages to reduce the maintenance burden when new languages are introduced.
	* More thoroughly documenting what is occurring in the function and where the wpcom language codes are sourced from.
	* Added a unit test for this function to validate the expected conversion for multiple strings
* Reducing redundant code related to passing the locate from PHP → JS → PHP.
	* Since the current user's WP locale is already available in `wcSettings`, I've relied on this to replace `wcpaySettings.userLocale`.
	* This reduces the maintenance burden of redundant, duplicate code.
* Map the WP locale → WPCOM language code within the REST API controller, rather than within JS.
	* This simplifies the client logic, allowing it to pass the available WordPress locale code without modification, relying on the API controller layer to transform the request into a transact-platform-server compatible locale code.

### Testing instructions

> [!IMPORTANT]
> You must use production or sandbox transact-platform-server for email/CSV translations to work correctly. E.g. with Jurassic Ninja. Build a release with `npm run build:release` and use the created .zip file for the testing.
> Alternatively, if you've figured out how to get these email/CSV translations working on your local transact-platform-server, please let me know how!

1. Browse to `WP Admin -> Users -> Profile`
2. Change the profile language to a wpcom-supported region-specific language:
	* `pt_BR` Portugese (Brazil)
	* `zh_CN` Chinese (Simplified)
	* `zh_TW` Chinese (Traditional)
4. Run a CSV export of transactions, payouts or disputes, making sure you have more than a single pagination to trigger a server export
5. Ensure the email and CSV are provided in the user language.
8. Repeat steps above with other wpcom-supported languages
	* E.g. for French, the following WP locales will all fall back to `fr` on wpcom.
		* Français `fr_FR` ([translate.wordpress.com link](https://translate.wordpress.com/projects/wpcom/fr/default/?filters%5Bterm%5D=wcpay&filters%5Bterm_scope%5D=scope_references&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc))
		* Français du Canada `fr_CA` ([translate.wordpress.com link](https://translate.wordpress.com/projects/wpcom/fr-ca/default/?filters%5Bterm%5D=wcpay&filters%5Bterm_scope%5D=scope_references&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc))
		* Français de Belgique `fr_BE` ([translate.wordpress.com link](https://translate.wordpress.com/projects/wpcom/fr-be/default/?filters%5Bterm%5D=wcpay&filters%5Bterm_scope%5D=scope_references&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc))
10. Repeat steps above with a language **unsupported by wpcom**, e.g. Polish `pl_PL`
	* The email and CSV language should be provided in English.

**WPCOM-compatible languages**
| WPCOM language code | WP locale code | Language                       |
|---------------------|----------------|--------------------------------|
| **ar**              | ar             | Arabic                         |
| **de**              | de_*           | German                         |
| **es**              | es_*           | Spanish                        |
| **fr**              | fr_*           | French                         |
| **he**              | he_*           | Hebrew                         |
| **id**              | id_*           | Indonesian                     |
| **it**              | it_*           | Italian                        |
| **ja**              | ja             | Japanese                       |
| **ko**              | ko_*           | Korean                         |
| **nl**              | nl_*           | Dutch (Netherlands)            |
| **pt-br**           | pt_BR          | Portuguese (Brazil)            |
| **ru**              | ru_*           | Russian (Russia)               |
| **sv**              | sv_*           | Swedish (Sweden)               |
| **tr**              | tr_*           | Turkish (Turkey)               |
| **zh-cn**           | zh_CN          | Simplified Chinese (Singapore) |
| **zh-tw**           | zh_TW          | Traditional Chinese (Taiwan)   |

------------------

### TODO

- [x] Consider mutating `locale` to match WPCOM langCode in [PHP REST API controller](https://github.com/Automattic/woocommerce-payments/blob/b20b368e76053c8a6be2e1f8ab492b9f9800b3bb/includes/admin/class-wc-rest-payments-transactions-controller.php/#L167) instead
	- I've taken this approach in 069aab4
- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### Additional information

As discussed in the #10149 comments, I initially considered using the `WP locale` → `WPCOM language code` mapping available in [@automattic/languages](https://github.com/Automattic/wp-calypso/blob/11523e35d08c9f747ef1deeca0bece9e664e9480/packages/languages/README.md). This would have allowed us to rely on this package as the source of truth for wpcom "langSlugs". A downside of this approach is that this package is relatively heavy, adding +5kB to various WooPayments JS bundle sizes.

Instead, I've decided to reduce the complexity of this solution and move the language code conversion logic to PHP.

I have not found a PHP package/resource with the same list of WP Locale → WPCOM Language. However, in reducing the hardcoded list to only the three that are region-specific, the maintenance burden is reduced. This approach is common across A8C ([GH search](https://github.com/search?q=org%3AAutomattic+pt-br+language%3APHP+&type=code)), of which I found [Jetpack's](https://github.com/Automattic/jetpack/blob/0ed6e32cb2a5c4c0f7a34d76a8606fedf7ba8321/projects/packages/jetpack-mu-wpcom/src/common/index.php#L19C1-L39C2) to be the simplest, which I've adapted and used in #10197.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10197` or branch name `fix/10149-csv-export-dash-separated-locales-not-working` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/10149-csv-export-dash-separated-locales-not-working) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9c0e873b0fe06bb752563963cc2447eb28650566
- Build time: 2025-07-04 07:26:53 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/data/deposits/resolvers.js [hunk 1]
```diff
@@ -84,7 +84,7 @@ const formatQueryFilters = ( query ) => ( {
 	],
 	status_is: query.statusIs,
 	status_is_not: query.statusIsNot,
-	locale: query.userLocale,
+	locale: query.locale,
```
Comment (Jinksi) [inline client/data/deposits/resolvers.js:87]: Leaving this as a generic query param, since this could be site, user or manually-selected locale in the future. These endpoints do not mandate this to be the user locale.

File: includes/class-wc-payments-utils.php [hunk 2]
```diff
@@ -1251,74 +1251,31 @@ public static function enqueue_style( $handle, $path = '', $deps = [], $version
...
-	 * Returns language data: english name and native name
+	 * Converts a WP locale to a wpcom-compatible language code.
 	 *
-	 * @param string $language Language code.
+	 * @see Automattic\Jetpack\Jetpack_Mu_Wpcom\Common::get_iso_639_locale() for similar logic.
+	 * @see https://translate.wordpress.com/projects/wpcom/ for the current state of wpcom translations.
 	 *
-	 * @return array
-	 */
-	public static function get_language_data( $language ) {
```
Comment (Jinksi) [inline includes/class-wc-payments-utils.php:1286]: `get_language_data` is no longer used.

File: includes/class-wc-payments-utils.php [hunk 3]
```diff
@@ -1251,74 +1251,31 @@ public static function enqueue_style( $handle, $path = '', $deps = [], $version
...
-			return $locale;
-		}
-
-		// Remove the country code and try with that.
-		$base_locale = substr( $locale, 0, 2 );
-		if ( in_array( $base_locale, $supported, true ) ) {
-			return $base_locale;
+	public static function convert_to_server_locale( string $wp_locale ): string {
+		$wp_locale_lowercase                    = strtolower( $wp_locale );
+		$region_specific_wpcom_language_codes   = [ 'pt_br', 'pt-br', 'zh_tw', 'zh-tw', 'zh_cn', 'zh-cn' ];
```
Comment (Jinksi) [inline includes/class-wc-payments-utils.php:1290]: Reducing the manual mapping of locales only to those that are region-specific.

This approach is borrowed from [Jetpack's `get_iso_639_locale()`￼](https://github.com/Automattic/jetpack/blob/0ed6e32cb2a5c4c0f7a34d76a8606fedf7ba8321/projects/packages/jetpack-mu-wpcom/src/common/index.php#L19C1-L39C2)

File: tests/js/jest-test-file-setup.js [hunk 4]
```diff
@@ -75,7 +75,8 @@ global.wcSettings = {
 		failed: 'Failed',
 		paid: 'Paid',
 	},
-	l10n: {
+	locale: {
+		siteLocale: 'en_US',
 		userLocale: 'en_US',
```
Comment (Jinksi) [inline tests/js/jest-test-file-setup.js:80]: Updating this to the accurately match what is available in the `wcSettings` global JS variable.

**Comment by Jinksi** [comment]
In testing, I've noticed that using "Portugese" other than "Portugese (Brazil)" `pt_PT` results in partially translated emails.

image


⚠️ Before merging, we'll need to clarify the expected behaviour:
* If partially-translated emails are to be avoided, reinstate the hard-coded list of translations and enforce the fallback to `en` within client.
	* Alternatively, let server manage which languages will be provided and which will fall back to `en` (this makes more sense)
* If partially-translated emails are OK, continue allowing server to handle the fallback translations.

**Update** in testing, I notice that other emails are partially translated when using `pt_PT`, e.g. WooCommerce new order emails.

File: client/data/deposits/resolvers.js (hunk 1 above)
Comment (haszari) [reply client/data/deposits/resolvers.js:87]: (Side note not relevant to this PR) 

Is this `formatQueryFilters` operating as an "allow list"?

It looks like the outcome of this method is to:

- Convert "pascalCase" keys to underscore snake_case vibe (server uses snake_case convention).
- Format (render to consistent text) some query data e.g. dates.
- And in the case of `match` and `locale`, allow them through unchanged.

Low priority questions…

- Is the "allow list" functionality intended, would it be simpler to trust the client (calling code) and only format what needs formatting, allow any keys through?
- Could we use a generic snake_case conversion instead of doing it manually, key by key?

File: client/data/disputes/resolvers.js [hunk 5]
```diff
@@ -38,7 +38,7 @@ const formatQueryFilters = ( query ) => ( {
 			: query.search,
 	status_is: query.statusIs,
 	status_is_not: query.statusIsNot,
-	locale: query.userLocale,
+	locale: query.locale,
 } );
```
Comment (haszari) [inline client/data/disputes/resolvers.js:42]: Similar comment to above: are these intentionally allow-lists or could we simplify by using generic processing for query args.

File: client/deposits/list/index.tsx [hunk 6]
```diff
@@ -214,7 +214,7 @@ export const DepositsList = (): JSX.Element => {
 
 	const endpointExport = async () => {
 		const userEmail = wcpaySettings.currentUserEmail;
-		const userLocale = wcpaySettings.userLocale.code;
+		const locale = wcSettings.locale.userLocale;
```
Comment (haszari) [inline client/deposits/list/index.tsx:221]: This is deceptive! 

- Is `wcSettings.locale.userLocale` a ~2-letter code?
- `wcpaySettings.userLocale.code` is a struct with other stuff in it (`code: english_name: ; native_name: ;`) - do we need it in our settings?

Using the store settings seems cleaner to me 🚀

Comment (haszari) [reply client/deposits/list/index.tsx:221]: > This is deceptive!

(i.e. took me a while to see what was changing)

Comment (haszari) [reply client/deposits/list/index.tsx:221]: OMG nice, you have removed `wcpaySettings.userLocale` 🫡

File: client/globals.d.ts [hunk 7]
```diff
@@ -123,28 +123,6 @@ declare global {
...
-			 * @example 'Spanish'
-			 */
-			english_name: string;
-			/**
-			 * The native name of the locale.
-			 *
-			 * @example 'Español'
-			 */
-			native_name: string;
-		};
```
Comment (haszari) [inline client/globals.d.ts:161]: 🫡 oh captain, my captain

remove that redundant code 🧹

File: includes/admin/class-wc-rest-payments-disputes-controller.php [hunk 8]
```diff
@@ -147,11 +147,13 @@ public function close_dispute( $request ) {
...
 	 */
 	public function get_disputes_export( $request ) {
-		$user_email = $request->get_param( 'user_email' );
-		$locale     = $request->get_param( 'locale' );
-		$filters    = $this->get_disputes_filters( $request );
+		$user_email   = $request->get_param( 'user_email' );
+		$wpcom_locale = WC_Payments_Utils::convert_to_server_locale(
+			$request->get_param( 'locale' )
+		);
+		$filters      = $this->get_disputes_filters( $request );
```
Comment (haszari) [inline includes/admin/class-wc-rest-payments-disputes-controller.php:173]: Nice and simple to do this inline. Long term I wonder if we might want middleware-style generic converters for various standard args.

That is probably overengineering, but at the same time, I worry that our request wrapper handling in client is too manual, since it's almost a 1:1 mapping to the service API, tweaking a few things here and there. One way to document that "magic" is to implement as middleware pattern. For example, WooPayments JavaScript front end calls store PHP/REST API, store PHP generically adds authentication for WooPayments Service (WPCOM) API.

File: includes/class-wc-payments-utils.php (hunk 2 above)
Comment (haszari) [reply includes/class-wc-payments-utils.php:1286]: Nice. And to confirm, it was only used to generate/render our JS settings data, which was not needed?

File: includes/class-wc-payments-utils.php [hunk 9]
```diff
@@ -1251,74 +1251,31 @@ public static function enqueue_style( $handle, $path = '', $deps = [], $version
...
-			'native_name'  => 'English (United States)',
-		];
-	}
-
-	/**
-	 * Converts a locale to the server supported languages.
-	 *
-	 * @param string $locale The locale to convert.
-	 *
-	 * @return string Closest locale supported ('en' if NONE)
```
Comment (haszari) [inline includes/class-wc-payments-utils.php:1311]: 💣

File: includes/class-wc-payments-utils.php (hunk 3 above)
Comment (haszari) [reply includes/class-wc-payments-utils.php:1290]: > This approach is borrowed from [Jetpack's get_iso_639_locale()￼](https://github.com/Automattic/jetpack/blob/0ed6e32cb2a5c4c0f7a34d76a8606fedf7ba8321/projects/packages/jetpack-mu-wpcom/src/common/index.php#L19C1-L39C2)

Recommend adding a comment "maintenance hint" about this, i.e. guide future team when WPCOM adds a new language (or removes one).

File: includes/class-wc-payments-utils.php [hunk 10]
```diff
@@ -1251,74 +1251,31 @@ public static function enqueue_style( $handle, $path = '', $deps = [], $version
...
-
-		if ( in_array( $locale, $supported, true ) ) {
-			return $locale;
-		}
-
-		// Remove the country code and try with that.
-		$base_locale = substr( $locale, 0, 2 );
-		if ( in_array( $base_locale, $supported, true ) ) {
-			return $base_locale;
+	public static function convert_to_server_locale( string $wp_locale ): string {
```
Comment (haszari) [inline includes/class-wc-payments-utils.php:1288]: Minor nitpick on naming, could be clearer IMO. 

- `convert` – is `map` clearer? I.e. we are mapping from one system to another.
- `server` – I will always rail against the word `server`, it's too generic. In this case we could use `wpcom` (the platform our service runs on), or `woopayments_service`. 
- Maybe `map_to_wpcom_locale_code`? I think code helps too, clarify that the input and output are the ~2 letter code things; `locale` could be represented a few ways.

Also suggest refreshing the doc comment (it's pretty clear as is), especially if you tweak the name.

File: includes/class-wc-payments-utils.php (hunk 3 above)
Comment (haszari) [reply includes/class-wc-payments-utils.php:1290]: Maybe in the docblock.

File: includes/class-wc-payments-utils.php [hunk 11]
```diff
@@ -1251,74 +1251,31 @@ public static function enqueue_style( $handle, $path = '', $deps = [], $version
...
+
+		$language_code = $is_region_specific_wpcom_language_code ?
+			// If it is a region-specific language code, we replace the underscore with a dash, e.g. 'pt_br' => 'pt-br'.
+			str_replace( '_', '-', $wp_locale_lowercase ) :
+			// Otherwise, we remove the country code and return only the language code, e.g. 'nl_NL' => 'nl'.
+			preg_replace( '/([-_].*)$/i', '', $wp_locale_lowercase );
+
+		if ( empty( $language_code ) ) {
+			// If the language code is empty, we return 'en' as a fallback.
+			return 'en';
```
Comment (haszari) [inline includes/class-wc-payments-utils.php:1301]: There's a mix of early-return and "return $language_code" style here. I recommend rewriting as early-return while here, then each case will be a single if, no nesting.

Hmm .. if this is verbatim from Jetpack code … maybe should leave as is? If so make that clear in the comments.

File: tests/unit/test-class-wc-payments-utils.php [hunk 12]
```diff
@@ -891,6 +891,37 @@ public function test_convert_to_stripe_locale() {
...
+			'Supported locale (Korean)'                => [ 'ko_KR', 'ko' ],
+			'Supported locale (Dutch)'                 => [ 'nl_NL', 'nl' ],
+			'Supported locale (Portuguese (Brazil))'   => [ 'pt_BR', 'pt-br' ],
+			'Supported locale (Russian)'               => [ 'ru_RU', 'ru' ],
+			'Supported locale (Swedish)'               => [ 'sv_SE', 'sv' ],
+			'Supported locale (Turkish)'               => [ 'tr_TR', 'tr' ],
+			'Supported locale (Chinese (Simplified))'  => [ 'zh_CN', 'zh-cn' ],
+			'Supported locale (Chinese (Traditional))' => [ 'zh_TW', 'zh-tw' ],
+			'Empty locale fallback to en'              => [ '', 'en' ],
+		];
```
Comment (haszari) [inline tests/unit/test-class-wc-payments-utils.php:922]: Is it worth testing a range of unsupported locales? The empty case is likely less important than uncommon language.

Also I would like to see a test for inexact match, e.g. `en_AU` or `pt_PT`. Maybe useful to group & comment the various test (map) scenarios in the provider too. Another way to do that is to have separate tests for each of the mapping scenarios, then the test name + provider name are "self documenting".

**Review by haszari — APPROVED** [review]
I have done a code review only. I approve! 

- Great to see some redundant code / data (page bloat!) removed. 
- The mapping is clearly defined and easier to maintain when supported languages change.

I left a bunch of comments about style and architecture considerations, I'll leave it to y'all to decide if any are worth following up. 

Also I suggest tweaking the title to celebrate the win - translated service-generated emails now use correct language? The description has good info on the "how" :)

**Comment by nagpai** [comment]
⚠️  I did a manual test on my Pressable hosted test site. 

- I set the user profile language to Brazilian Portuguese. 
- For some reason, I see the locale param being passed as `pt_BR` . I would expect this to be `pt-br`

image

- The language of the email seems  English, but the headers look Portuguese. 

Here's what I see when I change the language to German . 

image

**Comment by Jinksi** [comment]
Thanks for testing @nagpai 

> For some reason, I see the locale param being passed as pt_BR . I would expect this to be pt-br

In this new implementation, the locale passed from browser -> PHP REST API controller should be the WP locale ('pt_BR'). This will map to 'pt-br' when passing from controller → WPCOM.

So the headers are correct for this implementation.

The email should translate for 'pt-br', so I'll also conduct further testing to see if I can see the correctly translated emails for various languages.

**Comment by Jinksi** [comment]
> The language of the email seems English, but the headers look Portuguese.

@nagpai This highlights a problem with our approach to email transactions.

I've been able to reproduce this problem where emails are in one language, CSV in another.

Config:
* Site & WCPay account WP locale code `ja`
* User profile language WP locale code `pt_BR`

Result:
  * Email translated to Japanese
  * CSV translated to Portuguese


Therefore:
* CSV export emails will always be sent in the site locale: [source](https://github.com/Automattic/transact-platform-server/blob/7a80507a9b76e77147c9a26d78f5dc516720e60e/server/wp-content/rest-api-plugins/endpoints/wcpay/service/class-email-service.php#L758-L785).
* A transact-platform-server change is required to ensure the user locale is used for email as well.
* Due to a separate transact-platform-server issue (I’ll open one today), emails will not be translated for the majority of WP site locales represented by > 2 chars, falling back to English.
* I will mark this PR as blocked and open a new transact-platform-server PR proposing a fix for email translations. This client PR may change, removing the WP → WPCOM locale mapping from the client. FYI @haszari, I'll also take your suggestions on board once I finalise what code is remaining (e.g. the comments on the mapping function may not be relevant).

**Comment by Jinksi** [comment]
> I will mark this PR as blocked and open a new transact-platform-server PR proposing a fix for email translations.

I've opened issue https://github.com/Automattic/transact-platform-server/issues/7161 for this.

**Comment by Jinksi** [comment]
https://github.com/Automattic/transact-platform-server/issues/7161 has been resolved/merged, so work on this PR can continue.

**Review by RadoslavGeorgiev — APPROVED** [review]
The changes look good! :shipit: 

- All changes in code make sense.
- I tested on a JN site with different versions of French and Portuguese, everything worked as expected, at least with transactions. I have not tested the other screens, but based on how similar the changes are, I am confident that those would work as expected.

**Comment by dmvrtx** [comment]
@Jinksi , @haszari  Thank you for working on this and for leaving it in a great shape!

**Comment by Jinksi** [comment]
Awesome, happy to see this merged! Thanks @dmvrtx @RadoslavGeorgiev 🍻
