### PR TITLE
Clarify "disputed" order note: add amount and deadline 

### LINKED ISSUE #6379: Enrich "order has dispute" order note with amount, reason, and deadline
### Describe the bug

WCPay adds an order note when a dispute is raised. This note doesn't have much detail.

> (old wording) Payment has been disputed as fraudulent. See <link>dispute overview</link> for more details.

Screenshot 2023-05-26 at 1 55 42 PM

The goal of this issue is to update this note so it has relevant details, and ultimately help merchants to quickly respond to disputes.

New wording: 

> Payment has been <link>disputed for {AMOUNT} with {REASON}. Response due by {DEADLINE}</link>. (link to dispute detail)

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by haszari**
Fixes #6379 

#### Changes proposed in this Pull Request

This PR updates the order note added to disputed orders to make it more informative and more actionable. 

Example (single currency store):

Screenshot 2023-05-31 at 1 18 32 PM

Example (multi-currency store):

Multicurrency store disputed order note

Previous message:

> Payment has been disputed as %1$s. See <a>dispute overview</a> for more details.

New message includes amount and deadline date: 

> Payment has been disputed for %1$s with reason %2$s. <a>Response due by %3$s</a>.

Note that the reason displayed is the raw value from Stripe API and is not currently converted to human-readable string. This will need to be updated, either as part of #6356 (see checklist item 2: `Ensure consistent naming of dispute types across WCPay platform (server, client, documentation)`) or a separate issue.

#### Testing instructions
The order note is generated in response to a webhook, so you will need webhooks working on your store. I did this by testing against WCPay production server and using [ngrok](https://ngrok.com/) so my dev site has a publicly available hostname, can also use WCPay dev tools and local WCPay server.

- Set up store so connected to WCPay (test mode) and have products to buy.
- Purchase a product using a [dispute card number](https://stripe.com/docs/testing#disputes) e.g. `4000000000000259`
- View the order edit page for the order
- Should show an informative dispute notice with correct details
  - Please crosscheck deadline, amount etc are correct and consistent with dispute details

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : https://github.com/Automattic/woocommerce-payments/issues/6356#issuecomment-1571099446 
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6381` or branch name `fix/6379-clarify-disputed-order-note` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6379-clarify-disputed-order-note) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 1f9fb77094a29a3f2cc1268dd44bf163baf5ad66
- Build time: 2023-06-08 04:08:48 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by Jinksi** [comment]
I haven't reviewed yet but notice that the PHP `WC_Payments_Order_Service_Test` tests are failing.

**Comment by haszari** [comment]
> I haven't reviewed yet but notice that the PHP WC_Payments_Order_Service_Test tests are failing.

Good point! These should now be fixed 🤞🏻

File: includes/class-wc-payments-order-service.php [hunk 1]
```diff
@@ -276,16 +276,18 @@ public function mark_order_blocked_for_fraud( $order, $intent_id, $intent_status
 	 *
 	 * @param WC_Order $order      Order object.
 	 * @param string   $dispute_id The ID of the dispute associated with this order.
-	 * @param string   $reason     The reason for the dispute.
+	 * @param string   $amount     The disputed amount – formatted currency value.
+	 * @param string   $reason     The reason for the dispute – human-readable text.
+	 * @param string   $deadline   The deadline for responding to the dispute - formatted date string.
```
Comment (Jinksi) [inline includes/class-wc-payments-order-service.php]: What are your thoughts on naming this `$due_by` rather than `$deadline` to keep the naming consistent with other dispute-related logic?

Although I see that using a different var name helps to distinguish this since it is a formatted date string.

File: includes/class-wc-payments-order-service.php [hunk 2]
```diff
@@ -276,16 +276,18 @@ public function mark_order_blocked_for_fraud( $order, $intent_id, $intent_status
 	 *
 	 * @param WC_Order $order      Order object.
 	 * @param string   $dispute_id The ID of the dispute associated with this order.
-	 * @param string   $reason     The reason for the dispute.
+	 * @param string   $amount     The disputed amount – formatted currency value.
+	 * @param string   $reason     The reason for the dispute – human-readable text.
```
Comment (Jinksi) [inline includes/class-wc-payments-order-service.php:280]: In this description, "human-readable text" indicates to me that this is a formatted string (`Bank cannot process`) whereas it is actually a dispute reason "key" (`bank_cannot_process`).

Although I understand that this will be replaced a nicely formatted string in a subsequent PR.

File: includes/class-wc-payments-webhook-processing-service.php [hunk 3]
```diff
@@ -524,7 +524,17 @@ private function process_webhook_dispute_created( $event_body ) {
...
 		$reason       = $this->read_webhook_property( $event_object, 'reason' );
-		$order        = $this->wcpay_db->order_from_charge_id( $charge_id );
+		$amount_raw   = $this->read_webhook_property( $event_object, 'amount' );
+		$evidence     = $this->read_webhook_property( $event_object, 'evidence_details' );
+		$due_by       = $this->read_webhook_property( $evidence, 'due_by' );
+
+		$order = $this->wcpay_db->order_from_charge_id( $charge_id );
+
+		$currency = $order->get_currency();
+		$amount   = wc_price( WC_Payments_Utils::interpret_stripe_amount( $amount_raw, $currency ), [ 'currency' => strtoupper( $currency ) ] );
```
Comment (Jinksi) [inline includes/class-wc-payments-webhook-processing-service.php]: This currency format comes out different to that used for the order success note. E.g. `110,00 € EUR` vs `110,00 €`

Order success note:
image

Dispute note:
image


What do you think about using the same method ([`WC_Payments_Order_Service::get_order_amount()`](https://github.com/Automattic/woocommerce-payments/blob/8710fc79037796965e469b448c49cbc0a7782d4a/includes/class-wc-payments-order-service.php#L782)) to get the formatted currency string:

https://github.com/Automattic/woocommerce-payments/blob/8710fc79037796965e469b448c49cbc0a7782d4a/includes/class-wc-payments-order-service.php#L782

File: includes/class-wc-payments-webhook-processing-service.php [hunk 4]
```diff
@@ -536,7 +546,7 @@ private function process_webhook_dispute_created( $event_body ) {
 			);
 		}
 
-		$this->order_service->mark_payment_dispute_created( $order, $dispute_id, $reason );
+		$this->order_service->mark_payment_dispute_created( $order, $dispute_id, $amount, $reason, $due_by );
```
Comment (Jinksi) [inline includes/class-wc-payments-webhook-processing-service.php:552]: Idea: since we are not shipping human-readable dispute reasons in this PR, what do you think about wrapping the `$reason` key in quotes to make it more readable in the meantime.

E.g. `Payment has been disputed for 110.00 € with reason "fraudulent".`

**Review by Jinksi — APPROVED** [review]
LGTM @haszari 🙌 🏆

I've left some ideas and comments that do not block merging.

I've tested with a EUR currency disputed order. The amount & due date displayed in the note is accurate. Clicking on the note redirects to the correct dispute details page.

image

File: includes/class-wc-payments-webhook-processing-service.php (hunk 3 above)
Comment (haszari) [reply includes/class-wc-payments-webhook-processing-service.php]: Tricky … not sure how to call this one, so leaving as is for now. Tracing how that value is rendered, I see it uses `WC_Payments_Explicit_Price_Formatter::get_explicit_price()`. The method not quite right for my purposes – it depends on order and pulls currency from order (we need to use dispute, even though it should be the same), so would need to refactor to remove dependency on order.

Pros of current approach:

- Deferring to WooCommerce core for rendering prices. This should be more consistent overall. E.g. respect user preferences for number formatting. 
- Less code impact (though … maybe we should dig into `WC_Payments_Explicit_Price_Formatter` as a follow up - see below). 

Cons of current approach:

- Inconsistent price formats between WCPay order notes.

Which makes me wonder - is there a bug / arbitrary difference in `WC_Payments_Explicit_Price_Formatter::get_explicit_price()`? I see in your screenshot there's a different decimal point, plus I don't understand why it suffixes currency symbol.

File: includes/class-wc-payments-order-service.php (hunk 2 above)
Comment (haszari) [reply includes/class-wc-payments-order-service.php:280]: Good spotting! This is an aspirational (fake it til you make it) comment, anticipating the human-readable refresh coming soon :)

I've added the quotes 2e0acbad724cd0ded67be93cfa6ef2ac029338d4, I think these are useful generally. When it's human-readable string, the sentence will be more readable with quotes around e.g. `"Product not recieved"`.

File: includes/class-wc-payments-webhook-processing-service.php (hunk 3 above)
Comment (haszari) [reply includes/class-wc-payments-webhook-processing-service.php]: I'll retest with a multicurrency setup, want to ensure this is working correctly in that case. For example USD and CAD could be confusing.

Comment (Jinksi) [reply includes/class-wc-payments-webhook-processing-service.php]: Interesting! Some additional examples:

**WCPay disputes screens** display EURO amounts as `€110.00 EUR` with a decimal not comma and show `EUR`: 

Disputes List
image

Dispute details
image

The **WC order screen total** shows as `110.00 € EUR` with a decimal.
image

File: includes/class-wc-payments-webhook-processing-service.php (hunk 4 above)
Comment (haszari) [reply includes/class-wc-payments-webhook-processing-service.php:552]: Example:

Screenshot 2023-06-07 at 12 31 18 PM

File: includes/class-wc-payments-order-service.php (hunk 1 above)
Comment (haszari) [reply includes/class-wc-payments-order-service.php]: Consistency wins – renamed 4def31a95f9a8396a0a9edf5019a914456f9dcc0 – thanks for picking that up.

File: includes/class-wc-payments-order-service.php (hunk 2 above)
Comment (brucealdridge) [reply includes/class-wc-payments-order-service.php:280]: I was just writing about this need in https://github.com/Automattic/woocommerce-payments/pull/6475 but you beat me to it. Thank you!

File: includes/class-wc-payments-webhook-processing-service.php (hunk 3 above)
Comment (haszari) [reply includes/class-wc-payments-webhook-processing-service.php]: We need the currency consistently displayed in both order notes, so I'm fixing it. Will probably refactor `WC_Payments_Explicit_Price_Formatter` so there's a simple render price function I can use.

Screenshot 2023-06-07 at 2 34 59 PM

Comment (haszari) [reply includes/class-wc-payments-webhook-processing-service.php]: I've done a light refactor so we can use `WC_Payments_Explicit_Price_Formatter` to append currency symbol when needed. 3887d90461f744d6262df99c83b9c601200b2da6

**Comment by haszari** [comment]
Thanks for the feedback @Jinksi @brucealdridge – I think this PR's good to merge now. I'll leave it open for the actions to run, so if you want to re-review or retest my refactor of `render_explicit_price_with_currency()` go for it, otherwise I'll merge later today / tomorrow 😁

**Comment by Jinksi** [comment]
@haszari GH checks are failing, which may or may not be related to your changes.

I'll retest the `render_explicit_price_with_currency()` changes today.

**Comment by haszari** [comment]
> GH checks are failing, which may or may not be related to your changes.

I'll investigate!

File: includes/class-wc-payments-explicit-price-formatter.php [hunk 5]
```diff
@@ -106,21 +109,38 @@ public static function unregister_formatted_woocommerce_price_filter() {
...
+	 *
+	 * In multicurrency stores, order and price values are rendered with currency suffix.
+	 * This method only renders the currency suffix if appropriate (see `should_output_explicit_price`).
+	 *
+	 * @param string  $price A price value (as a string).
+	 * @param ?string $currency_code Currency of the price.
+	 *
+	 * @return string Price value with currency code suffix if necessary.
+	 */
+	public static function render_explicit_price_with_currency( string $price, ?string $currency_code ) {
```
Comment (Jinksi) [inline includes/class-wc-payments-explicit-price-formatter.php]: Thought: consider renaming this from `render_explicit_price_with_currency` to `get_explicit_price_with_currency`, since this does not actually render the string to the page.

**Review by Jinksi — APPROVED** [review]
👏 I've retested after merge and this looks good. I've left a minor non-blocking comment about the naming of a method.


On my multi-currency store, the dispute note I see reads:
```
Payment has been disputed for 110.00 € EUR with reason "fraudulent". Response due by June 17, 2023.
```

image

File: includes/class-wc-payments-explicit-price-formatter.php (hunk 5 above)
Comment (haszari) [reply includes/class-wc-payments-explicit-price-formatter.php]: Fair enough, I tend to use `render` for generating html, but `get` is more consistent with this class/codebase.

**Comment by haszari** [comment]
Merging! (queue)

File: includes/class-wc-payments-explicit-price-formatter.php (hunk 5 above)
Comment (Jinksi) [reply includes/class-wc-payments-explicit-price-formatter.php]: Updated in 5260756
