### PR TITLE
fire dispute row click from click on any cell, not just button

### LINKED ISSUE #8204: Dispute list row clicks aren't tracked
### Describe the bug
We have tracks events to understand usage of various screens and flows. 

In the dispute list, the merchant can see a list of disputes and click through to see details on a specific dispute.

That action is only currently tracked if merchant clicks `Respond` button. We should also track when they click the row (which performs same action) – and use the same event.

Screenshot 2024-02-15 at 12 19 50 PM

Discovered when working on #8069, spun off a new issue as that PR is no longer needed.

### PR DESCRIPTION
**Pull request by haszari**
Fixes #8204

#### Changes proposed in this Pull Request
Ensures the tracks event `wcpay_disputes_row_action_click` is fired consistently when merchant clicks to view details. We have an action button in the row, but clicking in any row cell performs the same action. So we need to make sure all ways of navigating to dispute details are tracked.

I suspect the row-click was added later (after the button and event) to make it easier to view dispute, but the existing tracks event was missed.

Note that the event name is not ideal - `wcpay_disputes_row_action_click`. Really the event is `wcpay_disputes_list_view_detail_click` or similar. However it's a good match – this event fires when merchant clicks the row or a specific call to action button in the row. Keeping the existing name so we have consistent data – no major issue with current event name IMO.

Screenshot 2024-02-15 at 12 19 50 PM

#### Testing instructions
- Get your store in a state where it has some disputes, in progress/needs response.
- Ensure your store is opted in to tracking and you can see events (browser dev tools `t.gif` or in tracks live view, etc).
- View `Payments > Disputes`.
- Click a dispute to see details.
  - Try clicking various places in the row - button and random cells/row background.
- Should always see `wcpay_disputes_row_action_click` when navigating to dispute detail.

Also test taking other actions on that page, e.g. view order or view customer. The correct events should fire, i.e. should not see `wcpay_disputes_row_action_click` when navigating to something other than dispute detail.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️) n/a - no functonality change
- [x] Tested on mobile (or does not apply)

**Post merge**

Post-merge tasks all n/a:

- No specific manual one-off testing required
- No changes to critical flows / common flows tested every release
- No merchant-facing changes to add to What's New

<details>
- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.
</details>

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8205` or branch name `fix/8204-consistently-track-dispute-table-clicks` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8204-consistently-track-dispute-table-clicks) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 50f5ef3adf0759c220b93fffa5ca1e8a9ce515b3
- Build time: 2024-02-14 23:14:20 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/disputes/index.tsx [hunk 1]
```diff
@@ -226,9 +226,19 @@ export const DisputesList = (): JSX.Element => {
...
+			// Use client-side routing to avoid page refresh.
+			e.preventDefault();
+			recordEvent( 'wcpay_disputes_row_action_click' );
+			const history = getHistory();
+			history.push( getDetailsURL( dispute.charge_id, 'transactions' ) );
+		};
 		const clickable = ( children: React.ReactNode ): JSX.Element => (
 			<ClickableCell
 				href={ getDetailsURL( dispute.charge_id, 'transactions' ) }
+				onClick={ onClickDisputeRow }
```
Comment (Jinksi) [inline client/disputes/index.tsx:241]: In testing, I discovered that `onClick` of `<ClickableCell />` is not fired when using `CMD + click`, therefore the tracks event is not recorded.

This is also the case for deposit table row `CMD + click` events.

This is a minor issue, unsure if it's worth fixing in this PR.

**Review by Jinksi — APPROVED** [review]
Nice one @haszari 🌟

This tests well – this event was recorded when clicking on the dispute row as well as the see details and `Respond now`/`See details` button. ✅

`CMD + click` doesn't record the event, as mentioned in my comment, above/below, but this may not be a big enough problem to worry about.

File: client/disputes/index.tsx (hunk 1 above)
Comment (haszari) [reply client/disputes/index.tsx:241]: > In testing, I discovered that onClick of <ClickableCell /> is not fired when using CMD + click, therefore the tracks event is not recorded.

TIL!

> This is a minor issue, unsure if it's worth fixing in this PR.

Agree it's not core to this PR, but feels like a moderate problem / gap with our components. My take is that we should be able to support cmd-click where practical, and those user actions should be tracked consistently. The part that's confusing me is cmd-click works – the user action happens – but the tracking doesn't. Could be an issue down in woo `Link` component.


https://github.com/woocommerce/woocommerce/blob/a0b72b0546cbf6366defbe7db4e84f692de4e200/packages/js/components/src/link/index.tsx#L37-L46

Can you log an issue for this?

Comment (haszari) [reply client/disputes/index.tsx:241]: Hmm … maybe we could add native tracks ability to components 🤔 - i.e. pass event name and props as component props, and delegate the `recordEvent` to the component.
