### PR TITLE
Disable Direct Checkout When WooPayments Gateway Is Disabled

### LINKED ISSUE #2829: Reactivating the Woo subscription does not activate the WCPay subscription
### Describe the bug

When you put a Woo Subscription on-hold, the WCPay Subscription is correctly being marked with "paused collection", but when you reactivate the subscription in Woo, the WCPay Subscription is still paused.

I think this issue is caused by a combination of things on both server and plugin side.

When a Woo Subscription is activated we send a request to WCPay Server to reactivate the subscription [here](https://github.com/Automattic/woocommerce-payments/blob/0a5ba9a7de88974e93733277170f01663ce757ed/includes/subscriptions/class-wc-payments-subscription-service.php#L210-L218).

The server expects this `pause_collection` to be an array, but we're sending it an empty string which it may not be liking (server code here: https://git.io/JENfB).

In the [Stripe API docs](https://stripe.com/docs/billing/subscriptions/pause#unpausing), they detail how to unpause a subscription by setting `pause_collection` as empty so we may need to make sure Server is handling this properly

### To Reproduce

1. If you have the subscriptions plugin activated, deactivate this to use WCPay built-in subscriptions.
2. While on branch `add/subscription_change_method`, purchase a new subscription (you may need to create a new WCPay subscription product if you don't have one)
2. On checkout complete, confirm the subscription is activated on your connected Stripe account
3. Suspend the subscription Woo
4. Confirm the subscription is paused in the stripe dashboard
5. Reactivate the subscription in Woo.
6. Notice the WCPay subscription in the stripe dashboard is still paused :x:

### Actual behavior

WCPay Subscriptions aren't being reactivated in the stripe dashboard when they're activated in Woo.

### PR DESCRIPTION
**Pull request by lovo-h**
Fixes 2829-gh-Automattic/woopay

#### Changes proposed in this Pull Request

The changes in this PR ensure that the WooPay Direct Checkout (DC) flow is enabled only when the WooPayments gateway is enabled.

Additionally, the changes in this PR ensure that filters/hooks are avoided to avoid compatibility issues with other gateways.

#### Testing instructions

**Reproduce Bug: DC Still Redirects to WooPay When WooPayments Gateway Is Disabled**
* Ensure you are on the `develop` branch.
* As a merchant, navigate to **Payments > Settings**.
* Enable WooPay, disable WooPayments, and click the **Save changes** button.
* As a shopper, ensure you are logged in to WooPay.
* Navigate to the merchant shop, add an item to the cart, and navigate to the cart page.
* Click the **Proceed to Checkout**.
* Confirm you are navigated to WooPay.
* Click **Place order** button.
* Confirm you received the following error: `Credit card / debit card is not available for this order—please choose a different payment method`.

**Confirm Fix: DC Does Not Redirect to WooPay When WooPayments Gateway Is Disabled**
* Ensure you are on the `fix/2829-disable-direct-checkout-when-woopayments-disabled` branch.
* As a merchant, navigate to **Payments > Settings**.
* Enable WooPay, disable WooPayments, and click the **Save changes** button.
* As a shopper, ensure you are logged in to WooPay.
* Navigate to the merchant shop, add an item to the cart, and navigate to the cart page.
* Click the **Proceed to Checkout**.
* Confirm you are navigated to merchant checkout.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9203` or branch name `fix/2829-disable-direct-checkout-when-woopayments-disabled` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/2829-disable-direct-checkout-when-woopayments-disabled) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: a80bce23ffaeeb67946813ddfb089bda5a256a00
- Build time: 2024-08-01 16:34:45 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: tests/unit/test-class-wc-payments-features.php [hunk 1]
```diff
@@ -227,6 +227,7 @@ public function test_is_woopay_express_checkout_enabled_returns_false_when_woopa
 	}
 
 	public function test_is_woopay_direct_checkout_enabled_returns_true() {
+		update_option( 'woocommerce_woocommerce_payments_settings', [ 'enabled' => 'yes' ] );
```
Comment (asumaran) [inline tests/unit/test-class-wc-payments-features.php:230]: It would be good to add a test case checking DC is disabled if `['enabled' => 'no']`

Comment (lovo-h) [reply tests/unit/test-class-wc-payments-features.php:230]: Good call out. Added in [a80bce2](https://github.com/Automattic/woocommerce-payments/pull/9203/commits/a80bce23ffaeeb67946813ddfb089bda5a256a00).

**Review by ricardo — APPROVED** [review]
LGTM and tests well.

**Comment by ricardo** [comment]
Related to the original issue, but unrelated to this PR, I found that we're still trying to record tracks events (unsuccessfully) when WooPayments is disabled. I'll check further if this also applies to other tracks events then I'll create an issue.

https://github.com/user-attachments/assets/e40b289d-c8fc-4d6f-b807-efeb7f66aa7b

**Review by asumaran — APPROVED** [review]
Code looks good and tests as expected.

- ✅ Bug is present in `develop` branch.
- switching to `fix/2829-disable-direct-checkout-when-woopayments-disabled`
    - ✅ no redirect to WooPay on shortcode cart page
    - ✅ no redirect to WooPay on block cart page
- Install WC PayPal extension and check out to 591857fff03d2e95ef8f924b1f87e91cceaa73e9 to observe fatal error on the WC PayPal extension.
- Switch to `fix/2829-disable-direct-checkout-when-woopayments-disabled`
    - ✅ No fatal error triggered by the WC PayPal extension.
    - ✅ Subscription error not reproducible https://github.com/Automattic/woocommerce-payments/pull/9147#issuecomment-2245796901
