### PR TITLE
Correct the `AccountOverview.OverviewsResponse` TS interface `account` type to show it is nullable

### LINKED ISSUE #7920: The `AccountOverview.OverviewsResponse` TypeScript interface incorrectly shows `account` as a non-nullable type
### Describe the bug
There is a mismatch between the `OverviewsResponse` TS interface and data returned from `getAllDepositsOverviews()` while the fetch request is in progress. When in progress, the `account` is returned as `null`.

https://github.com/Automattic/woocommerce-payments/blob/b37d805915d680220c63a6b323dceed6c2def7ad/client/data/deposits/selectors.js#L58-L64

This mismatch should be fixed to ensure consistent and accurate data representation, avoiding potential bugs and confusion.

```ts
export interface OverviewsResponse {
    overviews: {
        account: Account; // ⚠️ can be null 
        currencies: Array< Overview >;
    };
    isLoading: boolean;
}
```

Discovered in https://github.com/Automattic/woocommerce-payments/pull/7883#discussion_r1424699734

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #7920

> [!note]
> This is a small, dev-facing change. I hope this requires minimal effort to review!

#### Changes proposed in this Pull Request

This PR fixes a mismatch between the `OverviewsResponse` TS interface and data returned from `getAllDepositsOverviews()` while the fetch request is in progress:

https://github.com/Automattic/woocommerce-payments/blob/b37d805915d680220c63a6b323dceed6c2def7ad/client/data/deposits/selectors.js#L58-L64

`OverviewsResponse` has been corrected to define the `overviews.account` type as `Account | null`:

```ts
export interface OverviewsResponse {
	overviews: {
		account: Account | null;
		currencies: Overview[];
	};
	isLoading: boolean;
}
```

#### Testing instructions

* Run `npx tsc --noEmit` and ensure no TS errors are returned.
* Ensure relevant GH checks tests pass.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7921` or branch name `fix/7920-correct-account-overview-account-type-nullable` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7920-correct-account-overview-account-type-nullable) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: eaa6dcea40f3c243801831a318a9c0e5a1f86962
- Build time: 2023-12-18 00:51:52 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/components/account-balances/index.tsx [hunk 1]
```diff
@@ -115,7 +115,7 @@ const AccountBalances: React.FC = () => {
 			currencyCode: overview.currency,
 			availableFunds: overview.available?.amount ?? 0,
 			pendingFunds: overview.pending?.amount ?? 0,
-			delayDays: account.deposits_schedule.delay_days,
+			delayDays: account?.deposits_schedule.delay_days,
```
Comment (shendy-a8c) [inline client/components/account-balances/index.tsx]: tl;dr; this comment is just an FYI. Not suggesting any change.

Tempted to suggest a default value so in accordance of the [loading state](https://github.com/Automattic/woocommerce-payments/blob/a638d5599d8a09d14f5826a0e6af6492830a3374/client/components/account-balances/index.tsx#L79).

```suggestion
			delayDays: account?.deposits_schedule.delay_days ?? 0,
```

However, in case of `account` is null (which by itself is impossible to pass the `if ( isLoading )` check) `account?.deposits_schedule.delay_days` being undefined looks more correct:
Screenshot 2023-12-18 at 02 19 23

than if we set `delayDays` to be 0:
Screenshot 2023-12-18 at 02 19 37

Also I wondered why TS does not complain that `delayDays` can be undefined although [delayDays' type is defined as a `number`](https://github.com/Automattic/woocommerce-payments/blob/a638d5599d8a09d14f5826a0e6af6492830a3374/client/components/account-balances/index.tsx#L41). Maybe because [here](https://github.com/Automattic/woocommerce-payments/blob/a638d5599d8a09d14f5826a0e6af6492830a3374/client/components/account-balances/index.tsx#L111) we don't strictly define the type of `depositCurrencyTabs` to be `BalanceTabProps[]`.

**Review by shendy-a8c — APPROVED** [review]
Because https://github.com/Automattic/woocommerce-payments/issues/7920 stemmed from https://github.com/Automattic/woocommerce-payments/pull/7883#discussion_r1424699734, I checked to make sure if I removed this [line](https://github.com/Automattic/woocommerce-payments/blob/a638d5599d8a09d14f5826a0e6af6492830a3374/client/deposits/index.tsx#L58C15-L58C15), TS will correctly give a warning that account might be null [here](https://github.com/Automattic/woocommerce-payments/blob/a638d5599d8a09d14f5826a0e6af6492830a3374/client/deposits/index.tsx#L70). It does, so that's good!

> I hope this requires minimal effort to review!

Not too minimal because out of curiosity, I searched all `selectors.ts` and `selectors.js` to make sure there isn't other similar case.

Found 1 possible undefined return value in [client/data/capital/selectors.ts](https://github.com/Automattic/woocommerce-payments/blob/a638d5599d8a09d14f5826a0e6af6492830a3374/client/data/capital/selectors.ts#L26) but it's not a problem there. When I tried to remove [this check](https://github.com/Automattic/woocommerce-payments/blob/a638d5599d8a09d14f5826a0e6af6492830a3374/client/components/active-loan-summary/index.tsx#L141-L143), TS will throw an error correctly, so I started to think maybe if `client/data/deposits/selectors.js` is converted to TS, the possible null account will be caught.

Not suggesting to do that though.

This PR looks good as is!

**Comment by Jinksi** [comment]
> if client/data/deposits/selectors.js is converted to TS, the possible null account will be caught.

💯 if the `/client/data dir was migrated to TS, this issue would have been made apparent before commit.

Alternatively, we can migrate existing data fetching and caching logic to react-query (demo in #7502). We'd still have to define the API request return types and tie these to `useQuery` hooks, but there'd be less boilerplate code to migrate to TS.

File: client/components/account-balances/index.tsx (hunk 1 above)
Comment (Jinksi) [reply client/components/account-balances/index.tsx]: Another thing we could do to tidy this up – we can define and return 2 distinct types: one while loading and one loaded. E.g.

```ts
export interface OverviewsLoading {
  account: null;
  isLoading: true;
}

export interface Overviews {
  account: Account;
  isLoading: false;
}

export type OverviewsResponse = OverviewsLoading | Overviews;

export function isOverviewsLoading(response: OverviewsResponse): response is OverviewsLoading {
  return response.isLoading;
}
```

Then for the `isLoading` check, we can use the type assertion function `isOverviewsLoading`. If that returns false, all following logic will be confident that `account: Account`, no need for `??` to account for possible `account: null`.

Comment (Jinksi) [reply client/components/account-balances/index.tsx]: I've used your solution in eaa6dce as a good solution for now 👍

Comment (shendy-a8c) [reply client/components/account-balances/index.tsx]: > we can define and return 2 distinct types: one while loading and one loaded

Ow wow, that's actually neat.
