### PR TITLE
Skip limits per currency check on admin pages

### LINKED ISSUE #10380: Refactor payment method registration to include all registered payment gateways
### Describe the bug

Currently, WooPayments [conditionally registers payment methods for the checkout block](https://github.com/Automattic/woocommerce-payments/blob/31dacc853e3731af145c415c4541d80ff2b63a5c/client/checkout/blocks/index.js#L88), filtering out those that are ineligible based on requirements like country, total, etc. This is problem because WooCommerce core expects all registered payment gateways to have a matching call to `registerPaymentMethod()` and WooPayments registers each UPE payment method as a gateway, via `register_gateway()` in PHP. Relevant code [here](https://github.com/woocommerce/woocommerce/blob/284d195cd1973d1a87cefbce2b398bb9eb80a7f8/plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php#L559). When a registered gateway does not have a matching call to `registerPaymentMethod()`, a warning is displayed in the checkout editor stating that the missing payment method is incompatible with the checkout block. This is a false positive and only occurs due to the mismatch described above.

One situation that triggers this warning occurs when an enabled payment method has a minimum purchase amount, and the logged-in admin has items in their cart that do not meet that minimum. The checkout block relies on StoreAPI data for cart totals; therefore, the enabled payment method is not registered via `registerPaymentMethod()` in that scenario.

Ideally, all payment methods should be registered via `registerPaymentMethod()` and their display should be controlled via `canMakePayment` as opposed to conditionally registering each payment method.

This _might_ also be an opportunity to ensure payment method names are displayed properly in the checkout block editor. For example, when the Payment Options block is highlighted, a list of payment methods appears in the sidebar. Rather than detailing each enabled payment method, WooPayments is duplicated for each payment method: 

Image

### To Reproduce

1. Enable Affirm in the WooPayments settings
2. On the front end, add < $50 worth of items to the cart. The Affirm minimum is $50.
3. Open the checkout page in the editor
4. See the incompatibility warning.

### Actual behavior

WooPayments payment methods are not always registered via `registerPaymentMethod()` which can lead to false incompatibility warnings.

### Expected behavior

WooPayments payment methods should all be registered via `registerPaymentMethod()` and no incompatibility notices should appear. 

### Additional context

1. A good thread on the topic - p1739531148782289/1739228658.873269-slack-CU6SYV31A
2. https://github.com/Automattic/woocommerce-payments/issues/9363#issuecomment-2339856374

### PR DESCRIPTION
**Pull request by danielmx-dev**
Fixes  #10380

#### Changes proposed in this Pull Request

We currently split the payment methods availability checks between the frontend and backend. Although there isn't too much issues with shortcode checkout, blocks checkout actually expects the availability checks to be performed mostly in the frontend via the `canMakePayment` function. 

For this particular issue, the limits per currency check we perform for BNPLs is causing problems, particularly for Affirm that has a minimum amount of 50 USD per transaction. When looking at blocks checkout in the edit page view we can see the following warning:

In order to prevent this particular issue for this and any other BNPL, we can skip the limits per currency check when looking at blocks checkout in admin pages. Something similar is already performed to skip currency checks.

A long term solution would still need to be defined so we can get more clarity on where should each availability check be performed.

#### Testing instructions

1. Enable Affirm in the WooPayments settings
2. On the front end, add < $50 worth of items to the cart. The Affirm minimum is $50.
3. Open the checkout page in the editor

Before:
- See the incompatibility warning.

Now: 
- The incompatibility warning is gone

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10503` or branch name `fix/skip-limits-per-currency-check-admin` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/skip-limits-per-currency-check-admin) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 6bcaa450e9f898c8123fe4472dd7db1198c42236
- Build time: 2025-03-10 14:11:17 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -3928,7 +3928,7 @@ public function get_payment_method_ids_enabled_at_checkout( $order_id = null, $f
 
 				$skip_currency_check       = ! $force_currency_check && is_admin();
```
Comment (brettshumaker) [inline includes/class-wc-payment-gateway-wcpay.php:3931]: I can't comment on it directly since it's not part of this PR, but I fumbled around a bit on the comments above. The `currency_is_checked` language is the opposite of `$skip_currency_check`. At first I thought our logic was inverted since if `$force_currency_check` and `is_admin()` are `false`, `$skip_currency_check` will also be `false`. I was seeing `1` in the comments above and was briefly confused about what should be happening here.

You don't have to do this, but I wouldn't be mad if `currency_is_checked` was switched to match the `$skip_currency_check` OR just changed to say "The currency WILL/WILL NOT be checked."

**Review by brettshumaker — APPROVED** [review]
I left a nitpicky note about comments that you did not write, but I verified that I saw the warning before applying the PR and after the PR it went away. I also verified that the checkout page still showed Affirm when the cart's contents met the eligibility requirements.
