### PR TITLE
Suppress Unexpected JSON Output

### LINKED ISSUE #10470: JSON strings appearing in phpunit test output
### Description
There's a particular test that causes a JSON string to be output while running PHPUnit. I think this has been happening for a while but I decided to investigate it today. I've tracked it down to these [two switch conditions](https://github.com/Automattic/woocommerce-payments/blob/1dfacfe3d88a7346a951bf35444b5f0a8eff6870/tests/unit/test-class-wc-payments-account.php#L314-L352) in `test_maybe_handle_onboarding_connect_from_known_from`.

Would it be fine to wrap the `$wcpay_account->maybe_handle_onboarding();` at the bottom of that test in `ob_start()` and `ob_end_clean()` to clean up the PHPUnit output?

Image

cc @dmallory42 @vladolaru as the two folks I see who contributed to that section.

### PR DESCRIPTION
**Pull request by BurakParsAydin**
Fixes #10470 

#### Changes proposed in this Pull Request
This PR addresses an issue in the `maybe_handle_onboarding` test where unexpected JSON output was being generated, causing inconsistencies in test results. The root cause was that certain conditions triggered unintended side effects, leading to unpredictable output.

To resolve this, the test logic has been updated to ensure that JSON output is only generated when explicitly needed. This prevents unnecessary noise and improves test reliability.

#### Why this change is needed?
Without this fix, the test results could be inconsistent, making debugging and CI reliability harder. Suppressing the unwanted JSON output ensures that the test behaves predictably across different environments.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

File: tests/unit/test-class-wc-payments-account.php [hunk 1]
```diff
@@ -428,7 +428,9 @@ function () {
 		);
 
 		// Act.
+		ob_start();
```
Comment (dmallory42) [inline tests/unit/test-class-wc-payments-account.php:432]: I suggest we add an explanatory comment here: 

```suggestion
        // Some code paths in the onboarding output JSON, so we use output buffering to suppress it while testing.
		ob_start();
```

**Review by dmallory42 — APPROVED** [review]
Thanks for working on this!

As noted in https://github.com/Automattic/woocommerce-payments/issues/10470, it turns out this JSON output is actual an expected behaviour from the code in some flows, so suppressing it for the purpose of testing seems a good fix. 

I tested by running `npm run test:php` on both `develop` and this branch and can confirm the JSON no longer outputs during the tests.

I left one comment and will go ahead and merge once you get a chance to look at it. 🙂

**Comment by BurakParsAydin** [comment]
@dmallory42 Thanks for reviewing the PR 😊 I appreciate your time and effort. FYI, I’ve applied your suggestion.
