### PR TITLE
Fix saved card payment error on blocks checkout

### LINKED ISSUE #7700: Card testing prevention prevents saved card payments on blocks checkout
### Describe the bug
When a store has card testing mitigations active, the store can't process payments initiated from blocks checkout with a saved card, resulting with `We're not able to process this payment. Please refresh the page and try again` error.

### To Reproduce

1. Go to WooPayments dashboard on MC, open the settings for your blog ID 
2. Set `card_testing_prevention_enabled` meta value to 1 
3. Connect to your local store to sandbox
4. On WCPay dev tools, connect your store to sandbox, refresh the account cache
5. Add a beanie and go to blocks checkout
6. Try to pay with a saved card.

### Actual behavior
An error should be visible.

### Screenshots
image

### Expected behavior
The payment should be processed.

### PR DESCRIPTION
**Pull request by tpaksu**
Fixes #7700

#### Changes proposed in this Pull Request

This issue fixes the saved payment method payments on blocks checkout while card testing prevention measures are active for the store, by adding a payment preparation step that injects the required keys to the payment meta data.

Also updates the calls to `onPaymentProcessing` event with `onPaymentSetup` event, because the prior one will get deprecated soon, and will be replaced with the new event. 

Context: p1699875691276639/1699871439.948359-slack-C02TS23QJ1X
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/block-client-apis/checkout/checkout-flow-and-events.md#onpaymentprocessing

#### Testing instructions
1. Go to WooPayments dashboard on MC, open the settings for your blog ID 
2. Set `card_testing_prevention_enabled` meta value to 1 
3. Connect to your local store to sandbox
4. On WCPay dev tools, connect your store to sandbox, refresh the account cache
5. Add a beanie and go to blocks checkout
6. Try to pay with a saved card.
7. See that it's not accepted.
8. Checkout this branch. 
9. Repeat steps 5-7, and see that payment is going through.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7701` or branch name `fix/7700-card-testing-prevention-prevents-saved-card-payments-on-blocks-checkout` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7700-card-testing-prevention-prevents-saved-card-payments-on-blocks-checkout) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: a576445cab501c0b10ed0890602bd96b98f532dd
- Build time: 2023-11-14 06:41:32 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/checkout/blocks/saved-token-handler.js [hunk 1]
```diff
@@ -1,15 +1,40 @@
 /**
  * Internal dependencies
  */
+import { useEffect } from 'react';
 import { usePaymentCompleteHandler } from './hooks';
+import { select } from '@wordpress/data';
+
+const { getPaymentMethodData } = select( 'wc/store/payment' );
```
Comment (opr) [inline client/checkout/blocks/saved-token-handler.js]: I'd recommend changing this to `useSelect` and actually, I just re-read the [Best practices for using useSelect() from @wordpress/data](https://jardasn.blog/2021/01/22/some-best-practices-for-using-useselect-from-wordpress-data/). It says to `Always call selector functions inside the callback`.

The new code would look like so:

```tsx
const paymentMethodData = useSelect( ( select ) => {
  const store = select('wc/store/payment' );
  return store.getPaymentMethodData();
} );
```

If you do this, then you'd probably want to make the following changes to the `useEffect`

```tsx
useEffect( () => {
        /* return here because when the useEffect reruns we want to unsubscribe the onPaymentSetup so we don't have multiple. */
		return onPaymentSetup( async () => {
			const fraudPreventionToken = document
				.querySelector( '#wcpay-fraud-prevention-token' )
				?.getAttribute( 'value' );

			return {
				type: 'success',
				meta: {
					paymentMethodData: {
						...paymentMethodData,
						'wcpay-fraud-prevention-token':
							fraudPreventionToken ?? '',
					},
				},
			};
		} );
	}, [ onPaymentSetup, paymentMethodData ] );
```

Comment (tpaksu) [reply client/checkout/blocks/saved-token-handler.js]: Thanks for the review @opr, I'll do the changes you proposed.

Comment (tpaksu) [reply client/checkout/blocks/saved-token-handler.js]: Addressed in [1915aa1](https://github.com/Automattic/woocommerce-payments/pull/7701/commits/1915aa1624029d53561a6bc028f00d7875517601).

File: client/checkout/blocks/saved-token-handler.js [hunk 2]
```diff
@@ -1,15 +1,41 @@
...
+	eventRegistration: { onPaymentSetup, onCheckoutSuccess },
 	emitResponse,
 } ) => {
+	const paymentMethodData = useSelect( ( select ) => {
+		const store = select( 'wc/store/payment' );
+		return store.getPaymentMethodData();
+	} );
+
+	useEffect( () => {
+		onPaymentSetup( async () => {
```
Comment (opr) [inline client/checkout/blocks/saved-token-handler.js]: You need to `return` the result of `onPaymentSetup()` because this returns an "unsubscribe" function. When this `useEffect` reruns, it'll execute the return value of the last run (if it's a function), therefore unsubscribing the old listener before resubscribing the new one.

Currently this will add a new listener to `onPaymentSetup` every time the payment method data changes.

Comment (tpaksu) [reply client/checkout/blocks/saved-token-handler.js]: TIL. Good thinking.

Comment (eduardoumpierre) [inline client/checkout/blocks/saved-token-handler.js]: Non-blocking: we can remove the `async` from this function.

**Review by eduardoumpierre — APPROVED** [review]
The code looks good and the test instructions worked as expected. 

I think we're good to merge it as soon as the other ongoing discussions are resolved.

Thanks for working on this one! 🚢

File: client/checkout/blocks/saved-token-handler.js (hunk 2 above)
Comment (tpaksu) [reply client/checkout/blocks/saved-token-handler.js]: @FangedParakeet @bborman22 @kalessil shall I go on and add `return` to the other instances too?

Comment (tpaksu) [reply client/checkout/blocks/saved-token-handler.js]: Ok, missed that they are already returning by the short function calls! Sorry for the extra pings :)

Comment (tpaksu) [reply client/checkout/blocks/saved-token-handler.js]: Addressed it in [6dead9c](https://github.com/Automattic/woocommerce-payments/pull/7701/commits/6dead9cb960647545e583cd8e472f8e8882bf02a), thanks for the review!

Comment (tpaksu) [reply client/checkout/blocks/saved-token-handler.js]: Addressed in [6dead9c](https://github.com/Automattic/woocommerce-payments/pull/7701/commits/6dead9cb960647545e583cd8e472f8e8882bf02a), thanks for the review!

Comment (opr) [reply client/checkout/blocks/saved-token-handler.js]: As an additional test to make sure it's working, I'd recommend:

- add a console log to the `onPaymentSetup` function
- manually set the payment method data multiple times (`wp.data.dispatch( 'wc/store/payment').__internalSetPaymentMethodData( { test: true} )`) - this can be done in the JS console, doesn't need to be in code
- Reset the payment method data to what you want it to be
- Try to pay and ensure only one console log is output.

Comment (tpaksu) [reply client/checkout/blocks/saved-token-handler.js]: Well, it doesn't work as it's in the `SavedTokenHandler`, and it's only running just before the payment starts processing. Actually, to test it, I need to set a declined card as a saved payment method, giving an error like "Insufficient funds", or something.

Comment (opr) [reply client/checkout/blocks/saved-token-handler.js]: Ah ok, well I just think it'd be useful to check it's unsubscribed when `paymentMethodData` changes to prevent a potential memory leak. Code looks fine as it is but it would be nice to double check!

File: changelog/fix-7700-card-testing-prevention-prevents-saved-card-payments-on-blocks-checkout [hunk 3]
```diff
@@ -0,0 +1,5 @@
+Significance: patch
+Type: fix
+Comment: Fix card testing prevention enabling breaking saved card payments on blocks checkout
```
Comment (htdat) [inline changelog/fix-7700-card-testing-prevention-prevents-saved-card-payments-on-blocks-checkout]: I think this PR would deserve a proper entry into changelog.txt, rather than a comment to skip adding it to the changelog during the release process like this.

**Review by htdat — APPROVED** [review]
Thanks @tpaksu for quickly working on this issue. Pre-approve the PR. 

✅  I could confirm that manual tests work well. 
❓ I have [a comment above](https://github.com/Automattic/woocommerce-payments/pull/7701#discussion_r1391930034) regarding the changelog, plus that this PR title would mention also `card testing prevention` feature, such as `Fix card testing prevention breaking the block checkout with saved payment methods`.

File: changelog/fix-7700-card-testing-prevention-prevents-saved-card-payments-on-blocks-checkout (hunk 3 above)
Comment (tpaksu) [reply changelog/fix-7700-card-testing-prevention-prevents-saved-card-payments-on-blocks-checkout]: I think this as a a delicate situation, talking about fraud and mitigations, so I skipped the changelog. If you think it deserves publicity, I can switch it to a visible one.

Comment (htdat) [reply changelog/fix-7700-card-testing-prevention-prevents-saved-card-payments-on-blocks-checkout]: IMO, there is no issue with it since it's a public repo anyway.

Comment (tpaksu) [reply changelog/fix-7700-card-testing-prevention-prevents-saved-card-payments-on-blocks-checkout]: Updated the changelog in https://github.com/Automattic/woocommerce-payments/pull/7701/commits/3ce6713e425532b95e9a69e0eb006ae041e69ce8.
