### PR TITLE
Avoid updating billing details for legacy card objects

### LINKED ISSUE #8405: Payments using the legacy Card object can fail if there are changes to billing details
### Describe the bug

If a customer has a subscription where the tokenized payment method uses the legacy Card object, these payments can fail with the following error:

```
This PaymentMethod was converted from a legacy Card object. You may not update the email or phone number of these PaymentMethods.
```

Based on the error message, this is a result of changes to the customer's email or phone number. However, this only occurs with 7.3.0 active — reverting to 7.2.0 resolves the issue.

#### Note: I have not reproduced this yet.

1. Purchase a subscription product with a `card_` payment method.
2. Force a renewal by running the `woocommerce_scheduled_subscription_payment` scheduled action.
3. If that is successful, try adjusting either the email address or phone number associated with the customer and repeating step 2.

### Actual behavior

Payments fail when using a tokenized payment method, but only with 7.3.0 active. I suspect it is related to #8226 but I'm not positive.

Additionally, it's TBD if this only affects subscription renewals.

### Expected behavior

Renewals do not fail if they use the `card_` object while running 7.3.0

### Additional context

p1710532466431139-slack-C03EE4CPPK5
p1710531291134079/1704393766.219159-slack-C03EE4CPPK5

### PR DESCRIPTION
**Pull request by timur27**
Fixes https://github.com/Automattic/woocommerce-payments/issues/8405

#### Changes proposed in this Pull Request
Legacy card object [[ref](https://docs.stripe.com/api/cards/object)] has different schema than the payment method object [[ref](https://docs.stripe.com/api/payment_methods/object)]. This PR avoids updating billing details for legacy card objects to not face the error coming from Stripe API due to object schema incompatibility.

#### Testing instructions

``` 
💡 To create the legacy card object for your account, send the following request while inserting your customer ID, account ID and test API key

curl https://api.stripe.com/v1/customers/${customer_id}/sources \
-u ${test_api_key}: \
-H "Stripe-Account:${acct_id}" \
```
* Ensure that you have the saved payment method on your store which is legacy card from the request above
* On this branch, purchase a subscription with this saved payment method, confirm the successful purchase 
* Revert the fix commit, navigate to subscription details, process renewal, confirm that the error message is the same as in https://github.com/Automattic/woocommerce-payments/issues/8405
* Remove the revert so that the fix is in place
* In the failed order details options, choose `Retry renewal payment`
* Navigate to subscription details, process renewal and confirm the renewal was successful this time

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8664` or branch name `fix/no-billing-details-update-for-legacy-card` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/no-billing-details-update-for-legacy-card) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: f3c8b0e99cc19af8652595ed75a630a6d738a23a
- Build time: 2024-04-18 09:58:06 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -1514,7 +1514,10 @@ public function process_payment_for_order( $cart, $payment_information, $schedul
 				if ( $payment_information->is_using_saved_payment_method() ) {
 					$billing_details = WC_Payments_Utils::get_billing_details_from_order( $order );
 
-					if ( ! empty( $billing_details ) ) {
+					$is_legacy_card_object = strpos( $payment_information->get_payment_method() ?? '', 'card_' ) === 0;
+
+					// Don't update billing details for legacy card objects because they are not supported.
```
Comment (frosso) [inline includes/class-wc-payment-gateway-wcpay.php]:
```suggestion
					// Not updating billing details for legacy card objects because they have a different structure and are no longer supported.
```

I was thinking of adding a note on the different structure - but then I had to limit the length of the comment 😅 let me know your thoughts if it's worth adding.

**Review by frosso — APPROVED** [review]
Nice job with the tests, tested locally. I see some tests that might need fixing, but otherwise looks good :shipit:

File: includes/class-wc-payment-gateway-wcpay.php (hunk 1 above)
Comment (timur27) [reply includes/class-wc-payment-gateway-wcpay.php]: Changed the wording, always better to be as explicit as possible 👍 Thanks!
