### PR TITLE
Avoid PMME init for unavailable BNPL use-cases

### LINKED ISSUE #10179: Country eligibility check for BNPL messaging element on product/cart pages
### Describe the bug

The BNPL messaging element is rendered in a few pages:
- Product pages
- Block-based cart & checkout
- Shortcode-based cart & checkout

As it currently stands, the implementation for checkout pages is different than the ones on cart & product pages.
On the checkout pages, the eligibility check is done on the selected customer's billing country (or the store's country), and whether that country is allowed for the BNPL payment methods.

On the product & cart pages, this check doesn't seem to be implemented.

So, if the customer's billing country is not supported by any of the enabled BNPL methods (e.g.: billing country `CN`), the BNPL messaging element will still attempt to render, and then fail.
Sometimes, this failure is just present in the browser's console.
Other times, this failure can be visible in the store's front-end (if you're admin and have error logging enabled).

We should implement the same checks in the product & cart implementations for BNPL messaging eligibility.

### To Reproduce

1. Add a product to the cart
2. Go to checkout, select `CN` as the billing country
3. Go back to the product page or the cart page

### Actual behavior

The BNPL messaging attempts to render, but fails.

### Screenshots

Image

### Expected behavior

The BNPL messaging element shouldn't render if the country is not supported.

### Additional context

p1736962049965999-slack-CU6SYV31A

### PR DESCRIPTION
**Pull request by timur27**
Fixes https://github.com/Automattic/woocommerce-payments/issues/10179

#### Changes proposed in this Pull Request
Product page and cart pages tried to initialize PMME with Stripe for ineligible counties also. This PR re-uses the `isBnplAvailable` flag (while slightly expanding its checks) before attempting to mount the messaging elements.

#### Testing instructions

----
Confirm that the PMME container is correctly hidden when a country is not supported. This was done before, and this test is to confirm that there is no regression in this area.

* Choose the United States as the billing country on checkout
* Navigate to the product page and confirm the loaded PMME container is visible
* Change the billing country to a BNPL-unsupported one (e.g., `CH`)
* Navigate to the product page and confirm that there's no empty container (like the left screenshot below) and instead it's being wholly hidden (like the right screenshot below)

| This would be unexpected | This is expected |
|--------|-------|
| image  | image  |

----
Confirm that no console errors occur for classic cart and product page
* Check out `develop`
* Choose the United States as the billing country on checkout
* Navigate to the product page and confirm no user nor console errors
* Change the billing country to a BNPL-unsupported one (e.g., `CH`)
* Confirm there are no user errors visible on the page **but** console errors visible on both pages 
* Check out `fix/redundant-pmme-init` 
* Keep the unsupported checkout billing country
* Refresh product page and classic cart page and confirm the console error is gone
----

Confirm that no intermittent error on cart block is not showing up when refreshing the page. More on that in https://github.com/Automattic/woocommerce-payments/issues/10179#issuecomment-2674245284

----

Confirm that no console errors occur for cart block
* Check out `develop`
* Choose the United States as the billing country on checkout
* Navigate to the product page and confirm no user nor console errors
* Change the billing country to a BNPL-unsupported one (e.g., `CH`)
* Confirm there is user errors visible on the page
* Check out `fix/redundant-pmme-init` 
* Keep the unsupported checkout billing country
* Refresh the cart block page and confirm the error is gone

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10424` or branch name `fix/redundant-pmme-init` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/redundant-pmme-init) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: ebc1ff3f84ad17a38889d4642ff77926db77fb40
- Build time: 2025-02-21 20:25:40 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/product-details/bnpl-site-messaging/index.js [hunk 1]
```diff
@@ -53,7 +53,6 @@ export const initializeBnplSiteMessaging = async () => {
 		paymentMethods,
 		currencyCode,
 		isCart,
-		isCartBlock,
```
Comment (timur27) [inline client/product-details/bnpl-site-messaging/index.js:56]: Removal of `isCartBlock`, more details in p1740133472312029-slack-CU6SYV31A

File: includes/class-wc-payments-utils.php [hunk 2]
```diff
@@ -856,13 +856,18 @@ public static function get_bnpl_limits_per_currency( $payment_method ) {
 	 * @param float  $price Product price.
 	 * @return bool True if any BNPL method is available, false otherwise.
 	 */
-	public static function is_any_bnpl_method_available( array $enabled_methods, string $country_code, string $currency_code, float $price ): bool {
+	public static function is_any_bnpl_method_available( array $enabled_methods, string $country_code, string $currency_code, ?float $price = null ): bool {
```
Comment (timur27) [inline includes/class-wc-payments-utils.php]: We could split the `non-price` and `with-price` use-cases into several blocks and improve separation of concerns, but I want to ensure backwards compatibility with the AJAX call that uses this function also.

File: includes/class-wc-payments-payment-method-messaging-element.php [hunk 3]
```diff
@@ -146,6 +146,8 @@ public function init() {
 
 		if ( $product ) {
 			$script_data['isBnplAvailable'] = WC_Payments_Utils::is_any_bnpl_method_available( array_values( $bnpl_payment_methods ), $country, $currency_code, $product_price );
+		} else {
+			$script_data['isBnplAvailable'] = WC_Payments_Utils::is_any_bnpl_method_available( array_values( $bnpl_payment_methods ), $country, $currency_code );
 		}
```
Comment (danielmx-dev) [inline includes/class-wc-payments-payment-method-messaging-element.php]: I still don't understand why we have two scenarios for `is_any_bnpl_method_available` here. I assume that we don't send an amount when we are in the cart page since the totals could change, but it's the same case for variable products and quantities in the product page.

**Review by danielmx-dev — CHANGES_REQUESTED** [review]
I found an issue with variable products that it's not present in develop.

- Use a US Account in USD
- Enable only Affirm
- Add a product with variations (if you are using the test products, you can edit the Hoodie product)
- One of the variations should be below 50 USD and the other above 50 USD
- Save the changes
- Open the Product page
- Select one of the variations
- The following error will be displayed in the console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'update')
    at updateBnplPaymentMessage (index.js:84:29)
```

The PMME won't react dynamically to the price changes depending on the selected variation. This issue is not present in develop.

**Comment by danielmx-dev** [comment]
> I found an issue with variable products that it's not present in develop.
> 
> * Use a US Account in USD
> * Enable only Affirm
> * Add a product with variations (if you are using the test products, you can edit the Hoodie product)
> * One of the variations should be below 50 USD and the other above 50 USD
> * Save the changes
> * Open the Product page
> * Select one of the variations
> * The following error will be displayed in the console:
> 
> ```
> Uncaught TypeError: Cannot read properties of undefined (reading 'update')
>     at updateBnplPaymentMessage (index.js:84:29)
> ```
> 
> The PMME won't react dynamically to the price changes depending on the selected variation. This issue is not present in develop.

Note: This is also an issue when updating the quantity in the product page.

**Comment by timur27** [comment]
@danielmx-dev Thanks for the thorough review and catching the variations use-case! I learned a bit about all this and updated the PR, would appreciate your review. My take is following: 

As we are updating the PMME for variations or once the total changes, I should either start checking & potentially initializing PMME on the update, or I should stop initialization for country-specific restrictions only and let the limit-specific restrictions not block the initialization. 

I chose the second option and this is for the following reason: if I go with "start checking & potentially initializing PMME on the update", I need to start providing new totals that are coming from AJAX on the update. This will end up us handling two totals in the initialization implementation (one from the back-end, another one from the AJAX response) and the code will become more tricky to understand. Besides that, in this case I would keep [the branching you wondered about](https://github.com/Automattic/woocommerce-payments/pull/10424#discussion_r1965588421) and as I can see why it might be confusing, I would use the opportunity to get away from it.

File: includes/class-wc-payments-utils.php [hunk 4]
```diff
@@ -875,6 +875,25 @@ public static function is_any_bnpl_method_available( array $enabled_methods, str
...
 
+	/**
+	 * Check if any BNPL method is available for a given country.
+	 *
+	 * @param array  $enabled_methods Array of enabled BNPL methods.
+	 * @param string $country_code Country code.
+	 * @param string $currency_code Currency code.
+	 * @return bool True if any BNPL method is available, false otherwise.
+	 */
+	public static function is_any_bnpl_supporting_country( array $enabled_methods, string $country_code, string $currency_code ): bool {
```
Comment (timur27) [inline includes/class-wc-payments-utils.php:886]: It might seem at first glance that this function should be reusing components similar to `is_any_bnpl_method_available`, but after trying a bit, it doesn't seem to simplify things. So I kept it separate.

File: client/product-details/index.js
Comment (danielmx-dev) [inline client/product-details/index.js:1]: I see that this file is still adding event callbacks (e.g. for quantity change) even if the current country is not supported. Should we exit early if `shouldInitializePMME` is false ? Or is there a scenario where these handlers are needed ? I don't think the country can change in these pages (product/cart)

**Review by danielmx-dev — APPROVED** [review]
This works fine (mostly). I tested the following scenarios for both supported and unsupported country (I used an early exit in `client/product-details/index.js` when `shouldInitializePMME` is false):

- Product below required amount
- Product above required amount
- Product below required amount > Update quantity to bring total over required amount
- Variable product with base price below required amount > Selecting a variation with price over required amount
- Cart below required amount
- Cart above required amount
- Cart below required amount > Update quantity to bring total over required amount: This last scenario doesn't work using the cart block, but it's also failing in develop, so it's fine if it gets fixed in a separate issue, since your changes are not related.

**Review by danielmx-dev — APPROVED** [review]
👍
