### PR TITLE
Hide Fraud info banner until first transaction happens

### LINKED ISSUE #8279: Hide Fraud Tools Banner until account process a first order with WooPayments
### Describe the bug

As mentioned on Slack (p1709049534474959/1709049161.731439-slack-C03KTTK2YMA) - we should hide the `Enhanced Fraud Protection` banner while an account is in progressive/store setup. We should only show this banner once the account setup is fully complete.
 

### To Reproduce

1. Onboard a new progressive account.
2. You will see the Fraud Protection banner on the Overview page.

### Screenshots

Screenshot 2024-02-27 at 16 41 29

### Expected behavior

* For a progressive account, the FRT banner should only show after PO setup is complete.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by daquinons**
Fixes #8279 

#### Changes proposed in this Pull Request

**Hide Fraud info banner until first transaction happens**

To avoid overwhelming new users, we'll be displaying the informational banner about the fraud tools only after they've processed volume in their store using WooPayments.

#### Testing instructions

* Go [to your client phpMyAdmin](http://localhost:8083/index.php?route=/sql&pos=0&db=wordpress&table=wp_options) and make sure you don't have `wcpay_frt_discover_banner_settings` in the table wp_options. If you have it, delete it.

**No transactions**
* Go to [this line](https://github.com/Automattic/woocommerce-payments/blob/4fa44519a2e5da4b723c01e3ba92f513790a4db2/includes/admin/class-wc-payments-admin.php#L857) and modify it 
`'lifetimeTPV'                   => 0,`
* Go to Payments
* The Fraud tools banner is not appearing

**With transactions**
* Remove the modifications that you added in the last step (assuming your test account already has volume in it, if not, feel free to modify it with any number that is not `0`)
* Go to Payments
* The Fraud tools banner is appearing
 
Screenshot 2024-04-15 at 12 11 37

* Click on Dismiss
* The Fraud tools banner is not appearing
* Refresh
* The Fraud tools banner is not appearing

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8643` or branch name `8279/fix-fraud-banner-display-transaction` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=8279/fix-fraud-banner-display-transaction) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: d43f1f575f4f9f98337c51ba29e151cf8523dadb
- Build time: 2024-04-16 12:26:40 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/components/fraud-risk-tools-banner/index.tsx [hunk 1]
```diff
@@ -50,11 +50,7 @@ const FRTDiscoverabilityBanner: React.FC = () => {
 		setDontShowAgain();
 	};
 
-	if ( ! showBanner ) {
-		return null;
-	}
-
-	return (
+	return showBanner ? (
```
Comment (ismaeldcom) [inline client/components/fraud-risk-tools-banner/index.tsx]: _Nitpick_: For cases like this, we tend to use the early return syntax to avoid nesting the JSX code.

Anyway, just a matter of taste 🙂

**Review by ismaeldcom — APPROVED** [review]
Thanks for taking care of this, I like how you relied on the existing `lifetimeTPV` property to solve it in a simple way.

File: client/components/fraud-risk-tools-banner/index.tsx (hunk 1 above)
Comment (daquinons) [reply client/components/fraud-risk-tools-banner/index.tsx]: Thank you for letting me know! I've reverted it in https://github.com/Automattic/woocommerce-payments/pull/8643/commits/d43f1f575f4f9f98337c51ba29e151cf8523dadb
