### PR TITLE
Show deposit schedule message if account's deposits are unrestricted

### LINKED ISSUE #7874: Deposits - Overview: When available balance is at or below zero, no schedule is shown.
### Describe the bug

When a merchants available balance is at or below $0, no schedule is shown. This leads merchants to incorrectly assume that deposits are blocked or paused.

The deposit schedule should always show when deposits are not blocked or restricted.

image

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #7874

#### Changes proposed in this Pull Request

1. Renders the deposit schedule message on the Payments → Overview screen unless the account's deposits are blocked or restricted.

This helps communicate to merchants that they have an expected upcoming deposit, even if their available balance <= 0.

2. The "next deposit is scheduled" part of the message will only be rendered if there is available balance. Without available balance, this part of the message will not render. (in the future, this will only render if above the minimum automatic deposit threshold #6774)

image

#### Testing instructions

* Check that the message is rendered for accounts without deposit restrictions (use MC tools to add/remove restrictions to account)
	* With an available balance of 0
	* With a negative available balance
* Check that the message is not rendered
	* Deposits blocked
	* Deposits restricted

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7875` or branch name `fix/7874-show-deposit-schedule-when-zero-available-balance` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7874-show-deposit-schedule-when-zero-available-balance) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 8550239f77618cf55be33f5b34eadcc32e9739ee
- Build time: 2023-12-13 03:48:39 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by csmcneill** [comment]
I have a couple of live accounts. I enabled this PR via Jetpack Beta and tested it in a couple of scenarios; it LGTM so far. Sharing these here in case they help.

Live mode with a pending balance, no available balance, and in the new account waiting period:
live no available

Test mode with an available balance:
live test mode with available

Live mode with no transactions:
live no balance

Activating this with the WCPay dev tools _did_ produce a fatal error on one site, but it was because I was running an outdated build of the dev tools — doesn't seem to be an issue with the PR.

File: client/components/deposits-overview/index.tsx [hunk 1]
```diff
@@ -57,7 +57,7 @@ const DepositsOverview: React.FC = () => {
 		! isLoading &&
 		deposits?.length > 0 &&
 		!! account &&
-		! account?.deposits_blocked;
+		isDepositsUnrestricted;
```
Comment (brucealdridge) [inline client/components/deposits-overview/index.tsx]: I think we still want to show recent deposits if deposits are restricted. 
Actually recent deposits should show even if they're blocked IMO

Comment (Jinksi) [reply client/components/deposits-overview/index.tsx]: Good point, I'll test and remove this requirement.

Comment (Jinksi) [reply client/components/deposits-overview/index.tsx]: Updated in 867116c.

**Deposits hard blocked** – Deposits card not rendered anyway

image

**Deposits soft blocked** – Deposits card not rendered anyway

image 2


**Deposits schedule restricted** – recent deposit list shown

image 3

File: client/globals.d.ts [hunk 2]
```diff
@@ -30,7 +30,11 @@ declare global {
 			country?: string;
 			paymentsEnabled?: boolean;
 			deposits?: {
-				status: string;
+				status;
```
Comment (Jinksi) [inline client/globals.d.ts]:
```suggestion
				status: string;
```

**Comment by Jinksi** [comment]
My concern with this one is that the estimated date for daily schedule can be wildly incorrect.

If the account has zero available or pending, there is no way this account will receive a deposit tomorrow.

image

File: client/components/deposits-overview/index.tsx [hunk 3]
```diff
@@ -98,10 +95,11 @@ const DepositsOverview: React.FC = () => {
 			</CardHeader>
 
 			{ /* Deposit schedule message */ }
-			{ isNextDepositExpected && !! account && (
+			{ isDepositsUnrestricted && !! account && (
 				<CardBody className="wcpay-deposits-overview__schedule__container">
 					<DepositSchedule
 						depositsSchedule={ account.deposits_schedule }
+						showNextDepositDate={ availableFunds !== 0 }
```
Comment (shendy-a8c) [inline client/components/deposits-overview/index.tsx]: Is this intentional to show next deposit date string if available balance is not 0? That means if it's negative too.

For example, every time I create an instant deposit, not sure why the available balance becomes negative even though the total balance (available + pending) is correct.

In this case (when available balance is negative), I can see the next deposit date string.

Screenshot 2023-12-12 at 23 40 10

Also, per the issue https://github.com/Automattic/woocommerce-payments/issues/7874 the next deposit date string shouldn't show if available balance is at or below zero.

Comment (shendy-a8c) [reply client/components/deposits-overview/index.tsx]: Or you meant

```suggestion
						showNextDepositDate={ availableFunds > 0 }
```

File: client/components/deposits-overview/index.tsx [hunk 4]
```diff
@@ -35,6 +35,9 @@ const DepositsOverview: React.FC = () => {
 		overview,
 		isLoading: isLoadingOverview,
 	} = useSelectedCurrencyOverview();
+	const isDepositsUnrestricted =
+		wcpaySettings.accountStatus.deposits?.restrictions ===
```
Comment (shendy-a8c) [inline client/components/deposits-overview/index.tsx:39]: Why do you check for `wcpaySettings.accountStatus.deposits.restrictions` instead of `account.deposits_blocked`?

If I understand it correctly, `account.deposits_blocked` takes account new account waiting period and `wcpaySettings.accountStatus.deposits.restrictions` does not.

Just curious.

Current code would work because [the deposits card won't show if available balance is 0 and there is no deposits](https://github.com/Automattic/woocommerce-payments/blob/251fb285089a073f6d7f7279f34b56c6352a6ae9/client/components/deposits-overview/index.tsx#L86-L89) anyway. When in waiting period, merchant won't have deposits.

**Review by shendy-a8c — APPROVED** [review]
Overall looks good and tested well per testing instructions.

I have a question when available balance is negative, why the next date string shows up.

**Review by shendy-a8c — CHANGES_REQUESTED** [review]
Overall looks good and tested well per testing instructions.

I have a question when available balance is negative, why the next date string shows up.

File: client/components/deposits-overview/index.tsx (hunk 3 above)
Comment (Jinksi) [reply client/components/deposits-overview/index.tsx]: I think you're right, we should go with showing this if there is a positive available balance.

Comment (Jinksi) [reply client/components/deposits-overview/index.tsx]: Resolved in b6b2523f798de979fdc446d86d2eda648a23d59d

File: client/components/deposits-overview/index.tsx (hunk 4 above)
Comment (Jinksi) [reply client/components/deposits-overview/index.tsx:39]: AFAICT `account.deposits_blocked` [only checks for deposits blocked](https://github.com/Automattic/woocommerce-payments-server/blob/4f187b11eb9ca3237e4806a2f7de406a6f0d53a7/server/wp-content/rest-api-plugins/endpoints/wcpay/class-deposits-controller.php#L238), and doesn't take into consideration schedule restrictions.

In this case, we want to check for both schedule restrictions and blocked deposits, which `wcpaySettings.accountStatus.deposits.restrictions === 'deposits_unrestricted'` covers.

I could include a check for `wcpaySettings.accountStatus.deposits.completed_waiting_period === true`, that might be more explicit. What do you think?

**Comment by Jinksi** [comment]
Rebased to `release/6.9.2` and removed all commits carried over from `develop`.

File: client/components/deposits-overview/index.tsx (hunk 4 above)
Comment (shendy-a8c) [reply client/components/deposits-overview/index.tsx:39]: Thank you for explaining. I don't think it's necessary to check waiting period.

**Review by shendy-a8c — APPROVED** [review]
Looks good. Retested to make sure and everything looks good.
Also, I made sure the rebase went OK by comparing with the PR branch before rebased, https://github.com/Automattic/woocommerce-payments/pull/7896/files. I still had it on my local minus your latest commit.
