### PR TITLE
Prevent renewal subscription orders from being created if subscription was made in the mode that doesn't match current WooPayments mode

### LINKED ISSUE #3687: Renewal attempt for a canceled Subscription in Test mode after switching to Live mode
### Describe the bug

 It seems what happens is when there is a Sub created under WC Pay's Test mode and canceled after it is flipped to Live, the `wcpay_track_new_order` action continues to fire off, even if the action fails.

### To Reproduce

1. Purchase a Subscription in test mode
2. Notice the Scheduled Actions:
    https://d.pr/i/EQ77uL+
3. Cancel the Subscription while on test mode. 
4. Notice that the Subscription is set to `Pending Cancellation`, but `wcpay_track_new_order` is still present
5. Switch to Live mode
4. When it is time for renewal, the default subscription end scheduled action runs, along with `wcpay_track_new_order` which fails:

    https://d.pr/i/pkjQvA+
6. This generates new orders which should not be generated, and prevents canceling the Subscription itself since it generates this error:

    https://d.pr/i/PWDMxb+
7. Also note that the renewal orders keep coming in, even though they fail with this error: `action failed via WP Cron: Error: Unable to fetch payment method details from the provided payment_method_id.`

    https://d.pr/i/u4AV7W+

### Expected behavior

Either ensure no renewal orders are created post-cancellation or make it clear to the customer in the docs about what will happen to the subscriptions that are not completely canceled / that are in `pending cancellation` state.

### Desktop (please complete the following information):

Any

### Smartphone (please complete the following information):

Any

### Additional context

**Slack discussion** : p1642095259178500-slack-C7U3Y3VMY

**Customer Reports** : 4669003-zen

### PR DESCRIPTION
**Pull request by dmvrtx**
Fixes #3687

#### Changes proposed in this Pull Request

Add a hook to the `wcs_renewal_order_items` filter to stop the renewal order from being created if WooPayments is now in the mode that doesn't match the original subscription mode.  E.g. if original subscription was paid in the test mode and WooPayments is now in the live mode.

[`wcs_renewal_order_items`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/f7dbe327de15e47399ffec154cabc459ed7ffcdb/includes/wcs-order-functions.php#L238) is called within a transaction when renewal order is being constructed. Therefore, an error here will result in the order not being created and an error message reported.

#### Testing instructions

* Install WooCommerce Subscriptions and create a subscription product
* Create a subscription order in the test mode
* As a merchant, open the subscription order and choose "Create a pending renewal order". This command should complete succesfully.
* Edit the value for the `_wcpay_mode` meta for the created order in the database table `wp_wc_orders_meta`. E.g. to "foo".
* As a merchant, open the subscription order and choose "Create a pending renewal order". You will see a failure message: `Creation of the pending renewal order failed. The subscription was made in the mode "foo" that does not match the current WooPayments mode "test".`

image

 - Go to `WooCommerce -> Status -> Scheduled actions`
 - Find a pending action `woocommerce_scheduled_subscription_payment` with the subscription order.
 - Run the action.
 - A failure note will appear:

image

 - Failed actions will contain a record with an error:
 
image
 
 - Check that there is no new order has been created for the renewal.

>[!NOTE]
> When Shopper tries to renew a subscription themselves it appears to go into the different flow and creates a new order in the correct WooPayments mode and is unaffected by this change.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : [Link](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions-for-WC-Payments-9.2.0#subscription-renewal-should-fail-in-live-mode-if-subscription-was-placed-when-woopayments-was-in-the-test-and-vice-versa)
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10606` or branch name `add/3687-prevent-renewal-order-if-subscription-mode-does-not-match-current-mode` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/3687-prevent-renewal-order-if-subscription-mode-does-not-match-current-mode) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 2c7bc1fe7d30566b16b4e594f907f31f4e7ccbd0
- Build time: 2025-03-25 17:57:29 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/subscriptions/class-wc-payments-subscription-service.php [hunk 1]
```diff
@@ -874,6 +878,32 @@ public function maybe_cancel_subscription( $subscription, $new_payment_method )
...
+	 * @return array
+	 */
+	public function check_wcpay_mode_for_subscription( array $items, WC_Order $order, WC_Subscription $subscription ): array {
+		$parent_order = $subscription->get_parent();
+		if ( false !== $parent_order ) {
+			$subscription_mode = $parent_order->get_meta( WC_Payments_Order_Service::WCPAY_MODE_META_KEY );
+			$current_mode      = WC_Payments::mode()->is_test() ? Order_Mode::TEST : Order_Mode::PRODUCTION;
+
+			if ( is_string( $subscription_mode ) && '' !== $subscription_mode && $subscription_mode !== $current_mode ) {
+				throw new Subscription_Mode_Mismatch_Exception( 'The subscription was made in the mode "' . $subscription_mode . '" that does not match the current WooPayments mode "' . $current_mode . '".' );
```
Comment (RadoslavGeorgiev) [inline includes/subscriptions/class-wc-payments-subscription-service.php]: Subscriptions displays links to the latest `failed-scheduled-actions` logs, meaning that this message will be easily reachable by shop managers, not just developers. Therefore, I would strongly prefer it localized.

To avoid weird placeholders for translations, I'm fine with having two strings: One for live subscriptions in test mode, and one for test subscriptions in live mode.

**Review by RadoslavGeorgiev — APPROVED** [review]
I followed the testing instructions, and arrived at the correct message:

image

I've got one comment, feel free to address it and ship without further review. :shipit:

File: includes/subscriptions/class-wc-payments-subscription-service.php (hunk 1 above)
Comment (dmvrtx) [reply includes/subscriptions/class-wc-payments-subscription-service.php]: Thanks for pointing this out! Updated in a30697f9a

**Comment by RadoslavGeorgiev** [comment]
:shipit:
