### PR TITLE
Fix account status chip for progressively onboarded accounts

### LINKED ISSUE #6375: Adjust payments overview after recent Stripe changes
### Description
The overview screen for the PO account was looking like this before recent Stripe changes p1684873002176489-slack-C051WFFE961
image

But now it looks like this for progressive accounts (the same as for pending full KYC accounts)
image

We need to combine two things: use _Pending_ status chip instead of _Restricted_.

### PR DESCRIPTION
**Pull request by oaratovskyi**
Fixes #6375 

#### Changes proposed in this Pull Request

Fix account chip status for PO accounts: `Restricted` -> `Pending`.

#### Testing instructions

* Checkout the branch `fix/6375-account-status-for-po`
* Delete the old account if it exists (using server DB) + clear the cache. Force onboarding also may work.
* Ensure `Progressive Onboarding` feature flag is enabled.
* Onboard the new PO account and check its status. It should be _Pending_.

image

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _ 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6409` or branch name `fix/6375-account-status-for-po` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6375-account-status-for-po) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 26d786ce5ec81e958dea61cc34f63d1e51989af5
- Build time: 2023-06-01 10:08:58 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/account-status-settings/index.js [hunk 1]
```diff
@@ -123,7 +123,13 @@ const AccountStatus = ( props ) => {
 	return (
 		<div>
 			<div>
-				<StatusChip accountStatus={ accountStatus.status } />
+				<StatusChip
+					accountStatus={ accountStatus.status }
+					poEnabled={ accountStatus.progressiveOnboarding.isEnabled }
```
Comment (oaratovskyi) [inline client/account-status-settings/index.js:128]: not sure where it's used by the client, @ismaeldcom maybe you know? I fixed the code accordingly, don't know how to test 🙈

Comment (ismaeldcom) [reply client/account-status-settings/index.js:128]: As we mentioned on Slack, it seems to be unreferenced code, so we can just remove it in a follow-up issue.

**Review by ismaeldcom — APPROVED** [review]
Thanks for taking care of it! Tested on both local and JN, and it works as expected. Let's 🚢  it!

File: client/account-status-settings/index.js (hunk 1 above)
Comment (oaratovskyi) [reply client/account-status-settings/index.js:128]: Created follow up issue https://github.com/Automattic/woocommerce-payments/issues/6415
