### PR TITLE
fixed error when running e2e tests inside a folder with white spaces in the name

### LINKED ISSUE #3007: Can't run E2E tests on projects inside folder with white space in the name
### Describe the bug
When trying to run E2E tests using ```npm run tests:e2e``` I got errors like "git clone: Too many arguments"
Debugging it I discovered that the problem would happen when the project was inside a folder with white space in the name

### To Reproduce
- git clone this repository inside a folder with white space in the name
- try to run e2e tests
- an error should pop up saying something like "git clone: Too many arguments"

### Actual behavior
- "git clone: Too many arguments" Error happens when trying to run npm tests:e2e inside a folder with white spaces in the name

### Expected behavior
- no error should pop up when running tests inside a folder with white space in the name

### Desktop (please complete the following information):

* OS: macOS

### PR DESCRIPTION
**Pull request by leonardola**
This PR fixes an error message that would popup when running e2e tests inside a folder containing white spaces in the name

Fixes #3007  

#### Changes proposed in this Pull Request

added " when using the path to the project folder

#### Testing instructions
- git clone this repository inside a folder with white space in the name
- try to run e2e tests with ```npm run tests:e2e```
- an error should pop up saying something like "git clone: Too many arguments"

### CODE REVIEW

File: tests/e2e/env/setup.sh [hunk 1]
```diff
@@ -20,12 +20,12 @@ if [[ $FORCE_E2E_DEPS_SETUP || ! -d $SERVER_PATH ]]; then
 	fi
 
 	rm -rf $SERVER_PATH
```
Comment (ricardo) [inline tests/e2e/env/setup.sh:22]: @leonardola Should we add quotes here, [here](https://github.com/Automattic/woocommerce-payments/blob/3e499b0499b2e14306a16c7654df61adf4419c6c/tests/e2e/env/setup.sh#L14) and for the `$DEV_TOOLS_PATH` as well?

**Review by ricardo — APPROVED** [review]
LGTM 🚢
