### PR TITLE
Use correct currency in Payment Activity Card

### LINKED ISSUE #8700: Payment activity card amounts can be formatted with the incorrect currency symbol
### Describe the bug

In some cases the Payment Activity Card amounts can show with the wrong currency symbol (e.g. `$` rather than `CHF`) when rendering the TPV, etc amounts. 

Image

> [!TIP]
> Server issue https://github.com/Automattic/woocommerce-payments-server/issues/5207 will make the `reporting/payment_activity` endpoint return `currency` alongside the amounts – which can be used to resolve this.

#### Testing instructions
- Use a store that does not use `USD` (or any other dollar) as a default currency, e.g. onboard a German WCPay account with `NOK` or `CHF` as the default currency.
- Enable the feature flag: run `wp option update _wcpay_feature_payment_overview_widget 1` in CLI (`npm run cli` if docker)
- Go to `Payments -> Overview`
- Notice that the Payment Activity renders amounts incorrectly with `$` formatting

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #8700

#### Changes proposed in this Pull Request

This PR ensures the Payment Activity Card shows amounts in the correct currency by using the `currency` property returned by the `reporting/payment_activity` endpoint response.

I've also updated the interface for the `reporting/payment_activity` API response to reflect the server response ([response code ref](https://github.com/Automattic/woocommerce-payments-server/blob/f61c8880fc043477f3cfb1e9de0913547e973dac/server/wp-content/rest-api-plugins/endpoints/wcpay/class-reporting-controller.php#L132-L141)):

https://github.com/Automattic/woocommerce-payments/blob/5e99257730c5f83d988e81a6fc1c6324ddb8a2ef/client/data/payment-activity/types.d.ts#L3-L24

#### Testing instructions

- Use a store that does not use `USD` (or any other dollar) as a default currency, e.g. onboard a German WCPay account with `NOK` or `CHF` as the default currency.
- Enable the feature flag: run `wp option update _wcpay_feature_payment_overview_widget 1` in CLI (`npm run cli` if docker)
- Go to `Payments -> Overview`
- Ensure that the Payment Activity renders amounts with the correct currency symbol (e.g. `CHF`, not `$`).

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile **N/A**

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8701` or branch name `fix/8700-payment-activity-card-default-account-currency` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8700-payment-activity-card-default-account-currency) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: d1630b7768b5cd207ec7fc7c866b9f61b3c1dd09
- Build time: 2024-04-29 21:41:06 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by shendy-a8c** [comment]
I tried to work on this but didn't get much, @Jinksi.

File: client/components/payment-activity/payment-data-tile.tsx [hunk 1]
```diff
@@ -24,7 +24,7 @@ interface PaymentDataTileProps {
 	/**
 	 * The currency code for the amount displayed.
 	 */
-	currencyCode: string;
+	currencyCode?: string;
```
Comment (shendy-a8c) [inline client/components/payment-activity/payment-data-tile.tsx:27]: I wonder why this is optional. Actually, I also wonder why the other properties, amount, tooltip, etc, are optional.

Is it because when data is still being fetched or when an error returned by server, `currencyCode` and the other will be undefined?

This makes me think of error handling. When server returns an error, I think we should not render the payment activity card altogether.

What do you think? I think that work should be done in a separate PR though. I can take on it.

Comment (Jinksi) [reply client/components/payment-activity/payment-data-tile.tsx:27]: Yes, due to the way the components are currently rendered, `<Loadable>` is rendered if passed `undefined` values.

I haven't made changes to this component interface, but did update the type for the data returned from the server API in 8503feac733828c07966dfa37489d06fa56bdc6a

> When server returns an error, I think we should not render the payment activity card altogether.

But yes, I agree the error UI state might be a new new issue / PR 💯

File: client/components/payment-activity/payment-data-tile.tsx [hunk 2]
```diff
@@ -53,9 +53,9 @@ const PaymentDataTile: React.FC< PaymentDataTileProps > = ( {
 	reportLink,
 } ) => {
 	return (
-		<div id={ id } className="wcpay-payment-data-highlights__item">
+		<div className="wcpay-payment-data-highlights__item">
 			<p className="wcpay-payment-data-highlights__item__label">
-				<span>{ label }</span>
+				<span id={ id }>{ label }</span>
```
Comment (shendy-a8c) [inline client/components/payment-activity/payment-data-tile.tsx:58]: I don't understand why this `id` attribute needs to be moved but I don't see any CSS selector in `client/components/payment-activity/style.scss` that targets by id (prefixed with `#`), so I don't see this will affect anything.

File: client/data/payment-activity/test/reducer.test.ts [hunk 3]
```diff
@@ -12,6 +12,11 @@ describe( 'receivePaymentActivity', () => {
 		fees: 300,
 		disputes: 315,
 		refunds: 200,
+		currency: 'JPY',
```
Comment (shendy-a8c) [inline client/data/payment-activity/test/reducer.test.ts]: Shouldn't the value of currency in lower case?

I see in some other places as well in this PR's diff.

It's not breaking anything because any use of the currency code in `formatCurrency()` converts the string to upper case or lower case depending on the need correctly, so passing currency code in lower or upper case to `formatCurrency()` will work fine.

It's just that the response from server will always be in lower case.

**Review by shendy-a8c — APPROVED** [review]
Looks good and tested well.

I left a question and a non-blocking feedback.

File: client/components/payment-activity/payment-data-tile.tsx (hunk 2 above)
Comment (Jinksi) [reply client/components/payment-activity/payment-data-tile.tsx:58]: This is used for the `aria-labelledby` attribute for the value/amount.

E.g. to let screen-readers know that the TPV amount is labelled 'Total payment volume'.

I noticed this label wasn't being correctly parsed when I was writing a test to check the amount is using the correct currency symbol:

https://github.com/Automattic/woocommerce-payments/blob/d1630b7768b5cd207ec7fc7c866b9f61b3c1dd09/client/components/payment-activity/test/payment-data-tile.test.tsx#L53-L65

File: client/data/payment-activity/test/reducer.test.ts (hunk 3 above)
Comment (Jinksi) [reply client/data/payment-activity/test/reducer.test.ts]: Interestingly `wcpaySettings.currencyData` does use uppercase. But I've adjusted others to lowercase where applicable in 0c74c13, d1630b7.

https://github.com/Automattic/woocommerce-payments/blob/0c74c13a0c014f4417e094b84cc1faa982dee625/client/components/payment-activity/test/payment-data-tile.test.tsx#L30-L32
