### PR TITLE
Fix trial subscription checkout without WooPay signing up

### LINKED ISSUE #4777: Cannot checkout trial subscriptions when WooPay is enabled without signing up
### Describe the bug

Currently when we have WooPay and subscriptions enabled, we cannot finish a trial subscription without signing up to WooPay.

### To Reproduce

1. On merchant site with WooPay and subscriptions enabled, add a trial subscription to the cart.
2. Checkout the order on merchant site without signing up to WooPay (or dismiss the WooPay iframe).
3. A `Error processing checkout. Please try again.` error should appear.

### Actual behavior

Cannot finish the order.

### Screenshots

Screen Shot 2022-09-19 at 7 57 16 PM

### Expected behavior

Show order success screen.

### PR DESCRIPTION
**Pull request by alefesouza**
Fixes #4777 

#### Changes proposed in this Pull Request

* Fix an error that occur when checking out a trial subscription with WooPay without signing up.

#### Testing instructions

* On merchant site with WooPay and subscriptions enabled, add a trial subscription to the cart.
* Checkout the order on merchant site without signing up to WooPay (or dismiss the WooPay iframe).
* The order success page should appear as expect.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -3235,4 +3227,27 @@ public function append_stripelink_button( $field, $key, $args, $value ) {
...
 	}
+
+	/**
+	 * Determine if current payment method is a platform payment method.
+	 *
+	 * @param Payment_Information $payment_information The payment information.
+	 *
+	 * @return boolean True if it is a platform payment method.
+	 */
+	private function is_platform_payment_method( Payment_Information $payment_information ) {
```
Comment (a-danae) [inline includes/class-wc-payment-gateway-wcpay.php]: Because we're only using `$payment_information`'s `is_using_saved_payment_method()` value from this object, why not pass this value alone as a parameter to this method instead of passing the whole object?

**Review by a-danae — APPROVED** [review]
Things look good to me. Left a comment about a detail that could be different but nothing big. I've also tested other flows that could have been affected and didn't find anything off. Thanks!

File: includes/class-wc-payment-gateway-wcpay.php (hunk 1 above)
Comment (alefesouza) [reply includes/class-wc-payment-gateway-wcpay.php]: Makes sense, updated on https://github.com/Automattic/woocommerce-payments/pull/4778/commits/1436de0eb5c3309808c4d3bb5ce294d9fa9740f2.
