### PR TITLE
Check payment method is available before rendering it

### LINKED ISSUE #9365: Express Checkout box is always visible, even if there are no Express Payment Methods
Original issue 
https://github.com/woocommerce/woocommerce/issues/50353

### LINKED ISSUE #50353: Express Checkout box is always visible, even if there are no Express Payment Methods
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The Express Checkout box is always rendered in the Checkout block even when there are no Express Payment methods available:

image

It requires having WooPayments enabled, so I don't know if the issue is in WooCommerce core or WooPayments itself.

### Expected behavior

If no Express Payment methods are available, the Express Checkout box shouldn't be rendered.

### Actual behavior

The Express Checkout box is rendered even though there are no Express Payment methods available.

### Steps to reproduce

1. Create a new site and install WooCommerce and WooPayments.
2. Set up both plugins and import some products.
3. In the frontend, add a product to your cart and go to the Checkout.
4. As long as your browser doesn't support any of the Express Payment methods, you will see the Express Checkout box is rendered on top of the Checkout block without any contents. In the Cart block, you will also see the `OR` line above the _Proceed to Checkout_ block, which feels confusing.

image

### WordPress Environment

Tested with WC 9.1.4 and 9.2 beta with several browsers and two different stores, all of them using WP 6.6.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by asumaran**
Fixes https://github.com/Automattic/woocommerce-payments/issues/9365
Fixes https://github.com/woocommerce/woocommerce/issues/50353

#### Testing instructions

Please follow instructions from https://github.com/woocommerce/woocommerce/issues/50353. Bug should be gone with this branch.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9378` or branch name `as-fix-empty-express-checkout-element` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=as-fix-empty-express-checkout-element) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: e7717e5640e52917c7220c0c5d9641320ac47e07
- Build time: 2024-09-06 18:11:24 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by bborman22 — CHANGES_REQUESTED** [review]
I was able to test this mostly successfully. I confirmed that the Express Checkout box is not displayed if there are no express payment methods available. I also tested this alongside the PayPal button to confirm that when all of the WooPayment buttons are disabled the box still displays the PayPal button. I tested each combination below:

PayPal enabled / disabled
WooPay enabled / disabled
GPay & ApplePay enabled / disabled

I tested each combination on Chrome, Chrome Incognito, Safari, Firefox, and Brave browsers.

I confirmed in all scenarios that the box displayed or didn't display as appropriate. The only time the box doesn't display is when all three are disabled or if GPay & Apple Pay is the only method enabled and viewing on Firefox. I also did some regression checks on the blocks cart and both shortcode cart and checkout. I also confirmed the buttons were functional and I could complete a purchase in these scenarios.

For some of the issues I encountered they were unrelated to this PR, but I think we should fix them here given the severity and tight timeline before release:

1. ✅ I wasn't getting the GPay button when using the large size. This was due to the [removal of the WooPayments width override](https://github.com/Automattic/woocommerce-payments/pull/9248). I then tested with the WC 9.3 RC to confirm that the min-width there was applying correctly. So no need for changes here as WC 9.3 will include this fix as planned.
2. ❌ I tested different size and theme options and found that on small + light the GPay and Apple Pay buttons weren't rendering. This was due to [this fix](https://github.com/Automattic/woocommerce-payments/pull/9258/files#diff-012e9a1a278626a3ad8d0e95392d7b6df295ca06071ddcb214751e5ffbc083dfR46). I included a diff to fix this below, but I'll note this will re-open the 2px difference issue. I think this is an acceptable trade off to have the button display. This fix also makes sure we don't run into this concern about heigh min / max again 🤞 . If you could apply this patch and test out all combos of size + theme again to confirm it's all working as intended @asumaran?
3. ❌ When using the light theme, the outline of the GPay button is cut off on it's width (screenshot below). This is likely due to the odd way that Stripe is adjusting the background with a negative margin. This could be fixed by setting `.wc-block-components-express-payment .wc-block-components-express-payment__event-buttons>li` width to 99% instead of 100%. cc @alexflorisca let me know if there is another approach to take here. I'm guessing this only applies to Stripe ECE + GPay light / outline due to their negative margin. I'm not sure if this PR is the right place to fix this issue though.

```diff
diff --git a/client/express-checkout/blocks/components/express-checkout-component.js b/client/express-checkout/blocks/components/express-checkout-component.js
index 3a9962201..aeabc7ecd 100644
--- a/client/express-checkout/blocks/components/express-checkout-component.js
+++ b/client/express-checkout/blocks/components/express-checkout-component.js
@@ -53,9 +53,19 @@ const adjustButtonHeights = ( buttonOptions, expressPaymentMethod ) => {
 		expressPaymentMethod === 'googlePay' &&
 		buttonOptions.buttonTheme.googlePay === 'white'
 	) {
-		buttonOptions.buttonHeight = buttonOptions.buttonHeight - 2;
+		// The minimum allowed size is 40px.
+		buttonOptions.buttonHeight = Math.max(
+			buttonOptions.buttonHeight - 2,
+			40
+		);
 	}
 
+	// Clamp the button height to the allowed range 40px to 55px.
+	buttonOptions.buttonHeight = Math.max(
+		40,
+		Math.min( buttonOptions.buttonHeight, 55 )
+	);
+

 	return buttonOptions;
 };
 ```

Screenshot 2024-09-05 at 11 30 22 AM

**Comment by asumaran** [comment]
```
+	// Clamp the button height to the allowed range 40px to 55px.
+	buttonOptions.buttonHeight = Math.max(
+		40,
+		Math.min( buttonOptions.buttonHeight, 55 )
+	);
```

@bborman22 shouldn’t this last part of the diff be sufficient to fix the height issue you found?

**Comment by bborman22** [comment]
True, I had added the earlier constraint before deciding to go with a more widespread solution. So just the clamping at the end  should be sufficient.

**Comment by asumaran** [comment]
Thank you for the thorough and detailed review, @bborman22!. This should be ready for further review.

There's still some minor CSS issues that don't work with WC 9.2.3, for example:

Screenshot 2024-09-05 at 11 56 01 AM

But it's fixed on WC's `trunk`

Screenshot 2024-09-05 at 11 56 54 AM

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+ * Internal dependencies
+ */
+import { isLinkEnabled } from 'wcpay/checkout/utils/upe';
+import request from 'wcpay/checkout/utils/request';
+import WCPayAPI from 'wcpay/checkout/api';
+import { getUPEConfig } from 'wcpay/utils/checkout';
+
+export const checkPaymentMethodIsAvailable = memoize(
+	( paymentMethod, cart, resolve ) => {
+		const root = ReactDOM.createRoot(
```
Comment (bborman22) [inline client/express-checkout/utils/checkPaymentMethodIsAvailable.js:18]: I am getting the following warning from this line. I'm not sure why it's not getting flagged in `WooPayExpressCheckoutButtonContainer` also?

```
Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".
    at span
    at WooPayExpressCheckoutButtonContainer (webpack-internal:///./client/checkout/woopay/express-button/woopay-express-checkout-payment-method.js:39:73)
```

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+						},
+					} }
+					onReady={ ( event ) => {
+						let canMakePayment = false;
+						if ( event.availablePaymentMethods ) {
+							canMakePayment =
+								event.availablePaymentMethods[ paymentMethod ];
+						}
+						// eslint-disable-next-line no-console
+						console.log(
```
Comment (bborman22) [inline client/express-checkout/utils/checkPaymentMethodIsAvailable.js]: Like we discussed, let's remove this console log.

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+							`Payment method ${ paymentMethod }, is available? `,
+							canMakePayment
+						);
+						resolve( canMakePayment );
```
Comment (bborman22) [inline client/express-checkout/utils/checkPaymentMethodIsAvailable.js:71]: Do you think we should do any clean up here and unmount this element once we've gotten what we need?

**Review by bborman22 — CHANGES_REQUESTED** [review]
Thanks for addressing those two unrelated issues here. I can see the button rendering correctly now in the small + light theme 👍 

I retested the above scenarios in the same browsers and found that the Express Checkout box is correctly only rendered when there is available payment methods and is hidden otherwise. I left a couple notes on the code for things that still need to be addressed but overall it's testing really well.

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js (hunk 1 above)
Comment (bborman22) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js:18]: I see it is being thrown from the Container in that message I copied 🤦 , when I was looking reproduce, it was coming from the `checkPaymentMethodIsAvailable` function?

Comment (asumaran) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js:18]: I don't get this error, @bborman22. On which page are you getting this warning?

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js (hunk 3 above)
Comment (asumaran) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js:71]: Good call. I'll see what can we do.

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js (hunk 2 above)
Comment (asumaran) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js]: done [9d3b78b](https://github.com/Automattic/woocommerce-payments/pull/9378/commits/9d3b78b7fa336c1820a3e8ef43f8cd2683c016fb)

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js (hunk 3 above)
Comment (asumaran) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js:71]: done [3247c13](https://github.com/Automattic/woocommerce-payments/pull/9378/commits/3247c137752402e65299ecfa21f5aa8083d200be)

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js (hunk 1 above)
Comment (asumaran) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js:18]: It's odd we haven't noticed this before, as this is the only way we're importing ReactDOM across the entire plugin.

Comment (bborman22) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js:18]: Yeah it's really odd because like in my original mix up above, it seems to come intermittently. I also see it happening for WC Core blocks-checkout. I see this warning on the blocks checkout page.

Screenshot 2024-09-06 at 9 47 03 AM

It doesn't seem to be causing any issues and seems to work as expected? I also noticed that this error should only be coming from `react-dom` v18+ and in WooPayments we're using 17.0.2?

Given the following I think we can ignore this for now:
- You're not seeing the same error.
- We are using createRoot this way everywhere.
- The warning shouldn't even happen in our version of react-dom and `createRoot` [isn't exported from `react-dom/client` until v18](https://github.com/facebook/react/blob/main/CHANGELOG.md#react-dom-client).

We can ignore this for now.

**Review by bborman22 — CHANGES_REQUESTED** [review]
With those last issues addressed, I ran through the tests again with success! 

I found one more small (unrelated) display issue. I've included the diff here to fix it and ran through all my tests with it applied. If we can get this included here and if you wouldn't mind also doing one last pass for any display issues then I think we can merge this PR! Sorry for all the unrelated display fixes, but figured we can get them addressed with one-liners so worth including.

This issue happens when using the light or outline view in Safari on the Cart block with Storefront and the sidebar.

Screenshot 2024-09-06 at 10 54 57 AM

I was able to fix it with the following change:

```diff
diff --git a/client/express-checkout/blocks/express-checkout-element.scss b/client/express-checkout/blocks/express-checkout-element.scss
index ea02b0bfe..4b4e3d5e2 100644
--- a/client/express-checkout/blocks/express-checkout-element.scss
+++ b/client/express-checkout/blocks/express-checkout-element.scss
@@ -18,5 +18,6 @@
 .wc-block-components-express-payment
 	.wc-block-components-express-payment__event-buttons
 	> li {
+	margin-left: 1px !important;
 	width: 99% !important;
 }
```

**Comment by asumaran** [comment]
@bborman22 I've tested with Chrome, Safari and Firefox, also with PayPal and the original issue doesn't happen anymore.

Screenshot 2024-09-06 at 12 59 05 PM

However, I’ve found a small unrelated CSS issue on the **product page**: the PayPal buttons are too far from the Express Checkout button group, and the buttons themselves are too close together, not respecting the 12px spacing that was recently defined. This might need to be fixed within the PayPal plugin, but I’m mentioning it so that it’s on our radar cc @pierorocca

**Review by bborman22 — APPROVED** [review]
Went through another round of tests and confirmed it all looked good! Thanks for your patience with me on this review and addressing all the issues!

LGTM!

**Comment by sergiu-radu** [comment]
Hello @asumaran and @bborman22,

I see you updated the WooPayment to 8.2.0 and added 2 new containers on the cart/checkout page:
`<div id="express-checkout-check-availability-container-googlePay" style="height: 0; float:left; opacity: 0; pointer-events: none;"></div>`
and 
`<div id="express-checkout-check-availability-container-applePay" style="height: 0; float:left; opacity: 0; pointer-events: none;"></div>`

These containers are now direct child of the `entry-content` and this causes issues in some cases where direct child's of this container have a `width` CSS property, please see this video - https://d.pr/v/lJ3dKm

Maybe a better way/idea would be to place these new containers inside the `woocommerce` container that is inside the `entry-content`?
This solves the issue pretty well, please see this quick video - https://d.pr/v/DftSrP

What do you think?

**Comment by bborman22** [comment]
Thanks so much @sergiu-radu for calling this out! We actually ran into other issues with this approach as well and are looking at [this approach](https://github.com/Automattic/woocommerce-payments/pull/9420) as a replacement.

**Comment by sergiu-radu** [comment]
With pleasure @bborman22 :)

By the way, do you know when approximately a new update with this new approach will be released?
We have a lot of clients that where affected by the change from this PR and I have to know what to tell them.

**Comment by bborman22** [comment]
We're aiming to have it out within the next 24 hours. In the meantime a rollback to 8.1.1 should avoid the issue if that is an option.

**Comment by sergiu-radu** [comment]
Great, thanks for letting me know @bborman22 🤝

**Comment by bborman22** [comment]
@sergiu-radu WooPayments 8.2.1 was released a few hours ago and should have addressed the issue you were running into. Sorry for the disturbance and hoping you're sites are back on track now!

**Comment by sergiu-radu** [comment]
Hey @bborman22, yep, I tested it already and can confirm that everything is back to normal :)
Thank you very much for your help 🤝
