### PR TITLE
Fix Link errors after update

### LINKED ISSUE #4532: Stripe Link: After latest updates, some Link functionalities does not work anymore
### Describe the bug

After latest updates, some Link functionalities does not work anymore .
1. In some cases, address is not completed when "Ship to a different address" is checked in combination with different `Woo -> Settings -> Shipping -> Shipping options -> Shipping destination` settings
2. `State` dropdown is not updated anymore due to select2
3. In some cases  of `Woo -> Settings -> Shipping -> Shipping options -> Shipping destination` settings, there were some errors because some fields were not defined anymore

Check Link functionality with different combinations of  "Ship to a different address" and `Woo -> Settings -> Shipping -> Shipping options -> Shipping destination` setting.

### PR DESCRIPTION
**Pull request by dpaun1985**
Fixes #4532 

#### Changes proposed in this Pull Request
After latest updates, Link functionality was broken. This PR fixes:
-  autocomplete billing address
 - state/country dropdown
 - Link functionality with blocks

#### Testing instructions

* Navigate to Settings -> Payment Methods and enable Link payment method.
* create an order, go to checkout page and complete all checkout fields. Select also 1click payment under credit card fields
* finish the order
* create another order, go to checkout page and complete the email
* a pop-up should be shown to type the pin ( 0 0 0 0 0 0 for tests )
* all checkout billing fields should be completed
* the order should be completed without errors
* Install the https://github.com/woocommerce/woocommerce-blocks plugin.
* Create a new page and Checkout block.
* Verify that StripeLink is working correctly in the block.
* **check the above steps with different options of `Woo -> Settings -> Shipping -> Shipping options -> Shipping destination`**

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: client/checkout/stripe-link/index.js [hunk 1]
```diff
@@ -44,42 +44,47 @@ const enableStripeLinkPaymentMethod = ( options ) => {
...
+			fillWith( billingAddress, options.billing_fields.state, 'state' );
 			fillWith(
 				billingAddress,
-				options.billing_fields.country,
-				'country'
+				options.billing_fields.postal_code,
+				'postal_code'
 			);
 		}
+		jQuery( 'select' ).trigger( 'change' );
```
Comment (mordeth) [inline client/checkout/stripe-link/index.js:87]: Could we use a class or ID instead of `select`? We shouldn't trigger a change event for all `select` elements on the page.

File: client/checkout/stripe-link/index.js [hunk 2]
```diff
@@ -44,42 +44,47 @@ const enableStripeLinkPaymentMethod = ( options ) => {
...
 			fillWith( shippingAddress, options.shipping_fields.city, 'city' );
-			fillWith( shippingAddress, options.shipping_fields.state, 'state' );
 			fillWith(
 				shippingAddress,
-				options.shipping_fields.postal_code,
-				'postal_code'
+				options.shipping_fields.country,
+				'country'
 			);
+			jQuery( 'select' ).trigger( 'change' );
```
Comment (mordeth) [inline client/checkout/stripe-link/index.js:62]: That one should also be improved.

File: client/checkout/stripe-link/index.js [hunk 3]
```diff
@@ -44,42 +44,47 @@ const enableStripeLinkPaymentMethod = ( options ) => {
...
 			fillWith( billingAddress, options.billing_fields.city, 'city' );
-			fillWith( billingAddress, options.billing_fields.state, 'state' );
 			fillWith(
 				billingAddress,
-				options.billing_fields.postal_code,
-				'postal_code'
+				options.billing_fields.country,
+				'country'
 			);
+			jQuery( 'select' ).trigger( 'change' );
```
Comment (mordeth) [inline client/checkout/stripe-link/index.js:79]: That one should also be improved.

**Review by mordeth — APPROVED** [review]
LGTM!

**Review by mgascam — APPROVED** [review]
LGTM!
✅ Classic checkout works as expected
✅ Checkout block works as expected
✅ Tested with different Shipping destinations

**Comment by kalessil** [comment]
@dpaun1985 : are these changes backward compatible with the older blocks versions?

**Comment by dpaun1985** [comment]
> @dpaun1985 : are these changes backward compatible with the older blocks versions?

@kalessil yes, it should work on both versions.
