### PR TITLE
Fix security notices

### LINKED ISSUE #8468: Multi-currency: fix WordPress.Security phpcs reports
Part of https://github.com/Automattic/woocommerce-payments/issues/8434

Check and fix reports in the following files:

* `includes/multi-currency/MultiCurrency.php`

### PR DESCRIPTION
**Pull request by dwainm**
Fixes #8468

#### Changes proposed in this Pull Request
Add escaping and ignore where needed. 

#### Testing instructions

Make sure tests pass.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Review by ismaeldcom — APPROVED** [review]

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8474` or branch name `fix/multi-currency/phpcs-notices` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/multi-currency/phpcs-notices) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 42f1ec07a1ee9709ed40b93e816de15ebb15268e
- Build time: 2024-03-26 10:35:13 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/multi-currency/MultiCurrency.php [hunk 1]
```diff
@@ -1019,6 +1019,8 @@ public function display_geolocation_currency_update_notice() {
 		$notice_id = md5( $message );
 
 		echo '<p class="woocommerce-store-notice demo_store" data-notice-id="' . esc_attr( $notice_id . 2 ) . '" style="display:none;">';
+		// No need to escape here as the function called handles it.
+		// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
 		echo \WC_Payments_Utils::esc_interpolated_html(
 			$message,
```
Comment (reykjalin) [inline includes/multi-currency/MultiCurrency.php:1025]: Hmm, I would've expected this to get caught because of the following lines in `phpcs.xml.dist`:

https://github.com/Automattic/woocommerce-payments/blob/9b6a7da840d6371885f29f8502cec8f1433a6038/phpcs.xml.dist#L73-L77

I wonder if we're not adding that correctly 🤔 
It'd be neat if we didn't need the ignore. I'll see if I can look into this as part of #8460 👍

Comment (dwainm) [reply includes/multi-currency/MultiCurrency.php:1025]: Thank you @reykjalin, good catch there and thanks for looking into it. I wasn't aware of that rule.

Comment (reykjalin) [reply includes/multi-currency/MultiCurrency.php:1025]: Looks like this is actually an issue with the ruleset and not necessarily our config (although I think the config is wrong as well):

See https://github.com/WordPress/WordPress-Coding-Standards/issues/1176 and https://github.com/WordPress/WordPress-Coding-Standards/pull/2370.

I think the config is wrong based on [this example](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Customizable-sniff-properties/_compare/6a276c6762f1be8fd8a14a5fb9090e54889cc8bc...2798f6cb684918364e1dec6a1c6d85a2c1fbed77).

Either way, I guess this can wait until the next time we update the PHPCS sniffs since all those issues and PRs are still open 🫠
