### PR TITLE
Fix WCPay form fields references

### LINKED ISSUE #10193: WC_Payments_WooPay_Button_Handler is trying to access uninitialized data
### Describe the bug

The `WC_Payments_WooPay_Button_Handler` class relies on the contents of `WC_Payment_Gateway_WCPay#form_fields` to create the BUTTON_LOCATIONS options; however, this assumes that the data needed is always available. 

```php
$all_locations = $this->gateway->form_fields[ self::BUTTON_LOCATIONS ]['options'];

$this->gateway->update_option( self::BUTTON_LOCATIONS, array_keys( $all_locations ) );
```

This is untrue, given that in order for the form fields to be properly populated, `WC_Payment_Gateway_WCPay#get_form_fields` needs to be called first. If the form fields don't contain the expected data, the `$all_locations` array will be assigned a `null` value, which will cause the following fatal error: 

```
Fatal error: Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-woopay-button-handler.php:131
```

### To Reproduce

This issue was brought up to our attention here p1737129291734259-slack-C7U3Y3VMY , and it's related to a new site being set up. I currently don't have a precise way to replicate this, but in general the code shouldn't assume that the values are initialized. I guess we could force the `form_fields` values to be empty by just adding this line to `WC_Payments_WooPay_Button_Handler#init`
```php
$this->gateway->form_fields = [];
```
Enable WooPay to make sure that the code will run, then open checkout.

### Actual behavior
A fatal error will be thrown.

### Expected behavior
No fatal error should be thrown.

### PR DESCRIPTION
**Pull request by cesarcosta99**
Fixes #10193.

#### Changes proposed in this Pull Request

After #9940 the gateway `form_fields` is no longer initialized in `WC_Payment_Gateway_WCPay`. That changed made the call `$this->gateway->form_fields` in `WC_Payments_WooPay_Button_Handler` to evaluate to an empty array , causing the fatal error indicated in the issue.

We haven't been able to reproduce the issue live, but by doing a `var_dump($this->gateway->form_fields);` before [this condition](https://github.com/Automattic/woocommerce-payments/blob/573a5b3f75e1ef0bb2b18fc125e23c647255c091/includes/class-wc-payments-woopay-button-handler.php#L127) we can confirm `form_fields` is not evaluating as expected, and if a request ever gets to enter in that condition, it will get the fatal, which finally makes me conclude that's the root cause.

While searching for code references of `$this->gateway->form_fields` I noticed there's another in the settings REST controller, so I went ahead and changed it there too. This way we can prevent potential fatals on that class as well.

> [!WARNING]
> I'm aware this is going to conflict with #10236, but I deliberately created this separate PR to fix and test this issue in two fronts: a) by fixing the root cause in this PR; and b) by applying defensive programming in the other PR. I'm going to handle the conflicts in whichever gets merged last.

Related thread: p1737728531717659-slack-C01BZUL57SQ

#### Testing instructions

**Reproduce the issue**

1. Checkout to `develop`.
2. Add `true ||` to [this condition](https://github.com/Automattic/woocommerce-payments/blob/573a5b3f75e1ef0bb2b18fc125e23c647255c091/includes/class-wc-payments-woopay-button-handler.php#L127):
```php
if (true || ! array_key_exists( self::BUTTON_LOCATIONS, get_option( 'woocommerce_woocommerce_payments_settings' ) ) ) {
```
3. Add a product to the cart and navigate to checkout.
4. The same fatal error indicated in the issue should be triggered:
`Fatal error: Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given`

**Test: No fatal error is triggered**

1. Checkout to this branch.
2. Keep the condition change you did in step 2 above.
3. Refresh the checkout page.
4. You should not see any errors and page should load successfully.

**Regression test: WooPay selected pages is working as expected**

1. As a merchant, navigate to **Payments > Settings > Express checkouts > WooPay > Customize**.
2. Play with the **Enable WooPay button on selected pages** options by randomly checking and unchecking some of them.
3. As a customer, ensure the option is being saved and is working correctly by checking the WooPay express checkout button is being displayed in the pages you selected.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by cesarcosta99** [comment]
@ricardo, I requested your review directly here once this is tied to #10236 and the testing is exactly the same with one addition.

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10252` or branch name `fix/10193-form-fields-reference` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/10193-form-fields-reference) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 7c24b63b4402e226f879c2e22ce4aa87b6b7ad0e
- Build time: 2025-01-29 19:43:26 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by ricardo** [comment]
@cesarcosta99 Do we have a way to pinpoint the changes from https://github.com/Automattic/woocommerce-payments/pull/9940 as a culprit for this error? I tried to `git revert 4608ebb` that commit from `develop` and added the `true ||`, but I could still reproduce the issue.

File: includes/admin/class-wc-rest-payments-settings-controller.php [hunk 1]
```diff
@@ -945,12 +945,15 @@ private function update_woopay_enabled_locations( WP_REST_Request $request ) {
 			return;
 		}
 
-		$woopay_enabled_locations = $request->get_param( 'woopay_enabled_locations' );
+		$wcpay_form_fields = $this->wcpay_gateway->get_form_fields();
 
-		$all_locations = $this->wcpay_gateway->form_fields['payment_request_button_locations']['options'];
-		WC_Payments::woopay_tracker()->woopay_locations_updated( $all_locations, $woopay_enabled_locations );
+		if ( isset( $wcpay_form_fields['payment_request_button_locations']['options'] ) ) {
```
Comment (ricardo) [inline includes/admin/class-wc-rest-payments-settings-controller.php]: In this case, I'd be afraid this `if` statement could silence the original issue and create a different problem where the enabled locations settings are not updated.

I'd prefer only using `get_form_fields()` here as well, as we're not 100% sure what's causing the error, although I understand the intentional defensive programming.

**Review by ricardo — CHANGES_REQUESTED** [review]

File: includes/admin/class-wc-rest-payments-settings-controller.php (hunk 1 above)
Comment (cesarcosta99) [reply includes/admin/class-wc-rest-payments-settings-controller.php]: As discussed in Slack, I reverted the added `if` since there are other calls to `get_form_fields` in the same file. Done in d99cace.

**Comment by cesarcosta99** [comment]
> @cesarcosta99 Do we have a way to pinpoint the changes from #9940 as a culprit for this error?

@ricardo, yes, as I mentioned in p1737753080875879/1737728531.717659-slack-C01BZUL57SQ, you can start a git bisect at `develop` (preferably before #10236 to start with the bad behavior), checkout to say 8.5.0 (couple versions before 8.7.0) and use the condition change to test the issue. It should point you to #9940.

> I tried to `git revert 4608ebb` that commit from `develop` and added the `true ||`, but I could still reproduce the issue.

Considering the time you've left this comment, there's a chance you tested with #10236 merged in `develop`? If so, it'd prevent the fatal anyways.

At `develop`, I ran `git reset --hard 0454bb583` (immediate commit before #10236) and could reproduce the issue. Then, I did `git revert 4608ebb` (#9940), fixed the conflicts by accepting the incoming changes and was no longer able to reproduce the issue. Let me know if you're still having a different output.

File: includes/class-wc-payments-woopay-button-handler.php [hunk 2]
```diff
@@ -126,7 +126,7 @@ public function init() {
 		// Create WooPay button location option if it doesn't exist and enable all locations by default.
 		if ( ! array_key_exists( self::BUTTON_LOCATIONS, get_option( 'woocommerce_woocommerce_payments_settings' ) ) ) {
 			if ( isset( $this->gateway->form_fields[ self::BUTTON_LOCATIONS ]['options'] ) ) {
-				$all_locations = $this->gateway->form_fields[ self::BUTTON_LOCATIONS ]['options'];
+				$all_locations = $this->gateway->get_form_fields()[ self::BUTTON_LOCATIONS ]['options'];
```
Comment (ricardo) [inline includes/class-wc-payments-woopay-button-handler.php:129]: Since `$this->gateway->form_fields` wasn't available, we should probably use `->get_form_fields()` in the `isset` as well, what do you think? Or we might want to remove the `isset`?

**Review by ricardo — COMMENTED** [review]
@cesarcosta99 I was able to replicate the same issue after the revert. I must have mistakenly accepted the current changes instead of the incoming changes when fixing the conflict.

Just left a comment and I think we should be ready to merge.

File: includes/class-wc-payments-woopay-button-handler.php (hunk 2 above)
Comment (cesarcosta99) [reply includes/class-wc-payments-woopay-button-handler.php:129]: Nice catch! I missed it when resolving the conflicts. Since we now have history of failure in this piece, I think it's better to keep the `isset`. Updated it in 7c24b63.

**Review by ricardo — APPROVED** [review]
LGTM!
