### PR TITLE
Fix errors in WooCommerce email settings preview

### LINKED ISSUE #10436: WCPay emails produce errors in WooCommerce email settings preview
### Describe the bug

WooCommerce Payments emails produce errors in WooCommerce email settings preview.

### To Reproduce

1. Use **WooCommerce 9.8.0-dev** (or 9.7 Beta).
2. Enable the **Email improvements** feature flag in **WooCommerce > Settings > Advanced > Features > Experimental features**.
3. Enable `WP_DEBUG`.
4. Make sure **WooCommerce Payments** is enabled.
5. Go to **WooCommerce > Settings > Emails**.
6. Scroll down to the email preview section.
7. Select an email template related to **WooCommerce Payments** in the dropdown (e.g. New receipt).
8. Observe the errors. Examples:
8.1. Many undefined array keys.
8.2. Deprecation notices for function calls like ucfirst().
9. Try changing global email template styles like colors, font, logo, header alignment, footer text and see if changes are applied to your plugin's templates. If you notice something else that is off in your plugin's email template previews, feel free to improve it as well.

### Screenshots
Image

### Expected behavior

WooCommerce Payments email previews work correctly.

### Desktop (please complete the following information):

* OS: Any OS
* Browser: Any browser

### Additional context

WooCommerce version: 		9.8.0-dev
WordPress version: 		6.7.2
Server info: 		PHP/8.3.14

### Tips for fixing

Each error needs to be treated separately, but here are some general useful things.

Empty values, deprecation notices and general rendering errors are usually caused by missing email-specific variables in the preview, e.g. placeholder replacement values, custom email and order details etc. These variables can't be taken from the method that sends the actual email. Dummy values for the preview need to be explicitly provided by a plugin which adds its own email templates.

There is a new [`woocommerce_email_preview_placeholders`](https://github.com/woocommerce/woocommerce/blob/3f6b19126e26235ba6df5688632e96f8be6a08f5/plugins/woocommerce/src/Internal/Admin/EmailPreview/EmailPreview.php#L352-L360) filter to add more placeholders to be replaced that some of your emails may use.

Also, filters are now available to add additional data you might need for emails to be rendered properly in previews:
[`woocommerce_email_preview_dummy_order`](https://github.com/woocommerce/woocommerce/blob/3f6b19126e26235ba6df5688632e96f8be6a08f5/plugins/woocommerce/src/Internal/Admin/EmailPreview/EmailPreview.php#L274-L282)
[`woocommerce_email_preview_dummy_product`](https://github.com/woocommerce/woocommerce/blob/3f6b19126e26235ba6df5688632e96f8be6a08f5/plugins/woocommerce/src/Internal/Admin/EmailPreview/EmailPreview.php#L296-L304)
[`woocommerce_email_preview_dummy_address`](https://github.com/woocommerce/woocommerce/blob/3f6b19126e26235ba6df5688632e96f8be6a08f5/plugins/woocommerce/src/Internal/Admin/EmailPreview/EmailPreview.php#L296-L304)

Another group of filters is for adding support for custom fields and styles your emails might use: [`woocommerce_email_preview_email_content_setting_ids`](https://github.com/woocommerce/woocommerce/blob/fd60f275f51d7ededf69b27b6a884b25251ea3c9/plugins/woocommerce/src/Internal/Admin/EmailPreview/EmailPreview.php#L156), [`woocommerce_email_preview_email_style_setting_ids`](https://github.com/woocommerce/woocommerce/blob/fd60f275f51d7ededf69b27b6a884b25251ea3c9/plugins/woocommerce/src/Internal/Admin/EmailPreview/EmailPreview.php#L129).

Let me know if you need any more help in fixing the issues described above.

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #10436

The "New receipt" and "Payment authentication requested email" lacked preview support and were throwing errors when using the Email Preview feature of WooCommerce core. 

#### Changes proposed in this Pull Request

- Added email preview support for 
  - Payment authentication requested email
  - New Receipt email

#### Screenshots
Screenshot 2025-03-21 at 13 05 28

Screenshot 2025-03-21 at 13 06 29

#### Testing instructions

Prerequisites to test locally
1. Install and activate WooCommerce pre-release version. Hint: use Wordpress CLI `wp plugin install https://github.com/woocommerce/woocommerce/releases/download/9.8.0-beta.1/woocommerce.zip --activate --force`
2. Install and activate WooCommerce Subscriptions plugin to be able to test the "Payment authentication requested email"
3. Enable Email improvements feature flag:
   - Go to WooCommerce > Settings > Advanced > Features
   - Find "Experimental features" section
   - Check "Email improvements" checkbox
   - Save changes

#### Test Email Preview Functionality
1. Navigate to WooCommerce > Settings > Emails
2. Scroll down to the email preview section
4. From the dropdown, select each of these WooCommerce Payments email templates and verify no errors appear:
   - New receipt
   - Payment authentication requested email

#### Test Preview Data
1. For "New receipt" email template:
   - Verify merchant details (store name, address, contact info) are displayed correctly
   - Verify payment method details show sample card data (Visa ending in 4242)
   - Verify payment method details show sample application name and account type

2. For "Payment authentication requested email" email template:
   - Verify order details show sample customer data (John Doe)
   - Verify retry time is displayed correctly

#### Test Email Customization
1. Test global email template customizations:
   - Change email colors in WooCommerce > Settings > Emails
   - Update email header logo
2. Preview both email templates again and verify your changes are applied consistently

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10603` or branch name `fix/10436-wcpay-emails-produce-errors-in-woocommerce-email-settings-preview` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/10436-wcpay-emails-produce-errors-in-woocommerce-email-settings-preview) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 69876f1bc2df4b81655d57030f3588374fb6f5f2
- Build time: 2025-03-25 11:19:26 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by dmvrtx — COMMENTED** [review]
Thanks for working on it, @mgascam . Looks good, but I have a couple of notes:

 - "Payment authentication requested email" requires a WooCommerce Subscription plugin to be active.
 - "New receipt" email has a "Payment method" line under the order total which says "Direct bank transfer" (same as with the authentication requested email). However, the "Payment method" section below has information about a Visa card. It looks like some stubs are missing from the preview data. 

image

**Comment by mgascam** [comment]
> "New receipt" email has a "Payment method" line under the order total which says "Direct bank transfer" (same as with the authentication requested email). However, the "Payment method" section below has information about a Visa card. It looks like some stubs are missing from the preview data.

Good catch @dmvrtx! When WooCommerce Core instantiates the dummy order it sets the bank transfer as payment method. I'm [hooking into it](https://github.com/Automattic/woocommerce-payments/pull/10603/commits/c65783e484b34fe584a2fd1faa1fe4f73c36b7e5) to set the same payment method that woopayments uses for IPP payments. 

> * "Payment authentication requested email" requires a WooCommerce Subscription plugin to be active.

Can you ellaborate on this comment please? As far as I understand it is expected that the email requires a WooCommerce Subscription plugin to be active. Am I missing something? Did you notice something off or maybe a bug? Thanks in advance.

**Comment by dmvrtx** [comment]
> Can you ellaborate on this comment please? 

Sorry, I was not clear. My comment was that the testing instructions didn't mention the WooCommerce Subscriptions requirement. I figured this requirement out by looking at the image example in the issue, but it wasn't entirely obvious 😅

**Review by dmvrtx — APPROVED** [review]
Thanks for addressing suggestions! Looks good and tests well! Just the linter issue left.

File: includes/compat/subscriptions/class-wc-payments-email-failed-authentication-retry.php [hunk 1]
```diff
@@ -75,21 +157,27 @@ public function get_default_heading() {
...
-			$this->retry                 = WCS_Retry_Manager::store()->get_last_retry_for_order( wcs_get_objects_property( $order, 'id' ) );
-			$this->replace['retry-time'] = wcs_get_human_time_diff( $this->retry->get_time() );
+			$this->retry = WCS_Retry_Manager::store()->get_last_retry_for_order( wcs_get_objects_property( $order, 'id' ) );
 		} else {
 			Logger::log( 'WCS_Retry_Manager class or does not exist. Not able to send admin email about customer notification for authentication required for renewal payment.' );
 			return;
 		}
 
+		if ( ! $this->is_enabled() || ! $this->get_recipient() ) {
+			return;
```
Comment (zmaglica) [inline includes/compat/subscriptions/class-wc-payments-email-failed-authentication-retry.php]: Do you think we could do this check before line 160 to avoid this if check?

**Review by zmaglica — APPROVED** [review]
Left one small comment. Overall looks good!

File: includes/compat/subscriptions/class-wc-payments-email-failed-authentication-retry.php (hunk 1 above)
Comment (mgascam) [reply includes/compat/subscriptions/class-wc-payments-email-failed-authentication-retry.php]: That's a good optimization @zmaglica, I added it here [4bd91aa](https://github.com/Automattic/woocommerce-payments/pull/10603/commits/4bd91aafdb9b1e16c6045db6e21b102bd020a467) thanks!
