### PR TITLE
Attach the payment intent data to renewal orders

### LINKED ISSUE #3085: WCPay Subscription renewals don't have orders IDs attached to them on the transactions page
### Describe the bug

When viewing the **Payments > Transactions** page, you will notice there's some transactions which don't link to any WC Orders. These transactions are actually WCPay Subscription renewal orders:

On the `invoice.paid` Webhooks event handling, when we create the renewal order I think we need to also link the WCPay Transaction ID to this order we create as well.

### To Reproduce

To reproduce this issue, you'll need Stripe Billing clocks dev tools setup on your local store.

1. Checkout `develop` branch and pull down WCPay Dev tools latest `trunk` (to test billing clocks)
2. Make sure WC Subscriptions extension is disabled to use WCPay Subscriptions
3. Purchase a subscription product with WC Payments
4. Enable dev testing mode on the subscription to use billing clocks (https://d.pr/i/vETbae)
5. Fast-forward the subscriptions billing clock to process a successful renewal order
6. Once the renewal order is created, visit the **Payments > Transactions** page and you should see a new transaction with no ID in the **Order #** column.

### Actual behavior

WCPay Subscription renewal orders should be linked to Transactions on the transactions page.

### PR DESCRIPTION
**Pull request by a-danae**
Fixes #3085 

#### Changes proposed in this Pull Request

Add the payment intent data to renewal orders.

* Pass an instance of `WC_Payment_Gateway_WCPay` to the `WC_Payments_Subscription_Service` and `WC_Payments_Subscriptions`  class constructors
* Retrieve the related payment intent object when `invoice.paid` webhook is triggered
* Add the payment intent data to the order using [WC_Payment_Gateway_WCPay::attach_intent_info_to_order()](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L1165)

Besides adding the charge ID as a meta to the order (which would alone solve the linked issue), this PR also adds the other paymentIntent data as meta to the order and adds a note with its parsed information, as it happens with regular orders. 

Another approach was simply adding the charge ID as a meta to the order [here](https://github.com/Automattic/woocommerce-payments/compare/fix/order-id-missing-in-renewal-transactions?expand=1#diff-bf0178a8a5666e52202affc2f2e1acad3006584ce361f2d55241fa1193dbcf28L123), which would link the transaction and the order and solve the linked issue, instead of calling `get_and_attach_intent_info_to_order()`, but this approach seemed more complete. We could also mimic `WC_Payment_Gateway_WCPay::attach_intent_info_to_order()` instead of having to pass an instance of `WC_Payment_Gateway_WCPay` just for this method. Lmk what you think, glad to adjust it.

The tests are pending but I wanted to check the approach with you before getting into it.

#### Testing instructions

* Checkout develop branch and pull down WCPay Dev tools latest trunk (to test billing clocks)
* Make sure WC Subscriptions extension is disabled to use WCPay Subscriptions
* Purchase a subscription product with WC Payments
* Enable dev testing mode on the subscription to use billing clocks (https://d.pr/i/vETbae)
* Fast-forward the subscriptions billing clock to process a successful renewal order
* Once the renewal order is created, visit the Payments > Transactions page 
* Opposite to what the linked issue described, now you should see the ID under the `Order #` column for the newly added transaction
* When editing the related order, you should also see an order note with the payment details and a link to the details page of the related transaction

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

File: includes/subscriptions/class-wc-payments-subscription-service.php [hunk 1]
```diff
@@ -98,19 +98,22 @@ class WC_Payments_Subscription_Service {
...
 	 *
 	 * @return void
 	 */
 	public function __construct(
 		WC_Payments_API_Client $api_client,
 		WC_Payments_Customer_Service $customer_service,
 		WC_Payments_Product_Service $product_service,
-		WC_Payments_Invoice_Service $invoice_service
+		WC_Payments_Invoice_Service $invoice_service,
+		WC_Payment_Gateway_WCPay $card_gateway
```
Comment (mattallan) [inline includes/subscriptions/class-wc-payments-subscription-service.php:110]: From my understanding, this variable could reference a UPE gateway class and/or a Card gateway class so I think we should be less specific with the variable name to avoid confusion.

How about just naming this `$gateway`?

File: includes/subscriptions/class-wc-payments-subscriptions-event-handler.php [hunk 2]
```diff
@@ -121,6 +122,9 @@ public function handle_invoice_paid( array $body ) {
 			$order->payment_complete();
 		}
 
+		// Add the payment intent data to the order.
+		$this->subscription_service->get_and_attach_intent_info_to_order( $order, $wcpay_intent_id );
```
Comment (mattallan) [inline includes/subscriptions/class-wc-payments-subscriptions-event-handler.php:126]: I'm wondering if this function should be moved to the `invoice_service` class instead of the `subscription_service` 🤔 

Stripe Billing invoices are represented as WC orders in WooCommerce so I'm thinking it would make sense to call this as `invoice_service->get_and_attach_intent_info_to_order()`. Thoughts?

**Review by mattallan — CHANGES_REQUESTED** [review]
Nice start on this @a-danae !

I've just made a few small suggestions on this PR:
 - Move the new function to Invoice Service class
 - Rename variable is the service class to just `$gateway` instead of `$card_gateway`

Apart from that, this LGTM 💯

File: includes/subscriptions/class-wc-payments-subscriptions-event-handler.php (hunk 2 above)
Comment (a-danae) [reply includes/subscriptions/class-wc-payments-subscriptions-event-handler.php:126]: Makes complete sense to me 🙂  updating it

**Comment by mattallan** [comment]
Amazing work on this one @a-danae !

Code looks good and I've tested the changes and everything works perfectly.

> Besides adding the charge ID as a meta to the order (which would alone solve the linked issue), this PR also adds the other paymentIntent data as meta to the order and adds a note with its parsed information, as it happens with regular orders.

<3 this!
