### PR TITLE
Instant Deposits: Show amount on a notice and button label

### LINKED ISSUE #8220: Instant Deposits: `Deposit available funds` is unclear
### Describe the bug

When a merchant who has access to Instant Deposits has a pending balance but not available funds, the messaging is unclear. 

The merchant is told they can `Deposit available funds`, when `Available funds` are `$0.00` while also being told `You have no funds available to deposit.`

Screenshot 2024-02-19 at 2 50 55 PM

We should update the Instant deposit button with a clearer message.

### designs
We now have designs for this from @rogermattic 🙌🏻  (see comment below https://github.com/Automattic/woocommerce-payments/issues/8220#issuecomment-2006501704)

Image

`Learn more` link directs the user to: https://woo.com/document/woopayments/deposits/instant-deposits/

#### older info

Ideas:
 - `Deposit pending funds`
 - `Deposit $162.83 instantly!`
 - `Deposit $162.83 within 30 minutes`

### PR DESCRIPTION
**Pull request by nagpai**
Fixes #8220 

The PR implements a notice, updated button text and a tooltip for `Instant deposits` on the `Overview` page. The UI update will clearly inform the merchant of the exact amount available for instant deposit. 

#### Testing instructions
* On your test account use the instructions from the following links to have it ready with some instant deposit eligible balance
  * PdjTHR-2XG-p2 - Deposits Cheatsheet 
  * pdjTHR-3oY-p2 - - Demystifying Instant deposits 
  * You may sync your local test site to `acct_1LqHU4QocNIKfAAZ` . This account is approved for instant deposit and should show you the notice and button. 
* Browse to the Payments page. You should see a view similar to the screenshot `With notice` . Note that there is no tooltip icon visible
* The button and the notice should both indicate the correct values for the available amount for instant deposit. The notice should also show the correct fee % ( 1.5% )
* Dismiss the notice
* You will now see tooltip icon 
* On clicking, you should see the message, similar to what you see in the screenshot `Tooltip` 
* `Learn more` link should lead to - https://woocommerce.com/document/woopayments/deposits/instant-deposits/
* If you reload the page, the notice should not appear again. This should persist until you delete the option `wcpay_instant_deposit_notice_dismissed` from the client test site DB. 

#### Points of discussion / decision needed
These are minor changes and can be easily actioned depending on the outcome of the discussion.

* ✅ - Text updated via f93fecb -  ~Whether we need a [change in the text ](https://github.com/Automattic/woocommerce-payments/issues/8220#issuecomment-2175399487) to prevent confusion.~
* ✅  Test to be removed ~[Opinion needed](https://github.com/Automattic/woocommerce-payments/pull/8970#issuecomment-2175432057) - Not directly related, and minor test refactor~
* ✅  - Done - ~How to persist notice dismissal better - 1718694806082599-slack-C02BW3Z8SHK~

### Dev notes
* Figma design : https://www.figma.com/design/aDFNTeogq2cXSr4Nqeni8g/Instant-Deposits?node-id=768-76519&m=dev
* Used the pattern on this PR to persist the dismissed notice state using user settings. Props to @Jinksi  and @shendy-a8c 🙌 
-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8970` or branch name `fix/8220-instant-deposit-messaging` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8220-instant-deposit-messaging) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 93ce365f0fcf03356800499bc5c5c384d23da451
- Build time: 2024-06-20 11:03:59 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by nagpai** [comment]
#### ~Need opinion~

>[!NOTE]
> Resolved! The test is not wanted and removed  via [7034e22](https://github.com/Automattic/woocommerce-payments/pull/8970/commits/7034e224a702485e434b4a25b03dccba0d4c62a2)
> [Ref: discussion](https://github.com/Automattic/woocommerce-payments/pull/8970#discussion_r1645232799)

> Do we need to remove [this test](https://github.com/Automattic/woocommerce-payments/blob/86b2095b0a7fdf753af0edcd742f17fca0c46306/client/deposits/instant-deposits/test/index.tsx#L73-L74) that checks how the instant deposit button looks when amount is `0`? As [per logic ](https://github.com/Automattic/woocommerce-payments/blob/86b2095b0a7fdf753af0edcd742f17fca0c46306/client/components/account-balances/index.tsx#L131-L132)of the parent component, the button will be only displayed if the amount is greater than 0. 
> 
> I personally think the test is redundant, but wanted a confirmation from another eye since this is about removing a test. 
> 
> The test may have been created long time back, when the button was shown as disabled if the amount was zero, and not hidden.

File: client/components/account-balances/index.tsx [hunk 1]
```diff
@@ -1,22 +1,33 @@
...
  * Internal dependencies
  */
-import { useAllDepositsOverviews } from 'wcpay/data';
-import { useSelectedCurrency } from 'wcpay/overview/hooks';
+import type * as AccountOverview from 'wcpay/types/account-overview';
 import BalanceBlock from './balance-block';
+import HelpOutlineIcon from 'gridicons/dist/help-outline';
+import InlineNotice from '../inline-notice';
+import InstantDepositButton from 'deposits/instant-deposits';
+import SendMoneyIcon from 'assets/images/icons/send-money.svg?asset';
```
Comment (haszari) [inline client/components/account-balances/index.tsx:19]: Why the `?asset` – what is the purpose of this? I haven't seen it before.

File: changelog/fix-8220-instant-deposit-messaging [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Clearly display available instant deposit amount on notice and button label on Payment Overview page
```
Comment (haszari) [inline changelog/fix-8220-instant-deposit-messaging:4]: Nice clear merchant-relevant changelog 👌🏻

File: client/components/account-balances/index.tsx (hunk 1 above)
Comment (haszari) [reply client/components/account-balances/index.tsx:19]: I see this is used throughout WooPayments for SVGs, assuming this a way to load them as asset files at runtime. Asked for clarification (so I understand) in front end guild channel internally.

File: client/utils/currency/index.js [hunk 3]
```diff
@@ -349,6 +349,19 @@ function trimEndingZeroes( formattedCurrencyAmount = '' ) {
...
+	return formattedCurrencyAmount
+		.split( ' ' )
+		.map( ( chunk ) =>
+			endsWith( chunk, '0' )
+				? trimEnd( chunk, '0' ).replace( '.', '' )
+				: chunk
+		)
+		.join( ' ' );
+}
+
```
Comment (haszari) [inline client/utils/currency/index.js]: This feels like it would be a useful option on `formatCurrency()`, since it is not used independently.

e.g. 

```js
const formattedInstantBalanceAmount = formatCurrency( 
  instantBalance.amount, 
  instantBalance.currency, 
  'stripTrailingZeroDecimals'
);
```

or with named args "options"

```js
const formattedInstantBalanceAmount = formatCurrency( 
  instantBalance.amount, 
  instantBalance.currency, 
  options: {
    stripTrailingZeroDecimals: true,
  } 
);
```

Although probably not worth pulling that thread, I can see this aligns with the existing currency utils interface. So all good as is, just musing on how to make the utils API compact and simple.

File: client/deposits/instant-deposits/test/index.tsx [hunk 4]
```diff
@@ -92,7 +92,9 @@ describe( 'Instant deposit button and modal', () => {
 			screen.queryByRole( 'dialog', { name: /instant deposit/i } )
 		).not.toBeInTheDocument();
 		fireEvent.click(
-			screen.getByRole( 'button', { name: /Deposit available funds/i } )
+			screen.getByRole( 'button', {
+				name: /Instantly deposit \$123\.45/i,
+			} )
```
Comment (haszari) [inline client/deposits/instant-deposits/test/index.tsx:82]: > Do we need to remove [this test](https://github.com/Automattic/woocommerce-payments/blob/86b2095b0a7fdf753af0edcd742f17fca0c46306/client/deposits/instant-deposits/test/index.tsx#L73-L74) that checks how the instant deposit button looks when amount is 0? As [per logic ](https://github.com/Automattic/woocommerce-payments/blob/86b2095b0a7fdf753af0edcd742f17fca0c46306/client/components/account-balances/index.tsx#L131-L132)of the parent component, the button will be only displayed if the amount is greater than 0.

> I personally think the test is redundant, but wanted a confirmation from another eye since this is about removing a test.


I agree, I don't think keeping that test is a priority. 

Tip: it's easier to review stuff like this with a review comment thread. Some options:

- Add a self-review comment on the relevant file so the reviewer sees it roughly in context.
- Add a comment to the relevant code, then comment on that in a self-review.
- Best: be bold, delete the test, and make your pitch in your PR! You can always revert.

File: client/components/account-balances/index.tsx [hunk 5]
```diff
@@ -26,6 +37,10 @@ const AccountBalances: React.FC = () => {
 	const { overviews, isLoading } = useAllDepositsOverviews();
 	const { selectedCurrency } = useSelectedCurrency();
 
+	const [ showInstantDepositNotice, setShowInstantDepositNotice ] = useState(
+		true
+	);
```
Comment (haszari) [inline client/components/account-balances/index.tsx]: > How to persist notice dismissal better
Tip: add a self-review comment about your concerns/considerations, e.g. here near the relevant code.

This dismissal needs to be persisted, merchants will be justifiably annoyed if they seet the notice after dismissing it. Feels like spam/ads.

Notices dismissals are usually persisted to store (woo) database, as user option or site option. This is a blocker, needs to be fixed.

**Review by haszari — COMMENTED** [review]
Based on a code review this is looking good. I didn't test because my dev is not setup for instant deposits. Happy to do another test review later if needed (I can test on a different site).

There's one blocker: the notice dismissal should be persisted to user options. Look in `wcpaySettings` for similar examples, e.g. `isNextDepositNoticeDismissed` (aka `wcpay_next_deposit_notice_dismissed` in database).

> Whether we need a https://github.com/Automattic/woocommerce-payments/issues/8220#issuecomment-2175399487to prevent confusion.

The current wording was approved earlier (IIRC!) so hopefully we don't get bogged down 😁 

That said, it [looks like we have agreement](https://github.com/Automattic/woocommerce-payments/issues/8220#issuecomment-2176114111) from @rogermattic and @aheckler 🎉 so I recommend going with that new wording. If there is some technical problem with new wording, maybe we can push ahead with the previously approved wording. 

New wording:

> Get $239.66 via instant deposit. Funds are typically in your bank account within 30 minutes. Fee: 1.5%.
> Get $239.66 now

File: client/utils/currency/index.js (hunk 3 above)
Comment (haszari) [reply client/utils/currency/index.js]: Actually, do we need this at all? Would the `.00` (which is rare?) make the copy for the button or the notice meaningfully worse?

I think maybe we should remove this, keep it simple, always show amount consistently. 

@nagpai I recommend confirming this detail with @rogermattic / design before we commit to the extra formatting logic complexity.

File: client/deposits/instant-deposits/test/index.tsx (hunk 4 above)
Comment (nagpai) [reply client/deposits/instant-deposits/test/index.tsx:82]: Awesome tips! Rua! Thank you!

File: client/components/account-balances/index.tsx (hunk 1 above)
Comment (nagpai) [reply client/components/account-balances/index.tsx:19]: I first picked up the pattern from how SVGs were embedded earlier, and then read about it.  I hope I am right about this: `?asset` invokes the asset module of Webpack. [Ref](https://github.com/Automattic/woocommerce-payments/blob/ac88cc0337e7e420e067292bcad869a44fdb2bcc/webpack/shared.js#L101-L102). It bundles the SVG file to a base 64 URI, that can be easily used in HTML.  

Another [helpful read](https://www.linkedin.com/pulse/easy-to-understand-guide-asset-module-webpack-5-prasenjit-sutradhar/) I found.

File: client/utils/currency/index.js (hunk 3 above)
Comment (nagpai) [reply client/utils/currency/index.js]: >Actually, do we need this at all? Would the .00 (which is rare?) make the copy for the button or the notice meaningfully worse?

The chances of .00 coming may be a little more than we imagine, since the upper limit for instant deposit is $1000. This can be hit by many merchants. On my test site, seeing 1000.00 looked a bit awkward to me. I asked myself, why is it showing .00 when it is not needed? Sharing screenshots here: 

#### With decimal and zeroes
image

#### Trimmed
image

File: client/deposits/instant-deposits/test/index.tsx (hunk 4 above)
Comment (nagpai) [reply client/deposits/instant-deposits/test/index.tsx:82]: Test removed - [7034e22](https://github.com/Automattic/woocommerce-payments/pull/8970/commits/7034e224a702485e434b4a25b03dccba0d4c62a2) . Thank you!

File: client/utils/currency/index.js (hunk 3 above)
Comment (haszari) [reply client/utils/currency/index.js]: Right, but is the complexity worth it? Put another way, how important is it to fine tune the max case?

File: client/components/account-balances/index.tsx (hunk 5 above)
Comment (nagpai) [reply client/components/account-balances/index.tsx]: I have added the persistance via c9a35a2

Ref: discussion on slack where i got good guidance - p1718692277231899-slack-C02BW3Z8SHK

File: client/utils/currency/index.js (hunk 3 above)
Comment (nagpai) [reply client/utils/currency/index.js]: >Right, but is the complexity worth it? Put another way, how important is it to fine tune the max case?

This is a good question, and it is now making me lean towards having the decimals 🛝 . I checked [the design](https://www.figma.com/design/aDFNTeogq2cXSr4Nqeni8g/Instant-Deposits?node-id=768-76519&m=dev) just now, and it shows 1000 without the decimal. I request @rogermattic to advice, if it is okay to show `$1000.00` instead of `$1000` .  We will have simpler code.

**Review by brucealdridge — APPROVED** [review]
Tested and works well. Glad to see this issue progress! 

Good work @nagpai

File: client/utils/currency/index.js (hunk 3 above)
Comment (rogermattic) [reply client/utils/currency/index.js]: Hehehe this is a good training for my decision making :) 

>I request @rogermattic to advice, if it is okay to show $1000.00 instead of $1000 . 

While I do prefer `$1000` rather than `$1000.00`, and I love the effort @nagpai makes to accommodate this, I do believe this might not be worth it and I'm all for...

>We will have simpler code.

Comment (nagpai) [reply client/utils/currency/index.js]: > Hehehe this is a good training for my decision making :)

I am so glad to see you take it that way 😃 

Thanks for your prompt check as always, @rogermattic 🙏 !

Comment (nagpai) [reply client/utils/currency/index.js]: I have rolled back the changes, including updating tests - [8316fa1](https://github.com/Automattic/woocommerce-payments/pull/8970/commits/8316fa15f5fa3963c6bae40033c98caba5ad51cf) .
