### PR TITLE
Avoid registering express button hooks when payments are disabled

### LINKED ISSUE #5519: Disable Express Pay Buttons when Account Payments Are Disabled
### Describe the bug

When Payments to a WooCommerce Payments account are disabled due to missing information, the Express Pay buttons still appear on product pages, cart, and checkout. Customers receive an error upon attempting to checkout, as the account cannot receive payments. 

It would be better to disable these buttons, as the credit card fields are already disabled.

To test this, I created a new test site, set up WooCommerce Payments, and ensured the Express Pay buttons appeared. I then swapped the accounts to one that had previously been restricted for lack of information and cleared the WC Pay cache to ensure the disabled account was the one connected. The buttons still appeared, but the card fields were disabled at checkout. 
I then completed onboarding the account but with fake data that couldn't be verified so payments were still disabled. The buttons still appeared. 

### To Reproduce

1. Have a WooCommerce Payments account with disabled payments and deposits
2. Enable Express Payments at WooCommerce > Settings > Payments > WooCommerce Payments
3. Visit a product, cart or checkout page
4. Confirm that the Express button appears
5. Confirm that the credit card fields for checkout do not appear

### Actual behavior

The buttons appear and indicate to customers that they can pay with Apple Pay or Google Pay, even though the merchant cannot take payments using WooCommerce Payments.

### Screenshots

Screenshot 2023-02-03 at 6 21 09 PM

Screenshot 2023-02-03 at 6 17 37 PM

### Expected behavior

I expected the express buttons would be disabled if the site could not use WooCommerce Payments for transactions. 

### Additional context

Identified in 5926336-zen using WooCommerce Payments 5.4.0

### PR DESCRIPTION
**Pull request by mdmoore**
Fixes #5519

#### Changes proposed in this Pull Request

This PR ensures that express checkout buttons such as the WooPay, Apple Pay, and Google Pay buttons do not appear when payments are disabled on the WCPay account. 

#### Testing instructions

1. On the `develop` branch, enable Payment Requests and/or WooPay to ensure express checkout buttons will appear on the Checkout, Cart, or Product pages.
2. In the WooCommerce Payments Server codebase, open the accounts controller and change the [value of `payments_enabled`](https://github.com/Automattic/woocommerce-payments-server/blob/592789030a59f34f2bbc3bdc240112a3ded05866/server/wp-content/rest-api-plugins/endpoints/wcpay/class-accounts-controller.php#L668) to `false`.
3. Back on the WCPay client, clear the account cache via WCPay Dev Tools and double check the account data to ensure `payments_enabled` is set to `false`. 
4. Visit a Cart, Checkout, or Product page and notice that the express checkout/payment request buttons still appear.
6. Checkout the `fix/5519-disabled-account-hide-express-buttons` branch and refresh the page from above, verifying that the express checkout buttons do not appear.

-----

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6187` or branch name `fix/5519-disabled-account-hide-express-buttons` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/5519-disabled-account-hide-express-buttons) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b6b8d3fed04a51685b1f9a06795452bb0e9abc22
- Build time: 2023-05-08 15:17:00 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payments-features.php [hunk 1]
```diff
@@ -111,6 +111,30 @@ public static function is_upe_settings_preview_enabled() {
...
+	}
+
+	/**
+	 * Checks if WooPay is enabled.
+	 *
+	 * @return bool
+	 */
+	public static function is_woopay_enabled() {
+		$is_platform_checkout_eligible               = self::is_platform_checkout_eligible(); // Feature flag.
+		$is_platform_checkout_enabled                = 'yes' === WC_Payments::get_gateway()->get_option( 'platform_checkout', 'no' );
```
Comment (FangedParakeet) [inline includes/class-wc-payments-features.php]:
```suggestion
		$is_platform_checkout_enabled                = 'yes' === WC_Payments::get_gateway()->get_option( 'platform_checkout' );
```
I don't think you need to pass the second parameter [here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L1675), as it will be `null` by default.

File: includes/class-wc-payments.php [hunk 2]
```diff
@@ -1356,6 +1352,19 @@ function ( $container ) {
...
+	/**
+	 * Initializes express checkout buttons if payments are enabled
+	 *
+	 * @return void
+	 */
+	public static function maybe_display_express_checkout_buttons() {
+		if ( WC_Payments_Features::are_payments_enabled() ) {
+			$payment_request_button_handler                = new WC_Payments_Payment_Request_Button_Handler( self::$account, self::get_gateway() );
+			$platform_checkout_button_handler              = new WC_Payments_Platform_Checkout_Button_Handler( self::$account, self::get_gateway(), self::$platform_checkout_util );
+			self::$express_checkout_button_display_handler = new WC_Payments_Express_Checkout_Button_Display_Handler( self::get_gateway(), $payment_request_button_handler, $platform_checkout_button_handler );
```
Comment (FangedParakeet) [inline includes/class-wc-payments.php]:
```suggestion
			$express_checkout_button_display_handler = new WC_Payments_Express_Checkout_Button_Display_Handler( self::get_gateway(), $payment_request_button_handler, $platform_checkout_button_handler );
```
This is pretty pedantic, but since we moved the `is_woopay_enabled` functionality to the `WC_Payments_Features` class, does `$express_checkout_button_display_handler` need to be static anymore? Is it reused anywhere or can we just instantiate it here once as a local variable, like the other express checkout button handlers, and call it a day? 🤔

File: includes/class-wc-payments-features.php (hunk 1 above)
Comment (mdmoore) [reply includes/class-wc-payments-features.php]: Yes, good point! I think this default is being set throughout the codebase from it's initial incarnation, showing 'no' in the Gateway Settings or something similar. I can't find any place where we're actually checking for that string. Definitely not needed here. Fixed in [619bcca](https://github.com/Automattic/woocommerce-payments/pull/6187/commits/619bccad13ff41ba492fbd5bf444d4c6c2283017).

File: includes/class-wc-payments.php (hunk 2 above)
Comment (mdmoore) [reply includes/class-wc-payments.php]: Nice catch! It's only used here to instantiate the class now since we're no longer calling any methods on it. Fixed with [619bcca](https://github.com/Automattic/woocommerce-payments/pull/6187/commits/619bccad13ff41ba492fbd5bf444d4c6c2283017).

**Review by FangedParakeet — APPROVED** [review]
Cheers for making those miniature adjustments. Code looks great and works just as described. LGTM. :shipit:
