### PR TITLE
Fix UPE styles extraction in the Site Editor 

### LINKED ISSUE #10335: WooPayments card form fields are showing up in dark mode
### Describe the bug
The WooPayments form fields are showing up in dark mode on a light background theme, which is jarring and looks out of place.

Image

I've tested two different test sites and I'm not sure where the issue is coming from, however @pierorocca provided some context in Slack that there have been changes to the way we call the Stripe appearance API through UPE appearance.

### To Reproduce

1. Install and connect WooPayments
2. Go to checkout
3. See issue

### Expected behavior
The card form fields should match the store theme and be consistent with other form fields at checkout.

We'll need to adjust and correct the colors to more reliably match the store theme. Or consider a different approach if shoppers are likely to see this issue, since it could impact checkout conversion.

cc @FangedParakeet For your thoughts on next steps here.

### PR DESCRIPTION
**Pull request by danielmx-dev**
Fixes #10335

#### Changes proposed in this Pull Request

In order to prevent from bleeding into the page preview, the site editor embeds the contents into an iframe, however, react still runs in the context of the host page. 

The code that extracts the style also runs within the context of the host page, so any reference to the global window and host document will refer to this host page, instead of the elements that are contained within the page preview, this means that none of the style extraction will be performed as expected.

In this PR, we'll make sure that we use the correct document and window objects when performing the style extraction process.

#### Testing instructions

* Use the twenty twenty-five theme
* Make sure you are using blocks checkout
* Using the WCPay Dev tool, click on `Delete UPE appearance transients`. Make sure you don't have any other tabs/windows using checkout to prevent the styles from being computed before we finish our testing.
* Go to Appearance > Editor > Pages > Select your checkout page

**In develop**
- The inputs in the preview are displayed using a dark theme (even if we are using a light theme)
image

- If you open the actual checkout, the inputs will be dark:
image

**Current branch**
- The inputs will appear with a styling that is more similar to the rest of checkout
image

- If you open the actual checkout page, the styles should be consistent with the rest of the page
image

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10433` or branch name `fix/style-extraction-in-editor` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/style-extraction-in-editor) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 5e370c8a781442e538469d3fa0bc7c6dae866fb8
- Build time: 2025-02-27 16:38:08 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/checkout/upe-styles/index.js [hunk 1]
```diff
@@ -50,7 +50,7 @@ export const appearanceSelectors = {
 		pmmeRelativeTextSizeSelector: '.wc_payment_method > label',
 	},
 	blocksCheckout: {
-		appendTarget: '#contact-fields',
+		appendTarget: '.wc-block-checkout__contact-fields',
```
Comment (danielmx-dev) [inline client/checkout/upe-styles/index.js:53]: I had to change since the original selector was not present in `edit` mode.

File: tests/js/jest.config.js [hunk 2]
```diff
@@ -45,6 +45,14 @@ module.exports = {
...
 		'<rootDir>/tests/e2e',
 	],
+	watchPathIgnorePatterns: [
+		'/node_modules/',
+		'/vendor/',
+		'<rootDir>/.*/build/',
+		'<rootDir>/.*/build-module/',
+		'<rootDir>/docker/',
+		'<rootDir>/tests/e2e',
+	],
```
Comment (danielmx-dev) [inline tests/js/jest.config.js:55]: This is slightly unrelated to the PR but I'm always having issues when trying to run `npm run test:watch` due to the large number of files. Please let me know if I should revert this or put it in a separate PR.

File: client/checkout/blocks/payment-elements.js [hunk 3]
```diff
@@ -66,41 +78,43 @@ const PaymentElements = ( { api, ...props } ) => {
...
-					errorMessage={ errorMessage }
-					fingerprint={ fingerprint }
-					onLoadError={ setPaymentProcessorLoadErrorMessage }
-					theme={ appearance?.theme }
-					{ ...props }
-				/>
-			</Elements>
-		</LoadableBlock>
+		<div ref={ containerRef }>
+			<LoadableBlock isLoading={ ! appearance } numLines={ 3 }>
```
Comment (frosso) [inline client/checkout/blocks/payment-elements.js]: I suppose that it's a micro-optimization now, but what do you think of changing this line to
```suggestion
			<LoadableBlock isLoading={ ! appearance || !stripeForUPE } numLines={ 3 }>
```

and removing the `if ( ! stripeForUPE )` check a few lines above?

I'm thinking that with your changes, the `generateUPEAppearance()` function won't be executed until `stripeForUPE` has been provided.
But if instead we move the conditional on `stripeForUPE` below, we can load Stripe _and_ generate the UPE appearance concurrently.

File: client/checkout/blocks/payment-elements.js [hunk 4]
```diff
@@ -66,41 +78,43 @@ const PaymentElements = ( { api, ...props } ) => {
...
-					api={ api }
-					errorMessage={ errorMessage }
-					fingerprint={ fingerprint }
-					onLoadError={ setPaymentProcessorLoadErrorMessage }
-					theme={ appearance?.theme }
-					{ ...props }
-				/>
-			</Elements>
-		</LoadableBlock>
+		<div ref={ containerRef }>
```
Comment (frosso) [inline client/checkout/blocks/payment-elements.js]: (minor and optional, up to discussion) I have some (minor) concerns about wrapping the whole thing with this `div`.
I understand that it's necessary to get a reference for the `getFontRulesFromPage`/`getAppearance` functions.
I guess my concern lies with the possibility of breaking some CSS selectors 🤷 

But what do you think about wrapping everything in a Fragment, and mounting this `div` just as an empty element somewhere within that fragment?

I'm thinking of something like this:
```js
return (
		<>
			<LoadableBlock ...>
			  <Elements ... />
			</LoadableBlock>
			<div ref={ containerRef }></div>
		</>
);
```

Again, optional an up for discussion!

**Review by frosso — COMMENTED** [review]
I tested the changes with Chrome, Safari, Firefox, and they seem to behave consistently, so I think your approach is good 👍 

In `develop` on the "preview" pages, I see the loading box match the theme's color scheme if a dark theme is used (in this case, with TT5):
Screenshot 2025-02-27 at 2 48 30 PM

But with these changes, I see the light color scheme for the preview:
Screenshot 2025-02-27 at 2 52 28 PM

Is that something that can be improved?

**Review by frosso — APPROVED** [review]
Thank you for connecting earlier @danielmx-dev !

> In develop on the "preview" pages, I see the loading box match the theme's color scheme if a dark theme is used (in this case, with TT5)
> But with these changes, I see the light color scheme for the preview:

I think we were able to pinpoint this to a skill issue on my side: it looks like I was probably using "light" inputs, instead of the dark ones 🤦 

I'm good with your changes, since the other comments are pretty much optional 👍 

Thanks again! :shipit:

**Review by frosso — APPROVED** [review]
Checked again, still looking good! Thank you for considering my comments!
