### PR TITLE
Remove `simplifyDepositsUi` feature flag and legacy UI code

### LINKED ISSUE #5749: Remove feature flag and old UI code for simplify deposits UI
### Describe the bug

This issue is a reminder to remove the feature flag implemented here https://github.com/Automattic/woocommerce-payments/issues/5690, maybe when the feature is ready to go live 100%.
The feature flag might have been used in various places.
Make sure to remove them safely.
Remove old UI code.
Add a changelog.

### Additional context

Project: pdjTHR-2i5-p2

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #5749

#### Changes proposed in this Pull Request

This PR removes the `simplifyDepositsUi` feature flag which is now the default UI, removing legacy UI code and improving code quality in the process.

* 🧨 Remove the `simplifyDepositsUi` feature flag which was previously enabled by default.
* 🧨 Remove the legacy `<DepositsInformation />` card component that has been superseded by the `<AccountBalances />` and `<DepositsOverview />` card components (`client/deposits/utils`). This removed card was not visible due to the `simplifyDepositsUi` feature flag being enabled by default.
* 🧨 Remove functions from `client/deposits/utils` that were only used by the legacy `<DepositsInformation />` component.
* 🧨 Remove the legacy variant of the `<InstantDepositButton />` button with the new variant introduced in #6004.
* 🔧 Fixes tests that were affected by the above changes.
* ♻️ Refactor the `client/deposits/utils` code to TypeScript to improve code quality.
* ♻️ Refactor the `<InstantDepositButton />` and `<InstantDepositModal />` component to TypeScript to improve code quality.

#### Testing instructions

* Visit the **Payments → Overview** screen
* Ensure the the Account Balances and Deposits cards render as expected.
* With a WCPay account that is eligible for Instant Deposits, ensure that the Instant Deposit button renders as expected and the modal appears on click.
  * ℹ️ I have a test site that is eligible for Instant Deposits accessible via _secret store_ with ID `10962` (search for `ej-wcpay-usa` on _secret store_). I've uploaded this PR's built WCPay plugin to this site to facilitate testing this PR.
* Ensure all tests and GH checks pass.

Here is a screenshot of the Account Balances and Deposits cards **before/after** this PR for an account eligible for instant deposits.

<div style="display: flex; flex-direction: row;">

Before (develop branch)

After (this PR)
</div>

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6280` or branch name `5749-Remove-feature-flag-and-old-UI-code-for-simplify-deposits-UI` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=5749-Remove-feature-flag-and-old-UI-code-for-simplify-deposits-UI) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: ea18863886d6d62f4d528c63035954f1d5e65f33
- Build time: 2023-05-14 19:43:07 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/deposits/utils/index.ts
Comment (Jinksi) [inline client/deposits/utils/index.ts:1]: Only the functions `getDepositDate` and `getDepositMonthlyAnchorLabel` remain in this file, since the rest were only used by the legacy `<DepositsInformation />` component.

File: client/deposits/instant-deposits/index.tsx
Comment (Jinksi) [inline client/deposits/instant-deposits/index.tsx:1]: Moving the new variant of `<InstantDepositButton />` from `button-and-modal.js` to `index.tsx` as the legacy variant (with the button label `Instant Deposit`) is no longer in use.

File: client/components/account-balances/balances-tab-panel.tsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ import { getCurrencyTabTitle } from './utils';
 import BalanceBlock from './balance-block';
 import BalanceTooltip from './balance-tooltip';
 import { documentationUrls, fundLabelStrings } from './strings';
-import InstantDepositButton from 'deposits/instant-deposits/button-and-modal';
+import InstantDepositButton from 'deposits/instant-deposits';
```
Comment (Jinksi) [inline client/components/account-balances/balances-tab-panel.tsx:18]: The new version of `<InstantDepositButton />` that was contained in `instant-deposits/button-and-modal.js` has been moved to `instant-deposits/index.tsx`, which is being imported here.

File: client/deposits/utils/index.ts
Comment (Jinksi) [inline client/deposits/utils/index.ts:1]: Only the functions `getDepositDate` and `getDepositMonthlyAnchorLabel` remain in this file, since the rest were only used by the legacy `<DepositsInformation />` component.

File: client/deposits/instant-deposits/index.tsx
Comment (Jinksi) [inline client/deposits/instant-deposits/index.tsx:1]: Moving the new variant of `<InstantDepositButton />` from `button-and-modal.js` to `index.tsx` as the legacy variant (with the button label `Instant Deposit`) is no longer in use.

**Comment by Jinksi** [comment]
Note to reviewer. If approved, feel free to merge this PR to make it into the next WCPay code freeze 🚤

**Comment by shendy-a8c** [comment]
GH shows warning of unused variable for `isButtonDisabled` in `client/deposits/instant-deposits/test/index.tsx`.

Screenshot 2023-05-15 at 01 41 28

We explicitly also let eslint to ignore it. I wonder if this statement is good for its effect only and if so, maybe we don't need to assign it to a variable?

This is minor and maybe, if necessary, can be addressed in a separate PR.

File: client/deposits/instant-deposits/test/index.tsx [hunk 2]
```diff
@@ -12,10 +12,14 @@ import { useInstantDeposit } from 'wcpay/data';
...
-useInstantDeposit.mockReturnValue( {
+const mockUseInstantDeposit = useInstantDeposit as jest.MockedFunction<
+	typeof useInstantDeposit
+>;
+
+mockUseInstantDeposit.mockReturnValue( {
 	deposit: undefined,
-	isLoading: false,
-	submit: () => {},
+	inProgress: false,
```
Comment (shendy-a8c) [inline client/deposits/instant-deposits/test/index.tsx:21]: If I understand it correctly, `isLoading` was wrong and is now only caught because moving to TS. Winning!

File: client/deposits/utils/index.ts [hunk 3]
```diff
@@ -0,0 +1,49 @@
+/**
```
Comment (shendy-a8c) [inline client/deposits/utils/index.ts:1]: Unfortunately GH does not show this file is a rename from `client/deposits/utils/index.js` and does not show the diff. I had to download the two files and compare.

File: client/overview/test/index.js [hunk 4]
```diff
@@ -49,6 +49,9 @@ jest.mock( 'wcpay/data', () => ( {
 	useSettings: jest.fn().mockReturnValue( {
 		settings: { enabled_payment_method_ids: [ 'foo', 'bar' ] },
 	} ),
+	useDeposits: jest
```
Comment (shendy-a8c) [inline client/overview/test/index.js:52]: ~I'm not sure why this change is necessary.~ Without it, some unit tests are broken.

**Review by shendy-a8c — COMMENTED** [review]
Looks good and tested well.

Great work on the extra mile to convert js to ts when possible.

Question on the before and after screenshot in the PR description: they are supposed to look exactly the same right? I see a subtle difference on the instant deposit button. The _after_ screenshot has a border as if the button is focused. I'm assuming they are exactly the same but when you took the _after_ screenshot, you were focusing on the instant deposit button? When I look at your test site and my local store, UI looks exactly the same.

I tested the settings page too because it's affected by the change in `client/deposits/utils/index.ts` and the page looks good (unchanged and functional).

Also tested:
- On a fresh new site.
- On my local store which had the feature flag in the database but then deleted from the database, ie `DELETE FROM wp_no_cot.wp_options WHERE option_name = '_wcpay_feature_simplify_deposits_ui';`.
- On a site with previous version of WCPay and updated the plugin to a version with this PR change.

**Review by shendy-a8c — APPROVED** [review]

File: client/deposits/instant-deposits/test/index.tsx (hunk 2 above)
Comment (Jinksi) [reply client/deposits/instant-deposits/test/index.tsx:21]: Yeah, exactly!

File: client/overview/test/index.js (hunk 4 above)
Comment (Jinksi) [reply client/overview/test/index.js:52]: Ah yeah, should've mentioned this.

Previously, the tests for the Overview screen/component were not enabling the `simplifyDepositsUi` flag, so the mock `useDeposits` hook wasn't required.

**Comment by Jinksi** [comment]
> GH shows warning of unused variable for `isButtonDisabled` in `client/deposits/instant-deposits/test/index.tsx`.

I've created issue #6314 for this.
