### PR TITLE
Fix subscription sign-up fees not showing up for Payment Request

### LINKED ISSUE #1773: Subscription sign-up fees not included in total when paying with Payment Request button
See original issue in [Stripe#1459](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1459) for details and repro steps.

Fix needs to be ported from [Stripe#1555](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1555).

### PR DESCRIPTION
**Pull request by ricardo**
Fixes #1773

#### Changes proposed in this Pull Request

- Add get_product_price method to calculate product totals, considering sign-up fees, on the product page.

#### Testing instructions

- Ensure Payment Request Button is enabled under **WooCommerce > Payments > Settings**.
- Install WooCommerce Subscriptions.
- Create a subscription product similar to the one from [this screenshot](https://camo.githubusercontent.com/9f5809e1c37c126d15c3a006d43adf061a3ebf2e17b92674f8594f01209ab827/68747470733a2f2f642e70722f692f484439557a632b).
- Ensure you're signed in.
- Go to that subscription product page.
- Notice the total price is correct.

-------------------

- [x] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 1]
```diff
@@ -211,6 +211,22 @@ public function custom_button_selector() {
...
+	 * Gets the product total price.
+	 *
+	 * @param object $product WC_Product_* object.
+	 * @return integer Total price.
+	 */
+	public function get_product_price( $product ) {
+		$product_price = $product->get_price();
+		// Add subscription sign-up fees to product price.
+		if ( 'subscription' === $product->get_type() && class_exists( 'WC_Subscriptions_Product' ) ) {
+			$product_price = $product->get_price() + WC_Subscriptions_Product::get_sign_up_fee( $product );
```
Comment (vbelolapotkov) [inline includes/class-wc-payments-payment-request-button-handler.php:224]: I'm not an expert here but a bit concerned by this approach. Apparently if fixes particular issue but it doesn't look very extensible to me. I mean there might be other fees or plugins adding their own fees which ideally would be included into total. So that makes me think there should be some WC Core solution to calculate total (at least something is already used for cart) and I'd imagine we reuse it rather than making our own.

**Review by vbelolapotkov — COMMENTED** [review]
@ricardo I tried to test it but no luck. The payment request button doesn't appear to me on subscription product pages. It does on the simple product pages, so I assume it's configured setting properly. FYI, I tested it with Chrome.

**Comment by ricardo** [comment]
@vbelolapotkov Sorry, I forgot to mention in the testing instructions that you need to be signed in in order to see the button for subscriptions (This is an expected thing).

File: includes/class-wc-payments-payment-request-button-handler.php (hunk 1 above)
Comment (ricardo) [reply includes/class-wc-payments-payment-request-button-handler.php:224]: That's a good point and I also tried to find another WC core way of getting the product price other than `$product->get_price()`, but the sign up fee is a special thing from WC Subscriptions which is not part of the recurring price. [It's artificially added to the price on the first purchase](https://github.com/woocommerce/woocommerce-subscriptions/blob/82c9d287d35a87bb487559ac76d05d7b71f9a4b0/includes/class-wc-subscriptions-cart.php#L214-L221). I'd love to know if there's a better way of doing this, but I didn't find any generic way of getting the total including sign-up fees by looking at the source.

We offer a [limited number](https://github.com/Automattic/woocommerce-payments/blob/c435726fb9a50be9a3016bdcf1e4b5b21c8be08d/includes/class-wc-payments-payment-request-button-handler.php#L464-L478) of compatible product types, and some of them require special logic for the product page. Like [variable products](https://github.com/Automattic/woocommerce-payments/blob/c435726fb9a50be9a3016bdcf1e4b5b21c8be08d/includes/class-wc-payments-payment-request-button-handler.php#L242-L261).

We do take advantage of the cart totals when the payment request button is displayed on the cart or checkout page, or before the purchase is confirmed.

`get_product_price` is used only for displaying the price on the product page for the first time. - We get the final cart price once the payment is confirmed by adding the item to the cart and displaying the cart totals including tax and shipping once an address is chosen in the payment request dialog.

**Comment by vbelolapotkov** [comment]
> @vbelolapotkov Sorry, I forgot to mention in the testing instructions that you need to be signed in in order to see the button for subscriptions (This is an expected thing).
> 
> Edit: This PR doesn't need to go into 2.4.0.

You're right, sorry for bringing confusion. I confirm it works as expected when signed in.

**Review by vbelolapotkov — APPROVED** [review]
Sorry, mixed up the tab and approved by mistake.

File: includes/class-wc-payments-payment-request-button-handler.php (hunk 1 above)
Comment (ricardo) [reply includes/class-wc-payments-payment-request-button-handler.php:224]: I asked Lambda (p1620838312163000-slack-CJTS771PB) and they say there's no core way of getting the total price for the PRB from the product page without doing this sort of special logic for subscription products.

We are working on a more robust fix for this in Stripe through adopting a different approach  in 1563-gh-woocommerce/woocommerce-gateway-stripe.

We shall sync the fix here later, but for now I think we can consider this PR as a temporary fix.

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 2]
```diff
@@ -211,6 +211,22 @@ public function custom_button_selector() {
 		return $this->is_custom_button() ? '#wcpay-custom-button' : '';
 	}
 
+	/**
+	 * Gets the product total price.
+	 *
+	 * @param object $product WC_Product_* object.
+	 * @return integer Total price.
```
Comment (asumaran) [inline includes/class-wc-payments-payment-request-button-handler.php:218]: I think this method returns double (or float) since later will be multiplied by `100` in `WC_Payments_Utils::prepare_amount`

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 3]
```diff
@@ -211,6 +211,22 @@ public function custom_button_selector() {
...
+	 */
+	public function get_product_price( $product ) {
+		$product_price = $product->get_price();
+		// Add subscription sign-up fees to product price.
+		if ( 'subscription' === $product->get_type() && class_exists( 'WC_Subscriptions_Product' ) ) {
```
Comment (asumaran) [inline includes/class-wc-payments-payment-request-button-handler.php:223]: I agree this doesn't look good. Hopefully we will improve this with https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1563

**Review by asumaran — CHANGES_REQUESTED** [review]
@ricardo this looks good to me. I left just a comment for you.

File: includes/class-wc-payments-payment-request-button-handler.php (hunk 3 above)
Comment (ricardo) [reply includes/class-wc-payments-payment-request-button-handler.php:223]: Yes 👍

File: includes/class-wc-payments-payment-request-button-handler.php (hunk 2 above)
Comment (ricardo) [reply includes/class-wc-payments-payment-request-button-handler.php]: Good catch, it actually is `mixed`. Sometimes it's an `integer`, sometimes a `double` and sometimes a `string` after doing `gettype( $product_price )` and looking at the source for `$product->get_price()`.

Fixed in 3c8e4be3744f8384e83c51f719252fbe6e0784d6

**Comment by asumaran** [comment]
@ricardo please check the compatibility error

**Review by asumaran — APPROVED** [review]
It works well with all cases I've tested it except for express checkout using the Checkout block. Other than that LGTM
