### PR TITLE
Fix logic to retrieve initial shipping rates for ECE on shortcode cart and checkout pages

### LINKED ISSUE #9368: Use a shipping key to list options in express checkout.
### Describe the bug

This bug was discovered from a single merchant, and has been closed by #9322. Adding issue here for tracking purposes.

It looks like there’s an issue with how we filter shipping options in the shortcode checkout. [We’re filtering by the string “Shipping,” but the backend is returning it as “Delivery.”](https://github.com/Automattic/woocommerce-payments/blob/0d017f60546aa1870cac7b437b7cedad14ccbf0e/client/express-checkout/index.js#L215) I’m not sure why this is happening, especially since we’re using the translated string in both the frontend and backend. To make this check more robust, we could add a new key field that isn’t dependent on translation.

Context: p1724419340089459/1724340668.758779-slack-C7U3Y3VMY

### PR DESCRIPTION
**Pull request by rafaelzaleski**
Fixes p1724340668758779-slack-C7U3Y3VMY
Fixes #9368 

#### Changes proposed in this Pull Request

Updated the logic to retrieve the shipping cost for ECE. Previously, it was based on the translated string for "Shipping," but now it uses the key `total_shipping` to ensure consistency across translations.

#### Testing instructions

1. Test Express Checkout payments on the product page, shortcode cart, and shortcode checkout where shipping is required.
2. Verify that the payment sheet for Express Checkout methods accurately reflects the shipping options available on the cart page, including the names and respective amounts of the shipping options.
3. Ensure there are no console errors related to Express Checkout during the payment processing.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9322` or branch name `fix/ece-shortcode-get-shipping-rates` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/ece-shortcode-get-shipping-rates) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 532aad6bb862954956dde1bafe2a694d1b1ebd09
- Build time: 2024-08-26 16:54:15 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/express-checkout/class-wc-payments-express-checkout-button-helper.php [hunk 1]
```diff
@@ -117,6 +117,7 @@ public function build_display_items( $itemized_display_items = false ) {
 		if ( WC()->cart->needs_shipping() ) {
 			$shipping_tax = $this->cart_prices_include_tax() ? WC()->cart->shipping_tax_total : 0;
 			$items[]      = [
+				'key'    => 'total_shipping',
```
Comment (lovo-h) [inline includes/express-checkout/class-wc-payments-express-checkout-button-helper.php:120]: I am mainly curious but will we need to add the same key in the following line:
* [class-wc-payments-express-checkout-button-helper.php#L726](https://github.com/Automattic/woocommerce-payments/blob/2b912070adcb456f076c088c1b46feb29c523990/includes/express-checkout/class-wc-payments-express-checkout-button-helper.php#L726).

**Review by lovo-h — APPROVED** [review]
Code changes look good and test well.

#### Testing Instructions
* 🟢 Test Express Checkout payments on the product page, shortcode cart, and shortcode checkout where shipping is required.
* 🟢 Verify that the payment sheet for Express Checkout methods accurately reflects the shipping options available on the cart page, including the names and respective amounts of the shipping options.
* 🟢 Ensure there are no console errors related to Express Checkout during the payment processing.
* 🟢 `npm run test:js` and `npm run test:php`.
