### PR TITLE
Fix #5963. GPay shows $0 for subscription_variation products

### LINKED ISSUE #5963: Google Pay total to $0 if product type is subscription_variation
### Describe the bug
If a Product type is `subscription_variation`, the totals will be reset to $0 (or to the shipping method value actually), once the shipping method is selected from the Google Pay modal. The same behavior happens on Apple Pay.

### To Reproduce

1. Go to the product page of a subscription. Make sure the product type is subscription_variation and has free shipping
2. Click on Google Pay button
3. Check the totals, should have the Product price
4. Select a shipping method 
5. Check the totals again, the product price is $0

### Actual behavior
The totals are $0 and the actual order is created with $0

### Screenshots
Screen Shot 2023-04-03 at 13 41 58

### Expected behavior
The totals should remain the same.

### Desktop (please complete the following information):

* OS: Mac
* Browser Chrome
* Version 111.0.3

### Smartphone (please complete the following information):

* Device: Samsung
* OS: Android
* Browser Chrome

### Additional context
This happens because on the function `WC_Payments_Payment_Request_Button_Handler::ajax_add_to_cart()` the cart is empty via: `WC()->cart->empty_cart();`, and then the product is re-added to the cart but only if it matches certain conditions.

The current code evaluates if a product is a subscription using this if statemente: `if ( 'simple' === $product_type || 'subscription' === $product_type ) {`, but it doesn't evaluates if the product is `subscription_variation`, so the cart remains empty.

### PR DESCRIPTION
**Pull request by ecairol**
Fixes #5963

#### Changes proposed in this Pull Request

This change takes into account `subscription_variation` when re-adding products to the cart in the `ajax_add_to_cart()` function.

A similar fix was applied on the function `WC_Payments_Payment_Request_Button_Handler::get_product_price()` on the same file.

#### Testing instructions

1. Go to the product page of a subscription. Make sure the product type is subscription_variation and has free shipping
2. Click on Google Pay button
3. Check the totals, should have the Product price
4. Select a shipping method
5. Check the totals again, the product price is $0

Screen Shot 2023-04-03 at 13 41 58

Screen Shot 2023-04-03 at 14 10 52

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `5964` or branch name `fix/5963-gpay-total-0-for-subscription-variation-products` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/5963-gpay-total-0-for-subscription-variation-products) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 5eab9eb10076ce06e0be7266ee54db7a836046e5
- Build time: 2023-04-18 05:59:02 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 1]
```diff
@@ -1127,7 +1132,7 @@ public function ajax_add_to_cart() {
 			WC()->cart->add_to_cart( $product->get_id(), $qty, $variation_id, $attributes );
 		}
 
-		if ( 'simple' === $product_type || 'subscription' === $product_type ) {
+		if ( 'simple' === $product_type || in_array( $product_type, $subscription_types, true ) ) {
```
Comment (ecairol) [inline includes/class-wc-payments-payment-request-button-handler.php:1135]: I took this approach from the function `get_product_price()` on this same file. [Line 222](https://github.com/Automattic/woocommerce-payments/blob/f24aed493ee7f6d50b5caa71b060232a7b22be79/includes/class-wc-payments-payment-request-button-handler.php#L222). So maybe `$subscription_types` it could be abstracted as a class static variable and accessed in both places? I wanted to keep it as simple as possible, but let me know and I can make the change.

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 2]
```diff
@@ -1108,6 +1108,11 @@ public function ajax_add_to_cart() {
 			define( 'WOOCOMMERCE_CART', true );
 		}
 
+		$subscription_types = [
```
Comment (dpaun1985) [inline includes/class-wc-payments-payment-request-button-handler.php:1111]: I would add this as a constant. maybe we will need the subscription types somewhere else. 
Other than that, LGTM .

**Review by dpaun1985 — APPROVED** [review]
✅ LGTM! ( code review only )

**Comment by ecairol** [comment]
> ✅ LGTM! ( code review only )

Thank you @dpaun1985 
I've also added the changelog file that was missing.
What would be the next step for this to get shipped? Please let me know if there's something I should do.

**Comment by dpaun1985** [comment]
> > ✅ LGTM! ( code review only )
> 
> Thank you @dpaun1985 I've also added the changelog file that was missing. What would be the next step for this to get shipped? Please let me know if there's something I should do.

I added Fusion team as reviewers. Let's wait until the end of this week, and if nothing else pops-up, we can merge the issue.

**Review by elazzabi — APPROVED** [review]
LGTM code-wise. I think the repetition is fine (for now). Maybe we'll need to move it to the class as suggested in the future...

**Comment by anu-rock** [comment]
@dpaun1985 We have two approving reviews now, so it's a good time to merge this PR :)
