### PR TITLE
Load Checkout scripts when Cart Total is 0

### LINKED ISSUE #5641: [GlobalStep] Unable to view "Currency Switcher Widget" block at sidebar on "Appearance > Widgets" page.
### Bug Description:
Unable to view "Currency Switcher Widget" block at sidebar on "Appearance > Widgets" page.

### Environment:
Woocommerce Version: WooCommerce 7.4.0
WooCommerce Payments - 5.6.0 test-1
WordPress version: v6.1.1

PC:
Windows 10,
Chrome(Version 110.0.5481.178)
Firefox(Version 110.0)

### Steps To Reproduce:
1. Create any test site using the JN site.
2. Install and activate all the required plugins.
3. In WP Admin, click on Appearance > Widgets page.
4. Add a new block to the sidebar by clicking the plus icon at the bottom of the existing sidebar widgets.
5. Search Currency Switcher widget and select it. 
6. Observe that, we are unable to view "Currency Switcher Widget" block at sidebar.

### Actual Result:
Unable to view "Currency Switcher Widget" block at sidebar on "Appearance > Widgets" page.

### Expected Result:
"Currency Switcher Widget" block should be displayed properly at sidebar on "Appearance > Widgets" page.

### Screenshot:

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.4.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.55 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.0
WC Database Prefix: wp_
Total Database Size: 7.54MB
Database Data Size: 5.33MB
Database Index Size: 2.21MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.17MB + Index: 0.20MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.39MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.41MB + Index: 0.41MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
page: 10
post: 2
product: 23
product_variation: 7
revision: 3
shop_coupon: 2
shop_order: 55
shop_order_refund: 7
shop_subscription: 18

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.11.2
Code Snippets: by Code Snippets Pro – 3.2.2
Companion Plugin: by Osk – 1.29
WooCommerce Payments: by Automattic – 5.6.0-test-1
WooCommerce: by Automattic – 7.4.0

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 5.0.2
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Subscriptions: by WooCommerce – 4.9.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://military-plover.jurassic.ninja
Subscriptions-core Library Version: 5.3.1
Subscription Statuses: wc-pending: 1
wc-cancelled: 1
wc-active: 16

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 16
wc-cancelled: 1
wc-pending: 1

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-01 06:23:15 +00:00
Options: ✔
Notes: 38
Onboarding: completed

### WooCommerce Payments ###

Version: 5.6.0-test-1
Connected to WPCOM: Yes
Blog ID: 216103860
Account ID: acct_1MgMq8FfHSk08Tzv

### Action Scheduler ###

Canceled: 18
Oldest: 2023-02-28 07:15:06 +0000
Newest: 2023-02-28 11:37:06 +0000

Complete: 437
Oldest: 2023-02-28 06:23:27 +0000
Newest: 2023-02-28 09:30:48 +0000

Failed: 6
Oldest: 2023-02-28 06:43:30 +0000
Newest: 2023-02-28 10:00:21 +0000

Pending: 18
Oldest: 2023-03-01 06:23:27 +0000
Newest: 2023-04-30 09:31:57 +0000

### Status report information ###

Generated at: 2023-02-28 12:51:47 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by jessy-p**
Fixes #5641, #4764, #5277

#### Changes proposed in this Pull Request

- Reverts #5423. Deleted the changelog as well.
- Fixes the original issues #4764 and #5277 by loading the checkout scripts even when cart total is 0. This allows the Checkout form to be displayed if the cart is updated via AJAX on Checkout page.

#### Testing instructions

Testing instructions of #5641, #4764, #5277

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: changelog/fix-5641-check-cart-initialized [hunk 1]
```diff
@@ -0,0 +1,5 @@
+Significance: patch
+Type: fix
+Comment: It is a fix on top of #5423 which has a changelog
```
Comment (htdat) [inline changelog/fix-5641-check-cart-initialized]: Make sense to have this changelog as “insignificant change”, and then the original changelog should be sufficient for the release.

File: includes/class-wc-payment-gateway-wcpay.php [hunk 2]
```diff
@@ -617,7 +617,14 @@ public function register_scripts() {
 
 		wp_set_script_translations( 'WCPAY_CHECKOUT', 'woocommerce-payments' );
 
-		if ( ! WC()->cart->needs_payment() && is_checkout() && ! has_block( 'woocommerce/checkout' ) ) {
+		// load the scripts even if cart does not need payment.
+		if (
+			isset( WC()->cart ) &&
```
Comment (htdat) [inline includes/class-wc-payment-gateway-wcpay.php:630]: Nitpick: this is OK in this specific case. However, I think doing the direct check with `null` like [Woo core](https://github.com/woocommerce/woocommerce/blob/733bcc88cf5e9186b1ae61eb89e30d4eeac74040/plugins/woocommerce/includes/class-woocommerce.php#L851) does can be easier to understand, especially when `WC()->cart` is always [initialized as `null`](https://github.com/woocommerce/woocommerce/blob/733bcc88cf5e9186b1ae61eb89e30d4eeac74040/plugins/woocommerce/includes/class-woocommerce.php#L101-L101).

File: includes/class-wc-payment-gateway-wcpay.php [hunk 3]
```diff
@@ -617,7 +617,14 @@ public function register_scripts() {
...
+			! WC()->cart->is_empty() &&
```
Comment (htdat) [inline includes/class-wc-payment-gateway-wcpay.php:631]: This is redundant as it would have been covered in `WC()->cart->needs_payment` below?

**Review by htdat — COMMENTED** [review]
I manually tested this PR and it fixed the issue.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 3 above)
Comment (jessy-p) [reply includes/class-wc-payment-gateway-wcpay.php:631]: I am not 100% sure, I saw this check used in conjunction with `needs_payment` at other places.

Comment (htdat) [reply includes/class-wc-payment-gateway-wcpay.php:631]: I am seeing [this place](https://github.com/Automattic/woocommerce-payments/blob/d210279f3db18865ab6881f2e89fb5144c2d3b01/includes/class-wc-payment-gateway-wcpay.php#L659-L673) in one of the changed files in this PR.

I think this would help in the case: 

```php
WC()->cart->is_empty() === true && 
WC()->cart->needs_payment() === false
```

But in the case cart is empty, I think the changing code is not called as it would be terminated earlier during the request. 

Anyway, keeping this is OK. I am marking this comment as resolved.

**Review by htdat — APPROVED** [review]
LGTM after further reviewing in this convo.
https://github.com/Automattic/woocommerce-payments/pull/5652#discussion_r1121300654

**Comment by jessy-p** [comment]
@htdat, On second thought I felt that modifying `WC_Payments_Checkout::enqueue_payment_scripts` is not advisable. It is preferable that the code breaks on a zero cart total, than it affects any part of normal checkout, so I moved all the code to within the conditional. I've also restructured per your suggestion of #5423

**Review by fashuvo — APPROVED** [review]
Works correctly on UPE, Classic checkout, and Blocks checkout. And I'm able to see the `Currency Switcher` widget at the footer.

File: includes/class-wc-payment-gateway-wcpay.php [hunk 4]
```diff
@@ -617,11 +618,33 @@ public function register_scripts() {
...
+			if ( WC_Payments_Features::is_upe_legacy_enabled() ) {
+				wp_localize_script( 'wcpay-upe-checkout', 'wcpayConfig', WC_Payments::get_wc_payments_checkout()->get_payment_fields_js_config() );
+				wp_enqueue_script( 'wcpay-upe-checkout' );
+			} elseif ( WC_Payments_Features::is_upe_split_enabled() ) {
+				wp_localize_script( 'wcpay-upe-checkout', 'wcpay_upe_config', WC_Payments::get_wc_payments_checkout()->get_payment_fields_js_config() );
+				wp_enqueue_script( 'wcpay-upe-checkout' );
+			} else {
+				wp_localize_script( 'WCPAY_CHECKOUT', 'wcpayConfig', WC_Payments::get_wc_payments_checkout()->get_payment_fields_js_config() );
+				wp_enqueue_script( 'WCPAY_CHECKOUT' );
+			}
```
Comment (htdat) [inline includes/class-wc-payment-gateway-wcpay.php]: May simplify the code a bit. 

```suggestion

			$handle = 'WCPAY_CHECKOUT';
			$object_name = 'wcpayConfig';

			if ( WC_Payments_Features::is_upe_legacy_enabled() ) {
				$handle = 'wcpay-upe-checkout';
			} elseif ( WC_Payments_Features::is_upe_split_enabled() ) {
				$handle = 'wcpay-upe-checkout';
				$object_name = 'wcpay_upe_config';
			}

			wp_localize_script( $handle, $object_name, WC_Payments::get_wc_payments_checkout()->get_payment_fields_js_config() );
			wp_enqueue_script( $handle );
```

Not something to change here, but IMO, these $handle and $object_name should take advantage of const.

File: changelog/fix-5641-check-cart-initialized (hunk 1 above)
Comment (htdat) [reply changelog/fix-5641-check-cart-initialized]: Since this PR overrides #5423, let's remove the changelog file in that PR (`changelog/fix-4764-load-js-zero-cart`), and add the main changelog message here.

**Review by htdat — COMMENTED** [review]
I have some inline comments. However, in general, the code helped to fix both the regression issue #5641 and the original ones https://github.com/Automattic/woocommerce-payments/issues/4764 and https://github.com/Automattic/woocommerce-payments/issues/5277. 

#### Update: For the original issues, I manually tested in these checkout flows: 

✅ Non-UPE, classic checkout
✅ UPE legacy, classic checkout
✅ UPE Split, classic checkout

I did not Block checkout flows as the original issues did not happen on those flows.

**Comment by htdat** [comment]
#### I could not see the similar issue on the Woo Stripe plugin then I dug up further and I could figure out the reason: 

Here is [the code](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f862adeacf3b2d3c2e1257992111b44830c03c05/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L1779-L1833) on that repo similar to `register_scripts` in WCPay. 

The main difference is that `wp_enqueue_script` happens here rather than in WCPay, it was added when:

- Woo core calls `$gateway->payment_fields()`, 
- that runs [`do_action( 'wc_payments_add_payment_fields' )`](https://github.com/Automattic/woocommerce-payments/blob/5.5.1/includes/class-wc-payment-gateway-wcpay.php#L680-L682) in the main WCPay gateway
- which runs [the added filter](https://github.com/Automattic/woocommerce-payments/blob/5.5.1/includes/class-wc-payments-checkout.php#L76-L77) in `WC_Payments_Checkout`
- and finally runs `wp_enqueue_script`. 

**I think the most suitable fix is to do bring `wp_enqueue_script` calls into `WC_Payment_Gateway_WCPay::register_scripts` with the tight conditions similar to [Woo Stripe plugin](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f862adeacf3b2d3c2e1257992111b44830c03c05/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L1780-L1790)** But with the complicated gateway classes right now, we might follow up as an enhancement issue instead.

File: changelog/fix-5641-check-cart-initialized (hunk 1 above)
Comment (jessy-p) [reply changelog/fix-5641-check-cart-initialized]: Done

File: includes/class-wc-payment-gateway-wcpay.php (hunk 4 above)
Comment (jessy-p) [reply includes/class-wc-payment-gateway-wcpay.php]: Done.

**Review by htdat — APPROVED** [review]
Thanks for updating the code. Re-running manual tests again, they're all good. 

Let's 🚢!
