### PR TITLE
Fix amounts when manually renewing a subscription

### LINKED ISSUE #6739: Mini-cart shows unconverted amount when manually renewing subscription with Multi-Currency
### Describe the bug
The mini-cart will initially show the unconverted amount for the product being renewed during the manual renewal process.

### To Reproduce

Notes:
* You may need to use WooCommerce Subscriptions directly, and you will need to have manual renewals enabled under WooCommerce > Settings > Subscriptions.
*  This was tested with the Storefront theme, which adds a mini-cart to the header of the site. If you are not using Storefront, you will need to add the mini-cart widget somewhere that it will show up on the checkout page.

1. Create a simple subscription product.
2. Add one additional currency under WooCommerce > Settings > Multi-Currency.
3. Add the subscription product to your cart, and check out using a currency that is not the store default currency.
4. On the order confirmation page, click into the subscription.
5. Choose to _Renew now_.
6. When the page loads, you will notice the mini-cart has the wrong amount.

### Screenshots
Screenshot 2023-07-11 at 1 45 03 PM

### Additional context
Found in the testing of:
* https://github.com/Automattic/woocommerce-payments/pull/5489

### PR DESCRIPTION
**Pull request by cesarcosta99**
Fixes #6739.

#### Changes proposed in this Pull Request

This PR tweaks the `should_convert_product_price` logic in the WooCommerce Subscriptions multi-currency compatibility. The implementation of the method is changed in a way to separate the subscription renewal logic from the resubscribe logic since they can behave differently.

This fixes the "mini-cart" unconverted amount issue reported in #6739 and makes sure the amount is converted as needed in other places. "Mini-cart" is within quotes because the issue is not in the mini-cart, actually it's in the subtotal value that was not being converted on time for display.

#### Testing instructions

**Setup**

1. Switch to this branch.
2. As a merchant, ensure you have the Storefront theme active.
3. Install and activate WooCommerce Subscriptions, if needed.
4. Create a simple subscription product.
5. Add one additional currency under **WooCommerce > Settings > Multi-Currency**, if needed.
6. Navigate to **WooCommerce > Settings Subscriptions**.
7. Ensure **Accept Early Renewal Payments** is enabled and save.

> [!IMPORTANT]
> During testing, pay close attention to amounts all of the time. This way we can ensure a consistent conversion and behavior of all multi-currency and subscriptions interactions.

**Test: Ensure all amounts are displayed correctly when doing an early renewal**

1. As a customer, add the subscription product to your cart, and checkout using a currency that is not the store default currency.
2. Navigate to **My account > My Subscription**.
3. Click on the **Renew now** button.
4. Note the subtotal amount in the navigation bar and ensure it displays the correct amount all the time while navigating to the checkout page.
    Jan-15-2025 14-46-01
5. Navigate to the cart and ensure the amount is still correct.
6. Navigate to Blocks cart and Blocks checkout (or shortcode if Blocks is your default) and ensure the amount is still correct.
7. Navigate to other page than the cart and checkout and hover the cursor in the subtotal amount. Ensure all amount are correct.
9. Navigate back to the checkout and complete the purchase. Ensure the order has been processed with the expected amount.

**Regression test: Ensure purchasing a simple subscription works as expected**

1. As a merchant, create a simple subscription product.
2. As a customer, add the subscription product to your cart, and checkout using a currency that is not the store default currency.
3. Ensure the order has been processed with the expected amount.

**Regression test: Ensure automatic subscription renewal works as expected**

1. As a merchant, navigate to **WooCommerce > Status > Scheduled Actions**.
4. Click on **Pending** to filter them out.
5. Find the `woocommerce_scheduled_subscription_payment` item with the customer subscription ID.
6. Hover the item and click on **Run**.
7. Ensure a new order has been processed with the expected amount.

**Regression test: Ensure merchant manual subscription renewal works as expected**

1. As a merchant, navigate to the customer subscription in **WooCommerce > Subscriptions** and edit it.
2. In the **Order actions** section, select **Process renewal**, update and confirm.
3. Ensure a new order has been processed with the expected amount.

**Regression test: Ensure resubscribe works as expected**

1. As a merchant, navigate to the customer subscription in **WooCommerce > Subscriptions** and edit it.
2. Update the status to **Cancelled** and save.
3. As a customer, navigate to **My account > My Subscription**.
4. Click on the **Resubscribe** button and complete checkout.
5. Ensure the order has been processed with the expected amount.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10156` or branch name `fix/6739-renewal-subscription-price` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/6739-renewal-subscription-price) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 47d7dc9240a7409198568b3ab7b893109ba24a1c
- Build time: 2025-01-20 18:13:29 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php [hunk 1]
```diff
@@ -490,13 +490,56 @@ public function test_should_convert_product_price_return_false_when_false_passed
 	}
 
 	/**
-	 * Confirm that false is returned if specific types of subs are in the cart and there are specific calls in the backtrace.
-	 *
-	 * @dataProvider provider_sub_types_renewal_resubscribe
+	 * Confirm that true is returned if renewal is in cart and WooCommerce Subscriptions is setting up cart.
```
Comment (asumaran) [inline tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php]: Could you rephrase or improve this line? I find it a bit unclear.

**Review by asumaran — CHANGES_REQUESTED** [review]
The code looks good and works as expected. I’m leaving a small comment, but it doesn’t require any major changes.

Great fix, @cesarcosta99!

File: tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php (hunk 1 above)
Comment (cesarcosta99) [reply tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php]: Sure thing, done in 5ee287f. Let me know if that works 🙂

**Review by asumaran — APPROVED** [review]
