### PR TITLE
Fix missing payment status for disputes

### LINKED ISSUE #737: Missing mappings for the Payment Status Chip in Transaction Details
[The mappings](https://github.com/Automattic/woocommerce-payments/blob/241d218b853b5628412908a033c0ad4d128a0015/client/utils/charge/index.js#L31-L46) for the Payment Status Chip in the Transaction Details page are missing mappings for `warning_closed` and `charge_refunded`. This results in the chip using its own [default mapping](https://github.com/Automattic/woocommerce-payments/blob/241d218b853b5628412908a033c0ad4d128a0015/client/components/payment-status-chip/index.js#L15-L66) which results in an empty chip.

image

**Expected behavior**

A status chip that isn't empty:

image

# Suggested fix

* Map `charge_refunded` to `Refunded`, similar to what we're already doing for refunded transactions.
* Map `warning_closed` to `Disputed: Inquiry closed`, similar to how the dispute table [maps that to `Inquiry: Closed`](https://github.com/Automattic/woocommerce-payments/blob/241d218b853b5628412908a033c0ad4d128a0015/client/components/dispute-status-chip/mappings.js#L18-L21).

Note that these mappings will probably have to be implemented in the [charge `util.js` file](https://github.com/Automattic/woocommerce-payments/blob/241d218b853b5628412908a033c0ad4d128a0015/client/utils/charge/index.js#L49-L69).

@LevinMedia what do you say to these suggested chip texts?

# Reproducing the issue

1. Make a payment using Stripe's `inquiry` type [dispute testing number](https://stripe.com/docs/testing#disputes) to make a payment: `4000 0000 0000 1976`.
1. Challange the dispute with either `winning_evidence` or `losing_evidence`. Both should result in `warning_closed`.
1. Notice that the transaction details page now has an empty chip.

`charge_refunded` hasn't been reproduced yet (and might actually not strictly have to be handled) but we should cover our bases there anyway.

cc @luizreis

### PR DESCRIPTION
**Pull request by luizreis**
Fixes #737 

#### Changes proposed in this Pull Request

* Update payment statuses to match the ones used in the disputes list
* Adds a test to ensure dispute and inquiry statuses take precedence over refunds
* Refactor Payment Status Chip and extract mapping logic
* Tidy up some payment status and charge utils tests

#### Testing instructions

1. Check if existing payment statuses are working
2. Make a payment using Stripe's `inquiry` type [dispute testing number](https://stripe.com/docs/testing#disputes) to make a payment: `4000 0000 0000 1976`
2.1. Challenge the dispute with either `winning_evidence` or `losing_evidence`, or fully refund the order. All of the options should result in `warning_closed`
2.2. Make sure that the transaction details page has a `Disputed: Inquiry closed` status

\* `charge_refunded` hasn't been reproduced yet, but we should cover our bases there anyway

-------------------

- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by luizreis** [comment]
I had a call with @LevinMedia to clarify this and we decided that it would be better to:
- Update payment statuses to match the [disputes list](https://github.com/Automattic/woocommerce-payments/blob/master/client/components/dispute-status-chip/mappings.js). Meaning that we're going to differentiate between `disputes` and `inquiries` in the status chip and we're going to display the same text, adding a `Disputed:` label for non-inquiry cases.
- Dispute statuses should take precedence over refunds. In case a merchant refunds an inquiry and it gets to the `warning_closed` state, `Inquiry: Closed` should be the payment status.

I'll update this PR to address those decisions.

cc @reykjalin

**Comment by reykjalin** [comment]
>In case a merchant refunds an inquiry and it gets to the warning_closed state, Inquiry: Closed should be the payment status.

I feel like this is part of what I think might cause the confusion I mentioned in an earlier comment. The inquiry will be closed regardless of whether the inquiry was refunded or not, which may be confusing for merchants. I feel like we should differentiate between the 2 with something like `Inquiry: Closed` and `Inquiry: Refunded`, or maybe `Inquiry: Closed & Refunded`.

These inquiry statuses are, of course, different from `Disputed: Won`, `Disputed: Lost`, and `Refunded`.

cc @LevinMedia

**Comment by LevinMedia** [comment]
>I feel like this is part of what I think might cause the confusion I mentioned in an earlier comment. The inquiry will be closed regardless of whether the inquiry was refunded or not, which may be confusing for merchants.

I wrested with that for a bit too, but in the end decided that simply labeling it "Inquiry: closes" keeps it simple. 

If there's an inquiry on the payment, it could be partially refunded, in which case, the inquiry would still be open. That means we'd actually need an additional intermediary status of Inquiry: partially refunded.

I also like the idea of keeping "refunded" out of the inquiry status to separate it conceptually from from disputes, which equal an automatic refund (plus fee) no matter the circumstances. 

In the end, the data in the timeline should clarify the chain of events and payment status: The bank opened an inquiry - the merchant fully refunded the customer, and subsequently the inquiry was closed.

File: client/components/payment-status-chip/test/index.js [hunk 1]
```diff
@@ -7,70 +7,33 @@ import { render } from '@testing-library/react';
...
+		'disputed_won',
+		'disputed_lost',
+		'disputed_warning_needs_response',
+		'disputed_warning_under_review',
+		'disputed_warning_closed',
+	];
+
+	test.each( statuses )( 'renders %s status', ( status ) => {
+		const { container } = render( <PaymentStatusChip status={ status } /> );
+		expect( container ).toMatchSnapshot();
```
Comment (reykjalin) [inline client/components/payment-status-chip/test/index.js:36]: I like how the use of `test.each` to remove the redundancy of the previous tests ❤️
