### PR TITLE
Terminal locations: harden address data validation

### LINKED ISSUE #3071: Missing address check is incorrect
### Describe the bug

```
$is_address_unpopulated = 2 === count( $location_address ) && isset( $location_address['country'], $location_address['state'] );
        if ( $is_address_unpopulated ) {
            return rest_ensure_response(
                new \WP_Error(
```

https://github.com/Automattic/woocommerce-payments/pull/2990/files#diff-35aa27749cb2ec00d6dd9c7d2877ca18cd7d4d308334e2703f9c8a3d2ff6fba4R61

[Stripe location](https://href.li/?https://stripe.com/docs/api/terminal/locations/create) API requires a country and line1 fields
image

But on WCPay we don’t have any validation and people can enter, for instance, line2 and nothing in line1. The current check doesn’t take this into the account and will try to create a location on Stripe

Also from stripe dashboard:

```
Incomplete Location address
This location is missing required address fields: city and postal code. Please update your location to provide these fields by January 31, 2022. To learn more, visit the docs on creating locations.
```

So, city and postal code should be required too

### PR DESCRIPTION
**Pull request by kalessil**
Fixes #3071

#### Changes proposed in this Pull Request

- Hardened address data validation as requested
- TBD

#### Testing instructions

- Modify `includes/admin/class-wc-rest-payments-terminal-locations-controller.php` file and replace `'permission_callback' => [ $this, 'check_permission' ]` with `'permission_callback' => '__return_true'` for the `$this->rest_base . '/store'` route.
- Ensure the address is properly populated in WC settings
- Execute `curl -X GET {store_url}/wp-json/wc/v3/payments/terminal/locations/store`
- Observer the location address as a response
- Update WC setting so address city/line1/zip is empty
- Execute `curl -X GET {store_url}/wp-json/wc/v3/payments/terminal/locations/store`
- Observer the error as a response

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/admin/class-wc-rest-payments-terminal-locations-controller.php [hunk 1]
```diff
@@ -121,8 +121,8 @@ public function get_store_location( $request ) {
 		);
 
 		// If address is not populated, emit an error and specify the URL where this can be done.
-		$is_address_unpopulated = 2 === count( $location_address ) && isset( $location_address['country'], $location_address['state'] );
-		if ( $is_address_unpopulated ) {
+		$is_address_populated = isset( $location_address['country'], $location_address['city'], $location_address['postal_code'], $location_address['line1'] );
```
Comment (dmvrtx) [inline includes/admin/class-wc-rest-payments-terminal-locations-controller.php:124]: This is extremely strict. E.g. https://tosbourn.com/list-of-countries-without-a-postcode/

Comment (kalessil) [reply includes/admin/class-wc-rest-payments-terminal-locations-controller.php:125]: We are currently supporting US only, but I added a corresponding note in 48594dd9ddf3667e069e39da71b0a46f1137d441
