### PR TITLE
Fix order and subscription numbers on transaction list report

### LINKED ISSUE #1548: [GlobalStep] Order ID's are not exported and fails to display in the downloaded CSV file for the transaction table.
## Bug Description:
Order ID's are not exported and fails to display in the downloaded CSV file for the transaction table.

## Test Instructions:
https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions-for-WC-Payments-2.3.0#export-transactions-to-csv-file

## Environment:
Woocommerce Version : WooCommerce 5.1.
WordPress version: (v5.7)

**PC:**
Windows 10, Mac 10.14.6
Chrome(Version 89.0.4389.90) 
Firefox(Version 87.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete setup wizard using United States address as a store address and selecting WC Payments on Business Details step.
1. On the Home screen select Setup WooCommerce Payments task to trigger KYC flow.
1. Complete the KYC flow.
1. Add some products.
1. Go to frontend and purchase some products with WooCommerce payments.
1. Go to WP admin, Payments->Transactions.
1. Click on Download button present at transaction table header.
1. Note that CSV file gets downloaded.
1. Open the CSV.
1. Observe that Order ID's fails to display.

## Actual Result:
Order ID's are not exported and fails to display in the downloaded CSV file for the transaction table.

## Expected Result:
Order ID's should be exported and displayed in the downloaded CSV file for the transaction table.

## ScreenShot:

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://obvious-potter.jurassic.ninja
Site address (URL): https://obvious-potter.jurassic.ninja
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.8.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.16
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 4.27MB
Database Data Size: 2.70MB
Database Index Size: 1.57MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.45MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 6
post: 2
product: 21
product_variation: 7
revision: 4
shop_order: 16
shop_order_refund: 3
shop_subscription: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Query Monitor: by John Blackbourn – 3.6.7
Code Snippets: by Code Snippets Pro – 2.14.1
Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.3.5
Facebook for WooCommerce: by Facebook – 2.3.5
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
WooCommerce Blocks: by Automattic – 4.8.0
WooCommerce Payments: by Automattic – 2.3.0
WooCommerce Shipping & Tax: by Automattic – 1.25.11
WooCommerce Subscriptions: by WooCommerce – 3.0.12
WooCommerce: by Automattic – 5.1.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://obvious-potter.jurassic.ninja
Subscription Statuses: wc-active: 3
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 3

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions


### Action Scheduler ###

Complete: 101
Oldest: 2021-04-12 07:50:41 +0000
Newest: 2021-04-12 13:53:10 +0000

Pending: 5
Oldest: 2021-04-13 11:35:58 +0000
Newest: 2021-06-12 11:22:03 +0000


### Status report information ###

Generated at: 2021-04-12 13:59:28 +00:00
`
```
</details>

### PR DESCRIPTION
**Pull request by luizreis**
Fixes #1548 

#### Changes proposed in this Pull Request

This PR fixes the order and subscription values when generating the transaction list, to fix the CSV download report.

I haven't added a changelog entry as this fix only impacts the transaction list download, which hasn't been shipped yet.

#### Testing instructions

* Submit 3 orders: one with a Simple product, one with a Subscriptions product, and another with two Subscription products that are charged on different days. Your transactions list should look like this:
image
* Click on the "Download" button to export the data and assert that the order and subscription IDs have been exported correctly
* Disable the Subscriptions plugin and refresh the transactions list
    * Make sure the "Subscription #" column is not shown
    * Click on the "Download" button and assert that the order IDs have been exported correctly

Make sure the transaction list is rendered correctly and no console errors are thrown when rendering it.

*Missing order test:*

* Modify the `add_order_info_to_object` in `./includes/wc-payment-api/class-wc-payments-api-client.php:1119` to simulate an order not found response
* Reload the transactions list and assert that no errors show up in the console

-------------------

- [x] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by luizreis** [comment]
cc @kalessil as you're handling this release 😄

**Comment by kalessil** [comment]
Thanks for the ping and quick bug-fix @luizreis, I'll review and test the PR today.

**Review by kalessil — APPROVED** [review]
LGTM, :shipit:

File: client/transactions/list/index.js [hunk 1]
```diff
@@ -168,14 +168,20 @@ export const TransactionsList = ( props ) => {
...
-			wcpaySettings.isSubscriptionsActive &&
-			txn.order &&
-			txn.order.subscriptions &&
-			txn.order.subscriptions.map( ( subscription, i, all ) => [
-				<OrderLink key={ i } order={ subscription } />,
-				i !== all.length - 1 && ', ',
-			] );
+			wcpaySettings.isSubscriptionsActive && orderSubscriptions
+				? orderSubscriptions.map( ( subscription, i, all ) => [
+						<OrderLink key={ i } order={ subscription } />,
```
Comment (nb) [inline client/transactions/list/index.js:181]: First, sorry for the drive-by review. Do we have a better choice than to use the index for the `key`? If the order changes [things can get messy behind the scenes.](https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318)

Comment (luizreis) [reply client/transactions/list/index.js:181]: No worries at all, thank you for bringing this to our attention! We have this pattern being used in some other parts of the code, though it's not that common, so I created #1789 to track it and fix it in all of the places it's used.
