### PR TITLE
Remove duplicative multi-currency task

### LINKED ISSUE #3129: Remove duplicative task list item for Multi-Currency
### Describe the bug
Related to #3060 

The message "Sell worldwide in multiple currencies" appears inside Things to do and also in the inbox note. The message should **only** show in the inbox note and be **removed** from the things to do.

### To Reproduce

1. As a Merchant go to Payments > Overview
2. Scroll to Things to do
3. See "Sell worldwide in multiple currencies" message
4. Scroll a bit more and you will find another "Sell worldwide in multiple currencies" message as an inbox note

### Screenshots

Screen Shot 2021-10-15 at 10 45 13 AM

### Expected behavior
Only the inbox message should be shown
Screen Shot 2021-10-15 at 10 46 33 AM

### PR DESCRIPTION
**Pull request by a-danae**
Fixes #3129 

#### Changes proposed in this Pull Request

Remove multi-currency task keeping its setup page

As mentioned in the linked issue, we have an item saying "Sell worldwide in multiple currencies" doing the same. One is a task in the overview tasks list section, and the other is an inbox note on the same page. This PR removes the task in favor of the inbox note.

* Create a new page to handle the multi-currency setup
* Remove the task displayed on the overview page that pointed to the multi-currency setup
* Point the URLs that used to go to the task's page to the newly added page
* Remove the tests for the task functionalities

image

#### Testing instructions

* Enable the `_wcpay_feature_account_overview_task_list` feature (there's an option in the WCPay Dev tools)
* Go to Payments -> Overview
* Under the section "Things to do", make sure that the item "Sell worldwide in multiple currencies" doesn't show up. This section won't show up if there are no tasks to display. You can make it show up by creating some disputes
* At the bottom of that page, look for the note titled "Sell worldwide in multiple currencies". Make sure that "Set up now" takes you to `?page=wc-admin&path=/payments/multi-currency-setup` and not to `?page=wc-admin&task=woocommerce-payments--multi-currency-setup`. I had to disable and enable again WCPay for this to change

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

File: client/multi-currency-setup/test/index.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+describe( 'MultiCurrencySetupPage()', () => {
+	beforeEach( () => {
+		MultiCurrencySetup.mockReturnValue( <p>Multi-Currency setup task</p> );
+	} );
+
+	afterEach( () => {
+		jest.restoreAllMocks();
+	} );
+
+	it( 'renders "Sell worldwide in multiple currencies" task', () => {
```
Comment (chickenn00dle) [inline client/multi-currency-setup/test/index.js:25]: The naming of this test is a bit strange IMO considering we are moving away from representing this as a task in this PR.  I might be confused here, but it looks like what we are actually testing is whether the setup page renders at all. If so, maybe we change this to:

'renders "Sell worldwide in multiple currencies" page'

**Review by chickenn00dle — CHANGES_REQUESTED** [review]
Great work @a-danae 🙌 

I tested and can confirm the to do task has been removed, while the inbox note correctly directs to the new MC setup page.

I just had a few comments that needed to be addressed, then this looks good to go.

File: client/index.js [hunk 2]
```diff
@@ -149,6 +150,12 @@ addFilter(
 				__( 'Add additional payment methods', 'woocommerce-payments' ),
 			],
 		} );
+		pages.push( {
+			container: MultiCurrencySetupPage,
+			path: '/payments/multi-currency-available',
+			wpOpenMenu: menuID,
+			breadcrumbs: [ rootLink, __( 'Home', 'woocommerce-payments' ) ],
```
[the remark this answers is not in the document]
Comment (a-danae) [reply client/index.js]: Updated 👌  I kept the title displayed before when it was a task but it wouldn't really make sense to keep it if we can make it more descriptive. Thanks! Please let me know if another title would be better.

File: includes/multi-currency/Notes/NoteMultiCurrencyAvailable.php [hunk 3]
```diff
@@ -26,7 +26,7 @@ class NoteMultiCurrencyAvailable {
 	 * Url to start the setup process. Now redirects to the wizard page.
 	 */
 	// TODO: Proper url needed for setup process.
-	const NOTE_SETUP_URL = 'admin.php?page=wc-admin&task=woocommerce-payments--multi-currency-setup';
+	const NOTE_SETUP_URL = 'admin.php?page=wc-admin&path=/payments/multi-currency-available';
```
[the remark this answers is not in the document]
Comment (a-danae) [reply includes/multi-currency/Notes/NoteMultiCurrencyAvailable.php]: I think I mistakenly followed the `NOTE_NAME` defined [above](https://github.com/Automattic/woocommerce-payments/pull/3436/files/d8df91a991a8ac0a11bc98727157215d83d1cd11#diff-f8ba4a7821e5ea4491b18fd1db1a1fa2a7784545e7f0f313a8cad84622e7524eR23) as I don't really recall any reasoning behind this change. Updated now!

File: client/multi-currency-setup/test/index.js (hunk 1 above)
Comment (a-danae) [reply client/multi-currency-setup/test/index.js]: Agreed and updated. I'm wondering if we should keep this test at all since it's only testing whether the content of the page is rendering, tho. What do you think?

Comment (chickenn00dle) [reply client/multi-currency-setup/test/index.js]: Good question. I also was wondering about the need for this test. In the end, I suppose testing that the page renders the expected test is still useful, so I would say to keep it.

**Review by chickenn00dle — APPROVED** [review]
Thanks for addressing my feedback @a-danae!

This looks good to go now 👍

**Comment by a-danae** [comment]
Thank you for the feedback @chickenn00dle 🙌 

Changelog entry updated in both changelog.txt and readme.txt, and merging now.
