### PR TITLE
Settings: fix saving settings when enabled payment methods setting contains faulty data

### LINKED ISSUE #4847: Some Users Unable to Save Settings Due to Console Error Related to APMs
### Describe the bug
Some [WooCommerce Payments](https://woocommerce.com/products/woocommerce-payments/?aff=10486&cid=1131038) merchants are unable to save their settings at **Payments > Settings**. When they attempt to, they see an `Error Saving Settings` pop-up, and the following error appears in console:

```
{
  "code": "rest_invalid_param",
  "message": "Invalid parameter(s): enabled_payment_method_ids",
  "data": {
    "status": 400,
    "params": {
      "enabled_payment_method_ids": "enabled_payment_method_ids[1] is not one of card, bancontact, eps, giropay, ideal, sofort, sepa_debit, and p24."
    },
    "details": {
      "enabled_payment_method_ids": {
        "code": "rest_not_in_enum",
        "message": "enabled_payment_method_ids[1] is not one of card, bancontact, eps, giropay, ideal, sofort, sepa_debit, and p24.",
        "data": null
      }
    }
  }
}
```

Only merchants utilizing UPE are affected.

### To Reproduce
We've been unable to reproduce this so far.

### Workaround
Disabling UPE and re-enabling again fixes the issue.

### Additional context
Affected merchants so far:

- 5607423-zen
- 5607722-zen
- 5608298-zen
- 5608374-zen

### PR DESCRIPTION
**Pull request by kalessil**
Fixes #4847 

#### Changes proposed in this Pull Request

* When loading the settings page ( `Payments > Settings` ), attempt to repair any potentially corrupted state of the enabled payment method setting.
* Example situation - There were instances of non-US merchants seeing `Error Saving`, since there was `link` appearing as a payment method in their Enabled Payment Methods array

#### Testing instructions

* Enable a US WC Pay account on your test site
* Within `Payment > Settings`, enable `Link by Stripe`, and save settings
* Switch the site to a non-US WC Pay account
* Purge the account cache via WCPay Dev plugin settings to make sure the non-us account takes full effect on the site
* Browse to `Payment > Settings` and click the `Save changes` button at the bottom
* You should no longer see any errors. You should see `Settings Saved.` message. 

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile - Not applicable

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: changelog/fix-4847-saving-settings-when-enabled-pm-setting-faulty [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Repair a potentially corrupted state of enabled payment method settings, that causes an error while saving settings. Example - A frequently reported issue of `Link` payment method appearing in enabled payment methods array of non-us clients leading to error while trying to save.
```
Comment (kalessil) [inline changelog/fix-4847-saving-settings-when-enabled-pm-setting-faulty]: We should make this entry shorter. I'd kee the first sentence only,

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php [hunk 2]
```diff
@@ -200,7 +200,18 @@ public function test_get_settings_returns_available_payment_method_ids() {
 		$enabled_method_ids = $response->get_data()['available_payment_method_ids'];
 
 		$this->assertEquals(
-			[ 'card', 'au_becs_debit', 'bancontact', 'eps', 'giropay', 'ideal', 'sofort', 'sepa_debit', 'p24', 'link' ],
+			[
+				'card',
```
Comment (kalessil) [inline tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: Nice! Can we use constants from `\WCPay\Constants\Payment_Method` here, please?

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php [hunk 3]
```diff
@@ -255,6 +266,30 @@ public function test_get_settings_fails_if_user_cannot_manage_woocommerce() {
 		remove_filter( 'user_has_cap', $cb );
 	}
 
+	public function test_get_settings_without_error_when_faulty_enabled_payment_methods() {
+		$this->upe_gateway->update_option(
+			'upe_available_payment_method_ids',
+			[
+				'card',
```
Comment (kalessil) [inline tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: Also constant from `\WCPay\Constants\Payment_Method`.

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php [hunk 4]
```diff
@@ -255,6 +266,30 @@ public function test_get_settings_fails_if_user_cannot_manage_woocommerce() {
...
+				'giropay',
+				'ideal',
+				'sofort',
+				'sepa_debit',
+				'p24',
+			]
+		);
+
+		$request = new WP_REST_Request();
+		$request->set_param( 'enabled_payment_method_ids', [ 'card', 'link' ] );
```
Comment (kalessil) [inline tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: Also constants.

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php [hunk 5]
```diff
@@ -255,6 +266,30 @@ public function test_get_settings_fails_if_user_cannot_manage_woocommerce() {
...
+
+		$response = $this->upe_controller->get_settings( $request );
+
+		$this->assertEquals( [ 'card' ], $response->get_data()['enabled_payment_method_ids'] );
```
Comment (kalessil) [inline tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: Also constant + let's use `assertSame` instead of `assertEquals`. It's more strict towards types.

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php [hunk 6]
```diff
@@ -255,6 +266,30 @@ public function test_get_settings_fails_if_user_cannot_manage_woocommerce() {
 		remove_filter( 'user_has_cap', $cb );
 	}
 
+	public function test_get_settings_without_error_when_faulty_enabled_payment_methods() {
+		$this->upe_gateway->update_option(
+			'upe_available_payment_method_ids',
```
Comment (kalessil) [inline tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: Is this option the correct one?

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php [hunk 7]
```diff
@@ -313,6 +348,7 @@ public function test_update_settings_saves_enabled_payment_methods() {
 		$this->assertEquals( [ 'card', 'giropay' ], $this->upe_gateway->get_option( 'upe_enabled_payment_method_ids' ) );
 	}
 
+
```
Comment (kalessil) [inline tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: Do we need this empty line?

**Review by kalessil — COMMENTED** [review]
THanks for pushing this forward @nagpai! Left my feedback.

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php (hunk 3 above)
Comment (nagpai) [reply tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: Thank you for drawing my attention to this! I have changed all strings in files in our PR to use these constants. I have created a [separate ticket](https://github.com/Automattic/woocommerce-payments/issues/5409) to change this across the codebase. I will pick that up during free time!

Comment (kalessil) [reply tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: Sounds good! Marking comments about constants as resolved.

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php (hunk 6 above)
Comment (nagpai) [reply tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: Thanks for pointing this out. It may have happened while I referred to an earlier test. I understand now that we are wanting to test the `gateway` and not just `upe_gateway` response. I have changed this to use `gateway`. I hope this is fine now. 

[b547683](https://github.com/Automattic/woocommerce-payments/pull/5388/commits/b547683f01d8588a4ba746b89ac1b3b90ec92fb6)

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php (hunk 5 above)
Comment (nagpai) [reply tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: I have changed this 👍 . Thanks for sharing!

File: changelog/fix-4847-saving-settings-when-enabled-pm-setting-faulty (hunk 1 above)
Comment (nagpai) [reply changelog/fix-4847-saving-settings-when-enabled-pm-setting-faulty]: Done! Cropped to just the first sentence. . Marking as resolved.

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php [hunk 8]
```diff
@@ -255,10 +267,34 @@ public function test_get_settings_fails_if_user_cannot_manage_woocommerce() {
 		remove_filter( 'user_has_cap', $cb );
 	}
 
+	public function test_get_settings_without_error_when_faulty_enabled_payment_methods() {
+		$this->gateway->update_option(
+			'available_payment_method_ids',
+			[
+				Payment_Method::CARD,
```
Comment (kalessil) [inline tests/unit/admin/test-class-wc-rest-payments-settings-controller.php:274]: I know other tests are not following my feedback, but I suggest keeping only `card` and `sepa` here - other methods are not making sense in the context of this test case. When I'm reading it I'm not getting why all of those are saved - reducing the list will help the reader to understand the intention much easier.

File: includes/constants/class-payment-method.php [hunk 9]
```diff
@@ -20,13 +20,19 @@
  * @psalm-immutable
  */
 class Payment_Method extends Enum {
+	const BANCONTACT      = 'bancontact';
```
Comment (kalessil) [inline includes/constants/class-payment-method.php:23]: Nice, thank you!

**Review by kalessil — COMMENTED** [review]
Thanks for making changes @nagpai! I left a couple more comments.

PS: to move forward, please approve the PR and ask other folks from Pulsar to make one more review/testing round. I can not approve the PR as I've authored it.

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php (hunk 6 above)
Comment (nagpai) [reply tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: @kalessil Just to confirm, may I mark this as resolved? This is among my first tests and hence want to be safe :)). Thanks.

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php (hunk 5 above)
Comment (nagpai) [reply tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: Marking as resolved.

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php (hunk 6 above)
Comment (kalessil) [reply tests/unit/admin/test-class-wc-rest-payments-settings-controller.php]: Sure!

File: tests/unit/admin/test-class-wc-rest-payments-settings-controller.php (hunk 8 above)
Comment (nagpai) [reply tests/unit/admin/test-class-wc-rest-payments-settings-controller.php:274]: That makes sense. For the original one, I had taken a clue from another test, and to mock a common situation where most PM's ( excluding Link ) are enabled. But now that I think, they are not all needed, except one additional method other than card. Thanks. 

Made the change here - 88cc6c1

Marking as resolved.

**Review by nagpai — APPROVED** [review]
Approving based on @kalessil 's feedback and approval. The PR was started originally by him, and worked upon by me subsequently.

**Review by mgascam — APPROVED** [review]
LGTM!

✅ Followed the manual testing instructions and works as expected
