### PR TITLE
Move Promise instantiation into memoized function to ensure caching consistency

### LINKED ISSUE #9851: Dynamic toggling of payment methods fails in Blocks checkout after country change
### Describe the bug
With Blocks checkout, when opening the page, the correct list of payment methods is presented on the page to be selected from. However, upon changing the country, there should be dynamical toggling of certain payment methods depending on their availability in certain countries. This is not happening in Blocks, while still happening in shortcode checkout.

* Enable Bancontact as a payment method.
* Go to the shortcode checkout page.
* Select a country that does not support Bancontact.
    * Expected Behavior: Bancontact should not appear in the list of payment methods.
* Change the country to one that supports Bancontact.
    * Expected Behavior: Bancontact should appear in the list of payment methods. 

Confirm that the last expected behavior is not met. 

### Additional context
This functionality worked before `8.1.0`

### PR DESCRIPTION
**Pull request by timur27**
Fixes https://github.com/Automattic/woocommerce-payments/issues/9851

#### Changes proposed in this Pull Request
It was discovered that for some reason, `canMakePayment` for payment methods (non-express checkout payment methods) is executed only upon page load, but not executed on subsequent actions like e.g. billing country update. This applies to Blocks checkout only. 

The side effect ended up to be in the `canMakePayment`'s [callback implementation for express checkout methods](https://github.com/Automattic/woocommerce-payments/blob/develop/client/express-checkout/utils/checkPaymentMethodIsAvailable.js#L16). There are two aspects worth mentioning:

1️⃣  WooCommerce Blocks [takes all the registered payment methods](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/data/payment/utils/check-payment-methods.ts#L157-L159) and then [calls `canMakePayment`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/data/payment/utils/check-payment-methods.ts#L223) on each of those. Typically, express checkout payment methods are evaluated first due to the default registration order, unless explicitly configured otherwise.

2️⃣  The `canMakePayment`'s [callback implementation for express checkout methods](https://github.com/Automattic/woocommerce-payments/blob/develop/client/express-checkout/utils/checkPaymentMethodIsAvailable.js#L16) uses `memoize`, which caches the resolved result (a boolean) from the first execution. Subsequent calls to this function return the cached boolean instead of a promise with some resolution state, leaving promises unresolved in those cases. This behavior caused [the promises](https://github.com/Automattic/woocommerce-payments/blob/develop/client/express-checkout/blocks/index.js#L42-L44) to remain unhandled, as the cache bypassed the promise resolution logic.

This PR resolves the issue by caching the promise itself instead of its resolved value. Previously, memoize cached the resolved boolean, causing subsequent calls to bypass the promise logic. Now, the memoized function returns and caches the promise, ensuring that subsequent calls return the cached resolved promise which is handled by Blocks.

#### Testing instructions

For Blocks checkout

* check on `develop` that dynamical filtering upon billing country change is not working
* check out `fix/unhandled-promises` and make sure that dynamical filtering of payment methods works 
    * enable e.g. Klarna
    * while opening the page, confirm this payment method is visible or invisible (depending on the country selected) 
    * switch the country and confirm Klarna is appearing and disappearing as expected depending on the country
* confirm that the testing requirements from https://github.com/Automattic/woocommerce-payments/pull/9378 are still met

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9927` or branch name `fix/unhandled-promises` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/unhandled-promises) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 89f30b7ecd978c772b3fc054dd5b804513c61042
- Build time: 2024-12-17 08:27:50 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js [hunk 1]
```diff
@@ -14,71 +14,75 @@ import WCPayAPI from 'wcpay/checkout/api';
 import { getUPEConfig } from 'wcpay/utils/checkout';
 
 export const checkPaymentMethodIsAvailable = memoize(
-	( paymentMethod, cart, resolve ) => {
-		// Create the DIV container on the fly
-		const containerEl = document.createElement( 'div' );
+	( paymentMethod, cart ) => {
+		return new Promise( ( resolve ) => {
```
Comment (asumaran) [inline client/express-checkout/utils/checkPaymentMethodIsAvailable.js:18]: I added the `memoize` to avoid running the verification against Stripe multiple times. But if doing so means we might introduce bugs, maybe it’s best to remove it?

Although your fix works well according to my tests, I see that the function wrapped by the promise doesn't get executed again after updating the cart. This isn’t an issue for now since ECE isn't enabled/disabled dynamically (as I know of), but it could become a problem in the future.

I think we can leave it as you’ve proposed in this PR for now, as it seems to be working well.

**Review by asumaran — APPROVED** [review]
LGTM.

- Tested with multiple payment methods enabled and can confirm they toggle based on the country. Also tested with the euro currency to verify euro-based payment methods.
- Tested that payment methods are hidden after applying a 100% discount coupon.
- Tested and confirmed that the fix for [woocommerce/woocommerce#50353](https://github.com/woocommerce/woocommerce/issues/50353) is still applied.

File: client/express-checkout/utils/checkPaymentMethodIsAvailable.js (hunk 1 above)
Comment (timur27) [reply client/express-checkout/utils/checkPaymentMethodIsAvailable.js:18]: This is a good point. I was looking at it but haven't included it into this PR. I think that caching itself is a pretty nice addition because otherwise, like you're mentioning, we will be making unnecessary third-party Stripe requests too often.

There is indeed a potential issue because at the moment, `memoize` uses the entire `cart` object for cache key generation, which doesn't work well for object comparison and could lead to improper cache hits/misses.

By making the cache key more specific with only the relevant fields that affect the payment method availability:

```js
export const checkPaymentMethodIsAvailable = memoize(
	( paymentMethod, cart ) => {...},
	( paymentMethod, cart ) => {
		return JSON.stringify({
			paymentMethod,
			total_price: cart.cartTotals.total_price,
			country: cart.billingAddress?.country
		});
	}
);
```

we will ensure it runs on some specific updates. But for this, we'd need to know what fields are relevant in our context, e.g. if billing country change should trigger reviewing ece availability. I think we can open a follow up issue, if we consider this worth diving into further.

**Review by mdmoore — APPROVED** [review]
@timur27 Thanks for your help in testing this! Everything is testing well and payment methods are dynamically filtering again. 🚢
