### PR TITLE
Fix Shortcode Orders When Using WooPay Direct Checkout

### LINKED ISSUE #8628: Currency switcher doesn't work with shortcode checkout
## Describe the bug

After checking out with a specific currency using the shortcode checkout all future payments will be processed in that currency.

## To Reproduce

1. Make sure you have multi-currency enabled and at least 2 currencies available.
2. Add any product to your cart, go straight to the shortcode checkout, and pay for the order. Take note of the currency in use, we'll call it `currency A`.
3. Use the currency switcher to change the currency to another currency, `currency B`.
4. Add any product to your cart and go straight to the shortcode checkout.
5. Note that all amounts are correctly displayed in `currency B`.
6. Click **Place Order** to process the payment.
7. Note that all amounts on the **Order Received** screen are in `currency A`.
8. Note that **My Account &rarr; Orders &rarr; View Order** shows amounts in `currency A`.
9. Note that the transactions list on the merchant side shows amounts in `currency A`.

(7), (8), and (9) show that the order was processed in `currency A`. Just noting explicitly that this is not a _presentation issue_, but a _payment processing issue_.

## Actual behavior

The order is processed in `currency A` even though `currency B` has been selected via the currency switcher.

### Screenshots

> [!NOTE]
> You can ignore the rounding issue in the order total when the currency in the video is changed to `ISK`, that's a separate issue reported in #8267.

https://github.com/Automattic/woocommerce-payments/assets/13835680/bdeb8826-455a-4600-a7a7-d341d8c060f1

## Expected behavior

The order is processed using the currency currently selected in the currency switcher, in the test case that's `currency B`.

## Additional context

* Discovery and discussion: p1712876616528389-slack-C01BZUL57SQ

We've been able to determine that this was introduced in #8267 and removing the `woocommerce_create_order` filter here fixes the issue:

https://github.com/Automattic/woocommerce-payments/blob/6483d9a5b34ceab5215a09e89949a89e89127596/includes/class-wc-payments-woopay-direct-checkout.php#L22-L47

That said @lovo-h and I think it's possible this is an issue in the multi-currency implementation or the currency switcher, rather than being caused by the filter. Some exploration is needed to determine what is the root cause here.

### LINKED ISSUE #8775: WooPay's "Checkout as guest" flow removes customer-provided details from order if Direct Checkout is enabled and shortcode checkout is in use
### Describe the bug

If a guest user navigates to a WooPay surface and then selects the `Checkout as guest` option, they will be sent to the site's hosted checkout page.

When this happens, if the guest customer then adds their email, billing, and shipping information to the checkout page, the information is not included on the order received page (as noted in #8774).

However, if Direct Checkout is enabled, then the resulting order will be missing almost all of the provided information.

### To Reproduce

1. Install and activate the Storefront theme on a WooPay-eligible site.
2. Use the `[woocommerce_checkout]` shortcode on the site's checkout page.
3. Enable Direct Checkout via the blog RC; see pdpOw2-4lp-p2#happiness for details
4. Ensure you are logged out of WooPay.
5. Initiate the WooPay flow as a guest (e.g., use an incognito window).
6. Select "Checkout as guest" once you're redirected to WooPay.
7. Complete the checkout process on the site's checkout page using an email that is not currently associated with a WooPay account.
8. Note that the billing and shipping information provided on the checkout page are not on the order received page.
9. Edit the order from wp-admin.
10. Note that billing, shipping, and email address are missing.

### Actual behavior

Customer-provided information is not on included in the order.

### Screenshots

CleanShot 2024-05-03 at 16 13 37@2x

### Expected behavior

Information provided on the shortcode checkout page is accurately reflected on the order, including:
- Email address
- Billing address
- Shipping address

### Additional context

p1714725467619139-slack-C3NCP7ZJ6

### PR DESCRIPTION
**Pull request by lovo-h**
Fixes #8775 
Fixes #8628 

#### Changes proposed in this Pull Request

The changes in this PR ensure that when we reuse a draft order, it is updated with all necessary details (address, currency, etc.). 

Previously, when a draft order was created through the Direct Checkout flow, it was re-used to avoid a "stock: 1" bug (see https://github.com/Automattic/woocommerce-payments/issues/7256 for details). However, when reusing the draft order, the order did not include all the necessary information. 

Now, when a draft order is created through the Direct Checkout flow, it will still be re-used to avoid the "stock: 1" bug but the order will also be marked as "pending" so that it gets updated (as it normally would) during checkout.

#### Testing instructions

**Confirm issue: Shortcode orders are missing address**
* Switch over to the `develop` branch.
* Confirm the issue is reproducible when following the steps outlined in #8775.

**Confirm solution: Shortcode orders are not missing address**
* Switch over to this branch: `fix/8775-direct-checkout-shortcode-orders`.
* Confirm the issue is not reproducible when following the steps outlined in #8775.

**Confirm issue: Currency switcher doesn't work with shortcode checkout**
* Switch over to the `develop` branch.
* Confirm the issue is reproducible when following the steps outlined in #8628.

**Confirm solution: Currency switcher works with shortcode checkout**
* Switch over to this branch: `fix/8775-direct-checkout-shortcode-orders`.
* Confirm the issue is not reproducible when following the steps outlined in #8628.

**Regression Test: Ensure Purchasing a Product With 1 Stock Does Not Fail** (see #7256 for details)
* Ensure the WooPay Direct Checkout flow is enabled.
* Create an item with only 1 stock and run the following test scenarios (you will have to update the stock back to 1 after each test):
    * Use the WooPay button from the cart page and pay through the WooPay checkout.
    * Navigate to the cart page before going to the Merchant checkout and pay through the Merchant checkout (make sure not to type a valid WooPay address in the email field).
    * Navigate to the cart page before navigating to the Merchant checkout and pay through the WooPay Button.
    * Navigate to the cart page before navigating to the Merchant checkout and pay using the WooPay email input.
    * Navigate directly to the Merchant checkout and pay through the Merchant checkout (make sure not to type a valid woopay address in the email field).
    * Navigate directly to the Merchant checkout and pay through the WooPay button.
    * Navigate directly to the Merchant checkout and pay through the WooPay email input.
* Repeat these tests for both the shortcode cart/checkout and, optionally, the wcBlocks cart/checkout.
* As a merchant, ensure the address appears on each order, in the admin dashboard.
* As a merchant, ensure the address appears on each order, in Stripe.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8802` or branch name `fix/8775-direct-checkout-shortcode-orders` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8775-direct-checkout-shortcode-orders) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 81b7dd307c78c0763c45fcb5fb39ce25efc20e6c
- Build time: 2024-05-10 18:37:11 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by lovo-h** [comment]
@reykjalin, I made a minor change to fully address the following issue:
* #8628

[The change](https://github.com/Automattic/woocommerce-payments/pull/8802/commits/fdc538f53a394e015f2859913757499c6d9b80ab) ensures that an order is considered to be in one single state (either "draft" or "pending payment") in the current session.

File: includes/class-wc-payments-woopay-direct-checkout.php [hunk 1]
```diff
@@ -39,11 +42,23 @@ public function maybe_use_store_api_draft_order_id( $order_id ) {
 		$is_already_defined_order_id = ! empty( $order_id );
 		// Only apply this filter if the session doesn't already have an order_awaiting_payment.
 		$is_order_awaiting_payment = isset( WC()->session->order_awaiting_payment );
-		if ( ! $is_checkout || $is_already_defined_order_id || $is_order_awaiting_payment ) {
+		// Only apply this filter if draft order ID exists.
+		$is_draft_order_exists = ! empty( WC()->session->get( 'store_api_draft_order' ) );
+		if ( ! $is_checkout || $is_already_defined_order_id || $is_order_awaiting_payment || ! $is_draft_order_exists ) {
```
Comment (reykjalin) [inline includes/class-wc-payments-woopay-direct-checkout.php]: > [!NOTE]
> This is a nitpick.

Can we call this variable either `$does_draft_order_exist` or `$has_draft_order`? The `is` at the start here makes it a bit weird to read 😅 

```suggestion
		$does_draft_order_exist = ! empty( WC()->session->get( 'store_api_draft_order' ) );
		if ( ! $is_checkout || $is_already_defined_order_id || $is_order_awaiting_payment || ! $does_draft_order_exist ) {
```

```suggestion
		$has_draft_order = ! empty( WC()->session->get( 'store_api_draft_order' ) );
		if ( ! $is_checkout || $is_already_defined_order_id || $is_order_awaiting_payment || ! $has_draft_order ) {
```

**Review by reykjalin — CHANGES_REQUESTED** [review]
Looks great and all the tests pass 💯 

Had one small nitpick, but otherwise this is looking fiiiine 👌

**Review by reykjalin — APPROVED** [review]
