### PR TITLE
Apply localization to CSV exports sent via email.

### LINKED ISSUE #7843: CSVs are not localized if sent via email
### Describe the bug

When CSVs for deposits, transactions, and disputes are small enough to be downloaded directly from wp-admin, the language in the CSV will match the site's language if it is set to something that is not English. 

However, if a site's language is set to something other than English and a CSV is large enough that it is sent to the user via email, the resulting CSV is in English regardless of the site's language.

### To Reproduce

1. Ensure the site language is set to a non-English language (e.g., Español).
2. Isolate a small dataset of deposits, transactions, or disputes.
3. Download a CSV of the information.
4. Note that the details are localized (e.g., headings and statuses are in the site language as expected).
5. Expand the dataset from step 2 (or find a new dataset) so that it is too large for downloading from wp-admin.
6. Repeat step 3.
7. Check your email.
8. Download the CSV.
9. Note that the CSV is not localized (e.g., headings and statuses are **not** in the site language).

### Actual behavior

When downloading larger datasets as a CSV, the information is not localized. This creates a lack of parity in the experience when downloading smaller datasets directly from wp-admin. This also negatively affects merchants who primarily use non-English languages when generating or managing reports.

### Screenshots

Localized, small CSV downloaded directly from wp-admin with a site language of `Español`:

localized csv

Larger CSV from the same `Español` site that is emailed and is not localized:

non-localized csv

### Expected behavior

Localization behavior that affects CSV files persists regardless of how the CSV is delivered.

### PR DESCRIPTION
**Pull request by mordeth**
Fixes #7843

#### Changes proposed in this Pull Request
This pull request implements the localization of Transactions, Disputes, and Deposits for extensive CSV exports when they are sent to the merchant via email.

Screenshot 2023-12-22 at 20 19 38

Screenshot 2023-12-22 at 20 19 25

Screenshot 2023-12-22 at 20 19 11

Newly introduced export language modal.

Screenshot 2024-02-06 at 15 36 48

### Testing instructions

https://github.com/Automattic/woocommerce-payments/assets/8667118/3b57aaab-ab58-4f95-8134-ebfb2a765421

**Change site language**
- Navigate to Settings -> General and change the site language to Spanish.
- Go to Dashboard -> Updates.
- Navigate to the bottom and click `Update languages` button.

**Language export settings**
_To access the export language settings in Payments -> Settings, we must initially set a language other than English._

- Go to `Payments` -> `Settings`.
- Scroll down to the `Reporting` section.
- Confirm that the export language selection box is displayed.

#### Transactions
- Confirm that you have over 25 transactions to trigger the email export.
- Go to Payments -> Transactions.

**Case 1**
- Click the Download button on the top right corner of the table.
- A modal will be displayed prompting to select the download language.
- Uncheck the `Remember the language settings` checkbox.
- Select `Site language -> Spanish` and click download.
- Download the emailed export.
- Verify that the CSV export is in Spanish.

**Case 2**
- Click the Download button on the top right corner of the table.
- A modal will be displayed prompting to select the download language.
- Check the `Remember the language settings` checkbox.
- Select `Site language -> English` and click download.
- Download the emailed export.
- Verify that the CSV export is in English.

**Case 3**
- Click the Download button on the top right corner of the table.
- A modal shouldn't be displayed and the list will be exported in English automatically.
- Download the emailed export.
- Verify that the CSV export is in English.

**Case 4**
- Navigate to `Payments` -> `Settings`.
- Scroll down to `Reporting` section.
- Verify that the dropdown is update to `English`.

#### Deposits
- Confirm that you have over 25 deposits to trigger the email export.
- Go to Payments -> Deposits.

**Case 1**
- Click the Download button on the top right corner of the table.
- A modal will be displayed prompting to select the download language.
- Uncheck the `Remember the language settings` checkbox.
- Select `Site language -> Spanish` and click download.
- Download the emailed export.
- Verify that the CSV export is in Spanish.

**Case 2**
- Click the Download button on the top right corner of the table.
- A modal will be displayed prompting to select the download language.
- Check the `Remember the language settings` checkbox.
- Select `Site language -> English` and click download.
- Download the emailed export.
- Verify that the CSV export is in English.

**Case 3**
- Click the Download button on the top right corner of the table.
- A modal shouldn't be displayed and the list will be exported in English automatically.
- Download the emailed export.
- Verify that the CSV export is in English.

**Case 4**
- Navigate to `Payments` -> `Settings`.
- Scroll down to `Reporting` section.
- Verify that the dropdown is update to `English`.

#### Disputes
- Confirm that you have over 25 disputes to trigger the email export.
- Go to Payments -> Disputes.

**Case 1**
- Click the Download button on the top right corner of the table.
- A modal will be displayed prompting to select the download language.
- Uncheck the `Remember the language settings` checkbox.
- Select `Site language -> Spanish` and click download.
- Download the emailed export.
- Verify that the CSV export is in Spanish.

**Case 2**
- Click the Download button on the top right corner of the table.
- A modal will be displayed prompting to select the download language.
- Check the `Remember the language settings` checkbox.
- Select `Site language -> English` and click download.
- Download the emailed export.
- Verify that the CSV export is in English.

**Case 3**
- Click the Download button on the top right corner of the table.
- A modal shouldn't be displayed and the list will be exported in English automatically.
- Download the emailed export.
- Verify that the CSV export is in English.

**Case 4**
- Navigate to `Payments` -> `Settings`.
- Scroll down to `Reporting` section.
- Verify that the dropdown is update to `English`.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7938` or branch name `add/7843-localize-exports` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/7843-localize-exports) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: d866b1fee7e8ebe1770929a570cfec0ae7302c03
- Build time: 2024-02-08 12:04:11 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/deposits/list/index.tsx [hunk 1]
```diff
@@ -213,6 +213,7 @@ export const DepositsList = (): JSX.Element => {
 		setIsDownloading( true );
 		const downloadType = totalRows > rows.length ? 'endpoint' : 'browser';
 		const userEmail = wcpaySettings.currentUserEmail;
+		const locale = wcpaySettings.locale;
```
Comment (deepakpathania) [inline client/deposits/list/index.tsx]: Just passing by and had some questions:
- Should we give the merchants the choice to toggle this functionality somehow? It would be unexpected for merchants with a different site language to start getting their reports in a different language without any change on their side. So this should be an opt-in IMO.
- When localization is enabled, should we just translate the CSV headers? I believe the email body should also be translated in that case.
- Finally, how do we ensure that the translations in all the languages that we support as site languages work well for these headers? Should there be a whitelist or do we know that these would all be ok?

**Review by deepakpathania — COMMENTED** [review]
Noticed this PR and left a few thoughts, feel free to ignore if these are already discussed somewhere and I lack context. 👋

File: changelog/add-7843-localize-exports [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
+Type: add
+
+Apply localization to CSV exports sent via email.
```
Comment (anu-rock) [inline changelog/add-7843-localize-exports]:
```suggestion
Apply localization to CSV exports for transactions, deposits, and disputes sent via email.
```

**Review by anu-rock — APPROVED** [review]
LGTM 🎉 I've separately reviewed the server PR in detail.

File: client/deposits/list/index.tsx (hunk 1 above)
Comment (anu-rock) [reply client/deposits/list/index.tsx]: All very good questions.

> Should we give the merchants the choice to toggle this functionality somehow? It would be unexpected for merchants with a different site language to start getting their reports in a different language without any change on their side. So this should be an opt-in IMO.

I think that's a fair observation. Our changes will default all merchants to CSV reports in their site language whether they want it or not. It's not unreasonable to imagine a set of merchants that are happy receiving the reports in English irrespective of their site language.

One way to fix this is to keep the locale for reports as English and add a checkbox on WooPayments page to let merchants optionally receive CSVs in the site language.

Copying @souravdebnath1986 and @rogermattic for their expert thoughts on this discussion.

> When localization is enabled, should we just translate the CSV headers? I believe the email body should also be translated in that case.

I had this exact thought. I also believe we should apply localization to emails too. But I'm not sure if doing so would be within the scope of this issue. IMO, it depends on whether it's just the download report email or even the other email templates that are currently not localized. In the latter case, it'd be a separate project-like effort. Nevertheless, you've brought up a good point.

> Finally, how do we ensure that the translations in all the languages that we support as site languages work well for these headers? Should there be a whitelist or do we know that these would all be ok?

From what I know, the translations are a community effort and there's no way to be sure about 100% coverage of all strings in WooPayments. The good news is that all the top languages are 98% or more translated.

https://translate.wordpress.com/projects/woocommerce/woocommerce-payments

Comment (deepakpathania) [reply client/deposits/list/index.tsx]: Thanks for the quick response, I trust that you can take the conversation forward but happy to assist in case any assistance is needed from our end (I worked on the initial CSV export a bit so have some context).

Comment (mordeth) [reply client/deposits/list/index.tsx]: Great questions!

>Should we give the merchants the choice to toggle this functionality somehow? It would be unexpected for merchants with a different site language to start getting their reports in a different language without any change on their side. So this should be an opt-in IMO.

The existing functionality for CSV exports from the client consistently translates content to the site language when the total rows are fewer than the page size. To maintain uniform behavior, it is advisable to extend this translation requirement to server exports. Considering that the site is already translated, selecting an export language for client exports may not be possible.

If the goal is to introduce the language option exclusively for server exports, a user-friendly approach could be converting the Download button into a dropdown. This dropdown can then present two buttons: 'Export in English' and 'Export in site language.' 

>When localization is enabled, should we just translate the CSV headers? I believe the email body should also be translated in that case.

In alignment with Anurag's statement, I believe that translating the email content should not be considered as part of the current issue.

Comment (rogermattic) [reply client/deposits/list/index.tsx]: Hey! Thanks for pinging me here :) 

I agree with @anu-rock:

> 
>  It's not unreasonable to imagine a set of merchants that are happy receiving the reports in English irrespective of their site language. 
>  One way to fix this is to keep the locale for reports as English and add a checkbox on WooPayments page to let merchants optionally receive CSVs in the site language.

We can add this to our Payments settings.  

> If the goal is to introduce the language option exclusively for server exports, a user-friendly approach could be converting the Download button into a dropdown. This dropdown can then present two buttons: 'Export in English' and 'Export in site language.'

@mordeth I think this could be a nice approach but it might be a bit annoying for the user if they need to select an option each time they click **Download** (which should be a quick, direct action). 
However, this might work well for the first time download. We could display a popup with two language options and a note `Don't worry you can always change it later in settings`. In this way we can _kill two birds with one stone_, making sure that user downloads the file in the language they wanted and knows where to change it if they need to.

**Review by dpaun1985 — APPROVED** [review]
✅  LGTM
Code changes looks good.
Manually tested and works as expected

File: changelog/add-7843-localize-exports (hunk 2 above)
Comment (mordeth) [reply changelog/add-7843-localize-exports]: Updated, thank you!

File: client/deposits/list/index.tsx (hunk 1 above)
Comment (rogermattic) [reply client/deposits/list/index.tsx]: So this is how we can do it:

When the user clicks on the Download button, we will show this popup:
Screenshot 2024-01-09 at 16 52 28


And then we should also add this to our Payments Settings:
Screenshot 2024-01-09 at 16 52 38

Please feel free to let me know your feedback!

**Comment by mordeth** [comment]
@anu-rock @dpaun1985 I've integrated the new modal and language settings based on @rogermattic's designs. Could you please review the changes once more? 🙇

File: client/components/csv-export-modal/index.tsx [hunk 3]
```diff
@@ -0,0 +1,240 @@
...
+ */
+import { ReportingExportLanguageHook } from 'wcpay/settings/reporting-settings/interfaces';
+import { useReportingExportLanguage, useSettings } from 'wcpay/data';
+import ConfirmationModal from 'wcpay/components/confirmation-modal';
+import { getAdminUrl } from 'wcpay/utils';
+import './styles.scss';
+
+interface CSVExportModalProps {
+	totalItems: number;
+	exportType: string;
```
Comment (anu-rock) [inline client/components/csv-export-modal/index.tsx]: Since there are only a small set of possible values for this field, should we make it explicit here? Eg.:

```typescript
exportType: 'transactions' | 'deposits' | 'disputes';
```

File: client/components/csv-export-modal/test/index.test.tsx [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+
+		global.wcpaySettings = {
+			locale: {
+				code: 'es_ES',
+				native_name: 'Spanish',
+			},
+		};
+	} );
+
+	test( 'it renders correctly', () => {
```
Comment (anu-rock) [inline client/components/csv-export-modal/test/index.test.tsx:59]: Does it also make sense to introduce tests for other behaviors of the modal such as the remember checkbox? Are there any other behaviors worth covering?

File: client/deposits/list/index.tsx [hunk 5]
```diff
@@ -209,50 +223,51 @@ export const DepositsList = (): JSX.Element => {
 
 	const downloadable = !! rows.length;
 
-	const onDownload = async () => {
-		setIsDownloading( true );
-		const downloadType = totalRows > rows.length ? 'endpoint' : 'browser';
+	const endpointExport = async ( language: string ) => {
+		// We destructure page and path to get the right params.
+		// eslint-disable-next-line @typescript-eslint/no-unused-vars
```
Comment (anu-rock) [inline client/deposits/list/index.tsx:220]: Why do we need to suppress the linter warning here?

File: client/settings/reporting-settings/components/export-language/index.tsx [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+import { SelectControl, ExternalLink } from '@wordpress/components';
+
+/**
+ * Internal dependencies
+ */
+import interpolateComponents from '@automattic/interpolate-components';
+import { ReportingExportLanguageHook } from '../../interfaces';
+import { useReportingExportLanguage } from 'wcpay/data';
+
+const ExportLanguage: React.FC = () => {
```
Comment (anu-rock) [inline client/settings/reporting-settings/components/export-language/index.tsx:17]: Random thought: The code here looks a bit like the language selector in the modal component. I was wondering if it's possible to reuse this component in the modal?

File: includes/admin/class-wc-rest-payments-settings-controller.php [hunk 7]
```diff
@@ -201,6 +201,10 @@ public function register_routes() {
 						'description' => __( 'Monthly anchor for deposit scheduling when interval is set to monthly', 'woocommerce-payments' ),
 						'type'        => [ 'integer', 'null' ],
 					],
+					'reporting_export_language'         => [
+						'description' => __( 'Transactions, deposits and disputes exporting language.', 'woocommerce-payments' ),
```
Comment (anu-rock) [inline includes/admin/class-wc-rest-payments-settings-controller.php]: WDYT about:

```suggestion
						'description' => __( 'The language for an exported report for transactions, deposits, or disputes.', 'woocommerce-payments' ),
```

File: includes/class-wc-payments-utils.php [hunk 8]
```diff
@@ -992,4 +992,31 @@ public static function enqueue_style( $handle, $path = '', $deps = [], $version
...
+	 * Returns language data: english name and native name
+	 *
+	 * @param string $language Language code.
+	 *
+	 * @return array
+	 */
+	public static function get_language_data( $language ) {
+		require_once ABSPATH . 'wp-admin/includes/translation-install.php';
+
+		$transaltions = wp_get_available_translations();
```
Comment (anu-rock) [inline includes/class-wc-payments-utils.php]: Nitpick: there's a typo in variable name.

File: includes/class-wc-payments-utils.php [hunk 9]
```diff
@@ -992,4 +992,31 @@ public static function enqueue_style( $handle, $path = '', $deps = [], $version
...
+
+		if ( isset( $transaltions[ $language ] ) ) {
+			return [
+				'code'         => $language,
+				'english_name' => $transaltions[ $language ]['english_name'] ?? '',
```
Comment (anu-rock) [inline includes/class-wc-payments-utils.php]: I was wondering if it's better to return the default values as fallbacks rather than empty strings.

**Review by anu-rock — COMMENTED** [review]
Code-only re-review: Great work related to the export modal implementation 🎉

IMO, the testing instructions should be revised now that we have a new modal in the equation. I'll be happy to manually re-test based on revised instructions.

File: client/components/csv-export-modal/index.tsx (hunk 3 above)
Comment (mordeth) [reply client/components/csv-export-modal/index.tsx]: Well spotted, indeed it's wise to explicitly clarify that.

File: client/deposits/list/index.tsx (hunk 5 above)
Comment (mordeth) [reply client/deposits/list/index.tsx:220]: It's a remnant from the previous method. Removed it.

File: includes/admin/class-wc-rest-payments-settings-controller.php (hunk 7 above)
Comment (mordeth) [reply includes/admin/class-wc-rest-payments-settings-controller.php]: Updated!

File: includes/class-wc-payments-utils.php (hunk 8 above)
Comment (mordeth) [reply includes/class-wc-payments-utils.php]: Good catch! Fixed.

File: includes/class-wc-payments-utils.php (hunk 9 above)
Comment (mordeth) [reply includes/class-wc-payments-utils.php]: It's completely logical. Yet, I believe it's more beneficial to return the `$language` instead of the default `English (United States)` to avoid any potential confusion among the merchants.

File: client/settings/reporting-settings/components/export-language/index.tsx (hunk 6 above)
Comment (mordeth) [reply client/settings/reporting-settings/components/export-language/index.tsx:17]: My initial plan was to do that, but it would require adding a good amount of extra code to reuse the component, which isn't practical. Instead, I've exported the options variable as a reusable constant that both components can share.

File: client/components/csv-export-modal/test/index.test.tsx (hunk 4 above)
Comment (mordeth) [reply client/components/csv-export-modal/test/index.test.tsx:59]: Regrettably, verifying behaviors isn't straightforward due to the modal's requirements. The checkbox and select updates are stored in a local state to maintain the original value, which complicates mocking the functions.

I think it's best to maintain the current implementation rather than complicating the code just for the sake of testing. WDYT?

Comment (anu-rock) [reply client/components/csv-export-modal/test/index.test.tsx:59]: Sure, that sounds like a sensible reason to limit our testing to just rendering/snapshot.

**Comment by mordeth** [comment]
@anu-rock @dpaun1985 @elazzabi Could you please manually test the modal again with the updated testing instructions? Thank you!

File: client/deposits/list/index.tsx [hunk 10]
```diff
@@ -217,7 +217,6 @@ export const DepositsList = (): JSX.Element => {
 
 	const endpointExport = async ( language: string ) => {
 		// We destructure page and path to get the right params.
-		// eslint-disable-next-line @typescript-eslint/no-unused-vars
```
Comment (anu-rock) [inline client/deposits/list/index.tsx]: Whoops! Looks like removing this linter suppression triggered a few warnings. Are these really unused variables and can be removed? Or they are used somewhere and we should restore the suppression?

File: client/disputes/index.tsx [hunk 11]
```diff
@@ -362,7 +362,6 @@ export const DisputesList = (): JSX.Element => {
 
 	const endpointExport = async ( language: string ) => {
 		// We destructure page and path to get the right params.
-		// eslint-disable-next-line @typescript-eslint/no-unused-vars
```
Comment (anu-rock) [inline client/disputes/index.tsx]: There are linter warnings here too.

File: client/transactions/list/index.tsx [hunk 12]
```diff
@@ -605,7 +605,6 @@ export const TransactionsList = (
 
 	const endpointExport = async ( language: string ) => {
 		// We destructure page and path to get the right params.
-		// eslint-disable-next-line @typescript-eslint/no-unused-vars
```
Comment (anu-rock) [inline client/transactions/list/index.tsx]: More linter warnings.

File: client/settings/reporting-settings/constants.ts [hunk 13]
```diff
@@ -0,0 +1,17 @@
+/**
+ * External dependencies
+ */
+import { __ } from '@wordpress/i18n';
+
+export const exportLanguageOptions = [
```
Comment (anu-rock) [inline client/settings/reporting-settings/constants.ts]: I wonder if it's really a constant since it has a few moving parts such as `wcpaySettings.locale.code`. Would it be better to export this array from a function, eg. `getExportLanguageOptions`?

**Review by anu-rock — COMMENTED** [review]
Thanks for addressing my feedback. The new changes mostly look good. I've left a few very minor comments. Happy to do a follow-up review/approval today if it makes sense to address them. Otherwise, LGTM ✅

File: client/deposits/list/index.tsx (hunk 10 above)
Comment (mordeth) [reply client/deposits/list/index.tsx]: I attempted to eliminate the params variable, but doing so resulted in other errors. It seems the suppression was originally included for a reason, so I re-added it.

File: client/disputes/index.tsx (hunk 11 above)
Comment (mordeth) [reply client/disputes/index.tsx]: Resolved.

File: client/transactions/list/index.tsx (hunk 12 above)
Comment (mordeth) [reply client/transactions/list/index.tsx]: Resolved.

File: client/settings/reporting-settings/constants.ts (hunk 13 above)
Comment (mordeth) [reply client/settings/reporting-settings/constants.ts]: I agree that it doesn't truly function as a constant, and it would be more appropriate to place it within a method in the utils.

**Comment by dpaun1985** [comment]
When attempting to download the report with the "remember language settings" option enabled, I encounter an error.  Is something that I did wrong ? 
Screenshot 2024-02-08 at 11 54 15

**Comment by mordeth** [comment]
>When attempting to download the report with the "remember language settings" option enabled, I encounter an error. Is something that I did wrong ?

No, everything is functioning properly. The reason is that the `updateOptions` method operates exclusively in the production environment.

File: client/transactions/list/index.tsx [hunk 14]
```diff
@@ -605,6 +605,7 @@ export const TransactionsList = (
 
 	const endpointExport = async ( language: string ) => {
 		// We destructure page and path to get the right params.
+		// eslint-disable-next-line @typescript-eslint/no-unused-vars
```
Comment (anu-rock) [inline client/transactions/list/index.tsx:608]: We might need to restore the linter suppression on line 717 as well.

File: client/utils/index.js [hunk 15]
```diff
@@ -212,3 +213,23 @@ export const getExportLanguage = ( language, storedLanguage ) => {
 	// When modal is dismissed use the default language locale.
 	return language !== '' ? language : defaultLanguage;
 };
+
+/**
+ * Returns the language options for CSV exports language selector.
+ *
+ * @return {Array} Language options.
+ */
+export const exportLanguageOptions = () => {
```
Comment (anu-rock) [inline client/utils/index.js]: The name of this method makes it appear that we are exporting language options here. WDYT about `getExportLanguageOptions`?

File: client/transactions/list/index.tsx (hunk 14 above)
Comment (mordeth) [reply client/transactions/list/index.tsx:608]: Great catch! Restored.

File: client/utils/index.js (hunk 15 above)
Comment (mordeth) [reply client/utils/index.js]: Adding the `get` prefix is indeed logical. It has been updated.

**Review by anu-rock — APPROVED** [review]
LGTM after the last changes 🎉

**Review by dpaun1985 — APPROVED** [review]
:shipit:  LGTM

**Comment by csmcneill** [comment]
I am unable to replicate the desired outcome (localized CSVs) with the options in the latest test build of WCPay. I mentioned this in p1707785105823299-slack-C06BBFTF6EM but I am noting it here as well.

**Comment by mordeth** [comment]
PR #8190 has been deployed to address the issue encountered by @csmcneill.
