### PR TITLE
Fix race conditions leading to duplicate order status transitions and invoice already paid errors

### LINKED ISSUE #3273: [GlobalStep] "400 Bad Request" error triggers at Query Monitor after placing the order when using new credit card.
# Bug Description:
"400 Bad Request" error triggers at Query Monitor after placing the order when using new credit card.

# Environment:
Woocommerce Version : WooCommerce 5.8.0 
WooCommerce Payments 3.3.0-test-1
WordPress version: v5.8.1

PC:
Windows 10, Mac 10.14.6
Chrome(Version 95.0.4638.69) 
Firefox(Version 93.0)
Safari: v14.1.2

# Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Upload and activate the WooCommerce Payments v3.3.0-test-1 plugin. 
1. Complete the setup wizard.
1. Go to Store page and add "subscription product" to the cart.
1. Complete the checkout using credit card.
1. Again go to Store page and "subscription product" product to the cart.
1. Go to checkout page.
1. This time click "use new payment method" and add new credit card.
1. And click on "Sign Up"
1. Observe that "400 Bad Request" error triggers at Query Monitor after placing the order when using new credit card.

# Actual Result:
"400 Bad Request" error triggers at Query Monitor after placing the order when using new credit card.

# Expected Result:
User should be able to complete checkout without any error.

# Screenshot

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
`
### WordPress Environment ###

WC Version: 5.8.0
REST API Version: ✔ 5.8.0
WC Blocks Version: ✔ 5.9.1
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.7.2
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.51 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.25
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.8.0
WC Database Prefix: wp_
Total Database Size: 7.09MB
Database Data Size: 5.15MB
Database Index Size: 1.94MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.45MB + Index: 0.48MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 35
page: 7
post: 2
product: 36
product_variation: 7
revision: 2
shop_coupon: 3
shop_order: 42
shop_order_refund: 1
shop_subscription: 37

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.7.1
Code Snippets: by Code Snippets Pro – 2.14.2
Companion Plugin: by Osk – 1.18
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Payments: by Automattic – 3.3.0-test-1
WooCommerce: by Automattic – 5.8.0

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.12
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Subscriptions: by WooCommerce – 3.1.6

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://magellanic-koi.jurassic.ninja
Subscription Statuses: wc-active: 34
wc-pending: 2
wc-cancelled: 1

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 34
wc-cancelled: 1
wc-pending: 2

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
tokenization
add_payment_method

### Action Scheduler ###

Complete: 267
Oldest: 2021-11-02 10:47:07 +0000
Newest: 2021-11-02 15:33:43 +0000

Pending: 39
Oldest: 2021-11-02 16:57:32 +0000
Newest: 2021-12-02 14:21:40 +0000

### Status report information ###

Generated at: 2021-11-02 15:36:53 +00:00

</details>

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #3273 

#### Changes proposed in this Pull Request

When processing a payment via the UPE there's a race condition whereby the `payment_intent.succeeded` webhook is received and handled by the site while the site is already in the process of handling the original payment request. 

Both requests get their own instance of the order object with a pending status and then attempt to complete the order (via `WC_Order->payment_complete()`).

You can find the two stack traces in my comment here: https://github.com/Automattic/woocommerce-payments/issues/3273#issuecomment-960413704

Because both requests complete the order (resulting in duplicate order notes), it also triggers two calls to the `woocommerce_order_payment_status_changed` action and the subsequent `WC_Payments_Invoice_Service::maybe_record_invoice_payment()` function. 

Calling `maybe_record_invoice_payment()` for the same order twice leads to us attempting to mark the subscription initial invoice as paid (out of band) twice and causes to the following 400 error.

```
"message": "Invoice is already paid",
"type": "invalid_request_error"
```

This PR fixes those issues.

**Questions/concerns**
In this PR I fix the race condition that was leading to the duplicate paid invoice, however as a fallback, if we attempt to pay an already paid invoice, instead of throwing the error and adding the order note, I catch that specific error on client side and log it. This means it's still theoretically possible that these "invoice is already paid" errors occur on server, although given they're 400 errors, they aren't logged to the Slack channel. What is your opinion on that? Should we do more to prevent those, or handle them better on the server? 

#### Testing Prereqs
- Listening to webhooks. `npm run listen` in your local server.
- UPE enabled.  
- WC Subscriptions plugin disabled.
- A plugin like Query Monitor to see HTTP request errors.

#### Testing instructions 
1. Purchase a subscription product using WC Pay and enter a new payment method on checkout.
2. On `develop` you'll notice the following errors:
   - On the order received page you should get a HTTP error (see below).
   - If you view the order in the admin dashboard you'll notice that there are 2 order notes suggesting the order transitioned from **Pending → Processing** twice. There's also a note about the invoice is already paid. See the screenshot below.
   - If you view the WC pay logs in **WooCommerce → Status → Logs** you'll also notice a `payment_intent not found in array in ...` error. I've included the full error below.
3. Repeating the purchase on this branch should resolve those issues. 

#### Screenshots
**HTTP API error**

Screen Shot 2021-11-04 at 4 05 27 pm

**Order notes**

Screen Shot 2021-11-04 at 4 09 58 pm

**`woocommerce-payments` log error**
```
ERROR WCPay\Exceptions\Rest_Request_Exception: payment_intent not found in array in wp-content/plugins/woocommerce-payments/includes/subscriptions/class-wc-payments-subscriptions-event-handler.php:197
Stack trace:
#0 wp-content/plugins/woocommerce-payments/includes/subscriptions/class-wc-payments-subscriptions-event-handler.php(97): WC_Payments_Subscriptions_Event_Handler->get_event_property(Array, 'payment_intent')
#1 wp-content/plugins/woocommerce-payments/includes/admin/class-wc-rest-payments-webhook-controller.php(137): WC_Payments_Subscriptions_Event_Handler->handle_invoice_paid(Array)
#2 wp-includes/rest-api/class-wp-rest-server.php(1140): WC_REST_Payments_Webhook_Controller->handle_webhook(Object(WP_REST_Request))
#3 wp-includes/rest-api/class-wp-rest-server.php(987): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc/v3/payments...', Array, NULL)
#4 wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dispatch(Object(WP_REST_Request))
#5 wp-includes/rest-api.php(370): WP_REST_Server->serve_request('/wc/v3/payments...')
#6 wp-includes/class-wp-hook.php(303): rest_api_loaded(Object(WP))
#7 wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#8 wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#9 wp-includes/class-wp.php(388): do_action_ref_array('parse_request', Array)
#10 wp-includes/class-wp.php(750): WP->parse_request('')
#11 wp-includes/functions.php(1291): WP->main('')
#12 wp-blog-header.php(16): wp()
#13 index.php(17): require('/Users/jamesall...')
#14 {main}
```

-------------------

- [x] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

File: includes/subscriptions/class-wc-payments-subscriptions-event-handler.php [hunk 1]
```diff
@@ -123,8 +122,10 @@ public function handle_invoice_paid( array $body ) {
 			$order->payment_complete();
 		}
 
-		// Add the payment intent data to the order.
-		$this->invoice_service->get_and_attach_intent_info_to_order( $order, $wcpay_intent_id );
+		if ( isset( $event_object['payment_intent'] ) ) {
```
Comment (james-allan) [inline includes/subscriptions/class-wc-payments-subscriptions-event-handler.php:125]: Because the first subscription invoice is paid out of band, when we receive the paid invoice webhook, it no longer has a payment intent ID. This was causing the error in WC Pay logs that I mentioned on the PR description.

I've tested invoice paid webhooks for renewal orders and in those cases it is present and passes this condition correctly.

**Comment by james-allan** [comment]
Just making a note acknowledging that the unit tests are failing because getting a new instance of the order (via `wc_get_order()`) doesn't return the mock objects. 

I'll need to come up with a way to circumvent that.

**Comment by james-allan** [comment]
> Just making a note acknowledging that the unit tests are failing because getting a new instance of the order (via wc_get_order()) doesn't return the mock objects.
> 
> I'll need to come up with a way to circumvent that.

I was able to find another solution to that `wc_get_order()` problem. Instead of loading a whole new order object, I reread the current object again from the database.

**Review by mattallan — APPROVED** [review]
Nice fixes @james-allan and thanks for the clear steps to reproduce/test.

I reproduced the bug on `trunk` by confirming the [duplicate order notes](https://d.pr/i/vywFKK) for statuses transitioning and [WCPay logs](https://d.pr/i/i7OseW).

I've confirmed this PR fixes those issues 💯 
I also did some other testing just to make sure no existing behaviour has changed:

 - Using a saved card with UPE enabled
 - Checkout purchase with UPE disabled
 - WCPay Subscription renewal process

All looks good :+1:

I didn't have any thoughts on using `$order->get_data_store()->read( $order );` to get an updated version of the order before calling `$order->payment_complete()`.

It seems fine to me and works well to fix the bug.

---

I've marked this as good to merge but there's a conflict on the changelog edits.
