### PR TITLE
Sepa/1539 pay for order

### LINKED ISSUE #1522: Owner Undefined Undefined when paying order created manually
Step to reproduce:
1. Create an order from wp-admin (I tried with and without specifiying any billing details).

2. Click on the 'Customer payment page →' link above the order status dropdown.
Screen Shot 2021-04-07 at 16 27 13

3. Pay the order with wcpay.

4. Go to the transaction details page by clicking the link in the order note.
Screen Shot 2021-04-07 at 16 29 44

5. Notice the Customer is 'undefined undefined'.

Screen Shot 2021-04-07 at 16 31 07

6. Stripe dashboard also shows Owner Undefined Undefined.

Screen Shot 2021-04-07 at 16 32 35

I'm not sure what's the best solution here. It could be setting it to empty string if that's even possible, or use Stripe's customer id, eg cus_abcdefg.
I notice when I didn't specify any billing details, it shows the Stripe customer id under Customer, on Stripe dashboard.
Screen Shot 2021-04-07 at 16 34 21

### LINKED ISSUE #1539: Fix Pay for Order when using SEPA method.
When you create a manual order and go to pay it from My Account > Orders > Pay
If you try to use a SEPA method, after entering the number and clicking on `Pay for order`, there is an error message and you can not pay.

`Missing required param: billing_details[email].`

SEPAPayForOrderError

You should be able to pay using a SEPA method.

### PR DESCRIPTION
**Pull request by brezocordero**
Fixes #1539 
Fixes #1522 

#### Changes proposed in this Pull Request

Populate customer details from order or from customer when on "Pay for Order" or "Add Payment Method".

This also fixes a bug where the owner name would be set to the string 'undefined undefined'.

Note:
Payments will **not** go through on Pay for Order when using CC if on the order the name is left blank.
Payments will **not** go through on Pay for Order when using SEPA if on the order the name and billing email are left blank.

Add Payment method for SEPA is not working yet. It will be done on #1538 

#### Testing instructions

* Set store currency to euro
* Enable feature flag wp option, update `_wcpay_feature_sepa` to 1
* Enable SEPA in checkbox at bottom of `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments`
* Create a manual order for a customer or guest
* Make sure to enter name and email on billing details.
* Log out and visit the Pay for Order link as the customer or guest
* Select SEPA Method. Enter the test number and submit.
* Verify the payment goes through, verify the customer details in Stripe are correct.
* Verify the customer name is correct on the site transactions page.
* Repeat with CC.

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -529,6 +574,8 @@ public function payment_fields() {
 			wp_localize_script( 'wcpay-checkout', 'wcpay_config', $this->get_payment_fields_js_config() );
 			wp_enqueue_script( 'wcpay-checkout' );
 
+			$this->maybe_localize_customer_data();
```
Comment (superdav42) [inline includes/class-wc-payment-gateway-wcpay.php:577]: This will break down when CC method is disabled so we need to add this line to payment_fields method in the Sepa gateway.

It does cause duplicate data to be injected when both methods are disabled but there's other things that are duplicated as well so we should handle this in a future refactor.

File: client/checkout/classic/index.js [hunk 2]
```diff
@@ -38,8 +38,10 @@ jQuery( function ( $ ) {
 	);
 	const elements = api.getStripe().elements();
 
-	// In the future this object will be loaded with customer information through `wp_localize_script`.
-	const preparedCustomerData = {};
+	// Customer information for Pay for Oder and Save Payment method.
```
Comment (superdav42) [inline client/checkout/classic/index.js:41]:
```suggestion
	// Customer information for Pay for Order and Save Payment method.
```

File: client/checkout/classic/index.js [hunk 3]
```diff
@@ -38,8 +38,10 @@ jQuery( function ( $ ) {
...
+	/* global wcpayCustomerData */
```
Comment (superdav42) [inline client/checkout/classic/index.js:42]:
```suggestion
	/* global wcpayCustomerData from `wp_localize_script` */
```

File: includes/class-wc-payment-gateway-wcpay.php [hunk 4]
```diff
@@ -517,6 +517,51 @@ public function save_payment_method_checkbox( $force_checked = false ) {
...
+		$lastname   = '';
+
+		if ( isset( $_GET['pay_for_order'] ) && 'true' === $_GET['pay_for_order'] ) {
+			$order_id = wc_clean( $wp->query_vars['order-pay'] );
+			$order    = wc_get_order( $order_id );
+
+			if ( is_a( $order, 'WC_Order' ) ) {
+				$firstname  = $order->get_billing_first_name();
+				$lastname   = $order->get_billing_last_name();
+				$name       = $firstname . ' ' . $lastname;
```
Comment (superdav42) [inline includes/class-wc-payment-gateway-wcpay.php:542]:
```suggestion
```
Unused var

File: includes/class-wc-payment-gateway-wcpay.php [hunk 5]
```diff
@@ -517,6 +517,51 @@ public function save_payment_method_checkbox( $force_checked = false ) {
...
+		}
+
+		if ( is_add_payment_method_page() ) {
+			$user = wp_get_current_user();
+
+			if ( $user->ID ) {
+				$firstname  = $user->user_firstname;
+				$lastname   = $user->user_lastname;
+				$user_email = get_user_meta( $user->ID, 'billing_email', true );
+				$user_email = $user_email ? $user_email : $user->user_email;
```
Comment (superdav42) [inline includes/class-wc-payment-gateway-wcpay.php:554]:
```suggestion
				$user_email = get_user_meta( $user->ID, 'billing_email', true ) ?: $user->user_email;
```
I find this simpler and more clear what the code is doing.

File: includes/class-wc-payment-gateway-wcpay.php [hunk 6]
```diff
@@ -517,6 +517,51 @@ public function save_payment_method_checkbox( $force_checked = false ) {
...
+			return;
+		}
+
+		global $wp;
+		$user_email = '';
+		$firstname  = '';
+		$lastname   = '';
+
+		if ( isset( $_GET['pay_for_order'] ) && 'true' === $_GET['pay_for_order'] ) {
+			$order_id = wc_clean( $wp->query_vars['order-pay'] );
```
Comment (superdav42) [inline includes/class-wc-payment-gateway-wcpay.php:536]:
```suggestion
			$order_id = absint( $wp->query_vars['order-pay'] );
```

**Review by superdav42 — CHANGES_REQUESTED** [review]
Just a few small suggestions. The only one that is really needed in adding the line to the SEPA gateway too.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 1 above)
Comment (brezocordero) [reply includes/class-wc-payment-gateway-wcpay.php]: I have modified the function and include the localization in both classes.
Thanks for pointing it out.

File: client/checkout/classic/index.js (hunk 2 above)
Comment (brezocordero) [reply client/checkout/classic/index.js]: Done!

File: client/checkout/classic/index.js (hunk 3 above)
Comment (brezocordero) [reply client/checkout/classic/index.js:43]: The linter complains if I add the details.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 4 above)
Comment (brezocordero) [reply includes/class-wc-payment-gateway-wcpay.php:555]: Thanks for finding the redundancy. I ended up removing $`firstname` and `$lastname` because the value that is used in the script is `$name`.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 5 above)
Comment (brezocordero) [reply includes/class-wc-payment-gateway-wcpay.php:567]: Yes, it looks cleaner but our PHPCS rules do not allow for short ternaries...

File: includes/class-wc-payment-gateway-wcpay.php (hunk 6 above)
Comment (brezocordero) [reply includes/class-wc-payment-gateway-wcpay.php]: Good suggestion. Done!

File: includes/class-wc-payment-gateway-wcpay.php (hunk 5 above)
Comment (superdav42) [reply includes/class-wc-payment-gateway-wcpay.php:567]: That's probably a rule from PHP 5.2 days. Maybe we could change it at some point. This is fine for now.

**Review by superdav42 — APPROVED** [review]
LGTM!
