### PR TITLE
Fix WooPay button preview in plugin settings.

### LINKED ISSUE #9537: Express checkout button size for WooPay does not change in the preview
### Describe the bug
Changing the express checkout button size does not result in the WooPay button size changing in the preview. This could give the impression that WooPay functionality on checkout is broken when if fact only the settings preview is broken.

[Recording](https://d.pr/v/MyoG09)

### PR DESCRIPTION
**Pull request by rafaelzaleski**
Fixes #9537 

#### Changes proposed in this Pull Request

Fixes the issue where changing the express checkout button size does not update the WooPay button size in the preview. 

https://github.com/user-attachments/assets/8d418080-2470-44b7-a150-7fa5f55c311d

#### Testing instructions

1. **Reproduce the Issue on `develop`**
   - Visit the issue: [WooCommerce Payments Issue #9537](https://github.com/Automattic/woocommerce-payments/issues/9537).
   - Follow the steps described to confirm you can reproduce the issue on the `develop` branch.

2. **Switch to the Branch `fix/9537-woopay-button-size-preview`**
   - Build the project:
     ```bash
     npm install
     npm run build
     ```

3. **Verify the Issue is Resolved**
   - Repeat the reproduction steps from the issue.
   - Confirm that the issue no longer occurs on this branch, and check for any new, unintended behaviors.
-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9649` or branch name `fix/9537-woopay-button-size-preview` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9537-woopay-button-size-preview) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 81bd795138137b510c91aa28fd97fe2840742796
- Build time: 2024-10-31 22:52:00 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/checkout/woopay/express-button/woopay-express-checkout-button.js [hunk 1]
```diff
@@ -71,7 +71,8 @@ export const WoopayExpressCheckoutButton = ( {
 		borderRadius = buttonAttributes.borderRadius || borderRadius;
```
Comment (ricardo) [inline client/checkout/woopay/express-button/woopay-express-checkout-button.js]: Found a small issue related to the border-radius which I think we could fix here by using `??` instead of `||`.

```suggestion
		borderRadius = buttonAttributes.borderRadius ?? borderRadius;
```

The issue appears when I refresh the page with the border radius set to `0`. It uses the default border-radius from the CSS, because it tries to apply an invalid inline border-radius `undefined + 'px'`.

https://github.com/user-attachments/assets/8bf6c6d2-69f0-47ff-a280-fedf2fed80db

**Review by ricardo — APPROVED** [review]
LGTM and tests well 👍.

We just need to apply the null coalescing operator to fix the border radius issue.

File: client/checkout/woopay/express-button/woopay-express-checkout-button.js (hunk 1 above)
Comment (rafaelzaleski) [reply client/checkout/woopay/express-button/woopay-express-checkout-button.js]: Good find! Thank you!
