### PR TITLE
Avoid adding two fee details in the order page

### LINKED ISSUE #5691: Two fee details note on the order page
### Describe the bug

Convo: p1678288735391379-slack-C01BPL3ALGP

I noticed that there are two fee notes on the order page - 

Then I found out it’s related to this line from Platform PR #5321
https://github.com/Automattic/woocommerce-payments/blob/20cf3221d46159dabdeba9193fdcf548d8dc6314/includes/subscriptions/class-wc-payments-subscriptions.php#L70

which creates a new instance for `WC_Payments_Order_Service`, then this hook got registered two times in its constructor.

https://github.com/Automattic/woocommerce-payments/blob/20cf3221d46159dabdeba9193fdcf548d8dc6314/includes/class-wc-payments-order-service.php#L91

### To do

This specific use case is not bringing a big issue. But it has the similar cause like our recent 5.5.0 incident. So I think what we would do:

1, Review our PR 5321, and double check about this.
2, Convert `WC_Payments_Order_Service` and maybe other service classes into singleton, or could convert the order service to a dependency in class-wc-payments-subscriptions.php.

### To Reproduce

Use the `develop` branch to create any order.

### Screenshots

[Screenshot](https://user-images.githubusercontent.com/10045087/223919496-ff849181-c61e-4939-8a8d-8e13190b2e92.png)

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by htdat**
Fixes #5691

#### Changes proposed in this Pull Request

See my review here https://github.com/Automattic/woocommerce-payments/issues/5691#issuecomment-1461325022 too.

- Convert the order service to a dependency in `WC_Payments_Subscriptions`. Note: I acutally replace `$gateway` dependency with the order service as we're not actually using `$gateway`.
- Move the hook registration for ADD_FEE_BREAKDOWN_TO_ORDER_NOTES to `WC_Payments_Action_Scheduler_Service` so that we can avoid registering hooks in the order service's constructor.

With both changes above, the `WC_Payments_Order_Service` table in my review comment becomes something like this:  

| Class      | Avoid hooks in constructor | Instantiated only once | Need to fix
| ----------- | ----------- |----------- |----------- |
| WC_Payments_Order_Service   | ✅        |✅        | No |

#### Testing instructions

* Git: Check out the current `develop` branch. 
* Buy a product and go through the checkout process.
* Check the order page, and wait for a while. Otherwise, go to WP Admin > Settings > Scheduled Actions, search for `wcpay_add_fee_breakdown_to_order_notes` actions and run the action for this order.
* Confirm: there are two fee-detail notes.
* Git: check out this PR.
* Go through the same steps.
* Confirm: only one fee-details note in the order page.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] NO NEED - Tested on mobile (or does not apply)

**Post merge**

- [x] NO NEED - Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] NO NEED - Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] NO NEED - Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: includes/class-wc-payments-action-scheduler-service.php [hunk 1]
```diff
@@ -52,6 +52,7 @@ public function __construct(
 	public function add_action_scheduler_hooks() {
 		add_action( 'wcpay_track_new_order', [ $this, 'track_new_order_action' ] );
 		add_action( 'wcpay_track_update_order', [ $this, 'track_update_order_action' ] );
+		add_action( WC_Payments_Order_Service::ADD_FEE_BREAKDOWN_TO_ORDER_NOTES, [ $this->order_service, 'add_fee_breakdown_to_order_notes' ], 10, 3 );
```
Comment (RadoslavGeorgiev) [inline includes/class-wc-payments-action-scheduler-service.php:55]: > Move the hook registration for `ADD_FEE_BREAKDOWN_TO_ORDER_NOTES` to `WC_Payments_Action_Scheduler_Service` so that we can avoid registering hooks in the order service's constructor.

To be fair, `add_action_scheduler_hooks` is also called within a service's constructor, now it's just a separate service. It's a bit nicer that there is a separate method for that, but it's still called from the constructor.

No action needed here from you. Noting this for a future platform project/PR target: Move hooks outside of service constructors, and add a helper for those, ex. `WC_Payments::get_service( $class_name )`, which would instantiate a singleton service service, **and** call a specific method, ex. `register_hooks`.

File: changelog/fix-5691-two-fee-notes [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
+Type: fix
+
+Avoid adding two fee details in the order page (regression issue from PR 5321).
```
Comment (RadoslavGeorgiev) [inline changelog/fix-5691-two-fee-notes]: PR 5321 has not been released, and this might seem a bit confusing in the changelog. Should we maybe switch to a comment, which will be skipped for `changelog.txt`?

File: includes/subscriptions/class-wc-payments-subscriptions.php [hunk 3]
```diff
@@ -67,7 +67,7 @@ public static function init( WC_Payments_API_Client $api_client, WC_Payments_Cus
 		include_once __DIR__ . '/class-wc-payments-subscriptions-empty-state-manager.php';
 
 		self::$product_service      = new WC_Payments_Product_Service( $api_client );
-		self::$order_service        = new WC_Payments_Order_Service( $api_client );
+		self::$order_service        = $order_service;
```
Comment (RadoslavGeorgiev) [inline includes/subscriptions/class-wc-payments-subscriptions.php]: For future reference, should we reorder the assignments and add some comments here, to avoid easily following the existing example, and creating new instances?

Looking at it now, I guess reordering the whole method while adding comments would make sense:

1. Store dependencies (in this case just the order service). `// Store dependencies.`
2. Include new files. `// Load services`.
3. `// Instantiate additional classes.`

So the method would look like this:

```php
// Store dependencies.
self::$order_service = $order_service;

// Load Services.
include_once __DIR__ . '/class-wc-payments-product-service.php';
include_once __DIR__ . '/class-wc-payments-invoice-service.php';
include_once __DIR__ . '/class-wc-payments-subscription-service.php';
include_once __DIR__ . '/class-wc-payments-subscription-change-payment-method-handler.php';
include_once __DIR__ . '/class-wc-payments-subscriptions-plugin-notice-manager.php';
include_once __DIR__ . '/class-wc-payments-subscriptions-empty-state-manager.php';
include_once __DIR__ . '/class-wc-payments-subscriptions-event-handler.php';
include_once __DIR__ . '/class-wc-payments-subscriptions-onboarding-handler.php';
include_once __DIR__ . '/class-wc-payments-subscription-minimum-amount-handler.php';

// Instantiate additional classes.
self::$product_service      = new WC_Payments_Product_Service( $api_client );
self::$invoice_service      = new WC_Payments_Invoice_Service( $api_client, self::$product_service, self::$order_service );
self::$subscription_service = new WC_Payments_Subscription_Service( $api_client, $customer_service, self::$product_service, self::$invoice_service );
self::$event_handler        = new WC_Payments_Subscriptions_Event_Handler( self::$invoice_service, self::$subscription_service );

new WC_Payments_Subscription_Change_Payment_Method_Handler();
new WC_Payments_Subscriptions_Plugin_Notice_Manager();
new WC_Payments_Subscriptions_Empty_State_Manager( $account );
new WC_Payments_Subscriptions_Onboarding_Handler( $account );
new WC_Payments_Subscription_Minimum_Amount_Handler( $api_client );
```

**Review by RadoslavGeorgiev — APPROVED** [review]
Changes look great, @htdat! 👏 

Thank you for discovering this, and working on it! The changes LGTM, I've added a couple of suggestions, but I'm pre-approving the PR.

File: changelog/fix-5691-two-fee-notes (hunk 2 above)
Comment (htdat) [reply changelog/fix-5691-two-fee-notes]: Make sense, updated it https://github.com/Automattic/woocommerce-payments/pull/5693/commits/351da7b63f0fd022f5969d3d8f60e14f345453fe

File: includes/class-wc-payments-action-scheduler-service.php (hunk 1 above)
Comment (htdat) [reply includes/class-wc-payments-action-scheduler-service.php:55]: > To be fair, add_action_scheduler_hooks is also called within a service's constructor, now it's just a separate service. It's a bit nicer that there is a separate method for that, but it's still called from the constructor.

Yeah, that's totally right.

> Noting this for a future platform project/PR target: Move hooks outside of service constructors, and add a helper for those, ex. `WC_Payments::get_service( $class_name )`, which would instantiate a singleton service service, **and** call a specific method, ex. `register_hooks`.

Agreed here too, I am going to create an issue for this.

File: includes/subscriptions/class-wc-payments-subscriptions.php (hunk 3 above)
Comment (htdat) [reply includes/subscriptions/class-wc-payments-subscriptions.php]: Great suggestion. Updated f694c5282c9c052c6e578427ac26de39e8784e28

File: includes/class-wc-payments-action-scheduler-service.php (hunk 1 above)
Comment (htdat) [reply includes/class-wc-payments-action-scheduler-service.php:55]: Created issue: https://github.com/Automattic/woocommerce-payments/issues/5698
