### PR TITLE
Show empty state treatment only when WCPay not connected

### LINKED ISSUE #2511: WooCommerce Payments asking to "Finish Setup"
Note: We have not been able to reproduce this issue. We have gotten multiple reports of it from customers. Devs gave permission to open an issue. 

Issue: When clicking on "deposits", "transactions", or "disputes" it does not go to the report. Instead, the user gets a finish setup page. When they click the "finish setup" button it goes to the set up dashboard even if they have it configured. Customer can't see the deposit, transaction, or dispute history. 

Issue here: 4163046-zen

Public question here: https://wordpress.org/support/topic/keeps-asking-to-finish-setup/

Slack conversation here with more examples of the issue: p1626553885410700-slack-C7U3Y3VMY

### PR DESCRIPTION
**Pull request by dechov**
Fixes #2511

Huge kudos to @htdat for discovering (https://github.com/Automattic/woocommerce-payments/issues/2511#issuecomment-886051004) the likely cause of the issue.

#### Changes proposed in this Pull Request

If empty state experimental treatment (added in https://github.com/Automattic/woocommerce-payments/pull/1963) is active, it appears that Transactions and Deposits are currently not being shown. The change in https://github.com/Automattic/woocommerce-payments/commit/3d1bc5a02676c8d21bbb3bc3d74eebc0b29735e3 is to always show them when WCPay is connected.

Also, https://github.com/Automattic/woocommerce-payments/commit/2f24127eb990fd79ed2bcf6d56ba3d534f1e7774 ensures that the redirect to the onboarding screen (added in https://github.com/Automattic/woocommerce-payments/pull/2275) occurs only when not in treatment mode.

#### Testing instructions

First, go into treatment mode:

I tested this only in a local way by returning true from `is_in_treatment_mode`, and verifying the proper view with console statements in the `TransactionsPage` and `DepositsPage` components: `console.log( treatmentExperience === defaultExperience ? 'default table' : 'new empty state' );`

I would encourage testing by assigning the `treatment` variations as described in https://github.com/Automattic/woocommerce-payments/pull/1963.

Next, navigate to Deposits and Transactions screens on a connected site, and verify that the **default table view appears** (with data, or "No data to display" message) and the **"Finish setup" button does not**.

Also, test with a disconnected site (or set `wcpaydev_force_disconnected` option to true e.g. via WCPay dev tools) and verify that the "Finish setup" button appears on Deposits and Transactions screens, even on new page load.

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Not adding a changelog entry** mainly because I'm not sure whether this change will be rebased or cherry-picked into release branch, but one should be added prior to merge or release.

### CODE REVIEW

**Comment by moon0326** [comment]
@dechov Thank you so much for the PR 🙏 and my apologies for the bad code in my previous PR. Everything tested well with the changes. I'll leave approval to someone else since I'm the one who caused the issue.

File: client/deposits/index.js [hunk 1]
```diff
@@ -19,27 +19,29 @@ import ListBanner from '../empty-state-table/deposits-banner.svg';
...
 
 const DepositsPage = () => {
+	const defaultExperience = (
+		<>
+			<TestModeNotice topic={ topics.deposits } />
+			<DepositsList />
+		</>
+	);
+
+	const treatmentExperience = wcpaySettings.accountStatus.status ? (
```
Comment (htdat) [inline client/deposits/index.js:29]: This condition is OK for "WCPay not connected". 

However, the original issue https://github.com/Automattic/woocommerce-payments/issues/1816 mentions: 

> As a merchant who has installed WCPay but not completed the KYC. 

If so, two statuses `restricted` and `restricted_soon` will fall into this condition too? cc @moon0326 and @mattsherman

Here is the reference to these two statuses in the Overview page https://github.com/Automattic/woocommerce-payments/blob/2f24127eb990fd79ed2bcf6d56ba3d534f1e7774/client/account-status-settings/index.js#L46-L76

**Review by htdat — COMMENTED** [review]
Tests are OK. I have a question regarding whether or not we should implement the treatment for two mattered statuses. 

@moon0326 and @mattsherman - Also, this looks like a typo? 
https://github.com/Automattic/woocommerce-payments/blob/7530f1eda7a70fcc490c25ed4b079efbadab388b/client/empty-state-table/list.js#L56

I think the correct would be: 

>  'By clicking "Finish setup", you agree to the <a>Terms of Service</a>',

**Comment by moon0326** [comment]
> Tests are OK. I have a question regarding whether or not we should implement the treatment for two mattered statuses.
> 
> @moon0326 and @mattsherman - Also, this looks like a typo?
> https://github.com/Automattic/woocommerce-payments/blob/7530f1eda7a70fcc490c25ed4b079efbadab388b/client/empty-state-table/list.js#L56
> 
> I think the correct would be:
> 
> > 'By clicking "Finish setup", you agree to the Terms of Service',

I actually thought this was incorrect as well, but it looks like it's correct according to [grammarly](https://www.grammarly.com/blog/quotation-marks/#:~:text=In%20the%20United%20States%2C%20the,last%20night%2C%E2%80%9D%20Paul%20said.)

**Comment by elizaan36** [comment]
Yep, that should say `By clicking "Finish setup",...` ☺️

File: client/deposits/index.js (hunk 1 above)
Comment (dechov) [reply client/deposits/index.js:29]: I'm pretty sure we need to show these records even if the account is currently in a restricted state (or will be soon), but that's a great question in terms of the onboarding changes imminent on the server, since there will be accounts linked that have not yet completed initial KYC. I don't think they will be considered connected from the plugin's perspective until the initial KYC details are submitted, but we should check on that.

**Comment by dechov** [comment]
@moon0326 Should I add that text change in this PR?

Also, it wasn't bad code and there's no apology necessary 😄 I think we just need to enhance our processes to validate changes across wider sets of cases, and in particular across A/B test cases.

**Comment by adrianduffell** [comment]
> @moon0326 Should I add that text change in this PR?
> 
> Also, it wasn't bad code and there's no apology necessary 😄 I think we just need to enhance our processes to validate changes across wider sets of cases, and in particular across A/B test cases.

Thanks @dechov, I'm working on process improvements for Isotope around A/B testing and will take your feedback on board.

A few ideas so far:

- Complex PRs to be reviewed a second time by a more experienced WC Pay dev.
- Create documentation about the current A/B tests in WC Pay.
- For now, do testing directly against deployed experiments - skip staging mode (recommended by ExPlat team).

Also agree it wasn't bad code 🙂

**Comment by moon0326** [comment]
Thank you @dechov @adrianduffell 🙏 

@dechov Yes, that would be nice 👍

File: client/deposits/index.js (hunk 1 above)
Comment (dechov) [reply client/deposits/index.js:29]: Confirmed that with the new onboarding changes, there is currently no account status being returned until WCPay is connected _and onboarded_, so AFAIK this check will do.

**Comment by dechov** [comment]
Ready for further review.

File: client/deposits/index.js (hunk 1 above)
Comment (htdat) [reply client/deposits/index.js:29]: If so, I think we should be very clear about two terms "not yet completed KYC" and "WCPay not connected" as they're not the same. Otherwise, it will be very confusing for all people involved. 

If I understand correctly: 

- WCPay not connected = No KYC provided.
- Not yet completed KYC = (1) WCPay connected AND (2) some KYC docs provided but not enough = two statuses `restricted` or `restricted_soon` 

If this is correct, I will raise a small discussion in the upstream - this PT paJDYF-1rg-p2

Comment (dechov) [reply client/deposits/index.js:29]: `restricted` means there are requirements that are past due, and `restricted_soon` means there are requirements that will be due soon – for our current purposes, these would happen after initial KYC. (The status is defined in the `get_account_status` server function, and it's intended to match the Stripe dashboard's account status – e.g. [here](https://stripe.com/docs/connect/dashboard#restricted) – but isn't _directly_ derived from it.)

I think if we were to modify the server to return the account info prior to completion of initial KYC, we would assign a new status for that state. At that point, we can modify this logic to exclude that state _if_ we choose to keep this preview mode until initial KYC is complete, but we don't want to hide data just because there are currently (or soon will be) unfulfilled requirements on the account – does that sound right?

**Comment by moon0326** [comment]
> Ready for further review.

The adjusted text renders fine 👍

**Comment by kalessil** [comment]
@aprea, this PR looks pretty close to the context you was working so I wondering if you could give it review/testing. What do you think?

**Comment by dechov** [comment]
@aprea @kalessil et al., feel free to "take over" / update and merge if that helps to make it into the upcoming release.

**Comment by adrianduffell** [comment]
@htdat Are you able to assist approving this today? It looks like there is just the unresolved discussion here https://github.com/Automattic/woocommerce-payments/pull/2555#discussion_r676091855

Thank you

File: client/deposits/index.js (hunk 1 above)
Comment (htdat) [reply client/deposits/index.js:29]: @dechov - your reply makes sense and I totally agree. However, that also means we may need to update this P2 paJDYF-1rg-p2 and ask for using the correct wording "WCPay not connected". 

I am going to add a comment in this P2.

Comment (htdat) [reply client/deposits/index.js:29]: Comment paJDYF-1rg-p2#comment-7381

**Review by htdat — APPROVED** [review]
🚢 it!

> @htdat Are you able to assist approving this today? It looks like there is just the unresolved discussion here https://github.com/Automattic/woocommerce-payments/pull/2555#discussion_r676091855

I moved the convo to paJDYF-1rg-p2#comment-7381

**Comment by adrianduffell** [comment]
Thanks @htdat !

As per @dechov [comment above](https://github.com/Automattic/woocommerce-payments/pull/2555#issuecomment-890113036) I'll merge this now to help it into the upcoming release.

> I moved the convo to paJDYF-1rg-p2#comment-7381

I'll take a look 👀
