### PR TITLE
Payouts - Show failure message in payout details for failed payouts 

### LINKED ISSUE #8203: Show specific payout error for 'Failed' payouts on payout detail screen
### Describe the bug
Payouts can fail for various reasons: 

- Missing payment details
- Payment to account failed / bounced
- etc (I don't know the full list)

In WooPayments we should surface any error messages or related details of why (e.g. if payout details are missing) 

Here's what a failed payout looks like in the UI (details screen):

no error message when payout fails

### To Reproduce
- Visit the Stripe Express dashboard for your test WooPayments account (Payments → Overview → Account Details → Edit Details)
- Update the payout bank account to a [failing test account](https://docs.stripe.com/connect/testing#payouts), e.g. 110000000/000111111116 
- Wait for a scheduled payout to fail

There are likely other testing steps to generate a failed payout. This issue is intended to cover multiple errors/failure modes. 

### Actual behavior
- `Failed` payout shown in UI, with linked transactions, and no error message.

### Expected behavior
- Show an error message or explanation.
- Possibly the linked transactions should be un-linked or greyed out– I'm not sure what this means when the payout failed

```[tasklist]
### Subtasks ( added by @nagpai )
- [x] Capture `failure_code` in our database - https://github.com/Automattic/transact-platform-server/issues/7091
- [x] Expose `failure_code` in service, for failed payout objects that are sent in webhooks -https://github.com/Automattic/transact-platform-server/issues/7092
- [x] Show localized messages related to the `failure_code` on any failed payout
```

### PR DESCRIPTION
**Pull request by nagpai**
Fixes #8203 

> [!IMPORTANT]  
>  Please make sure https://github.com/Automattic/transact-platform-server/pull/7300 is merged before this PR

#### Changes proposed in this Pull Request

* Show a localized reason for failure for any failed payouts.  The messages are generated based on mapping of `failure_code` captured for each failed payout ( captured since Feb 4, 2025  - https://github.com/Automattic/transact-platform-server/pull/7159 ) , with translatable strings on client introduced in this PR
* For failed payouts, where there is no `failure_code` captured, we will be showing an untranslated `failure_message` that is captured directly from Stripe's payout object, as a fallback
* For any `failure_code` not included in our current map of codes, ( probably newly introduced by Stripe ), the code will show the fallback  untranslated `failure_message` captured from Stripe's payout object.

image

#### Testing instructions

Checkout your local server instance to https://github.com/Automattic/transact-platform-server/pull/7300

##### Scenario 1 - Failed payout with a valid `failure_code`
* Link your local site with a test site that has had a recent failed payout. This can be generated if needed using a failing bank account on the test account. Or alternatively, manually tweaking the payout on the test server database with status as `failed` and `failure_code` same as any of those available in [payoutFailureMessages] (https://github.com/Automattic/woocommerce-payments/pull/10462/files#diff-f3ae55d63a28e488eedb193add7f91f1c19b25bbb8cfabd52d6a9f3ebf90d803R39) ( map of failure code and messages ) 
* Browse to `Payments -> Payouts` and click on the failed payout.
* You should see the relevant failure message matching the failure_code 

image

##### Scenario 2 - Failed payout with no `failure_code`
* This scenario simulates failed payouts captured before February 4, 2025, when we did not have failure_code captured in our database.
* Open up a failed payout in the test database, and delete its failure_code. Add any test `failure_message`
* Open up the payout from `Payments -> Payouts` - You should see the test message you added in the failure reason box

image

##### Scenario 3 - Failed payout with a non-matching / new `failure_code`
* Within the test db, edit the `failure_code` on any failed payout to a test text, and not within our existing failure code map. 
* Add any test failure_message that is easy to identify, similar to the last scenario
* Browse to `Payments -> Payouts`. The failure reason should show the test failure_message. 

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10462` or branch name `add/8203-payout-failure-notice` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/8203-payout-failure-notice) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 072cb4605b39c70b95de158761c8fd42dbd759e0
- Build time: 2025-03-05 06:38:11 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/deposits/strings.ts [hunk 1]
```diff
@@ -32,3 +32,106 @@ export const depositStatusLabels: Record<
 	canceled: __( 'Canceled', 'woocommerce-payments' ),
 	failed: __( 'Failed', 'woocommerce-payments' ),
 };
+
+/**
+ * Mapping of payout failure code to display string.
+ */
+export const payoutFailureMessages: Record< PayoutFailureCode, string > = {
```
Comment (shendy-a8c) [inline client/deposits/strings.ts:39]: Looking at https://docs.stripe.com/api/payouts/object#payout_object-failure_code, these are missing from this mapping:
- incorrect_account_holder_address
- incorrect_account_holder_tax_id
- invalid_account_number_length

Is that intentional?

File: client/deposits/strings.ts [hunk 2]
```diff
@@ -32,3 +32,106 @@ export const depositStatusLabels: Record<
...
+	bank_account_restricted: __(
+		'The bank account has restrictions on either the type or number of transfers allowed. This normally indicates that the bank account is a savings or other non-checking account.',
+		'woocommerce-payments'
+	),
+	debit_not_authorized: __(
+		'Debit transactions are not approved on the destination bank account. Bank accounts need to be set up for both credit and debit transfers.',
+		'woocommerce-payments'
+	),
+	invalid_card: __(
+		'The card used was invalid. This usually means the card number is invalid or the account has been closed. Please verify card details before retrying.',
```
Comment (shendy-a8c) [inline client/deposits/strings.ts]: I ran through these sentences to AI and this one can be improved:

```suggestion
		'The card used was invalid. This usually means the card number is incorrect or the account has been closed. Please verify the card details before retrying.',
```

File: client/deposits/strings.ts [hunk 3]
```diff
@@ -32,3 +32,106 @@ export const depositStatusLabels: Record<
...
+		'The card used has expired. Please switch to a different card or payment method. Contact the issuing bank for clarification before trying again.',
+		'woocommerce-payments'
+	),
+	could_not_process: __(
+		// The same failure code is used if processing is failed by the bank or Stripe.
+		'The bank or the payment processor could not process this transfer.',
+		'woocommerce-payments'
+	),
+	invalid_account_number: __(
+		'The bank account details on file are probably incorrect. The routing number seems correct, but the account number is invalid.',
```
Comment (shendy-a8c) [inline client/deposits/strings.ts]: I ran through these sentences to AI and this one can be improved:

```suggestion
		'The bank account details on file are probably incorrect. While the routing number appears correct, the account number is invalid.',
```

File: client/deposits/strings.ts [hunk 4]
```diff
@@ -32,3 +32,106 @@ export const depositStatusLabels: Record<
...
+		'woocommerce-payments'
+	),
+	incorrect_account_holder_name: __(
+		'The bank account details on file are probably incorrect.',
```
Comment (shendy-a8c) [inline client/deposits/strings.ts]: I ran through these sentences to AI and this one can be improved:

```suggestion
		'The bank account holder name on file appears to be incorrect.',
```

File: client/types/deposits.d.ts [hunk 5]
```diff
@@ -52,3 +54,29 @@ export type DepositStatus =
 	| 'in_transit'
 	| 'canceled'
 	| 'failed';
+
+export type PayoutFailureCode =
```
Comment (shendy-a8c) [inline client/types/deposits.d.ts:58]: See my above comment. This part might be affected if you decide to add the missing enums from https://docs.stripe.com/api/payouts/object#payout_object-failure_code:

- incorrect_account_holder_address
- incorrect_account_holder_tax_id
- invalid_account_number_length

**Comment by shendy-a8c** [comment]
I tested with 4 scenarios: 3 scenarios explained in the PR description plus one scenario where `failure_code` and `failure_message` are missing even though payout's status is failed which `Failure reason: Unknown` will be displayed.

I tested by hardcoding the `deposit.status`, `deposit.failure_code`, and `deposit.failure_message`, eg:
```
deposit.status = 'failed';
deposit.failure_code = 'bank_account_restricted';
deposit.failure_message = 'Failure Message';
```

File: client/deposits/strings.ts (hunk 1 above)
Comment (nagpai) [reply client/deposits/strings.ts:39]: Unintentional and nice catch, Thanks @shendy-a8c ! 

When I started collating the list of failure_code , I found that the documented enum had some missing like `invalid_card` . Hence, I went about querying our DB for unique failure_code ( via failure messages initially since we did not capture code at that time ). I exchanged some notes with Stripe and came up with the list. It looks like I missed these three which were on the documented enum. I have not found any instances of these while querying, but a good idea to include them! Thanks!

File: client/deposits/strings.ts (hunk 2 above)
Comment (nagpai) [reply client/deposits/strings.ts]: I have used these strings from what was sent by Stripe. The suggestions noted by you are good and I will change them.  In this string though, I would prefer keeping 'invalid' as it fits the context better IMO.

File: client/types/deposits.d.ts (hunk 5 above)
Comment (nagpai) [reply client/types/deposits.d.ts:58]: Thanks for marking these! I have updated the type def here as well - [072cb46](https://github.com/Automattic/woocommerce-payments/pull/10462/commits/072cb4605b39c70b95de158761c8fd42dbd759e0)

File: client/deposits/strings.ts (hunk 4 above)
Comment (nagpai) [reply client/deposits/strings.ts]: Changed here, thanks - [d256e22](https://github.com/Automattic/woocommerce-payments/pull/10462/commits/d256e22ea41da96714e462291a2032cd16427eb0)

File: client/deposits/strings.ts (hunk 3 above)
Comment (nagpai) [reply client/deposits/strings.ts]: Changed here - [d256e22](https://github.com/Automattic/woocommerce-payments/pull/10462/commits/d256e22ea41da96714e462291a2032cd16427eb0) , thanks!

File: client/deposits/strings.ts (hunk 2 above)
Comment (nagpai) [reply client/deposits/strings.ts]: Changed here, thanks! - [d256e22](https://github.com/Automattic/woocommerce-payments/pull/10462/commits/d256e22ea41da96714e462291a2032cd16427eb0)

File: client/deposits/strings.ts (hunk 1 above)
Comment (nagpai) [reply client/deposits/strings.ts:39]: I have added these three failure codes to the map here - [072cb46](https://github.com/Automattic/woocommerce-payments/pull/10462/commits/072cb4605b39c70b95de158761c8fd42dbd759e0) .. Thanks for spotting it!

File: client/deposits/strings.ts (hunk 2 above)
Comment (shendy-a8c) [reply client/deposits/strings.ts]: > I have used these strings from what was sent by Stripe.

Ah. I didn't know that and *doh* it's right there in the docs. How could I miss that.

That should have been safe to use then but it's OK too to have something different as well, part of owning our own product.

**Review by shendy-a8c — APPROVED** [review]

**Comment by nagpai** [comment]
Marking as blocked until this server PR that exposes `failure_message` in the Payout API response, is merged - https://github.com/Automattic/transact-platform-server/pull/7300
