### PR TITLE
fix: ECE failure with more than 9 shipping options

### LINKED ISSUE #10490: ECE - error when the store provides more than 9 shipping rates
### Describe the bug

I noticed the ECE (both tokenized ECE and non-tokenized ECE) can error out with the following message:
> Uncaught (in promise) IntegrationError: Invalid value for shippingaddresschange event resolve callback: shippingRates should be an array of size less than 10. You specified [redacted]

I couldn't find this limitation being documented on the Stripe website docs.

### To Reproduce

1. As a merchant, navigate to `wp-admin` > WooCommerce > Settings > Shipping
2. If you don't have it already, create a "US" (or US California, to be even more specific - you'll need it to match with Google Pay test shipping addresses) shipping zone
3. Add 10 shipping options to the shipping zone (they can all be "flat rate", for example)
4. As a merchant, ensure you have Google Pay/Apple Pay enabled in your WooPayments settings
5. As a customer, add a physical product to the cart
6. Navigate to the cart page (either block-based or shortcode-based)
7. Click on the GooglePay/ApplePay button
8. Select the "California" address
9. Notice the error in the console

Image

Image

Image

### Expected behavior

There should be no error in the console.
The shipping rates should be limited to 9.

### PR DESCRIPTION
**Pull request by frosso**
Fixes https://github.com/Automattic/woocommerce-payments/issues/10490

#### Changes proposed in this Pull Request

I implemented this change for both the Tokenized ECE and non-tokenized ECE. The behavior is similar.
I did not add tests to the non-tokenized ECE since there are none to begin with. It'll be replaced by the Tokenized ECE "soon", so I don't think it's worth spending too much of our time on it.

#### Testing instructions

1. As a merchant, navigate to `wp-admin` > WooCommerce > Settings > Shipping
2. If you don't have it already, create a "US" (or US California, to be even more specific - you'll need it to match with Google Pay test shipping addresses) shipping zone
Screenshot 2025-03-05 at 6 55 54 PM

3. Add 10 shipping options to the shipping zone (they can all be "flat rate", for example)
4. As a merchant, ensure you have Google Pay/Apple Pay enabled in your WooPayments settings
5. As a customer, add a physical product to the cart
6. Navigate to the cart page (test this for both block-based and shortcode-based checkout)
7. Click on the GooglePay/ApplePay button
8. Select the "California" address
9. The console error should no longer appear

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10491` or branch name `fix/ece-shipping-rates-upper-limit-count` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/ece-shipping-rates-upper-limit-count) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 80891037e2c8ae2a1e2e20c22454650fa82dc5a2
- Build time: 2025-03-06 15:36:29 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/express-checkout/constants.js [hunk 1]
```diff
@@ -0,0 +1 @@
+export const SHIPPING_RATES_UPPER_LIMIT_COUNT = 9;
```
Comment (mdmoore) [inline client/express-checkout/constants.js:4]: Maybe a comment explaining why this limit is needed would be useful for future maintainers?

**Review by mdmoore — APPROVED** [review]
This is working well. Before the fix, I see this error: 

```Uncaught (in promise) IntegrationError: Invalid value for click event resolve callback: shippingRates should be an array of size less than 10. You specified: [{"id":"flat_rate:22","amount":45,"displayName":"Flat rate"},{"id":"flat_rate:26","amount":7000,"displayName":"Flat rate large"},{"id":"flat_rate:27","amount":500,"displayName":"Flat rate"},{"id":"flat_rate:28","amount":500,"displayName":"Flat rate"},{"id":"flat_rate:29","amount":500,"displayName":"Flat rate"},{"id":"flat_rate:30","amount":500,"displayName":"Flat rate"},{"id":"flat_rate:31","amount":500,"displayName":"Flat rate"},{"id":"flat_rate:32","amount":500,"displayName":"Flat rate"},{"id":"flat_rate:33","amount":500,"displayName":"Flat rate"},{"id":"flat_rate:34","amount":500,"displayName":"Flat rate"}].```

After the fix the error no longer occurs in either the non-tokenized ECE or the tokenized ECE. 

My guess is that this would be an edge case. 10 shipping options is a lot. But perhaps this is worth adding to public docs somewhere. Thanks for the fix!

File: client/express-checkout/constants.js (hunk 1 above)
Comment (frosso) [reply client/express-checkout/constants.js:4]: I was initially thinking that somebody could use git blame to look into the reasoning, but it doesn't hurt being explicit - good suggestion, thanks! :) done in 80891037e
