### PR TITLE
Euro is displayed as zero-decimal currency for Japanese accounts

### LINKED ISSUE #6944: Euro is displayed as zero-decimal currency for Japanese accounts
### Describe the bug
A Japanese account using a multi-currency widget or having a store currency such as the euro would get the fixed fees in EUR as a zero-decimal currency.

### To Reproduce
1. Connect a Japanese account and enable multi-currency.
2. Set the currency from the multi-currency widget to EUR.
3. Create an order with EPS.
4. Navigate to `Payments` -> `Transactions` and open Transaction details for the recent order.
5. Verify the fixed Base fee is displayed as +0 EUR

### Screenshots
Screenshot 2023-08-07 at 15 46 23

### Expected behavior
The fixed fee in YEN is less than a Euro, but instead of showing 0 EUR, we have to display the cents.

### Additional context
(p1691072561961909-slack-C04DN7Q51KK)

### PR DESCRIPTION
**Pull request by mordeth**
Fixes #6944

#### Changes proposed in this Pull Request
A temporary way of fixing a bug where the Euro currency is displayed as a zero-decimal country for Japanese merchants. 

Before the fix:
Screenshot 2023-08-07 at 15 46 23

After the fix:
Screenshot 2023-08-07 at 15 45 31

#### Testing instructions
- Connect a Japanese account and enable multi-currency.
- Set the currency from the multi-currency widget to EUR.
- Create an order with EPS.
- Navigate to `Payments` -> `Transactions` and open `Transaction details` for the recent order.
- Verify the fixed Base fee is displayed as 0,28 EUR instead of 0 EUR.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6945` or branch name `fix/euro-displayed-as-zerodecimal-currency-for-japan` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/euro-displayed-as-zerodecimal-currency-for-japan) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 3d557429c22015107cb36a0f190161f381e2d660
- Build time: 2023-08-08 08:38:46 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/utils/currency/index.js [hunk 1]
```diff
@@ -60,7 +60,7 @@ export const getCurrency = ( currencyCode, baseCurrencyCode = null ) => {
 				currency.decimalSeparator = baseCurrency.decimalSeparator;
 				currency.thousandSeparator = baseCurrency.thousandSeparator;
 				currency.symbolPosition = baseCurrency.symbolPosition;
-				if ( currency.precision !== 0 ) {
+				if ( currency.precision !== 0 && country !== 'JP' ) {
```
Comment (vbelolapotkov) [inline client/utils/currency/index.js:66]: I certainly see many problems from that fix:

1. Country and currency are not the same things. 
2. This logic doesn't explain why only JP is exception.
3. The fix is for very particular case. What about any other zero-decimal currencies?

Overall, from the quick glance it feels like the fix is for the symptom, not for the root problem.

Comment (mordeth) [reply client/utils/currency/index.js:66]: I agree. This is a temporary fix until we explore if removing the precision overwriting would cause any issues. 

1. Initially, I tried to rely on the `baseCurrencyCode`, but it is rarely present, and it anyway falls back to `currencyData[ country ]`, which still depends on the country, not the currency. We are retrieving the Japanese currency data and overwriting the selected currency precision.
2. Agree. A comment should be added explaining why JP is an exception.
3. That PR doesn't aim to resolve the root problem. That way of overwriting the currency data is causing other non-significant issues and undoubtedly more issues in the future for other zero-decimal currencies and needs to be reworked.

Comment (elazzabi) [reply client/utils/currency/index.js:66]: I also added a small comment stating that this is a temporary fix https://github.com/Automattic/woocommerce-payments/pull/6945/commits/3d557429c22015107cb36a0f190161f381e2d660

**Review by elazzabi — APPROVED** [review]
Looks good to me 👍

**Review by anu-rock — COMMENTED** [review]
LGTM (code-only review).

Noting again that this is a temporary fix that we aim to refactor in v6.4.

___

#### Review checklist

| Parameter  | Result |
| ------------- | ------------- |
| Approach  | ✅ All good |
| Implementation  | ✅ All good |
| Automated tests  | Not applicable |
| Naming  | Not applicable |
| Typing  | Not applicable |
| Code comments  | ✅ All good |
| Changelog  | ✅ All good |
| Testing instructions  | 👍 Almost good |
| Manual testing  | Skipped |

**Review by anu-rock — APPROVED** [review]

**Comment by anu-rock** [comment]
**Update:** I followed up with manual testing and found the fix to be working 👍 

image

File: client/utils/currency/index.js (hunk 1 above)
Comment (vbelolapotkov) [reply client/utils/currency/index.js:66]: Thanks, with comment it looks much better.

**Comment by souravdebnath1986** [comment]
image
Saw this late, thanks for looking at the fix. The one aspect which is confusing is that the fixed fee callout in the 'Base fee' field is in EUR. Normally for multi-currency transactions, there are 2 fee callouts as shown below - Fee in the transaction currency (so makes sense to have the fixed fee callout in EUR here) and Base Fee which is in the merchant currency. 
image
