### PR TITLE
Fix: BNPL payment methods should work when available in the Pay For Order page

### LINKED ISSUE #8254: BNPL payment method issue in the "Customer payment page" flow
### Describe the bug

The Affirm / Afterpay / Klarna payment methods cannot be paid using the "Customer payment page" flow

### To Reproduce

1. In the wp-admin Order page, create an Order with the "pending payment" status, assign it to a customer
2. Copy the "Customer payment page" URL and open it as the assigned customer
3. The Pay for Order page is opened. Open the Chrome browser's console log, and see that there is a `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'value')` error.
4. Try choosing Klarna, click the "Pay for Order" button. Observe that there is a `Cannot read properties of null (reading 'submit')` error and the page is stuck

### Screenshots

image

image

image

### Expected behavior

BNPL payment methods should be usable on that page, or they need to be hidden if the flow is not supported

### PR DESCRIPTION
**Pull request by danielmx-dev**
Fixes #8254

#### Changes proposed in this Pull Request

- Make sure the `wcpayCustomerData` global variable is properly rendered. A couple issues related to this were fixed:
  - The `payment_fields()` code was running before the `wcpay-upe-checkout` script was registered, so when `wp_localize_script` ran, nothing was added to the page. This problem was solved for the `wcpay_upe_config` variable by adding a callback to `wp_footer` but the same fix wasn't applied to `wcpayCustomerData`. This PR should make both work consistently.
  - When multiple Payment Methods were enabled, the callbacks to localize the scripts were queued multiple times. This was unnecessary given that the variables always had the same names, so the values were overridden. To prevent rendering unnecessary data, I'm using a workaround using a dummy action to verify if the callback already run once.
- Pass default values to the payment elements when available. 
- `is_enabled_at_checkout` was updated so it checks the order data instead of the cart data to determine availability

#### Testing instructions

* Use a US WooPayments account.
* Enable Affirm, AfterPay/ClearPay, and Klarna.
* In WP Admin, create an order, make sure to include customer details as Name, Email, and Country (must be US). Add a product of at least 50 USD (which is Affirm's minimum amount).
* Copy the **Customer payment page** URL.
* As a customer, go to the Customer payment page.

**Before (using develop)**
BNPL payment methods showed up but nothing was rendered when selected. (Verify for all BNPL methods)
image

Clicking **Pay for Order** results in an error.
image

**After (Using this branch)**
The contents of the BNPL methods is properly rendered, customer information is prefilled based on the data filled for the order.
image

Submitting the order should result in a successful payment. Test this for all BNPL methods (Klarna, Afterpay/Clearpay, and Affirm).

**Testing payment method availability**
* In WP Admin, update the Billing information of the pending order to another country.
* If you reload the Pay for Order page, the BNPL methods should no longer show up.
image

* In WP Admin, restore the billing country to US but change the line items so the total is less than 50 USD.
* Reload the pay for order page, Affirm should not be displayed:
image

# Regression Testing

* Make sure that Credit Cards (with and without 3DS) continue to work as expected in the pay for order flow.
* Test the Add Payment Method flow to make sure cards can still be added.
* Test the Classic Checkout and Blocks Checkout flow to make sure BNPL and Card payments still work as expected.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9670` or branch name `fix/8254-bnpl-pay-for-order` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8254-bnpl-pay-for-order) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 296a3b815ac5415485c7a7727779d452ade62b96
- Build time: 2024-11-06 17:03:58 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: tests/unit/test-class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -706,6 +731,77 @@ function ( $order ) {
 		$this->assertFalse( $afterpay_method->is_enabled_at_checkout( 'US' ) );
 	}
 
+	public function test_payment_methods_enabled_based_on_currency_limits() {
+		WC_Helper_Site_Currency::$mock_site_currency = 'USD';
+
+		WC()->session->init();
+		WC()->cart->empty_cart();
+		// Total is 100 USD, which is above both payment methods (Affirm and AfterPay) minimums.
+		WC()->cart->add_to_cart( WC_Helper_Product::create_simple_product()->get_id(), 10 );
```
Comment (danielmx-dev) [inline tests/unit/test-class-wc-payment-gateway-wcpay.php:740]: The amount could be defined a bit more "dynamically" (in case the limits change in the future) but I didn't want to overcomplicate things, lmk what do you think.

File: includes/class-wc-payments-checkout.php [hunk 2]
```diff
@@ -376,16 +376,35 @@ public function payment_fields() {
...
 				$prepared_customer_data = $this->customer_service->get_prepared_customer_data();
 				if ( ! empty( $prepared_customer_data ) ) {
-					wp_localize_script( 'wcpay-upe-checkout', 'wcpayCustomerData', $prepared_customer_data );
+					add_action(
+						'wp_footer',
+						function () use ( $prepared_customer_data ) {
+							if ( ! did_action( '__wcpay_customer_data_localized' ) ) {
+								wp_localize_script( 'wcpay-upe-checkout', 'wcpayCustomerData', $prepared_customer_data );
+							}
+							do_action( '__wcpay_customer_data_localized' );
```
Comment (frosso) [inline includes/class-wc-payments-checkout.php:405]: I like the way you're leveraging `do_action`/`did_action` to check whether a function had already been executed.

File: includes/payment-methods/class-upe-payment-method.php [hunk 3]
```diff
@@ -171,11 +171,26 @@ public function is_enabled_at_checkout( string $account_country ) {
 
 		// This part ensures that when payment limits for the currency declared, those will be respected (e.g. BNPLs).
 		if ( [] !== $this->limits_per_currency ) {
-			$currency = get_woocommerce_currency();
+			$order = null;
+			if ( is_wc_endpoint_url( 'order-pay' ) ) {
+				$order = wc_get_order( absint( get_query_var( 'order-pay' ) ) );
```
Comment (frosso) [inline includes/payment-methods/class-upe-payment-method.php:176]: (minor) WooCommerce Core does a similar check on the currency amount (although we're not leveraging it because of the multi-currency setup): https://github.com/woocommerce/woocommerce/blob/7eabbe4ecd7dd1cff6a36055c8a07c3bdf64abb1/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php#L290-L308

However, I noticed that they first do:
```php
$order_id = absint( get_query_var( 'order-pay' ) )
```

And then:
```php
if ( 0 < $order_id ) {
  // proceeds with getting the order
}
```

However, we're not doing the check on the `$order_id`, here.
I'm not sure if you considered it - but wanted to raise it anyways. I'm guessing that if we call `wc_get_order()` with `''` (empty string - the default value returned by `get_query_var()`, we might get the order with id `0`. Is that something we should be concerned about?
I don't think we'd need to be concerned about it, but wanted to double-check with you.

File: includes/payment-methods/class-upe-payment-method.php [hunk 4]
```diff
@@ -171,11 +171,26 @@ public function is_enabled_at_checkout( string $account_country ) {
...
+				$order = is_a( $order, 'WC_Order' ) ? $order : null;
+			}
+
+			if ( $order ) {
+				$currency = $order->get_currency();
+			} else {
+				$currency = get_woocommerce_currency();
+			}
 			// If the currency limits are not defined, we allow the PM for now (gateway has similar validation for limits).
 			// Additionally, we don't engage with limits verification in no-checkout context (cart is not available or empty).
```
Comment (frosso) [inline includes/payment-methods/class-upe-payment-method.php]: Should we be concerned with (or change) this comment, since maybe the pay-for-order could be considered a "no-checkout context"? 👀 

I wonder if, instead, we should perform a check like this:
```php
			$currency = get_woocommerce_currency();
			if ( $order ) {
				$currency = $order->get_currency();
			}

			// If the currency limits are not defined, we allow the PM for now (gateway has similar validation for limits).
			$total = null;
			if ( $order ) {
				$total = $order->get_total();
			} elseif ( isset( WC()->cart ) ) {
				$total = WC()->cart->get_total( '' );
			}

			if ( isset( $this->limits_per_currency[ $currency ] ) && ! empty( $total ) ) {
				$amount = WC_Payments_Utils::prepare_amount( $total, $currency );
```

File: client/checkout/utils/upe.js [hunk 5]
```diff
@@ -119,6 +119,18 @@ export const getUpeSettings = () => {
 		};
 	}
 
+	if ( window.wcpayCustomerData ) {
```
Comment (frosso) [inline client/checkout/utils/upe.js:122]: It took me a bit to find the other area where we check for `window.wcpayCustomerData` and pass such data to Stripe, and to identify if there are any opportunities for improvement - but I think this is the only way, good find!

**Review by frosso — APPROVED** [review]
Looks good, just one question on the "no-checkout context" and whether that area needs an adjustment. Good improvements 👍

File: includes/payment-methods/class-upe-payment-method.php (hunk 3 above)
Comment (danielmx-dev) [reply includes/payment-methods/class-upe-payment-method.php:176]: I followed the same approach we already use to retrieve the order in the Pay for Order flow: https://github.com/Automattic/woocommerce-payments/blob/c061a0874a4af2d3dbe25a88c6cca44015d02a5a/includes/class-wc-payments-checkout.php#L264-L268

I also checked the source code for `wc_get_order` and it should return false in case we sent either `0` or `''`.
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-order-factory.php#L28-L32
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-order-factory.php#L210-L221

File: client/checkout/classic/payment-processing.js [hunk 6]
```diff
@@ -192,6 +192,16 @@ function createStripePaymentMethod(
...
 
+	if (
+		getUPEConfig( 'isOrderPay' ) &&
+		[ 'afterpay_clearpay', 'affirm' ].includes( paymentMethodType ) &&
+		params?.billing_details?.address &&
+		! params.billing_details.address.line1
+	) {
+		// These payment methods don't accept an address object with partial information.
+		delete params.billing_details.address;
+	}
```
Comment (danielmx-dev) [inline client/checkout/classic/payment-processing.js]: I was able to successfully place orders with Affirm and Afterpay by adding this code.

Although I was using test mode, the order seems to have all the correct information. I assume any missing details would be captured by Affirm/Afterpay?

**Comment by danielmx-dev** [comment]
@frosso I pushed some changes to improve the compatibility with BNPL payment methods and their requirements. I also updated the test instructions to include regression testing for other payment methods/flows.

**Review by frosso — APPROVED** [review]
Can confirm, it's working now 👍 thanks for catching it!
