### PR TITLE
Fix Afterpay and Affirm requirements in order pay flow

### LINKED ISSUE #10572: Fix isMissingRequiredAddressFieldsForBNPL function
### Describe the bug

When https://github.com/Automattic/woocommerce-payments/pull/9670 was implemented, an error was introduced during the development that wasn't caught during testing. The [isMissingRequiredAddressFieldsForBNPL](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/payment-processing.js#L131) function was designed to validate the address fields provided by the pay for order flow to make sure the minimum requirements for affirm and afterpay are met; however, an error in the first line prevents the function to actually run as expected:

```js
if ( [ 'afterpay_clearpay', 'affirm' ].includes( paymentMethodType ) ) {  // <- this should be negated
```

We need to fix that condition and also make sure the original issue is still solved for BNPL payment methods.

* Use a US WooPayments account.
* Enable Affirm, AfterPay/ClearPay, and Klarna.
* In WP Admin, create an order, make sure to include customer details as Name, Email, and Country (must be US). Add a product of at least 50 USD (which is Affirm's minimum amount).
* Copy the **Customer payment page** URL.
* As a customer, go to the Customer payment page.
* Perform the following with each BNPL payment method.
* Try to place the order

### Actual behavior
Affirm
Image

Afterpay
Image

Klarna: Works as expected.

### Expected behavior
All BNPL payment methods should be able to place an order. If we find that it's actually impossible to place an order with certain missing billing data, we need to hide that payment method.

### PR DESCRIPTION
**Pull request by danielmx-dev**
Fixes #10572
Fixes WOOPMNT-4861

#### Changes proposed in this Pull Request

 - Update conditional that cleans up billing details for the BNPL payment methods on the Pay for Order page.
 - Update availability check for the BNPL methods to exclude them based on billing data.
#### Testing instructions

 * Create a US-based merchant account.
 * Enable Affirm, Afterpay and Klarna payment methods.
 * Go to `WooCommerce` > `Orders` > `Add order`
 * Include products above USD 50 into the order to match BNPL requirements.
 * Edit billing details to include Name, Last name, Country and State, but no other fields.
 * Open "Customer payment page" link.
 * Ensure that only Klarna is available besides "Cards".
 * Check that checking out with Klarna works.
 * Go back to the order page and update Billing details to include Address line 1, City and Postcode.
 * Open "Customer payment page" link.
 * Affirm and Afterpay should become available. Check that checking out is possible with both payment methods.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10586` or branch name `fix/afterpay-affirm-order-pay-flow` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/afterpay-affirm-order-pay-flow) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: ebc0630eb054cd6e1550c77e604877d36e41c9ce
- Build time: 2025-08-18 12:34:54 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/checkout/classic/payment-processing.js [hunk 1]
```diff
@@ -131,7 +131,7 @@ function submitForm( jQueryForm ) {
  * @return {boolean} True, if there are missing address fields. False, if the validation passes or is not applicable.
  */
 function isMissingRequiredAddressFieldsForBNPL( params, paymentMethodType ) {
-	if ( [ 'afterpay_clearpay', 'affirm' ].includes( paymentMethodType ) ) {
+	if ( ! [ 'afterpay_clearpay', 'affirm' ].includes( paymentMethodType ) ) {
```
Comment (mgascam) [inline client/checkout/classic/payment-processing.js]: minor: We have constants for payment method IDs in `client/constants/payment-method.ts`, can we use them?

**Review by mgascam — COMMENTED** [review]
The code changes look good, just left a minor suggestion. I found something unexpected while testing in a fresh JN site, I'll share more details in the Linear issue

File: client/checkout/classic/payment-processing.js (hunk 1 above)
Comment (dmvrtx) [reply client/checkout/classic/payment-processing.js]: Good call. Updated in ebc0630eb

**Review by htdat — APPROVED** [review]
Thanks for moving this PR forward, @dmvrtx!  

Manual tests work well, and code changes look good.
