### PR TITLE
Handle IPP failure webhooks

### LINKED ISSUE #9220: Payment failed webhook handler ignores IPP payment method
### Describe the bug

The method that handles the `payment_intent.payment_failed` webhook takes not action when the payment method is specified as 'card_present'.

As a consequence, there is no note added to the order informing the merchant of the failure and the order status does not change to Failed

### To Reproduce

1. Place an order using Woocommerce mobile app
2. Try to capture it in a way that triggers a `payment_failed`error.

### Actual behavior

The order does not transition to failed status. There is no note added to the details of the order informing the merchant of the error.

### Expected behavior

The order transitions to failed status. A note is added to the order informing the merchant of the error.

### Additional context

We need to add the `card_present` payment method to the array of actionable payment methods in `process_webhook_payment_intent_failed` method.

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #9220

We detected that some webhooks related to IPP failure flows are not correctly handled in the client.

p2: p91TBi-bJV-p2#comment-12671
Slack: p1722407912357319-slack-C01BPL3ALGP

#### Changes proposed in this Pull Request

- Adds IPP payment to the list of actionable methods of the payment failed webhook.
- When the order id is not present in the payment intent metadata, attempt to find it in the charge metadata.

#### Testing instructions

Please check PdfdoF-D-p2 for detailed instructions. To get you started:

* Install in your test device a development build of the Android mobile app. You can get one from any open PR in the repo, like https://github.com/woocommerce/woocommerce-android/pull/12228. You'll need it to simulate a card reader.
* Create a build of WooPayments plugin based on the current branch (npm run build:release or Jetpack Beta) and upload it to your test site.
* Launch the app and connect it with your test site.
* Go to Settings > Developer Options and enable the simulated card reader
* Create an order and set any amount that ends with 5 cents i.e $10.05 to trigger a declined error.
* In the order, click on "Collect Payment".
* Follow the prompts in the app to place the payment with the simulated card reader until the payment fails.
* Go to the details of the order on your test site. 
* Check the status of the order is Failed and there's an order note with information of the failure.

Screenshot 2024-08-06 at 15 59 54

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9198` or branch name `add/ipp-missing-failure-webhooks` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/ipp-missing-failure-webhooks) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 443f2a75438f61eb94c73f2a7fcf20be8d2e683a
- Build time: 2024-08-06 13:36:24 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payments-webhook-processing-service.php [hunk 1]
```diff
@@ -154,6 +154,12 @@ public function process( array $event_body ) {
 			case 'charge.refunded':
 				$this->process_webhook_refund_triggered_externally( $event_body );
 				break;
+			case 'charge.failed':
+				// TODO: Implement this. During manual tests with a physical card reader, we found that this event can also be triggered:
+				// https://dashboard.stripe.com/test/connect/accounts/acct_1KBG7y2HCBWb6DsL/payments/ch_3PicUz2HCBWb6DsL1hY7VS3F
+				// https://dashboard.stripe.com/test/connect/accounts/acct_1KBG7y2HCBWb6DsL/payments/ch_3PicVR2HCBWb6DsL1sXHsjfa
+				// Can we just call $this->process_webhook_payment_intent_failed( $event_body ); ?
```
Comment (zmaglica) [inline includes/class-wc-payments-webhook-processing-service.php]: I think you cannot since the event body could be different.  I cannot open the listed events, but I think that the payment_intent failed is sent here too. Is that correct?

File: includes/class-wc-payments-webhook-processing-service.php [hunk 2]
```diff
@@ -414,11 +421,13 @@ private function process_webhook_payment_intent_failed( $event_body ) {
 
 		$actionable_methods = [
 			Payment_Method::CARD,
+			Payment_Method::CARD_PRESENT,
```
Comment (zmaglica) [inline includes/class-wc-payments-webhook-processing-service.php:417]: Maybe this line is only needed in order to make things work as expected.

File: includes/class-wc-payments-webhook-processing-service.php (hunk 1 above)
Comment (mgascam) [reply includes/class-wc-payments-webhook-processing-service.php]: Yes, the payment_intent failed is also sent (I did not see it initially because I was looking at the charge details and not the payment_intent). It also sends a payment_intent.canceled.

We should be good with adding the card present to the actionable methods, but Jirka tested it (details in the p2 thread) and it did not seem to work. We need to keep investigating why

**Review by zmaglica — APPROVED** [review]

**Review by malinajirka — APPROVED** [review]
I've tested the build on my site with the mobile app and it works as expected, thanks! The code looks fine to my newbie eye, but I don't have enough codebase and language knowledge to properly review it. 

Thanks for working on this 🙇
