### PR TITLE
Fix broken dispute details UI

### LINKED ISSUE #7958: Dispute details UI styles are broken
### Describe the bug

The dispute details section of the Transaction Details screen is rendered incorrectly.

image

### To Reproduce

* As a shopper, create a disputed order by purchasing a test product using the card `4000000000000259` at checkout.
* As a merchant, navigate to Payments -> Disputes and click the row for the dispute you just created. You will be taken to the "Transaction Details" screen.
* Notice the dispute details are rendered incorrectly.

### Additional context

* Picked up by GS release testing: see p1703587731891169/1703587650.615579-slack-C011ENB20Q1.
* It seems to be related to [styling changes](https://github.com/Automattic/woocommerce-payments/commit/f73f0df93f336101ffe995ec47849c0a8a60b589#diff-665428377b787ea358c2e2210532d896d44b2fb05d88184a0381916fb75e5709) introduced in #7742.
    https://github.com/Automattic/woocommerce-payments/blob/62c69cbe63b6987394f88363b5b97efefc09e206/client/payment-details/summary/style.scss#L11-L14 	
* Related: I've opened #7960 since disputed transactions should not show the refund dropdown if they are not refundable.

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #7958

Note: see #7742 for the original implementation of the transaction refund menu & modal.

#### Changes proposed in this Pull Request

This PR fixes the dispute details UI within the Transaction Details screen.

It removes a global CSS declaration that inadvertently changes the styles of the dispute details. Using the `Flex` component will apply the intended `flex-direction: row` style directly to the top card on this page without impacting other page components.

Also, the payment status chip has been allowed to wrap on small viewports.

**Before**
image

**After**

image

Related: I've opened #7960 since disputed transactions should not show the refund dropdown if they are not refundable.

#### Testing instructions

* As a shopper, create a disputed order by purchasing a test product using the card `4000000000000259` at checkout.
* As a merchant, navigate to Payments -> Disputes and click the row for the dispute you just created. You will be taken to the "Transaction Details" screen.
* Ensure the dispute details are rendered correctly.
* Ensure the refund dropdown menu is rendered correctly.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7959` or branch name `fix/7958-transaction-details-dispute-details-broken-ui` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7958-transaction-details-dispute-details-broken-ui) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b5d1da3e16264a1b3936814dcbfba568d2cdab39
- Build time: 2024-01-02 02:21:54 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/payment-details/summary/index.tsx [hunk 1]
```diff
@@ -243,307 +243,314 @@ const PaymentDetailsSummary: React.FC< PaymentDetailsSummaryProps > = ( {
...
-									{ formatExplicitCurrency(
-										-balance.refunded,
-										balance.currency
-									) }
-								</p>
-							) : (
-								''
-							) }
-							<p>
+				<Flex direction="row" align="start">
```
Comment (Jinksi) [inline client/payment-details/summary/index.tsx:246]: Although this looks like a large diff, the only change is wrapping the contents of this card in a `<Flex />` component.

**Review by shendy-a8c — APPROVED** [review]
Looks good!

Confirmed that now the dispute details section on the transaction details page is not broken.

The refund menu after clicking the three dots also shows up correctly.

Screenshot 2024-01-02 at 12 11 11
