### PR TITLE
BNPL - Fix sending of shipping data for Afterpay in classic checkout

### LINKED ISSUE #6792: BNPL - Fix the PM conditional in Afterpay shipping address sending check
### Describe the bug

For Afterpay, we have a requirement of sending Shipping Address, in the request. We had introduced [this code](https://github.com/Automattic/woocommerce-payments/pull/6492/files#diff-bcfd303d507c33a27671935e724ee64d0df30ff2a18bb6ef4c94f28d48190124R1119) in an earlier PR to to do that. ( [Link in the develop branch ](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L1119)) 

Props to @FangedParakeet who reminded that `$payment_information->get_payment_method()` would not return the name of the payment method  (i.e. `afterpay_clearpay` ). Instead it returns the payment method id similar to `pm_xxxxxyyyy...` . Because of this the code in the if statement will never execute. 

### Additional context
Discussion on slack with hints to resolve this 
p1689060282807879-slack-C02C00HCJ8J
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/pull/6800
- [ ] https://github.com/Automattic/woocommerce-payments/pull/6838
```

### PR DESCRIPTION
**Pull request by nagpai**
Fixes part of #6792 

#### Changes proposed in this Pull Request

Make sure for Afterpay payments, the shipping address is sent when both billing and shipping address are separately mentioned at checkout. So far, only the billing address was sent, even if there was a shipping address separately specified. 

The PR also does the following refactor: 

* Remove redundant PHP code that attempted to send shipping address when payment method was Afterpay
* Move`getShippingDetails` and `getBillingDetails` methods to Utils file so that it can be used in both Legacy and Split UPE versions without repeating the same code. 

There will be a separate PR for blocks checkout. 

#### Testing instructions

1.  Make sure your local setup is connected ot an account with Afterpay enabled
2. Within WooPayments Dev tools make sure to select `Legacy UPE` 
3. Open the site in an incognito window and try to do a checkout in classic checkout with Afterpay
4. Add only the Billing address without opting to add a separate shipping address
5. Open the browser console to monitor any errors ( console and network tab ) 
6. Complete the checkout and wait for the test redirect screen of Stripe to appear that shows the data submitted in the transaction
7. Within the Payment Intent details on that page, please check the Shipping address, it should be the billing address
8. Repeat the test transaction steps - this time - add a separate Shipping address.
9. The submitted Payment intent information on the test Afterpay authorization page should show the specified Billing address , and not the shipping address.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6800` or branch name `fix/6792-afterpay-shipping-data` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6792-afterpay-shipping-data) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 07c54dad428dd9b3753d12fa031ab4c12e38e861
- Build time: 2023-07-25 08:52:47 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by dmvrtx — APPROVED** [review]
Looks good and works as expected on the local setup. Extra thanks for refactoring through extracting and unifying methods!

File: client/checkout/utils/upe.js [hunk 1]
```diff
@@ -300,3 +300,71 @@ export const getStripeElementOptions = (
...
+/**
+ * Converts form fields object into Stripe `shipping` object.
+ *
+ * @param {Object} fields Object mapping checkout shipping fields to values.
+ * @return {Object} Stripe formatted `shipping` object.
+ */
+export const getShippingDetails = ( fields ) => {
+	// Shipping address is needed by Afterpay. If available, use shipping address, else fallback to billing address.
+	if (
+		document.getElementById( 'ship-to-different-address-checkbox' ) &&
```
Comment (kalessil) [inline client/checkout/utils/upe.js]: How reliable is picking the element ID in the context of WP customizations, things like Elementor?

Comment (kalessil) [reply client/checkout/utils/upe.js]: Also, did we test blocks integration here?

Comment (nagpai) [reply client/checkout/utils/upe.js]: >Also, did we test blocks integration here?

I have a separate PR for [block checkout](https://github.com/Automattic/woocommerce-payments/pull/6838). Did you mean that? or perhaps some other arrangement?

Comment (kalessil) [reply client/checkout/utils/upe.js]: Yes, that one.

Comment (nagpai) [reply client/checkout/utils/upe.js]: >How reliable is picking the element ID in the context of WP customizations, things like Elementor?

This is a good point. I will check this deeper.  I saw a similar check in the existing code though [for StripeLink](https://github.com/Automattic/woocommerce-payments/blob/a3039cdca03d6fcb41f2cd720757c4601e9ea46a/client/checkout/classic/upe.js#L268). 

Let me do a check on Elementor, or find a better way to trace this 👍

Comment (kalessil) [reply client/checkout/utils/upe.js]: Worth re-evaluating, thanks.

Comment (nagpai) [reply client/checkout/utils/upe.js]: @kalessil  - I did a deeper check with external themes like Flatsome ( proprietary ), and Astra ( Elementor and Beaver Builder versions ). I found that it is better to use the checkbox form submit field instead of the CSS ID. It seems to work correctly across all the themes I mentioned above, and Storefront too. 

I have made the change here, and I hope this is a good solution
f0592fc

Comment (kalessil) [reply client/checkout/utils/upe.js]: That looks much better, thanks!

File: client/checkout/utils/upe.js [hunk 2]
```diff
@@ -300,3 +300,71 @@ export const getStripeElementOptions = (
...
 	return options;
 };
+
+/**
+ * Converts form fields object into Stripe `shipping` object.
+ *
+ * @param {Object} fields Object mapping checkout shipping fields to values.
+ * @return {Object} Stripe formatted `shipping` object.
+ */
+export const getShippingDetails = ( fields ) => {
```
Comment (kalessil) [inline client/checkout/utils/upe.js:337]: @nagpai: I can see the phone is removed compared to the original functions. Is it intended?

File: client/checkout/utils/upe.js [hunk 3]
```diff
@@ -300,3 +300,71 @@ export const getStripeElementOptions = (
...
+				country: fields.shipping_country || '-',
+				line1: fields.shipping_address_1 || '-',
+				line2: fields.shipping_address_2 || '-',
+				city: fields.shipping_city || '-',
+				state: fields.shipping_state || '-',
+				postal_code: fields.shipping_postcode || '-',
+			},
+		};
+	}
+	return {
```
Comment (kalessil) [inline client/checkout/utils/upe.js]: That's pretty much a code duplicate. We can refactor this a bit like this:

```javascript
let billingAsShippingAddress = getBillingDetails(fields);
delete billingAsShippingAddress.email;

return billingAsShippingAddress;
```

**Review by kalessil — CHANGES_REQUESTED** [review]

File: client/checkout/utils/upe.js (hunk 2 above)
Comment (nagpai) [reply client/checkout/utils/upe.js:337]: Intentionally not included, since the [sample information](https://stripe.com/docs/payments/afterpay-clearpay/accept-a-payment?platform=web&ui=checkout#accept-a-payment) does not include phone, indicating its not needed by Afterpay . 

The classic checkout fields, as well as form submit data, does not include a phone number for shipping. 

image

image

File: client/checkout/utils/upe.js (hunk 3 above)
Comment (nagpai) [reply client/checkout/utils/upe.js]: Thanks for this solution! I was feeling a bit itchy about the repetition. I will keep this in mind for future patterns too. 🙏 

Resolved here: 07c54da

File: client/checkout/utils/upe.js (hunk 2 above)
Comment (kalessil) [reply client/checkout/utils/upe.js:337]: Sounds good!

File: client/checkout/utils/upe.js [hunk 4]
```diff
@@ -300,3 +300,64 @@ export const getStripeElementOptions = (
...
+				line1: fields.shipping_address_1 || '-',
+				line2: fields.shipping_address_2 || '-',
+				city: fields.shipping_city || '-',
+				state: fields.shipping_state || '-',
+				postal_code: fields.shipping_postcode || '-',
+			},
+		};
+	}
+
+	const billingAsShippingAddress = getBillingDetails( fields );
```
Comment (kalessil) [inline client/checkout/utils/upe.js:358]: Is delete working with constant-variables?

**Review by kalessil — COMMENTED** [review]
LGTM (cod review only). Please make one more manual test before merging.

**Review by kalessil — APPROVED** [review]

File: client/checkout/utils/upe.js (hunk 4 above)
Comment (nagpai) [reply client/checkout/utils/upe.js:358]: It's working here, since we are deleting the properties within the const object. Props to ESLint :D that gave suggestion to replace `let` with `const`, since there is no reassignment of the whole object.

Comment (kalessil) [reply client/checkout/utils/upe.js:358]: Gotcha, thanks!

**Comment by nagpai** [comment]
>LGTM (cod review only). Please make one more manual test before merging.

One more round of manual testing done and looks fine.
