### PR TITLE
Restrict Stripe Link to credit card payment method and improve cleanup

### LINKED ISSUE #9814: Stripe Link initialized with non-card payment methods
### Describe the bug
Stripe Link in Blocks checkout is initialized for payment methods other than card, which can lead to confusion during the checkout.

https://github.com/user-attachments/assets/d302d7ad-9a81-477a-b1d5-e30444978ac6

### To Reproduce

1. Navigate to Blocks checkout while having more than one payment method enabled on the checkout together with Stripe Link
2. Open a non-card payment method
3. See the Stripe Link button appearing in the email input element

### Expected behavior
Stripe Link should load with credit card only.

### PR DESCRIPTION
**Pull request by timur27**
Fixes https://github.com/Automattic/woocommerce-payments/issues/9814

#### Testing instructions

_**For Blocks checkout**_

1. The behavior described in [#9814](https://github.com/Automattic/woocommerce-payments/issues/9814) is no longer reproducible because the Link button for non-card payment methods is no longer present within the email input field.
2. Stripe Link is functional and is available (both through the button within the email input element and through the `keyup` eventlistener within email input element) **_only_** when credit card payment gateway is selected

**_For the shortcode:_**
Ensure that if a non-card payment gateway is selected and the Link button is clicked, the following behaviors occur
* Having the credit card gateway selected and a saved payment token checked, the new payment token checkbox is automatically checked when user clicks the Link button within the email input element
* The form falls back from the selected payment method to card payment gateway's new payment method input element if
    * new payment token checkbox was previously selected within CC gateway
    * saved payment token checkbox if it was previously selected within CC gateway

Sanity checking the Link functionality in general with shortcode checkout
* open the shortcode checkout and provide a non-registered Stripe Link email: you should be able to enter your phone and name form provided by Link after you enter credit card details.
* prepare another cart and open the shortcode checkout: click the Link button in the email element and confirm that autofill works as expected. Complete the transaction by either closing the page or purchasing the product.
* (if you don't have saved tokens) save a new payment method either by navigating to My account -> Payment methods or by saving payment method during the payment. Make sure that the saved payment method is set as default.
* navigate to checkout page, confirm the saved payment token is selected by default
* click Stripe Link button and verify that together with Link modal popping up, the selected payment method is switched from saved token to the new payment element
* complete the autofill modal steps and confirm you have the right payment method selected
* complete the purchase, navigate to order details in the admin panel, open payment intent details and confirm payment method is Link on the transaction details page
* navigate to shortcode checkout page again but this time just pay with the saved payment token (card) which is selected by default
* confirm that the payment method is now CC on the transaction details page

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9822` or branch name `fix/stripe-link-button` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/stripe-link-button) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: d87b45266fdbb7dd870390b3962e8579f7725482
- Build time: 2024-12-02 11:28:32 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/checkout/stripe-link/index.js [hunk 1]
```diff
@@ -4,6 +4,13 @@
...
 export const switchToNewPaymentTokenElement = () => {
+	// Switch to card payment method before enabling new payment token element
+	document
+		.querySelector(
+			'input[name="payment_method"][value="woocommerce_payments"]'
+		)
+		?.click();
+
 	const newPaymentTokenElement = document.getElementById(
 		'wc-woocommerce_payments-payment-token-new'
```
Comment (timur27) [inline client/checkout/stripe-link/index.js:15]: Once https://github.com/Automattic/woocommerce-payments/pull/9782 is merged, I think we could look new token element from within the `.wcpay-upe-form` container we created there, but since I'm unsure about PR merging sequence just yet, I avoided to set that branch as the upstream for this PR.

File: client/checkout/stripe-link/index.js [hunk 2]
```diff
@@ -4,6 +4,13 @@
 import { dispatchChangeEventFor } from '../utils/upe';
 
 export const switchToNewPaymentTokenElement = () => {
+	// Switch to card payment method before enabling new payment token element
+	document
+		.querySelector(
+			'input[name="payment_method"][value="woocommerce_payments"]'
+		)
+		?.click();
+
```
Comment (timur27) [inline client/checkout/stripe-link/index.js:13]: It was 
```js
	document
		.querySelector( '.wcpay-upe-element[data-payment-method-type="card"]' )
		?.closest( '.wc_payment_method' )
		?.querySelector( 'input[type="radio"]' )
		?.click();
```
at first but after our discussion in https://github.com/Automattic/woocommerce-payments/pull/9782#discussion_r1862359667, I switched to 

```js
	document
		.querySelector(
			'input[name="payment_method"][value="woocommerce_payments"]'
		)
		?.click();
```

File: client/checkout/stripe-link/index.js [hunk 3]
```diff
@@ -65,6 +73,11 @@ const enableStripeLinkPaymentMethod = async ( options ) => {
 		);
 		switchToNewPaymentTokenElement();
 	} );
+
+	return () => {
+		emailField.removeEventListener( 'keyup', handleKeyup );
+		removeLinkButton();
+	};
```
Comment (frosso) [inline client/checkout/stripe-link/index.js:80]: Discussed offline - we'll need to handle the early return on L54, because it's not returning a promise like the `client/checkout/blocks/payment-processor.js` expects it to when the email field is not present.
You could replace the early return with:
```
return Promise.resolve( () => null );
```

Comment (frosso) [reply client/checkout/stripe-link/index.js:80]: Errata corrige: my bad, since `enableStripeLinkPaymentMethod` is defined as `async`, it will always return a promise. All good here! :) sorry about the confusion!

Comment (timur27) [reply client/checkout/stripe-link/index.js:80]: You beat me by responding faster! 😄 
Agreed. I think returning a Promise would still be great for consistency https://github.com/Automattic/woocommerce-payments/pull/9822/commits/d87b45266fdbb7dd870390b3962e8579f7725482 👀

**Review by frosso — APPROVED** [review]
Changes look good 👍 

While testing the shortcode checkout, I noticed that the Link autofill doesn't seem to be working for me.
I cross-referenced the same changes on `develop`, and the same behavior happens. So I don't think it's related to your changes.
However, I still wanted to point it out in case you noticed something similar (or different).

In any case, since it doesn't seem to be related to these changes, I think this is good 👍 

https://github.com/user-attachments/assets/6f23077c-6657-4ef4-875e-05f76566d949

**Comment by timur27** [comment]
Interesting, thanks for bringing it up @frosso. I couldn’t reproduce this issue on either the `develop` or `fix/stripe-link-button` branches. It’s possible that we’re encountering a misbehavior triggered by a specific set of data or actions present in both branches. This is definitely worth investigating further.

If you agree, I can spend 10 minutes testing it tomorrow, or alternatively, I can create a backlog issue to ensure it gets double-checked.

https://github.com/user-attachments/assets/5ba6e0ae-fb9f-43c8-a135-be423e95b215
