### PR TITLE
Prevent WooPay modal from showing when editing theme

### LINKED ISSUE #5658: WooPay redirect triggers when customizing Blocks theme
### Describe the bug
WooPay checkout gets triggered when customizing the theme in wp-admin

### To Reproduce
- Go to wp-admin > WooCommerce > settings > advanced
- Set the checkout page to the Blocks checkout page
- Go to Appearance > Customize > WooCommerce > Checkout
- The WooPay redirect/OTP modal will show up if the email in the input is a valid WooPay account

### PR DESCRIPTION
**Pull request by leonardola**
Fixes #5658

#### Changes proposed in this Pull Request
This PR fixes a bug that would make the WooPay otp/redirect modal to show up when editing the theme in wp-admin when using the blocks checkout

#### Testing instructions
- Go to wp-admin > WooCommerce > settings > advanced
- Set the checkout page to the Blocks checkout page
- Go to Appearance > Customize > WooCommerce > Checkout
- The WooPay redirect/OTP modal must not show up
- As a customer try to checkout via WooPay in the blocks checkout page

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: client/checkout/blocks/index.js [hunk 1]
```diff
@@ -65,8 +65,24 @@ registerPaymentMethod( {
 	},
 } );
 
+/**
+ * Checks whether we're in a preview context.
+ *
+ * @return {boolean} Whether we're in a preview context.
+ */
+const isPreviewing = () => {
```
Comment (hsingyuc) [inline client/checkout/blocks/index.js]: I see we also have `isPreviewing` under `checkout/blocks`.  Should we move it to utils to prevent duplication and future maintenance?

File: includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php [hunk 2]
```diff
@@ -84,6 +84,15 @@ abstract protected function prepare_payment_information( $order );
...
 	private static $payment_method_meta_key = 'token';
 
+	/**
+	 * Stores a flag to indicate if the subscription integration hooks have been attached.
+	 *
+	 * The callbacks attached as part of maybe_init_subscriptions() only need to be attached once to avoid duplication.
+	 *
+	 * @var bool False by default, true once the callbacks have been attached.
+	 */
+	private static $has_attached_integration_hooks = false;
```
Comment (hsingyuc) [inline includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php]: Are these supposed to be in this PR?

**Review by hsingyuc — COMMENTED** [review]
@leonardola Thank you for working on this!  Do you mean this PR fixes [#5658](https://github.com/Automattic/woocommerce-payments/issues/5658)?   If hiding the WooPay express button on the customize checkout blocks is expected then the test works well for me.

File: client/checkout/blocks/index.js (hunk 1 above)
Comment (leonardola) [reply client/checkout/blocks/index.js]: Moved to a separate file and also fixed the button not showing so it looks the same as the classic checkout via ce1a7a68057b7ae7753d36efc0bb5b44247d7118

**Review by hsingyuc — APPROVED** [review]
Thank you for the fixes! Tests as expected and code LGTM.
