### PR TITLE
fix: UPE styles on block-based checkout

### LINKED ISSUE #11208: Bug: payments redirect text (`.Text--redirect`) overlaps when multiline
### Describe the bug

Payments methods in block based checkout text overlaps when multiline.

### To Reproduce

1. Enable custom payment methods (e.g. Klarna, iDEAL, EPS)
2. Add
3. Go to checkout
4. Choose some of those methods and narrow down the screen so the text overlaps

### Actual behavior
Text overlaps with each other

### Screenshots
1 | 2
-- | --
Image | Image

### Expected behavior
Text should appear multiline

### Desktop (please complete the following information):

* OS: OSX
* Browser: Chrome
* Version: 143.0.7499.109 

### Additional information:

1. I checked and `.Text--redirect` has `line-height: 0`. Disabling this style is enough to fix the issue. Unfortunately, given the dynamic nature of styles building I'm not sure where this styles is coming from.
2. Raised in 10620534-zd-a8c

### PR DESCRIPTION
**Pull request by frosso**
Fixes #11208
Fixes WOOPMNT-5564

#### Changes proposed in this Pull Request

Recent [WooCommerce Core block checkout styles changes](https://github.com/woocommerce/woocommerce/blob/7b78e2df7e7c64aa5d8d703d295139e80654a023/plugins/woocommerce/client/blocks/packages/components/text-input/style.scss#L6-L7) caused a performance regression in the `getAppearance` function, which computes styles for Stripe's Payment Element theming.

The `line-height` property was being computed to `0px`.
I added a backwards-compatible change to ensure that we can compute the `line-height` from additional elements on the page.

The previous implementation of `getFieldStyles` just grabbed the first available element. In our case, it would have been the email input field.
I needed a way to have a fallback mechanism. That's why I initially moved from `scope.querySelector` to `scope.querySelectorAll`. But that was too bad for performance. So I instead just increased the number of possible elements to gather the styles from, and ensured we get at least one of each selector (instead of just the first available on the page).

Before:
Screenshot 2025-12-16 at 12 09 49 AM

After:
Screenshot 2025-12-16 at 12 09 27 AM

With these changes, I'm also introducing a 20% performance improvement on the styles computation.
Before:
Screenshot 2025-12-15 at 11 49 22 PM
Screenshot 2025-12-15 at 11 49 12 PM
Screenshot 2025-12-15 at 11 48 53 PM
Screenshot 2025-12-15 at 11 48 44 PM

After:
Screenshot 2025-12-15 at 11 45 42 PM
Screenshot 2025-12-15 at 11 45 35 PM

#### Testing instructions

- Install one of the latest versions of WC ( e.g.: https://github.com/woocommerce/woocommerce/releases/tag/10.4.2 )
- Ensure you're using the block-based checkout
- Ensure you have at least one of the redirect-based methods enabled, like any of the BNPLs or Alipay or WeChat Pay
- As a customer, add a product to the cart
- As a merchant, navigate to the WooPayments Dev Tools and click on "Delete UPE appearance transients"
  - As an alternative, ensure that [all these returned attributes are `null`
](https://github.com/Automattic/woocommerce-payments/blob/e5aeb50deecd708e0ca706328602ae0f69ab717e/includes/class-wc-payments-checkout.php#L232-L238)
- As a customer, navigate to the block-based checkout page
- Select one of the redirect-based payment methods
- The styles shouldn't be messed up anymore

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: client/checkout/upe-styles/index.js [hunk 1]
```diff
@@ -56,6 +55,8 @@ export const appearanceSelectors = {
 		upeThemeTextSelectors: [
 			'.wc-block-components-checkout-step__description',
 			'.wc-block-components-text-input',
+			'.wc-block-components-radio-control__label',
+			'.wc-block-checkout__terms',
```
Comment (frosso) [inline client/checkout/upe-styles/index.js:59]: The problem was that some of these had `lineHeight` computed as `0`

File: client/checkout/upe-styles/index.js [hunk 2]
```diff
@@ -413,35 +414,70 @@ const hiddenElementsForUPE = {
...
 
 	const validProperties = upeRestrictedProperties[ upeElement ];
 
-	const elem = scope.querySelector( selector );
+	const elem = elements[ 0 ];
 
 	const styles = windowObject.getComputedStyle( elem );
 
 	const filteredStyles = {};
-	for ( let i = 0; i < styles.length; i++ ) {
```
Comment (frosso) [inline client/checkout/upe-styles/index.js:435]: Before: we were iterating over _all_ styles.
Now: we're iterating only over `validProperties`.

Before we were iterating over 300 computed styles and filtering only the ones we wanted.
Now we're iterating over the ones we want an filtering from the computed styles.

Much saving!

File: client/checkout/upe-styles/upe-styles.js [hunk 3]
```diff
@@ -116,7 +116,7 @@ export const upeRestrictedProperties = {
 	'.Tab': [ ...restrictedTabProperties ],
 	'.Tab--selected': [
 		...restrictedTabSelectedProperties,
-		borderOutlineBackgroundProps,
```
Comment (frosso) [inline client/checkout/upe-styles/upe-styles.js:119]: This was a bug in the previous implementation.

**Review by rtio — APPROVED** [review]
Image

Image

Tested in this JN site: 39e7a-pb/

**Comment by shameemreza** [comment]
@frosso One merchant reported that the issue still persists on ticket 10662507-zen, and it only works correctly on the classic checkout. They're using Storefront. Are they missing anything here? They've already cleared the cache, but the issue is still the same.

**Comment by frosso** [comment]
@shameemreza the fix hasn't been released yet. It's currently planned to be released in WooPayments 10.4.0.
