### PR TITLE
Construct table summary data only when transactions and deposits summary data has been loaded.

### LINKED ISSUE #1639: Transactions and deposits counts on the table summary are rendered as "undefined" while the data is loading.
The following behavior is applicable for both Transactions and Deposits tables.

Presently we render the number of transactions and deposits in the summary section of the respective tables. While the data is being fetched from the server the count is rendered as `undefined`.

Screenshot 2021-04-21 at 3 42 00 AM
Screenshot 2021-04-21 at 3 56 33 AM

The same issue can be replicated if the WCPay server is not running and still being proxied by WCPay dev plugin, i.e When API call is failing which results in `depositsSummary` being an [empty object](https://github.com/Automattic/woocommerce-payments/blob/cbfc71927444732ac01e973f9c8ebda8f399611d/client/deposits/list/index.js#L73).

**Steps to reproduce:**
- goto `develop` branch.
- try loading deposits or transactions page, and watch the table summary (bottom of the table).
- you should see `undefined` transaction while the table data is being loaded.

**Potential solutions:**
1. We can hide the summary from being rendered all together, until we have the final data to display.
2. We can keep the default count as Zero always.

### PR DESCRIPTION
**Pull request by naman03malhotra**
Fixes #1639 

Presently we render the number of transactions and deposits in the summary section of the respective tables. While the data is being fetched from the server the count is rendered as `undefined`.

`isSummaryLoading` is set to false initially which leads to construction of an array with empty/falsy values.

#### Changes proposed in this Pull Request
- Construct table summary data only when transactions and deposits summary data has been loaded. This way table summary won't be rendered unless the summary data is loaded. As per comment https://github.com/Automattic/woocommerce-payments/issues/1639#issuecomment-837296088

#### Testing instructions
- switch to `fix/1639-transaction-deposit-count`
- goto deposits page, the table summary should appear after the data has been loaded.
- goto transactions page, the table summary should appear after the data has been loaded.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

File: client/deposits/list/index.js [hunk 1]
```diff
@@ -129,17 +127,24 @@ export const DepositsList = () => {
...
-	if ( ! isSummaryLoading ) {
-		const isSingleCurrency =
-			2 > ( depositsSummary.store_currencies || [] ).length;
+	const isSingleCurrency =
+		2 > ( depositsSummary.store_currencies || [] ).length;
+
+	let summary;
+	const isDespositsSummaryDataLoaded =
+		depositsSummary.count !== undefined &&
+		depositsSummary.total !== undefined;
```
Comment (naman03malhotra) [inline client/deposits/list/index.js:137]: There are more attributes to test if the data has been loaded but I believe checking these two should suffice, for now, let me know if more properties need to be checked.

File: client/deposits/list/index.js [hunk 2]
```diff
@@ -70,9 +70,7 @@ const getColumns = ( sortByDate ) => [
 
 export const DepositsList = () => {
 	const { deposits, depositsCount, isLoading } = useDeposits( getQuery() );
-	const { depositsSummary, isLoading: isSummaryLoading } = useDepositsSummary(
-		getQuery()
-	);
+	const { depositsSummary } = useDepositsSummary( getQuery() );
```
Comment (kalessil) [inline client/deposits/list/index.js:73]: We should keep `isSummaryLoading` here and use it when calculating `isDespositsSummaryDataLoaded`, mostly to clarify that those data are coming from a data store.

File: client/deposits/list/index.js [hunk 3]
```diff
@@ -129,17 +127,24 @@ export const DepositsList = () => {
...
-	];
-
 	const isCurrencyFiltered = 'string' === typeof getQuery().store_currency_is;
-	if ( ! isSummaryLoading ) {
-		const isSingleCurrency =
-			2 > ( depositsSummary.store_currencies || [] ).length;
+	const isSingleCurrency =
+		2 > ( depositsSummary.store_currencies || [] ).length;
+
+	let summary;
```
Comment (kalessil) [inline client/deposits/list/index.js:134]: Not sure about this change, why not initializing with an empty array and pushing count similar to total?

File: client/transactions/list/index.js [hunk 4]
```diff
@@ -339,17 +339,25 @@ export const TransactionsList = ( props ) => {
...
-	];
 	const isCurrencyFiltered = 'string' === typeof getQuery().store_currency_is;
-	if ( ! isSummaryLoading ) {
-		const isSingleCurrency =
-			2 > ( transactionsSummary.store_currencies || [] ).length;
+
+	const isSingleCurrency =
+		2 > ( transactionsSummary.store_currencies || [] ).length;
+
+	let summary;
```
Comment (kalessil) [inline client/transactions/list/index.js:347]: Similar to comment for deposits listing.

File: client/transactions/list/index.js [hunk 5]
```diff
@@ -144,10 +144,10 @@ export const TransactionsList = ( props ) => {
 		getQuery(),
 		props.depositId
 	);
-	const {
-		transactionsSummary,
-		isLoading: isSummaryLoading,
-	} = useTransactionsSummary( getQuery(), props.depositId );
+	const { transactionsSummary } = useTransactionsSummary(
```
Comment (kalessil) [inline client/transactions/list/index.js:147]: Similar to comment for deposits listing.

**Review by kalessil — CHANGES_REQUESTED** [review]
Left a few comments, which are rather for better defining the code intention.

File: client/deposits/list/index.js (hunk 3 above)
Comment (naman03malhotra) [reply client/deposits/list/index.js:137]: If we do not want to render table summary then it expects a falsy value, as per https://github.com/woocommerce/woocommerce-admin/blob/b2693e66f22a8a09224ea7c97c8f6071163c06fb/packages/components/src/table/index.js#L255

If we pass an empty array (which is a truth value), then it would render the `TableSummary` component and creating a dom node that is not necessary unless we have the data.

Earlier I thought I would create a separate variable to control this behavior and pass the same to the component, something like:
```js
const summaryData = summary.length ? summary : undefined
```

But initializing `summary` with a falsy value in the first place seems like a better approach to me.

For now I'll add a comment for better clarification, please let me know what do you think?

File: client/transactions/list/index.js (hunk 4 above)
Comment (naman03malhotra) [reply client/transactions/list/index.js:348]: explanation same as the comment above ^

File: client/deposits/list/index.js (hunk 2 above)
Comment (naman03malhotra) [reply client/deposits/list/index.js]: Yeah it makes sense, better for code context and readability, added back in https://github.com/Automattic/woocommerce-payments/pull/1788/commits/5078ef80d3d3a2f1aed306029ebcaae5f63db474

File: client/deposits/list/index.js (hunk 3 above)
Comment (kalessil) [reply client/deposits/list/index.js:139]: Great, the comment clarifies the intention really well thanks.
I'm on a final testing round then.

**Review by kalessil — APPROVED** [review]
LGTM, :shipit: !
