### PR TITLE
Prevents querying for stripe billing subscriptions on every page load and changes how our Stripe Billing code is loaded.

### LINKED ISSUE #9717: Avoid running query in `WC_Payments::should_load_stripe_billing_integration()` on every page load
The fallback query used in `WC_Payments::should_load_stripe_billing_integration()` currently runs on every page load.  The decision from the query results should probably be cached, especially since it isn't a simple query and isn't extremely fast.

https://github.com/Automattic/woocommerce-payments/blob/faf5ef75bb30dab72af974374b58be0803c278ae/includes/class-wc-payments.php#L2067-L2080

Resulting Query:

```
SELECT wp_wc_orders.id FROM wp_wc_orders INNER JOIN wp_wc_orders_meta AS meta0 ON ( wp_wc_orders.id = meta0.order_id ) WHERE 1=1 AND (wp_wc_orders.status IN ('wc-pending','wc-active','wc-on-hold','wc-cancelled','wc-switched','wc-expired','wc-pending-cancel')) AND (wp_wc_orders.type = 'shop_subscription') AND ((meta0.meta_key = '_wcpay_subscription_id')) GROUP BY wp_wc_orders.id ORDER BY wp_wc_orders.date_created_gmt DESC LIMIT 0, 1
```

Query explain:

```
+----+-------------+--------------+--------+---------------------------------------------+----------------+---------+-------------------------+------+---------------------------------------------------------------------+
| id | select_type | table        | type   | possible_keys                               | key            | key_len | ref                     | rows | Extra                                                               |
+----+-------------+--------------+--------+---------------------------------------------+----------------+---------+-------------------------+------+---------------------------------------------------------------------+
| 1  | SIMPLE      | meta0        | ref    | meta_key_value,order_id_meta_key_meta_value | meta_key_value | 258     | const                   | 1    | Using index condition; Using where; Using temporary; Using filesort |
| 1  | SIMPLE      | wp_wc_orders | eq_ref | PRIMARY,status,type_status,type_status_date | PRIMARY        | 8       | wpmu_d05.meta0.order_id | 1    | Using where                                                         |
+----+-------------+--------------+--------+---------------------------------------------+----------------+---------+-------------------------+------+---------------------------------------------------------------------+
```

### LINKED ISSUE #10044: Handling Stripe Billing webhooks on a store with no Stripe Billing subscriptions results in PHP critical error
### Describe the bug

Slack thread: p1734981208053319-slack-C03V0SP07SL
P2: pbUcTB-5ZF-p2

This problem is a bit of an edge case, however, if a store finds itself in a situation where it has disabled the Stripe Billing feature but still has active Stripe Billing subscriptions that have become unlinked in Woo (i.e. missing `_wcpay_subscription_id` metadata), when Stripe sends an `invoice.x` webhook event, the following exception will occur:

```
2024-12-23T01:38:42+00:00 Critical Uncaught Error: Class "WC_Payments_Subscriptions" not found in /plugins/woocommerce-payments/includes/class-wc-payments-webhook-processing-service.php:194
```

This issue is caused by the `WC_Payments_Subscriptions` class only being loaded [here](https://github.com/Automattic/woocommerce-payments/blob/442ba90742cbfb5f9b7df672675b48a3f40b91ed/includes/class-wc-payments.php#L730) which is within a `should_load_stripe_billing_integration()` check, and `WC_Payments_Webhook_Processing_Service` calling this class for any Stripe Billing webhook without checking the class exists.

Props @csmcneill for finding this!

### Expected behavior

Despite the store presenting itself has not using Stripe Billing, I think we should still handle these webhooks in some way.

If a store has disabled the Stripe Billing feature and doesn't have any Stripe Billing subscriptions but is still receiving these webhooks, then something has gone terribly wrong.

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #9717 
Fixes #10044

#### Changes proposed in this Pull Request

This PR is making a few fundamental changes to how we load our Stripe Billing integration. As reported in #9717, on every page load, we were calling `should_load_stripe_billing_integration()` which checks if the store has the Stripe Billing feature enabled, or has existing Stripe Billing subscriptions. 

Querying for existing Stripe Billing subscriptions requires a meta query to find out if there is at least one subscription with `_wcpay_subscription_id` metadata. Doing this on every page load is a pretty substantial performance hit for stores where probably 95%+ of them have never enabled Stripe Billing before.

During an initial investigation phase, I discovered there wasn't a reliable way to cache this query result without potentially introducing a bad merchant experience. On top of that, if a store doesn't have Stripe Billing enabled or Subscriptions extension active, but does have Stripe Billing subscriptions, we should technically load Stripe Billing integration so that incoming webhooks could potentially be handled and/or logged.

For this reason, the biggest change coming in this PR is to make it so we always load out Stripe Billing integration classes for eligible stores.

The subsequent changes I made, were to make sure we're not adding hooks/filters that aren't necessary and/or calling subscription functions assuming that the store has Subscriptions activated.

#### Testing instructions

> [!NOTE]
> I haven't finished testing all of the flows that are effected by these changes. I've listed all of the tests I have/will complete below.

- [x] With Query Monitor + WooPayments + Subscriptions + Stripe Billing disabled. Confirm that loading any page doesn't run the following query:
image
- [x] Legacy Stripe Billing integration testing
  - [x] Creating subscription products 
  - [x] Purchasing Stripe Billing subscriptions
  - [x] Changing a payment method
  - [x] Create a pending subscription parent order and purchase with WooPayments
  - [x] Billing clock renewal testing
- [x] Legacy Stripe Billing -> activating WooCommerce Subscriptions (don't migrate existing)
  - [x] Purchasing subscriptions doesn't create stripe billing
  - [x] Billing clock renewal testing for non-migrated stripe billing subscriptions
- [x] Stripe Billing + WooCommerce Subscriptions
  - [x] Creating subscription products 
  - [x] Purchasing Stripe Billing subscriptions
  - [x] Changing a payment method
  - [x] Changing from Stripe to WooPayments with Stripe Billing
  - [x] Billing clock renewal testing
- [x] Stripe Billing disabled + WooCommerce Subscriptions
  - [x] Creating/updating products doesn't create/update them in stripe
  - [x] Purchasing subscriptions doesn't create stripe billing subscriptions
  - [x] Changing payment method doesn't create stripe billing subscription
  - [x] Processing subscription renewals works correctly.
- [x] Eligible store without Subscriptions or Stripe Billing
-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10358` or branch name `fix/9717-prevent-querying-stripe-billing-every-page-load` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9717-prevent-querying-stripe-billing-every-page-load) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b387737663854e35ec8ca1b99c318bb45a007153
- Build time: 2025-02-18 02:33:21 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by james-allan** [comment]
I went through all the files that will now be loaded on stores who are eligible. 

- [x] **`WC_Payments_Product_Service`**
   - All external Subscription plugin calls are `WC_Subscriptions_Product::is_subscription()`
   - 🟢 All have `class_exists( 'WC_Subscriptions_Product' )` or `$this->is_subscriptions_plugin_active()` checks protecting against fatals. 
   - ⚠️  There are two exceptions:
      - `update_products()` 
      - `maybe_schedule_product_create_or_update()` 
      - Both these functions are only called via callbacks attached via `add_product_update_listeners()` and that function is only called if `should_use_stripe_billing()` passes and so we should be protected. 
- **`WC_Payments_Invoice_Service`**
   - 🟢 All callbacks are only attached if `should_use_stripe_billing()` passes so we should be good. 
   - External references to Subscription classes:
      - `wcs_get_subscriptions_for_order()` call is protected with `function_exists()` check. 
      - 🗒️ `WC_Subscription` in function signatures. For some reason I thought this was cause a fatal at time of parsing this class but apparently that's not true. 
   - All other functions only make use of internal functions or WC core methods.
- **`WC_Payments_Subscription_Service`**
   -  🗒️ `WC_Subscription` in function signature of most functions.
   - `wcs_get_subscriptions_for_renewal_order()` without a defensive check, however it's only attached if `should_use_stripe_billing()` passes. 
   - All other functions are either defensive or have `WC_Subscription` and would fatal if called without a subscription object. 
- **`WC_Payments_Subscriptions_Event_Handler`**.
     - 🟢  All functions in this class first try to get a subscription object via `get_subscription_from_wcpay_subscription_id()` which will return false if subscription functionality doesn't exist. The functions then halt at that point. 
- **`WC_Payments_Subscription_Change_Payment_Method_Handler`**
    -  🟢 All callbacks are only attached if `should_use_stripe_billing()` is true which can only be true if Subscriptions functionality exists. 
    - 🟢 All functions are defensive by checking if core subscription classes or functions exist.
- **`WC_Payments_Subscriptions_Plugin_Notice_Manager`**
    - We may be able to improve the performance of this class. It's a fairly simple class, however for some reason it always prints the notice on the plugin screen even if there are no subscriptions. See `output_notice_template()`. If we check if subscriptions are present, we may want to cache it so it only runs once at least. 
- **`WC_Payments_Subscriptions_Empty_State_Manager`**
    - 🟢 All external calls are protected by a `function_exists()` call.
- **`WC_Payments_Subscriptions_Onboarding_Handler`**
    -  🟢 All callbacks are only attached if `should_use_stripe_billing()` is true which can only be true if Subscriptions functionality exists. 
- `WC_Payments_Subscription_Minimum_Amount_Handler`
    - There aren't any external calls to Subscription classes.
    - 🟢 The only callback is only attached if `should_use_stripe_billing()` is true. 

As part of code review I reviewed each file to make sure there are no flows that could lead to a fatal error due to missing WC Subscription classes etc. I'm going to do some testing next week on a site to make sure there isn't anything I missed during code review.

File: includes/subscriptions/class-wc-payments-subscription-service.php [hunk 1]
```diff
@@ -142,24 +142,27 @@ public function __construct(
 			add_action( 'woocommerce_checkout_subscription_created', [ $this, 'create_subscription' ] );
 			add_action( 'woocommerce_renewal_order_payment_complete', [ $this, 'create_subscription_for_manual_renewal' ] );
 			add_action( 'woocommerce_subscription_payment_method_updated', [ $this, 'maybe_create_subscription_from_update_payment_method' ], 10, 2 );
+
+			// Save the new token on the WCPay subscription when it's added to a WC subscription.
+			add_action( 'woocommerce_payment_token_added_to_order', [ $this, 'update_wcpay_subscription_payment_method' ], 10, 3 );
```
Comment (james-allan) [inline includes/subscriptions/class-wc-payments-subscription-service.php:149]: I think this one needs to be moved to the `class_exists( 'WC_Subscription' )` check below.

If you have WC Subscriptions enabled and have some legacy Stripe Billing subscriptions, if you change the subscriptions payment method, it isn't updated in Stripe. 


Looking at the `update_wcpay_subscription_payment_method()` function, it looks safe to run on WC Subscription stores.

Comment (mattallan) [reply includes/subscriptions/class-wc-payments-subscription-service.php:149]: Thanks @james-allan. Fixed in [b387737](https://github.com/Automattic/woocommerce-payments/pull/10358/commits/b387737663854e35ec8ca1b99c318bb45a007153)

**Comment by james-allan** [comment]
### WC Pay Subscriptions (Legacy)

_I tested the following with **WooPayments** enabled and the **WCPay Subscriptions** feature enabled via the Dev tools plugin. WooCommerce Subscriptions was not activated._

**Expectation:** All Stripe Billing features should be available and work as expected. 

- [x] Create a subscription product
- [x] Trash subscription product - archived product in Stripe
- [x] Untrash product - unarchived product in Stripe
- [x] Purchase subscription
- [x] Suspend (pause) and resume a subscription
- [x] Cancel subscription
- [x] Cancel an active subscription and re-subscribe
- [x] Change payment method (card) for an active subscription
- [x] Renew subscription - via Stripe Billing

### No Subscriptions functionality

_I retested after **deactivating WCPay Subscriptions**. There is no Subscriptions functionality on the site._

Expectation: Stripe Billing code should be loaded because my store is eligible, however there should be no errors and no change in core flows. 

- [x] `WC_Payments_Subscription_Service` class exists check - confirm that the Stripe Billing integration code is loaded. 
- [x] Create a simple product
- [x] Trashing simple product
- [x] Untrash product
- [x] Purchase products
- [x] Add payment method

### WooCommerce Subscriptions + Stripe Billing Setting

_I tested the following with **WooPayments**, **WC Subscriptions**, and **Stripe Billing** turned on via the WooPayments settings._

**Expectation:** All Stripe Billing features should be available and work as expected. 

- [x] Create a subscription product
    - 🟡 For some reason the subscription product wasn't created at Stripe. It was automatically created once I purchased the product though. This is fine. 
- [x] Trash subscription product - archived product in Stripe
- [x] Untrash product - unarchived product in Stripe
- [x] Purchase subscription
- [x] Suspend (pause) and resume a subscription
- [x] Cancel subscription
- [x] Cancel an active subscription and re-subscribe
- [x] Change payment method (card) for an active subscription
- [x] Renew subscription - via Stripe Billing

### WooCommerce Subscriptions + Tokenized Subscriptions (No Stripe Billing)

_I tested the following with **WooPayments** and **WC Subscriptions** with **Stripe Billing** turned off via the WooPayments settings. ie Tokenized subscriptions_

**Expectation:** Stripe Billing code should be loaded, however, it should have no impact on functionality. 

- [x] Create a subscription product - No Stripe Billing product
- [x] Trash subscription product 
- [x] Untrash product
- [x] Purchase subscription - No Stripe Billing subscription
- [x] Suspend (pause) and resume a subscription
- [x] Cancel subscription
- [x] Cancel an active subscription and re-subscribe
- [x] ⚠️ Change payment method (card) for an active subscription - Stripe Billing (see comment [here](https://github.com/Automattic/woocommerce-payments/pull/10358/files#r1958963093))
    - Fixed in [b387737](https://github.com/Automattic/woocommerce-payments/pull/10358/commits/b387737663854e35ec8ca1b99c318bb45a007153)
- [x] Change payment method (card) for an active subscription - Token
- [x] Renew subscription - via Stripe Billing
- [x] Renew subscription - via token

**Review by james-allan — APPROVED** [review]
Changes look good Matt. I've tested the 4 different scenarios and the flows that are affected. Things work as expected and I didn't see any errors caused by us expecting WC Subscriptions code to be active.

**Comment by mattallan** [comment]
Thanks @james-allan for your feedback and thorough testing!
I have also gone through the following test scenarios on this branch:

With Query Monitor + WooPayments + Subscriptions + Stripe Billing disabled. Confirm that loading any page doesn't run the following query:
- [x] With Query Monitor + WooPayments + Subscriptions + Stripe Billing disabled. Confirm that loading any page doesn't run the following query:
image
- [x] Legacy Stripe Billing integration testing
  - [x] Creating subscription products 
  - [x] Purchasing Stripe Billing subscriptions
  - [x] Changing a payment method
  - [x] Create a pending subscription parent order and purchase with WooPayments
  - [x] Billing clock renewal testing
- [x] Legacy Stripe Billing -> activating WooCommerce Subscriptions (don't migrate existing)
  - [x] Purchasing subscriptions doesn't create stripe billing
  - [x] Billing clock renewal testing for non-migrated stripe billing subscriptions
- [x] Stripe Billing + WooCommerce Subscriptions
  - [x] Creating subscription products 
  - [x] Purchasing Stripe Billing subscriptions
  - [x] Changing a payment method
  - [x] Changing from Stripe to WooPayments with Stripe Billing
  - [x] Billing clock renewal testing
- [x] Stripe Billing disabled + WooCommerce Subscriptions
  - [x] Creating/updating products doesn't create/update them in stripe
  - [x] Purchasing subscriptions doesn't create stripe billing subscriptions
  - [x] Changing payment method doesn't create stripe billing subscription
  - [x] Processing subscription renewals works correctly.
- [x] Eligible store without Subscriptions or Stripe Billing
