### PR TITLE
Apply User-Defined Date Formatting Settings to WP Admin React Components

### LINKED ISSUE #6567: User set Date and Time formatting aren't respected in react components
### Describe the bug

Date and time formats are user settable in WordPress. WCPay components do not use these settings instead opting to hardcode formats.

### To Reproduce

1. Go to 'Settings' > 'General'
2. Change a date time format that is not the default.
3. Visit a page with react components such as Transactions
4. See dates and time format is not used.

**NB:** This also applies to Deposits, Disputes, Loans, and more.

### Actual behavior

Date and time formats are hardcoded inside react components across WCPay. User settings are not respected.

### Screenshots

Screenshot 2023-06-22 at 2 52 03 PM
Screenshot 2023-06-22 at 2 51 40 PM

### Expected behavior

User set date/time formats should be used wherever possible

### Sample Snippets:

https://github.com/Automattic/woocommerce-payments/blob/23b58e9ea093f9fd001c761abfda30bc13234a81/client/disputes/index.tsx#L204-L207

https://github.com/Automattic/woocommerce-payments/blob/23b58e9ea093f9fd001c761abfda30bc13234a81/client/disputes/index.tsx#L213-L216

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #6567

This pull request includes changes to ensure that user-defined date and time formatting settings are respected across various React components in the WooCommerce Payments plugin. The most important changes include the replacement of `dateI18n` with custom date formatting functions, the addition of a new `DateFormatNotice` component, and updates to test files to accommodate these changes.

### Improvements to date and time formatting:

* [`client/capital/index.tsx`](diffhunk://#diff-79118330b412c1ae9a6bb2ef711c58de6ae5742f018af797dbb1682566ce7283R27-R28): Replaced `dateI18n` with `formatDateTimeFromString` for date formatting in loan status and rows data. Added `DateFormatNotice` component to display a notice about date format changes. [[1]](diffhunk://#diff-79118330b412c1ae9a6bb2ef711c58de6ae5742f018af797dbb1682566ce7283R27-R28) [[2]](diffhunk://#diff-79118330b412c1ae9a6bb2ef711c58de6ae5742f018af797dbb1682566ce7283L83-R84) [[3]](diffhunk://#diff-79118330b412c1ae9a6bb2ef711c58de6ae5742f018af797dbb1682566ce7283L115-R118) [[4]](diffhunk://#diff-79118330b412c1ae9a6bb2ef711c58de6ae5742f018af797dbb1682566ce7283L153-R156) [[5]](diffhunk://#diff-79118330b412c1ae9a6bb2ef711c58de6ae5742f018af797dbb1682566ce7283R213)
* [`client/components/account-status/account-fees/expiration-description.js`](diffhunk://#diff-8ec3d59273e022e3b0f80cce08bae3437064ae6d39f1349bfc67ffcbc2b6f7deL29-R28): Replaced `dateI18n` with `formatDateTimeFromString` for expiration date formatting. [[1]](diffhunk://#diff-8ec3d59273e022e3b0f80cce08bae3437064ae6d39f1349bfc67ffcbc2b6f7deL29-R28) [[2]](diffhunk://#diff-8ec3d59273e022e3b0f80cce08bae3437064ae6d39f1349bfc67ffcbc2b6f7deL47-R46)
* [`client/components/active-loan-summary/index.tsx`](diffhunk://#diff-862535a6d946dab6ab1768f87e8ed8b9451d7937fb545a9c2aa0d1c4432c5a85L213-R214): Replaced `dateI18n` with `formatDateTimeFromTimestamp` for various date fields in the active loan summary. [[1]](diffhunk://#diff-862535a6d946dab6ab1768f87e8ed8b9451d7937fb545a9c2aa0d1c4432c5a85L213-R214) [[2]](diffhunk://#diff-862535a6d946dab6ab1768f87e8ed8b9451d7937fb545a9c2aa0d1c4432c5a85L254-R251) [[3]](diffhunk://#diff-862535a6d946dab6ab1768f87e8ed8b9451d7937fb545a9c2aa0d1c4432c5a85L281-R277)
* [`client/components/disputed-order-notice/index.js`](diffhunk://#diff-b6c213dfcda31572de267d719805c04f5e475da81c81b9a3fba1f8b5ac30bf55L134-R136): Replaced `dateI18n` with `formatDateTimeFromString` for dispute notice dates and ensured consistent timezone-independent comparison using UTC. [[1]](diffhunk://#diff-b6c213dfcda31572de267d719805c04f5e475da81c81b9a3fba1f8b5ac30bf55L134-R136) [[2]](diffhunk://#diff-b6c213dfcda31572de267d719805c04f5e475da81c81b9a3fba1f8b5ac30bf55L185-R187)

### Addition of `DateFormatNotice` component:

* [`client/components/date-format-notice/index.tsx`](diffhunk://#diff-4ed5fd74e15d5398781ca46c7f655d766e906a7471426d3865cbe19574af803bR1-R67): Added a new component to display a notice about the date and time formats matching user preferences.
* [`client/components/date-format-notice/style.scss`](diffhunk://#diff-32f649f9a33997f72fc459558e242bc78f014378c7fccc51786c4ca90edfec35R1-R5): Added styles for the `DateFormatNotice` component.

### Test updates:

* Updated test files to mock date formats and include the new `DateFormatNotice` component in snapshots. [[1]](diffhunk://#diff-5773f76b58656257286f4f514fdf46256288aaf0d37c8f3ad7a8b95bda6cab8eR28) [[2]](diffhunk://#diff-5773f76b58656257286f4f514fdf46256288aaf0d37c8f3ad7a8b95bda6cab8eR41) [[3]](diffhunk://#diff-81f04262c1dcce722529a5fd2d9646828db1b524dbd72fb26b063e41820e1951R8-R55) [[4]](diffhunk://#diff-9aba291c05625490418224f793801dc20087e49797789a4e28dc1100ee3ba190R49) [[5]](diffhunk://#diff-ca55669d0bb95fa98cfd14abc4779746ca1f69b7c90618ae83b7eeaccd8d511dR39) [[6]](diffhunk://#diff-ae859803e818cb267ca471f469d0d729d422925f8b105ea783849d682330a6efR71) [[7]](diffhunk://#diff-ae859803e818cb267ca471f469d0d729d422925f8b105ea783849d682330a6efR244) [[8]](diffhunk://#diff-1d992efb624a1e41406397c5e209481bed42487c70cf967c0790952bfc45fa63R17-R25) [[9]](diffhunk://#diff-1d992efb624a1e41406397c5e209481bed42487c70cf967c0790952bfc45fa63R46)

##### General Date and Time Display Testing

* Navigate to `WP Admin > Settings > General` and set your preferred Date and Time Formats and Timezone.
* Verify that the date format matches the user-defined settings in WordPress when you navigate to the WooPayments plugin pages.
* Verify that the dates and times are correctly converted from UTC to your preferred timezone.

##### Component Specific Testing 

**Transactions**

- Navigate to `WP Admin > Payments > Transactions`.
- Verify the values in `Date / Time` and `Deposit Date` columns.
Screenshot 2024-10-29 at 17 12 32
Screenshot 2024-10-29 at 17 12 37

**Capital Loans**

This section is hidden if your user does not have capital loans. Follow the steps in this [guide](https://docs.stripe.com/capital/test-mode-tooling) to create one offer for your user. Once the offer is created, your user will get an email to confirm it. Visit the link in the email, but make sure to use your local store URL, not the server one.

- Navigate to `WP Admin > Payments > Capital loans`
- Verify that the `Active loan overview` dates are formatted according to the user settings.
- Verify that the `All Loans` table dates are formatted according to the user settings. There are two columns that contain dates: `Disbursed` and `First Paydown`.

Screenshot 2024-11-04 at 12 17 37

**Deposits**

- Navigate to `WP Admin > Payments > Deposits`
- Verify that the dates in the Deposit history table are formatted according to the user settings
Screenshot 2024-11-04 at 12 23 38

- Click on a row and verify that the date and times in the Date /Time column of the deposit details are formatted correctly.
Screenshot 2024-11-04 at 12 24 13

**Disputes**
You can use [test cards](https://docs.stripe.com/testing#disputes) to create disputed orders.

- Navigate to `WP Admin > Payments > Disputes`
- Verify the date and time in the `Disputed on` column (you may need to reveal it)
Screenshot 2024-11-04 at 12 40 28
- Click one row to navigate to the details view and verify the dates
Screenshot 2024-11-04 at 12 41 16

- Click on `Challenge Dispute` and verify the dates in the form are correct
Screenshot 2024-11-04 at 12 45 21

**Documents**

In the server, you can use the cli to add a document to your account `wp wcpay add_document_for_account 236870460 vat_invoice --period_from="2024-10-01 00:00:00" --period_to="2024-10-31 23:59:59"`

- Navigate to `WP Admin > Payments > Documents`
- Verify that the dates in the Date and Description columns in the Documents list are correctly formatted
Screenshot 2024-11-04 at 13 07 17

**Date and time format change notice**

- Navigate to any page under the `WP Admin > Payments` menu i.e. `Transactions`.
- Check that the following notice is displayed.
Screenshot 2024-12-18 at 13 18 33
- Click the `settings link` and check that you are redirected to the `Settings > General` page.
- Navigate back to the previous page.
- Check that the notice is no longer displayed.
- Delete the `wcpay_date_format_notice_dismissed` option.
- Check the notice is displayed on any page under `WP Admin > Payments` menu.
- Dismiss the notice by clicking on the icon.
- Check that the notice is no longer displayed.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions-for-WC-Payments-8.7.0#bug-fix---user-set-date-and-time-formatting-arent-respected-in-react-components
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9635` or branch name `fix/6567-user-set-date-and-time-formatting-arent-respected-in-react-components` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/6567-user-set-date-and-time-formatting-arent-respected-in-react-components) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: d294fcec3adce5444db50c8384af37401278f5e0
- Build time: 2024-12-20 11:02:39 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by brucealdridge** [comment]
I have requested an optional review from Helix. Dates/Timezones have been on our radar recently.

File: client/utils/date-time.ts [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+ * Formats a date and time string according to WordPress settings or a custom format.
+ *
+ * @param { string | Date } dateTime - The date and time string (e.g., '2024-10-23 15:28:26') or a JS Date object.
+ * @param { FormatDateTimeOptions } options - Additional options to control time inclusion and whether to use GMT/UTC.
+ * @return { string } - The formatted date and time string.
+ */
+export function formatUserDateTime(
+	dateTime: string | Date,
+	options: FormatDateTimeOptions = {
+		includeTime: true,
```
Comment (deepakpathania) [inline client/utils/date-time.ts]: I feel the `false` scenario for `includeTime` is the more common one, could we update the default value to reflect that? 🤔

File: client/utils/date-time.ts [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+	const {
+		customFormat = null,
+		includeTime = true,
+		useGmt = false,
+		separator = ' / ',
+	} = options;
+
+	// Use the WordPress settings for date and time format if no custom format is provided
+	const format =
+		customFormat ||
```
Comment (deepakpathania) [inline client/utils/date-time.ts:74]: Should we validate the `customFormat` to ensure it is a valid option for the `dateI18n` function?

**Review by deepakpathania — COMMENTED** [review]
Left some comments.

File: client/utils/date-time.ts (hunk 1 above)
Comment (mgascam) [reply client/utils/date-time.ts]: Yes, good point, addressed here [70b3c92](https://github.com/Automattic/woocommerce-payments/pull/9635/commits/70b3c921a7088370a6c7e1f503489a1b3902cb89) thanks!

File: client/utils/date-time.ts (hunk 2 above)
Comment (mgascam) [reply client/utils/date-time.ts:74]: I looked into adding this validation, but it turns out to be trickier than it seems. The issue is that the `dateI18n` function supports the same formats as [PHP’s date function](https://www.php.net/manual/en/function.date.php). According to the [documentation](https://www.php.net/manual/en/datetime.format.php), "Unrecognized characters in the format string will be printed as-is." This provides a lot of flexibility. For instance, unsupported characters can be included as long as they’re escaped: a format like 'l \t\h\e jS' can output something like "Wednesday the 19th."

Given the flexibility that dateI18n offers with custom formats, I don't think it makes sense to implement strict validation. Instead, I’ve added unit tests to document this behavior: [368e80e](https://github.com/Automattic/woocommerce-payments/pull/9635/commits/368e80e72c06e2777cb87bb5b9c40d60b62de473) and [666473d](https://github.com/Automattic/woocommerce-payments/pull/9635/commits/666473d233e287747e8fc427a14b6ea327ec36ad). What do you think?

Comment (deepakpathania) [reply client/utils/date-time.ts:74]: Fair and makes sense.

File: includes/admin/class-wc-payments-admin.php [hunk 3]
```diff
@@ -958,6 +958,8 @@ private function get_js_settings(): array {
 			'lifetimeTPV'                        => $this->account->get_lifetime_total_payment_volume(),
 			'defaultExpressCheckoutBorderRadius' => WC_Payments_Express_Checkout_Button_Handler::DEFAULT_BORDER_RADIUS_IN_PX,
 			'isWooPayGlobalThemeSupportEligible' => WC_Payments_Features::is_woopay_global_theme_support_eligible(),
+			'dateFormat'                         => wc_date_format(),
```
Comment (deepakpathania) [inline includes/admin/class-wc-payments-admin.php:987]: For older plugins that don't have these - will there be any issues during updation? That is for reports or other places that folks might be downloading, will there be discrepancies in data format due to this? 🤔

**Review by deepakpathania — COMMENTED** [review]
Changes mostly LGTM but have a question around data integrity for older plugins updating to a future version with these changes.

File: includes/admin/class-wc-payments-admin.php (hunk 3 above)
Comment (mgascam) [reply includes/admin/class-wc-payments-admin.php:987]: I focused on limiting changes to only the areas of code where dates are displayed to the user, so I don't expect any major issues. Additionally, the fact that the unit tests and snapshots passed with minimal adjustments gives me further confidence.

However, there is a chance that merchants might be confused, as the way dates and times are presented will change without any direct action from them. This includes the dates in downloaded files, which, as you mentioned, could potentially impact automated processes on their end (just thinking about a possible scenario). While the default WordPress date format (F j, Y) isn’t drastically different from the previously hard-coded format (M j, Y), which was the most commonly used before this change, there could still be some adjustments.

I'm not entirely sure how to assess the potential negative impact on merchants, to be honest. Overall, though, I see this as a welcome improvement, as it adapts date formats to user-selected settings, making them feel more intuitive. For example, the MM-DD-YYYY format can be confusing for Spanish speakers like myself, as we typically use the DD-MM-YYYY format. There’s also an option for merchants to use a custom format, allowing them to keep the previous date style if desired. However, it's worth noting that we weren’t using formats consistently across the WooPayments plugin codebase before this update.

But I may be wrong, so I'm wondering if I should gather more feedback in a p2 before going ahead with this change. What do you think?

Comment (deepakpathania) [reply includes/admin/class-wc-payments-admin.php:987]: I feel we could make this a setting maybe in WooPayments that allows merchants to sync the date format with the WP admin settings maybe and default it to false. That way merchants can explicitly opt-in to if needed and would expect the change to be reflected from the toggle onwards. WDYT?

Comment (mgascam) [reply includes/admin/class-wc-payments-admin.php:987]: Thank you for sharing this idea @deepakpathania; it’s definitely a possible solution, though I’m not entirely convinced. My concern is that there’s already a place to manage date and time formats in `Settings > General`. Adding a similar option under the WooPayments settings might create confusion. Additionally, the current behavior of ignoring user preferences is inconsistent, and introducing a setting here feels somewhat like a workaround for the core issue. That said, as you pointed out, this could help reduce potential confusion for merchants by giving them control over format changes.

I'm considering an alternative approach: we could inform merchants that they can select their preferred formats through WordPress settings. This could be done with an admin notice or a tooltip, perhaps in places like the date column in tables.

Comment (mgascam) [reply includes/admin/class-wc-payments-admin.php:987]: > This could be done with an admin notice or a tooltip, perhaps in places like the date column in tables.

Something like this:


https://github.com/user-attachments/assets/f0ae0f68-1e19-493c-a917-e25667f9f7db

Comment (haszari) [reply includes/admin/class-wc-payments-admin.php:987]: This sounds worth consulting designers about! @mgascam I love the idea of leaning into WordPress core settings and simplifying things.

Comment (deepakpathania) [reply includes/admin/class-wc-payments-admin.php:987]: This makes sense to me but as Rua mentioned, maybe let's consult someone from Design about this before shipping.

Comment (mgascam) [reply includes/admin/class-wc-payments-admin.php:987]: > This sounds worth consulting designers about!

Thanks for your insights, @deepakpathania and @haszari! I think consulting designers is a great idea.

@rogermattic, I noticed your recent post on [table design](https://paymentsdesignwip.wordpress.com/2024/10/24/new-reporting-experience-report-design-tables/), so I thought you might have some relevant context here. However, please feel free to redirect me if needed. To summarize, this PR aims to remove the hardcoded date & time formats currently in use in the WooPayments plugin, instead aligning them with WordPress General settings. While I believe this is the right direction, we’re aware this change could potentially inconvenience some merchants, as it will be applied automatically with the update.

To minimize disruption, we’re exploring a few options (see comments above). One approach we’re leaning towards is adding a tooltip in the relevant column headers to inform merchants of the change. The tooltip could guide users to the General settings where they can manage date & time formats. Do you think this is a suitable solution? Any additional insights or ideas would be much appreciated. 🙇

**Comment by rogermattic** [comment]
Thanks for tagging me @mgascam !

> To summarize, this PR aims to remove the hardcoded date & time formats currently in use in the WooPayments plugin, instead aligning them with WordPress General settings. While I believe this is the right direction...

Thanks for the TLDR; ! I think it is a great idea! 

> ...we’re aware this change could potentially inconvenience some merchants, as it will be applied automatically with the update.
Agreed— It's a small change but I agree it can be frustrating. We can definitely support users here, and I really like your ideas! I’m leaning slightly towards a dismissable admin notice (mentioned earlier) over a tooltip. We could also consider a mini spotlight, though I’ll need to explore how that might look. Something like this (a random example from somewhere else):

Screenshot 2024-11-06 at 10 48 27

A tooltip might be less noticeable than a notice, especially if we're aiming to introduce this change smoothly and reduce potential user frustration. However, a tooltip could work well as a secondary guide, pointing out where to adjust settings and perhaps disappearing eventually after some time when the users get familiar with the flow.

To start, I’d suggest exploring either the admin notice or spotlight options. What do you think? If you’re on board, I can mock up two mini proposals for us to review.

Also, what will be the default view that the user sees after the update? Will it be something like this (from the [Storybook](https://wordpress.github.io/gutenberg/?path=/docs/dataviews-dataviews--docs))?: 
Screenshot 2024-11-06 at 10 42 54

Also, am I understanding this correctly, to adjust the settings the users will need to follow exactly the steps that you listed above as testing instructions?
> 1. Navigate to WP Admin > Settings > General and set your preferred Date and Time Formats and Timezone.
>2. Verify that the date format matches the user-defined settings in WordPress when you navigate to the WooPayments plugin pages.
>3. Verify that the dates and times are correctly converted from UTC to your preferred timezone.

**Comment by mgascam** [comment]
Thanks for your quick response @rogermattic 🙇 I loved your perspective and I feel we are aligned. Let's discuss the next steps 😄 

> To start, I’d suggest exploring either the admin notice or spotlight options. What do you think? If you’re on board, I can mock up two mini proposals for us to review.

Yes I agree that the admin notice and/or the spotlight options can work. Please share the mocks and, in the meantime, I'll look into how those components work from a code point of view (never used them yet)

> Also, what will be the default view that the user sees after the update? Will it be something like this (from the [Storybook](https://wordpress.github.io/gutenberg/?path=/docs/dataviews-dataviews--docs))?

After the update, they will see the date & times formatted according to their saved preferences. The defaults are `F j, Y` for dates (e.g. November 6, 2024) and `g:i a` for time (e.g. 11:06 am) and the UTC timezone. The date in your example will be rendered like this `January 01, 2021 / 12:00 am`.

> Also, am I understanding this correctly, to adjust the settings the users will need to follow exactly the steps that you listed above as testing instructions?
> 
Yes, this is where date and time settings live in the WordPress Admin.

**Comment by mgascam** [comment]
> What do you think? If you’re on board, I can mock up two mini proposals for us to review.

Hi @rogermattic 👋 , just checking in to see if you've had a chance to work on the mocks. I believe we could use the [Notice](https://developer.wordpress.org/block-editor/reference-guides/components/notice/) component to inform merchants, but I'd prefer to hold off on any decisions until we've reviewed your proposals.

For your information, I'll be on support rotation next week, but I'd like to resume work on this the following week. It would be great if we could review the mocks in the meantime. Does that work for you?

Thanks in advance!

File: client/capital/index.tsx [hunk 4]
```diff
@@ -112,7 +112,7 @@ const getRowsData = ( loans: CapitalLoan[] ) =>
 		const data = {
 			paid_out_at: {
 				value: loan.paid_out_at,
-				display: clickable( dateI18n( 'M j, Y', loan.paid_out_at ) ),
+				display: clickable( formatUserDateTime( loan.paid_out_at ) ),
```
Comment (Jinksi) [inline client/capital/index.tsx]: Kudos for tackling this @mgascam 🙌.

As I've been auditing our timezone inconsistencies (as shared on P2 paJDYF-fQl-p2), I've noticed some places where we are incorrectly inferring the TZ of API-response timestamp strings.

For example, this capital loans list view datetime will not be inferred as a UTC datetime unless we explicitly pass this to the `datei18n` date parser – one way is to add a `Z` TZ identifier suffix or use `moment.utc().toISOString()` which is used elsewhere in this codebase.

```suggestion
				display: clickable(
					formatUserDateTime( loan.paid_out_at + 'Z' )
				),
```

Here's an example of a loan datetime display before and after adding the TZ above (I added `includeTime: true` to help debug).

Before adding TZ identifier, with input UTC timestamp string `2024-11-08 04:58:35`:
without TZ utc

I assume it is [interpreting the timestamp as local/browser timezone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format:~:text=When%20the%20time%20zone%20offset%20is%20absent%2C%20date%2Donly%20forms%20are%20interpreted%20as%20a%20UTC%20time%20and%20date%2Dtime%20forms%20are%20interpreted%20as%20a%20local%20time.), before converting to store timezone.

After adding TZ identifier, correctly converts to the store TZ (New York) of `7 November 2024 at 23:58`:
with TZ utc


The new `formatUserDateTime` shared function has helped to fix some of these (e.g. disputes list). I wonder if there is a suitable way we can abstract away the API response datetime value parsing as well?

Although, ideally, we should return the TZ within the timestamp string in the API response, which could simplify datetime handling on the frontend.

Comment (mgascam) [reply client/capital/index.tsx]: Thanks for the review and your comments @Jinksi, much appreciated 😄 

> one way is to add a Z TZ identifier suffix or use moment.utc().toISOString() which is used elsewhere in this codebase.

I completely agree with you, and I reached the same conclusion while working on this task. For context, my focus has been on how dates are rendered to the merchant, aiming to avoid manipulating the "input" dates directly. My primary concern was ensuring that dates are displayed accurately and without errors.

However, I now realize this approach may have been flawed. I think it’s safe to assume that we are working with dates in the UTC timezone ("Z"), but as you pointed out, there are cases where this timezone information is missing. In my opinion, we should consistently convert raw date inputs to UTC (I'm using moment.utc for this) before formatting them. This would allow us to rely on dateI18n for consistent formatting of dates and times.

I’ve already made a few commits (e.g., [857dbf0](https://github.com/Automattic/woocommerce-payments/pull/9635/commits/857dbf015c1044529c13e58a8e478d00889f3fda)) to incorporate the conversion to UTC, but there are still a few more to go. Hopefully, I’ll be able to request a new review by tomorrow in my timezone.

> The new formatUserDateTime shared function has helped to fix some of these (e.g. disputes list). I wonder if there is a suitable way we can abstract away the API response datetime value parsing as well?

I’m not sure I have a great answer for this one yet, sorry. Perhaps we could update the `formatUserDateTime` function to handle the UTC conversion by default. This might reduce the repetition of `moment.utc` calls across the codebase. However, there is a potential complication: we are also working with dates in UNIX format (epoch). We’d need to account for these formats too, and I’m not sure yet how complex that might become.

Comment (Jinksi) [reply client/capital/index.tsx]: > we are also working with dates in UNIX format (epoch). We’d need to account for these formats too, and I’m not sure yet how complex that might become.

Yes, agree that an incremental approach here is suitable, and using `moment.utc` before passing in to `formatUserDateTime` is a robust and clear way to ensure incoming API response timestamps are interpreted as UTC.

File: client/utils/date-time.ts [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+	customFormat?: DateTimeFormat; // Custom format to use instead of WordPress settings
+}
+
+/**
+ * Formats a date and time string according to WordPress settings or a custom format.
+ *
+ * @param { string | Date } dateTime - The date and time string (e.g., '2024-10-23 15:28:26') or a JS Date object.
+ * @param { FormatDateTimeOptions } options - Additional options to control time inclusion and whether to use GMT/UTC.
+ * @return { string } - The formatted date and time string.
+ */
```
Comment (Jinksi) [inline client/utils/date-time.ts]: It may help future devs not make mistakes here by clarifying that the `formatUserDateTime` expects `dateTime: string | Date` to be passed in as a UTC date or string, which is then converted to the WP Settings TZ. Otherwise, `datei18n` will parse the string as the browser's local timezone.

```suggestion
/**
 * Formats a date and time string according to WordPress settings or a custom format.
 *
 * @param { string | Date } dateTime - The date and time string (e.g. '2024-10-23 15:28:26') or a JS Date object. `dateTime` strings without a timezone suffix (e.g. `Z` for UTC) will be interpreted as the browser's local timezone.
 * @param { FormatDateTimeOptions } options - Additional options to control time inclusion and whether to use GMT/UTC.
 * @return { string } - The formatted date and time string.
 */
```

File: client/utils/date-time.ts [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+import { dateI18n } from '@wordpress/date';
+
+type DateTimeFormat = string | null;
+
+interface FormatDateTimeOptions {
+	includeTime?: boolean; // Whether to include time in the formatted string (defaults to true)
+	useGmt?: boolean; // Whether to display the time in GMT/UTC (defaults to false)
+	separator?: string; // Separator between date and time (defaults to ' / ')
+	customFormat?: DateTimeFormat; // Custom format to use instead of WordPress settings
+}
```
Comment (Jinksi) [inline client/utils/date-time.ts]: If we add these comments as type annotations above, code editors (or VSCode at least) will show these on hover.

image


```suggestion
interface FormatDateTimeOptions {
	/** Whether to include time in the formatted string (defaults to true) */
	includeTime?: boolean;
	/** Whether to display the time in GMT/UTC (defaults to false) */
	useGmt?: boolean;
	/** Separator between date and time (defaults to ' / ') */
	separator?: string;
	/** Custom format to use instead of WordPress settings, e.g. 'Y-m-d H:i' */
	customFormat?: DateTimeFormat;
}
```

This may help future devs understand `useGmt` – it wasn't immediately clear to me if it means the input is GMT or the output is GMT.

File: client/utils/test/date-time.test.ts
Comment (Jinksi) [inline client/utils/test/date-time.test.ts:1]: 💭 as a side-quest, I tinkered with testing different WP TZ Settings in this test suite since the output of `datei18n` would be different based on this ([see this branch](https://github.com/Automattic/woocommerce-payments/compare/fix/6567-user-set-date-and-time-formatting-arent-respected-in-react-components...fix/6567-user-set-date-and-time-formatting-test-WP-timezone-settings)).

Changing the WP date settings from JS in the test suite requires a later version of `@wordpress/date` AFAICT so we can use `getSettings`/`setSettings`, so I upgraded from `4.5.0` to the latest `5.13.0`. But then 💣💥 many tests started failing because `5.13.0` is parsing timezones differently 🤔

**TLDR**: we probably should leave the `@wordpress/date` upgrade for a subsequent PR that addresses TZ inconsistencies.

File: client/capital/index.tsx (hunk 4 above)
Comment (mgascam) [reply client/capital/index.tsx]: I implemented two utility functions using `moment.utc`: [formatDateTimeFromString](https://github.com/Automattic/woocommerce-payments/pull/9635/files#diff-87e7d575d3a841713f1f229aa40ddf0a14bc352d9c4b840529c415ee7b96f04aR22) and [formatDateTimeFromTimestamp](https://github.com/Automattic/woocommerce-payments/pull/9635/files#diff-87e7d575d3a841713f1f229aa40ddf0a14bc352d9c4b840529c415ee7b96f04aR30). I noticed there was too much repetition, so these functions aim to simplify and abstract this complexity for developers using them.
The only caveat is that developers must ensure they use the appropriate function for the given input format (string or timestamp).

File: client/utils/date-time.ts (hunk 6 above)
Comment (mgascam) [reply client/utils/date-time.ts]: > If we add these comments as type annotations above, code editors (or VSCode at least) will show these on hover.

That's a great tip, thanks for sharing. I'm following your suggestion here [298fe08](https://github.com/Automattic/woocommerce-payments/pull/9635/commits/298fe08b0483b7ac6379167317853b6cae8a319d).

>This may help future devs understand useGmt – it wasn't immediately clear to me if it means the input is GMT or the output is GMT.

I agree; it wasn’t immediately clear to me either. Initially, I kept it because we were using it in certain places, apparently due to potential incompatibility with WordPress 5.4. However, after reconsidering, I’ve decided to remove it for two reasons:

1. Setting useGmt to true overrides the user’s settings, forcing the output to GMT. This goes against the purpose of this pull request, which aims to respect user preferences.
We’re no longer constrained by the WordPress 5.4 support policy, as the current major version is WordPress 6.7.
2. It's worth mentioning that removing useGmt: true caused some test snapshots to fail. To resolve this, I mocked the dateI18n function to use the GMT timezone, ensuring consistency in the tests.

I believe removing this parameter simplifies the code and improves clarity, but I’d love to hear your thoughts if you have any concerns or alternative suggestions.

Comment (haszari) [reply client/utils/date-time.ts]: I was going to suggest _renaming_ `useGmt` so it's clearer what it does (e.g. `forceDisplayAsUtc` … but removing the option sounds even better 🚀

Comment (Jinksi) [reply client/utils/date-time.ts]: Yeh good point, perhaps we can have a separate function for store TZ and GMT TZ, but both follow the date formatting/locale defined in WP settings.

This is similar to the separate `@wordpress/date` functions [`datei18n()`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-date/#datei18n) for store TZ and [`gmdatei18n()`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-date/#gmdatei18n) for GMT/UTC TZ.

Comment (mgascam) [reply client/utils/date-time.ts]: Thanks for your helpful comments, @haszari and @Jinksi!

If I understand correctly, you're suggesting that it would be beneficial to allow specifying the format as either the store's timezone (TZ) or UTC.  I’ve added a timezone option, leveraging the fact that the [datei18n()](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-date/#datei18n) function supports it.

By default, this option is `undefined`, which means the utility functions will use the store's timezone. However, this also provides the flexibility to override the store's timezone by explicitly setting a different one (UTC or any other), should a need arise. While we don’t currently have a specific use case for this, it seemed like a simple enhancement.

You can review the changes in this commit: [933422e](https://github.com/Automattic/woocommerce-payments/pull/9635/commits/933422e00040f48a13487650adc0c1615f8aa8af).

File: client/capital/index.tsx (hunk 4 above)
Comment (mgascam) [reply client/capital/index.tsx]: Closing this thread as resolved, but please feel free to re-open

File: client/utils/test/date-time.test.ts
Comment (mgascam) [reply client/utils/test/date-time.test.ts:1]: > TLDR: we probably should leave the @wordpress/date upgrade for a subsequent PR that addresses TZ inconsistencies.

Thanks for looking into upgrading the date package. I agree with you in postponing the upgrade to a later PR 👍 . This one grew a bit too much already.

Comment (mgascam) [reply client/utils/test/date-time.test.ts:1]: Marking as resolved, but feel free to reopen.

File: client/utils/date-time.ts (hunk 5 above)
Comment (mgascam) [reply client/utils/date-time.ts]: I'd say this comment is no longer relevant after last changes. But I made sure to mention that the input dates are converted to UTC for consistency e.g. [here](https://github.com/Automattic/woocommerce-payments/blob/933422e00040f48a13487650adc0c1615f8aa8af/client/utils/date-time.ts#L22) and here https://github.com/Automattic/woocommerce-payments/blob/933422e00040f48a13487650adc0c1615f8aa8af/client/utils/date-time.ts#L54

**Comment by rogermattic** [comment]
Hey @mgascam! Thanks for working on this issue, and sorry for the delay in my response. I’m sharing the promised designs now!

**Design**
After considering the importance of this announcement and how noticeable it should be, I decided to use an inline notice. It’s important enough to stand out but doesn’t need the prominence of something like a spotlight, which might be too distracting. Placing it close to the relevant context also felt like the best approach, so I’ve designed it accordingly.

Version A

The message can read:

> The date and time formats now match your preferences. You can update them anytime in the [settings].

Regarding the component, I believe it’s the same `inline notice` used elsewhere in WooCommerce. @nagpai kindly confirmed it’s implemented [here in the WooPayments client code](https://github.com/Automattic/woocommerce-payments/blob/develop/client/components/inline-notice/index.tsx) by inheriting and customizing the WP core notice.

**Behaviour**
I propose we allow the users to dismiss the message manually. Once dismissed, the message should not reappear.
If the user clicks on the link within the message, assume they understand the change and dismiss the message permanently.
Clicking on `settings` link in the message takes the user to the relevant place in the settings area where they can configure the format.

Let me know your thoughts!

**Comment by mgascam** [comment]
> Hey @mgascam! Thanks for working on this issue, and sorry for the delay in my response. I’m sharing the promised designs now!

No worries, and thanks for sharing the designs!

I’ve pushed an initial implementation in this [commit](https://github.com/Automattic/woocommerce-payments/pull/9635/commits/0086c7ceced0ace7f324951976c186e30498fff3). So far, I’ve added the changes to the Transactions list page and the Overview page. The goal is to gather feedback first, and once we’re aligned, I’ll implement the changes across the remaining pages.

### Transactions List

**Desktop**

https://github.com/user-attachments/assets/b7e3d578-3b7b-466a-8f69-4e31e0f88334

**Mobile**

localhost_8082_wp-admin_admin php_page=wc-admin path=%2Fpayments%2Ftransactions(Pixel 7)


### Overview

**Desktop**

Screenshot 2024-12-04 at 12 45 29

**Mobile**

localhost_8082_wp-admin_admin php_page=wc-admin path=%2Fpayments%2Foverview(Pixel 7)

@rogermattic, could you please review and share your feedback? There are a couple of points where I’d like your input:
**1. Table Header Notice Placement**
I couldn’t place the inline notice within the table header. This is due to a limitation in the [TableCard](https://woocommerce.github.io/woocommerce/?path=/docs/woocommerce-admin-components-tablecard--docs) WooCommerce component, which doesn’t support passing a custom component to the header.
I attempted a workaround using the title and actions props, but it didn’t work. The current solution is to place the notice outside the header, as shown in the screenshots.
If this placement isn’t acceptable, we’ll need to add a new feature to the TableCard component in the WooCommerce repo and wait for its release before proceeding. While I’d prefer to ship this sooner, I’ll follow your lead here.
**2. Dismiss Behavior**
I implemented a simple dismiss functionality using browser local storage to persist the user’s preference. This means the notice will remain dismissed unless the user clears their browser’s local storage.
I opted for this approach because I assume this notice will be removed in a future version (perhaps the next one or the one after). If you’d prefer persisting this in the database, let me know, and I can update the implementation.

Thanks, and looking forward to your feedback!

**Comment by rogermattic** [comment]
> If this placement isn’t acceptable, we’ll need to add a new feature to the TableCard component in the WooCommerce repo and wait for its release before proceeding. While I’d prefer to ship this sooner, I’ll follow your lead here.

I mean I'd prefer the placement within the table but if this increases the complexity much, I'd understand this.  

With regards to the Payments Overview though, are we placing it there cause the change also reflects in the mini Deposits overview table? I personally wouldn't advise we have it there otherwise, and even in that case... I'm not sure this needs to be surfaced there... rather than only in the actual Deposits table on the Deposits page. WDYT? 

> I implemented a simple dismiss functionality using browser local storage to persist the user’s preference. This means the notice will remain dismissed unless the user clears their browser’s local storage.

Does it mean that if the user clears the cache, the previously dismissed banner comes back? I'm asking just out of curiosity, as I think this isn't a big deal. And like you say... we should probably keep it for a few release cycles only.

**Comment by rogermattic** [comment]
Actually, after a bit more thinking... I understand it iseasier to implement it above the table, and I hate being stubborn and saying this but I’m leaning towards suggesting that we implement it within the table instead. Unless this really increases the effort massively??
The inline notice doesn’t work well on the gray background, and the alternative general notice style feels too disconnected from the context.  A

**Comment by mgascam** [comment]
Added blocked status until we implement the inline notification in the TableCard header: https://github.com/woocommerce/woocommerce/issues/53496. Please check previous [comments](https://github.com/Automattic/woocommerce-payments/pull/9635#issuecomment-2518643469) for context.

**Comment by haszari** [comment]
> [client/components/date-format-notice/index.tsx](https://github.com/Automattic/woocommerce-payments/pull/9635/files#diff-4ed5fd74e15d5398781ca46c7f655d766e906a7471426d3865cbe19574af803bR1-R42): Added a new DateFormatNotice component to inform users about the new date and time formatting settings and provide a link to configure these settings.

> Added blocked status until we implement the inline notification in the TableCard header: https://github.com/woocommerce/woocommerce/issues/53496. Please check previous https://github.com/Automattic/woocommerce-payments/pull/9635#issuecomment-2518643469 for context.

This is an important PR – making dates respect user preferences. Here's my understanding of why it's blocked:

- We're changing the date formatting.
- So we want to tell the merchant that things changed.
- The mechanism / UX we want to use for that notice is not implemented and needs a change in WooCommerce core.

This is unfortunate – we should be able to fix date formatting without implementing a new kind of notice.

Here are some options I think are reasonable:

1. Ship the change with a release note and clarify in docs (and any release comms). I.e. quietly change it. 
2. Ship the change with a release note, clarify in docs etc as above AND implement some kind of notice in the admin UI. Any kind of notice, whatever works best / we can ship without a hassle.

@rogermattic @mgascam would you be concerned if we went with (1) approach – ship quietly? Do we expect significant support requests – @AashikP keen for your thoughts on risk of shipping quietly. 

@rogermattic – how important is it to you that we delay shipping the date fix until we have a new kind of notice implemented in core? 

> After considering the importance of this announcement and how noticeable it should be, I decided to use an inline notice. It’s important enough to stand out but doesn’t need the prominence of something like a spotlight, which might be too distracting. 

Personally, I think a spotlight notice is reasonable. It's a little loud, but this is a pervasive change (respecting date format throughout WooPayments), so a "global" notice is a good fit. We used a spotlight for payouts which was a less impactful and more localised change.

**Comment by rogermattic** [comment]
> 
> Here are some options I think are reasonable:
> 
> 1. Ship the change with a release note and clarify in docs (and any release comms). I.e. quietly change it.
> 2. Ship the change with a release note, clarify in docs etc as above AND implement some kind of notice in the admin UI. Any kind of notice, whatever works best / we can ship without a hassle.

> @rogermattic @mgascam would you be concerned if we went with (1) approach – ship quietly? Do we expect significant support requests – @AashikP keen for your thoughts on risk of shipping quietly.

I’d definitely go for **option 2**. I think it could get confusing for users if they see a change and don’t know how to get back to their previous setup.

1. They might not realise how their preferences are currently set up.
2. They could worry about exporting, especially if they have something configured elsewhere that depends on the date column.

So yeah, I think it’s quite important to show some kind of context or information.
 

> @rogermattic – how important is it to you that we delay shipping the date fix until we have a new kind of notice implemented in core?

At first, I thought we already had that inline notice ready, so I definitely didn’t mean to delay shipping. I only suggested it because I thought it’d be helpful to have the notice closer to the context —that’s all. Sorry for complicating @mgascam ’s life in the process!

> This is an important PR – making dates respect user preferences. 

@mgascam apologies, but would it still be possible to somehow go back to the notice **style** and **positioning** that you had implemented initially, just with the copy I proposed?

image

**Comment by AashikP** [comment]
>  @AashikP keen for your thoughts on risk of shipping quietly.

From what I understand, this is a very welcome change that implements consistency across WooPayments. Is there a specific reason we'd want to ship this quietly? 

Unless we do, there should be some (any) form of notice to the merchants. Without that, we can expect some support requests. Maybe it is because of confusion and, in some cases, anger because they never noticed that the time now reflects the time they've configured under General settings. 

One extreme example is when the merchant blames us for the lost dispute. They might say they missed the deadline because they assumed the time was in UTC, their time zone, etc.

@aheckler  We should also add a notice in the public docs letting them know what timezone WooPayments uses and how they can change it.

cc @francoishvz

**Comment by aheckler** [comment]
IMHO we should just ship this and not worry about it. No announcement needed other than the release notes / changelog.

The fact that the dates and times shown by WooPayments did NOT respect the merchant's core WP settings from the very beginning is/was a bug. This PR fixes that bug. And we release bug fixes all the time with zero notice. I don't think this one needs to be any different.

I wouldn't even bother mentioning this in the docs to be honest, since following the core WP settings is the obviously correct thing to do.

**Comment by AashikP** [comment]
> The fact that the dates and times shown by WooPayments did NOT respect the merchant's core WP settings from the very beginning is/was a bug. 

@aheckler  Now that you mention it, you're right! I totally missed that this was originally reported as a bug. I assumed this to be a feature update.

There's only one merchant report in the bug report, and we will get back to them during the release phase.

We don't usually provide notices for bug fixes. That said, I'd still consider this notice as `nice to have` just to avoid confusion. 

The public docs update is understandable since this was a bug to begin with. We don't need to specifically mention this in the docs.

**Comment by mgascam** [comment]
Thank you, everyone, for your helpful comments!


>Ship the change with a release note, clarify in docs etc as above AND implement some kind of notice in the admin UI. Any kind of notice, whatever works best / we can ship without a hassle.

@haszari I also prefer this option, and it seems we are all aligned on it. I've made the necessary changes to use the BannerNotice component in this [commit](https://github.com/Automattic/woocommerce-payments/pull/9635/commits/31a6aacb3082b3adf0a8795a7776bfa9eaa4465b).

For context, I completely agree that this is a bug. However, my main concern has been avoiding unintended negative impacts from fixing it, especially given the low number of complaints. The suggestion to show a notice for merchants resonated with me as a practical solution. Additionally, I appreciated @rogermattic's idea to place the notice within the table context, as it would have been more targeted.

Initially, I assumed it would be straightforward to implement this change using the new TableCard component from the woocommerce/components repository. However, after gaining more experience, I realized I underestimated the complexity. Specifically, the plugin relies on the woocommerce/components bundle from WooCommerce core, which means we would need to wait for a new WooCommerce core release. This approach would be problematic, as merchants who update WooPayments without updating WooCommerce core would not see the notice.

Given this limitation, I believe moving forward with the BannerNotice is the best option. While not ideal, it ensures we can inform merchants about the change effectively.

I've added the notice to all pages under the Payments navigation menu. Below are some screenshots for your review—please let me know your thoughts.

Lastly, I’ll be on extended AFK starting Dec 23rd, so it would be great to get additional reviews and feedback next week. Thank you!

Screenshot 2024-12-13 at 17 38 52

Screenshot 2024-12-13 at 17 39 09

Screenshot 2024-12-13 at 17 38 52

cc: @AashikP @aheckler

**Comment by AashikP** [comment]
Looks good to me! Thank you!

File: client/components/date-format-notice/index.tsx [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+const DateFormatNotice: React.FC = () => {
+	const [ isBannerVisible, setIsBannerVisible ] = useState( () => {
+		// Initialize state from localStorage
+		return localStorage.getItem( STORAGE_KEY ) !== 'true';
+	} );
+
+	const handleDismiss = () => {
+		setIsBannerVisible( false );
+		localStorage.setItem( STORAGE_KEY, 'true' );
+	};
```
Comment (Jinksi) [inline client/components/date-format-notice/index.tsx]: 💭 What do you think about persisting this banner dismissed state as a WP option, rather than localStorage?

This would prevent the notice appearing again for a user who may have dismissed in a different browser, or browser session.

There is a similar implementation of using a WP option to persist the "Next Payout Notice" dismissal state.

https://github.com/Automattic/woocommerce-payments/blob/02b16c5ee1a8fb06c9f96ec597c782a68b591619/client/deposits/index.tsx#L28-L46

**Review by Jinksi — APPROVED** [review]
I’ve conducted a round of testing on this PR and can see that it is looking good! It is so good to see more consistent datetime handling across the UI and in the code. 🙌

I've left a suggestion about using WP option rather than `localStorage` to persist the banner dismissal state, which should improve UX for merchants who dismiss the notice.

To summarise the only inconsistencies that I’ve found (not blocking merge):
* Server-generated CSVs datetimes do not use the WP settings datetime format
* Client-generated CSV datetimes *do* use the WP settings datetime format, except for Transactions
  * Transaction client-generated CSV export looks to be intentionally matching the server formatting instead
  * We shouldn’t worry about inconsistencies across JS/server CSVs in this PR, since we are fixing those in #9969. @Automattic/helix we should consider a consistent, intentional approach to datetime formatting as part of the Simplify CSV project paJDYF-g1S-p2 – either use the WP Settings datetime formatting, or use a standard format, e.g. ISO 8601.
* The main dates and times of the transaction timeline view don’t use the WP settings datetime format – this may need to be fixed upstream in `@woocommerce/components`
* Server-generated VAT invoices use a server-defined format – again, not a worry for this PR

### Steps tested
* Set WP date/time settings to `m_d_Y` `H_i` (`12_17_2024` `23_56`)
* Set WP store TZ to New York
* Set browser time to **Mumbai** (Browser Dev Tools → More Tools → Sensors)
* Payments → Overview
  * New notice displayed and links to the correct page ✅
  * Dismissing the notice works ✅
  * Payout dates are formatted as per WP settings ✅
* Payout detail view
  * Dates and times formatted as per WP settings ✅
* Payouts list view
  * Dates and times formatted as per WP settings ✅
  * Client-side CSV export dates and times are formatted as per WP settings  ✅
  * Server CSV export dates and times are not formatted as per WP settings ⚠️
* Transaction detail view
  * Transation summary and dispute dates and times formatted as per WP settings ✅
  * Timeline event details (e.g. payout event) dates and times are formatted as per WP settings ✅
  * Main timeline dates and times are not formatted as per WP settings ⚠️
* Transactions list view
  * Dates and times formatted as per WP settings ✅
  * Client-side CSV export dates and times are not formatted as per WP settings ⚠️
  * Server CSV export dates and times are not formatted as per WP settings ⚠️
* Disputes list view
  * Dates and times formatted as per WP settings ✅
  * Client-side CSV export dates and times are formatted as per WP settings ✅
  * Server CSV export dates and times are not formatted as per WP settings ⚠️
* Dispute challenge view
  * Dates and times formatted as per WP settings ✅
* Capital Loan list view
  * Dates and times formatted as per WP settings ✅
* Documents list view
  * Dates and times formatted as per WP settings ✅
* VAT invoice download
  * Dates and times are formatted as per WP settings ⚠️ (server-generated)

File: client/components/date-format-notice/index.tsx
Comment (Jinksi) [inline client/components/date-format-notice/index.tsx:1]: I gather that we should remove this notice at an arbitrary point in the future once it is no longer new, e.g. in WooPayments 9.0.

So, once merged, we should open an issue to remove this and put it on our radar somewhere so we don't forget.

File: client/components/date-format-notice/index.tsx (hunk 7 above)
Comment (mgascam) [reply client/components/date-format-notice/index.tsx]: > What do you think about persisting this banner dismissed state as a WP option, rather than localStorage?

Yes, this is a better approach. I initially opted for a quick implementation using localStorage, but persisting it as a WordPress option is indeed the more robust solution. Thanks for pointing this out! You can review the changes in this commit: [ffa3ac7](https://github.com/Automattic/woocommerce-payments/pull/9635/commits/ffa3ac7ff7716546de89c0fd9545338cd38c28f6).

File: client/components/date-format-notice/index.tsx
Comment (mgascam) [reply client/components/date-format-notice/index.tsx:1]: Yes, I agree that the notice should be removed in the near future. I'll add it to my TODO list and create an issue in Gamma's backlog as soon as we merge this PR.

File: client/components/date-format-notice/index.tsx (hunk 7 above)
Comment (haszari) [reply client/components/date-format-notice/index.tsx]: Good catch @Jinksi 🙌🏻
