### PR TITLE
Fix to an issue with attaching exchange rates for zero-decimal currencies

### LINKED ISSUE #2930: Multi-currency analytics: non-decimal currency bug
### Describe the bug
When charging an order using the customer currency of Japanese yen, on a store with a base currency of GBP, the analytics incorrectly calculates the converted amounts. 

### To Reproduce

1. create your store with a default currency of GBP
2. Place an order using JPY
3. Note the converted amount in the transactions screen is correct
4. Note the converted amounts in the analytics package are incorrect, the decimals are two places off. 

### Screenshots

Screen Shot 2021-09-16 at 9 36 18 PM
New order in JPY

Screen Shot 2021-09-16 at 9 36 37 PM
Correct converted amount in Transactions screen

Screen Shot 2021-09-16 at 9 35 44 PM
Incorrect converted amounts in analytics

### PR DESCRIPTION
**Pull request by dmallory42**
Fixes #2930

#### Changes proposed in this Pull Request

- Adds a fix to ensure the exchange rate for zero-decimal to non-zero-decimal currencies is stored correctly. The exchange rate provided by Stripe needs to be multipled/divided by 100 in this case, because Stripe expects non-zero decimal amounts to be provided in cents (e.g. 1000 USD = $10.00), but zero-decimal currencies are provided as-is (e.g. 1000 JPY = 1000 yen). This leads to the exchange rate being off by 2dp in these cases.
- Also added a check to make sure the Stripe account currency matches the store default currency. If there is a mis-match here, the exchange rate stored in Stripe will not be usable for analytics because it is converting between presentment currency and Stripe account currency, where we are expecting it to be between presentment currency and store default currency. In these cases, we can just fallback to using the `_wcpay_multi_currency_order_exchange_rate meta key for analytics.
  
- 

#### Testing instructions

* Go to `Settings -> Multi Currency` and add Japanese Yen to your enabled currencies. If the exchange rate isn't fetched manually from the server (this could happen if you are pointing at your local WCPay Server) then go into the settings for Yen and set a manual rate (check what the USD -> Yen conversion rate is using a currency conversion website).
* Also make sure you have a non-zero decimal currency like GBP or EUR set up in Multi-Currency.
* Go to your store, change the currency to JPY using the multi-currency dropdown, and then purchase a product. Make a note of the value of the order in JPY and the original value in USD.
* Change the currency to EUR/GBP using the multi-currency dropdown and make another order. Note the value of the order in EUR and the original value in USD.
* Go to `localhost:8083` and check the `wp_postmeta` table. You should see a meta key `_wcpay_multi_currency_stripe_exchange_rate` for the two orders.
* For the JPY order, multiply the exchange rate by the order value and make sure it gives you the original value of the order in USD (note: this may not be exact, because of fluctuations and differences between the Stripe exchange rate and the multi-currency exchange rate, but it should be close).
* Do the same with the EUR order, and verify it gives you a value which is close to the USD order value.
* Go to `Analytics -> Orders` and verify that you can see the two orders and the totals are displayed correctly.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -11,6 +11,7 @@
 
 use WCPay\Exceptions\{ Add_Payment_Method_Exception, Process_Payment_Exception, Intent_Authentication_Exception, API_Exception };
 use WCPay\Logger;
+use WCPay\MultiCurrency\MultiCurrency;
```
Comment (ismaeldcom) [inline includes/class-wc-payment-gateway-wcpay.php:14]: We finally don't need to use `MultiCurrency` here, right?

**Review by ismaeldcom — APPROVED** [review]
LGTM! Tested with different zero decimal currencies and now the exchange rate is perfect. has been a little more tricky than it seemed. Thanks for fixing it so fast! ⚡ 

Preaproving it, just found a little nitpick, let's 🚢  it!

File: includes/class-wc-payment-gateway-wcpay.php (hunk 1 above)
Comment (dmallory42) [reply includes/class-wc-payment-gateway-wcpay.php]: Good catch! This was leftover from a previous attempt. Fixed in 3795b84d02b8a7b3758e28e063426feecba97a30!
