### PR TITLE
Removed PHP ENUM dependency due to conflicts with multiple PHP versions

### LINKED ISSUE #5533: Current enum library in use is 1.7.7, causing errors when PHP version is 8.1+
### Describe the bug

[The message/error can be seen here](https://gist.github.com/anastas10s-afk/a92eda6a03e0567c362b5899afc278e0), literally overtaking the whole screen.

### To Reproduce

Suffices to have WooCommerce & WooCommerce Payments active on a site, where the PHP version is 8.1+, for the errors to start appearing.

### Actual behavior

WooCommerce Payments apparently [returns an error, with PHP versions 8.1.14 & 8.2.1](https://wordpress.org/support/topic/status-on-updating-depreciated-php-call-please/#post-16389912), in my staging installation.
[Nothing I could find on GitHub](https://github.com/Automattic/woocommerce-payments/issues?q=is%3Aissue+in%3Atitle+php+is%3Aopen).

### Screenshots

https://snipboard.io/vjslMy.jpg

### Expected behavior

Have the enum library updated, please.
The enum library currently in use is 1.7.7: 
https://github.com/Automattic/woocommerce-payments/blob/develop/composer.lock

While its newer versions contain a fix: 
https://github.com/myclabs/php-enum/releases

### Additional context

- https://wordpress.org/support/topic/error-with-php-8-1/

### PR DESCRIPTION
**Pull request by zmaglica**
Fixes #5533 

#### Changes proposed in this Pull Request

In newer versions of PHP (8.1 and 8.2), the enum package we use could throw warnings and errors because the package uses some deprecated functions which cause some errors and warnings. To overcome this issue, the ENUM package has been removed and implemented a built-in solution that mimics the package functionalities.

#### Testing instructions

Make sure that all tests are passing.

*

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: includes/constants/class-base-constant.php [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+
+	/**
+	 * Compare to enums.
+	 *
+	 * @param mixed $variable Constant object to compare.
+	 *
+	 * @return bool
+	 */
+	final public function equals( $variable = null ): bool {
+		return $variable instanceof self && $this->get_value() === $variable->get_value() && static::class === \get_class( $variable );
```
Comment (marcinbot) [inline includes/constants/class-base-constant.php]: Shouldn't this be `$variable instanceof static` instead of `self`? And wouldn't that be the same as `static::class === \get_class( $variable )` for the purposes of this function?

File: includes/constants/class-base-constant.php [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+		return new static( $name );
+	}
+
+	/**
+	 * Get real enum value.
+	 *
+	 * @return mixed|string
+	 */
+	public function __toString() {
+		return constant( \get_class( $this ) . '::' . $this->value );
```
Comment (marcinbot) [inline includes/constants/class-base-constant.php]: I think `$this->get_value()` would be better in case we ever want to serialize the constants and pass them to JS.

File: includes/constants/class-base-constant.php [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+	/**
+	 * Class constructor.
+	 *
+	 * @param mixed $value Constant from class.
+	 */
+	public function __construct( $value ) {
+		if ( $value instanceof static ) {
+			$value = $value->get_value();
+		}
+		$this->value = $value;
```
Comment (marcinbot) [inline includes/constants/class-base-constant.php:44]: I think there should be some validation to check that the `$value` is a valid constant on the class. We could use the `search` function for that.

File: includes/constants/class-base-constant.php (hunk 1 above)
Comment (zmaglica) [reply includes/constants/class-base-constant.php]: Yes, you are correct. I will remove instance of check.

File: includes/constants/class-base-constant.php (hunk 3 above)
Comment (zmaglica) [reply includes/constants/class-base-constant.php:44]: I think that a better option would be to move the constant validation form _callStatic to the constructor, so we don't have to use the search function. The search function is used to get a constant name from a constant value, so in this case it will not be good option to use.

**Review by marcinbot — COMMENTED** [review]
The code looks good, but haven't tested everything yet.

File: includes/constants/class-base-constant.php [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+
+	/**
+	 * Compare to enums.
+	 *
+	 * @param mixed $variable Constant object to compare.
+	 *
+	 * @return bool
+	 */
+	final public function equals( $variable = null ): bool {
+		return $this->get_value() === $variable->get_value() && static::class === \get_class( $variable );
```
Comment (htdat) [inline includes/constants/class-base-constant.php]:
```suggestion
		return is_object( $variable ) && static::class === \get_class( $variable ) && $this->get_value() === $variable->get_value();
```

Tight up the conditions here: move the check class name as the second condition and a check with `is_object`? Otherwise, comparing with a random value (not created by this Enum) can yell errors. Then add the relevant tests too. 

You can apply this diff for the test file https://gist.github.com/htdat/c874e552412fc2c8fd85a33b0c91295a and run PHP tests to see these errors ` npm run test:php -- --filter=Base_Constant_Test`.

File: includes/constants/class-base-constant.php [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+
+if ( ! defined( 'ABSPATH' ) ) {
+	exit; // Exit if accessed directly.
+}
+
+
+/**
+ * Base constant class to hold common logic for all constants.
+ */
+abstract class Base_Constant {
```
Comment (htdat) [inline includes/constants/class-base-constant.php:20]: Nitpick: Since we're really writing a base class for enums, shall we call this `Enum` rather than `Base_Constant` like the previously imported package?

File: tests/unit/test-class-base-constant.php [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+class Base_Constant_Test extends WCPAY_UnitTestCase {
+
+	public function test_base_constant_will_create_constant() {
+		$class = Payment_Method::BASC();
+		$this->assertInstanceOf( Payment_Method::class, $class );
+		$this->assertSame( $class->get_value(), 'BASC' );
+		$this->assertSame( (string) $class, 'bacs_debit' );
+	}
+
+	public function test_get_const_name_by_value() {
```
Comment (htdat) [inline tests/unit/test-class-base-constant.php]: May remove this one as it's a duplication of `test_class_will_return_const_name_if_searched_by_correct_const_value`.

File: includes/constants/class-base-constant.php [hunk 7]
```diff
@@ -0,0 +1,106 @@
...
+
+	/**
+	 * Class constructor.
+	 *
+	 * @param mixed $value Constant from class.
+	 * @throws \InvalidArgumentException
+	 */
+	public function __construct( $value ) {
+		if ( $value instanceof static ) {
+			$value = $value->get_value();
```
Comment (htdat) [inline includes/constants/class-base-constant.php:37]: Nitpick: I am not sure if it's only me but I found out `$value` and `get_value` confusing. We're actually referring to constant names here, so I think they would be `$name` and `get_name`? 

For example, here `BASC` is the constant name while `bacs_debit` is the constant value. 

https://github.com/Automattic/woocommerce-payments/blob/ea1865e88eae4c152fe4125ff29b5bd6b89a38c2/includes/constants/class-payment-method.php#L22

**Review by htdat — CHANGES_REQUESTED** [review]
Besides my inline comments, I manually tested some flows with xDebug enabled to ensure that the relevant methods from the base class are covered: 

- Check out with non-UPE flow for testing `__callStatic` ([code ref](https://github.com/Automattic/woocommerce-payments/blob/ea1865e88eae4c152fe4125ff29b5bd6b89a38c2/includes/class-wc-payment-gateway-wcpay.php#L822-L823)), and `equals` ([code ref](https://github.com/Automattic/woocommerce-payments/blob/ea1865e88eae4c152fe4125ff29b5bd6b89a38c2/includes/class-wc-payment-gateway-wcpay.php#L1079-L1079))
- Enable MultiCurrency with additional payment methods such as `giropay` for testing `search` ([code ref](https://github.com/Automattic/woocommerce-payments/blob/ea1865e88eae4c152fe4125ff29b5bd6b89a38c2/includes/multi-currency/PaymentMethodsCompatibility.php#L69-L69))

For manual testing with GlobalStep, I think asking them to check wp-content/debug.log and ensuring no relevant error are quite enough.

File: includes/constants/class-base-constant.php (hunk 4 above)
Comment (zmaglica) [reply includes/constants/class-base-constant.php]: `is_object` validation is not necessary because get_class will return the name of the class, even for primitive types like int and string. The only thing that we could check is that the `$variable` is an instance of a base constant, so we don't have an issue with get_value() not existing on the passed variable.

File: includes/constants/class-base-constant.php (hunk 5 above)
Comment (zmaglica) [reply includes/constants/class-base-constant.php:20]: The reason why I put it as a base const since we're only using this for constants, and if you look from a different perspective, the enums are constants with steroids, and I wasn't sure where to put enum class since it felt wired to put it inside const folder with "Enum" name.

File: tests/unit/test-class-base-constant.php (hunk 6 above)
Comment (zmaglica) [reply tests/unit/test-class-base-constant.php]: Noted. I will fix this.

File: includes/constants/class-base-constant.php (hunk 7 above)
Comment (zmaglica) [reply includes/constants/class-base-constant.php:37]: This approach is a fallback legacy to Enum package we used before, and I mimic the function calls to make it backward compatible.

File: includes/constants/class-base-constant.php (hunk 4 above)
Comment (htdat) [reply includes/constants/class-base-constant.php]: > because get_class will return the name of the class, even for primitive types like int and string

This seems not... true. https://3v4l.org/tFM3p

> The only thing that we could check is that the $variable is an instance of a base constant, so we don't have an issue with get_value() not existing on the passed variable.

I think this works too.

File: changelog/fix-5533-remove-enum-dependecy [hunk 8]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Removed PHP ENUM dependency due to conflicts with multiple PHP versions.
```
Comment (htdat) [inline changelog/fix-5533-remove-enum-dependecy]: Maybe also update the PR title a bit to reflect that we are not just going to "remove" the package but also add a replacement.

```suggestion
Replace PHP dependency myclabs/php-enum with a built-in solution due to conflicts with multiple PHP versions.
```

File: includes/constants/class-base-constant.php (hunk 4 above)
Comment (zmaglica) [reply includes/constants/class-base-constant.php]: Fixed in 7bc2338108d0882d11be026767037bd102509de7

File: tests/unit/test-class-base-constant.php (hunk 6 above)
Comment (zmaglica) [reply tests/unit/test-class-base-constant.php]: Fixed in 3caf6def25a21932cfa2e70f087a52edb7d07671

**Review by htdat — APPROVED** [review]
I am pre-approving PR. 
But it's worth double-checking to see why E2E tests failed. 

From quick looking at a run failure https://github.com/Automattic/woocommerce-payments/actions/runs/4321710982, this seems irrelevant to this change.
