### PR TITLE
Minor copy improvements on the Settings page

### LINKED ISSUE #7299: (Minor) WooPayments `General` settings help text emphasises test mode
### Describe the bug
In the settings screen for WooPayments, there's help text to explain each category of settings. 

The top category is `General` and the main setting is to enable / disable WooPayments. There's also a much less important `Test mode` setting (mostly used by developers, or stores trialling WooPayments). 

The help text says: `Enable or disable WooPayments on your store and turn on test mode to simulate transactions.`. As I see it, this places a lot of emphasis on `Test mode` as a setting the merchant might want to toggle.

Screenshot 2023-09-27 at 2 24 27 PM

### Expected behavior
My suggested change is to either:

- Remove the help text – I think the label `General` and the copy in the settings box do a good job of explaining the settings. Less is more. Declutter. (I prefer this)
- OR
- Simplify the help text to focus on the fact that these are high-level settings that affect things globally: `Enable WooPayments on your store` or `Global settings`.

### PR DESCRIPTION
**Pull request by anu-rock**
Fixes #7299

#### Changes proposed in this Pull Request

* De-emphasize test mode in the description for General settings section - screenshot below.
* Fix sofort migration links - replaced the docs link from `#sofort-deprecation` to `#sofort-migration`.

A note about the second change: The old link https://woo.com/document/woopayments/payment-methods/additional-payment-methods/#sofort-deprecation doesn't work anymore. The section in the docs it refers to seems to have been renamed recently, causing the link to break.

image

#### Testing instructions

This pull request contains very minor text refinements. Reviewing them should be enough.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8410` or branch name `update/7299-general-settings-desc` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/7299-general-settings-desc) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: e23115b8768032f62b1bc214d1101daab5ffdf9c
- Build time: 2024-03-22 10:49:14 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by mordeth — APPROVED** [review]
✅  Changes are looking good!

**Review by elazzabi — APPROVED** [review]
Looks good

File: client/components/payment-methods-list/payment-method.tsx [hunk 1]
```diff
@@ -350,7 +350,7 @@ const PaymentMethod = ( {
 						) }
 						<a
 							// eslint-disable-next-line max-len
-							href="https://woo.com/document/woopayments/payment-methods/additional-payment-methods/#sofort-deprecation"
+							href="https://woo.com/document/woopayments/payment-methods/additional-payment-methods/#sofort-migration"
```
Comment (haszari) [inline client/components/payment-methods-list/payment-method.tsx:353]: What's the rationale for this change? Seems unrelated. 

> Fix sofort migration links - replaced the docs link from #sofort-deprecation to #sofort-migration.

I saw  ⏫  in PR description but didn't see a linked issue or explanation why – i.e. are there external links that use `-migration` that were broken? Or are we changing the wording to soften (`deprecation` is hard)?

File: changelog/update-7299-general-settings-desc [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
+Type: update
+
+Minor copy improvements on the Settings page.
```
Comment (haszari) [inline changelog/update-7299-general-settings-desc]: Suggest making this specific since it's a targeted improvement – e.g. `Remove mention of test mode from general settings help text`. Though probably can skip changelog for this.

**Review by haszari — APPROVED** [review]
Thanks for picking this up @anu-rock ! I made some nitpicky minor comments … but this looks good & safe to me (note I did not test, assuming other reviewers have). Small things like this make our settings page focused and uncluttered – more friendly.

File: client/components/payment-methods-list/payment-method.tsx (hunk 1 above)
Comment (anu-rock) [reply client/components/payment-methods-list/payment-method.tsx:353]: This issue is indeed unrelated. The old link https://woo.com/document/woopayments/payment-methods/additional-payment-methods/#sofort-deprecation doesn't work anymore. I think someone from the docs team renamed the Sofort section (and hence the internal link) recently, causing it to break here.

I noticed it by chance while testing this PR. I included the fix here as the code change is loosely related to what I intended to originally do - fix text on the Settings page.

File: changelog/update-7299-general-settings-desc (hunk 2 above)
Comment (anu-rock) [reply changelog/update-7299-general-settings-desc]: That makes sense. I'll update the changelog.

**Review by dmallory42 — APPROVED** [review]
Looks good to me. Thanks for making this change!

File: client/components/payment-methods-list/payment-method.tsx (hunk 1 above)
Comment (anu-rock) [reply client/components/payment-methods-list/payment-method.tsx:353]: Updated the PR description with the reasoning for this change. Marking this thread as resolved. Thanks for the tip!

File: changelog/update-7299-general-settings-desc (hunk 2 above)
Comment (anu-rock) [reply changelog/update-7299-general-settings-desc]: Updated in https://github.com/Automattic/woocommerce-payments/pull/8410/commits/8a0707c91202c28f26d1a96ab300cb90cf96381c.
