### PR TITLE
Fix WooPay checkboxes while signed in

### LINKED ISSUE #9186: Multiple payment method saving checkboxes
### Describe the bug
image

Two payment method saving checkboxes are displayed at the same time.

### To Reproduce

1. Sign into a merchant's store with a shopper account
2. Go to checkout
3. Enter email that does NOT have a WooPay account
4. See both checkboxes present on checkout

### Expected behavior
Only WooPay's checkbox should be visible in this case.

Expected behavior from @pierorocca:
Store - signed out, WooPay - not known user -> Show WooPay checkbox.
Store - signed out, WooPay - signed in -> Show no checkboxes
**Store - signed-in, WooPay - not known user -> Show WooPay checkbox (currently showing both)**
Store - signed-in, WooPay - signed in-> Show no checkboxes or show store checkbox? (currently showing store checkbox)

### PR DESCRIPTION
**Pull request by alefesouza**
Fixes #9186

#### Changes proposed in this Pull Request

This PR updates the `Save payment information to my account for future purchases.` checkbox and the WooPay checkbox while the user is signed in to match what is described [here](https://github.com/Automattic/woocommerce-payments/issues/9186#issuecomment-2257205073).

Also updates the WooPay component spacing to match 2JyXNimI4oGeJZhgQNZE9V-fi-1168_19276.

#### Testing instructions

* Logout on WooPay.
* Sign in on the merchant store.
* Add products to the cart.
* Access the blocks checkout page.
* The `Save payment information to my account for future purchases.` checkbox should be hidden.
* If the user email exists on WooPay, the WooPay checkbox should be hidden, if not, the WooPay checkbox should be shown.
* Sign in on WooPay with the same email.
* Reload the checkbox page.
* The `Save payment information to my account for future purchases.` checkbox and the WooPay one should be hidden.
* Change the email to a non existent WooPay email.
* Click the WooPay checkbox.
* Design should match 2JyXNimI4oGeJZhgQNZE9V-fi-1168_19276.
* You can also follow [this comment](https://github.com/Automattic/woocommerce-payments/issues/9186#issuecomment-2257205073) to test while logged out on merchant store.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9240` or branch name `fix/woopay-checkboxes-while-signed-in` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/woopay-checkboxes-while-signed-in) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 17b5316e2c8dd22d637c55102ab511556a5f3c02
- Build time: 2024-08-13 03:10:05 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by leonardola — CHANGES_REQUESTED** [review]
It's mostly working but I found one flow that was not described that seems to be broken

- Log out of WooPay 
- Log in to the merchant site with the same email as WooPay
- Visit the checkout page
- The checkboxes won't show up, just as expected
- Now remove the email. Checkboxes don't show up
- Type in a non WooPay email. Checkboxes don't show up

File: client/checkout/woopay/email-input-iframe.js [hunk 1]
```diff
@@ -530,6 +530,14 @@ export const handleWooPayEmailInput = async (
 		}
 	} );
 
+	if ( woopayEmailInput.value ) {
+		const email = woopayEmailInput.value;
+
+		if ( validateEmail( email ) ) {
+			woopayLocateUser( email, false );
```
Comment (leonardola) [inline client/checkout/woopay/email-input-iframe.js:541]: The locate user function is doing way more than just locate an user. It's adding tracks and opening an iframe so we should rename it to something that actually tells what it is doing. I though of `showIframeToWooPayUserOrShowOptIn` but we're not actually showing the opt-in here. We're just tracking that it shows up even though that happens somewhere else. It might be good to actually move the tracking code to where we actually show the opt-in

File: includes/class-wc-payments-checkout.php [hunk 2]
```diff
@@ -347,9 +347,14 @@ public function get_enabled_payment_method_config() {
 	 * @return bool - True if the payment method is reusable and the saved cards feature is enabled for the gateway and there is no subscription item in the cart, false otherwise.
 	 */
 	private function should_upe_payment_method_show_save_option( $payment_method ) {
+		if ( $payment_method->get_id() === Payment_Method::CARD && is_user_logged_in() && WC_Payments_Features::is_woopay_enabled() ) {
```
Comment (leonardola) [inline includes/class-wc-payments-checkout.php:350]: What about non UPE merchants? Did all merchants get migrated to UPE or WooPay is not available for non UPE merchants?

File: client/checkout/woopay/email-input-iframe.js [hunk 3]
```diff
@@ -398,7 +398,7 @@ export const handleWooPayEmailInput = async (
 				// Dispatch an event after we get the response.
 				dispatchUserExistEvent( data[ 'user-exists' ] );
 
-				if ( data[ 'user-exists' ] ) {
+				if ( data[ 'user-exists' ] && shouldOpenIframe ) {
 					openIframe( email );
 				} else if ( data.code !== 'rest_invalid_param' ) {
 					recordUserEvent( 'checkout_woopay_save_my_info_offered' );
```
Comment (leonardola) [inline client/checkout/woopay/email-input-iframe.js:406]: If the user exists but the Iframe is not shown are we offering the opt-in still because we're recording a track event as if we did show the opt-in

**Comment by alefesouza** [comment]
> Now remove the email. Checkboxes don't show up

@pierorocca should we show the checkbox when the user empty the email field? The field will have an error message.

> Type in a non WooPay email. Checkboxes don't show up

@leonardola I could reproduce that when the user has a saved payment method and it's selected, was this the case for you? Apparently [this line](https://github.com/Automattic/woocommerce-payments/blob/914cef65fd3e35a47ed9e5cc2004790bef9621a8/client/components/woopay/save-user/checkout-page-save-user.js#L190) limits the WooPay account creation only when the user chooses to add a new payment method.

**Comment by pierorocca** [comment]
> @pierorocca should we show the checkbox when the user empty the email field? The field will have an error message.

Which field? Until it's known they're a WooPay user, the checkbox should be shown. A null/blank email should show the checkbox. Continue to show the checkbox after it's determined the email is not a WooPay user (most users at this point). 

Another way to look at it is - always show checkbox until it's known that the email belongs to a WooPay user, at which point the checkbox is hidden.

Also account for a user that navigates back either using Checkout as guest or Alternative payment methods. If at any point the user changes the prefilled email to a non-WooPay email, show the checkbox.

File: includes/class-wc-payments-checkout.php (hunk 2 above)
Comment (alefesouza) [reply includes/class-wc-payments-checkout.php:350]: The `showSaveOption` [here](https://github.com/Automattic/woocommerce-payments/blob/914cef65fd3e35a47ed9e5cc2004790bef9621a8/includes/class-wc-payments-checkout.php#L324) is the one that shows the save card option and it references only this method, also I couldn't downgrade to non-UPE and didn't find any related things on the WCPay DevTools, I found the following P2: paJDYF-9xf-p2

@pierorocca could you confirm that we only use UPE on WCPay right now?

File: client/checkout/woopay/email-input-iframe.js (hunk 3 above)
Comment (alefesouza) [reply client/checkout/woopay/email-input-iframe.js:406]: Fixed on https://github.com/Automattic/woocommerce-payments/pull/9240/commits/284bebdd60c3923600b24965048f34f6c0b6737c.

File: client/checkout/woopay/email-input-iframe.js (hunk 1 above)
Comment (alefesouza) [reply client/checkout/woopay/email-input-iframe.js:541]: > We're just tracking that it shows up even though that happens somewhere else.

It happens inside the `dispatchUserExistEvent` when it's `false`.

> It might be good to actually move the tracking code to where we actually show the opt-in

Yes, but we should not track when the response is `rest_invalid_param` [here](https://github.com/Automattic/woocommerce-payments/blob/284bebdd60c3923600b24965048f34f6c0b6737c/client/checkout/woopay/email-input-iframe.js#L405).

**Comment by pierorocca** [comment]
> @pierorocca could you confirm that we only use UPE on WCPay right now?

I missed this question. Yes only UPE is in use on WooPayments on stores that meet the minimum requirement for WooPay.

**Review by leonardola — APPROVED** [review]
Changes look good now. Thanks for working on the fixes
