### PR TITLE
Remove pending renewal order creation from admin page

### LINKED ISSUE #3139: Merchant (admin) should not be able to add a pending renewal order for Stripe billing subscriptions
### Describe the bug
There is an option in the `Subscription Actions` dropdown allowing admins to `Create a pending renewal order`:

Screen Shot 2021-10-18 at 4 48 05 PM

This should only be shown for subscriptions that support early manual renewal. This is not supported for WCPay Subscriptions, as the renewal is handled by Stripe Billing / WCPay.

### To Reproduce
1. Set up WCPay Subscriptions. Ensure WooCommerce Subscriptions extension is disabled, update to `develop` or a version of WCPay that includes built-in subscriptions, and enable the feature flag. Set up a subscription product.
2. Purchase a subscription as a shopper.
3. As admin, go to `WooCommerce > Subscriptions` and click through to a subscription (click ID number in `Subscription` column.
4. Click actions dropdown.

#### Actual behavior
`Create a pending renewal order` is available.

#### Expected behavior
`Create a pending renewal order` should not be shown for WCPay Stripe Billing subscriptions. This flow is not available for these subscriptions.

### PR DESCRIPTION
**Pull request by brianyu28**
Fixes #3139 

#### Changes proposed in this Pull Request

For WCPay Subscriptions, remove "Create pending renewal order" as a subscription action, since renewals are handled by Stripe Billing.

Create pending renewal order

Subscriptions Core adds the "Create pending renewal order" option by hooking into the `woocommerce_order_actions` filter. This PR removes the option by hooking into the same filter after Subscriptions Core and removing the option.

Question: Subscriptions Core will add the `wcs_create_pending_parent` action instead of `wcs_create_pending_renewal` if there isn't already a parent order on the subscription. Does WCPay Subscriptions support manually creating the parent order? I believe so, but if not, we should remove the `wcs_create_pending_parent` action too.

#### Testing instructions

* Set up WCPay Subscriptions, and ensure WooCommerce Subscriptions is disabled.
* As a customer, purchase a new subscription product.
* As admin, go to `WooCommerce > Subscriptions`, click on the subscription ID, and look at the options in the "Subscription actions" dropdown. "Create a pending renewal order" should not appear as an option.

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/subscriptions/class-wc-payments-subscription-service.php [hunk 1]
```diff
@@ -570,6 +571,21 @@ public function prevent_wcpay_subscription_changes( bool $supported, string $fea
...
+	 *
+	 * @param array $actions Array of available actions.
+	 * @return array Array of updated actions.
+	 */
+	public function prevent_wcpay_manual_renewal( array $actions ) {
+		global $theorder;
+
+		if ( wcs_is_subscription( $theorder ) && self::is_wcpay_subscription( $theorder ) ) {
+			unset( $actions['wcs_create_pending_renewal'] );
+		}
```
Comment (haszari) [inline includes/subscriptions/class-wc-payments-subscription-service.php:585]: Perhaps we should [remove this default from `subscriptions-core`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/admin/class-wcs-admin-meta-boxes.php#L173) and re-add it only in subs pro. Thoughts @james-allan ?

IMO `subscriptions-core` should not implement behaviour that is not needed for the WCPay Subscriptions use case. Then we wouldn't need to add hooks to disable pro-only functionality like this.

**Review by haszari — COMMENTED** [review]
This looks reasonable, though I think it would be simpler and more robust to factor that action out of `subscriptions-core` and into the pro extension (see comment).

File: includes/subscriptions/class-wc-payments-subscription-service.php (hunk 1 above)
Comment (james-allan) [reply includes/subscriptions/class-wc-payments-subscription-service.php:585]: > IMO subscriptions-core should not implement behaviour that is not needed for the WCPay Subscriptions use case.

These actions are needed for creating subscriptions manually and managing manual subscriptions so subscriptions-core will need to maintain them for that case. 

So IMO the approach is to either:

- Keep this PR as it is. Which is fine.
- Or. Add the logic Brian is adding here to core so core holds the context about removing the actions for WCPay Subscriptions. 

Honestly, doing it in WCPay is the cleaner approach IMO because you don't have to juggle core having that logic and then having to override it or add additional context in the WC Subscriptions plugin.

File: includes/subscriptions/class-wc-payments-subscription-service.php [hunk 2]
```diff
@@ -570,6 +571,21 @@ public function prevent_wcpay_subscription_changes( bool $supported, string $fea
...
+	 * Remove pending renewal order creation from admin edit subscriptions page.
+	 *
+	 * @param array $actions Array of available actions.
+	 * @return array Array of updated actions.
+	 */
+	public function prevent_wcpay_manual_renewal( array $actions ) {
+		global $theorder;
+
+		if ( wcs_is_subscription( $theorder ) && self::is_wcpay_subscription( $theorder ) ) {
+			unset( $actions['wcs_create_pending_renewal'] );
```
Comment (james-allan) [inline includes/subscriptions/class-wc-payments-subscription-service.php:584]: We'll also need to unset the `wcs_create_pending_parent` action here. It's somewhat difficult to get that to show up but you can achieve it by:

1. Creating a subscription manually. 
2. Set the status to active.
3. Add line items and a customer.
4. Using the changes in #3095, 
      - log in as the customer
      - go to the My Account subscription page and set up your subscription with WCPayments via the add payment flow. 
5. View the subscription actions as an admin user. 

The `wcs_create_pending_parent` action would be shown but we wouldn't want admin to create pending parent orders for WCPay Subscriptions either. 

If we're being super cautious we would also want to unset `wcs_process_renewal`. At the moment it is won't be shown for WCPay Subscriptions given they don't support [date changes](https://github.com/automattic/woocommerce-subscriptions-core/blob/trunk/includes/admin/class-wcs-admin-meta-boxes.php#L182), if in the future we do support date changes, we would still not want it to be shown, so might as well remove it.

Comment (james-allan) [reply includes/subscriptions/class-wc-payments-subscription-service.php:585]: Awsome.
