### PR TITLE
Show Payments → Overview waiting period notice for new accounts that have completed one or more transactions

### LINKED ISSUE #8040: New account waiting period notice is not displayed for new accounts (regression)
### Describe the bug
After onboarding to WooPayments, the first payouts are held for 7-14 days to mitigate risk for new accounts. We have a notice to explain this to merchants:

seven business days

However, it's not currently displaying, because the notice is not rendered unless … the store has at least one deposit (! 🤨): 

https://github.com/Automattic/woocommerce-payments/blob/81f4be369a8571fa708316dcccbb2290a4732f0e/client/components/deposits-overview/index.tsx#L91-L94

Thanks @Jinksi for discovering this

### To Reproduce
1. Onboard a new WooPayments account.
2. Make a test purchase.
3. Go to `Dashboard > Payments` overview screen.

Should have a message here explaining that deposits will start 7-14 days after first payment.

### Actual behavior
No notice on overview.

There is one in settings:

Screenshot 2024-01-18 at 10 45 07 AM

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #8040

#### Changes proposed in this Pull Request

This PR shows the new account waiting period deposit notice on the Payments → Overview screen for new accounts within the waiting period who have received a transaction (have a pending or available balance).

image

Accounts that have not received any transactions (no pending or available balance) will not see the notice on the Payments → Overview screen.

image

Note: the wording of this notice is being updated in #8030

#### Testing instructions

* Test with a new account that has not received any transactions
* On the Payments → Overview screen, you should not see the deposits card or the new account waiting period notice
* Complete a transaction to accrue some pending funds
* On the Payments → Overview screen, you should see the deposits card and the new account waiting period notice

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : __QA Testing Not Applicable__
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable. **N/A**
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable. **N/A**

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8041` or branch name `fix/8040-new-account-waiting-period-notice` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8040-new-account-waiting-period-notice) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 6e9e181ebfbbe95c940ec2cee7c8186bdd8b9709
- Build time: 2024-01-18 04:26:34 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/components/deposits-overview/index.tsx [hunk 1]
```diff
@@ -144,50 +149,54 @@ const DepositsOverview: React.FC = () => {
...
-						wcpayTracks.recordEvent(
-							wcpayTracks.events
-								.OVERVIEW_DEPOSITS_VIEW_HISTORY_CLICK
-						)
-					}
-				>
-					{ __(
-						'View full deposits history',
-						'woocommerce-payments'
+			{ ( hasRecentDeposits || canChangeDepositSchedule ) && (
```
Comment (Jinksi) [inline client/components/deposits-overview/index.tsx:153]: This is a minor change, recommend using the "Hide whitespace" option in the GH diff viewer

File: changelog/fix-8040-new-account-waiting-period-notice [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+On Payments Overview, show the first deposit waiting period notice for new accounts that have transacted
```
Comment (haszari) [inline changelog/fix-8040-new-account-waiting-period-notice]: Could use `reinstate` or similar wording to clarify that this is putting something back. 

e.g. `Reinstate first deposit waiting period notice in payments overview (fix bug)`

File: client/components/deposits-overview/index.tsx [hunk 3]
```diff
@@ -88,8 +89,12 @@ const DepositsOverview: React.FC = () => {
...
 	}
 
-	// This card isn't shown if there are no deposits, so we can bail early.
-	if ( ! isLoading && deposits.length === 0 ) {
+	if (
+		! hasCompletedWaitingPeriod &&
+		availableFunds === 0 &&
+		pendingFunds === 0
+	) {
+		// If the account has not received any transactions before completing the waiting period, don't show the deposits overview section.
```
Comment (haszari) [inline client/components/deposits-overview/index.tsx]: This comment might be easier to read above the if (less indentation). 

Also … getting my head around it, I think it means…

- Don't show deposits card if
  - The site is still in the waiting period
  - AND 
  - The site has no transactions

Or 

```
If still in new account waiting period and account has no transactions,
don't render deposits card (nothing to show).
```

File: client/components/deposits-overview/index.tsx [hunk 4]
```diff
@@ -133,7 +138,7 @@ const DepositsOverview: React.FC = () => {
 				) }
 			</CardBody>
 
-			{ showRecentDeposits && (
+			{ hasRecentDeposits && (
```
Comment (haszari) [inline client/components/deposits-overview/index.tsx:142]: Nice – only show deposits history & heading if there are some deposits to show 👌🏻

File: client/components/deposits-overview/index.tsx [hunk 5]
```diff
@@ -144,50 +149,54 @@ const DepositsOverview: React.FC = () => {
...
-								.OVERVIEW_DEPOSITS_VIEW_HISTORY_CLICK
-						)
-					}
-				>
-					{ __(
-						'View full deposits history',
-						'woocommerce-payments'
+			{ ( hasRecentDeposits || canChangeDepositSchedule ) && (
+				<CardFooter className="wcpay-deposits-overview__footer">
+					{ hasRecentDeposits && (
```
Comment (haszari) [inline client/components/deposits-overview/index.tsx:155]: Only render link to deposits list if there are deposits 👌🏻

File: client/components/deposits-overview/index.tsx [hunk 6]
```diff
@@ -144,50 +149,54 @@ const DepositsOverview: React.FC = () => {
...
-						}
-					>
-						{ __(
-							'Change deposit schedule',
-							'woocommerce-payments'
-						) }
-					</Button>
-				) }
-			</CardFooter>
+					{ canChangeDepositSchedule && (
```
Comment (haszari) [inline client/components/deposits-overview/index.tsx:176]: Only render link to deposit settings if it can be edited/changed 👌🏻

**Review by haszari — APPROVED** [review]
Logic looks great – much more readable with each boolean variable split out.

I've tested on my new site with some transactions, and confirmed the notice now shows:

Screenshot 2024-01-18 at 3 47 55 PM

I also tested with my other store that has transactions, and is out of the waiting period, but has no payouts, and the UI also is correct/makes sense:

Screenshot 2024-01-18 at 3 57 39 PM

So  … both my tests were somewhat edge-case.

I haven't tested other scenarios! I'm guessing you've tested with a normalish account (multiple payouts), let me know if you want more testing.

**Comment by haszari** [comment]
> I've tested on my new site with some transactions, and confirmed the notice now shows:

Screenshot 2024-01-18 at 3 47 55 PM

Actually there's a bug here!

> Available funds are automatically dispatched every day – your next deposit is scheduled for January 19th, 2024.

> Your first deposit is held for seven business days. Why?

I onboarded this store todayish, so my next deposit should be after the 7-day waiting period. We probably need to log an issue for that, maybe introduced as part of the changes to remove estimated deposit. 

Note also this makes calculating the next deposit date trickier, as it needs to take into account the waiting period (#4435).

File: changelog/fix-8040-new-account-waiting-period-notice (hunk 2 above)
Comment (Jinksi) [reply changelog/fix-8040-new-account-waiting-period-notice]: 😃 resolved in 721c3c6faeb27e19bdfbcedc0f9f75dad664e019

File: client/components/deposits-overview/index.tsx (hunk 3 above)
Comment (Jinksi) [reply client/components/deposits-overview/index.tsx]: 👍 nice suggestion, resolved in 6e9e181ebfbbe95c940ec2cee7c8186bdd8b9709

**Comment by Jinksi** [comment]
> I onboarded this store todayish, so my next deposit should be after the 7-day waiting period. 

This could be a scenario specific to test accounts. I wouldn't expect accounts within the waiting period to have `available` funds, but that's an assumption.

I agree, new issue to investigate and resolve if necessary.

Update: or resolve as part of https://github.com/Automattic/woocommerce-payments-server/issues/4435

**Comment by Jinksi** [comment]
I've tested an account that is out of the waiting period and has a deposit history – rendered as expected.

image

**Comment by Jinksi** [comment]
Confirmed the following behaviour for a fresh JN account:

No transactions, no deposits overview card:

image

First transaction occurs, deposits overview card and notice is rendered:

image

Note that the schedule is displayed, but no expected date (since available balance = 0).
