### PR TITLE
Use UPE gateway for card when WooPay disabled and Link enabled

### LINKED ISSUE #1645: Develop branch - the plugin conflicts with the Stripe plugin
To reproduce:
- Checkout `develop`
- Install and activate the Stripe gateway
- Attempt to load the site, get a fatal error:
```
Fatal error: Cannot declare class WC_Payment_Token_SEPA, because the name is already in use
```
Screenshot 2021-04-21 at 13 03 25

cc @harriswong

### PR DESCRIPTION
**Pull request by FangedParakeet**
Fixes 1645-gh-Automattic/woopay

Resolves compatibility with Stripe Link when split UPE gateway is enabled. The split UPE gateway will now use the legacy card gateway **only** when WooPay is enabled: when WooPay is disabled, we can use a split UPE gateway for the card gateway, which will allow us to use Link with the UPE card gateway.

#### Changes proposed in this Pull Request

When the split UPE gateway is enabled, legacy card gateway will only be used when WooPay is enabled; otherwise, split UPE card gateway will be used. Stripe Link now functional in both classic and blocks checkouts with split UPE gateway enabled. 

#### Testing instructions

Please test the following:

- Link checkout/signup flow with split UPE enabled (shortcode and blocks).
- Link checkout/signup flow with legacy UPE enabled (shortcode and blocks).
- Card checkout with Link disabled with split UPE enabled (shortcode and blocks).
- Card checkout with Link disabled with legacy UPE enabled (shortcode and blocks).
- Card checkout with WooPay enabled with split UPE enabled (shortcode and blocks).

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by mdmoore** [comment]
In general, it looks like Link is working as expected off of the UPE gateway. All Link in blocks flows are working well 🥳!

I'm running into to 2 issues while testing: 

1. When Split UPE is enabled, an error occurs on the **shortcode checkout** page when the Stripe element attempts to mount. The error is: 
`wc is not defined`. Here's the console:

```
Uncaught (in promise) ReferenceError: wc is not defined
    getConfig checkout.js:12
    decryptClientSecret encryption.js:14
    mountUPEElement upe-split.js:309
    async* upe-split.js:410
    jQuery 7
    success checkout.min.js:1
    jQuery 7
    update_checkout_action checkout.min.js:1
    setTimeout handler*update_checkout checkout.min.js:1
    jQuery 7
    init_checkout checkout.min.js:1
    jQuery 7
    init checkout.min.js:1
    <anonymous> checkout.min.js:1
    jQuery 13
checkout.js:12:18
```

I wonder if `decryptClientSecret()` needs to call `getUPEConfig()` instead, which looks for `wcpay_upe_config` rather than the undefined `wcpayConfig`. When Split UPE is enabled, [the config object is named `wcpay_upe_config`](https://github.com/Automattic/woocommerce-payments/blob/9b8c8abef36552f144412041710b589cd1c7e232/includes/class-wc-payments-upe-checkout.php#L234). 

~~2. When WooPay is enabled, the legacy card element isn't used. The UPE gateway is used instead:~~ https://github.com/Automattic/woocommerce-payments/pull/5541#issuecomment-1432240327



Let me know if I've missed any configuration that might alleviate the above issues.

**Comment by mdmoore** [comment]
>Let me know if I've missed any configuration that might alleviate the above issues.

In a quick moment of clarity, I realized I was expecting to be automatically pushed behind the Split UPE flag when enabling WooPay. I was forcing legacy UPE with the Dev Tools. When I test with Split UPE + WooPay, #2 above is void. WooPay + Split UPE + Blocks Checkout is 👌.

**Comment by FangedParakeet** [comment]
> When Split UPE is enabled, an error occurs on the shortcode checkout page when the Stripe element attempts to mount. The error is:
> wc is not defined. Here's the console:

@mdmoore I actually resolved this in f32aaab4eda84972575e247c79c74ce0d244cb8d by allowing `getConfig` to use `getUPEConfig` as a fallback, but it seems that got overwritten in a merge. I just returned that functionality in 8fcba3d6290aa4fe01245bf4d251a7f831bb7a10. 

I'm not sure if it will cause any drawbacks, but can't see any immediately. Let me know if that solves this problem. 🙏

**Comment by timur27** [comment]
#### Gateway appearance
Within this step, the goal was to check if _Stripe Payment Element/Card Element_ both appeared as expected depending on the settings. No payment attempts were performed as part of this step. The below results refer to both shortcode and blocks checkouts.

_Split UPE_

1. WooPay & Link disabled -> Stripe Payment Element ✅ 
2. WooPay enabled & Link disabled -> Card Element in shortcode ✅ but Payment Element in blocks ❌ 
3. WooPay disabled & Link enabled -> Stripe Payment Element ✅
    - For EUR, Link button is not shown and the autofill modal is not launched ✅ 
    - For USD, Link button is shown and the autofill modal is launched ✅ 

_Legacy UPE_
WooPay & Link disabled -> Stripe Payment Element ✅
WooPay disabled & Link enabled -> Stripe Payment Element ✅

#### Payment processing
From the previous step, we know what is the behavior on the UI depending on the settings. The current step focuses on the gateway functionality. 

##### Split UPE

_WooPay & Link disabled_
1. Shortcode checkout ❌ 
<details><summary>What's the error</summary>
<p>

```json
{
  "result": "failure",
  "messages": "<ul class=\"woocommerce-error\" role=\"alert\">\n\t\t\t<li>\n\t\t\tInvalid payment method. Please input a new card number.\t\t</li>\n\t</ul>\n",
  "refresh": false,
  "reload": false
}
```

image

</p>
</details>

2. Blocks checkout ✅ 

_WooPay enabled & Link disabled_
1. Shortcode checkout ✅ 
2. Blocks checkout ❌ 
<details><summary>What's the error</summary>
<p>

```json 
{
  "code": "woocommerce_rest_checkout_process_payment_error",
  "message": "Invalid payment method. Please input a new card number.",
  "data": {
    "status": 402
  }
}
```

image


</p>
</details>

_WooPay disabled & Link enabled_
1. Shortcode - similar behavior as with _WooPay & Link disabled_ ❌ 
2. Blocks - similar behavior as with _WooPay & Link disabled_ ✅ 

##### Legacy UPE 
_WooPay & Link disabled_
1. Shortcode ✅ 
2. Blocks ✅ 

_WooPay disabled & Link enabled (USD)_
1. Shortcode ✅ 
2. Blocks ✅

**Comment by mdmoore** [comment]
After @timur27 found and fixed a couple issues earlier, I've completed another round of testing to ensure no regression. I'm happy to report that everything is working well! 

## Appearance
### Spit UPE - Blocks and Shortcode Checkout
WooPay & Link disabled -> Stripe Payment Element ✅
WooPay enabled & Link disabled -> Card Element ✅
WooPay disabled & Link enabled -> Stripe Payment Element ✅
- For EUR, Link button is not shown and the autofill modal is not launched ✅
- For USD, Link button is shown and the autofill modal is launched ✅

### Legacy UPE - Blocks and Shortcode Checkout
WooPay & Link disabled -> Stripe Payment Element ✅
WooPay disabled & Link enabled -> Stripe Payment Element ✅



## Payment Processing
### Spit UPE

#### WooPay & Link disabled
- Shortcode Checkout ✅
- Blocks Checkout ✅

#### WooPay enabled & Link disabled
- Shortcode Checkout ✅
- Blocks Checkout ✅

#### WooPay disabled & Link enabled
- Shortcode Checkout ✅
- Blocks Checkout ✅

### Legacy UPE

#### WooPay & Link disabled
- Shortcode Checkout ✅
- Blocks Checkout ✅

#### WooPay disabled & Link enabled
- Shortcode Checkout ✅
- Blocks Checkout ✅

**Review by frosso — APPROVED** [review]

File: client/checkout/classic/upe-split.js [hunk 1]
```diff
@@ -701,14 +702,11 @@ jQuery( function ( $ ) {
 	/**
 	 * Checks if the customer is using a saved payment method.
 	 *
-	 * @param {string} paymentMethodType Stripe payment method type ID.
 	 * @return {boolean} Boolean indicating whether or not a saved payment method is being used.
 	 */
-	function isUsingSavedPaymentMethod( paymentMethodType ) {
```
Comment (frosso) [inline client/checkout/classic/upe-split.js:707]: This will make SEPA fail once attempting to make it compatible with Split UPE, but patching this way to make things work
