### PR TITLE
Fix subscriptions price strings for variations and sign up fees.

### LINKED ISSUE #2122: "From" price for variable subscriptions not converted
Variable subscriptions may have a "From" price displayed along with the actual price per variation. The "From" price is not being converted into the selected currency.

If the product also includes a signup fee, the signup fee is not converted in the "From" pricing, either.

Steps to replicate:

1. Create a variable subscription product that has at least 2 attributes and variations.
2. The variations will need to have different prices.
3. View product, and the _From_ price will not be converted.

Markup 2021-06-10 at 10 57 32

### PR DESCRIPTION
**Pull request by jessepearson**
Fixes #2122 #2130

#### Changes proposed in this Pull Request

* Added filters for Subscriptions price strings.
* No tests added due to Subs has to be installed for this.

#### Testing instructions

* Use a variable subscription product that has price differences between variations, and also a sign up fee for at least one variation.
* View product, and change currency.
* Confirm that from and sign up fee amounts are converted
* Select a variation and confirm price string below variation selection is converted.

Screen Capture on 2021-06-15 at 12-18-33

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/multi-currency/class-frontend-prices.php [hunk 1]
```diff
@@ -51,6 +51,10 @@ public function __construct( Multi_Currency $multi_currency ) {
 			add_filter( 'woocommerce_coupon_get_amount', [ $this, 'get_coupon_amount' ], 50, 2 );
 			add_filter( 'woocommerce_coupon_get_minimum_amount', [ $this, 'get_coupon_min_max_amount' ], 50 );
 			add_filter( 'woocommerce_coupon_get_maximum_amount', [ $this, 'get_coupon_min_max_amount' ], 50 );
+
+			// Subscription product hooks.
+			add_filter( 'woocommerce_subscriptions_product_price', [ $this, 'get_product_price' ], 50, 2 );
+			add_filter( 'woocommerce_subscriptions_product_sign_up_fee', [ $this, 'get_product_price' ], 50, 2 );
```
Comment (luizreis) [inline includes/multi-currency/class-frontend-prices.php:57]: What do you think of adding these hooks to the [filters test](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/unit/multi-currency/test-class-frontend-prices.php#L48)? I think the `has_filter` check should work even if Subscriptions is not installed as part of the unit tests.

**Review by luizreis — APPROVED** [review]
LGTM! I had a concern about mixing Subscriptions compatibility logic with the `Frontend_Prices` class but it seems to be fine, at least while it's just a couple of hooks. Feel free to :shipit: once the comment regarding adding that simple test is addressed!
