### PR TITLE
Fix - error while checking out with UPE when fields are hidden

### LINKED ISSUE #2743: Unable to Complete Checkout with WCPay When Phone field is "Hidden" (via Customizer) at Checkout
When the Phone field is set to `Hidden` in the Customizer under **WooCommerce > Checkout**, payments via WooCommerce Payments do not go through, failing with an error:

```
You specified "never" for fields.billing_details.phone when creating the payment Element, but did not pass confirmParams.payment_method_data.billing_details.phone when calling stripe.confirmPayment or stripe.confirmSetup. If you opt out of collecting data via the payment Element using the fields option, the data must be passed at confirm-time.
```

wcpaycheckouterror

User had initially `unset` the field via custom code, but then saw same issue after removing the code and hiding the field via Customizer. I confirmed the same on my test site.

Initially when testing with the field marked as `Optional` and leaving it blank seemed to work, so just hiding it via CSS looked like a temporary workaround. However, at the moment I am unable to make that work either. Leaving it Optional (and UN-hidden), it is displaying this error:

```
You passed an empty string for 'payment_method_data[billing_details][phone]'. We assume empty values are an attempt to unset a parameter; however 'payment_method_data[billing_details][phone]' cannot be unset. You should remove 'payment_method_data[billing_details][phone]' from your request or supply a non-empty value.
```

wcpaycheckouterror

### PR DESCRIPTION
**Pull request by naman03malhotra**
Fixes #2743  #2688 #2785 

#### Changes proposed in this Pull Request

- Passing a truthy `-` as value for the fields in case they are undefined or empty.

#### Testing instructions 1

- Install [checkout field editor](https://github.com/woocommerce/woocommerce-checkout-field-editor).
- goto WooCommerce => Checkout fields.
- Hide `billing_phone` or/and `billing_address_2` fields.
- Try checking out with UPE.
- Order should pass through, no errors observed.

#### Testing instructions 2
- Install [checkout field editor](https://github.com/woocommerce/woocommerce-checkout-field-editor).
- goto WooCommerce => Checkout fields.
- Keep `billing_phone` or/and `billing_address_2` fields but do not mark them as required.
- Try checking out with UPE.
- Order should pass through, no errors observed.

#### Testing instructions 3
- Install [checkout field editor](https://github.com/woocommerce/woocommerce-checkout-field-editor).
- goto WooCommerce => Checkout fields.
- Keep `billing_phone` or/and `billing_address_2` fields and mark them as required.
- Try checking out with UPE.
- Order should pass through, no errors observed.

-------------------

- [x] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

File: client/checkout/classic/upe.js [hunk 1]
```diff
@@ -116,11 +116,9 @@ jQuery( function ( $ ) {
 	const hiddenBillingFields = {
 		name: 'never',
```
Comment (naman03malhotra) [inline client/checkout/classic/upe.js:117]: Just want to confirm, all these other fields will always be required during checkout with UPE right? I am not sure if the customer would want to hide one of these remaining fields as well using customizer, else it will throw a similar error.

**Comment by aprea** [comment]
This appears to fix the issue when using the provided testing instructions but introduces a new problem.

Testing instructions:
- Install [checkout field editor](https://github.com/woocommerce/woocommerce-checkout-field-editor).
- Navigate to **WooCommerce** → **Checkout fields**.
- Remove the `Required` validation rule from the `billing_phone` field & save (the field should still be enabled)
- Fill in all the required checkout fields but leave the phone number field empty.
- Attempt to checkout
- Observe the following error:

> You passed an empty string for 'payment_method_data[billing_details][phone]'. We assume empty values are an attempt to unset a parameter; however 'payment_method_data[billing_details][phone]' cannot be unset. You should remove 'payment_method_data[billing_details][phone]' from your request or supply a non-empty value.

Screen Shot 2021-09-06 at 2 59 15 pm

Rather than hardcoding the `hiddenBillingFields` variable, is it possible to build this list dynamically on the backend and pass it down to the client via an inline script? i.e. https://developer.wordpress.org/reference/functions/wp_add_inline_script/

File: client/checkout/classic/upe.js (hunk 1 above)
Comment (aprea) [reply client/checkout/classic/upe.js:117]: I was trying to some docs for this options object, I found this page https://stripe.com/docs/js/elements_object/create_element?type=card

But wasn't about to find docs for the `payment` element type that we use here https://github.com/Automattic/woocommerce-payments/blob/c2dd9bbaab9d337e933e1a1c168740d1cc46965b/client/checkout/classic/upe.js#L302

image

Is it because this feature is in private beta? Any ideas?

**Comment by naman03malhotra** [comment]
@achyuthajoy and I were discussing this on a pairing session, this what we discovered:
So stripe throws an error when we pass an empty string while processing the payment. Initially, we thought of excluding each field from the `getBillingFields` Object but a better approach would be to filter the data for non-empty values while creating the fields object. Fixed this in: https://github.com/Automattic/woocommerce-payments/pull/2853/commits/650ebd562204c2641a359a8a0cf58ff1364d23bb

File: client/checkout/classic/upe.js (hunk 1 above)
Comment (naman03malhotra) [reply client/checkout/classic/upe.js:117]: We backtraced the PR which was responsible for adding this code. We found that there is no official documentation for this feature as this is in beta and stripe proved information about this may be via google docs. More details here: https://github.com/Automattic/woocommerce-payments/issues/1981

File: client/checkout/classic/upe.js [hunk 2]
```diff
@@ -499,7 +497,9 @@ jQuery( function ( $ ) {
 		blockUI( $form );
 		// Create object where keys are form field names and keys are form field values
 		const formFields = $form.serializeArray().reduce( ( obj, field ) => {
-			obj[ field.name ] = field.value;
+			if ( '' !== field.value ) {
+				obj[ field.name ] = field.value;
+			}
```
Comment (marcinbot) [inline client/checkout/classic/upe.js:502]: Would it work if we left `hiddenBillingFields` as is and assigned an empty string to any form fields that are specified by that variable but not there?

I think the issue is that, with the checkout customizer, the field is not there and therefore the will be missing from the `formFields` which will then trigger the error.

So checking for an empty string here won't do anything I think.

File: client/checkout/classic/upe.js [hunk 3]
```diff
@@ -116,11 +116,9 @@ jQuery( function ( $ ) {
 	const hiddenBillingFields = {
 		name: 'never',
 		email: 'never',
-		phone: 'never',
 		address: {
 			country: 'never',
 			line1: 'never',
-			line2: 'never',
```
Comment (marcinbot) [inline client/checkout/classic/upe.js:123]: I see the resolved conversation here: https://github.com/Automattic/woocommerce-payments/pull/2853#discussion_r702253708 but I think allowing these two fields but not the others will still cause occasional issue reports. Yes, these two are the most common, but then, for example, some countries don't have states, so a merchant could disable that field.

So we should prepare for any of these fields to be missing (even if it doesn't make any sense to hide name/email inputs) and handle it differently.

#1981 has been mentioned which fixes empty customer details on the txn admin page, but TBH if the admin decides to not take any of those details, then it's still better to process the transaction with empty strings rather than fail with a scary error.

File: client/checkout/classic/upe.js (hunk 2 above)
Comment (naman03malhotra) [reply client/checkout/classic/upe.js:502]: >Would it work if we left hiddenBillingFields as is and assigned an empty string


The problem is with passing the empty string. Stripe expects to pass any other character except a `""` string. So if a field is marked as optional and the customer does not fill any input, we get an empty string value for which stripe throws as an error.

Here, by checking for the empty string, we are excluding the fields which didn't receive any input and should not be sent to stripe. Another option would be to check if the input value is empty and pass some other character like `-`.

File: client/checkout/classic/upe.js (hunk 3 above)
Comment (naman03malhotra) [reply client/checkout/classic/upe.js:123]: >some countries don't have states, so a merchant could disable that field

I agree, there can be a case where merchants can disable other fields as well.

We can follow one of two approaches here:
- Remove if not all but some more of these fields marked as required, but I am not sure what those fields should be and what would be the side-effects for that change, let's say we don't pass state information while checking out to stripe, would that be okay?
- While creating `billing_details` object, we can check for the empty values and assign `undefined` or `-`.

File: client/checkout/classic/upe.js (hunk 2 above)
Comment (naman03malhotra) [reply client/checkout/classic/upe.js:502]: We can leave `hiddenBillingFields` as is, but then we have to check if the field value is empty and pass some other character with truthy value. But IMO, `hiddenBillingFields` we have only those fields which are absolutely required.

Comment (naman03malhotra) [reply client/checkout/classic/upe.js]: Assigning a truthy value seems like a better and scalable approach to me, made changes here: https://github.com/Automattic/woocommerce-payments/pull/2853/commits/07652b3f8c62d617005cc9499c3351a2301ae039

We can discuss the relevance and what values should exist in `hiddenBillingFields` in a separate ticket.

Comment (marcinbot) [reply client/checkout/classic/upe.js]: Ah, I missed the empty string discussion above, my bad 😅 So it seems that the problem has been the object created by `getBillingDetails`. Maybe the fix would be to add a check to `getBillingDetails` to remove any keys that are null or empty?

Sorry for trying to guess what would work here, I can't find any UPE docs on the internet.

Comment (naman03malhotra) [reply client/checkout/classic/upe.js]: >Maybe the fix would be to add a check to getBillingDetails to remove any keys that are null or empty?

If a field is marked as required in `hiddenBillingFields` then it has to be passed with`billing_details`. That is why in [my first approach](https://github.com/Automattic/woocommerce-payments/pull/2853/files/650ebd562204c2641a359a8a0cf58ff1364d23bb) I remove the required fields and filtered our the empty keys, but the problem with that is what if the merchant remove any other field which is marked as required eg `state` then a similar error will be thrown. So for now I think passing a truthy value when the field value is missing or empty should do the job in every scenario.

Comment (marcinbot) [reply client/checkout/classic/upe.js]: > Assigning a truthy value seems like a better and scalable approach to me

We seem to have posted this around the same time, and I still think that maybe removing the keys from the object is worth testing for whether it will work here. It seems like a cleaner solution. None of the address fields are required in the traditional way of creating an intent [[doc](https://stripe.com/docs/api/customers/object#customer_object-address)] so we shouldn't have to force them here either.

But if for any reason it doesn't work, then yes, having a truthy placeholder looks like a fine solution to me too :)

Comment (naman03malhotra) [reply client/checkout/classic/upe.js]: UPE is beta so docs are not public, stripe shared some docs internally with us here: https://github.com/Automattic/woocommerce-payments/issues/1981

Comment (marcinbot) [reply client/checkout/classic/upe.js]: > in my first approach I remove the required fields

Yes, the field values are removed, but then due to how `getBillingDetails` works, it will always produce a key for that value. For example, with the missing address line 2 it would be `address.line2 = null` and I think that's what Stripe is complaining about. If there never was an `address.line2` key, then no problem should occur.

Comment (marcinbot) [reply client/checkout/classic/upe.js]: I just tested and removing the key does not work. I think the truthy value approach is the best one for now.

**Review by marcinbot — APPROVED** [review]
LGTM :shipit:

**Comment by vbelolapotkov** [comment]
Marking as ready based on Marcin's approval
