### PR TITLE
Fallback to card payment type in get_payment_method_types

### LINKED ISSUE #8969: Investigate need for creating payment intent with fallback of all enabled payment methods
### Describe the bug

As part of https://github.com/Automattic/woocommerce-payments/pull/8966 it was noted that the Payment Intent was created with all the enabled payment methods.

This is happening because this line isn't detecting the correct payment method being used:
https://github.com/Automattic/woocommerce-payments/blob/13ea0cffabe45301b6f2850036784e389142559b/includes/class-wc-payment-gateway-wcpay.php#L2059-L2059

As part of the PR review process, we discussed the possibility of removing such fallback, and just using `card` instead: https://github.com/Automattic/woocommerce-payments/pull/8966#pullrequestreview-2122582752

The purpose of this ticket is to investigate the need for such fallback, to determine if it's needed in any of the supported scenarios.
If it's not needed, let's fallback to using `card`, instead.

### PR DESCRIPTION
**Pull request by mdmoore**
Fixes #8969 

#### Changes proposed in this Pull Request

Rather than falling back to to all enabled payment methods in `get_payment_method_types()`, this PR changes the fallback to `card`. After testing all different payment flows, including saved payment methods, express checkouts and subscription renewals, I've found that the only scenario that will hit the fallback is WooPay payments. This means it's safe to fallback to `card`. It's possible that tokenized ECE payments will also land in the fallback, in which case `card` will also be good.

#### Testing instructions

* Test various payments such as
  - New card payment
  - Saved card payment
  - ECE payment
  - Subscription renewal
  - Pay for order
  - WooPay
  - Any other payment scenario that might be affected

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9829` or branch name `8969-fallback-to-card-payment-type` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=8969-fallback-to-card-payment-type) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 4d98b58424f37f414847101dcec3e5a79a868667
- Build time: 2024-12-05 19:34:28 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by timur27** [comment]
I think we removed the changes with the most recent commit.

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -2127,8 +2127,8 @@ public function get_payment_method_types( $payment_information ): array {
 			$order_id        = $order instanceof WC_Order ? $order->get_id() : null;
 			$payment_methods = $this->get_payment_methods_from_gateway_id( $token->get_gateway_id(), $order_id );
 		} else {
-			// Final fallback case, if all else fails.
-			$payment_methods = WC_Payments::get_gateway()->get_payment_method_ids_enabled_at_checkout( null, true );
+			// Final fallback case, if all else fails. WooPay payments will use this case.
+			$payment_methods = [ Payment_Method::CARD ];
```
Comment (timur27) [inline includes/class-wc-payment-gateway-wcpay.php]: This fallback is pretty general, and if any code calling this method has some bug in the payment method area, we will fall to the card payment method, which does seem a little bit risky.

Since it's WooPay and ECE, can we specify their fallback? 

For WooPay, can the following line 

```php
$woopay_intent_id = sanitize_user( wp_unslash( $_POST['platform-checkout-intent'] ?? '' ), true );
```

implemented [after the `get_payment_method_types` is called](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L1578) be added to the more specific check, rather than returning card if for everything? 

Regarding ECE, I tested and it seems that we have mappings ([#1](https://github.com/Automattic/woocommerce-payments/blob/develop/client/tokenized-express-checkout/transformers/stripe-to-wc.js#L76-L79) [#2](https://github.com/Automattic/woocommerce-payments/blob/develop/client/tokenized-payment-request/transformers/stripe-to-wc.js#L85-L88)) which will ensure the `payment_method` request param will be always present for this type of payment flow. Can we double-check whether this is the case and if yes then it seems that the only thing to fall back to is the WooPay scenario which can be specified by using the `platform-checkout-intent` payment request param in the `else if`.

What are your thoughts? Thanks!

**Review by timur27 — COMMENTED** [review]
An alternative to the idea mentioned in https://github.com/Automattic/woocommerce-payments/pull/9829#discussion_r1861940313 would be to consider moving [the retrieval of payment methods](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L1574) to [the non-WooPay intent creation flow](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L1604) because this variable seems to be used within that code block only? 

From the implementation it seems that WooPay will not enter that flow because it will create an intent before and the intent should be non-empty at this point. So, maybe this change will allow us to completely remove the fallback in `get_payment_method_types`.

This is just an idea, which seems to be worth consideration but need to be double-checked.

**Comment by timur27** [comment]
Let's also consider making `get_payment_method_types` private if it's supposed to be used within the gateway class.

**Comment by mdmoore** [comment]
>From the implementation it seems that WooPay will not enter that flow because it will create an intent before and the intent should be non-empty at this point. So, maybe this change will allow us to completely remove the fallback in get_payment_method_types.

Thanks for the suggestion. After testing, it looks like the fallback can be safely removed. I've done so in [b8ae943](https://github.com/Automattic/woocommerce-payments/pull/9829/commits/b8ae943944c1ea6fe3cae3819d7fa789489549c7) if you can take another look when you have a chance. Thanks Timur!

File: tests/unit/payment-methods/test-class-upe-split-payment-gateway.php [hunk 2]
```diff
@@ -1140,58 +1140,6 @@ public function test_get_payment_methods_without_request_context() {
...
-		$mock_upe_gateway->expects( $this->once() )
-			->method( 'get_payment_method_ids_enabled_at_checkout' )
-			->willReturn( [ Payment_Method::CARD ] );
-
-		$payment_methods = $mock_upe_gateway->get_payment_method_types( $payment_information );
-
-		$this->assertSame( [ Payment_Method::CARD ], $payment_methods );
-
-		WC_Payments::set_gateway( $gateway );
-	}
```
Comment (mdmoore) [inline tests/unit/payment-methods/test-class-upe-split-payment-gateway.php]: Removing this test case since it's testing the fallback case that has been removed.

File: tests/unit/test-class-wc-payment-gateway-wcpay.php [hunk 3]
```diff
@@ -1239,21 +1239,6 @@ public function test_get_payment_methods_without_post_request_context() {
...
-		$gateway = WC_Payments::get_gateway();
-		WC_Payments::set_gateway( $this->card_gateway );
-
-		$payment_methods = $this->card_gateway->get_payment_method_types( $payment_information );
-
-		$this->assertSame( [ Payment_Method::CARD ], $payment_methods );
-
-		WC_Payments::set_gateway( $gateway );
-	}
-
```
Comment (mdmoore) [inline tests/unit/test-class-wc-payment-gateway-wcpay.php:1256]: This is also testing the removed fallback case.

**Review by timur27 — APPROVED** [review]
Looks much cleaner now in general, thank you! 💪 

May I ask to quickly have a look whether the suggestion from https://github.com/Automattic/woocommerce-payments/pull/9829#issuecomment-2507215725 make sense and apply it if so?

**Comment by mdmoore** [comment]
>May I ask to quickly have a look whether the suggestion from https://github.com/Automattic/woocommerce-payments/pull/9829#issuecomment-2507215725 make sense and apply it if so?

Sorry for not addressing this one. My only concern is that we might break some integration at this point, given that this is the main gateway class. Internally, we're only using `get_payment_method_types()` within the `WC_Payment_Gateway_WCPay` class, but it's hard to know what external integrations have extended the class and made use of the function. If that's not a concern, we can make the change to `private`.

**Comment by timur27** [comment]
> My only concern is that we might break some integration at this point, given that this is the main gateway class. Internally, we're only using get_payment_method_types() within the WC_Payment_Gateway_WCPay class, but it's hard to know what external integrations have extended the class and made use of the function

This is interesting. I wasn't thinking about it because we don't define any APIs to be used by other plugins. Let's keep it public for now, but it would be good to discuss why it was public in the first place and how to gracefully reduce method accessibility given potential problems with third-party integrations.
