### PR TITLE
Unify payment method icon design

### LINKED ISSUE #7183: Align logo border with icon edge
### Describe the bug

For PM icons that have filled background, the border applied with CSS doesn't perfectly align with the fill. 

This is no an issue with icons with transparent backgrounds (which is most of cases)

### Screenshots
image
### To Reproduce

1. Go to `payments->settings`
2. Observe the Affirm Icon in PM list

### Expected behavior
There shouldn't be a gap between the background and border. 

It can be achieved in several ways:
- have dedicated icons with border in the SVG (not preferred) 
- Adjust Affirm Icon
- Adjust the CSS rule (could be hard, since we are using `box-shadow` not `border`)

### PR DESCRIPTION
**Pull request by KarlisJ**
Fixes #7183

#### Changes proposed in this Pull Request

Unify the design for Payment method and Card icon design.
- borders are consistent 
- alignement is consistent

#### Testing instructions

TODO: Need to list all use places. Quite hard to gather them all

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by KarlisJ** [comment]
We still need to fix some failing tests, mostly just recreating snapshots.

Also, this PR needs to address the use cases where assets are used as CSS backgrounds. I might skip it since there are no problems with alignment or borders.

File: client/payment-methods-icons.tsx [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+import DinersClubAsset from 'assets/images/cards/diners.svg?asset';
+import UnionPayAsset from 'assets/images/cards/unionpay.svg?asset';
+
+import './style.scss';
+
+const iconComponent = ( src: string, alt: string ): ReactImgFuncComponent => (
+	props
+) => <img className={ 'payment-method__icon' } src={ src } alt={ alt } />;
+
+// export const CreditCardIcon = iconComponent(
```
Comment (kalessil) [inline client/payment-methods-icons.tsx]: Dead code?

File: client/payment-methods-icons.tsx [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+// 	CreditCardAsset,
+// 	'Credit / Debit card'
+// );
+
+export const BancontactIcon = iconComponent( BancontactAsset, 'Bancontact' );
```
Comment (kalessil) [inline client/payment-methods-icons.tsx]: Not sure, but we should probably make alt-text translatable for all icons declared here.

File: client/payment-methods-icons.tsx [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+export const GooglePayIcon = iconComponent( GooglePayAsset, 'Google Pay' );
+
+export const VisaIcon = iconComponent( VisaAsset, 'Visa' );
+export const MastercardIcon = iconComponent( MasterCardAsset, 'Mastercard' );
+export const AmericanExpressIcon = iconComponent(
+	AmexAsset,
+	'American Express'
+);
+export const DinersClubIcon = iconComponent( DinersClubAsset, 'Diners Club' );
+export const UnionPayIcon = iconComponent( UnionPayAsset, 'UnionPay' );
```
Comment (kalessil) [inline client/payment-methods-icons.tsx]: It'd also be great to have constants sorted by name.

**Review by kalessil — COMMENTED** [review]
Early feedback: looks good! Leaving some comments to look into (minor ones).

File: client/payment-methods-map.tsx [hunk 4]
```diff
@@ -200,11 +197,10 @@ const PaymentMethodInformationObject: Record<
 			affirm: __( 'Affirm', 'woocommerce-payments' ),
 		},
 		description: __(
-			// translators: %s is the store currency.
-			'Allow customers to pay over time with Affirm. Available to all customers paying in %s.',
+			'Expand your business with Affirm',
```
Comment (mgascam) [inline client/payment-methods-map.tsx]: I noticed we are changing the description for Affirm and Afterpay, is this intended? Asking because for Klarna we are not changing this description.

File: client/style.scss [hunk 5]
```diff
@@ -169,3 +169,24 @@
 	.components-tooltip {
 	display: none;
 }
+
+img {
+	&.payment-method__icon {
+		outline: 1px solid rgba( 0, 0, 0, 0.25 );
```
Comment (mgascam) [inline client/style.scss:175]: out of curiosity, why we use `outline` instead of `border` ? Asking because border is more commonly used.

File: client/payment-methods-map.tsx [hunk 6]
```diff
@@ -217,11 +213,10 @@ const PaymentMethodInformationObject: Record<
 			afterpay_clearpay: __( 'Afterpay', 'woocommerce-payments' ),
 		},
 		description: __(
-			// translators: %s is the store currency.
-			'Allow customers to pay over time with Afterpay. Available to all customers paying in %s.',
+			'Expand your business with Afterpay',
```
Comment (mgascam) [inline client/payment-methods-map.tsx]: Same as previous comment

**Review by mgascam — COMMENTED** [review]
Looking great already! I left a couple of comments to double check with you.

One thing I noticed is that the Link icon does not have border on the Payment > Settings screen in the Express Checkout section.

Screenshot 2023-10-26 at 11 48 26

File: client/payment-methods-icons.tsx [hunk 7]
```diff
@@ -0,0 +1,84 @@
...
+import DinersClubAsset from 'assets/images/cards/diners.svg?asset';
+import UnionPayAsset from 'assets/images/cards/unionpay.svg?asset';
+
+import './style.scss';
+
+const iconComponent = ( src: string, alt: string ): ReactImgFuncComponent => (
+	props
+) => <img className={ 'payment-method__icon' } src={ src } alt={ alt } />;
+
+export const AffirmIcon = iconComponent( AffirmAsset, __( 'Affirm' ) );
```
Comment (kalessil) [inline client/payment-methods-icons.tsx]: It's typically 2 parameters: string and the domain `woocommerce-payments`

File: client/payment-methods-map.tsx (hunk 4 above)
Comment (KarlisJ) [reply client/payment-methods-map.tsx]: Not intended, thanks for pointing out. Could be incorrect merge from `develop`. I'll look into that.

File: client/style.scss (hunk 5 above)
Comment (KarlisJ) [reply client/style.scss:175]: @bradyv Could answer better to this question as the credit for CSS goes to him.

AFAIU, the issue with the border was that it's is drawn around the asset which created the inconsistencies between CC icon (which had the individual borders baked into the asset) and other assets. 

With the new grid approach that might not be the problem anymore. 

Luckily, we now have single source of truth for the border CSS and it can be easily adjusted.

**Comment by KarlisJ** [comment]
@mgascam Thank you for pointing out the missing LinkIcon.

I've implemented all requested changes. Just need to resolve failing tests (in most cases recreating snapshot)

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7560` or branch name `fix/7183-unify-pm-icon-design` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7183-unify-pm-icon-design) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 86a81f17cc693ba27488490b1f2ecfc4b537bdd2
- Build time: 2023-10-27 13:15:32 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by dmvrtx — APPROVED** [review]
Everything looks good and consistent on the Settings and Transactions screens! Good work!

File: client/style.scss (hunk 5 above)
Comment (bradyv) [reply client/style.scss:175]: @mgascam Basically exactly what @KarlisJ  said. `outline` allows us to set a negative offset that draws the stroke on top of the icon. Using `border` required additional mockup that made it much more difficult to scale to different icon sizes.

Beyond just inconsistencies between assets this also gives us a much nicer display as the stroke is clearly visible for all icons regardless of icon colour or the background colour they're displayed on.

Comment (mgascam) [reply client/style.scss:175]: Thanks for clarification @bradyv @KarlisJ
