### PR TITLE
Pass parameters in query string for DELETE requests.

### LINKED ISSUE #2925: Cancelling subscriptions on WCPay Server return `wcpay_authorization_failure` error
### Describe the bug

On our JN test store (login details in SS, search "Little Buzzard"), cancelling the subscription in Woo doesn't cancel the Subscription on Stripes end. Other requests like updating the status to pending cancel and on-hold work perfectly fine, just cancelling doesn't.

I also can't reproduce this locally while running the local server, only on JN using the live server.

In the logs I see:

```
2021-09-16T02:02:05+00:00 INFO REQUEST DELETE https://public-api.wordpress.com/wpcom/v2/sites/%s/wcpay/subscriptions/sub_1Ja9uI2HBBsND3Su04qyYCp2
2021-09-16T02:02:06+00:00 ERROR Sorry, you cannot access this resource. (wcpay_authorization_failure)
2021-09-16T02:02:06+00:00 INFO There was a problem canceling the subscription on WCPay server: Error: Sorry, you cannot access this resource.
```

My current suspicion is that making DELETE requests to server is restricted or something. I noticed WCPay Client doesn't make any other DELETE requests to server apart from two new DELETE requests being added by WC Pay Subscriptions code (cancelling subscriptions and deleting invoice items).

Rather than making a delete request to cancel a subscription, I think we should send this to server as POST request and then have server handle cancelling the subscription using Stripe APIs.

### To Reproduce

1. Purchase a subscription in WooCommerce on the JN test store.
2. Confirm the subscription in Stripe dashboard is created
3. Cancel the subscription in Woo (set the status to Cancelled on the Edit Subscription page)
4. Note the Subscription isn't cancelled in WCPay

### Expected behavior

The subscription in Stripe is archived/deleted when cancelled in WooCommerce.

### PR DESCRIPTION
**Pull request by shendy-a8c**
Fixes #2925

#### Changes proposed in this Pull Request

- Make sure parameters is passed as query string for DELETE requests.
- Fix some indentitation.
- Introduce constant for PUT.

#### Testing instructions

- Purchase a subscription in WooCommerce on the JN store: p1631763567328100/1631758836.323500-slack-C02BW3Z8SHK.
- Confirm the subscription in Stripe dashboard is created.
- Cancel the subscription in Woo (set the status to Cancelled on the Edit Subscription page).
- Confirm the subscription in Stripe dashboard is cancelled (check Subscriptions > Cancelled tab).

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)
- [x] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

File: includes/wc-payment-api/class-wc-payments-api-client.php [hunk 1]
```diff
@@ -1391,7 +1392,7 @@ protected function request( $params, $api, $method, $is_site_specific = true, $u
 		$headers['User-Agent']   = $this->user_agent;
 
 		Logger::log( "REQUEST $method $url" );
-		if ( 'POST' === $method || 'PUT' === $method ) {
+		if ( in_array( $method, [ self::POST, self::PUT ], true ) ) {
```
Comment (shendy-a8c) [inline includes/wc-payment-api/class-wc-payments-api-client.php:1395]: Not related to the issue but might as well tidying up this code.

File: tests/unit/wc-payment-api/test-class-wc-payments-api-client.php [hunk 2]
```diff
@@ -188,46 +188,46 @@ public function test_create_setup_intent() {
...
+								'object' => 'setup_intent',
+							]
+						),
+						'response' => [
+							'code'    => 200,
+							'message' => 'OK',
+						],
+					]
+				)
+			);
```
Comment (shendy-a8c) [inline tests/unit/wc-payment-api/test-class-wc-payments-api-client.php:230]: This whole thing is just some indentation change.

File: tests/unit/wc-payment-api/test-class-wc-payments-api-client.php [hunk 3]
```diff
@@ -257,49 +257,49 @@ public function test_create_and_confirm_setup_intent_with_SEPA() {
...
+								'payment_method' => $payment_method_id,
+							]
+						),
+						'response' => [
+							'code'    => 200,
+							'message' => 'OK',
+						],
+					]
+				)
+			);
```
Comment (shendy-a8c) [inline tests/unit/wc-payment-api/test-class-wc-payments-api-client.php:302]: Just indentation change.

File: tests/unit/wc-payment-api/test-class-wc-payments-api-client.php [hunk 4]
```diff
@@ -1133,6 +1133,52 @@ public function data_get_intent_description() {
...
+	 *
+	 * @throws Exception - In the event of test failure.
+	 */
+	public function test_cancel_subscription() {
+		$this->mock_http_client
+			->expects( $this->once() )
+			->method( 'remote_request' )
+			->with(
+				[
+					'url'             => 'https://public-api.wordpress.com/wpcom/v2/sites/%s/wcpay/subscriptions/sub_test?test_mode=0',
```
Comment (shendy-a8c) [inline tests/unit/wc-payment-api/test-class-wc-payments-api-client.php:1147]: This test is to make sure `test_mode` parameter is passed as query string.

**Comment by shendy-a8c** [comment]
Thank you, @marcinbot!

File: includes/wc-payment-api/class-wc-payments-api-client.php (hunk 1 above)
Comment (marcinbot) [reply includes/wc-payment-api/class-wc-payments-api-client.php:1395]: Since this is for when the body is present in the request, we should probably calculate it in the same way as above, i.e. use `! in_array( $method, [ self::GET, self::DELETE ], true )`, or better yet, make it into a variable. Or check if `null !== $body`

File: tests/unit/wc-payment-api/test-class-wc-payments-api-client.php [hunk 5]
```diff
@@ -1133,6 +1133,52 @@ public function data_get_intent_description() {
...
+								'object' => 'subscription',
+							]
+						),
+					]
+				)
+			);
+
+		$result = $this->payments_api_client->cancel_subscription( 'sub_test' );
+		$this->assertEquals( 'sub_test', $result['id'] );
+		$this->assertEquals( 'subscription', $result['object'] );
```
Comment (aprea) [inline tests/unit/wc-payment-api/test-class-wc-payments-api-client.php:1179]: **Nitpick:**

```diff
-assertEquals
+assertSame
```

**Comment by aprea** [comment]
LGTM, works as expected with the provided testing instructions

**Review by aprea — APPROVED** [review]

File: tests/unit/wc-payment-api/test-class-wc-payments-api-client.php (hunk 5 above)
Comment (shendy-a8c) [reply tests/unit/wc-payment-api/test-class-wc-payments-api-client.php]: Addressed d43b1d0e46bb36fc4c3d498750ac1914b6e53b8e.

**Comment by shendy-a8c** [comment]
Thank you for the review, @aprea. I just push some commits around redacting parameters and addressing @marcinbot's [comment](https://github.com/Automattic/woocommerce-payments/pull/2942#discussion_r712114348). Please give another look.

**Comment by aprea** [comment]
With the assumption that your latest commits were deployed to the JN testing site I tested again on https://little-buzzard.jurassic.ninja and it still LGTM ✅
