### PR TITLE
Redirect to onboarding when account disconnected

### LINKED ISSUE #648: Manually opening a Payments page will result in a blank page if not connected to WCPay
**Steps to reproduce:**
- Start with a new site, or disconnect your site from WCPay/Stripe.
- Open this page: `http://<YOUR_SITE>/wp-admin/admin.php?page=wc-admin&path=/payments/deposits`

**What happened:** Blank page.

**What I expected:** I should have been redirected to the "Connect" splash screen.

There should be some client-side logic to redirect the merchant to the `/payments/connect` page if they somehow navigated to a WCPay Dashboard page without having WCPay set up.

I set this as "Priority: Low" because it's a very unlikely scenario.

### PR DESCRIPTION
**Pull request by aprea**
Fixes #648

#### Changes proposed in this Pull Request

Redirect to the onboarding page when the WooCommerce Payments account is disconnected.

| Before | After |
|-|-|
|Screen Shot 2021-06-21 at 10 16 28 am|Screen Shot 2021-06-21 at 10 17 03 am|

#### Testing instructions

* Start with a new site, or disconnect your site from WCPay/Stripe.
* Open this page: `http://<YOUR_SITE>/wp-admin/admin.php?page=wc-admin&path=/payments/deposits`
* Observe you are redirected to `/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect`

-------------------

- [x] Added changelog entry
- [x] Covered with tests
- [x] Tested on mobile

### CODE REVIEW

File: includes/admin/class-wc-payments-admin.php [hunk 1]
```diff
@@ -527,4 +531,52 @@ public function payment_gateways_container() {
...
+		if ( $this->account->is_stripe_connected() ) {
+			return true;
+		}
+
+		$page_paths = [];
+
+		foreach ( $this->admin_child_pages as $payments_child_page ) {
+			$page_paths[] = preg_quote( $payments_child_page['path'], '/' );
+		}
+
```
Comment (aprea) [inline includes/admin/class-wc-payments-admin.php:575]: FYI the below regex is:
```
/^(\/payments\/overview|\/payments\/deposits|\/payments\/transactions|\/payments\/disputes)/
```

File: includes/admin/class-wc-payments-admin.php [hunk 2]
```diff
@@ -70,6 +78,49 @@ public function add_payments_menu() {
 
 		$top_level_link = $should_render_full_menu ? '/payments/overview' : '/payments/connect';
 
+		$this->admin_child_pages = [
```
Comment (vbelolapotkov) [inline includes/admin/class-wc-payments-admin.php:81]: Moving configs to variable is great idea IMO. How about moving it to static const? I don't see it's ever reassigned or modified.

Comment (aprea) [reply includes/admin/class-wc-payments-admin.php:81]: I had the same thought but I don't think it's possible. This array calls the `__()` function a few times. If I attempt to make this definition a class constant I receive the following error:

>Fatal error: Constant expression contains invalid operations

As per the [PHP docs](https://www.php.net/manual/ro/language.oop5.static.php):

>Like any other PHP static variable, static properties may only be initialized using a literal or constant before PHP 5.6; expressions are not allowed. In PHP 5.6 and later, the same rules apply as const expressions: some limited expressions are possible, provided they can be evaluated at compile time.

I could potentially move this to the constructor though.

Comment (vbelolapotkov) [reply includes/admin/class-wc-payments-admin.php:81]: Oh, right! I didn't spot this, sorry.

> I could potentially move this to the constructor though.

🤔 I'm not sure how often the class instance is created: with each HTTP call, when any admin page is accessed or only for WC Pay admin page. Maybe setting it to empty array in constructor would be the best alternative to avoid reading from variable before it has value assigned.

**Review by shendy-a8c — CHANGES_REQUESTED** [review]
Overall looks good. I tested and it works.

My feedbacks:
- Combine `current_user_can_access_page()` into `maybe_redirect_to_onboarding()`.
- Because `maybe_redirect_to_onboarding()` hooks to `admin_menu` callback, we want to be very careful to only do something if page is requesting our plugin's menu, so I'm thinking there should be a `$is_wcpay_menu` and `$this->account->is_stripe_connected()` check.
- Checking `$is_wcpay_menu` (your awesome `preg_match()` approach) is cheaper compared to `is_stripe_connected()`, so it should come first.

What do you think?

File: tests/unit/admin/test-class-wc-payments-admin.php [hunk 3]
```diff
@@ -91,9 +96,7 @@ public function test_it_renders_payments_badge_if_stripe_is_not_connected() {
 		// The badge is temporarily not shown at all. See
 		// class-wc-payments-admin.php line 227. This should be removed when
 		// implementing https://github.com/automattic/woocommerce-payments/issues/2071.
-		if ( true === true ) {
-			return;
-		}
+		static::markTestSkipped( 'Not yet implemented.' );
```
Comment (aprea) [inline tests/unit/admin/test-class-wc-payments-admin.php:99]: Unrelated change. Previously, this test was showing as "risky" during test runs. This feels a little most explicit.

File: changelog.txt [hunk 4]
```diff
@@ -8,6 +8,7 @@
 * Fix - Use of deprecated call-style to registerPaymentMethods. WooCommerce Payments now requires WooCommerce Blocks of at least version 3.9.0.
 * Fix - Deposit date on Transactions list page.
 * Fix - Rounding error when displaying fee percentages on the Overview and Transactions pages.
+* Fix - WooCommerce Payments admin pages redirect to the onboarding page when the WooCommerce Payments account is disconnected.
```
Comment (shendy-a8c) [inline changelog.txt:11]: Even better!

**Review by shendy-a8c — APPROVED** [review]
LGTM.
