### PR TITLE
Only request WooPay session once on Blocks pages

### LINKED ISSUE #7357: Get WooPay Session is called multiple times on Blocks Cart and Checkout
### Describe the bug

When the `_wcpay_feature_woopay_first_party_auth` flag is enabled and a shopper visits a blocks checkout, the request to `wc-ajax=wcpay_get_woopay_session` is called up to 6 times. I believe this is because it is handled within a `useEffect` that is getting updated. I haven't determined this, but I'm thinking that `newIframe` is being updated when `listenForCartChanges` is updated.

### To Reproduce

1. Have the `_wcpay_feature_woopay_first_party_auth` feature flag enabled on a WooPay enabled merchant site.
2. Add a product to the cart.
3. Visit the blocks checkout page or the blocks cart page.
4. Monitor the Network tab in dev tools to see that the request is made multiple times instead of the expected once.

### Actual behavior

There are multiple requests to `wc-ajax=wcpay_get_woopay_session` when loading the blocks checkout page.

### Screenshots

Screenshot 2023-10-03 at 12 37 10 PM

### Expected behavior

This request should only be fired once from that page similar to what happens on the product, shortcode cart, and shortcode checkout pages.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by cesarcosta99**
Fixes #7357.

#### Changes proposed in this Pull Request

It changes the way the WooPay button is rendered in the Blocks cart and checkout pages. We're adopting a ReactDOM render approach instead of simply rendering the component to prevent the component re-rendering, that was how multiple requests were being made.

The new approach creates a raw HTML node, and a new root through ReactDOM, then the new root is rendered in the node a single time, and the request is made only once.

#### Testing instructions

1. Pull the latest changes on WooPay.
2. On branch `develop`, run `npm start` to build the assets and try to reproduce the steps described on #7357.
3. Switch to this branch and run `npm start` to rebuild the assets.
4. Add a product to the cart.
5. Visit both the Blocks checkout page and the Blocks cart page.
5.1. Monitor the Network tab in dev tools to confirm the request `wcpay_get_woopay_session` is made only once in each page.
7. Confirm the first party auth flow works as expected.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7393` or branch name `fix/7357-multiple-woopay-session-requests-on-blocks` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7357-multiple-woopay-session-requests-on-blocks) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 777dbe2da4038188e9db3cf80bee3fb717dd2a16
- Build time: 2023-10-05 21:54:34 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/checkout/woopay/express-button/woopay-express-checkout-payment-method.js [hunk 1]
```diff
@@ -1,3 +1,9 @@
+/**
+ * External dependencies
+ */
+import { useCallback } from 'react';
```
Comment (bborman22) [inline client/checkout/woopay/express-button/woopay-express-checkout-payment-method.js:4]: I was a little concerned about these imports, but I see there wasn't any file size or download size different on the front-end. Just wanted to confirm if there's any other performance aspect to be concerned with these?

File: client/checkout/woopay/express-button/woopay-express-checkout-payment-method.js [hunk 2]
```diff
@@ -18,15 +24,27 @@ const api = new WCPayAPI(
 	request
 );
 
+const WooPayExpressCheckoutButtonContainer = () => {
+	const onRefChange = useCallback( ( node ) => {
+		if ( node ) {
```
Comment (bborman22) [inline client/checkout/woopay/express-button/woopay-express-checkout-payment-method.js:29]: I wasn't able to get into a scenario where node was empty, I was wondering if there is a process that could trigger that just to confirm what happens when this condition is false?

**Review by bborman22 — APPROVED** [review]
This tested really well for me! I was able to confirm that not only did it limit the get woopay session calls to one, it logically also only loaded the connect iframe from WooPay once as well. This is a huge win for performance / wasted requests! I also confirmed that the first party flow worked for all pages and I was able to complete checkout in each case.

I left two small questions around the updates, but neither one is blocking just wanted to get a better understanding of how this code might fail. 

LGTM!

File: client/checkout/woopay/express-button/woopay-express-checkout-payment-method.js (hunk 1 above)
Comment (cesarcosta99) [reply client/checkout/woopay/express-button/woopay-express-checkout-payment-method.js:4]: Nope. Since they're React stuff, they're already included in the bundle so no concerns on that aspect.

File: client/checkout/woopay/express-button/woopay-express-checkout-payment-method.js (hunk 2 above)
Comment (cesarcosta99) [reply client/checkout/woopay/express-button/woopay-express-checkout-payment-method.js:29]: When that condition is `false`, the WooPay button isn't rendered. For this scenario to happen there must be something really wrong happening with React, so I'd say it's nearly impossible. We could totally remove the `if`, however, there's no performance implication and I think we can afford having this check to walk on the safe side.

Comment (bborman22) [reply client/checkout/woopay/express-button/woopay-express-checkout-payment-method.js:29]: > For this scenario to happen there must be something really wrong happening with React

Awesome, in that case no concern from my side and having the check is definitely worth it, just wanted to make sure I wasn't missing an obvious edge case to test while reviewing thanks!
