### PR TITLE
Cancel non-captured authorizations if order is cancelled.

### LINKED ISSUE #5605: Able to capture cancelled order from Transactions > Uncaptured page
### Describe the bug
The listing at Payments > Transactions > Uncaptured shows a listing of orders that have had authorizations done, but they have not been captured. This page does not show the status of the order, so if an order is in Cancelled status, the authorization could be captured here accidentally.

### To Reproduce

1. Enable _Issue an authorization on checkout, and capture later_ under Payments > Settings and then the Transactions section.
2. Place an order in the store.
3. Go to the order in the admin and set it to Cancelled status.
4. Go to Payments > Transactions > Uncaptured.
5. The order will be listed there and you will be able to _Capture_ the payment for it.

### Additional notes

It is possible to go to the order itself and capture the payment through the order actions, as well. This was mentioned in https://github.com/Automattic/woocommerce-payments/issues/173

### PR DESCRIPTION
**Pull request by dmvrtx**
Fixes #5605

#### Changes proposed in this Pull Request

Cancel non-captured authorizations if order is cancelled.

When WooPayments plugin is running in "Issue an authorization on checkout, and capture later" mode, it creates an authorization when order is placed. Such authorization can later be captured from order screen or transactions screen.

However, when order is cancelled in WooCommerce, such authorizations remained, and could lead to a confusion, e.g. being shown as "Uncaptured" in the transactions screen.

Since there is no money transferred from the shopper to the merchant at this moment, we can fully cancel such authorizations when order is cancelled and remove any potential confusion.

Captured authorizations are not subject of this change, since in this case it is up to the merchant to decide how those should be refunded.

In line with #5712 when merchant tries to cancel an order with uncaptured authorization, a modal will appear, asking for confirmation.

**Before: modal confirmation**

_This modal still remains in use for paid orders which can be refunded._

Before: Modal confirmation

**Before: cancelled order**

Before: Cancelled order

**Before: transactions screen**

Before: Transactions screen

**Before: transaction details**

Transaction details

**After: modal confirmation**

_Missing border line is a compression artifact_ 🤷‍♂️ 

After: Modal confirmation

**After: cancelled order**

After: cancelled order

**After: transactions screen**

After: Transactions screen

#### Testing instructions

 * Enable _"Issue an authorization on checkout, and capture later"_ in the _Payments_ -> _Settings_ -> _Transactions_ section.
 * Create an order and checkout.
   * Authorization should be indicated in order notes and appear on the _Payments_ -> _Transactions_ screen.
 * Cancel an order.
   * Order notes should indicate cancelled authorization.
   * Authorization shouldn't appear on the _Payments_ -> _Transactions_ screen.

 * Disable _"Issue an authorization on checkout, and capture later"_
 * Create an order and checkout.
   * Successful transaction should appear in the _Payments_ -> _Transactions_ screen.
 * Cancel an order
   * Successful transaction should remain in the _Payments_ -> _Transactions_ screen.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7743` or branch name `add/5605-cancel-authorizations-if-order-is-cancelled` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/5605-cancel-authorizations-if-order-is-cancelled) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: f5cede5b512d82e437fe2ac047ad17109b559bec
- Build time: 2023-12-19 11:44:45 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -2911,6 +2912,34 @@ public function cancel_authorization( $order ) {
...
+	public function cancel_authorizations_on_order_cancel( $order_id ) {
+		$order = new WC_Order( $order_id );
+		if ( null !== $order ) {
+			$intent_id = $this->order_service->get_intent_id_for_order( $order );
+			if ( null !== $intent_id ) {
+				$request = Get_Intention::create( $intent_id );
+				$request->set_hook_args( $order );
+				$intent = $request->send();
+
+				$charge = $intent->get_charge();
```
Comment (kalessil) [inline includes/class-wc-payment-gateway-wcpay.php]: To simplify a bit: `$charge = $request->send()->get_charge()`.

File: includes/class-wc-payment-gateway-wcpay.php [hunk 2]
```diff
@@ -2911,6 +2912,34 @@ public function cancel_authorization( $order ) {
 		];
 	}
 
+	/**
+	 * Cancels uncaptured authorizations on order cancel.
+	 *
+	 * @param int $order_id - Order ID.
+	 */
+	public function cancel_authorizations_on_order_cancel( $order_id ) {
```
Comment (kalessil) [inline includes/class-wc-payment-gateway-wcpay.php:2881]: Fo the sake of resilence, can we add errors handling in order to let the order status change rolling (authorization will expire eventually). Don't think we need any logging or order notes.

**Review by kalessil — COMMENTED** [review]
Leaving a couple of comments, to look into for ths approach.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 1 above)
Comment (dmvrtx) [reply includes/class-wc-payment-gateway-wcpay.php]: With the follow-up updates to ensure order always contains latest intent status, this `$intent` variable is used later to update intent status, even if cancellation is not performed.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 2 above)
Comment (dmvrtx) [reply includes/class-wc-payment-gateway-wcpay.php:2881]: Included in the follow-up update, along with an order note if failure happens.

File: includes/class-wc-payment-gateway-wcpay.php [hunk 3]
```diff
@@ -2911,6 +2912,52 @@ public function cancel_authorization( $order ) {
...
+					if ( null !== $charge
+						&& false === $charge->is_captured()
+						&& Intent_Status::SUCCEEDED === $charge->get_status()
+						&& Intent_Status::REQUIRES_CAPTURE === $intent->get_status()
+					) {
+							$request = Cancel_Intention::create( $intent_id );
+							$request->set_hook_args( $order );
+							$intent = $request->send();
+
+							$this->order_service->update_order_status_from_intent( $order, $intent );
```
Comment (kalessil) [inline includes/class-wc-payment-gateway-wcpay.php]: IMO, This update is unnecessary - it does too much, incl. order status updates in some scenarios. Such circular logic can break at any time.

We should keep `$this->order_service->set_intention_status_for_order( $order, $intent->get_status() );` though - webhooks will arrive much later.

File: includes/class-wc-payment-gateway-wcpay.php [hunk 4]
```diff
@@ -2911,6 +2912,52 @@ public function cancel_authorization( $order ) {
...
+					}
+
+					$this->order_service->set_intention_status_for_order( $order, $intent->get_status() );
+					$order->save();
+				} catch ( \Exception $e ) {
+					$order->add_order_note(
+						WC_Payments_Utils::esc_interpolated_html(
```
Comment (kalessil) [inline includes/class-wc-payment-gateway-wcpay.php:2912]: Oh, that's nice. Since auto-cancelling is not a standard thing, should we add a note not on success as well - for observability?

Comment (dmvrtx) [reply includes/class-wc-payment-gateway-wcpay.php:2912]: That's why I want to use `update_order_status_from_intent` above: it creates a cancellation note. The problem is it is tied with the order status logic and extracting it requires more refactoring than is warranted for this change 😅

Comment (kalessil) [reply includes/class-wc-payment-gateway-wcpay.php:2912]: Okay, test coverage on client is around 62%, which is a bit less than needed for confident refactoring. I could leave without the order note on success.

Marking this conversation branch as resolved.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 3 above)
Comment (kalessil) [reply includes/class-wc-payment-gateway-wcpay.php]: Surfacing from another conversation branch in this PR: Having order note on success is not that important compared to the mentioned risk.

File: tests/unit/test-class-wc-payment-gateway-wcpay.php [hunk 5]
```diff
@@ -944,6 +944,97 @@ public function test_capture_charge_without_level3() {
...
+			->willReturn( $mock_intent );
+
+		$this->mock_wcpay_request( Cancel_Intention::class, 0, $intent_id );
+
+		$order->set_status( 'cancelled' );
+		$order->save();
+
+		$order = wc_get_order( $order->get_id() );
+
+		$this->assertEquals( Intent_Status::SUCCEEDED, $order->get_meta( '_intention_status', true ) );
```
Comment (kalessil) [inline tests/unit/test-class-wc-payment-gateway-wcpay.php]: Strict assertions, please.

File: tests/unit/test-class-wc-payment-gateway-wcpay.php [hunk 6]
```diff
@@ -944,6 +944,97 @@ public function test_capture_charge_without_level3() {
...
+		);
+
+		$get_intent_request = $this->mock_wcpay_request( Get_Intention::class, 1, $intent_id );
+		$get_intent_request->expects( $this->once() )
+			->method( 'format_response' )
+			->willReturn( $mock_intent );
+
+		$this->mock_wcpay_request( Cancel_Intention::class, 0, $intent_id );
+
+		$order->set_status( 'cancelled' );
```
Comment (kalessil) [inline tests/unit/test-class-wc-payment-gateway-wcpay.php]: `Order_Status::CANCELLED`?

File: tests/unit/test-class-wc-payment-gateway-wcpay.php [hunk 7]
```diff
@@ -944,6 +944,97 @@ public function test_capture_charge_without_level3() {
...
+		$cancel_intent_request->expects( $this->once() )
+			->method( 'format_response' )
+			->willReturn( $mock_canceled_intent );
+
+		$order->set_status( 'cancelled' );
+		$order->save();
+
+		$order = wc_get_order( $order->get_id() );
+
+		$this->assertEquals( Intent_Status::CANCELED, $order->get_meta( '_intention_status', true ) );
```
Comment (kalessil) [inline tests/unit/test-class-wc-payment-gateway-wcpay.php]: Strict assertions, please.

File: tests/unit/test-class-wc-payment-gateway-wcpay.php [hunk 8]
```diff
@@ -944,6 +944,97 @@ public function test_capture_charge_without_level3() {
...
+		$get_intent_request->expects( $this->once() )
+			->method( 'format_response' )
+			->willReturn( $mock_intent );
+
+		$cancel_intent_request = $this->mock_wcpay_request( Cancel_Intention::class, 1, $intent_id );
+		$cancel_intent_request->expects( $this->once() )
+			->method( 'format_response' )
+			->willReturn( $mock_canceled_intent );
+
+		$order->set_status( 'cancelled' );
```
Comment (kalessil) [inline tests/unit/test-class-wc-payment-gateway-wcpay.php]: `Order_Status::CANCELLED`?

File: tests/unit/test-class-wc-payment-gateway-wcpay.php [hunk 9]
```diff
@@ -944,6 +944,97 @@ public function test_capture_charge_without_level3() {
...
+	public function test_capture_cancelling_order_cancels_authorization() {
+		$intent_id = uniqid( 'pi_' );
+		$charge_id = uniqid( 'ch_' );
+
+		$order = WC_Helper_Order::create_order();
+		$order->set_transaction_id( $intent_id );
+		$order->update_meta_data( '_intent_id', $intent_id );
+		$order->update_meta_data( '_charge_id', $charge_id );
+		$order->update_meta_data( '_intention_status', Intent_Status::REQUIRES_CAPTURE );
+		$order->update_status( Order_Status::ON_HOLD );
```
Comment (kalessil) [inline tests/unit/test-class-wc-payment-gateway-wcpay.php:959]: Hm, are we sure about this status in this test case?

File: includes/class-wc-payment-gateway-wcpay.php (hunk 3 above)
Comment (dmvrtx) [reply includes/class-wc-payment-gateway-wcpay.php]: I think it'd be prudent to have a note to indicate the change. Otherwise we will have it if authorisation is cancelled manually, but not if automatically. I'll look into extracting note creation into public methods in Order Service.

File: tests/unit/test-class-wc-payment-gateway-wcpay.php (hunk 9 above)
Comment (dmvrtx) [reply tests/unit/test-class-wc-payment-gateway-wcpay.php:959]: That's the usual order status if payment hasn't been captured yet.

File: tests/unit/test-class-wc-payment-gateway-wcpay.php (hunk 7 above)
Comment (dmvrtx) [reply tests/unit/test-class-wc-payment-gateway-wcpay.php]: Done in 2a37196b4

File: tests/unit/test-class-wc-payment-gateway-wcpay.php (hunk 5 above)
Comment (dmvrtx) [reply tests/unit/test-class-wc-payment-gateway-wcpay.php]: Done in 2a37196b4

File: includes/class-wc-payment-gateway-wcpay.php (hunk 3 above)
Comment (dmvrtx) [reply includes/class-wc-payment-gateway-wcpay.php]: I've extracted the note creation into a separate method. It required only a small update to the tests to accommodate changed order of the notes.

**Review by kalessil — APPROVED** [review]
LGTM (code review only)!

File: includes/class-wc-payments-order-service.php [hunk 10]
```diff
@@ -806,6 +806,21 @@ public function get_billing_data_from_order( WC_Order $order ): array {
 		];
 	}
 
+	/**
+	 * Creates an "authorization cancelled" order not if not already present.
```
Comment (mgascam) [inline includes/class-wc-payments-order-service.php]:
```suggestion
	 * Creates an "authorization cancelled" order note if not already present.
```

**Review by mgascam — APPROVED** [review]
LGTM! Tested following instructions and work as intended. 

Noticed a small typo you might want to address.

**Review by KarlisJ — APPROVED** [review]
LGTM, tests well

**Comment by dmvrtx** [comment]
@elizaan36, @mgascam raised a valid point that for both modals, already existing one and newly introduced, merchant still has to click "Update" button on the order page, even after clicking "Cancel order" or "Cancel order and authorization" buttons.

While it allows merchant to review the changes before finalising them and is consistent with how changes to other order statuses are done, it can lead to a misunderstanding of the flow. I think of two possible ways of addressing it: either change wording on "Cancel order..." buttons (preferred by me) or automatically submit a cancellation. What do you think?

**Comment by elizaan36** [comment]
> automatically submit a cancellation

This was actually my assumption!  I would expect the modal to submit the cancellation since the action "Cancel order" / "Cancel order and authorization" implies that.

File: client/order/cancel-authorization-confirm-modal/index.js [hunk 11]
```diff
@@ -0,0 +1,109 @@
...
+import { __ } from '@wordpress/i18n';
+import { Button } from '@wordpress/components';
+import interpolateComponents from '@automattic/interpolate-components';
+import { useState } from '@wordpress/element';
+/**
+ * Internal dependencies
+ */
+import ConfirmationModal from 'wcpay/components/confirmation-modal';
+
+const CancelAuthorizationConfirmationModal = ( { originalOrderStatus } ) => {
```
Comment (kalessil) [inline client/order/cancel-authorization-confirm-modal/index.js]: Can we use TypeScript here, please?

File: client/order/index.js [hunk 12]
```diff
@@ -108,6 +110,20 @@ jQuery( function ( $ ) {
...
+				renderModal(
+					<CancelAuthorizationConfirmationModal
+						originalOrderStatus={ originalStatus }
+					/>
+				);
+				return;
+			}
+			// If it is possible to refund an order, double check that
+			// merchants indeed wants to cancel, or if they just want to
+			// refund.
```
Comment (kalessil) [inline client/order/index.js:126]: ❤️ the comments. Not related to your change, but it make sense to keep consistency and refactor conditional for the confirmation:

```
if ( canRefund && refundAmount > 0) {
renderModal(
		<CancelConfirmationModal
			originalOrderStatus={ originalStatus }
		/>
);
}
```

File: client/order/cancel-authorization-confirm-modal/index.js (hunk 11 above)
Comment (dmvrtx) [reply client/order/cancel-authorization-confirm-modal/index.js]: Done in f834ba284

File: client/order/index.js (hunk 12 above)
Comment (dmvrtx) [reply client/order/index.js:126]: Done in 087c3ceac

**Comment by kalessil** [comment]
Thanks for the updates @dmvrtx! Will do the final testing/review round tomorrow.

**Comment by dmvrtx** [comment]
@kalessil, I've added a naïve implementation of submitting an order cancellation through the modal in 8cd053e46. I'd love to have it go through an API but my extensive search only lead me to the options which would require substantial changes in the code.

File: client/order/cancel-authorization-confirm-modal/index.tsx [hunk 13]
```diff
@@ -0,0 +1,134 @@
...
+		handleCancelOrder();
+		closeModal();
+	};
+
+	const buttonContent = (
+		<>
+			<Button isSecondary onClick={ doNotCancel }>
+				{ __( 'Do Nothing', 'woocommerce-payments' ) }
+			</Button>
+			<Button isPrimary onClick={ cancelOrder }>
```
Comment (mgascam) [inline client/order/cancel-authorization-confirm-modal/index.tsx:61]: An alternative approach could be to craft an href to cancel the order, in a similar way how the order actions in the preview list work. To be on the safe side, we could build the url in PHP side and expose to the JS through the usual global. Here we'd have the following code:

```suggestion
			<Button isPrimary href={ wcpay_order_config.cancelOrderUrl }>
```
Note that we would get rid of the `cancelOrder` function.

File: includes/admin/class-wc-payments-admin.php [hunk 14]
```diff
@@ -734,6 +734,7 @@ public function enqueue_payments_scripts() {
 						'refundedAmount'        => $order->get_total_refunded(),
 						'canRefund'             => $this->wcpay_gateway->can_refund_order( $order ),
 						'chargeId'              => $this->order_service->get_charge_id_for_order( $order ),
+						'hasOpenAuthorization'  => $this->order_service->has_open_authorization( $order ),
```
Comment (mgascam) [inline includes/admin/class-wc-payments-admin.php:737]: To follow the proposed approach we'd need to  build the url to cancel the order here, something like:
```suggestion
						'hasOpenAuthorization'  => $this->order_service->has_open_authorization( $order ),
						'cancelOrderUrl'        => wp_nonce_url( admin_url( 'admin-ajax.php?action=woocommerce_mark_order_status&status=cancelled&order_id=' . $order->get_id() ), 'woocommerce-mark-order-status' ),
						
```

**Review by mgascam — COMMENTED** [review]
Thanks for addressing the submission of the form @dmvrtx. I had a look to the available options looking for alternatives and was only able to find the following. Given that there's a [mark_order_status](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-ajax.php#L564C46-L564C46) AJAX action available I thought it could be a reasonable alternative to fire a GET request, as this method expects, when the button in the modal is clicked. 
The creation of the link would be in the PHP to create the appropiate nonce, and exposed to the JS via config object in window. The `mark_order_status` also checks if the user has enough privileges to cancel the order, but it's true that if the html is edited, an arbitrary order  could be cancelled, given it exists.

File: client/order/cancel-authorization-confirm-modal/index.tsx (hunk 13 above)
Comment (kalessil) [reply client/order/cancel-authorization-confirm-modal/index.tsx:61]: It's a bit complicated, I think the current approach is better. I'm checking how to make it more reliable, will post a new comment soon.

File: client/order/cancel-authorization-confirm-modal/index.tsx [hunk 15]
```diff
@@ -0,0 +1,134 @@
...
+		isCancelAuthorizationConfirmationModalOpen,
+		setIsCancelAuthorizationConfirmationModalOpen,
+	] = useState( true );
+
+	const closeModal = (): void => {
+		setIsCancelAuthorizationConfirmationModalOpen( false );
+	};
+
+	const handleCancelOrder = (): void => {
+		const orderEditForm: HTMLFormElement | null = document.querySelector(
```
Comment (kalessil) [inline client/order/cancel-authorization-confirm-modal/index.tsx]: A bit more cryptic, but clearer connection to the status field: `document.querySelector( '#order_status' )?.closest( 'form' ) || null;`.

My thinking is if the select ID changes, it'll be easier to find usage. Also, we reinforce our logic towards changes in the form ID/structure.

**Review by kalessil — CHANGES_REQUESTED** [review]

File: includes/admin/class-wc-payments-admin.php (hunk 14 above)
Comment (dmvrtx) [reply includes/admin/class-wc-payments-admin.php:737]: Thank you for investigating the alternatives @mgascam, a good learning for me 😀

File: client/order/cancel-authorization-confirm-modal/index.tsx (hunk 15 above)
Comment (dmvrtx) [reply client/order/cancel-authorization-confirm-modal/index.tsx]: Addressed in e8ff054c6

**Review by kalessil — APPROVED** [review]
Works like a charm! I know it's not the most critical feature, but it's a fantastic quality of live improvement - many thanks for implementing it!

File: tests/unit/helpers/class-wc-helper-intention.php [hunk 16]
```diff
@@ -34,25 +34,60 @@ public static function create_charge( $data = [] ) {
 						'funding' => 'credit',
 					],
 				],
+				'payment_method'         => 'pm_mock',
+				'amount_captured'        => 5000,
+				'amount_refunded'        => 0,
+				'application_fee_amount' => 0,
+				'balance_transaction'    => 'txn_mock',
```
Comment (anu-rock) [inline tests/unit/helpers/class-wc-helper-intention.php:41]: @dmvrtx Stripe typically supplies a [balance_transaction](https://stripe.com/docs/api/balance_transactions/object) object attached to this property rather than directly its ID. I'm curious if you set it to txn_xxx id here on purpose.

**Context:** In [trying to access](https://github.com/Automattic/woocommerce-payments/blob/fbc8664dfb36ab954c5961dea6941868716ffe18/includes/class-wc-payments-order-service.php#L791) the balance transaction id, my PR is [failing](https://github.com/Automattic/woocommerce-payments/actions/runs/7338045342/job/19979943150?pr=7945) 25 tests 😕 However, manual testing confirms that my code works with actual payments.

Comment (anu-rock) [reply tests/unit/helpers/class-wc-helper-intention.php:41]: I just pushed this change in my PR. Hope you're okay with it.

https://github.com/Automattic/woocommerce-payments/pull/7945/commits/83d5af89335bd77c2cdcb9fa58d3418c21d998e7

Comment (dmvrtx) [reply tests/unit/helpers/class-wc-helper-intention.php:41]: Stripe documentation indicates that it is a transaction ID e.g. [for a Charge object](https://stripe.com/docs/api/charges/object#charge_object-balance_transaction)

I think failing tests are based on assumption that request to Stripe is sent with an [`expand` setting](https://stripe.com/docs/api/expanding_objects) for the `balance_transaction`. In this case it is indeed returned as an object. Such nuance is not handled well by the testing framework though.

Comment (anu-rock) [reply tests/unit/helpers/class-wc-helper-intention.php:41]: TIL about the `expand` setting.
