### PR TITLE
Remove total from active dispute task title when from multiple currencies

### LINKED ISSUE #6613: Refine wording of the Active Disputes task: remove total when disputes are from multiple currencies to improve clarity
### Describe the bug

The Active Disputes task uses the wording `Respond to 5 active disputes for a total of $123, €123, £123` when multiple disputes from **multiple currencies** are awaiting a response. This wording is confusing when dealing with multiple currencies and should be improved by removing the total and including the count only:

`Respond to 5 active disputes`

Multiple disputes from a **single currency** will still read: `Respond to 5 active disputes for a total of $123`.

This wording applies to the task on both the Payments → Overview screen and WC → Home screen.

### To Reproduce

1. Ensure you have 2+ disputed orders in 2+ currencies due within 7 days.
2. Go to Payments → Overview to view the active disputes task.
3. The wording will show "Respond to %d active disputes for a total of %s"
4. Observe the same wording within the WC → Home active disputes task.

### Actual behavior

The Active Disputes task on the Payments → Overview screen and WC → Home screen uses the wording `Respond to %d active disputes for a total of %s` when multiple disputes with multiple currencies are awaiting a response.

### Screenshots

Image

### Expected behavior

The Active Disputes task on the Payments → Overview screen and WC → Home screen should use the wording `Respond to %d active disputes` when multiple disputes from **multiple currencies** are awaiting a response. Multiple disputes from a **single currency** will still read: `Respond to 5 active disputes for a total of $123`.

### Additional context

p1687998571298839-slack-C03LA109BKM

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #6613

#### Changes proposed in this Pull Request

This PR removes the calculated total amounts from the active dispute task title when disputes are for multiple currencies. This simplifies the readability of the title.

#### WC Home

**Before**
Screenshot 2023-07-11 at 10 56 00

**After** (ignore mouse-hover grey colouring)
Screenshot 2023-07-11 at 10 48 40

#### Payments Overview

**Before**

baaa7426591246174520e61d98635774

**After**

4c0675d480b7807ff543613a02a096f9

#### Testing instructions

* Using a multi-currency WCPay store, create disputed transactions across multiple currencies. These should be due within 7 days to view the active dispute task. 

**Mocking disputes**

**Payments Overview:** Add the following in `client/overview/index.js`, replacing `const { disputes: activeDisputes } =`, modifying `due_by` if necessary:

```js
const activeDisputes = [
	{
		wcpay_disputes_cache_id: 1,
		stripe_account_id: 'stripe_account_id_1',
		dispute_id: 'dispute_id_1',
		charge_id: 'charge_id_1',
		amount: 100,
		currency: 'USD',
		reason: 'DisputeReason',
		source: 'source_1',
		order_number: 123456,
		order: null,
		customer_name: 'John Doe',
		customer_email: 'john.doe@example.com',
		customer_country: 'USA',
		status: 'DisputeStatus',
		created: '2023-07-01',
		due_by: '2023-07-15',
	},
	{
		wcpay_disputes_cache_id: 2,
		stripe_account_id: 'stripe_account_id_2',
		dispute_id: 'dispute_id_2',
		charge_id: 'charge_id_2',
		amount: 200,
		currency: 'EUR',
		reason: 'DisputeReason',
		source: 'source_2',
		order_number: 654321,
		order: null,
		customer_name: 'Jane Smith',
		customer_email: 'jane.smith@example.com',
		customer_country: 'UK',
		status: 'DisputeStatus',
		created: '2023-07-02',
		due_by: '2023-07-16',
	},
	{
		wcpay_disputes_cache_id: 3,
		stripe_account_id: 'stripe_account_id_3',
		dispute_id: 'dispute_id_3',
		charge_id: 'charge_id_3',
		amount: 300,
		currency: 'JPY',
		reason: 'DisputeReason',
		source: 'source_3',
		order_number: 987654,
		order: null,
		customer_name: 'David Lee',
		customer_email: 'david.lee@example.com',
		customer_country: 'Japan',
		status: 'DisputeStatus',
		created: '2023-07-03',
		due_by: '2023-07-17',
	},
];
```

**WC Home**: return the following in the function `get_disputes_needing_response()` from `includes/admin/tasks/class-wc-payments-task-disputes.php`:

```php
// mock disputes with multiple currencies.
return [
	[
		'dispute_id' => 'dp_123',
		'amount'     => 10000,
		'currency'   => 'USD',
		'due_by'     => ( new \DateTime( 'now', new \DateTimeZone( 'UTC' ) ) )->modify( '+1 day' )->format( 'Y-m-d H:i:s' ),
	],
	[
		'dispute_id' => 'dp_456',
		'amount'     => 10000,
		'currency'   => 'EUR',
		'due_by'     => ( new \DateTime( 'now', new \DateTimeZone( 'UTC' ) ) )->modify( '+2 day' )->format( 'Y-m-d H:i:s' ),
	],
	[
		'dispute_id' => 'dp_789',
		'amount'     => '',
		'currency'   => 'USD',
		'due_by'     => ( new \DateTime( 'now', new \DateTimeZone( 'UTC' ) ) )->modify( '+3 day' )->format( 'Y-m-d H:i:s' ),
	],
];
```

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6642` or branch name `fix/6613-active-dispute-task-wording-multicurrency` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6613-active-dispute-task-wording-multicurrency) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 60844badc57ea2f37fb91a559efaf1ff74b8cb26
- Build time: 2023-07-12 23:16:32 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/admin/tasks/class-wc-payments-task-disputes.php [hunk 1]
```diff
@@ -106,27 +106,36 @@ public function get_title() {
...
 		}
 
-		$currencies_map = [];
-		foreach ( $active_disputes as $dispute ) {
-			if ( ! isset( $currencies_map[ $dispute['currency'] ] ) ) {
-				$currencies_map[ $dispute['currency'] ] = 0;
-			}
-			$currencies_map[ $dispute['currency'] ] += $dispute['amount'];
-		}
+		$dispute_currencies = array_unique( array_column( $active_disputes, 'currency' ) );
```
Comment (shendy-a8c) [inline includes/admin/tasks/class-wc-payments-task-disputes.php:109]: `nit`: since you will use the numeric index, ie `$dispute_currencies[0]`, later on, it's safer to wrap `array_unique()` (which will not maintain index) with [array_values()](https://www.php.net/manual/en/function.array-values.php).

Without it, it'd be OK too because you're just getting the first element. It'd be a problem if we try to get 2nd element etc.

**Review by shendy-a8c — APPROVED** [review]
Looks good and tested well. I have minor feedback. Approving as it's good to merge as is anyway.

File: includes/admin/tasks/class-wc-payments-task-disputes.php (hunk 1 above)
Comment (Jinksi) [reply includes/admin/tasks/class-wc-payments-task-disputes.php:109]: TIL! Thanks.

In this case, I assume it is OK, since we're accessing `$dispute_currencies[0]` only if `count( $dispute_currencies ) === 1`.

Comment (shendy-a8c) [reply includes/admin/tasks/class-wc-payments-task-disputes.php:109]: Ah, right!
