### PR TITLE
Fix including of a renamed exception file

### LINKED ISSUE #967: Include error with WP_DEBUG
To reproduce:
* Have WP_DEBUG set to true in wp-config
* Open any of the wcpay admin pages
* `Warning: include_once(redacted/woocommerce-payments/includes/exceptions/class-wc-payments-rest-request-exception.php): failed to open stream: No such file or directory in redacted/woocommerce-payments/includes/class-wc-payments.php on line 443`

cc @kalessil

### PR DESCRIPTION
**Pull request by marcinbot**
Fixes #967

#### Changes proposed in this Pull Request

* Updated the included path
* Tried searching for any other missed paths with `wc-payments.*exception`, couldn't find any
* Updated the `docker-setup` to make sure WP_DEBUG is enabled together with other debug options 

#### Testing instructions

* Make sure your wp-config.php contains the following lines:
```
define( 'WP_DEBUG', true);
define( 'WP_DEBUG_DISPLAY', true );
define( 'WP_DEBUG_LOG', true );
define( 'SCRIPT_DEBUG', true );
```
* Load any wcpay admin page (transactions, deposits etc)
* No notices should be displayed

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

File: bin/docker-setup.sh [hunk 1]
```diff
@@ -73,6 +73,12 @@ cli config set DOCKER_REQUEST_URL "( ! empty( \$_SERVER['HTTPS'] ) ? 'https://'
 cli config set WP_SITEURL DOCKER_REQUEST_URL --raw
 cli config set WP_HOME DOCKER_REQUEST_URL --raw
 
+echo "Enabling WP_DEBUG"
```
Comment (kalessil) [inline bin/docker-setup.sh:76]: Slightly misleading, as we enable more flags there. What about "Enabling WordPress debug-flags"?

**Review by kalessil — APPROVED** [review]

File: bin/docker-setup.sh (hunk 1 above)
Comment (marcinbot) [reply bin/docker-setup.sh]: Good point, changed in b34fa33. Will merge once the tests finish
