### PR TITLE
Fix legacy currency switcher removing url params

### LINKED ISSUE #2151: If currency is updated via widget on `order-pay` page it causes an error
If an order is created manually or fails for any reason, the store customer can access the order through My Account > Orders and pay from there. This page is different from the checkout page and has parameters in the url in order to display the page. When the widget is used, it clears out those parameters, so the order gets broken.

This likely happens with other instances where there are already parameters in the url that need to be there, as well.

Steps to replicate:

1. Add item to cart and proceed to checkout.
2. Use 4000000000000002 with any future expiration and cvv.
3. After order fails, go to My Account > Orders, and click to pay the order.
4. Change the currency via the widget, and the error will show.

Screen Capture on 2021-06-11 at 12-54-48

### PR DESCRIPTION
**Pull request by ismaeldcom**
Fixes #2151 

#### Changes proposed in this Pull Request
We need to preserve the url params after selecting a new currency in the legacy widget. I opted to just output hidden inputs from $_GET except `currency` to keep them. The only alternative I considered was to use JS to redirect, checking if there are any params before adding/replacing currency. But I think this is a simpler solution without need for any additional JS code.

#### Testing instructions
You can test this following the **Steps to replicate** from #2151 or just adding any param to the url and then changing the currency with the widget. In both cases the params should be preserved.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Review by dmallory42 — CHANGES_REQUESTED** [review]
LGTM and works well with a normal query string, however I noticed it throws an error when array params are used in the query string, for example, this would be a valid query string which would cause an error to get thrown:

`http://localhost:8082/?test[]=1&test[]=2`

Screenshot 2021-06-14 at 16 08 22

I'm not sure the best way to solve this, maybe just checking if `$value` is an array in the loop and if it is, looping over it and creating multiple hidden inputs for it would be enough?

**Comment by ismaeldcom** [comment]
Thanks @dmallory42 for noticing that! I forgot to test it with array params. I thought of using recursion to add support for params with multiple arrays. But ended using `http_build_query` and string manipulation for a simpler solution. What do you think? Check 383e2c6

**Comment by dmallory42** [comment]
I think that looks like a neat solution to me, clever to use `http_build_query` for it! 

I added one comment to the test but apart from that looks good to go to me! 🎉

File: tests/unit/multi-currency/test-class-currency-switcher-widget.php [hunk 1]
```diff
@@ -85,6 +85,16 @@ public function test_widget_renders_enabled_currencies_with_symbol_and_flag() {
 		$this->expectOutputRegex( '/<option value="EUR">🇪🇺 &euro; EUR<\/option>/' );
 	}
 
+	public function test_widget_renders_hidden_input() {
+		$_GET = [
+			'test_name'  => 'test_value',
+			'test_array' => [ 0 => [ 0 => 'test_array_value' ] ],
```
Comment (dmallory42) [inline tests/unit/multi-currency/test-class-currency-switcher-widget.php:91]: Does `$_GET` support named array keys, do you know? Just wondering if we should add a test for cases like `[  'val1' => 123, 'val2' => 234 ]`.

**Review by dmallory42 — APPROVED** [review]

File: tests/unit/multi-currency/test-class-currency-switcher-widget.php (hunk 1 above)
Comment (ismaeldcom) [reply tests/unit/multi-currency/test-class-currency-switcher-widget.php:91]: 🤔 Not sure if understand you correctly here. Do you mean something like e91ab56? Is that the case. Yes, we can use named keys in `$_GET` also.

Comment (dmallory42) [reply tests/unit/multi-currency/test-class-currency-switcher-widget.php:91]: Yup, that's exactly what I meant! Sorry if my wording wasn't clear. 🙂 

Thanks for adding a test for that! all LGTM! :shipit:
