### PR TITLE
Fix error while changing payment method of subscription product

### LINKED ISSUE #3924: Cannot update subscriptions on Edit Subscription page when the customer has more saved cards than posts per page
### Describe the bug

When trying to update a subscription purchased with WooCommerce Payments via the Edit Subscription page, I noticed the subscription wasn't updating at all and there was the following error notice being displayed:

image

After inspecting the payment method on the subscription, I noticed the it was empty:

image

This error is caused by `WC_Payment_Tokens::get_tokens()` inside `WC_Payment_Gateway_WCPay::get_user_formatted_tokens_array()` ([called here](https://github.com/Automattic/woocommerce-payments/blob/2201af20dd66c3a71a149572e2630b589aaa0619/includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php#L506)) is returning a list of user tokens limited by `get_option( 'posts_per_page' );` and the card that is saved on the subscription is outside of this limit.

**Possible solution**

I don't think the number of cards being displayed on the Subscriptions payment method should be limited by whatever the store has set for `posts_per_page`.

One option to fix this would be to update the [`WC_Payment_Gateway_WCPay::get_user_formatted_tokens_array()`](https://github.com/Automattic/woocommerce-payments/blob/2201af20dd66c3a71a149572e2630b589aaa0619/includes/class-wc-payment-gateway-wcpay.php#L2527) function so that it will accept custom args (like `'limit'`) that is passed to `get_tokens()`.

### To Reproduce

This bug exists for all types of subscriptions purchased with WooCommerce Payments (i.e. WCPay subscriptions and subscriptions purchased while the WC Subscriptions extension is active).

1. In the `wp_options` table set `posts_per_page` row to `1`
2. Make sure your account has more than 1 saved card with WC Payments
3. Purchase a new subscription with a new saved card
5. Visit the Edit Subscription admin page for this new subscription (**WooCommerce > Subscriptions > click on subscription ID**)
6. Update the status of the subscription from Active to On-hold
7. Press Update button on the Edit Subscription page.
8. Notice the error seen in the above screenshot
9. View the payment details on the subscription and notice it's empty.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by nagpai**
Fixes #3924 

#### Changes proposed in this Pull Request

Fix error in updating subscription when saved cards are more than `posts per page` setting

* Pass a large `token limit` argument to the `get_tokens` function, to mitigate the error. 
* This is a short-term solution to avoid the error for an edge case, where number of saved cards is greater than `posts per page`
* The longer term solution will be to fix this open issue in WC Core. - 
https://github.com/woocommerce/woocommerce/issues/25025

#### Testing instructions

1.   In the `wp_options` table set `posts_per_page` row to `1`
2.  Make sure your account has more than 1 saved card with WC Payments
3.  Purchase a new subscription with a new saved card
4.  Visit the Edit Subscription admin page for this new subscription (**WooCommerce > Subscriptions > click on subscription ID**)
5.  Update the status of the subscription from Active to On-hold
6.  Press Update button on the Edit Subscription page.
7. You should see no errors, and only a message mentioning the subscription status has been updated
8. If you try to edit the user payment details within the sub in WP Admin, you should be able to see the other payment methods in it.  

#### Before  

a. Error on changing status of subscription
image

b. No payment methods appearing within the Subscription Billing settings
image

#### After

a. On changing status of subscription ( no more error ) 
image

b. Payment methods appear in dropdown in subscription billing settings 
image

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply) - Not applicable

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Review by dpaun1985 — APPROVED** [review]
LGTM! 👍 
✅ Tested and works as expected!

File: tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php [hunk 1]
```diff
@@ -512,6 +512,29 @@ public function test_render_custom_payment_meta_input_invalid_value() {
...
+		}
+
+		$this->expectOutputString(
+			'<select name="field_id" id="field_id"><option value="" selected disabled>Please select a payment method</option><option value="' . $tokens[0]->get_id() . '" >' . $tokens[0]->get_display_name() . '</option><option value="' . $tokens[1]->get_id() . '" >' . $tokens[1]->get_display_name() . '</option><option value="' . $tokens[2]->get_id() . '" >' . $tokens[2]->get_display_name() . '</option><option value="' . $tokens[3]->get_id() . '" >' . $tokens[3]->get_display_name() . '</option><option value="' . $tokens[4]->get_id() . '" >' . $tokens[4]->get_display_name() . '</option><option value="' . $tokens[5]->get_id() . '" >' . $tokens[5]->get_display_name() . '</option><option value="' . $tokens[6]->get_id() . '" >' . $tokens[6]->get_display_name() . '</option><option value="' . $tokens[7]->get_id() . '" >' . $tokens[7]->get_display_name() . '</option><option value="' . $tokens[8]->get_id() . '" >' . $tokens[8]->get_display_name() . '</option><option value="' . $tokens[9]->get_id() . '" >' . $tokens[9]->get_display_name() . '</option><option value="' . $tokens[10]->get_id() . '" >' . $tokens[10]->get_display_name() . '</option></select>'
```
Comment (anu-rock) [inline tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php]: Nitpick: We should split this into multiple lines for ease of reading.

**Review by anu-rock — APPROVED** [review]
LGTM :shipit: 

✅ Code changes look good. (left a nitpicky comment)
✅ Tested the change in browser successfully.

**Comment by anu-rock** [comment]
I'll also add that we should update PR's title to something more appropriate as it'll become the first line of our squashed & merged commit.

**Comment by nagpai** [comment]
> I'll also add that we should update PR's title to something more appropriate as it'll become the first line of our squashed & merged commit.

I have renamed the PR 👍

File: includes/class-wc-payment-gateway-wcpay.php [hunk 2]
```diff
@@ -63,6 +63,14 @@ class WC_Payment_Gateway_WCPay extends WC_Payment_Gateway_CC {
 	const UPDATE_SAVED_PAYMENT_METHOD     = 'wcpay_update_saved_payment_method';
 	const UPDATE_CUSTOMER_WITH_ORDER_DATA = 'wcpay_update_customer_with_order_data';
 
+	/**
+	 * Set a large limit argument for retrieving user tokens.
+	 *
+	 * @type int
+	 */
+
+	const USER_FORMATTED_TOKENS_LIMIT = 100;
```
Comment (kalessil) [inline includes/class-wc-payment-gateway-wcpay.php:72]: Not sure about the naming here, what is the intention of `FORMATTED` here?

File: tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php [hunk 3]
```diff
@@ -512,6 +512,29 @@ public function test_render_custom_payment_meta_input_invalid_value() {
 		$this->wcpay_gateway->render_custom_payment_meta_input( $subscription, 'field_id', 'invalid_value' );
 	}
 
+	public function test_render_custom_payment_meta_input_many_tokens() {
```
Comment (kalessil) [inline tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php]: I'd suggest using `multiple` instead of `many` in the test name.

File: tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php [hunk 4]
```diff
@@ -512,6 +512,29 @@ public function test_render_custom_payment_meta_input_invalid_value() {
...
+		$subscription = WC_Helper_Order::create_order( self::USER_ID );
+		$tokens       = [];
+
+		// Create 11 tokens and make it available to the subscription.
+
+		for ( $i = 1; $i <= 11; $i++ ) {
```
Comment (kalessil) [inline tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php]: We can simplify this with e.g.

```php
$tokens = [
    WC_Helper_Token::create_token( self::PAYMENT_METHOD_ID . '_first', self::USER_ID ),
    WC_Helper_Token::create_token( self::PAYMENT_METHOD_ID . '_second', self::USER_ID ),
    WC_Helper_Token::create_token( self::PAYMENT_METHOD_ID . '_thurd', self::USER_ID ),
];
```

It'll make the test code supplier.

**Review by kalessil — CHANGES_REQUESTED** [review]
Hey Nagesh! it great to see more PRs from you coming. I left some comments.

File: tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php (hunk 4 above)
Comment (nagpai) [reply tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php]: Sure, I will switch to that. It was looking repetitive with about 11 tokens, so used a for loop. I agree that it will be simpler not to use the loop and keep things straight.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 2 above)
Comment (nagpai) [reply includes/class-wc-payment-gateway-wcpay.php:72]: I had initially named it `TOKENS_LIMIT` . Based on suggestion from @dpaun1985 , which I agreed - It was appearing too generic. So drew reference from the name of the [associated function](https://github.com/Automattic/woocommerce-payments/blob/b028841a3dc52564d549d0a1b088e93fdff78734/includes/class-wc-payment-gateway-wcpay.php#L2876)  - `get_user_formatted_tokens`

Let me know if it needs a change, @kalessil .

Comment (kalessil) [reply includes/class-wc-payment-gateway-wcpay.php:72]: I see, then it makes sense. Thanks for explaining - we can keep the constant name as it is.

File: tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php (hunk 3 above)
Comment (nagpai) [reply tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php]: Changed it to `multiple` . Thanks!

File: tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php (hunk 4 above)
Comment (nagpai) [reply tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php]: Removed the loop and added the simple array with tokens within it, as suggested.

File: tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php [hunk 5]
```diff
@@ -512,6 +512,34 @@ public function test_render_custom_payment_meta_input_invalid_value() {
...
+			WC_Helper_Token::create_token( self::PAYMENT_METHOD_ID . '_2', self::USER_ID ),
+			WC_Helper_Token::create_token( self::PAYMENT_METHOD_ID . '_3', self::USER_ID ),
+			WC_Helper_Token::create_token( self::PAYMENT_METHOD_ID . '_4', self::USER_ID ),
+			WC_Helper_Token::create_token( self::PAYMENT_METHOD_ID . '_5', self::USER_ID ),
+			WC_Helper_Token::create_token( self::PAYMENT_METHOD_ID . '_6', self::USER_ID ),
+			WC_Helper_Token::create_token( self::PAYMENT_METHOD_ID . '_7', self::USER_ID ),
+			WC_Helper_Token::create_token( self::PAYMENT_METHOD_ID . '_8', self::USER_ID ),
+			WC_Helper_Token::create_token( self::PAYMENT_METHOD_ID . '_9', self::USER_ID ),
+			WC_Helper_Token::create_token( self::PAYMENT_METHOD_ID . '_10', self::USER_ID ),
+			WC_Helper_Token::create_token( self::PAYMENT_METHOD_ID . '_11', self::USER_ID ),
```
Comment (kalessil) [inline tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php:528]: @nagpai , can we keep only 3 of them here - it shall be enough for test and easier to read the test case.

Comment (nagpai) [reply tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php:528]: An [earlier PR](https://github.com/Automattic/woocommerce-payments/pull/1097) cited in our [related issue](https://github.com/Automattic/woocommerce-payments/issues/3924#issuecomment-1102378293), mentioned and fixed an error when there were more than 10 cards. There was no accompanying test to that. Hence thought of testing this with 11 to be safe. 

Let me know if it makes sense to keep it at 11, or reduce to three or lesser number.

File: tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php (hunk 1 above)
Comment (anu-rock) [reply tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php]: Something like this:

```suggestion
	        '<select name="field_id" id="field_id">' .
            '<option value="" selected disabled>Please select a payment method</option>' .
            '<option value="' . $tokens[0]->get_id() . '" >' . $tokens[0]->get_display_name() . '</option>' .
            '<option value="' . $tokens[1]->get_id() . '" >' . $tokens[1]->get_display_name() . '</option>' .
            '<option value="' . $tokens[2]->get_id() . '" >' . $tokens[2]->get_display_name() . '</option>' .
            '<option value="' . $tokens[3]->get_id() . '" >' . $tokens[3]->get_display_name() . '</option>' .
            '<option value="' . $tokens[4]->get_id() . '" >' . $tokens[4]->get_display_name() . '</option>' .
            '<option value="' . $tokens[5]->get_id() . '" >' . $tokens[5]->get_display_name() . '</option>' .
            '<option value="' . $tokens[6]->get_id() . '" >' . $tokens[6]->get_display_name() . '</option>' .
            '<option value="' . $tokens[7]->get_id() . '" >' . $tokens[7]->get_display_name() . '</option>' .
            '<option value="' . $tokens[8]->get_id() . '" >' . $tokens[8]->get_display_name() . '</option>' .
            '<option value="' . $tokens[9]->get_id() . '" >' . $tokens[9]->get_display_name() . '</option>' .
            '<option value="' . $tokens[10]->get_id() . '" >' . $tokens[10]->get_display_name() . '</option>' .
            '</select>'
```

Comment (anu-rock) [reply tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php]: It'll look like this in code:

image

Comment (nagpai) [reply tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php]: Thank you so much for the guidance! I had indeed missed the basics, and added a new line within the quoted string itself. Updated it and it looks much more readable now!

File: tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php (hunk 5 above)
Comment (kalessil) [reply tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php:528]: Gotcha! Then, let's stick to those 11 tokens.

**Review by kalessil — APPROVED** [review]
LGTM!

File: tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php (hunk 1 above)
Comment (anu-rock) [reply tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php]: Thanks for fixing this. It looks much better now :)

**Comment by haszari** [comment]
Thanks for fixing this annoying issue @nagpai !
