### PR TITLE
Fix placeholder injection problem in New Receipt email

### LINKED ISSUE #4071: Text placeholders not working on In Person Payment receipt email
### Describe the bug

The placeholders `{site_title}` and `{site_url}` in the 'New Receipt' email are not being injected. They remain as `{site_title}` and  `{site_url}` in the email's text.

### To Reproduce

1. Pay for an order with a card reader
2. Check the email sent to customer

### Actual behavior

See that placeholders are not replaced
### Expected behavior

The placeholders are replaced by the site and url of the merchant's site.

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #4071

#### Changes proposed in this Pull Request
Fixes a bug that causes that the the placeholders `{site_title}` and `{site_url}` in the 'New Receipt' email are not being injected.

The WC_Email parent class merges the placeholders defined in the subclass with its own, when the constructor is executed. For this reason we need to move the call to the parent constructor only after placeholders are defined.

#### Testing instructions

* Set up the local dev store with WCPay plugin to allow for Cash on Delivery orders
* Set up local dev WCPay server to listen to webhooks
* Pay for the order using a card reader, you can emulate one if you follow this [guide](pdjVC1-9M-p2): 
* Check that the `{site_title}` and `{site_url}` placeholders are replaced with the correct data in the email. You can use a plugin like [WP Mail Log](https://wordpress.org/plugins/wp-mail-logging/) for this purpose.

HTML version:

Screen Shot 2022-04-05 at 13 43 48

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) :'QA Testing Not Applicable'

### CODE REVIEW

File: changelog/fix-4071-text-placeholders-not-working-on-in-person-payment-receipt-email [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Fix placeholder injection problem in New Receipt email
```
Comment (KarlisJ) [inline changelog/fix-4071-text-placeholders-not-working-on-in-person-payment-receipt-email:4]: I'm not the best person to judge what is or isn't good changelog entry but `injection problem` seems quite generic.

File: includes/emails/class-wc-payments-email-ipp-receipt.php [hunk 2]
```diff
@@ -63,6 +60,9 @@ public function __construct() {
 			// Triggers for this email.
 			add_action( 'woocommerce_payments_email_ipp_receipt_notification', [ $this, 'trigger' ], 10, 3 );
 
+			// Call parent constructor.
```
[the remark this answers is not in the document]
Comment (KarlisJ) [reply includes/emails/class-wc-payments-email-ipp-receipt.php:63]: +1 from me. The `WC_Email` feels poorly designed and in no way the intended usage seems natural. So I would even include that it's the intended use of parent class rather than some hack. 

Context: Comments like this can be viewed as an explanation of a hack but here it's actually the intended use case.

[the remark this answers is not in the document]
Comment (mgascam) [reply includes/emails/class-wc-payments-email-ipp-receipt.php]: Done

File: changelog/fix-4071-text-placeholders-not-working-on-in-person-payment-receipt-email (hunk 1 above)
Comment (mgascam) [reply changelog/fix-4071-text-placeholders-not-working-on-in-person-payment-receipt-email]: Done

**Review by anu-rock — APPROVED** [review]
LGTM with the new changes ✅

File: includes/emails/class-wc-payments-email-ipp-receipt.php [hunk 3]
```diff
@@ -63,6 +61,15 @@ public function __construct() {
 			// Triggers for this email.
 			add_action( 'woocommerce_payments_email_ipp_receipt_notification', [ $this, 'trigger' ], 10, 3 );
 
+			/**
+			 * Please don't move. The call to the parent constructor here is intentional. It allows this class to merge
+			 * its placeholders with the parent's and prefix the settings with its own identifier.
+			 * Moving this call to the top of the constructor will cause the placeholders to stop working and
+			 * loose the woocommerce_payments_ prefix in the settings.
```
Comment (KarlisJ) [inline includes/emails/class-wc-payments-email-ipp-receipt.php:68]: Small typo "loose" -> "lose"

**Comment by KarlisJ** [comment]
LGTM!

File: includes/emails/class-wc-payments-email-ipp-receipt.php (hunk 3 above)
Comment (mgascam) [reply includes/emails/class-wc-payments-email-ipp-receipt.php]: Done
