### PR TITLE
Polish logic of redirect when click Set Up WooPayments from WC Home

### LINKED ISSUE #7625: Clicking on the completed "Set up WooPayments" task from Core takes you to a "Sorry you are not allowed to access this page"
### Describe the bug
See 03:35 in this recorded demo p1698953366764689-slack-C03KTTK2YMA

After clicking on that task, it should redirect the user to the Payments dashboard.

Note: the code lives in Woo Core repo, but opening the issue here for easier management and tracking

### PR DESCRIPTION
**Pull request by oaratovskyi**
Related #7625

**Follow up of** https://github.com/Automattic/woocommerce-payments/pull/7652 with intent to improve the solution for more account statuses by making decision based on `details_submitted` value, see p1699436266692369/1699365759.939169-slack-C03KTTK2YMA

#### Description

Merchants currently observe an issue with Set up WooPayments task: when account completed the KYC / are rejected / pending - have Stripe account connected, the link redirect them to `payments/onboarding` which results in Not allowed page error
image

#### Changes proposed in this Pull Request

I decided that the best experience for merchants will be to get redirected to `payments/overview` page if the account connected to Stripe in any status. If we try to redirect the merchant to `payments/onboarding` page when they have Stripe account connected, they'll face Not allowed page. That's why we should redirect even partially onboarded users (details_submitted = false) to the overview page. They'll be able to proceed from there by hitting Finish Setup button
image

**Important**
Tests are not added since there is no tests for `maybe_handle_onboarding` function. Creating tests for it is out of scope for this PR. It'll be done in https://github.com/Automattic/woocommerce-payments/issues/7654

#### Testing instructions

**Pre-requisites**
* Checkout the branch `tweak/7625-set-up-woopayments-link-from-core-polish-current-logic` 
* Ensure Progressive onboarding feature flag is enabled

**Stripe account not connected**
* Navigate to Payments Connect page
* Onboard an account as a builder, it'll end up in `Complete` status
* Get back to WC Home and click Set up WooPayments
* Ensure you get redirected to `payments/overview` page

**Stripe account connected (pending)**
* Delete/mark as deleted current account 
* Navigate to Payments Connect page
* Complete PO as a merchant, it should and up in the `Pending` status
* Get back to WC Home and click Set up WooPayments
* Ensure you get redirected to `payments/overview` page

**Stripe KYC left early / partially onboarded accounts**
* Delete/mark as deleted current account 
* Navigate to Payments Connect page
* Start onboarding as a builder, leave the KYC immediately on the Stripe step (Return to Dev Shared Account WCPay)
* You should see Finish setting up WooPayments on the overview page
* Get back to WC Home and click Set up WooPayments
* Ensure you get redirected to `payments/overview` page

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions-for-WC-Payments-6.8.0#fix-not-allowed-page-when-clicking-set-up-woopayments-from-core-and-account-is-already-onboarded_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7659` or branch name `tweak/7625-set-up-woopayments-link-from-core-polish-current-logic` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=tweak/7625-set-up-woopayments-link-from-core-polish-current-logic) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: a5f5eeb6fea925b03b052c319c627923df182e6d
- Build time: 2023-11-08 16:08:14 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payments-account.php [hunk 1]
```diff
@@ -222,21 +222,6 @@ public function is_account_rejected(): bool {
 		return strpos( $account['status'] ?? '', 'rejected' ) === 0;
 	}
 
-	/**
-	 * Checks if the account has been completed.
-	 * Returns false if the account is not connected.
-	 *
-	 * @return bool True if the account is connected and complete, false otherwise or on error.
-	 */
-	public function is_account_complete(): bool {
```
Comment (oaratovskyi) [inline includes/class-wc-payments-account.php:231]: Removed as not needed anymore 👀

**Review by vladolaru — APPROVED** [review]
Nice to see this proactivity and push for perfection, @oaratovskyi! 💪

All the testing instructions check out! And the code changes make for more resilient system! 🚢 it!
