### PR TITLE
Save tokens for Link payment method

### LINKED ISSUE #4703: StripeLink: no token is saved for subscription orders
### Describe the bug

When ordering a subscription product, the payment token is saved in the database.

Context: p1662348099755489-slack-C7U3Y3VMY
### To Reproduce

1. Create an order with a subscription product
2. Pay it with Link payment method
3. The payment token is not saved in the database.

### PR DESCRIPTION
**Pull request by dpaun1985**
Fixes #4703 

#### Changes proposed in this Pull Request
For subscriptions, the payment method token should be saved in order to be re-used for subscription renewal. 
This PR updates Link payment method to save the token.

#### Testing instructions

* **Scenario 1**
* Create a new subscription order and pay it using Link
* Payment should be completed
* The payment of renewal for the subscription should be processed without errors. To check this, use a 1 day subscription renewal.
* Subscription fee should be applied
* **Scenario 2**
* Create a new subscription with 1 day trial version order and pay it using Link
* Payment should be completed
* The payment for the subscription should be processed without errors after the trial ends.
* Subscription fee should be applied
* **Scenario 3**
* Install [Woocommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/)
* When WCS is enabled it will take over the subscription functionality and will be managed by WCS.
* In order to trigger subscription renewals, you can follow the steps [ [here](https://woocommerce.com/document/testing-subscription-renewal-payments/) ]
* Repeat the tests above. 
* Subscription fee should NOT be applied.

Notes: 
1. In order to test the built-in subscription, you have to create a 1day subscription and wait for Stripe to renew the subscription. You cannot test it with Stripe's Subscription Clocks, because this will create a duplicate customer, and a new payment method ( credit card payment method ). 
2. If the subscription is not renewed after 1 day on client side, you can check the events on Stripe side for that subscription because you might have the listen webhook closed on your local when Stripe renewed the subscription.
3. [Subscriptions plugin](https://woocommerce.com/products/woocommerce-subscriptions/) overlaps the built in subscriptions.
4. In order to test the subscriptions plugin, please use the steps from [here](https://woocommerce.com/document/testing-subscription-renewal-payments/). 
-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: changelog/fix-4703-link-for-subscriptions [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Save tokens for Link payment method
```
Comment (kalessil) [inline changelog/fix-4703-link-for-subscriptions]: Can we mention subscriptions here, please?

File: includes/class-wc-payment-token-wcpay-link.php [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+	/**
+	 * Get type to display to user.
+	 *
+	 * @param  string $deprecated Deprecated since WooCommerce 3.0.
+	 * @return string
+	 */
+	public function get_display_name( $deprecated = '' ) {
+		$display = sprintf(
+			/* translators: customer email */
+			__( 'Link email %s', 'woocommerce-payments' ),
```
Comment (kalessil) [inline includes/class-wc-payment-token-wcpay-link.php]: While we use Link in general, I think in this case, `Stripe Link` would be more clarifying.

File: includes/class-wc-payments-token-service.php [hunk 3]
```diff
@@ -64,6 +64,10 @@ public function add_token_to_user( $payment_method, $user ) {
 			$token = new WC_Payment_Token_WCPay_SEPA();
 			$token->set_gateway_id( CC_Payment_Gateway::GATEWAY_ID );
 			$token->set_last4( $payment_method[ Payment_Method::SEPA ]['last4'] );
+		} elseif ( Payment_Method::LINK === $payment_method['type'] ) {
```
Comment (kalessil) [inline includes/class-wc-payments-token-service.php]: It's a good time to refactor the block with `switch-case` construct. WDYT?

File: tests/unit/test-class-wc-payments-token-service.php [hunk 4]
```diff
@@ -111,6 +110,27 @@ public function test_add_token_to_user_for_sepa() {
...
+			'id'   => 'pm_mock',
+			'link' => [
+				'email' => 'test@test.com',
+			],
+			'type' => Payment_Method::LINK,
+		];
+
+		$token = $this->token_service->add_token_to_user( $mock_payment_method, wp_get_current_user() );
+
+		$this->assertEquals( 'woocommerce_payments', $token->get_gateway_id() );
```
Comment (kalessil) [inline tests/unit/test-class-wc-payments-token-service.php]: Strict asserts, please.

File: includes/class-wc-payment-token-wcpay-link.php [hunk 5]
```diff
@@ -0,0 +1,86 @@
...
+	}
+
+	/**
+	 * Returns the customer email.
+	 *
+	 * @param string $context What the value is for. Valid values are view and edit.
+	 *
+	 * @return string Customer email.
+	 */
+	public function get_email( string $context = 'view' ): string {
```
Comment (kalessil) [inline includes/class-wc-payment-token-wcpay-link.php]: I'm a bit not sure how well this comes by with WCs' flexibility. Other tokens (incl. WC itself) declare types in doc-blocks, but not in method definition (return and parameters types), should we follow the same path (I'm not sure and would like to get a collective decision on this)?

File: includes/class-wc-payment-token-wcpay-link.php [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+		return $this->get_prop( 'email', $context );
+	}
+
+	/**
+	 * Set the customer email.
+	 *
+	 * @param string $email Customer email.
+	 */
+	public function set_email( string $email ) {
```
Comment (kalessil) [inline includes/class-wc-payment-token-wcpay-link.php]: Similar case here: I'm a bit not sure how well this comes by with WCs' flexibility.

**Review by kalessil — CHANGES_REQUESTED** [review]

File: includes/class-wc-payment-token-wcpay-link.php (hunk 5 above)
Comment (dpaun1985) [reply includes/class-wc-payment-token-wcpay-link.php]: checking the requirements [here](https://wordpress.org/plugins/woocommerce-payments/), min PHP version is 7.0. Scalar types were introduced in PHP 7.0, so I expect that this will not create an issue.
Other opinions would be helpful.

Comment (kalessil) [reply includes/class-wc-payment-token-wcpay-link.php]: I'm concerned about the possibility that WooCommerce might pass in data of the wrong type.
If there are no scenarios when this might happen, I'm ok with keeping the types.

**Comment by fashuvo** [comment]
**Size Change:** 0 B 

**Total Size:** 1.63 MB



<details><summary>ℹ️ <strong>View Unchanged</strong></summary>

| Filename | Size |
| :--- | :---: |
| `release/woocommerce-payments/assets/css/admin.css` | 913 B |
| `release/woocommerce-payments/assets/css/success.css` | 401 B |
| `release/woocommerce-payments/dist/blocks-checkout.css` | 1.77 kB |
| `release/woocommerce-payments/dist/blocks-checkout.js` | 27 kB |
| `release/woocommerce-payments/dist/checkout.css` | 1.85 kB |
| `release/woocommerce-payments/dist/checkout.js` | 25.9 kB |
| `release/woocommerce-payments/dist/index.css` | 35.8 kB |
| `release/woocommerce-payments/dist/index.js` | 627 kB |
| `release/woocommerce-payments/dist/multi-currency-analytics.js` | 8.22 kB |
| `release/woocommerce-payments/dist/multi-currency-switcher-block.js` | 71 kB |
| `release/woocommerce-payments/dist/multi-currency.css` | 14.7 kB |
| `release/woocommerce-payments/dist/multi-currency.js` | 109 kB |
| `release/woocommerce-payments/dist/onboarding.css` | 1.12 kB |
| `release/woocommerce-payments/dist/onboarding.js` | 38 kB |
| `release/woocommerce-payments/dist/order.js` | 299 B |
| `release/woocommerce-payments/dist/payment-gateways.css` | 1.2 kB |
| `release/woocommerce-payments/dist/payment-gateways.js` | 82.8 kB |
| `release/woocommerce-payments/dist/payment-request.js` | 22.4 kB |
| `release/woocommerce-payments/dist/platform-checkout.css` | 3.73 kB |
| `release/woocommerce-payments/dist/platform-checkout.js` | 76.6 kB |
| `release/woocommerce-payments/dist/settings.css` | 47.2 kB |
| `release/woocommerce-payments/dist/settings.js` | 148 kB |
| `release/woocommerce-payments/dist/subscription-edit-page.js` | 3.66 kB |
| `release/woocommerce-payments/dist/subscription-product-onboarding-modal.css` | 7.18 kB |
| `release/woocommerce-payments/dist/subscription-product-onboarding-modal.js` | 16.5 kB |
| `release/woocommerce-payments/dist/subscription-product-onboarding-toast.js` | 428 B |
| `release/woocommerce-payments/dist/subscriptions-empty-state.css` | 298 B |
| `release/woocommerce-payments/dist/subscriptions-empty-state.js` | 48.8 kB |
| `release/woocommerce-payments/dist/tos.css` | 236 B |
| `release/woocommerce-payments/dist/tos.js` | 22.7 kB |
| `release/woocommerce-payments/dist/upe_checkout.css` | 1.85 kB |
| `release/woocommerce-payments/dist/upe_checkout.js` | 37.2 kB |
| `release/woocommerce-payments/dist/upe-blocks-checkout.css` | 1.77 kB |
| `release/woocommerce-payments/dist/upe-blocks-checkout.js` | 43.4 kB |
| `release/woocommerce-payments/includes/subscriptions/assets/css/plugin-page.css` | 633 B |
| `release/woocommerce-payments/includes/subscriptions/assets/js/plugin-page.js` | 355 B |
| `release/woocommerce-payments/vendor/automattic/jetpack-admin-ui/src/css/jetpack-icon.css` | 224 B |
| `release/woocommerce-payments/vendor/automattic/jetpack-assets/build/i18n-loader.js` | 2.43 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-assets/src/js/i18n-loader.js` | 1.01 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-identity-crisis/babel.config.js` | 160 B |
| `release/woocommerce-payments/vendor/automattic/jetpack-identity-crisis/build/index.css` | 2.27 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-identity-crisis/build/index.js` | 13.3 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-identity-crisis/build/index.rtl.css` | 2.27 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-tracking/src/js/tracks-ajax.js` | 789 B |
| `release/woocommerce-payments/vendor/automattic/jetpack-tracking/src/js/tracks-callables.js` | 925 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/about.css` | 1.2 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/admin-order-statuses.css` | 403 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/admin.css` | 3.43 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/checkout.css` | 299 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/modal.css` | 742 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/view-subscription.css` | 572 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/wcs-upgrade.css` | 411 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/admin-pointers.js` | 544 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/admin.js` | 8.97 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/jstz.js` | 6.8 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/jstz.min.js` | 3.83 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/meta-boxes-coupon.js` | 544 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/meta-boxes-subscription.js` | 2.35 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/moment.js` | 22.1 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/moment.min.js` | 11.6 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/payment-method-restrictions.js` | 1.29 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/wcs-meta-boxes-order.js` | 502 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/frontend/payment-methods.js` | 355 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/frontend/single-product.js` | 429 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/frontend/view-subscription.js` | 1.38 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/frontend/wcs-cart.js` | 387 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/modal.js` | 1.1 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/wcs-upgrade.js` | 1.27 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/build/index.css` | 392 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/build/index.js` | 3.06 kB |

</details>



<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a>

File: includes/class-wc-payment-token-wcpay-link.php (hunk 5 above)
Comment (dpaun1985) [reply includes/class-wc-payment-token-wcpay-link.php]: To be on the safe side, I removed the types.

File: includes/class-wc-payment-token-wcpay-link.php (hunk 6 above)
Comment (dpaun1985) [reply includes/class-wc-payment-token-wcpay-link.php]: To be on the safe side, I removed the types.

**Comment by fashuvo** [comment]
**Size Change:** 0 B 

**Total Size:** 1.63 MB



<details><summary>ℹ️ <strong>View Unchanged</strong></summary>

| Filename | Size |
| :--- | :---: |
| `release/woocommerce-payments/assets/css/admin.css` | 913 B |
| `release/woocommerce-payments/assets/css/success.css` | 401 B |
| `release/woocommerce-payments/dist/blocks-checkout.css` | 1.77 kB |
| `release/woocommerce-payments/dist/blocks-checkout.js` | 27 kB |
| `release/woocommerce-payments/dist/checkout.css` | 1.85 kB |
| `release/woocommerce-payments/dist/checkout.js` | 25.9 kB |
| `release/woocommerce-payments/dist/index.css` | 35.8 kB |
| `release/woocommerce-payments/dist/index.js` | 627 kB |
| `release/woocommerce-payments/dist/multi-currency-analytics.js` | 8.22 kB |
| `release/woocommerce-payments/dist/multi-currency-switcher-block.js` | 71 kB |
| `release/woocommerce-payments/dist/multi-currency.css` | 14.7 kB |
| `release/woocommerce-payments/dist/multi-currency.js` | 109 kB |
| `release/woocommerce-payments/dist/onboarding.css` | 1.12 kB |
| `release/woocommerce-payments/dist/onboarding.js` | 38 kB |
| `release/woocommerce-payments/dist/order.js` | 299 B |
| `release/woocommerce-payments/dist/payment-gateways.css` | 1.2 kB |
| `release/woocommerce-payments/dist/payment-gateways.js` | 82.8 kB |
| `release/woocommerce-payments/dist/payment-request.js` | 22.4 kB |
| `release/woocommerce-payments/dist/platform-checkout.css` | 3.73 kB |
| `release/woocommerce-payments/dist/platform-checkout.js` | 76.6 kB |
| `release/woocommerce-payments/dist/settings.css` | 47.2 kB |
| `release/woocommerce-payments/dist/settings.js` | 148 kB |
| `release/woocommerce-payments/dist/subscription-edit-page.js` | 3.66 kB |
| `release/woocommerce-payments/dist/subscription-product-onboarding-modal.css` | 7.18 kB |
| `release/woocommerce-payments/dist/subscription-product-onboarding-modal.js` | 16.5 kB |
| `release/woocommerce-payments/dist/subscription-product-onboarding-toast.js` | 428 B |
| `release/woocommerce-payments/dist/subscriptions-empty-state.css` | 298 B |
| `release/woocommerce-payments/dist/subscriptions-empty-state.js` | 48.8 kB |
| `release/woocommerce-payments/dist/tos.css` | 236 B |
| `release/woocommerce-payments/dist/tos.js` | 22.7 kB |
| `release/woocommerce-payments/dist/upe_checkout.css` | 1.85 kB |
| `release/woocommerce-payments/dist/upe_checkout.js` | 37.2 kB |
| `release/woocommerce-payments/dist/upe-blocks-checkout.css` | 1.77 kB |
| `release/woocommerce-payments/dist/upe-blocks-checkout.js` | 43.4 kB |
| `release/woocommerce-payments/includes/subscriptions/assets/css/plugin-page.css` | 633 B |
| `release/woocommerce-payments/includes/subscriptions/assets/js/plugin-page.js` | 355 B |
| `release/woocommerce-payments/vendor/automattic/jetpack-admin-ui/src/css/jetpack-icon.css` | 224 B |
| `release/woocommerce-payments/vendor/automattic/jetpack-assets/build/i18n-loader.js` | 2.43 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-assets/src/js/i18n-loader.js` | 1.01 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-identity-crisis/babel.config.js` | 160 B |
| `release/woocommerce-payments/vendor/automattic/jetpack-identity-crisis/build/index.css` | 2.27 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-identity-crisis/build/index.js` | 13.3 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-identity-crisis/build/index.rtl.css` | 2.27 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-tracking/src/js/tracks-ajax.js` | 789 B |
| `release/woocommerce-payments/vendor/automattic/jetpack-tracking/src/js/tracks-callables.js` | 925 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/about.css` | 1.2 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/admin-order-statuses.css` | 403 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/admin.css` | 3.43 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/checkout.css` | 299 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/modal.css` | 742 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/view-subscription.css` | 572 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/wcs-upgrade.css` | 411 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/admin-pointers.js` | 544 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/admin.js` | 8.97 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/jstz.js` | 6.8 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/jstz.min.js` | 3.83 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/meta-boxes-coupon.js` | 544 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/meta-boxes-subscription.js` | 2.35 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/moment.js` | 22.1 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/moment.min.js` | 11.6 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/payment-method-restrictions.js` | 1.29 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/wcs-meta-boxes-order.js` | 502 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/frontend/payment-methods.js` | 355 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/frontend/single-product.js` | 429 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/frontend/view-subscription.js` | 1.38 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/frontend/wcs-cart.js` | 387 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/modal.js` | 1.1 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/wcs-upgrade.js` | 1.27 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/build/index.css` | 392 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/build/index.js` | 3.06 kB |

</details>



<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a>

**Comment by fashuvo** [comment]
**Size Change:** 0 B 

**Total Size:** 1.69 MB



<details><summary>ℹ️ <strong>View Unchanged</strong></summary>

| Filename | Size |
| :--- | :---: |
| `release/woocommerce-payments/assets/css/admin.css` | 913 B |
| `release/woocommerce-payments/assets/css/success.css` | 401 B |
| `release/woocommerce-payments/dist/blocks-checkout.css` | 1.77 kB |
| `release/woocommerce-payments/dist/blocks-checkout.js` | 28.1 kB |
| `release/woocommerce-payments/dist/checkout.css` | 1.85 kB |
| `release/woocommerce-payments/dist/checkout.js` | 26.7 kB |
| `release/woocommerce-payments/dist/index.css` | 35.8 kB |
| `release/woocommerce-payments/dist/index.js` | 640 kB |
| `release/woocommerce-payments/dist/multi-currency-analytics.js` | 8.41 kB |
| `release/woocommerce-payments/dist/multi-currency-switcher-block.js` | 79 kB |
| `release/woocommerce-payments/dist/multi-currency.css` | 14.7 kB |
| `release/woocommerce-payments/dist/multi-currency.js` | 117 kB |
| `release/woocommerce-payments/dist/onboarding.css` | 1.12 kB |
| `release/woocommerce-payments/dist/onboarding.js` | 38.1 kB |
| `release/woocommerce-payments/dist/order.js` | 299 B |
| `release/woocommerce-payments/dist/payment-gateways.css` | 1.2 kB |
| `release/woocommerce-payments/dist/payment-gateways.js` | 91 kB |
| `release/woocommerce-payments/dist/payment-request.js` | 23 kB |
| `release/woocommerce-payments/dist/platform-checkout.css` | 3.73 kB |
| `release/woocommerce-payments/dist/platform-checkout.js` | 76.9 kB |
| `release/woocommerce-payments/dist/settings.css` | 47.2 kB |
| `release/woocommerce-payments/dist/settings.js` | 157 kB |
| `release/woocommerce-payments/dist/subscription-edit-page.js` | 3.66 kB |
| `release/woocommerce-payments/dist/subscription-product-onboarding-modal.css` | 7.18 kB |
| `release/woocommerce-payments/dist/subscription-product-onboarding-modal.js` | 16.7 kB |
| `release/woocommerce-payments/dist/subscription-product-onboarding-toast.js` | 428 B |
| `release/woocommerce-payments/dist/subscriptions-empty-state.css` | 298 B |
| `release/woocommerce-payments/dist/subscriptions-empty-state.js` | 49 kB |
| `release/woocommerce-payments/dist/tos.css` | 236 B |
| `release/woocommerce-payments/dist/tos.js` | 31.7 kB |
| `release/woocommerce-payments/dist/upe_checkout.css` | 1.85 kB |
| `release/woocommerce-payments/dist/upe_checkout.js` | 38 kB |
| `release/woocommerce-payments/dist/upe-blocks-checkout.css` | 1.77 kB |
| `release/woocommerce-payments/dist/upe-blocks-checkout.js` | 44.8 kB |
| `release/woocommerce-payments/includes/subscriptions/assets/css/plugin-page.css` | 633 B |
| `release/woocommerce-payments/includes/subscriptions/assets/js/plugin-page.js` | 355 B |
| `release/woocommerce-payments/vendor/automattic/jetpack-admin-ui/src/css/jetpack-icon.css` | 224 B |
| `release/woocommerce-payments/vendor/automattic/jetpack-assets/build/i18n-loader.js` | 2.43 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-assets/src/js/i18n-loader.js` | 1.01 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-identity-crisis/babel.config.js` | 160 B |
| `release/woocommerce-payments/vendor/automattic/jetpack-identity-crisis/build/index.css` | 2.27 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-identity-crisis/build/index.js` | 13.3 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-identity-crisis/build/index.rtl.css` | 2.27 kB |
| `release/woocommerce-payments/vendor/automattic/jetpack-tracking/src/js/tracks-ajax.js` | 789 B |
| `release/woocommerce-payments/vendor/automattic/jetpack-tracking/src/js/tracks-callables.js` | 925 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/about.css` | 1.2 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/admin-order-statuses.css` | 403 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/admin.css` | 3.43 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/checkout.css` | 299 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/modal.css` | 742 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/view-subscription.css` | 572 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/css/wcs-upgrade.css` | 411 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/admin-pointers.js` | 544 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/admin.js` | 8.97 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/jstz.js` | 6.8 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/jstz.min.js` | 3.83 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/meta-boxes-coupon.js` | 544 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/meta-boxes-subscription.js` | 2.35 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/moment.js` | 22.1 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/moment.min.js` | 11.6 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/payment-method-restrictions.js` | 1.29 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/admin/wcs-meta-boxes-order.js` | 502 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/frontend/payment-methods.js` | 355 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/frontend/single-product.js` | 429 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/frontend/view-subscription.js` | 1.38 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/frontend/wcs-cart.js` | 387 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/modal.js` | 1.1 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/assets/js/wcs-upgrade.js` | 1.27 kB |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/build/index.css` | 392 B |
| `release/woocommerce-payments/vendor/woocommerce/subscriptions-core/build/index.js` | 3.06 kB |

</details>



<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a>

File: includes/class-wc-payment-token-wcpay-link.php [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+}
+
+/**
+ * WooCommerce Stripe Link Payment Token.
+ *
+ * Representation of a payment token for Link.
+ *
+ * @class    WC_Payment_Token_WCPay_Link
+ */
+class WC_Payment_Token_WCPay_Link extends WC_Payment_Token {
```
Comment (KarlisJ) [inline includes/class-wc-payment-token-wcpay-link.php:19]: To me `WC_WCPay_Link_Payment_Token` reads better.

Edit: I now see that you're following the existing convention. That's better

File: includes/class-wc-payment-token-wcpay-link.php [hunk 8]
```diff
@@ -0,0 +1,86 @@
...
+	 * Stores Link payment token data.
+	 *
+	 * @var array
+	 */
+	protected $extra_data = [
+		'email' => '',
+	];
+
+	/**
+	 * Get type to display to user.
```
Comment (KarlisJ) [inline includes/class-wc-payment-token-wcpay-link.php]: The description doesn't align with the method name. Is the description correct?

**Review by KarlisJ — COMMENTED** [review]
LGTM!

Purely code review changes is looking good. Left some minot comments.

File: includes/class-wc-payment-token-wcpay-link.php (hunk 8 above)
Comment (dpaun1985) [reply includes/class-wc-payment-token-wcpay-link.php]: added more context. thx

**Comment by elazzabi** [comment]
As mentioned in Slack, I tried to test this but the test subscriptions are paused for some reason...

**Comment by dpaun1985** [comment]
> As mentioned in Slack, I tried to test this but the test subscriptions are paused for some reason...

@elazzabi could you please check the order notes/logs to see why is the subscription paused ?

**Comment by dpaun1985** [comment]
> > As mentioned in Slack, I tried to test this but the test subscriptions are paused for some reason...
> 
> @elazzabi could you please check the order notes/logs to see why is the subscription paused ?

This was caused because of the duplicate site check. 
context: p1664372952456779-slack-C02C00HCJ8J

File: includes/class-wc-payment-token-wcpay-link.php [hunk 9]
```diff
@@ -0,0 +1,86 @@
+<?php
+/**
+ * Class WC_Payment_Token_WCPay_SEPA
```
Comment (Jinksi) [inline includes/class-wc-payment-token-wcpay-link.php]:
```suggestion
 * Class WC_Payment_Token_WCPay_Link
```

Nitpick: comment references SEPA rather than Link

**Review by Jinksi — APPROVED** [review]
LGTM @dpaun1985 🙌 

I've left one (very) minor suggestion.

I've tested purchasing with the Stripe Link payment method on a live (Pressable) site with a test WCPay account, all is working as expected:
- [x] WCPay daily sub purchase + extra subs fee.
- [x] WCPay daily sub renewal + extra subs fee. (awaiting 24h renewal period)
- [x] WCPay daily sub + 24h trial order.
- [x] WCPay daily sub + 24h trial renewal + extra subs fee. (awaiting 24h renewal period)
- [x] WC Subs daily sub purchase: no extra subs fee.
- [x] WC Subs daily sub renewal: no extra subs fee. (trigger scheduled action)
- [x] WC Subs daily sub + 24h trial order.
- [x] WC Subs daily sub + 24h trial renewal: no extra subs fee. (trigger scheduled action)

~PS I'll return in 23hrs to check that the WCPay sub renewals have gone through~ 😄 

**Update**: the WCPay sub renewals were processed with the correct fees ✅ 🥳

File: includes/class-wc-payment-token-wcpay-link.php (hunk 9 above)
Comment (dpaun1985) [reply includes/class-wc-payment-token-wcpay-link.php]: done. thank you!

**Comment by dpaun1985** [comment]
> LGTM @dpaun1985 🙌
> 
> I've left one (very) minor suggestion.
> 
> I've tested purchasing with the Stripe Link payment method on a live (Pressable) site with a test WCPay account, all is working as expected:
> 
> * [x]  WCPay daily sub purchase + extra subs fee.
> * [x]  WCPay daily sub renewal + extra subs fee. (awaiting 24h renewal period)
> * [x]  WCPay daily sub + 24h trial order.
> * [x]  WCPay daily sub + 24h trial renewal + extra subs fee. (awaiting 24h renewal period)
> * [x]  WC Subs daily sub purchase: no extra subs fee.
> * [x]  WC Subs daily sub renewal: no extra subs fee. (trigger scheduled action)
> * [x]  WC Subs daily sub + 24h trial order.
> * [x]  WC Subs daily sub + 24h trial renewal: no extra subs fee. (trigger scheduled action)
> 
> ~PS I'll return in 23hrs to check that the WCPay sub renewals have gone through~ 😄
> 
> **Update**: the WCPay sub renewals were processed with the correct fees ✅ 🥳

Thank you !!

File: includes/class-wc-payments-token-service.php [hunk 10]
```diff
@@ -60,17 +60,25 @@ public function add_token_to_user( $payment_method, $user ) {
...
-		} else {
-			$token = new WC_Payment_Token_CC();
-			$token->set_gateway_id( CC_Payment_Gateway::GATEWAY_ID );
-			$token->set_expiry_month( $payment_method[ Payment_Method::CARD ]['exp_month'] );
-			$token->set_expiry_year( $payment_method[ Payment_Method::CARD ]['exp_year'] );
-			$token->set_card_type( strtolower( $payment_method[ Payment_Method::CARD ]['brand'] ) );
-			$token->set_last4( $payment_method[ Payment_Method::CARD ]['last4'] );
+		switch ( $payment_method['type'] ) {
+			case Payment_Method::SEPA:
+				$token = new WC_Payment_Token_WCPay_SEPA();
```
Comment (dmvrtx) [inline includes/class-wc-payments-token-service.php:65]: I find it a bit odd, that token classes are not declared in the `use ...` section

Comment (kalessil) [reply includes/class-wc-payments-token-service.php:65]: Those are in the same folder and namespace, hence it works without imports.

**Review by kalessil — APPROVED** [review]
LGTM!

**Comment by kalessil** [comment]
@dpaun1985: I believe we can go ahead with actualizing the branch and merging the PR.
