### PR TITLE
Fix multiple conversions with subscription switching, minor refactor for manual renewals

### LINKED ISSUE #2125: Subscription switching pricing is not working correctly when prices are converted
Subscriptions allows customers to switch between variations of a variable subscription, if the option is enabled. There is an option to prorate the cost of the switch, which will charge the difference between the variation options. When prices are being converted, the costs are not being properly calculated.

1. Go to WooCommerce > Settings > Subscriptions and enable switching, also setting to prorate recurring payment for upgrades and downgrades.
2. Use or set up a variable sub product that has at least 2 variations with different prices, such as 10/month and 20/month.
3. Sign up for the lower price.
4. Once order is complete, scroll down to use the View option to view the subscription.
5. Use the _Upgrade or Downgrade_ button on the subscription to start the process.
6. Choose the higher priced variation on the product and you will see no additional fee is being charged if the currency is being converted.
7. Doing the above with multi-currency disabled results in the proper calculations

Bonus issue:
If the subscription is purchased in the store's base currency, and then switched in a converted currency, the difference for proration is the difference in the store's base currency.

1. Make sure you're either using the store base currency or have multi-currency disabled.
2. Do steps 1-5 above.
3. Change currencies, and then choose the higher priced variation to switch.
4. The difference being charged in the cart will be the store's base currency difference.

Screenshot on 2021-06-10 at 12-18-33

### PR DESCRIPTION
**Pull request by jessepearson**
Fixes #2125

#### Changes proposed in this Pull Request

* Move/add filters for subscriptions to `Compatibility` class.
* Include `MultiCurrency` class into `Compatibility` class.
* `get_subscription_product_price` returns proper amount for subscription price.
* `get_subscription_product_signup_fee` returns proper amount for subscription sign up fee.
* `maybe_disable_mixed_cart` disables allowing more than just a single subscription being added to the cart. Presently only when there's a switch in the cart. Prevents subscriptions with different currencies being added to the cart.
* Update `override_selected_currency` to check for subscription switches and force the currency to the sub's currency.
* Update `should_hide_widgets` to hide widgets if a switch is happening.
* `get_subscription_switch_cart_items` returns subscription cart items.
* `get_subscription_switch_id_from_superglobal` gets sub switch id from `$_GET` superglobal.
* `get_product_price` consolidated checks. Hoped to remove compatibility here, but due to how prices are filtered, we cannot do that just yet.
* Updated `WC_Subscriptions` helper class to handle `wcs_get_order_type_cart_items` calls.
* Updated/added tests to match additions and changes.

#### Testing instructions

For sub switching:

1. Go to WooCommerce > Settings > Subscriptions and enable switching, also setting to prorate recurring payment for upgrades and downgrades.
2. Use or set up a variable sub product that has at least 2 variations with different prices, such as 10/month and 20/month.
3. Sign up for the lower price.
4. Once order is complete, scroll down to use the _View_ option to view the subscription.
5. Use the _Upgrade or Downgrade_ button on the subscription to start the process.
6. Choose the higher priced variation on the product and add to cart.
7. The cart should show the sign up fee as the proper prorated amount to upgrade.

For manual renewals:

1. Go to WooCommerce > Settings > Subscriptions and enable _Accept Early Renewal Payments_.
2. Purchase a subscription, or use existing one. 
3. Go to My Account > Subscriptions, then _View_ a subscription.
4. Click _Renew now_.
5. The cost of the subscription should be the same, meaning not double converted.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

File: tests/unit/multi-currency/test-class-compatibility.php [hunk 1]
```diff
@@ -40,23 +50,220 @@ public function setUp() {
...
+		];
+	}
+
+	public function test_get_subscription_product_price_does_not_convert_price() {
+		$this->mock_utils->method( 'is_call_in_backtrace' )->willReturn( true );
+		$this->mock_wcs_cart_contains_renewal( true );
+		$this->assertSame( 10.0, $this->compatibility->get_subscription_product_price( 10.0, $this->mock_product ) );
+	}
+
+	public function test_get_subscription_product_price_converts_price_test_1() {
```
Comment (dmallory42) [inline tests/unit/multi-currency/test-class-compatibility.php:85]: Would it be possible add a docblock comment for these tests just saying what each individual scenario is checking for, like you've done with the `test_get_subscription_product_signup_fee_does_not_convert_price_*` tests?

**Review by dmallory42 — APPROVED** [review]
LGTM and works well, thanks for all of your work on subscriptions compatibility!

I left one minor comment to consider about tests, but I'm approving this! :shipit:

File: tests/unit/multi-currency/test-class-compatibility.php (hunk 1 above)
Comment (jessepearson) [reply tests/unit/multi-currency/test-class-compatibility.php]: Totally possible, and now done. I initially did that due to I was thinking too hard about it and wanted to describe all of what was happening, looking at it today I was able to conjure up better names.
