### PR TITLE
Don't try load Subscriptions Core when WooCommerce isn't active

### LINKED ISSUE #3265: Fatal error when Wcpay is active but Woo core is not
### Describe the bug

When wcpay is active but woo core isn't an uncaught fatal error is thrown. Likely it's caused by the use of `Automattic\WooCommerce\Admin\PluginsHelper::is_plugin_active()` assuming `Automattic\WooCommerce\Admin\PluginsHelper` is defined.

A simple fix would be to check if `Automattic\WooCommerce\Admin\PluginsHelper` exists or if Woo core / admin is installed.

### To Reproduce

1. Install WooCommerce
2. Install WooCommerce Payments
3. Deactivate WooCommerce

### Actual behavior

An uncaught fatal error is thrown. Something like:
```
Fatal error: Uncaught Error: Class 'Automattic\WooCommerce\Admin\PluginsHelper' not found in {plugins path}/woocommerce-payments/woocommerce-payments.php:131
...
```

### Expected behavior

There shouldn't be a fatal error.

Note that there is already an existing warning when WooCommerce is not active:
```
WooCommerce Payments

WooCommerce Payments requires WooCommerce to be installed and active. Activate WooCommerce
```

### Additional context

Thanks, @htdat, for catching this bug. Thread: p1635759035320500-slack-CGGCLBN58.
He also mentioned there is [a PR](https://github.com/Automattic/woocommerce-payments/pull/3130) to refactor `WC_Payments::check_plugin_dependencies` which might be related to this issue.

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #3265 

#### Changes proposed in this Pull Request

- Don't init `woocommerce-subscriptions-core` if the `Automattic\WooCommerce\Admin\PluginsHelper` class doesn't exist.

When you deactivate the WooCommerce plugin and you have WooCommerce Payments active and the WCPay Subscriptions feature is enabled you get the following fatal error:

```
[02-Nov-2021 05:18:52 UTC] PHP Fatal error:  Uncaught Error: Class 'Automattic\WooCommerce\Admin\PluginsHelper' not found in /Users/matt/local/woo/wp-content/plugins/woocommerce-payments/woocommerce-payments.php:131
Stack trace:
#0 /Users/matt/local/woo/wp-content/plugins/woocommerce-payments/woocommerce-payments.php(134): {closure}('woocommerce-sub...')
#1 /Users/matt/local/woo/wp-content/plugins/woocommerce-payments/woocommerce-payments.php(152): wcpay_init_subscriptions_core()
#2 /Users/matt/local/woo/wp-settings.php(409): include_once('/Users/matt/loc...')
#3 /Users/matt/local/woo/wp-config.php(99): require_once('/Users/matt/loc...')
#4 /Users/matt/local/woo/wp-load.php(50): require_once('/Users/matt/loc...')
#5 /Users/matt/local/woo/wp-admin/admin.php(34): require_once('/Users/matt/loc...')
#6 /Users/matt/local/woo/wp-admin/plugins.php(10): require_once('/Users/matt/loc...')
#7 /Users/matt/.composer/vendor/laravel/valet/server.php(235): require('/Users/matt/loc...')
#8 {main}
  thrown in /Users/matt/local/woo/wp-content/plugins/woocommerce-payments/woocommerce-payments.php on line 131
```

This PR stops this fatal error from occurring by making sure the `Automattic\WooCommerce\Admin\PluginsHelper` class exists before trying to call `PluginsHelper::is_plugin_active()`. If this class doesn't exist, we don't try load Subscriptions Core.

#### Testing instructions

1. Activate WooCommerce and WooCommerce Payments
2. Remove `define( 'WCPAY_TEST_ENV', true );` from wp-config if you have this (this forces `WC_Payments::check_plugin_dependencies()` to always pass true
2. Make sure you have WCPay Subscriptions feature enabled (using WCPay dev tools or set `_wcpay_feature_subscriptions` option to `1`)
3. Go to **WP Admin > Plugins** and deactivate the WooCommerce plugin
4. On `trunk` you'll get fatal error
5. On this branch you won't see any fatal error and will see the following notice:

image

---

Closes #3265

### CODE REVIEW

**Comment by aprea** [comment]
Hey @mattallan,

I'm running into the following error when attempting to activate WooCommerce on this branch.

```
Fatal error: Uncaught Error: Class 'WC_Deprecated_Filter_Hooks' not found
in /var/www/html/wp-content/plugins/woocommerce-payments/vendor/woocommerce/subscriptions-core/includes/deprecated/class-wcs-deprecated-filter-hooks.php on line 23
```

Screen Shot 2021-11-04 at 10 34 37 am

**Steps to reproduce:**
- WooCommerce Payments is active.
- WooCommerce is not active.
- Navigate to `/wp-admin/plugins.php`
- Attempt to activate WooCommerce
- Observe the error above

**Comment by mattallan** [comment]
Hey @aprea Thanks for looking into this one!
Do you have `define( 'WCPAY_TEST_ENV', true )` set on your store by any chance?

This will need to be removed if you do or set it to false.
When this is true the WCPay dependency check function always returns true

**Comment by aprea** [comment]
Hey @mattallan, I don't believe I have that constant defined. I dropped the following into a mu-plugin:

```php
add_action( 'init', function() {
	var_dump( defined( 'WCPAY_TEST_ENV' ) );
	exit;
}, 99 );
```

And it returned `bool(false)`.

And I couldn't find any relevant references to `WCPAY_TEST_ENV` when searching my local codebase.

I also tried explicitly defining that constant to `false` but I still observed the above error.

**Comment by mattallan** [comment]
Ahh, sorry @aprea! I was able to reproduce this by having both WooCommerce and the WooCommerce Admin standalone plugin active and then deactivating WooCommerce.

When WooCommerce is deactivated, WC Admin will also deactivate itself in the same request, however, at this point the PluginsHelper class is still available so Subscriptions Core is still being loaded.

To work around this, I've just changed the approach a little... If `Automattic\WooCommerce\Admin\PluginsHelper` is loaded, fallback to using WordPress' own `is_plugin_active()` function. We're using `is_plugin_active()` to init core in [WC Subscriptions](https://github.com/woocommerce/woocommerce-subscriptions/blob/46f951c59ad00741118d2a0c61dc49aa4c5f6800/woocommerce-subscriptions.php#L201-L205) so i think it's fine to use here as a fallback :)

File: woocommerce-payments.php [hunk 1]
```diff
@@ -106,7 +106,7 @@ function wcpay_init() {
 	 * Initialise subscriptions-core if WC Subscriptions (the plugin) isn't loaded
 	 */
 	function wcpay_init_subscriptions_core() {
-		if ( ! WC_Payments_Features::is_wcpay_subscriptions_enabled() ) {
+		if ( WC_Payments_Features::is_wcpay_subscriptions_enabled() ) {
```
Comment (aprea) [inline woocommerce-payments.php:109]: @mattallan was this change intentional? With this change, I'm no longer able to access subscriptions functionality

**Comment by htdat** [comment]
@aprea and @mattallan - since this PR #3130 has been merged. I think you guys might refactor the current logic here and use the Dependency Service class too, or at least have a follow-up GitHub issue to refactor it later.

File: woocommerce-payments.php (hunk 1 above)
Comment (mattallan) [reply woocommerce-payments.php]: Oh my! No, it wasn't intentional to break everything haha 🙈 Thanks for catching this!!

Comment (mattallan) [reply woocommerce-payments.php]: Fixed in 8d45beb

**Comment by mattallan** [comment]
> I think you guys might refactor the current logic here and use the Dependency Service class too, or at least have a follow-up GitHub issue to refactor it later.

Thanks for the suggestion @htdat, however, I don't think we can use that new service class in this case because loading WCS Core is done before that dependency service exists.

The dependency service class is set up in the `WC_Payments::init()` function call, which is hooked onto the`plugins_loaded` action, but we need to load WCS Core before this because [Subscriptions Core has it's own classes which are inited on `plugins_loaded`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/class-wc-subscriptions-core-plugin.php#L140-L145) 😅

**Comment by aprea** [comment]
@mattallan I'm still running into `Fatal error: Uncaught Error: Class 'WC_Deprecated_Filter_Hooks' not found` on page requests when WooCommerce is deactivated.

Maybe a silly question but I noticed we're not checking whether WooCommerce is active in `wcpay_init_subscriptions_core`, it seems like we're only checking whether `woocommerce-subscriptions` and `woocommerce-subscriptions-core` are active.

Do we need to add a check for WooCommerce here?

**Comment by mattallan** [comment]
😭 Sorry @aprea !! Yeah, you're right.

I'm trying to avoid an issue caused by the order in which plugins are loaded by WP, resulting in `class_exists( 'WooCommerce' )` not always working how we want it to.

For example, if I use the following code:

```
function wcpay_init_subscriptions_core() {
	if ( ! class_exists( 'WooCommerce' ) || ! WC_Payments_Features::is_wcpay_subscriptions_enabled() ) {
		return;
	}

       // Load Subscriptions Core
```

And I rename `wp-content/plugins/woocommerce` to something like `woocommerce-trunk`. This will cause the WooCommerce plugin to load after WC Payments and so the `WooCommerce` class won't exist yet.

I guess this is pretty edge-case so I guess I should focus on fixing the main problem and then look into this other issue later.

I've added a check for WC in 0698f63

File: woocommerce-payments.php [hunk 2]
```diff
@@ -106,7 +106,7 @@ function wcpay_init() {
 	 * Initialise subscriptions-core if WC Subscriptions (the plugin) isn't loaded
 	 */
 	function wcpay_init_subscriptions_core() {
-		if ( ! WC_Payments_Features::is_wcpay_subscriptions_enabled() ) {
+		if ( ! class_exists( 'WooCommerce' ) || ! WC_Payments_Features::is_wcpay_subscriptions_enabled() ) {
```
Comment (aprea) [inline woocommerce-payments.php:109]: `class_exists( 'WooCommerce' )` is returning `false` for me even with WooCommerce active 🤔 This results in subscriptions core not loading.

I wonder if we need to do something similar to line `101` and run `wcpay_init_subscriptions_core` on the `plugins_loaded` hook?

Comment (mattallan) [reply woocommerce-payments.php:109]: Hey @aprea, I've just pushed up a commit which inits subscriptions core on the `plugins_loaded` hook but with priority `0`.

Why priority 0?

WCS Core already hooks onto [`plugins_loaded`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/da32cf1d9073b40ca32d34a9381a9a6d2288aeb3/includes/class-wc-subscriptions-core-plugin.php#L141-L145) and other early hooks like `woocommerce_blocks_loaded` which I believe is hooked onto `plugins_loaded` 9, so we want to make sure Subscriptions Core is inited as early as possible.

I've just gone through the list of action hooks in WCS Core to make sure nothing would be already called/missed now that we're initing on plugins loaded 0 and I couldn't see anything.

Because this is a fairly big change to subscriptions, I also performed some quick smoke tests:
 - Create subscriptions product
 - Purchase a subscription on checkout
 - Test checkout blocks with subscriptions
 - Cancel a subscription
 - Update subscription settings
 - Disable/enable WCPay Subscriptions feature

All were fine ✅ 

Other tests:
 - WooCommerce deactivated 👍 
 - WooCommerce Admin activated + deactive Woocommerce 👍 
 - WooCommerce activated :+1:

**Review by aprea — APPROVED** [review]
LGTM! I tried a bunch of different combinations of activating & deactivating WooCommerce, WooCommerce Payments, WooCommerce Subscriptions and WooCommerce Subscriptions Core.

**Comment by mattallan** [comment]
Thanks @aprea for your patience with this PR haha! I've taken another look at this and I'm happy to merge this as well

Cheers!
