### PR TITLE
Ensure Subscription integration hooks during initialization is only run once

### LINKED ISSUE #5615: With UPE enabled, customers are being charged multiple times for renewal order
### Describe the bug

On the latest version of WC Payments (5.5 - released last week), subscription customers are being charged multiple times for renewal orders. 

The cause of this was introduced in this PR:

- https://github.com/Automattic/woocommerce-payments/pull/3968

As part of that PR, multiple instances of the payment method classes (eg `CC_Payment_Gateway`) are instantiated in each request. Those payment method classes extend `WC_Payment_Gateway_WCPay` and call that base class constructor. That class hierarchy leads to multiple calls of [`$this->maybe_init_subscriptions()`](https://github.com/automattic/woocommerce-payments/blob/trunk/includes/class-wc-payment-gateway-wcpay.php#L386) which hooks onto the `'woocommerce_scheduled_subscription_payment_' . $this->id` hook each time ([code ref](https://github.com/automattic/woocommerce-payments/blob/5.5.0/includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php#L138)). 

For as many `'woocommerce_scheduled_subscription_payment_' . $this->id` functions that are hooked on, there are that many charge requests for renewal orders. For example, with legacy UPE this was 2 (CC + UPE). But with UPE SPlit enabled there were like 8 renewal order charges (CC + all the UPE ones). 

### To Reproduce

1. Enable WC Payments 5.5.0
2.Enable UPE.
3. Enable the WC Subscriptions extension.
_3. Optional. Create a subscription product if you don't have one._ 
4. Purchase the subscription.
5. Go to the edit subscription screen and from the actions drop down, process a renewal order. (see screenshot below).
6. Go to your Stripe dashboard and the transaction list. 
7. Note there are 2 or more charges for the same renewal order ID.

Screenshot 2023-02-27 at 1 27 38 pm

Admin Process renewal action.

### Actual behavior

For every payment method class that extends the `WC_Payment_Gateway_WCPay` class, there's a `$this->maybe_init_subscriptions()` call and that leads to multiple instances WC Payments hooking onto `woocommerce_scheduled_subscription_payment_`. 

For each one of those functions hooked onto that hook, there's a renewal charge being processed.

### Screenshots

Screenshot 2023-02-27 at 1 25 25 pm

Duplicate charges. 

### Expected behavior

A customer should only be charged once for each renewal order.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #5615

#### Changes proposed in this Pull Request

<sup>❗ **Problem description largley copied from https://github.com/Automattic/woocommerce-payments/pull/5619**</sup>

This PR addresses the issue that was discovered in https://github.com/Automattic/woocommerce-payments/issues/5615. In short, the issue was that subscription renewals were being charged multiple times. It was discovered that it was running a separate transaction for as many UPE payment methods that were available + 1. 

We discovered this was due to the fact that the `woocommerce_scheduled_subscription_payment_woocommerce_payments` action was being added for every payment method class. This was happening since each class was ultimately inheriting from `WC_Payment_Gateway_WCPay` which calls `maybe_init_subscriptions()` in it's constructor and each class was calling it's parent constructor within its own constructor.

To address this issue, this PR introduces an early exit criteria to `maybe_init_subscriptions()` which will prevent multiple calls from attaching multiple callbacks. This approach was originally suggested by @hsingyuc [here](https://github.com/Automattic/woocommerce-payments/pull/5619/files#r1119448666).

These callbacks were only intended to be run once, not once for each payment method (including all the UPE ones). What's more, at the current time, it is only intended to run while `woocommerce_payments` is the method ID (via `$this->id`). As has been discussed in these two Slack threads:

- p1677546873476009/1677504529.971689-slack-C04RDE70TUJ
- p1677540409817719/1677504089.424059-slack-C04RDE70TUJ

As UPE support for subscriptions is rolled out, it's possible this will extend to other payment methods with different IDs, however to get ahead of that and to avoid forgetting and reintroducing this duplication, I've also made sure that we only attach the callbacks for the `woocommerce_payments` ID and I've left a comment to be explicit about the care needed if this is broadened in the future.

#### Testing instructions

<sup>❗ **Testing instructions copied from https://github.com/Automattic/woocommerce-payments/pull/5619**</sup>

The following test should all be performed under each of these four scenarios:
- No UPE at all.
- Legacy UPE.
- Split UPE without WooPay.
- Split UPE with WooPay.

1. Configure store for the current scenario you are testing above.
2. If not already present, install the WC Subscriptions plugin and add a subscription product.
3. Go to checkout a subscription product using a CC.
4. Confirm subscription checkout was successful and a subscription was created.
5. Now as merchant admin, go into the subscription that was created and under the subscription actions, choose "Process Renewal" and hit Update.
6. Confirm that the renewal order was created and paid under the subscription order page under "Related Orders".
7. Log into the Stripe dashboard and view the test merchant account's payments and confirm that there is only one charge for the renewal.

After confirmation of the above, run an additional test with a subscription and SEPA.
1. Enable SEPA on your merchant account from the Stripe dashboard.
2. Restart your local WCPay server memcache instance to clear cached account data.
3. Refresh account data on merchant store with the dev tools.
4. Under Payment settings, make sure SEPA is enabled.
5. Checkout with a subscription product and repeat steps 5, 6, and 7 from above.

**Note:** While the scenarios above will cover the primary expected areas of impact, it wouldn't hurt to confirm some processes with WooPay enabled and disabled in non-UPE and legacy UPE as well.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php [hunk 1]
```diff
@@ -75,6 +75,16 @@ class WC_Payment_Gateway_WCPay_Subscriptions_Payment_Method_Order_Note_Test exte
...
 
+	public function tear_down() {
+		parent::tear_down();
+
+		// So that the gateway hooks are re-attached for the next test, we need to reset the flag that prevents the integration hooks from being attached.
+		$reflection = new \ReflectionClass( $this->wcpay_gateway );
+		$property   = $reflection->getProperty( 'has_attached_integration_hooks' );
+		$property->setAccessible( true );
+		$property->setValue( $this->wcpay_gateway, false );
+	}
```
Comment (james-allan) [inline tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php:86]: Any ideas on a better way to handle this? 

Because the `$has_attached_integration_hooks` private static variable is set to `true` when the `maybe_init_subscriptions()` is called and the callbacks are attached, we need to make sure we unset that flag so that the next `WC_Payment_Gateway_WCPay` instance will attach the callbacks again.

Comment (reykjalin) [reply tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php:86]: I'm no expert at unit tests, so not really. Maybe just recreating the test gateway object would be easier to read?

Something like `$this->mock_gateway = new WC_Payments_Gateway( /* ... */ );` might be enough to do the trick 🤔

**Review by reykjalin — APPROVED** [review]
This tests well for me, no issues found; the renewals bug is no longer present.

I do wonder if the static variable truly solves this for all cases? I'm not really sure how to test what happens, for example, if one of the alternative payment methods will support subscriptions in the future 🤔 

Overall this looks good to me though 👍

**Comment by RadoslavGeorgiev** [comment]
@reykjalin this is just a temporary fix, right? This seems like a question we'll only need to answer when we start the refactor.

**Comment by reykjalin** [comment]
> this is just a temporary fix, right? 

I think that's the intent, yes. I just wanted to be explicit that I think this should be a temporary fix, given that we're exploring multiple avenues of addressing the issue and this seems at the surface good enough 🤔 

> This seems like a question we'll only need to answer when we start the refactor

Probably yes. Unless we don't start the refactor immediately and an APM gains subscription support in the meantime, but that's not likely to happen anytime soon ☺️

File: tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php (hunk 1 above)
Comment (timur27) [reply tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php:86]: This small limitation makes me think, why should we define the `$has_attached_integration_hooks` property as static? The goal of this class variable is to provide the information about the state of `WC_Payment_Gateway_WCPay` and I can't think of the use case when we'd need to get the state of this flag without initializing the gateway. 

If we define `$has_attached_integration_hooks` just as a private variable and use getters and setters, this should be more natural and will help us avoid using reflection in tests. Am I missing something? Looking forward to hearing your opinions.

> Obviously, this should not block the PR, but given that the discussion on test design has started, I thought it's worth touching on this topic quickly.

**Comment by shendy-a8c** [comment]
Hi, since this PR has not yet merged, I wonder if it's OK to change the PR's base branch to `trunk`. Discussion: p1677579853660769/1677578222.590459-slack-CGGCLBN58.

**Review by RadoslavGeorgiev — COMMENTED** [review]
Changes look good so far, but when testing with WooPay enabled, fields are not rendered:

image

That's because something's wrong with the JS config:

image

I'm in the process of figuring out why it's happening, will update you once I know.

File: includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php [hunk 2]
```diff
@@ -131,6 +140,19 @@ public function maybe_init_subscriptions() {
...
 		$this->supports = array_merge( $this->supports, $payment_gateway_features );
 
+		/**
+		 * The following callbacks are only attached once to avoid duplication.
+		 * The callbacks are also only intended to be attached for the WCPay core payment gateway ($this->id = 'woocommerce_payments').
+		 *
+		 * If new payment method IDs (eg 'sepa_debit') are added to this condition in the future, care should be taken to ensure duplication,
+		 * including double renewal charging, isn't introduced.
+		 */
+		if ( self::$has_attached_integration_hooks || 'woocommerce_payments' !== $this->id ) {
```
Comment (timur27) [inline includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php:149]: I have a suspicion (haven't checked yet due to some local limitations) - I think this `if` statement will work, but because of the first part only. 

`$this->id` will always return `woocommerce_payments` for any split UPE gateway. This happens because of the wrong sequence of properties initialization. For each payment method, the parent WCPay gateway [initializes the id first here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L202) to be `woocommerce_payments`, then runs `maybe_init_subscriptions()` using this value, and afterward, [sets the id to be the proper one here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-upe-split-payment-gateway.php#L92-L95). Such behavior is wrong and it should be fixed, but I think outside of this PR's scope. 

In [the previous solution](https://github.com/Automattic/woocommerce-payments/pull/5619) we explicitly executed the subscriptions logic from the card gateway, which makes things more clear and correct in the context of the above paragraph. What do you all think about it?

Comment (RadoslavGeorgiev) [reply includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php:149]: The part about the previous solutions that I did not like was that it would have prevented using SEPA for subscriptions, as it would be just the one gateway, which gets subscriptions initialized.

Now I realize that without split-UPE, there is just one gateway. And a couple of seconds ago, I saw that having SEPA enabled makes the account ineligible for split-UPE anyway.

So practically both solutions have the same effect right now.

**Review by RadoslavGeorgiev — APPROVED** [review]
Changes look good to me, thank you!

The only thing I could not test was split-UPE + WooPay + entering a new card, but the same behavior appears in `develop`, so I would not want this to slow down the PR.

**Comment by shendy-a8c** [comment]
To whoever will merge this PR, it's crucial to merge this PR to `trunk`. Read p1677580131148839/1677578222.590459-slack-CGGCLBN58.

I am not sure whether this PR or https://github.com/Automattic/woocommerce-payments/pull/5619 that will be the fix for https://github.com/Automattic/woocommerce-payments/issues/5615. Please let me know.

I also wonder if changing the PR base branch to `trunk` would cause a problem like would all the tests that have been done invalidated etc.

File: tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php (hunk 1 above)
Comment (james-allan) [reply tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php:86]: We need to use a static variable in this case because the `$has_attached_integration_hooks` state needs to be shared across all instances of the trait. 

This is essentially the set up in a rough example. I've created a little example here: https://onlinephp.io/c/f87e6 

Essentially, by using a static variable, all payment method instances will inherit whether any of them have attached the callbacks. By using a standard variable, they wouldn't inherit that knowledge from the other payment method objects.

**Comment by james-allan** [comment]
> To whoever will merge this PR, it's crucial to merge this PR to trunk. Read p1677580131148839/1677578222.590459-slack-CGGCLBN58.

Thanks @shendy-a8c. I've updated the branch to `trunk`.
