### PR TITLE
Add validation for Multi-Currency settings updates (and minor text fixes)

### LINKED ISSUE #6185: Rename "Add currencies" button
Minor issue, but the Add Currencies button could use a name improvement since, after all, it's possible to also _remove_ currencies using it.

Screenshot taken on 2023-05-01 at 19 52 45 UTC@2x

Maybe one of these?

- Add/remove currencies
- Edit currencies list
- Manage currencies

... or similar.

### LINKED ISSUE #6335: Incorrect text in Multi-Currency onboarding wizard related to currency switcher in cart widget
### Describe the bug
The text in the screenshot is wrong. Initially the currency switcher was supposed to be added to the cart widget, however, this never worked. We decided to add it to the Storefront breadcrumb bar, this is what is on the MC settings page:

> Add a currency switcher to the Storefront theme on breadcrumb section.

Screenshot 2023-05-19 at 9 49 13 AM

### To Reproduce

1. You need to update the option `wcpay_multi_currency_setup_completed` in the database to `no`: `wp option update wcpay_multi_currency_setup_completed no`
2. Go to Payments > Overview, scroll down and look for the note with the title "Sell worldwide in multiple currencies"
3. Click the "Set up now" button.
4. On the next page choose a currency and add it to get to step 2.
5. You will now see what is in the above screenshot.

### PR DESCRIPTION
**Pull request by jessepearson**
Fixes #6335 #6185

### Changes proposed in this Pull Request

**Add `InvalidCurrencyException` class**

* This was added to be able to be thrown whenever an invalid currency is used.

**Add `InvalidCurrencyCodeException` class**

* This was added to be able to be thrown whenever an invalid currency code is used.

**Updates to `MultiCurrency` class**

* Add `get_store_currencies` method to return the available, enabled, and default currencies for the store.
* Add `get_single_currency_settings` method to return the settings for a single currency.
* Add `update_single_currency_settings` to update the settings for a single currency.
* Update the `set_enabled_currencies` method to only allow available currencies to be set as enabled. This also makes it so improper data is not able to be stored in the option in the database. These checks include exiting if a string is passed instead of an array, or if anything other than an available currency code is in the passed array.

The additions above allow code to be removed from the `RestController` class and become available for any additional uses.

**Updates to `RestController` class**

* Update REST routes to include `args` that include the passed args along with their type, format, and if they are required. This helps with validation and sanitization.
* Moved some "working/lifting" code to new methods in the `MultiCurrency` class, as mentioned above. This keeps this method more on point and lean.
* Updated all methods to use `rest_ensure_response` to properly return REST responses.
* The `update_enabled_currencies` will check for exceptions and return a proper `WP_Error` if found.

**Updates and additions to unit tests**

* `MultiCurrency` unit tests were updated accordingly.
* Tests were added for the `RestController` class, and one was set to be skipped. This is due to in order to get `available_currencies` the account has to return as connected to WCPay via Jetpack. This is noted in the tests themselves.
  * I tried, for far too long, to try to get the test to work, but I don't believe it is possible. The class being tested doesn't have the `MultiCurrency` class/object passed to it, which means `MultiCurrency` and all objects that build it are not able to be mocked. Since there are no mocks involved, we are not able to make it seem like the test store is connected to WCPay.

**Other updates**

* Fix a couple minor text strings in the admin to solve/fix the issues mentioned above.

### Testing instructions

**Testing the update currencies modal and update currencies button:**

* Activate/include the below snippets on your site.
* Go to WooCommerce > Settings > Multi-Currency.
* Confirm the button to modify currencies reads _Add/remove currencies_ and has the proper "default" button styling.
* Click _Add/remove currencies_ so that the modal opens, you should see _AAA_ at the top of the list.
* Deactivate/remove the snippets on/from your site.
* Select _AAA_ in the modal and click _Update selected_.
* You should get a snackbar notice that says, "Error updating selected currencies"
* You should also get an error logged in your `woocommerce-payments-xxx` log like: "ERROR Invalid currency/currencies passed to set_enabled_currencies: AAA"

Snippets:
```
add_filter( 'wcpay_multi_currency_available_currencies', function( $currencies ) {
	$currencies[] = 'AAA';
	return $currencies;
} );

add_filter( 'woocommerce_currencies', function( $currencies ) {
	$currencies['AAA'] = 'AAA';
	return $currencies;
} );
```

**Testing currencies getting updated via UPE payment methods:**

* Apply patch below.
* Enable UPE.
* Enable P24, and then _Save changes_.
* There should be no errors logged in either the `debug` or `woocommerce-payments-xxx` log , this should silently fail.

Patch:
```diff
diff --git a/client/payment-methods-map.tsx b/client/payment-methods-map.tsx
index 89ef891bc..3b53df396 100644
--- a/client/payment-methods-map.tsx
+++ b/client/payment-methods-map.tsx
@@ -115,7 +115,7 @@ const PaymentMethodInformationObject: Record<
                        'woocommerce-payments'
                ),
                icon: iconComponent( P24Icon, 'Przelewy24 (P24)' ),
-               currencies: [ 'EUR', 'PLN' ],
+               currencies: [ 'EUR', 'PLN', 'AAA' ],
                stripe_key: 'p24_payments',
                allows_manual_capture: false,
        },
diff --git a/includes/payment-methods/class-p24-payment-method.php b/includes/payment-methods/class-p24-payment-method.php
index 73e388e1e..c962e14ca 100644
--- a/includes/payment-methods/class-p24-payment-method.php
+++ b/includes/payment-methods/class-p24-payment-method.php
@@ -26,7 +26,7 @@ class P24_Payment_Method extends UPE_Payment_Method {
                $this->stripe_id   = self::PAYMENT_METHOD_STRIPE_ID;
                $this->title       = 'Przelewy24 (P24)';
                $this->is_reusable = false;
-               $this->currencies  = [ 'EUR', 'PLN' ];
+               $this->currencies  = [ 'EUR', 'PLN', 'AAA' ];
                $this->icon_url    = plugins_url( 'assets/images/payment-methods/p24.svg', WCPAY_PLUGIN_FILE );
        }
 
```

**Testing text during MC onboarding is correct:**

* You need to update the option `wcpay_multi_currency_setup_completed` in the database to `no`: `wp option update wcpay_multi_currency_setup_completed no`
* Go to Payments > Overview, scroll down and look for the note with the title "Sell worldwide in multiple currencies"
* Click the _Set up now_ button.
* On the next page choose a currency and add it to get to step 2.
* You should now see what is in the below screenshot.

Screenshot 2023-06-07 at 1 41 23 PM

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6468` or branch name `add/validation-for-mc-settings` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=add/validation-for-mc-settings) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 5677aae98d6533e7dc3cad2d7e67a904e207b15a
- Build time: 2023-06-20 11:26:43 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by jessepearson** [comment]
I noticed inconsistencies in how REST requests were being handled with sanitization and validation, so I have created more updates in how things are handled. I also moved most of the logic from the RestController to the main MultiCurrency class. I am working on tests for the RestController, which don't currently exist, and I have run out of time.

File: includes/multi-currency/RestController.php [hunk 1]
```diff
@@ -89,95 +140,79 @@ public function register_routes() {
...
-			if ( isset( $params['price_charm'] ) ) {
-				update_option( 'wcpay_multi_currency_price_charm_' . $currency_code, (float) $params['price_charm'] );
-			}
-		}
-
-		return $this->get_currency_settings( $request );
+	public function update_single_currency_settings( $request ) {
+		$currency_code      = $request->get_param( 'currency_code' );
+		$exchange_rate_type = $request->get_param( 'exchange_rate_type' );
+		$price_rounding     = $request->get_param( 'price_rounding' );
```
Comment (tpaksu) [inline includes/multi-currency/RestController.php:197]: `price_rounding` and `price_charm` are expected as `float`s in the method signature of `update_single_currency_settings`, maybe we should ensure that they are converted to a float?

File: tests/unit/multi-currency/test-class-rest-controller.php [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+		// Assert: Confirm the response is what we expected.
+		$this->assertEquals( $expected, $response );
+	}
+
+	/**
+	 * This test uses USD due to that's the only currency available to test with.
+	 * This is due to when MC is initialized it attempts to get the available currencies based on the WCPay server
+	 * connection and account currencies. If there is not a valid JP connection, it just returns the store currency.
+	 */
+	public function test_update_single_currency_settings() {
```
Comment (tpaksu) [inline tests/unit/multi-currency/test-class-rest-controller.php:157]: Maybe we can add an unhappy path for this test.

Comment (tpaksu) [reply tests/unit/multi-currency/test-class-rest-controller.php:157]: Also for the other tests, to see the validation works.

File: includes/multi-currency/MultiCurrency.php [hunk 3]
```diff
@@ -455,6 +456,61 @@ public function get_switcher_widget_markup( array $instance = [], array $args =
...
+	 *
+	 * @param string $currency_code      The single currency code to be updated.
+	 * @param string $exchange_rate_type The exchange rate type setting.
+	 * @param float  $price_rounding     The price rounding setting.
+	 * @param float  $price_charm        The price charm setting.
+	 * @param ?float $manual_rate        The manual rate setting, or null.
+	 *
+	 * @return void
+	 */
+	public function update_single_currency_settings( string $currency_code, string $exchange_rate_type, float $price_rounding, float $price_charm, $manual_rate = null ) {
```
Comment (tpaksu) [inline includes/multi-currency/MultiCurrency.php:513]: Didn't check if we have a protection for that on the UI, but I wonder what will happen if `exchange_rate_type` is `manual` and `manual_rate` is sent as an invalid value, like a string, or `0`?

File: includes/multi-currency/MultiCurrency.php [hunk 4]
```diff
@@ -455,6 +456,61 @@ public function get_switcher_widget_markup( array $instance = [], array $args =
...
+
+	/**
+	 * Gets the currency settings for a single currency.
+	 *
+	 * @param   string $currency_code The currency code to get settings for.
+	 *
+	 * @return  array The currency's settings.
+	 */
+	public function get_single_currency_settings( string $currency_code ): array {
+		$currency_code = strtolower( $currency_code );
```
Comment (tpaksu) [inline includes/multi-currency/MultiCurrency.php:490]: Should we return an error when the currency doesn't exist on the available list?

**Review by tpaksu — CHANGES_REQUESTED** [review]
Thanks for working on this, the code is clean and understandable as always :) I have some questions that needs clarification before starting the manual test. I don't think the code changes will break anything, and I think it'll work as expected without needing a manual test.

File: includes/multi-currency/RestController.php (hunk 1 above)
Comment (jessepearson) [reply includes/multi-currency/RestController.php:197]: This happens within the REST request itself with the addition here: https://github.com/Automattic/woocommerce-payments/pull/6468/files#diff-f5ba94e7313766ad1445e023461ba80603c3abbbe1f8ef0145115dccdda54472R99-R109

The conversion/casting happens here: https://github.com/WordPress/WordPress/blob/6.2.2/wp-includes/rest-api.php#L2795-L2797

We can add the casting back that I removed if you think it is needed.

Comment (tpaksu) [reply includes/multi-currency/RestController.php:197]: Gotcha! Thanks for the context, missed that it's done on the REST validation level.

File: includes/multi-currency/MultiCurrency.php (hunk 3 above)
Comment (tpaksu) [reply includes/multi-currency/MultiCurrency.php:513]: Ok, the string scenario will also be handled by the REST endpoint. The case for 0 is not checked though.

File: tests/unit/multi-currency/test-class-rest-controller.php (hunk 2 above)
Comment (jessepearson) [reply tests/unit/multi-currency/test-class-rest-controller.php:157]: I updated the test to somewhat accommodate for the use case, deletes the option from the database, then allows the method to add it back, and checks that. This was done in https://github.com/Automattic/woocommerce-payments/pull/6468/commits/b95cb5dcaede7900d086aac1daeae14440343dc9

File: includes/multi-currency/MultiCurrency.php (hunk 4 above)
Comment (jessepearson) [reply includes/multi-currency/MultiCurrency.php:490]: Good catch with this, I have made updates to consider that in https://github.com/Automattic/woocommerce-payments/pull/6468/commits/b95cb5dcaede7900d086aac1daeae14440343dc9

File: includes/multi-currency/MultiCurrency.php (hunk 3 above)
Comment (jessepearson) [reply includes/multi-currency/MultiCurrency.php:513]: It looks like currently the UI allows them to submit whatever they want. With [the check added here](https://github.com/Automattic/woocommerce-payments/pull/6468/files#diff-f5ba94e7313766ad1445e023461ba80603c3abbbe1f8ef0145115dccdda54472R99-R102), it makes sure the value is at least numeric. 

I added in a test check to make sure the number was > 0 before updating the option in the database, but that led to another issue. The data in the component gets updated with what's submitted, so the form retains what is submitted, even though that is not what is in the database. I'll have to update it to throw an exception so that the state in the component is not updated.

Comment (jessepearson) [reply includes/multi-currency/MultiCurrency.php:513]: New exception is thrown in https://github.com/Automattic/woocommerce-payments/pull/6468/commits/cd5c60e9e030148abf340e8bad882ccb3747edb0 tests are included in https://github.com/Automattic/woocommerce-payments/pull/6468/commits/5b51410d700310c1c8133b86f5f2a1a45387be3f . Sorry there were two, I wasn't able to get the tests completed on Friday, but wanted to push my changes that were complete.

File: tests/unit/multi-currency/test-class-multi-currency.php [hunk 5]
```diff
@@ -938,6 +985,208 @@ function( $key, $generator, $validator ) {
...
+				'manual_rate'        => null,
+				'price_rounding'     => null,
+				'price_charm'        => null,
+			],
+		];
+	}
+
+	public function test_get_single_currency_settings_throws_exception_on_unavailable_currency() {
+		// Arrange: Set the currencies to change to.
+		$currency_code = 'banana';
```
Comment (tpaksu) [inline tests/unit/multi-currency/test-class-multi-currency.php:1065]: LMAO :)

**Review by tpaksu — APPROVED** [review]
Tested all outlined scenarios, and they work. Actually tested the UPE enabling currencies on activation a bit longer, to see if any logs are added, then I realized "silently" means "no logging" :D And also thanks for expanding the testing scenarios with the failing ones, all LGTM, we can 🚢  it.
