### PR TITLE
Fix fatal errors when `get_product` method returns `null`

### LINKED ISSUE #5906: Payment request button -  Two different fatal error logs
### Describe the bug

For some time, I've seen two errors stemming from the file `includes/class-wc-payments-payment-request-button-handler.php` on Atomic sites. It's not new, but we should take the time to fix them.

Grafana dashboard: [link](https://mc.a8c.com/grafana/d/o7i4CqH4z/wc-pay-additional?orgId=1&var-hvm_blogID=All&var-tag_value=&var-log_level=error&var-e2e_blogID=211482617&var-webhook_url=All&var-last_wcpay_version=5.6.2&var-atomic_logs_severity=Fatal%20error&var-Filters=file%7C%3D%7C%2Fwordpress%2Fplugins%2Fwoocommerce-payments%2F5.6.2%2Fincludes%2Fclass-wc-payments-payment-request-button-handler.php)

## First error

```
PHP Fatal error:  Uncaught Error: Call to a member function needs_shipping() on bool in /wordpress/plugins/woocommerce-payments/5.6.2/includes/class-wc-payments-payment-request-button-handler.php:803
Stack trace:
#0 /wordpress/plugins/woocommerce-payments/5.6.2/includes/class-wc-payments-payment-request-button-handler.php(530): WC_Payments_Payment_Request_Button_Handler->is_product_supported()
#1 /wordpress/plugins/woocommerce-payments/5.6.2/includes/class-wc-payments-payment-request-button-handler.php(158): WC_Payments_Payment_Request_Button_Handler->should_show_payment_request_button()
#2 /wordpress/core/6.2/wp-includes/class-wp-hook.php(308): WC_Payments_Payment_Request_Button_Handler->set_session('')
#3 /wordpress/core/6.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /wordpress/core/6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/core/6.2/wp-includes/template-loader.php(13): do_action('template_redire...')
#6 /wordpress/core/6.2/wp-blog-header.php(19): require_once('/wordpress/core...')
#7 /wordpress/core/6.2/index.php(17): require('/wordpress/core...')
#8 {main}
  thrown in /wordpress/plugins/woocommerce-payments/5.6.2/includes/class-wc-payments-payment-request-button-handler.php on line 803
```

https://github.com/Automattic/woocommerce-payments/blob/e6d1a56ee45dff756b7c0767dbddccf385f27345/includes/class-wc-payments-payment-request-button-handler.php#L789-L834

I think we may just need to use if/elseif to avoid going through all the cases and risk calling a method on a product that is falsy.

## Second error

```
PHP Fatal error:  Uncaught Error: Call to a member function get_type() on bool in /wordpress/plugins/woocommerce-payments/5.6.2/includes/class-wc-payments-payment-request-button-handler.php:1116
Stack trace:
#0 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): WC_Payments_Payment_Request_Button_Handler->ajax_add_to_cart('')
#1 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /wordpress/plugins/woocommerce/7.5.1/includes/class-wc-ajax.php(94): do_action('wc_ajax_wcpay_a...')
#4 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): WC_AJAX::do_wc_ajax('')
#5 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(false, Array)
#6 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/core/6.1.1/wp-includes/template-loader.php(13): do_action('template_redire...')
#8 /wordpress/core/6.1.1/wp-blog-header.php(19): require_once('/wordpress/core...')
#9 /wordpress/core/6.1.1/index.php(17): require('/wordpress/core...')
#10 {main}
  thrown in /wordpress/plugins/woocommerce-payments/5.6.2/includes/class-wc-payments-payment-request-button-handler.php on line 1116
```

https://github.com/Automattic/woocommerce-payments/blob/e6d1a56ee45dff756b7c0767dbddccf385f27345/includes/class-wc-payments-payment-request-button-handler.php#L1101-L1141

For that one, I'm not sure what is going on

### To Reproduce
Unclear

### PR DESCRIPTION
**Pull request by mordeth**
Fixes #5906

#### Changes proposed in this Pull Request
Fixes the fatal errors for the rare cases when the `get_product` method returns `null`.

#### Testing instructions
It is unknown why the `get_product()` method returns `null`, as I cannot reproduce it. Looks like `is_product()` is returning false for specific products due to a third-party plugin or wrong configuration.

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6377` or branch name `fix/5906-request-button-fatal-errors` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/5906-request-button-fatal-errors) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9bd967fa3ef12379a6f10c78d82d0e255456534a
- Build time: 2023-07-04 11:04:27 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 1]
```diff
@@ -686,7 +686,7 @@ public function get_product() {
 			}
 		}
 
-		return false;
+		return null;
```
Comment (anu-rock) [inline includes/class-wc-payments-payment-request-button-handler.php:699]: Should we also update the return type in doc comments for this method?

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 2]
```diff
@@ -790,32 +790,24 @@ private function is_product_supported() {
...
 		$is_supported = true;
 
-		if ( ! is_object( $product ) || ! in_array( $product->get_type(), $this->supported_product_types(), true ) ) {
+		if ( is_null( $product ) ) {
 			$is_supported = false;
-		}
-
-		// Trial subscriptions with shipping are not supported.
-		if ( class_exists( 'WC_Subscriptions_Product' ) && $product->needs_shipping() && WC_Subscriptions_Product::get_trial_length( $product ) > 0 ) {
+		} elseif ( ! is_object( $product ) || ! in_array( $product->get_type(), $this->supported_product_types(), true ) ) {
```
Comment (anu-rock) [inline includes/class-wc-payments-payment-request-button-handler.php]: What do you think about refactoring the whole if-else ladder as:

```php
if ( is_null( $product )
  || ! is_object( $product )
  || ! $this->is_supported_type( $product )
  || $this->is_trial_subscription_with_shipping( $product )
  || $this->product_is_charged_upon_release( $product )
  ...
 ) {
  $is_supported = false;
}
```

**Review by anu-rock — COMMENTED** [review]
I like the approach as it addresses the fatal error issue. But I'd check once with @ricardo as for why `get_product` is currently returning false by default (#1584).
___

#### Review checklist

| Parameter  | Result |
| ------------- | ------------- |
| Approach  | ✅ All good |
| Implementation  | ✅ All good |
| Automated tests  | Not applicable |
| Naming  | Not applicable |
| Typing  | 💬 Left a minor comment |
| Code comments  | ✅ All good |
| Changelog  | ❌ Missing |
| Testing instructions  | Not applicable since it's not known how to reproduce the issue |
| Manual testing  | Not applicable |

File: includes/class-wc-payments-payment-request-button-handler.php (hunk 2 above)
Comment (ricardo) [reply includes/class-wc-payments-payment-request-button-handler.php]: <s>Did we add the `is_null` check only because we changed the default return to `null` in `get_product`?</s>
Edit: Sorry, I focused on Anurag's question and didn't check the PR description.

> But I'd check once with @ricardo as for why get_product is currently returning false by default (https://github.com/Automattic/woocommerce-payments/pull/1584).

I think it's because `wc_get_product` will return `false` by default, so I just followed the same pattern.

File: includes/class-wc-payments-payment-request-button-handler.php (hunk 1 above)
Comment (mordeth) [reply includes/class-wc-payments-payment-request-button-handler.php:699]: No, we shouldn't. The `wc_get_product` method returns `WC_Product|false|null`.

**Review by elazzabi — APPROVED** [review]
Code review looks good ✅

**Review by dpaun1985 — APPROVED** [review]
✅ LGTM  code review only

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 3]
```diff
@@ -790,21 +790,14 @@ private function is_product_supported() {
...
-			$is_supported = false;
-		} elseif ( class_exists( 'WC_Pre_Orders_Product' ) && WC_Pre_Orders_Product::product_is_charged_upon_release( $product ) ) {
-			// Pre Orders charge upon release not supported.
-			$is_supported = false;
-		} elseif ( class_exists( 'WC_Composite_Products' ) && $product->is_type( 'composite' ) ) {
-			// Composite products are not supported on the product page.
-			$is_supported = false;
-		} elseif ( class_exists( 'WC_Mix_and_Match' ) && $product->is_type( 'mix-and-match' ) ) {
-			// Mix and match products are not supported on the product page.
+		if ( ! is_object( $product )
```
Comment (anu-rock) [inline includes/class-wc-payments-payment-request-button-handler.php]: Thanks for accommodating my suggested change :) It looks quite clean now 😄 

Should we restore the clarifying code comments from previews if conditions?

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 4]
```diff
@@ -790,21 +790,14 @@ private function is_product_supported() {
...
+			|| ! is_null( $product )
```
Comment (anu-rock) [inline includes/class-wc-payments-payment-request-button-handler.php]: Shouldn't this be without the not (!) ?

Comment (mordeth) [reply includes/class-wc-payments-payment-request-button-handler.php]: Yes, my bad! Fixed it!

File: includes/class-wc-payments-payment-request-button-handler.php (hunk 3 above)
Comment (mordeth) [reply includes/class-wc-payments-payment-request-button-handler.php]: That makes sense, I will bring back the inline comments.

**Review by anu-rock — APPROVED** [review]
LGTM after the latest changes 🎉
