### PR TITLE
Fix fetch authorization data and wrong capture deadline in the payment details screen.

### LINKED ISSUE #5221: Paid transactions appear as 'Payment authorized' in Transactions details page
### Describe the bug

Paid transactions display a wrong status in the Transactions details page of WP Admin.

### To Reproduce

1. As a shopper, Place an order and [checkout with normal credit card](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#checkout-with-normal-credit-card). Note the order
2. As a merchant, navigate to WP Admin > Payment > Transactions.
3. Click on the row of the order you just placed

### Actual behavior

The status 'chip' shows `Payment authorized`

Screenshot 2022-12-01 at 12 17 21

### Expected behavior

The status 'chip' shows `Paid`

Screenshot 2022-12-01 at 12 21 50

### Additional context

Check fix proposal in this thread: p1669856465693949/1669834642.836459-slack-CGGCLBN58

### LINKED ISSUE #5231: Wrong call to fetch authorization data from the Transaction details for failed payments
### Describe the bug

In the Transactions details page, we inform the merchant of the deadline to capture a payment if it is not still captured. To display this information, we need to call the `/payments/authorizations/` endpoint. This call only makes sense when the payment is set to be manually captured.

After the release of [v5.1.0](https://github.com/Automattic/woocommerce-payments/releases/tag/5.1.0) there are some error traces in the logs caused by fetching authorization data for failed payments marked to be captured **automatically**. Check this Slack thread for more details: p1669933803935859-slack-C46H1UYN4.

The root cause seems to be related to a flaw in the logic that controls if the `/payments/authorizations/` endpoint should be called.

Note that, apart from the 500 error in the Network tab of the browser dev. tools, this error is transparent to the merchant.

### To Reproduce

1. As a shopper, checkout an order using a card that will cause a failed payment. You can use Stripe test card 4000000000009995 (more [info](https://stripe.com/docs/testing#declined-payments)). Please note that you'll see an error in the checkout form but the order will be created in failed state.
2. As a merchant, go to WooCommerce > Orders and find the order you just created. Note the status will be Failed.
3. In the order details page, click on the payment id to go to the transactions details page.
4. Open the Network tab on the browser developer tools

### Actual behavior

You'll see a get request to `payments/authorizations/<payment_intent_id` with a 500 status response

### Screenshots

Screenshot 2022-12-02 at 18 44 21

### Expected behavior

No call to the `payments/authorizations/<payment_intent_id` endpoint, since the payment is not marked to be manually captured.

### PR DESCRIPTION
**Pull request by mgascam**
The previous logic was failing when the payment was in Failed state.

Fixes #5231 #5221

#### Changes proposed in this Pull Request

This change fixes two bugs in the payment details screen related to the manual capture workflow:

* Only fetch authorization data when the payment is set to manual capture. The previous implementation had a bug that was causing to fetch authorization data for failed payments.
Screenshot 2022-12-02 at 18 44 21
    
* Fix wrong hour in the capture deadline caused by missing 'created' information in the front end store.
Screenshot 2022-12-05 at 21 37 49

#### Testing instructions

_Automatic capture_
1. As a shopper, checkout an order using a card that will cause a failed payment. You can use Stripe test card 4000000000009995 (more [info](https://stripe.com/docs/testing#declined-payments)). Please note that you'll see an error in the checkout form but the order will be created in failed state.
2. As a merchant, go to WooCommerce > Orders and find the order you just created. Note the status will be Failed.
3. In the order details page, click on the payment id to go to the transactions details page.
4. Open the Network tab on the browser developer tools
5. Ensure there is no call to the payments/authorizations/<payment_intent_id endpoint, since the payment is not marked to be manually captured.
6. Check that the Payment status is `Paid`.

_Manual capture_
1. Using Merchant account enable Manual capture on Payments > Settings page and save settings. 
2. Follow normal card checkout flow as a Shopper to make a purchase. Take a note of order number created.
3. Using Merchant account go to Payments > Transactions. Check there is an Uncaptured tab next to Transactions tab.
4. Click on Uncaptured tab.
5. In the Uncaptured transactions table, click on the row with the order you created in previous step. It will take you to the payment details page.
6. In the payment details page, check that there is a section that contains information about the capture deadline and a Capture button
7. Check that the date in the capture deadline is correct (add 7 days to date creation)
Screenshot 2022-12-05 at 22 02 33

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) :  'QA Testing Not Applicable'
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by nagpai** [comment]
**Testing - Automatic Capture**

I followed the instruction, and I still seem to be seeing the attempt to fetch and error 500

image

I hope I am not missing  any other setting or step in the test. 

( Leaving the PR status as `needs review` to see if any other colleague gets the same message and to rule out anything going on in my local setup )

**Comment by nagpai** [comment]
**Test - Manual Capture**

Tested and works perfect!

image

File: client/payment-details/summary/index.tsx [hunk 1]
```diff
@@ -113,10 +113,10 @@ const PaymentDetailsSummary = ( {
 		featureFlags: { isAuthAndCaptureEnabled },
 	} = useContext( WCPaySettingsContext );
 
-	// We should only fetch the authorization data if the payment is marked for manual capture
+	// We should only fetch the authorization data if the payment is marked for manual capture and it is not already captured.
 	const shouldFetchAuthorization =
-		charge.amount !== charge.amount_captured &&
-		charge.amount_refunded === 0 &&
+		'captured' in charge && // captured key is only present for manual capture payments. See https://stripe.com/docs/api/charges/object#charge_object-captured
```
Comment (nagpai) [inline client/payment-details/summary/index.tsx]: In my test, I found `captured: false` prop for a failed transaction with manual capture disabled ( automatic capture ) . 

image

We may want to test if the `captured` key is passed on by Stripe , for a failed transaction, even if it is not a manual capture.

Comment (nagpai) [reply client/payment-details/summary/index.tsx]: Advance apologies, if I have missed anything or not done the test correctly.

**Review by nagpai — COMMENTED** [review]
I was still getting the authorization related error for automatic authorization case. I have left a comment related to the same in the code. Pardon me if I have read it wrong.

File: changelog/fix-5231-wrong-call-to-fetch-authorization-data-from-the-transaction-details-for-failed-payments [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Fix wrong capture deadline date in the payment details page.
```
Comment (kalessil) [inline changelog/fix-5231-wrong-call-to-fetch-authorization-data-from-the-transaction-details-for-failed-payments]: Can we expand this a little bit more, so some context is present, please? This is an external communication and we should keep good standards here.

File: client/payment-details/summary/index.tsx (hunk 1 above)
Comment (kalessil) [inline client/payment-details/summary/index.tsx]: Is there an alternative syntax for this? IDK, 'typeof charge.captured !== undefined' or something in that direction?

File: client/payment-details/summary/index.tsx [hunk 3]
```diff
@@ -113,10 +113,10 @@ const PaymentDetailsSummary = ( {
...
+		! charge.captured &&
```
Comment (kalessil) [inline client/payment-details/summary/index.tsx:120]: We lost the check for the refunded amount here, why so?

File: includes/wc-payment-api/models/class-wc-payments-api-charge.php [hunk 4]
```diff
@@ -476,6 +476,7 @@ public function jsonSerialize(): array {
 			'refunded'               => $this->get_refunded(),
 			'refunds'                => $this->get_refunds(),
 			'status'                 => $this->get_status(),
+			'captured'               => $this->is_captured(),
```
Comment (kalessil) [inline includes/wc-payment-api/models/class-wc-payments-api-charge.php]: Can we move it before 'refunded' please?

**Review by kalessil — CHANGES_REQUESTED** [review]

File: client/payment-details/summary/index.tsx (hunk 1 above)
Comment (mgascam) [reply client/payment-details/summary/index.tsx]: No need to apologyze, you are 100% true. I misunderstood the Stripe docs here https://stripe.com/docs/api/charges/object#charge_object-captured. So I thought that the captured key would only be present in manual capture, but that is not the case. This means it is not enough to check for the presence of captured, we need to explicitly exclude:
* Failed charges
* Refunds

Thanks for catching it!

Comment (mgascam) [reply client/payment-details/summary/index.tsx]: For the record, I was thinking that the captured key will only be present in the object for manually captured payments, but I was wrong. Please check the comment above.

That's why I was using the "in" operator, but as I said this is pointless. Anyway thanks for the hint, I'll think twice before using it again, as it seems not to be readable.

File: changelog/fix-5231-wrong-call-to-fetch-authorization-data-from-the-transaction-details-for-failed-payments (hunk 2 above)
Comment (mgascam) [reply changelog/fix-5231-wrong-call-to-fetch-authorization-data-from-the-transaction-details-for-failed-payments]: Thanks, I hope it is better like this? [c5b2e48](https://github.com/Automattic/woocommerce-payments/pull/5232/commits/c5b2e483f969fcfbce322c23edea33a2ebdd86d0)

File: client/payment-details/summary/index.tsx (hunk 3 above)
Comment (mgascam) [reply client/payment-details/summary/index.tsx:120]: I was mistaken and thought that checking for `captured` would be enough. Added it back.

Comment (mgascam) [reply client/payment-details/summary/index.tsx:120]: Done here [c5b2e48](https://github.com/Automattic/woocommerce-payments/pull/5232/commits/c5b2e483f969fcfbce322c23edea33a2ebdd86d0)

File: includes/wc-payment-api/models/class-wc-payments-api-charge.php (hunk 4 above)
Comment (mgascam) [reply includes/wc-payment-api/models/class-wc-payments-api-charge.php]: Done here [c5b2e48](https://github.com/Automattic/woocommerce-payments/pull/5232/commits/c5b2e483f969fcfbce322c23edea33a2ebdd86d0)

File: changelog/fix-5231-wrong-call-to-fetch-authorization-data-from-the-transaction-details-for-failed-payments (hunk 2 above)
Comment (kalessil) [reply changelog/fix-5231-wrong-call-to-fetch-authorization-data-from-the-transaction-details-for-failed-payments]: Yes!

**Review by kalessil — APPROVED** [review]
LGTM!

**Comment by kalessil** [comment]
Hey @nagpai :wave: Can you give a try to new testing round, please?

File: client/payment-details/summary/index.tsx (hunk 1 above)
Comment (nagpai) [reply client/payment-details/summary/index.tsx]: The changes look good, and are testing correctly now. Thanks, @mgascam 🙌 

LGTM!

**Review by nagpai — APPROVED** [review]
LGTM! 

The tests are passing and the code looks good too 👍
