### PR TITLE
Transaction detail render customer with falling back to order details

### LINKED ISSUE #7740: In-Person Payment: transaction details are not rendering customer details corerctly
### Describe the bug

`PaymentDetailsSummary` component when renders `CustomerLink` supplying customer data from `charge.billing_details`. When billing details are not provided (In-Person Payments), the customer shall be rendered based on `charge.order` as fallback. Client shall also inject `customer_email` and `customer_name` into `charge.order` as well (currently, we have only `customer_url` what's not enough for the fallback) based on order meta-data (`customer_email`, `customer_name`, which In-Person Payments do provide).

### PR DESCRIPTION
**Pull request by kalessil**
Fixes #7740 

#### Changes proposed in this Pull Request

When rendering transaction details, use order details as fallback to charge billing details for rendering customer details.

#### Testing instructions

* in `client/payment-details/summary/index.tsx` find usage of `CustomerLink` and simulate missing billing details with `billing_details={ null }`
* rebuild the client and open any transaction details, ensure customer name is rendered without changes

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7757` or branch name `fix/7740-transaction-detail-render-customer-name-fallback` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7740-transaction-detail-render-customer-name-fallback) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: a9148737504ac2760e46376b158eb53e3458026a
- Build time: 2023-11-22 14:12:39 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/components/customer-link/index.tsx [hunk 1]
```diff
@@ -13,20 +13,26 @@ import { getAdminUrl } from 'wcpay/utils';
 import { ChargeBillingDetails } from 'wcpay/types/charges';
 
 const CustomerLink = ( props: {
-	customer: null | ChargeBillingDetails;
```
Comment (mgascam) [inline client/components/customer-link/index.tsx:16]: ❤️

**Review by mgascam — APPROVED** [review]
LGTM! I followed testing instructions an works as intended.
