### PR TITLE
Fix non-rendering PMME container on cart block for specific scenario

### LINKED ISSUE #10448: PMME not updating on cart block
### Describe the bug
PMME is not shown when opening the page when the cart total is outside the limits for the BNPL (e.g. less than $50 for Affirm), and then entering the limit by e.g. increasing the quantity. 

### To Reproduce

1. Enable Affirm
2. Add products to the cart for total less than $50
3. Go to cart block
4. No PMME for Affirm (expected)
5. Increase the quantity for cart total to be >= $50
6. No PMME for Affirm (unexpected) 

### Expected behavior
PMME is initialized on cart block similarly to other pages (shortcode cart and product page) when entering the limits for a payment method.

### PR DESCRIPTION
**Pull request by timur27**
Fixes https://github.com/Automattic/woocommerce-payments/issues/10448

#### Testing instructions

> 1️⃣  Enable Affirm in your store
> 2️⃣  Ensure the country used in checkout is a country that supports Affirm (e.g. United States)

##### From below-the-limit to within-the-limit
* add a product with the price lower than $50 to the cart 
* open the _**cart block**_ and confirm no PMME on the page
* start increasing the quantity of the product in the cart so that the cart total is >= $50
* confirm PMME appears on the page
* go in/out the limit by changing the quantity and confirm expected dynamic PMME render

##### From within-the-limit to below-the-limit
* add multiple products to the cart so that the total is $50 or higher
* confirm PMME appears on the cart block page
* decrease the quantity/remove some products from the cart
* confirm that PMME disappears once the cart total is lower than $50

> Change the checkout country to an unsupported one (e.g. Poland)

* navigate to the cart block page and confirm no user or console errors
* change the quantity to enter/exit the $50 cart total limit and confirm the PMME is not appearing (due to unsupported country) and no errors

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10455` or branch name `fix/pmme-on-cart-block` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/pmme-on-cart-block) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: bbf4ff7836471e3669a76cd007771e0b9356ab5b
- Build time: 2025-02-27 13:51:58 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/cart/blocks/index.js [hunk 1]
```diff
@@ -2,26 +2,10 @@
  * Internal dependencies
  */
 import { renderBNPLCartMessaging } from './product-details';
-import { getUPEConfig } from 'wcpay/utils/checkout';
 
 const { registerPlugin } = window.wp.plugins;
 
-const paymentMethods = getUPEConfig( 'paymentMethodsConfig' ) || {};
```
Comment (timur27) [inline client/cart/blocks/index.js:9]: I think using payment methods config as a filter is redundant here because we have enough flags in `client/cart/blocks/product-details.js` checking whether to show/initialize the PMME based on other (similar) limits/country logic [coming from the PMME class on the back end](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-payment-method-messaging-element.php#L145-L149). I think this needs to be refactored and I've raised that in p1740588909669789-slack-CU6SYV31A, so that this can be addressed at the right time given multiple refactors currently ongoing

**Review by gpressutto5 — APPROVED** [review]
Works as expected!
