### PR TITLE
Display errors from WC form when using UPE.

### LINKED ISSUE #1961: UPE Error handling on processCheckout flow
When checking out with UPE and providing some invalid data in the regular WC checkout fields, the error message displayed is too generic and missing some details.

**To Reproduce**
- With UPE enabled, go to perform a checkout.
- Provide an invalid postal code in the WC fields and all valid data in the UPE fields.
- Click Place Order
- Get error message: `Error submitting form! undefined: undefined.`

UPE-Checkout-Error

This error is being thrown from the [processCheckout call](https://github.com/Automattic/woocommerce-payments/blob/daa8389c91e3867cd059e5446e27b58ad5b15e4e/client/checkout/api/index.js#L338). The API response contains the error message as markup in the response as shown in the image below.

UPE-checkout-error-response

### PR DESCRIPTION
**Pull request by brezocordero**
Fixes #1961 

#### Changes proposed in this Pull Request

Display errors on checkout coming from WooCommerce form and UPE form when using UPE.

For consistency with other functions, I have changed `processCheckout` to return the error message inside of an object with the `message` property.

#### Testing instructions

* With UPE Enabled, add a product to the cart and go to checkout.
* Select UPE as payment method, leave some of the fields incomplete, click on 'Place Order'
* Check UPE errors are displayed
* Fill out all UPE fields, remove the zip code from WooCommerce form
* Click on 'Place Order'
* Check that WooCommerce error message for that field is displayed.
ZipCodeError

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

File: client/checkout/api/index.js [hunk 1]
```diff
@@ -344,12 +344,12 @@ export default class WCPayAPI {
 		} )
 			.then( ( response ) => {
 				if ( 'failure' === response.result ) {
-					throw response.messages;
+					throw { message: response.messages };
```
Comment (brezocordero) [inline client/checkout/api/index.js:347]: If there is a specific object type to use here, happy to change it. I couldn't find any other example wrapping up the message.

Comment (FangedParakeet) [reply client/checkout/api/index.js:347]:
```suggestion
					throw new Error( response.messages );
```

I think since `response.messages` will be a string in this situation, you could throw a JS Error instead and `showError` would be able to unpack the string from the error's `message` property. Works for me when I tested it and might look a little cleaner, but I leave it in your hands.

File: client/checkout/api/index.js [hunk 2]
```diff
@@ -344,12 +344,12 @@ export default class WCPayAPI {
...
 				}
 				return response;
 			} )
 			.catch( ( error ) => {
-				throw `Error submitting form! ${ error.status }: ${ error.statusText }.`;
+				throw error;
```
Comment (FangedParakeet) [inline client/checkout/api/index.js:352]:
```suggestion
				if( error.message ) {
				    throw error;
				} else {
				    throw new Error( `Error submitting form! ${ error.status }: ${ error.statusText }.` );
				}
```
Currently, just throwing the error here is a little redundant, so we don't really need to have this catch block. 

However, @superdav42 noticed that if this AJAX request times out or returns a `500` for some reason, then the `request` function rejects and the error thrown is a [jqxhr object](https://api.jquery.com/jQuery.ajax/#jqXHR) instead of the error object we would expect from `wp_send_json_error`. You can test this by using the debugger to cause a timeout or simply putting some broken code inside the `process_payment` function that will force the response to be a `500` error. 

I implemented that previous `Error submitting form!` message, using the `error.status` and `error.statusText` properties to handle this case. You're welcome to come up with a more user friendly error message than the one I used though! I think this case is necessary though, because otherwise a server error here just leaves JS errors in the console and doesn't tell the user that something has gone wrong.

I think similar logic to this should also probably be implemented around the `createIntent` function as well.

**Review by FangedParakeet — CHANGES_REQUESTED** [review]
I suggested a few changes here--basically the AJAX request error handling here breaks if the server fails to respond or responds with a server error.

Also, I noticed one other thing that doesn't involve your changes, but I think it would be nice if you could fix as well! [This exception](https://github.com/Automattic/woocommerce-payments/blob/88ef5d4eabbfd5f647b84cc56b56f05188f285a8/includes/payment-methods/class-upe-payment-gateway.php#L67) inside the `create_payment_intent_ajax` function causes the code to break and the server to respond with a `500` status. Either we need to remove the second parameter to the `Exception` constructor (`wcpay_upe_intent_error`) or we need to use `Process_Payment_Exception` instead, which takes a string error code as its second parameter. I think this is the only place in the code where I could find this problem.

File: client/checkout/api/index.js (hunk 2 above)
Comment (brezocordero) [reply client/checkout/api/index.js]: I have added the case, thanks for pointing it out!

File: client/checkout/api/index.js (hunk 1 above)
Comment (brezocordero) [reply client/checkout/api/index.js]: Done!

**Comment by brezocordero** [comment]
> I noticed one other thing that doesn't involve your changes, but I think it would be nice if you could fix as well

Of course!

> or we need to use Process_Payment_Exception instead, which takes a string error code as its second parameter.

I used `Process_Payment_Exception`, same as in `process_redirect_payment`.

File: client/checkout/api/index.js [hunk 3]
```diff
@@ -320,12 +320,21 @@ export default class WCPayAPI {
...
+					throw response.data.error;
+				}
+				return response.data;
+			} )
+			.catch( ( error ) => {
+				if ( error.message ) {
+					throw error;
+				} else {
+					// Covers the case of error on the Ajax request.
+					throw new Error( error.statusText );
```
Comment (FangedParakeet) [inline client/checkout/api/index.js:335]: Lovin' it: this actually looks like it gets formatted pretty nicely inside `showError`, so happy days.

**Review by FangedParakeet — APPROVED** [review]
Cheers for sorting out all the suggestions I made! Looks tip top to me now: even printing the WC AJAX status error ends up looking pretty neat and tidy on the front end. Here are all the points I tried breaking the code.

- Throwing error with incomplete UPE fields
- Throwing error with incomplete checkout fields 
- Throwing error while creating payment intent
- Throwing error while completing checkout
- Throwing error while processing payment
- Throwing error while server implodes

Everything had a pretty little error and looks good to me. I also ran through a successful checkout with and without a saved payment method, just to make sure it's not all doom and gloom, and that worked fine too.

Love it. Merge it.
