### PR TITLE
Fix UPE missing international card fee

### LINKED ISSUE #2804: UPE causes incorrect fee calculation
### Describe the bug
When using UPE, fee calculation is wrong.

### To Reproduce

1. Use US store (might happen for other country as well).
2. Purchase something with CA card, `4000001240000000`, in USD presentment currency (might happen for other currency as well).
3. Notice the fee is wrong even though percentage and fixed fee are displayed correctly.

### Actual behavior
Fee is `3.2`.
Net is `96.8`.

### Screenshots
image (1)

### Expected behavior
Fee should be `4.2` instead of `3.2`.
Net should be `95.8` instead of `96.8`.

### Additional context
p1629978489004400-slack-CGGCLBN58

### PR DESCRIPTION
**Pull request by ismaeldcom**
Fixes #2804

#### Changes proposed in this Pull Request
- Enable `card_country_event_beta_1` to receive the card country on the Payment Element `change` event.
- Capture the country on every `change` event and update the intent. Using a hidden input in the classic checkout and state in the blocks one.
- Send it to the server if available.

More context on the applied solution on paJDYF-2yJ-p2

#### Testing instructions
ℹ️ You need to checkout the server branch `fix/upe-international-fees` to test it.

It's a bit tricky to test, cause as [Stripe already mentioned here: p1632154471189300/1630001570.005200-slack-C9976E5MJ, test cards don't return the appropriate country. We can mimic the correct behaviour editing the value of `wcpay_payment_country` on the classic checkout.

##### Fees apply correctly
- Use a US store.
- Make a purchase using an international card like BR `4000000760000002` and updating the value of the `wcpay_payment_country` input to `BR`.
- Look at the transaction and check that the applied fee amount is ok.

##### Country properly captured
- Input the first 6 digits of a non-test known country card in the classic checkout, for example `494019` for Spain.
- Confirm that the `wcpay_payment_country` input value is right, `ES` for the previous example.

#### Screenshots
| Before | After |
|-|-|
|Screenshot 2021-09-23 at 11 13 42|Screenshot 2021-09-23 at 11 13 52|

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-upe-payment-gateway.php [hunk 1]
```diff
@@ -134,8 +134,9 @@ public function update_payment_intent_ajax() {
 			$payment_intent_id         = isset( $_POST['wc_payment_intent_id'] ) ? wc_clean( wp_unslash( $_POST['wc_payment_intent_id'] ) ) : '';
 			$save_payment_method       = isset( $_POST['save_payment_method'] ) ? 'yes' === wc_clean( wp_unslash( $_POST['save_payment_method'] ) ) : false;
 			$selected_upe_payment_type = ! empty( $_POST['wcpay_selected_upe_payment_type'] ) ? wc_clean( wp_unslash( $_POST['wcpay_selected_upe_payment_type'] ) ) : '';
+			$payment_country           = ! empty( $_POST['wcpay_payment_country'] ) ? wc_clean( wp_unslash( $_POST['wcpay_payment_country'] ) ) : '';
```
Comment (bborman22) [inline includes/payment-methods/class-upe-payment-gateway.php:137]: Since we're defaulting to null in the function parameters, I was wondering if we should use null here as well? Or the other way around and use the empty string as the default parameter value? I don't think it will make any difference, but was just thinking it could be nice to keep with the same default in each scenario?

File: includes/payment-methods/class-upe-payment-gateway.php [hunk 2]
```diff
@@ -335,6 +338,7 @@ public function process_payment( $order_id ) {
 		$token                     = Payment_Information::get_token_from_request( $_POST ); // phpcs:ignore WordPress.Security.NonceVerification.Missing
 		$selected_upe_payment_type = ! empty( $_POST['wcpay_selected_upe_payment_type'] ) ? wc_clean( wp_unslash( $_POST['wcpay_selected_upe_payment_type'] ) ) : ''; // phpcs:ignore WordPress.Security.NonceVerification.Missing
 		$payment_type              = $this->is_payment_recurring( $order_id ) ? Payment_Type::RECURRING() : Payment_Type::SINGLE();
+		$payment_country           = ! empty( $_POST['wcpay_payment_country'] ) ? wc_clean( wp_unslash( $_POST['wcpay_payment_country'] ) ) : ''; // phpcs:ignore WordPress.Security.NonceVerification.Missing
```
Comment (bborman22) [inline includes/payment-methods/class-upe-payment-gateway.php:341]: Same note as above.

**Review by bborman22 — APPROVED** [review]
This worked exactly as expected for me. I tested with shortcode and block checkouts and used a few different combinations of card numbers to determine that the country was being set correctly at the right times.

I just had one very minor note about the default value of the `payment_country` and whether it should be null or empty string. It is very minor and I wouldn't hold the PR back for it so still approving. I also think this PR can add a changelog and readme entry for this  addition.

LGTM!

File: includes/payment-methods/class-upe-payment-gateway.php (hunk 1 above)
Comment (ismaeldcom) [reply includes/payment-methods/class-upe-payment-gateway.php]: Thanks for catching that @bborman22! I missed it after switching between null and empty string a couple of times.
*Addressed in b205d96*
