### PR TITLE
Automatically disable Link when WooPay is also enabled

### LINKED ISSUE #5648: Can't disable WooPay or Link after upgrading to 5.5
### Describe the bug
Merchants that had Link active and migrated to WC Payments 5.5 and got WooPay auto enabled can't use any of those methods because one needs the other to be disabled but as both are enabled it's not possible do disable any of them.

slack link: p1677604444196419-slack-C022WMN88KG

### To Reproduce
- Enable UPE and Split UPE via Dev Tools
- Enable WooPay and Link at the same time. To allow this, remove [these lines](https://github.com/Automattic/woocommerce-payments/blob/trunk/client/settings/express-checkout/index.js#L82-L107) and [these lines](https://github.com/Automattic/woocommerce-payments/blob/trunk/client/settings/express-checkout/index.js#L325-L350)
- Now revert the changes in the code
- Reload the settings page and you should see the following

https://user-images.githubusercontent.com/6342964/221988548-2e7aca8a-f957-4962-90b7-71388cf38b50.mov

### Expected behavior
When both WooPay and Link are enabled at the same time we should disable Link and keep WooPay enabled. Later the merchant can choose between WooPay or Link.

### PR DESCRIPTION
**Pull request by leonardola**
Fixes #5648

#### Changes proposed in this Pull Request
This PR disables Link when WooPay is active. To allow merchants to later choose between WooPay or Link.

#### Testing instructions
- While on `trunk` branch
- Enable UPE and Split UPE via Dev Tools
- Enable WooPay and Link at the same time. To allow this, remove [these lines](https://github.com/Automattic/woocommerce-payments/blob/trunk/client/settings/express-checkout/index.js#L82-L107) and [these lines](https://github.com/Automattic/woocommerce-payments/blob/trunk/client/settings/express-checkout/index.js#L325-L350)
- Now revert the changes in the code
- Reload the settings page and you should see the following

https://user-images.githubusercontent.com/6342964/221988548-2e7aca8a-f957-4962-90b7-71388cf38b50.mov

- Checkout to this PR branch and [re]load any page
- Now Link should be inactive and it is now possible do disable WooPay and then enable Link if necessary.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: includes/class-wc-payments.php [hunk 1]
```diff
@@ -560,14 +560,24 @@ public static function get_plugin_headers() {
 	 */
 	public static function register_gateway( $gateways ) {
 		if ( WC_Payments_Features::is_upe_split_enabled() ) {
+
+			$payment_methods = self::$card_gateway->get_payment_method_ids_enabled_at_checkout();
+
+			if ( in_array( 'link', $payment_methods, true ) && self::$platform_checkout_button_handler->is_woopay_enabled() ) {
+				$key = array_search( 'link', $payment_methods, true );
```
Comment (alefesouza) [inline includes/class-wc-payments.php]:
```suggestion
			$key = array_search( 'link', $payment_methods, true );

			if ( $key !== false && self::$platform_checkout_button_handler->is_woopay_enabled() ) {
```

As `array_search` returns false if a value doesn't exists in the array, wouldn't be better to use it to check if the key exists?

**Review by alefesouza — APPROVED** [review]
It works as expected and code looks good to me, just a simple suggestion that does not block anything.
