### PR TITLE
Fix new user not being saved in platform

### LINKED ISSUE #5784: New WooPay user doesn't get created even when checking the save my information for a faster and secure checkout box
### Describe the bug
On the WooPay site, the new user doesn't get created after going through the checkout process and checking the `Save my information for a faster and secure checkout` box on the checkout page.  

### To Reproduce
1. Purchase a product as a new user
2. Make sure to add the country code for the phone number (ex.+14706629035)
3. Check the `Save my information for a faster and secure checkout` box
4. Go to WooPay site and search for the new user
5. See the new user can not be found

### Actual behavior
The new user doesn't get created.

### Expected behavior
The new user should get created.

### PR DESCRIPTION
**Pull request by hsingyuc**
Fixes #5784 

#### Changes proposed in this Pull Request
Add the `set_save_payment_method_to_platform` to the `WooPay_Create_And_Confirm_Intention`

#### Testing instructions
1. Purchase a product as a new user
2. Make sure to add the country code for the phone number (ex.+14706629035)
3. Check the `Save my information for a faster and secure checkout` box
4. Go to WooPay site and search for the new user
5. See the new user gets created

*

-------------------

- [X] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Review by leonardola — APPROVED** [review]
Looks good. User was created as expected

File: includes/core/server/request/class-woopay-create-and-confirm-intention.php [hunk 1]
```diff
@@ -34,4 +34,13 @@ public function set_has_woopay_subscription( $has = true ) {
 		$this->set_param( 'woopay_has_subscription', $has );
 	}
 
+	/**
+	 * Save payment method to platform.
+	 *
+	 * @param bool $save save payment method to platform.
+	 */
+	public function set_save_payment_method_to_platform( $save = true ) {
+		$this->set_param( 'save_payment_method_to_platform', $save );
```
Comment (ricardo) [inline includes/core/server/request/class-woopay-create-and-confirm-intention.php:44]: I guess this doesn't affect functionality, but we should probably add `save_payment_method_to_platform` to the `DEFAULT_PARAMS` const, similar to the [WooPay_Create_And_Confirm_Setup_Intention](https://github.com/Automattic/woocommerce-payments/blob/fe3e25719fac9f2817612c96ab103a1d5e8613b3/includes/core/server/request/class-woopay-create-and-confirm-setup-intention.php#L17) class.

Also noticed that in `WooPay_Create_And_Confirm_Setup_Intention` the const is named `DEFAULTS` instead of `DEFAULT_PARAMS` as in other classes, so maybe a minor suggestion for improvement.

**Review by ricardo — APPROVED** [review]
LGTM. Thanks for fixing this!
