### PR TITLE
Add stripe account id to the product id metadata to fix the issue when stripe account id changes.

### LINKED ISSUE #3269: Using product IDs after moving/changing WCPay connect accounts
### Describe the bug

It's currently possible to have product IDs stored in the database that aren't linked to the current WCPay Connect account. This can happen in any number of ways. I've included what I believe to be two possible scenarios below. 

1. Merchant connects to WC Pay, creates a subscription product on account, disconnects from WC Pay, re-onboards and creates a new account. The customer attempts to make a purchase of the product using that new account. 
2. A store is set up on a staging/demo site, a subscription product is created, the site is migrated/deployed/goes live, the merchant re-onboards to WCPay on the live site. The database was migrated from the demo site and so WC Pay product IDs copy over. The customer attempts to purchase the product. 

In both cases, a product ID linked to 1 WCPay account is used with a different WCPay account and results in the following error.

```
No such product: 'prod_KVUN2p9l83HkTO'
```

### To Reproduce

I'm not 100% sure how to reliably replicate this issue following a real-world set of steps. The steps below are a way of illustrating how this might happen. I've also based the above 2 scenarios after observing the error logs in logstash. 

To replicate I: 

1. Created a new JN site. 
2. Installed and activated WooCommerce, WooCommerce Payments and WCPay Dev Tools.
3. Onboarded to WC Payments. 
4. Created a Subscription product. 
5. Went into WCPay Dev from the WP admin checked the box to force re-onboarding. 
6. Reonboard to WC Pay. 
7. After onboarding for a second time attempt to purchase the product. 
8. You should get the error above. 

### Expected behavior

When a site moves WCPay accounts existing any product IDs created on a different account should be deleted or some validation should occur to make sure the product ID is still valid for this account.  

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by zmaglica**
Fixes #3269  

#### Changes proposed in this Pull Request  

When a new product is created, we call the Products API to store it on the server. The issue arises when a client re-onboards or switches to a different Stripe account, making previously created product IDs invalid.  

This PR resolves the issue by linking product IDs to their associated Stripe accounts. Now, when a product is created, the plugin calls the API to create the product on the server, which returns an ID. This ID is stored along with the corresponding Stripe account ID. When retrieving a product from metadata or options, the plugin verifies whether the stored product ID belongs to the current Stripe account.  

Product IDs are stored in both product metadata and the options table, depended on the type of product:
- **Product meta**: A new meta key now stores the Stripe account ID.
- **Options table**: Instead of using a meta key like we did in products meta, product IDs and Stripe account IDs are stored as an array in a single metakey.  

#### Note

The tests are not added yet. They will be added once we confirm that this approach is applicable.

#### Testing instructions  

1. Make sure that your server branch is on this PR: https://github.com/Automattic/transact-platform-server/pull/7336 or that PR is merged.  
3. Ensure you have a subscription and a shipping option with a cost.  
4. Add a subscription product and proceed with payment.  
5. Re-onboard your account.  
6. Add the same subscription product and complete the payment.  
7. Previously, this would trigger a "product not found" error. With this change, the subscription purchase should proceed without errors.  

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10562` or branch name `fix/3269-add-account-id-to-product-id-metadata` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/3269-add-account-id-to-product-id-metadata) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 572e10c6b2ea0713ca707a8fd06a5b1c335a2b53
- Build time: 2025-03-25 16:28:02 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 1]
```diff
@@ -274,20 +355,22 @@ public function create_product( WC_Product $product ) {
...
 	 */
-	public function create_product_for_item_type( string $type ) {
-		try {
-			$wcpay_product = $this->payments_api_client->create_product(
-				[
-					'description' => 'N/A',
-					'name'        => ucfirst( $type ),
-				]
-			);
+	public function create_product_for_item_type( string $type, string $stripe_account_id ): array {
```
Comment (htdat) [inline includes/subscriptions/class-wc-payments-product-service.php]: 1. I think $stripe_account_id can be fetched from `$this->account->get_stripe_account_id()` so I don't think we need to have a new extra param here. 

2. This method is currently being used in this class only so we can mark it as `private` too.

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 2]
```diff
@@ -162,15 +209,48 @@ public static function sanitize_option_key( string $type ) {
...
+			// Product exists, update metadata with current account.
+			if ( ! empty( $product_data ) ) {
+				$product->update_meta_data( $option_key . '_linked_to', $current_account_id );
+				$product->save();
+				return true;
+			}
+
+			return false;
+		} catch ( \Exception $e ) {
+			Logger::log( 'Error validating WCPay product: ' . $e->getMessage() );
```
Comment (htdat) [inline includes/subscriptions/class-wc-payments-product-service.php]: Maybe should log more details such as `$wcpay_product_id, $wcpay_account_id, $product->id`.

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 3]
```diff
@@ -162,15 +209,48 @@ public static function sanitize_option_key( string $type ) {
...
+		$option_key       = self::get_wcpay_product_id_option( $test_mode );
+		$wcpay_product_id = $product->get_meta( $option_key );
+
+		// No product ID exists.
+		if ( empty( $wcpay_product_id ) ) {
+			return false;
+		}
+
+		// Check if we have the linked account metadata.
+		$linked_account_id  = $product->get_meta( $option_key . '_linked_to' );
```
Comment (htdat) [inline includes/subscriptions/class-wc-payments-product-service.php]: I think we should have the same method like `self::get_wcpay_product_id_option` to get the Stripe account ID. Probably, and the key may be something like`_wcpay_linked_stripe_account_id_live` and `_wcpay_linked_stripe_account_id_test`

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 4]
```diff
@@ -124,31 +133,69 @@ public static function get_wcpay_product_hash( WC_Product $product ): string {
...
+				// Validate that the product exists for the current account.
+				$existing_product = $this->payments_api_client->get_product_by_id( $product );
+
+				if ( $existing_product ) {
+					// Product exists, migrate to new format.
+					$product = [
+						'wcpay_product_id'  => $existing_product['wcpay_product_id'],
+						'stripe_account_id' => $stripe_account_id,
+					];
+					update_option( $option_key_name, $product );
```
Comment (htdat) [inline includes/subscriptions/class-wc-payments-product-service.php]: I am trying to understand if there is any specific con or issue with having another option to just save for `stripe_account_id`, similar to the way you're having for `WC_Product`. 

May I miss something in this regard?

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 5]
```diff
@@ -124,31 +133,69 @@ public static function get_wcpay_product_hash( WC_Product $product ): string {
...
+				$this->create_product( $product );
 			}
 		}
 
 		return $product->get_meta( self::get_wcpay_product_id_option( $test_mode ), true );
 	}
 
 	/**
-	 * Gets the WC Pay product ID associated with a WC product.
+	 * Get or create WCPay product ID for a given item type.
```
Comment (htdat) [inline includes/subscriptions/class-wc-payments-product-service.php]: Not an issue with this PR. This is the right thing to update this method description. I think it's worth updating the method name to have the `get_or_create` prefix rather than the current `get`.

**Review by htdat — COMMENTED** [review]
I think the approach looks great in general. But I am a bit cautious about why we need to have two approaches in saving `_stripe_account_id` for `WC_Product` and generic products (saved in the options table). See more in my inline comments.

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 4 above)
Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php]: It's like a micro optimization. We remove the need for one extra option to store and fetch. The `WC_Product` part already had some code dependent on where the product ID needs to be returned, so that's why I went with storing two metadata values. Here, with the options, we can store an array since we only use it here, and as mentioned above, I did some micro optimization, and that's why I opted for this approach.

We could also store two options, nothing wrong with that.

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 3 above)
Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php]:
```
	public static function get_wcpay_product_id_option( $test_mode = null ): string {
		$test_mode = null === $test_mode ? WC_Payments::mode()->is_test() : $test_mode;
		return $test_mode ? self::TEST_PRODUCT_ID_KEY : self::LIVE_PRODUCT_ID_KEY;
	}

```

This is already covered. In this end, the key equals to `_wcpay_product_id_test_linked_to` or `_wcpay_product_id_live_linked_to` depended on the environment.

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 1 above)
Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php]: Addressed here: https://github.com/Automattic/woocommerce-payments/pull/10562/commits/0003080248da247a54807cb037e463e65958e742

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 2 above)
Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php]: Good point. Fixed here: https://github.com/Automattic/woocommerce-payments/pull/10562/commits/0003080248da247a54807cb037e463e65958e742

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 5 above)
Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php]: Maybe we can create an issue for this to avoid brining more changes to this PR. WDYT?

Comment (htdat) [reply includes/subscriptions/class-wc-payments-product-service.php]: Yeah, that works. This is just a nice-to-have item for the current PR.

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 3 above)
Comment (htdat) [reply includes/subscriptions/class-wc-payments-product-service.php]: I meant we have a separated method from `get_wcpay_product_id_option` something like 

```php
	public static function get_wcpay_stripe_account_id_option_key( $test_mode = null ): string {
		$test_mode = null === $test_mode ? WC_Payments::mode()->is_test() : $test_mode;
		return $test_mode ? `_wcpay_linked_stripe_account_id_test` : `_wcpay_linked_stripe_account_id_live`; // Note: these values can be defined as constants within this class
	}
```

With this approach, we can avoid the error-prone when trying to concatenate the option key like the way the PR is doing: 

```php
    $product->get_meta( $option_key . '_linked_to' );
```

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 4 above)
Comment (htdat) [reply includes/subscriptions/class-wc-payments-product-service.php]: Gotcha, thanks for the extra details. If so, IMHO, the consistency with `WC_Product` and avoiding changing the meta value type (from `string` to `array`) have more advantages in terms of readability and future maintenance.

Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php]: Addressed here: https://github.com/Automattic/woocommerce-payments/pull/10562/commits/79cb7a924968f47a74bb3a1d2f76bccc924cd586

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 5 above)
Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php]: I agree. I thought that it will take more time, but the change is not that time-consuming. Addressed here: https://github.com/Automattic/woocommerce-payments/pull/10562/commits/7ce66dd4d0d06e7f7ab58b0b0cd94ffbb606c336

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 3 above)
Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php]: I see. Good point. Addressed here: https://github.com/Automattic/woocommerce-payments/pull/10562/commits/79cb7a924968f47a74bb3a1d2f76bccc924cd586

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 6]
```diff
@@ -115,40 +131,78 @@ public static function get_wcpay_product_hash( WC_Product $product ): string {
...
+					$this->save_wcpay_product_data( $wcpay_product_id, $stripe_account_id, $sanitized_type );
+					return $wcpay_product_id;
+				} else {
+					// Product doesn't exist, create new one.
+					return $this->create_product_for_item_type( $sanitized_type );
+				}
+			} catch ( \Exception $e ) {
+				// Error occurred, create new product.
+				return $this->create_product_for_item_type( $sanitized_type );
+			}
```
Comment (mgascam) [inline includes/subscriptions/class-wc-payments-product-service.php]: minor: I wonder if the merchant should be aware of the fact that we needed to create a new product. I guess not, but maybe we could write something to the logs about this action? Perhaps using the debug level, so it can be easier to troubleshoot if needed?

**Review by mgascam — APPROVED** [review]
The code changes look good to me and I tested it with WooCommerce Subscriptions and worked as expected. Only added a minor comment about an option to log something when a product is not found and created.

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 7]
```diff
@@ -623,16 +740,31 @@ private function set_wcpay_product_hash( WC_Product $product, string $value ) {
...
+	 * Returns the Stripe account ID. Used to avoid repeat calls to the account service.
+	 *
+	 * @return string
+	 */
+	private function get_stripe_account_id() {
+		if ( null === $this->stripe_account_id ) {
+			$this->stripe_account_id = $this->account->get_stripe_account_id();
+		}
+		return $this->stripe_account_id;
+	}
```
Comment (htdat) [inline includes/subscriptions/class-wc-payments-product-service.php]: I wonder if we really this method when `$this->account->get_stripe_account_id();` has already implemented a caching mechanism already.

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 3 above)
Comment (htdat) [reply includes/subscriptions/class-wc-payments-product-service.php]: @zmaglica - it seems this commit 79cb7a924968f47a74bb3a1d2f76bccc924cd586 as well as the last HEAD of this PR/branch are still not yet introducing a util function `get_wcpay_stripe_account_id_option_key`. I see that `_linked_to` is still used multiple times.

File: includes/subscriptions/class-wc-payments-product-service.php [hunk 8]
```diff
@@ -115,40 +131,78 @@ public static function get_wcpay_product_hash( WC_Product $product ): string {
...
+				// Validate that the product exists for the current account.
+				$existing_product = $this->payments_api_client->get_product_by_id( $wcpay_product_id );
+
+				if ( $existing_product ) {
+					// Product exists, save with current account ID.
+					$this->save_wcpay_product_data( $wcpay_product_id, $stripe_account_id, $sanitized_type );
+					return $wcpay_product_id;
+				} else {
+					// Product doesn't exist, create new one.
+					return $this->create_product_for_item_type( $sanitized_type );
```
Comment (deepakpathania) [inline includes/subscriptions/class-wc-payments-product-service.php:191]: The case block above suggests that the product exists and the subsequent handling is under that assumption but here we are creating a new product so it seems confusing. I am not sure whether we should create a new product in this scenario or bail out and log that this happened, and then suggesting the end merchant steps to resolve the problem. 🤔

**Review by deepakpathania — COMMENTED** [review]
Left a comment.

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 7 above)
Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php]: It is cached on the database level, and for each call we make a database query to fetch the stripe account id. With this function we even cache that so we don't have to query for the cache each time.

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 8 above)
Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php:191]: Good point, but I think we need to create a new product here. The issue is that the user can have product ID already stored, but not linked, which means that this product was created before this PR. When the merchant installs the plugin with this PR, and before anything else or before any purchase, the merchant re-onboards we have a situation where we have stored product ids that belong to another stripe account ID. Now we have a product ID stored in a legacy way where the stored product is not linked to a specific Stripe account ID, but it belongs to a totally different stripe account id. To be sure, and to avoid linking a product id that belongs to someone else, we fetch the product by ID to confirm that the product ID actually belongs to that Stripe account ID and not to someone else.

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 7 above)
Comment (htdat) [reply includes/subscriptions/class-wc-payments-product-service.php]: 🤔 `Database_Cache::get_or_add` implements the in-memory cache already, so we actually query the database for the first attempt during a request lifecycle only.

Edit: if the `Database_Cache` had not implemented the in-memory caching yet, we would have handled enhanced `Database_Cache` with it rather than just doing that here, IMHO.

https://github.com/Automattic/woocommerce-payments/blob/8f9395fbb68c08c1c69153c7319aabc3d0080cf0/includes/class-database-cache.php#L87-L95

Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php]: I think I am wrong. Yes, the cache is added in place, so we don't need this function. I will remove it.

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 3 above)
Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php]: This is fixed with the latest commit.

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 7 above)
Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php]: This is removed.

File: includes/subscriptions/class-wc-payments-product-service.php (hunk 6 above)
Comment (zmaglica) [reply includes/subscriptions/class-wc-payments-product-service.php]: Good point. Addressed here: https://github.com/Automattic/woocommerce-payments/pull/10562/commits/4d302974387e653e3f2bd696f8092d2ca3157da0

**Review by mgascam — APPROVED** [review]
Thanks for addressing my comment @zmaglica. Code changes look good to me and tests work as intended.

**Review by deepakpathania — APPROVED** [review]
Changes LGTM based on the discussion above and tests are passing.
