### PR TITLE
Hide Payment Request Buttons when cart contains multiple packages

### LINKED ISSUE #1563: Payment Request button: Support multiple shipping packages
Related to 1504-gh-woocommerce/woocommerce-gateway-stripe

This is an issue with the shortcode implementation and the blocks implementation. I'm not sure if it's possible to add multiple shipping packages to the Payment Request API, but at least there are some inconsistencies with the shipping descriptions in the PRB which needs to be fixed.

Steps to reproduce are detailed in the Stripe issue above.

### PR DESCRIPTION
**Pull request by reykjalin**
Fixes #1563 

Exact copy of https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1591 in function and form. Please refer to testing instructions and further information there.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 1]
```diff
@@ -537,6 +537,12 @@ public function has_allowed_items_in_cart() {
 			}
 		}
 
+		// We don't support multiple packages with Payment Request Buttons because we can't offer a good UX.
+		$packages = WC()->cart->get_shipping_packages();
+		if ( 1 < count( $packages ) ) {
+			return false;
+		}
+
```
Comment (reykjalin) [inline includes/class-wc-payments-payment-request-button-handler.php:545]: There's some more discussion in p1626166679419900-slack-CU6SYV31A on why we think this check is sufficient.

File: changelog.txt [hunk 2]
```diff
@@ -7,6 +7,7 @@
 * Fix - Do not overwrite admin pages when account is disconnected.
 * Update - Set a description when creating payment intents.
 * Add - Use date picker for applicable dispute evidence fields.
+* Fix - Disabled Payment Request Buttons when order has to be split into multiple packages because Payment Requests do not support that use case.
```
Comment (reykjalin) [inline changelog.txt:10]: I don't think we should merge and try to squeeze this into the 2.7.0 release, so we'll need to move the changelog entries to 2.8.0 before we merge.

**Review by ricardo — APPROVED** [review]
Tests well and LGTM! 🎉 🚢

File: changelog.txt (hunk 2 above)
Comment (ricardo) [reply changelog.txt:10]: Feel free to merge after rebasing and fixing the changelog version. 👍
