### PR TITLE
Fix missing transaction error when viewing orders placed in mismatched test mode

### LINKED ISSUE #7076: Fetching the charge on each order screen is causing excessive `resource_missing (charge id)` errors
### Describe the bug

On each order screen where WooPayments is the payment method, [we fetch the charge](https://github.com/Automattic/woocommerce-payments/blob/850b3b891033c8573ebbada1582f05fb6540b5dc/client/order/index.js#L130) to determine if the charge is disputed and render a [disputed order notice](https://github.com/Automattic/woocommerce-payments/blob/850b3b891033c8573ebbada1582f05fb6540b5dc/client/order/index.js#L129).

This is contributing to excessive `Invalid request error: resource_missing (charge id)` errors occurring (see logstash), due to:
* the charge ID stored as order meta may be for a live transaction, and the site is in test mode (or vice versa).
* the charge ID stored as order meta may not exist anymore (I'm unsure if this is a possibility).

### To Reproduce

1. Use a WooPayments account that can switch between live/test mode (e.g. onboard with real bank account details).
1. Enable test mode.
1. Create a disputed order in test mode using the card `4000000000000259`.
1. View the order. See the dispute notice introduced in 6.2.
1. Switch to live mode.
1. View the order. See request to `/charges` responds `500` with message
	```
	Error: No such charge: 'ch_abcde'; a similar object exists in test mode, but a live mode key was used to make this request.
	```

### Additional context

* Slack discussion Aug 26 2023: p1692999889340419-slack-CGGCLBN58
* Slack discussion Jul 24 2023: p1690190397004289-slack-CGGCLBN58
* The disputed order notice was introduced in WooPayments 6.2:
   #6354

### LINKED ISSUE #7967: Viewing a test mode order while test mode is disabled produces errors
### Describe the bug

This may be related to https://github.com/Automattic/woocommerce-payments/pull/7898, which was included in the 7.0.0 release.

If an order is placed in test mode, and that same order is viewed after test mode is disabled, it produces a snackbar error:

```
Error retrieving transaction.
```

I suspect this is a result of a 500 error in the console...

```
/wp-json/wc/v3/payments/charges/ch_3OUYY42EHhK9IQzL0RyLhuof?_locale=user:1 
        
        
       Failed to load resource: the server responded with a status of 500 ()
```

...and this `500` network response:

```
{
    "code": "wcpay_get_charge",
    "message": "Error: No such charge: 'ch_3OUYY42EHhK9IQzL0RyLhuof'; a similar object exists in test mode, but a live mode key was used to make this request.",
    "data": null
}
```

Re-enabling test mode resolves the error.

### To Reproduce

1. Enable test mode.
2. Place an order.
3. View the edit order page for the order placed in step 2.
4. Disable test mode.
5. Repeat step 3.
6. Note the snackbar error.
7. Check your browser's console tool.
8. Check your browser's network tool.

### Actual behavior
A snackbar error is displayed when viewing a test transaction while WooPayments is not in test mode. This can create some confusion for the merchant.

### Screenshots

snackbar error

### Expected behavior

To some extent, the network response and the resulting console error are expected because we are trying to access test mode data while not in test mode. However, suppressing the snackbar error here may be a good option to consider.

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #7967 
Fixes #7076

#### Changes proposed in this Pull Request

This PR checks to see if the order and site test mode match before rendering the disputed order notice and subsequently fetching charge data.

This prevents the error `Error: No such charge: 'ch_abcde';` from being returned by the server and the `Error retrieving transaction.` snackbar from rendering.

To ensure the notice continues to render for orders created prior to 6.9 (which added the `wcpay_mode` order meta #7651), the disputed order notice will always render if no `wcpay_mode` order meta is defined.

Tradeoffs of this approach:
1. The disputed order notice will not show for disputed orders when the order was created in test mode but the site is in live mode (or vice versa).

#### Testing instructions

* Use a store setup in live mode during KYC. (I've set one up, search Secret Store for `ej-wcpay-aus` with a live-mode order [here](https://ej-woo.mystagingwebsite.com/wp-admin/post.php?post=361&action=edit)).
* Enable test mode.
* Place a test order.
* Disable test mode.
* View the order as merchant.
* On `develop`, you will notice a network request error and a `Error retrieving transaction` snackbar.
* On this branch, the `/charges` network request will not occur and there should not be an error snackbar.

**Disputed orders**
* Use a store setup in live mode during KYC.
* Enable test mode.
* Place a disputed test order with the card `4000000000000259`.
* View the order as merchant.
* You should see the disputed order notice, since the disputed order was created in test mode.
* Disable test mode.
* View the disputed order as merchant.
* You will no longer see the disputed order notice, since the order/site test mode is mismatched.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7972` or branch name `fix/7967-disputed-order-notice-test-mode-check` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7967-disputed-order-notice-test-mode-check) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9397f222ea0566ec691a55ee06d9180cb59ab908
- Build time: 2024-01-05 01:11:50 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/order/index.js [hunk 1]
```diff
@@ -175,16 +175,20 @@ jQuery( function ( $ ) {
 			'#wcpay-order-payment-details-container'
 		);
 
-		// If the container doesn't exist (WC < 7.9), or the charge ID isn't present, don't render the notice.
+		// Check if the order's test mode meta matches the site's current test mode setting.
+		// E.g. order and site are both in test mode, or both in live mode.
+		const isOrderTestModeMatch = orderTestMode === wcpaySettings.testMode;
```
Comment (Jinksi) [inline client/order/index.js]: In order to continue to display the disputed order notice for orders created < 6.9, we could check if the `_wcpay_mode` order meta exists before checking for a match. This would mean that the network error will continue to occur for orders created < 6.9 if the order/site test mode is mismatched.

**Review by brucealdridge — APPROVED** [review]
Tested and confirmed working.
