### PR TITLE
Fix failing E2E pipelines

### LINKED ISSUE #7966: Fix e2e tests for subscriptions and checkout which fail with WC 8.5.0-beta.1
### Describe the bug
`WC - beta | wcpay - shopper` and `WC - beta | subscriptions - shopper` are [failing](https://github.com/Automattic/woocommerce-payments/actions/runs/7394021531/job/20117715005).

`WC - beta | wcpay - shopper` needs selector adjustments (p1704202276581069/1704092507.706699-slack-CGGCLBN58).

`WC - beta | subscriptions - shopper` needs selector adjustments (adjusted in https://github.com/Automattic/woocommerce-payments/compare/develop...fix/e2e-selectors) and a bit more investigation for the second failing test (p1704276442739969/1704092507.706699-slack-CGGCLBN58)

In both cases, failing E2E tests are passing manually.

### LINKED ISSUE #8051: GitHub Actions are failing
### Describe the bug
A lot of E2E tests are failing ([example](https://github.com/Automattic/woocommerce-payments/actions/runs/7582789096)).

This happens after WooCommerce version update due to notices' selectors being different. 

### Expected behavior 
`E2E Tests - All` flow should pass.

### PR DESCRIPTION
**Pull request by timur27**
Fixes https://github.com/Automattic/woocommerce-payments/issues/8051
Fixes https://github.com/Automattic/woocommerce-payments/issues/7966

#### Changes proposed in this Pull Request
This PR
* Fixes tests that are failing on `develop` due to new notices selectors coming from WooCommerce
* Adds some backward compatibility for old selectors to be supported as well and thus makes [`WC 7.7.0` flow](https://github.com/Automattic/woocommerce-payments/actions/runs/7586821939/job/20665971286) pass as well
* Cleans up some unused code (more https://github.com/Automattic/woocommerce-payments/pull/8048#discussion_r1459306170

> All tests pass now https://github.com/Automattic/woocommerce-payments/actions/runs/7586821939

#### Testing instructions

* run https://github.com/Automattic/woocommerce-payments/actions/workflows/e2e-test.yml against this branch once more and confirm all tests pass

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8048` or branch name `fix/e2e-tests` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/e2e-tests) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 19f2e0537806cb64b42b767eb9068e6bbed6c7d6
- Build time: 2024-01-19 17:37:43 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: tests/e2e/utils/payments.js [hunk 1]
```diff
@@ -44,36 +44,6 @@ export async function fillCardDetails( page, card ) {
...
-			delay: 20,
-		} );
-		await page.waitFor( 1000 );
-
-		const cardCvcInput = await stripeFrame.waitForSelector(
-			'[name="cvc"]',
-			{ timeout: 30000 }
-		);
-		await cardCvcInput.type( card.cvc, { delay: 20 } );
-		await page.waitFor( 1000 );
```
Comment (timur27) [inline tests/e2e/utils/payments.js:76]: This is just a side cleanup, this code was used for legacy card element only.

File: tests/e2e/utils/flows.js [hunk 2]
```diff
@@ -297,6 +298,46 @@ export const shopperWCP = {
...
+			} );
+		} )();
+
+		const oldErrorBannerToCheck = ( async () => {
+			await expect( page ).toMatchElement( oldNoticeSelector, {
+				text: errorText,
+			} );
+		} )();
+
+		await Promise.race( [ errorBannerToCheck, oldErrorBannerToCheck ] );
```
Comment (timur27) [inline tests/e2e/utils/flows.js:319]: This allows us to choose from two promises that check old & new selector. This way, we're able to support both selectors from the current and old WooCommerce version.

**Review by gpressutto5 — APPROVED** [review]
