### PR TITLE
Simplify and harden our onboarding [connect] links and Connect page state logic

### LINKED ISSUE #183: OAuth flow - detect if an oauth session is already active
See https://github.com/Automattic/woocommerce-payments/pull/171#issuecomment-521056967

The OAuth init endpoint returns a `secret` which gets stored as a transient for a day or until the flow is finished. If at the end of the flow the passed in secret mismatches the transient, then no account is connected and an error is shown. This can lead to a few edge cases:
* Starting the flow in another tab, not finishing it, then starting the flow again, then finishing the first flow - the transient would get overwritten and finishing the first flow would result in an error
* Finishing the flow after a day - Stripe might not allow this as they have a timeout as well, but technically it's possible for the transient to expire

Potential solutions:
* Use an array of transients
* Preferred: check if the transient is set, and when a new flow is started show a message asking for confirmation

### LINKED ISSUE #6542: Attach new `wcpay_overview_task_click` tracks event to existing tasks
### Describe the bug

In #6371, the tracks event `wcpay_overview_task_click` was introduced for monitoring click events on the new dispute resolution task. This event should be attached to other tasks in the Payments → Overview task list for completeness.

### LINKED ISSUE #7803: Misleading dev mode message when onboarding as a live account
### Describe the bug

Follow on from #7768

As mentioned by @daquinons https://github.com/Automattic/woocommerce-payments/pull/7768#issuecomment-1831163066, there is a misleading prompt if the user is in dev mode but onboards a "live" account. We should update the logic to catch this corner case and either hide this message or show a different message, because in this case, the account is being treated by the system as if it is a live account, NOT a dev account, and therefore nothing happens when the button is clicked.

This is only affecting dev mode accounts (using dev tools plugin), so it wouldn't be a problem for merchants, it's just a bit confusing for devs.

### Expected behaviour

As mentioned on Slack:

> If Dev mode is enabled and I click on “live account”, a dev mode account is created
> If I click on Set up payments, the account is deleted and I’m redirected to the onboarding again
> If I click on live mode, a new dev mode account will be created, and that’s expected (we have an info banner for it)

### LINKED ISSUE #8990: Possible issue with sandbox onboarding
### Describe the bug

As mentioned in this Slack thread: p1718875622258119-slack-C03KTTK2YMA

There seems to be a possible issue with onboarding in sandbox mode in some cases

### To Reproduce

1. Use Jurassic Ninja to create a new site (this is necessary because it's not possible to test this flow with the Dev Tools plugin installed)
2. Install WooCommerce, go through the onboarding, and install WooPayments as part of this.
3. Click on the `Get Paid` task on the WooCommerce Home page.
4. On the WooPayments onboarding page, click "Setting up store for a client" and then `Enable sandbox`. 

### Expected behavior

When sandbox mode is enabled, via the onboarding wizard, the Stripe KYC should always be in test mode, meaning it is possible to enter fake test data to pass the onboarding.

### Actual behavior

There are some reports (see Slack link above) that sandbox mode isn't properly initialised, and the user is taken to a _live_ Stripe KYC.

I haven't been able to reproduce, but it may be worth testing with different store countries to see if that leads to reproducing the issue. In the Slack thread, it was onboarded as a merchant from the Netherlands.

### LINKED ISSUE #9024: Connect account page results as in Not allowed if accessed directly
### Describe the bug
Currently, in `develop` branch we have a small bug: when `payments/connect` page is accessed directly and user is already has Stripe account, it results in Not allowed

### To Reproduce

1. Onboard new Stripe account
2. Visit `payments/connect` page

### Actual behavior
The merchant sees `Not allowed` error since page is not registered due to merchant has Stripe account

### Expected behavior
The merchant should be redirected to `payments/overview` page if they have started the KYC (because they'll have Stripe account).

### Additional context
The bug priority is low because we have it for a while on develop and it hasn't been raised by HEs or merchants. It's very hard to reproduce with our regular cases, but easy to reproduce if the URL is typed directly.

Discovered by @dmallory42 when testing https://github.com/Automattic/woocommerce-payments/pull/8590

### LINKED ISSUE #9101: PHP Notice when returning from Stripe KYC
### Describe the bug

We have our Webhook_Reliability service hook in to the `woocommerce_payments_account_refreshed` action to schedule some jobs via the WC ActionScheduler.

The risk is that the `woocommerce_payments_account_refreshed` action gets run too early in the WP execution, and the ActionScheduler is not initialized. In this case, two "doing it wrong" notices is triggered:

```
Notice: Function as_unschedule_action was called incorrectly. as_unschedule_action() was called before the Action Scheduler data store was initialized Please see Debugging in WordPress for more information. (This message was added in version 3.1.6.) in /var/www/html/wp-includes/functions.php on line 6078 Call Stack: 0.0019 384336 1. {main}() /var/www/html/wp-admin/admin.php:0 0.0023 385040 2. require_once('/var/www/html/wp-load.php') /var/www/html/wp-admin/admin.php:34 0.0026 385704 3. require_once('/var/www/html/wp-config.php') /var/www/html/wp-load.php:50 0.0030 397536 4. require_once('/var/www/html/wp-settings.php') /var/www/html/wp-config.php:255 0.3256 13281024 5. do_action() /var/www/html/wp-settings.php:625 0.3256 13281400 6. WP_Hook->do_action() /var/www/html/wp-includes/plugin.php:517 0.3256 13281400 7. WP_Hook->apply_filters() /var/www/html/wp-includes/class-wp-hook.php:348 0.3259 13319104 8. WC_Payments::{closure:/var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php:594-601}() /var/www/html/wp-includes/class-wp-hook.php:324 0.3259 13319560 9. WC_Payments::maybe_register_woopay_hooks() /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php:597 0.3259 13319560 10. WC_Payments_Features::is_woopay_eligible() /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php:1529 0.3259 13319560 11. WC_Payments_Account->is_account_rejected() /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-features.php:214 0.3259 13319560 12. WC_Payments_Account->is_stripe_connected() /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-account.php:231 0.3259 13319560 13. WC_Payments_Account->try_is_stripe_connected() /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-account.php:179 0.3259 13319560 14. WC_Payments_Account->get_cached_account_data() /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-account.php:192 4.6373 13512600 15. do_action() /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-account.php:1579 4.6373 13512976 16. WP_Hook->do_action() /var/www/html/wp-includes/plugin.php:517 4.6373 13512976 17. WP_Hook->apply_filters() /var/www/html/wp-includes/class-wp-hook.php:348 5.1266 13546728 18. WC_Payments_Webhook_Reliability_Service->maybe_schedule_fetch_events() /var/www/html/wp-includes/class-wp-hook.php:324 5.1266 13546728 19. WC_Payments_Webhook_Reliability_Service->schedule_fetch_events() /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-webhook-reliability-service.php:84 5.1266 13546728 20. WC_Payments_Action_Scheduler_Service->schedule_job() /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-webhook-reliability-service.php:171 5.1266 13546728 21. as_unschedule_action() /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-action-scheduler-service.php:152 5.1266 13546728 22. ActionScheduler::is_initialized() /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/functions.php:263 5.1267 13547048 23. _doing_it_wrong() /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php:229 5.1267 13553512 24. wp_trigger_error() /var/www/html/wp-includes/functions.php:6022 5.1270 13554680 25. trigger_error() /var/www/html/wp-includes/functions.php:6078
```

### To Reproduce

I can reproduce this in my local dev environment when not running the Stripe webhook listening and fully onboarding and account.

### LINKED ISSUE #9103: Unable to establish a Jetpack connection when onboarding from Payments Settings
### Describe the bug

If the merchant starts the onboarding process from the WooCommerce > Settings > Payments page, when clicking on the "Connect your store" CTA button on the Connect page, it will get redirected back to the Connect page, not to the WPCOM Jetpack connection screens.

### To Reproduce

1. Create a new JN site with the latest version of WooCommerce (here is [a quick link to create a short-lived one](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce))
2. Skip the WooCommerce guided setup and set your store country to 'US'
3. Go to WooCommerce > Settings > Advanced > WooCommerce.com and enable "Show Suggestions"
4. Go to WooCommerce > Settings > Payments
5. Click on the "Install" button for WooPayments
6. When redirected to the WooPayments Connect page, click on "Connect your store"
7. You will get redirected back to the WooPayments Connect page, not the Jetpack connection setup screens

### Screenshots

Here is a recording: 

https://github.com/user-attachments/assets/4598f339-545b-4cad-a710-dc5db351d41d

### Expected behavior

Clicking on the "Connect your store" CTA button should redirect to the WPCOM Jetpack connection screens.

### Additional context

p7Ldg5-79L-p2#comment-13003

cc @timmy5685

### PR DESCRIPTION
**Pull request by vladolaru**
Fixes #9103
Fixes #9101
Fixes #8990
Fixes #7803
Fixes #183
Fixes #6542
Fixes #9024
Yeah... I know these are quite a few, but that is what you get when you work on something long overdue.

#### The bullet points

1. **Ensure the Connect page contents make sense in the given context:**
  - If you have an account connected, the builder flow section will not show
  - If you have an account connected, the incentive will not show
  - If you have a missing/broken Jetpack connection but a connected account, we will not show the sandbox notice as you will not be onboarding a new account
  - If you have a broken account in test mode, we will show the switch to live sandbox notice (the same as in Payments Overview), as opposed to the regular one, to allow you to switch to live right from the Connect page
  - The "Reset account" button will appear whenever there is a partially onboarded account or a test mode account that is broken
  - If you had a previously working setup that is now broken, show a persistent error notice instructing you complete the WooPayments setup to process transactions.
2. **Separate between dev mode and test mode onboarding:**
  - There is test mode onboarding (like through the builder flow) and then there is dev mode which has the effect of forcing test mode onboarding regardless of flow (besides doing other things like forcing the gateway into test mode)
  - Dev mode should be additional/on-top-of the onboarding mode. It should not overreach if we are to maintain our sanity.
3.  Ensure `from` and `source` in the URLs maintain/determine proper value even when coming from WooCommerce places where we have no control of the URLs used
1.  Ensure `from` and `source` get sent with Tracks events, when we have them.
1.  **Restyle the error notices on the Connect page** to make their content more legible (the red background was an eye-sore) - make them similar to warning notices.
1.  Ensure **our main menu item has that red badge** when a previously good setup is now broken to catch the attention (as attention is definitely needed).
1.  Have far more test coverage.

#### The story 

I would say refactor, but it is more like reengineering our handling of connect links (via the `maybe_handle_onboarding` method) to make it simpler, predictable, resilient, much better documented, and covered by unit tests (there were none before).

Connect links are a catchall tool where we can throw merchants from anywhere into the onboarding flow, trusting the system to look at the current store state, maybe take some action, and point the merchant to the right place. Naturally, as we wanted to do more and provide more tailored experiences, the complexity has become too much to handle. This PR "cleans the room" and establishes code logic driven by business/product logic (and documents it).

At the same time, I tried to impose a clear separation between determining the `from` of a connect link and the onboarding `source` of the current onboarding flow. Conflating the two got it into trouble with the recent onboarding incident (paJDYF-ehK-p2).
- `from` means where the merchant was in the onboarding flow immediately before. It might mean a certain step, or a certain page, or a certain button on a page. Its goal is to guide us on what to do next. `from` is not meant to be sticky and it should change throughout the onboarding flow, generally representing the previous step.
- `source` means the very top place the merchant started the onboarding flow (our TOFU, if you will). `source` is meant to be sticky and not change throughout the onboarding flow as it gets attached to our Tracks events.

Another important concept that I tried to apply consistently is: **when do we have a GOOD Stripe account to work with?** Up until now, we've been dangling between `is_stripe_connected` and `is_details_submitted` (or a combination of the two). I believe the `is_stripe_account_valid` logic is the way to go! We are much more strict about the account state and will redirect to the connect page whenever the account is not in working condition (this doesn't mean pending verifications). **A GOOD account:**
- is connected (obviously)
- has submitted details
- has the minimum capabilities in a working state (right now, `card_payments` NOT `unrequested`)

If either of these is not met, **WooPayments can't work,** and we should not show the Payments Overview page or any other page. This is building/expanding [this PR](https://github.com/Automattic/woocommerce-payments/pull/5414) by Oleks. 

For our sanity, I went to our surfaces (in JS) and made sure that whenever some place (like a button) redirects folks to onboarding, it also declares where they are sending _from_ and maintains the _source_. It is best to avoid automagically determining the _from_ as much as possible (we have logic to fallback on referer and stuff, but it is best to be declarative about it because it has important implications).

Our JS Tracks events got a "splash" of conformity: they will send the `source` and `from` whenever they can. There were some missing Tracks events around our tasks, modals, etc. Now we have them. 

_Notes to PR reviewers:_
1. Don't panic at the large diff numbers :) About 1300 of the added lines are unit tests. And a couple more hundred are inline docs.
2. The `maybe_handle_onboarding` code flow and documentation need to make sense to you. If something doesn't, point it out.

#### Onboarding flows testing instructions

* The code changes need to make sense
* The PHPUnit tests need to pass
* Smoke test our onboarding like crazy :) 

I think it is best to use short-lived JN stores ([quick link to create with just WooCommerce](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce)) without WooPayments on the live-branch and instead upload the branch's built zip (you can find it via the `Prepare live branch for Jetpack Beta Builder / Build and inform the zip file (pull_request)` CI job details > `Upload the zip file as an artifact` step, but you will need to change the directory name in the zip to just `woocommerce-payments`). This way all the logic that automatically attempts to install/activate the plugin (like Payments task, Incentive, or Payments Settings) will work and not error out.

Also, try it mostly without the WCPay Dev Tools and dev mode enabled.

At each step in the onboarding flow, please make sure that the `source` and `from` GET params make sense. The `source` param should be very sticky, while the `from` param should point to the immediately previous step (not sticky) - `from` is not necessarily pointing to a page, but also to a certain tool.
As long as you stay in an onboarding flow, the `source` should remain the same. If you navigate away, reset the account, or move from test to live, the source will reset.

Please stay on the lookout and report back any "You are not allowed to access this page" scenarios. There shouldn't be any.

Here are a couple of ideas:
  * Start onboarding from all the Woo places: Payments task, Incentive, Payments Settings (try it with the plugin not installed, installed but not active, and active)
  * Start onboarding from the Connect Page, the Overview page via the reset account tool and the test-to-live notice.
  * Start onboarding with and without having a Jetpack connection. Decline the Jetpack connection. Try again and decline it still. Try again and approve it.
  * When in our Onboarding wizard, exit it and see where you are returned. Enter it again.
  * Finish the Onboarding wizard and go to the Stripe KYC. Return straight away and see where you end up. Try to finish the setup, and you should end up in the Stripe KYC again.
  * Try onboarding a progressive account

#### Working to not working testing instructions

Start each testing scenario with a fully working setup: Jetpack connection working and a fully onboarded account.

* Go to the Connect page (`/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect&from=WCADMIN_PAYMENT_TASK`) and you should be redirected to the Payments Overview page
* Break your Jetpack connection with the [Jetpack Debug Helper](https://github.com/Automattic/jetpack-debug-helper) plugin. 
  * All you should see is the Connect page. The builder flow section should not be visible, there should be an error message, and the "Payments" menu item should have a red badge:
  
  * If you try to go to a link like Payments Overview (`/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Foverview`) you should be redirected back to the Connect page.
* Unbreak your Jetpack connection with the [Jetpack Debug Helper](https://github.com/Automattic/jetpack-debug-helper) plugin and if you go to the Connect page (`/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect`) you should be redirected to the Payments Overview page.
* Hack your local account cache (`wcpay_account_data` option) so it has `card_payments` as `unrequested` (put `s:13:"card_payments";s:11:"unrequested";` in the serialized JSON)
  * All you should see is the Connect page. The builder flow section should not be visible, the CTA label should be different, it should have an error message, the "Payments" menu item should have a red badge:
  WsZXYe
  * If you try to go to a link like Payments Overview (`/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Foverview`) you should be redirected back to the Connect page
* Hack your local account cache (`wcpay_account_data` option) back to a valid state so it has `card_payments` as `active` (put `s:13:"card_payments";s:6:"active";` in the serialized JSON)
  * If you try to go to a link like Payments Connect (`/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect`), you should be redirected back to the Overview page
 * Hack your local account cache (`wcpay_account_data` option) so it has `card_payments` as `unrequested` (put `s:13:"card_payments";s:11:"unrequested";` in the serialized JSON) and go to the Connect page. Reset your account, and it should work and redirect you back to the Connect page with no error and the builder flow section visible:
 

#### Multiple onboarding sessions testing instructions

1. Start a new onboarding flow and proceed to the Stripe KYC - stay there
1. In a new browser tab, go to the Connect page and click on "Verify business details"
1. You should be redirected back to the Connect page with a notice like this:
UZTeIm
-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9105` or branch name `fix/9103-payments-settings-originated-onboarding-flow` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9103-payments-settings-originated-onboarding-flow) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 66c3ec7dbb4d2b8abf869158e7dbdc303796e147
- Build time: 2024-08-08 10:51:41 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payments-webhook-reliability-service.php [hunk 1]
```diff
@@ -155,9 +157,17 @@ private function schedule_process_event( string $event_id ) {
...
 	 * Schedule a job to fetch failed events.
 	 *
+	 * We will bail if this is called too early and ActionScheduler is not initialized.
+	 *
 	 * @return void
 	 */
 	private function schedule_fetch_events() {
+		// If the ActionScheduler is not initialized, we will get a fatal error when trying to schedule.
+		if ( ! ActionScheduler::is_initialized() ) {
+			Logger::info( 'Skipping scheduling a job to fetch failed events from the server: ActionScheduler is not initialized.' );
```
Comment (oaratovskyi) [inline includes/class-wc-payments-webhook-reliability-service.php:167]: For me it looks more like a `warning` level

File: includes/class-wc-payments-utils.php [hunk 2]
```diff
@@ -741,7 +741,7 @@ public static function get_last_refund_from_order_id( $order_id ) {
 	 * @return boolean
 	 */
 	public static function should_use_new_onboarding_flow(): bool {
-		if ( defined( 'WCPAY_DISABLE_NEW_ONBOARDING' ) && WCPAY_DISABLE_NEW_ONBOARDING ) {
+		if ( apply_filters( 'wcpay_disable_new_onboarding', defined( 'WCPAY_DISABLE_NEW_ONBOARDING' ) && WCPAY_DISABLE_NEW_ONBOARDING ) ) {
```
Comment (oaratovskyi) [inline includes/class-wc-payments-utils.php:746]: Is this just for testing, correct?

File: client/components/account-status/account-tools/index.tsx [hunk 3]
```diff
@@ -24,7 +24,7 @@ const handleReset = () => {
 	trackAccountReset();
 
 	window.location.href = addQueryArgs( wcpaySettings.connectUrl, {
-		'wcpay-reset-account': true,
+		'wcpay-reset-account': 'true',
```
Comment (oaratovskyi) [inline client/components/account-status/account-tools/index.tsx:25]: I am not sure why this change is needed, could you explain?

File: changelog/fix-9103-payments-settings-originated-onboarding-flow [hunk 4]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fix
+
+Fix onboarding redirect loop when starting from Woo Settings Payments.
```
Comment (oaratovskyi) [inline changelog/fix-9103-payments-settings-originated-onboarding-flow:4]: I think it's more than that, since a lot of stuff is changed

File: includes/class-wc-payments-account.php [hunk 5]
```diff
@@ -108,7 +108,8 @@ public function init_hooks() {
 		add_action( 'admin_init', [ $this, 'maybe_redirect_after_plugin_activation' ], 11 ); // Run this after the WC setup wizard and onboarding redirection logic.
 		add_action( 'admin_init', [ $this, 'maybe_redirect_by_get_param' ], 12 ); // Run this after the redirect to onboarding logic.
 		add_action( 'admin_init', [ $this, 'maybe_redirect_from_settings_page' ] );
-		add_action( 'admin_init', [ $this, 'maybe_redirect_from_onboarding_page' ] );
+		add_action( 'admin_init', [ $this, 'maybe_redirect_from_onboarding_wizard_page' ] );
+		add_action( 'admin_init', [ $this, 'maybe_redirect_from_connect_page' ] );
```
Comment (oaratovskyi) [inline includes/class-wc-payments-account.php]: I am curious why having separate entrypoint rather than doing it in maybe_handle_onboarding?

File: includes/class-wc-payments-account.php [hunk 6]
```diff
@@ -926,169 +1101,156 @@ public function maybe_handle_onboarding() {
...
 
-				// Set the test mode to false now that we are handling a real onboarding.
+				// Disable test mode onboarding now that we are handling a live onboarding.
 				WC_Payments_Onboarding_Service::set_test_mode( false );
 
-				$this->redirect_to_onboarding_page_or_start_server_connection( $onboarding_source );
-				return;
+				// Only redirect to the onboarding wizard if the new onboarding flow is enabled.
+				// Otherwise, proceed to the Stripe init.
+				if ( WC_Payments_Utils::should_use_new_onboarding_flow() ) {
```
Comment (oaratovskyi) [inline includes/class-wc-payments-account.php]: it's a bit confusing IMO cause we use new onboarding flow by default now

File: includes/class-wc-payments-account.php (hunk 5 above)
Comment (oaratovskyi) [reply includes/class-wc-payments-account.php]: I mean similar is also happening [here](https://github.com/Automattic/woocommerce-payments/blob/00eb23816876c3c41935dcb8b8d40af7aa2b2e82/includes/class-wc-payments-account.php#L1062-L1062), but for fully onboarded accounts

File: includes/class-wc-payments-account.php [hunk 7]
```diff
@@ -900,23 +960,138 @@ public function maybe_handle_onboarding() {
...
+		 *      4.1 On SUCCESS -> redirect to WPCOM/Jetpack connection screen (Calypso).
+		 *      4.2 On ERROR -> redirect to CONNECT PAGE with ERROR message
+		 * 5. Working WPCOM/Jetpack connection:
+		 *    5.1 Handle test to live account switch -> redirect to ONBOARDING WIZARD
+		 *    5.2 Handle onboarding/account reset -> redirect to CONNECT PAGE
+		 *    5.3 If NO Stripe account connected:
+		 *         5.3.1 If we come from ONBOARDING WIZARD or use the SANDBOX MODE/BUILDER FLOW:
+		 *                Initialize the Stripe account and:
+		 *                5.3.1.1 On SUCCESS -> redirect to STRIPE KYC
+		 *                5.3.1.2 On existing account -> redirect to OVERVIEW PAGE
```
Comment (oaratovskyi) [inline includes/class-wc-payments-account.php]: how can this happen? We don't have Stripe account connected

File: includes/class-wc-payments-webhook-reliability-service.php (hunk 1 above)
Comment (vladolaru) [reply includes/class-wc-payments-webhook-reliability-service.php:167]: The thing is it is not an error or something we should investigate - that is why I went with info. Simply, we refresh the account cache too early for ActionScheduler jobs to be attached based on it. We can't do anything about it.

WDYT?

File: includes/class-wc-payments-utils.php (hunk 2 above)
Comment (vladolaru) [reply includes/class-wc-payments-utils.php:746]: Yes. We can't wrangle constants when running PHPUnit tests.

File: client/components/account-status/account-tools/index.tsx (hunk 3 above)
Comment (vladolaru) [reply client/components/account-status/account-tools/index.tsx:25]: To ensure consistency and guard ourselves against JS and/or browser quirks. As it happens, boolean `true` gets passed back to PHP as string `true` and we check explicitly for string `true`. To make matters more resilient, we should pass exactly what we expect and not rely on automagical casting.

File: changelog/fix-9103-payments-settings-originated-onboarding-flow (hunk 4 above)
Comment (vladolaru) [reply changelog/fix-9103-payments-settings-originated-onboarding-flow:4]: Yeah. It started like that. But regardless of it, we don't want more than this in our changelogs.

File: includes/class-wc-payments-account.php (hunk 5 above)
Comment (vladolaru) [reply includes/class-wc-payments-account.php]: Like I explained in the big comment in `maybe_handle_onboarding`, we should not confuse connect links with connect _page_ links. `maybe_redirect_from_connect_page` handles possible redirects from the Connect page, not from connect links. I hope this makes sense.

File: includes/class-wc-payments-webhook-reliability-service.php (hunk 1 above)
Comment (oaratovskyi) [reply includes/class-wc-payments-webhook-reliability-service.php:167]: Ah, ok then. I was triggered by fatal error before and now we just making it info and I thought it can be fixed by the merchant
Thanks for explanation!

File: includes/class-wc-payments-account.php (hunk 6 above)
Comment (vladolaru) [reply includes/class-wc-payments-account.php]: I didn't want to break the "contract" of those constants. Maybe someone is relying on them. If you know nobody is, we can refactor further.

File: includes/class-wc-payments-account.php (hunk 5 above)
Comment (oaratovskyi) [reply includes/class-wc-payments-account.php]: Yeah, gotcha. Maybe worth mentioning in very short in `maybe_redirect_from_connect_page` too (like @see ...), so you can reach it from two entrypoints 🙂

File: includes/class-wc-payments-account.php (hunk 7 above)
Comment (vladolaru) [reply includes/class-wc-payments-account.php]: On our platform, if there is already a Stripe account associated/connected with the blog (regardless of the client state) we will simply return that back in the form of `url:false` in the response.

File: includes/class-wc-payments-account.php (hunk 6 above)
Comment (oaratovskyi) [reply includes/class-wc-payments-account.php]: yes, you're right. some developers may rely on them, let's leave it for now
we should deprecate it first and then remove if we really want to disable old flow fully

File: includes/class-wc-payments-account.php (hunk 5 above)
Comment (vladolaru) [reply includes/class-wc-payments-account.php]: [Added](https://github.com/Automattic/woocommerce-payments/pull/9105/commits/12e765046aa1b158aab7d62499cd6a7ea0705efe) docs.

Comment (oaratovskyi) [reply includes/class-wc-payments-account.php]: Thanks!

File: includes/class-wc-payments-account.php (hunk 6 above)
Comment (dmallory42) [reply includes/class-wc-payments-account.php]: I looked into the history of this - it was introduced in #7773, and I think our thinking was to leave a way of using the old onboarding **just in case** there was a bug with the new onboarding that meant we needed to provide a workaround.

At this point, it's been 8 months and we haven't needed to use it, so my opinion is we should clean it up and remove it (in a new issue, since I don't want to add more to this PR 🙂 )

Comment (vladolaru) [reply includes/class-wc-payments-account.php]: Good call, Daniel. I am all for removing stuff. Could you wrangle and issue and add it to our backlog?

**Review by oaratovskyi — DISMISSED** [review]
@vladolaru I've left my feedback in Slack due to big number of messages and images
p1721721612331869-slack-C03KTTK2YMA
let me know when you fix the bugs with behaviour and I'll take a look!

File: includes/class-wc-payments-account.php (hunk 6 above)
Comment (vladolaru) [reply includes/class-wc-payments-account.php]: No need for another issue. I've removed it in this PR :)

Comment (dmallory42) [reply includes/class-wc-payments-account.php]: Oh, awesome. Thank you for taking care of it!

File: client/overview/index.js [hunk 8]
```diff
@@ -217,9 +219,23 @@ const OverviewPage = () => {
...
+						'There was a problem resetting your account. Please wait a few seconds and try again.',
+						'woocommerce-payments'
+					) }
+				</Notice>
+			) }
 			{ isDevMode ? (
 				<OverviewSandboxModeNotice
-					ctaAction={ () => setLivePaymentsModalVisible( true ) }
+					ctaAction={ () => {
+						recordEvent( 'wcpay_setup_live_payments_modal_open', {
```
Comment (dmallory42) [inline client/overview/index.js]: Small bit of housekeeping: new events should be added to the `client/tracks/event.d.ts` file. 

Because this is a JS file, you won't get a warning in the code, but if it was a TS file you would. 🙂

File: client/overview/modal/setup-live-payments/index.tsx [hunk 9]
```diff
@@ -13,16 +13,39 @@ import { Icon, currencyDollar } from '@wordpress/icons';
...
 }
 
-const SetupLivePaymentsModal: React.FC< Props > = ( { onClose }: Props ) => {
+const SetupLivePaymentsModal: React.FC< Props > = ( {
+	from,
+	source,
+	onClose,
+}: Props ) => {
 	const handleSetup = () => {
+		recordEvent( 'wcpay_onboarding_flow_setup_live_payments', {
```
Comment (dmallory42) [inline client/overview/modal/setup-live-payments/index.tsx:30]: As mentioned in comment above, this event should be added to the `client/tracks/event.d.ts` file.

File: client/overview/modal/setup-live-payments/index.tsx [hunk 10]
```diff
@@ -13,16 +13,39 @@ import { Icon, currencyDollar } from '@wordpress/icons';
...
 		window.location.href = addQueryArgs( wcpaySettings.connectUrl, {
-			'wcpay-disable-onboarding-test-mode': true,
+			'wcpay-disable-onboarding-test-mode': 'true',
+			from,
+			source: 'wcpay-setup-live-payments', // Overwrite any existing source because we are starting over.
+		} );
+	};
+
+	const trackAndClose = () => {
+		recordEvent( 'wcpay_setup_live_payments_modal_exit', {
```
Comment (dmallory42) [inline client/overview/modal/setup-live-payments/index.tsx:43]: This one too :)

File: client/settings/general-settings/index.js [hunk 11]
```diff
@@ -38,9 +39,14 @@ const GeneralSettings = () => {
 									if ( enableTestMode ) {
 										setTestModeModalVisible( true );
 									} else {
-										updateIsTestModeEnabled(
-											enableTestMode
+										recordEvent(
+											'wcpay_test_mode_disabled',
```
Comment (dmallory42) [inline client/settings/general-settings/index.js:43]: And this one :)

File: includes/class-wc-payments-account.php [hunk 12]
```diff
@@ -838,15 +848,104 @@ public function maybe_redirect_from_onboarding_page(): bool {
...
 
+	/**
+	 * Redirects connect page (payments/connect) to the overview page for stores that
+	 * have a working Jetpack connection and a connected Stripe account.
+	 *
+	 * Note: Connect _page_ links are not the same as connect links.
+	 *       Connect links are used to start/re-start/continue the onboarding flow and they are independent of
+	 *       the WP dashboard page (based solely on request params).
+	 *
+	 * IMPORTANT: The logic should be kept in sync with the one in maybe_redirect_from_overview_page to avoid loops.
```
Comment (dmallory42) [inline includes/class-wc-payments-account.php:908]: I'm guessing you probably already covered this, but if not, is there a unit test we can put in place that will validate this?

File: includes/class-wc-payments-onboarding-service.php [hunk 13]
```diff
@@ -233,69 +261,310 @@ public static function set_test_mode( bool $test_mode ): void {
...
+				break;
+		}
+
+		$referer_params = [];
+		wp_parse_str( wp_parse_url( $referer, PHP_URL_QUERY ), $referer_params );
+
+		/**
+		 * =================
+		 * Use the source from the referer URL, if present and valid.
+		 */
```
Comment (dmallory42) [inline includes/class-wc-payments-onboarding-service.php]:
```suggestion
		/**
		 * =================
		 * Use the source from the referer URL, if present and valid.
		 * =================
		 */
```

File: client/overview/index.js (hunk 8 above)
Comment (vladolaru) [reply client/overview/index.js]: Good call! Adding them all.

File: client/components/account-status/account-tools/index.tsx [hunk 14]
```diff
@@ -24,13 +24,15 @@ const handleReset = () => {
...
+		source: 'wcpay-reset-account', // Overwrite any existing source because we are starting over.
 	} );
 };
 
 export const AccountTools: React.FC< Props > = ( props: Props ) => {
+	const source = 'wcpay-finish-setup-tool';
 	const accountLink = addQueryArgs( props.accountLink, {
-		source: 'account-tools__finish-setup-button',
```
Comment (oaratovskyi) [inline client/components/account-status/account-tools/index.tsx:33]: I wonder if it'll affect our funnels somehow, because the source changes
I guess it will, probably data teams will need to do some tweaks, right?

Comment (vladolaru) [reply client/components/account-status/account-tools/index.tsx:33]: I wouldn't worry about it as I am pretty sure nobody took that source value into account. We are currently focused on the big sources (Woo core ones and our Connect page).

File: includes/class-wc-payments-account.php (hunk 12 above)
Comment (vladolaru) [reply includes/class-wc-payments-account.php:908]: Good call, Daniel! I've added [the anti-looping tests](https://github.com/Automattic/woocommerce-payments/pull/9105/commits/862d8a1658180dc63e6cf185e6f88e1fcb0ab715).

Comment (dmallory42) [reply includes/class-wc-payments-account.php:908]: Perfect, looks great!

**Comment by timmy5685** [comment]
@vladolaru - I asked @mordeth to make some minor tweaks to the copy on the payments overview screen when in test drive and I'd like to align that here. and I have also proposed some minor tweaks.

Current: “Please complete your WooPayments setup to process transactions.”
NEW: “Please complete your WooPayments setup to process live payments.”

Current: “There is already an ongoing account setup session (probably in another browser tab). Please finish it or click here to start a again.”
NEW: "Another account setup session is already in progress. Please finish it or click here to start a again.

Another question re: 
image
I'm confused by the red notification at the top: “There is already an ongoing account setup session (probably in another browser tab). Please finish it or click here to start a again.” vs the button " Finish business details verification"

In the message - we're telling them to go find that other session or start a new one, but in the button we're telling them to continue with their existing account setup. So what does that button do? Take them to the same session that instructed them to go find in the notification at the top? or something else?

File: client/connect-account-page/index.tsx [hunk 15]
```diff
@@ -52,26 +56,52 @@ const ConnectAccountPage: React.FC = () => {
...
 	const isCountrySupported = !! availableCountries[ country ];
 
+	const urlParams = new URLSearchParams( window.location.search );
+
 	const determineTrackingSource = () => {
-		const urlParams = new URLSearchParams( window.location.search );
-		const from = urlParams.get( 'from' ) || '';
+		// If we have a source query param in the current request, use that.
+		const urlSource = urlParams.get( 'source' )?.replace( /[^\w-]+/g, '' );
+		if ( !! urlSource && 'unknown' !== urlSource ) {
```
Comment (oaratovskyi) [inline client/connect-account-page/index.tsx:71]: `!!` is this a mistake? I think it should be just `!`

File: client/connect-account-page/index.tsx [hunk 16]
```diff
@@ -192,7 +264,24 @@ const ConnectAccountPage: React.FC = () => {
 							{ strings.nonSupportedCountry }
 						</BannerNotice>
 					) }
-					{ devMode && <SandboxModeNotice /> }
+					{
+						// Show general sandbox notice when no account is connected but sandbox mode is active.
+						! isAccountConnected && devMode ? (
+							<SandboxModeNotice />
+						) : (
+							// If we already have a sandbox account connected (but in a bad state) and
```
Comment (oaratovskyi) [inline client/connect-account-page/index.tsx]: what means `but in a bad state`? I don't see this condition below

File: client/connect-account-page/index.tsx [hunk 17]
```diff
@@ -227,35 +316,64 @@ const ConnectAccountPage: React.FC = () => {
...
+					{
+						// Only show the incentive if an account is NOT connected.
+						! isAccountConnected && incentive && (
+							<Incentive { ...incentive } />
+						)
+					}
+					{
+						// Only show the sandbox mode panel if an account is NOT connected.
+						! isAccountConnected && (
+							<Panel className="connect-account-page__sandbox-mode-panel">
```
Comment (oaratovskyi) [inline client/connect-account-page/index.tsx:384]: Do we have this as a component? If yes let's use it

Comment (oaratovskyi) [reply client/connect-account-page/index.tsx:384]: is it `TestModeNotice`?

File: client/overview/modal/reset-account/index.tsx [hunk 18]
```diff
@@ -9,6 +9,7 @@ import { Button, CardDivider, Modal } from '@wordpress/components';
  */
 import './style.scss';
 import strings from './strings';
+import { __ } from '@wordpress/i18n';
```
Comment (oaratovskyi) [inline client/overview/modal/reset-account/index.tsx]: github actions says it's not used

File: client/tracks/event.d.ts [hunk 19]
```diff
@@ -59,12 +59,16 @@ export type Event =
...
+	| 'wcpay_onboarding_flow_setup_live_payments'
 	| 'wcpay_overview_balances_currency_tab_click'
 	| 'wcpay_overview_deposits_view_history_click'
 	| 'wcpay_overview_deposits_change_schedule_click'
 	| 'wcpay_overview_task_click'
 	| 'wcpay_overview_payment_activity_click'
+	| 'wcpay_setup_live_payments_modal_open'
+	| 'wcpay_setup_live_payments_modal_exit'
 	| 'wcpay_view_submitted_evidence_clicked'
+	| 'wcpay_test_mode_disabled'
```
Comment (oaratovskyi) [inline client/tracks/event.d.ts:72]: maybe also add `wcpay_test_mode_modal_exit` and `wcpay_test_mode_enabled`

File: includes/class-wc-payments-account.php [hunk 20]
```diff
@@ -709,37 +751,28 @@ public function maybe_redirect_after_plugin_activation() {
 			return false;
 		}
 
-		$account = $this->get_cached_account_data();
```
Comment (oaratovskyi) [inline includes/class-wc-payments-account.php:712]: hmm, why is it removed?

File: includes/class-wc-payments-account.php [hunk 21]
```diff
@@ -842,17 +882,115 @@ public function maybe_redirect_from_onboarding_page(): bool {
...
+		if ( ! $this->has_working_jetpack_connection() || ! $this->is_stripe_account_valid() ) {
+			$this->redirect_service->redirect_to_connect_page(
+				sprintf(
+				/* translators: 1: WooPayments. */
+					__( 'Please <b>complete your %1$s setup</b> to process transactions.', 'woocommerce-payments' ),
+					'WooPayments'
+				),
+				WC_Payments_Onboarding_Service::FROM_OVERVIEW_PAGE,
+				[
+					'promo'                       => ! empty( $_GET['promo'] ) ? sanitize_text_field( wp_unslash( $_GET['promo'] ) ) : false,
```
Comment (oaratovskyi) [inline includes/class-wc-payments-account.php]: I wonder if we need `promo`, `progressive`, `collect_payout_requirements` and `create_builder_account` on the connect page

File: client/connect-account-page/index.tsx (hunk 15 above)
Comment (vladolaru) [reply client/connect-account-page/index.tsx:71]: I want to test if the urlSource is truthy and not `unknown`

File: includes/class-wc-payments-account.php (hunk 20 above)
Comment (vladolaru) [reply includes/class-wc-payments-account.php:712]: Because it is tested by:
```
// If everything is in working order, don't redirect.
if ( $this->has_working_jetpack_connection() && $this->is_stripe_account_valid() ) {
```

**Comment by vladolaru** [comment]
Thanks for the copy, @timmy5685! Making the changes.

> I'm confused by the red notification at the top: “There is already an ongoing account setup session (probably in another browser tab). Please finish it or click here to start a again.” vs the button " Finish business details verification"
>
> In the message - we're telling them to go find that other session or start a new one, but in the button we're telling them to continue with their existing account setup. So what does that button do? Take them to the same session that instructed them to go find in the notification at the top? or something else?

You are right about the confusion. The "Finish business details verifications" just takes them back to the Connect page. Unfortunately there is no way to recreate the session (security reasons). We could disable the button, as a compromise. WDYT?

File: client/connect-account-page/index.tsx (hunk 16 above)
Comment (vladolaru) [reply client/connect-account-page/index.tsx]: It was missing `! isAccountValid &&` but that is implied since you are on the Connect page with a connected account. I will add it for clarity.

**Comment by timmy5685** [comment]
@vladolaru -

> The "Finish business details verifications" just takes them back to the Connect page.

Do you mean that it's just a loop then? I'm on the connect page, I click "finish business verification details", and I just looped back to the page I am already on?

If so - I would keep the button saying "Verify business details" (no need to update it to say "Finish business details verifications" and grey it out since we are showing them an error at the top already which should explain why the button is disabled.

Just to confirm - how much of an edge case is this?

File: client/connect-account-page/index.tsx (hunk 17 above)
Comment (vladolaru) [reply client/connect-account-page/index.tsx:384]: I don't follow: that is the builder flow section of the Connect page.

**Comment by vladolaru** [comment]
> Do you mean that it's just a loop then? I'm on the connect page, I click "finish business verification details", and I just looped back to the page I am already on?

Yes @timmy5685 

> Just to confirm - how much of an edge case is this?

If you start a Stripe KYC session in a browser and try to go to the Connect page and start another one you will end up in this case.

**Comment by vladolaru** [comment]
There you go, @timmy5685 :

File: includes/class-wc-payments-account.php (hunk 21 above)
Comment (vladolaru) [reply includes/class-wc-payments-account.php]: You have a point! Probably not. Removing them.

**Comment by timmy5685** [comment]
@vladolaru - that doesn't look like our normal pattern for our disabled buttons.

@orcunomattic - can you confirm?

**Comment by vladolaru** [comment]
@timmy5685 That is just the disabled primary button component. There is no custom styling that I can see.

**Comment by orcungogus** [comment]
> @vladolaru - that doesn't look like our normal pattern for our disabled buttons.
> @orcunomattic - can you confirm?

@timmy5685, that does match our button styling for disabled buttons, yes:
Primary-button

more info on the button component here: https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/button

**Comment by timmy5685** [comment]
thanks @vladolaru @orcunomattic - for some reason I thought we have a different style (greyed out or something) when a primary button is disabled. Realizing I was probably confusing that with the disabled secondary button style. Appreciate y'all confirming!

**Comment by vladolaru** [comment]
@dmallory42 if you have the time for another round of smoke testing... very much appreciated.

**Review by dmallory42 — APPROVED** [review]
Thanks a lot for the awesome work on this PR! I've smoke tested some more with different scenarios and everything is looking as expected. I think this is ready to go! :shipit: 

A small suggestion, we should consider checking the [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) to see if there's any other onboarding scenarios we want to add, just to be extra safe - or, if we have especially specific edge cases to test, we can add them to the release-specific testing instructions.

**Comment by vladolaru** [comment]
Thank you, @dmallory42 !

> A small suggestion, we should consider checking the [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) to see if there's any other onboarding scenarios we want to add, just to be extra safe - or, if we have especially specific edge cases to test, we can add them to the release-specific testing instructions.

Good point! I will add a critical flow for onboarding from the WooCommerce Payments Settings. Will also look to update the testing instructions for the rest of the flows, where there are changes.

**Comment by vladolaru** [comment]
@dmallory42 I've [updated the critical flows](https://github.com/Automattic/woocommerce-payments/issues/9239).
