### PR TITLE
Fix: Handle payment methods errors in backend

### LINKED ISSUE #9177: Checkout: Handle errors from endpoint POST /v1/payment_methods
### Describe the bug

Currently, after shoppers fill out card details and submit the "Pay now" button, a `POST /payment_methods` request is sent. 

This can create an error (decline) right away and shoppers are aware about that in the checkout page. However, merchants do not have any visibility about this failure.

### To Reproduce

Currently, this is not possible to reproduce in the test/dev mode. However, that's possible if using a test card for the test mode in a live mode. 

### Actual behavior

Merchants have no idea about this attempt, and no order is created in WP Admin. 

### Expected behavior

Merchants are aware about this error. They expect to see an order created in WP Admin, or at least an entry in the WooPayments log. 

### Dev notes 

Here is the current flow: 

1. Customer adds products, and goes to the checkout page.
2. Customer submits card details, then WooPayment uses Stripe JS to submit these raw card details to `POST /v1/payment_methods`
3. Stripe returns a payment method ID `pm_random_string`.
4. WooPayents use this payment method to submit this order thorugh the Woo core checkout process i.e. to `/?wc-ajax=checkout `for the classic checkout.
5. On the PHP side of the merchant side: a new order is created, a payment intent creation request is sent to the WooPayments server.

However, in these failed cases, the process above is terminated at step 2, as Stripe did not return any payment method ID. Therefore, the checkout page also relays the same/similar error message, i.e. `Your card has been declined` and no order is created/udpated.

### Additional context

- Originally reported in p1721152035596249-slack-C7U3Y3VMY
- More details 3533d-pb

### PR DESCRIPTION
**Pull request by danielmx-dev**
Fixes #9177

#### Changes proposed in this Pull Request

* Whenever an error occurs while submitting a request to `v1/payment_methods`, instead of showing the error right away to the shopper, we'll submit the error to the backend for it to be recorded in a failed order.

I also had some issues with the Playwright tests being flaky, so I increased the timeouts to obtain more consistently successful builds.

#### Testing instructions

* ⚠️ **PREREQUISITE**: This requires a WooPayments account in Live mode, this won't work in Sandbox/Test mode.
* Add any product to the shopping cart, then go to blocks checkout (**Repeat for classic checkout afterwards**).
* Fill all the required information, for the credit card, use one of [Stripe test cards](https://docs.stripe.com/testing#cards)

Actual Behavior (without this PR):
* An error will be displayed to the shopper.
* As a merchant, if you login to wp-admin and then go to WooCommerce -> Orders, you won't see any new records for the previously failed attempt.

Expected behavior (with this PR):
* An error will be displayed to the shopper (this time it'll take longer since a request is being made to the backend).
* As a merchant, if you login to wp-admin and then go to WooCommerce -> Orders, you should see a Failed order for the previous attempt. 
* In the order notes, verify that the error message is also recorded.
image

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply): **N/A**

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9226` or branch name `fix/9177-handle-payment-method-errors-in-backend` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9177-handle-payment-method-errors-in-backend) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 33693f0a3934511d86578b3762159f770233b5cf
- Build time: 2024-08-14 15:41:10 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-payment-information.php [hunk 1]
```diff
@@ -260,7 +274,16 @@ public static function from_payment_request(
...
+		$pi = new Payment_Information( $payment_method, $order, $payment_type, $token, $payment_initiated_by, $manual_capture, $cvc_confirmation, $fingerprint, $payment_method_stripe_id );
+
+		if ( self::PAYMENT_METHOD_ERROR === $payment_method ) {
+			$error_message = $request['wcpay-payment-method-error-message'] ?? __( 'Invalid Payment Method', 'woocommerce-payments' );
+			$error_code    = $request['wcpay-payment-method-error-code'] ?? 'unknown-error';
+			$error         = new \WP_Error( $error_code, $error_message );
+			$pi->set_error( $error );
+		}
+
+		return $pi;
```
Comment (frosso) [inline includes/class-payment-information.php]:
```suggestion
		$payment_information = new Payment_Information( $payment_method, $order, $payment_type, $token, $payment_initiated_by, $manual_capture, $cvc_confirmation, $fingerprint, $payment_method_stripe_id );

		if ( self::PAYMENT_METHOD_ERROR === $payment_method ) {
			$error_message = $request['wcpay-payment-method-error-message'] ?? __( 'Invalid Payment Method', 'woocommerce-payments' );
			$error_code    = $request['wcpay-payment-method-error-code'] ?? 'unknown-error';
			$error         = new \WP_Error( $error_code, $error_message );
			$payment_information->set_error( $error );
		}

		return $payment_information;
```

⛏️ `$pi` might be a bit on the short side. While it works, it might be clearer for others (and our future selves) if we used more descriptive names, like `$payment_information` instead. I think it could make the code easier to understand and maintain, even when it's in a short scope like this. What do you think?

File: client/checkout/blocks/payment-processor.js [hunk 2]
```diff
@@ -193,8 +194,24 @@ const PaymentProcessor = ( {
 
 					if ( result.error ) {
 						return {
-							type: 'error',
-							message: result.error.message,
+							type: 'success',
```
Comment (frosso) [inline client/checkout/blocks/payment-processor.js]: I believe I understand that in order for the error message to be added as an order note, we need to first submit the payment information to the server. So we're saying "there has been an error, but let's treat it as success" (please let me know if that's accurate or not).

However, this keeps giving me pause.

Is there any other hook from WooCommerce Blocks we can use to add this information to the order, without having to return `success` even tho there has been an error?

File: client/checkout/constants.js [hunk 3]
```diff
@@ -17,6 +17,7 @@ export const PAYMENT_METHOD_NAME_EXPRESS_CHECKOUT_ELEMENT =
 	'woocommerce_payments_express_checkout';
 export const PAYMENT_METHOD_NAME_WOOPAY_EXPRESS_CHECKOUT =
 	'woocommerce_payments_woopay_express_checkout';
+export const PAYMENT_METHOD_ERROR = 'ERROR';
```
Comment (frosso) [inline client/checkout/constants.js]: Should we prefix this with a `woocommerce_payments_` string as well? Honest question, I just wonder if there could be clashes.

**Review by frosso — COMMENTED** [review]
I tested this in various scenarios, and the solution seems to be working very well! 💪 I see the note added to the order, and the order has the correct status.

It took me a bit to test this due to the live mode, and I thought that I had found an issue with the `4000000000009235` card (I had to double-check different builds 😅 ).

The fact we're using the `success` status even tho there has been an error feels _weird_ to me (for lack of a better adjective).

I asked the blocks team for their blessings, I hope that's ok :) p1723471558023509-slack-C02TS23QJ1X

File: client/checkout/blocks/payment-processor.js (hunk 2 above)
Comment (danielmx-dev) [reply client/checkout/blocks/payment-processor.js]: Out of the possible [result types](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-blocks/assets/js/base/context/event-emit/utils.ts#L22-L26), only `success` allows the checkout request to go through. I have added a comment to clarify that.

Comment (frosso) [reply client/checkout/blocks/payment-processor.js]: That's ⭐  _perfection_ ⭐ , thank you for adding it!

**Review by frosso — APPROVED** [review]
Thank you for the changes! I tested this again multiple times, on multiple scenarios, with shortcode/block cart & checkout.

I'll point out that GooglePay/ApplePay failures don't seem to be recorded (which I think is fine).
And subscription/subscription renewal failures also don't seem to be reported (but I didn't notice any divergence of behavior from `develop`).

Great job with this solution, making it backwards compatible as well! 💪 

EDIT: should we add this scenario to the critical flows?

**Comment by danielmx-dev** [comment]
> EDIT: should we add this scenario to the critical flows?

I have updated the testing instructions to indicate that a failed order will be created when the payment fails, as well as how to validate the order note. https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#checkout-failures-with-various-cards

**Comment by frosso** [comment]
Great, thank you @danielmx-dev ! 💯
