### PR TITLE
Fix e2e tests related to the WooCommerce blocks' checkout

### LINKED ISSUE #3274: E2e tests related to the WooCommerce blocks checkout fail
### Describe the bug

The e2e tests related to the WooCommerce blocks checkout fail with `Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.`

### To Reproduce

1. Checkout the 'develop' branch
2. Run `npm run test:e2e ./tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js` or `npm run test:e2e ./tests/e2e/specs/shopper/shopper-wc-blocks-checkout-purchase.spec.js`
3.  Notice all of the e2e tests fail with `Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 100000ms timeout specified by jest.setTimeout.`

### Actual behavior
All of the WCB checkout-related tests fail with the same error.

### Expected behavior
The tests shouldn't fail so consistently.

### Additional context

Looks like this is related to us trying to fill the shipping fields instead of the billing fields, and WCB not having a default value for the state field, and the checkout process not being able to continue because this required field is missing.

### PR DESCRIPTION
**Pull request by a-danae**
Fixes #3274 

#### Changes proposed in this Pull Request

Update the flow for filling up the WCB's checkout in the e2e tests

* Fill up the billing fields instead of the shipping ones
* Fill up the state field

Waiting for the tests from this PR run to finish before requesting a review.

#### Testing instructions

* Check out the 'develop' branch
* Run npm run test:e2e ./tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js or npm run test:e2e ./tests/e2e/specs/shopper/shopper-wc-blocks-checkout-purchase.spec.js
* Opposite to the related issue, all tests should pass now

Or just make sure those e2e tests from this PR pass, while they're failing in other PRs.

There are other tests failing, but I kept them out of the scope of this PR.

-------------------

- [ ] Added changelog entry (or does not apply) - Would this need a changelog entry?
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

File: tests/e2e/utils/flows.js [hunk 1]
```diff
@@ -203,6 +203,10 @@ export const shopperWCP = {
 			'#billing-postcode',
 			customerBillingDetails.postcode
 		);
+		await clearAndFillInput(
+			'#billing-state input',
```
Comment (deepakpathania) [inline tests/e2e/utils/flows.js:207]: Do you think it makes sense to add a direct identifier for this element instead of accessing the `input` through another selector? Might be more explicit like the other ones we are using to clear inputs.

File: tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js [hunk 2]
```diff
@@ -15,7 +15,7 @@ import {
 	RUN_WC_BLOCKS_TESTS,
 } from '../../utils';
 
-const shippingDetails = config.get( 'addresses.customer.shipping' );
+const billingDetails = config.get( 'addresses.customer.billing' );
```
Comment (deepakpathania) [inline tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js:18]: Nitpick but maybe we could use constants above to get the identifiers with explicit names like `CUSTOME_BILLING_DETAILS` so that they're easier to identify and change. This might be a bigger thing to replicate across all instances but maybe we could just start with the files we are touching for now. WDYT?

**Comment by deepakpathania** [comment]
@a-danae For some reason, the block inserter doesn't get loaded in the E2E test flow in my local setup. When trying to open the same flow in a normal chrome tab, I can see that it works as intended. Because of this the local setup is currently getting stuck at `addNewPageCheckoutWCB` step. PFA screenshots for reference.
- E2E flow with blurred out toggle block inserter.
Screenshot 2021-11-30 at 11 48 48 AM

- Normal chrome tab
Screenshot 2021-11-30 at 11 48 48 AM

Are there any specific config that I need to set for this to work and if so could you add them to the testing instructions?
cc @achyuthajoy

**Comment by a-danae** [comment]
> For some reason, the block inserter doesn't get loaded in the E2E test flow in my local setup

I'm able to replicate this behavior too when running the tests in `dev` mode. I'm digging deeper there. Do things work for you when running it with a regular non-dev run?

In the meantime, I pushed an adjustment for a detail during the checkout with WCB, and I'm proceeding with the updates you suggested.

Thanks for checking this out, @deepakpathania 🙂

**Comment by deepakpathania** [comment]
> Do things work for you when running it with a regular non-dev run?

They don't, I get timeouts - either for async callbacks not being invoked within time or waiting for selectors, screenshot attached for reference.

Screenshot 2021-12-01 at 3 05 18 PM

File: tests/e2e/utils/flows.js (hunk 1 above)
Comment (a-danae) [reply tests/e2e/utils/flows.js]: Looks like this isn't relevant to the fix. Was it relevant before? Did I get something wrong? Dunno, but I've removed it.

**Comment by a-danae** [comment]
> For some reason, the block inserter doesn't get loaded in the E2E test flow in my local setup

Looks like this is related to the User-Agent header used during the dev tests. Reference [here](https://github.com/WordPress/gutenberg/issues/12657#issuecomment-459892911).

The agent used during the tests is `puppeteer-debug wp-e2e-test`. When I add `page.setUserAgent( 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36' );` (which is the one from my browser) right before [this](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/utils/flows.js#L400) `page.goto()`, things work well.

I used that agent just for testing whether that was it. I'm looking for a more generic one that works for the tests.

> They don't, I get timeouts - either for async callbacks not being invoked within time or waiting for selectors, screenshot attached for reference.

Ah, yep, I only pushed the fix for the tests under `shopper-wc-blocks-checkout-purchase.spec.js`. I've pushed it for `shopper-wc-blocks-checkout-failures.spec.js`, so now they should work too.

I'm addressing the issue when creating the WCB Checkout page and pinging you back.

File: tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js (hunk 2 above)
Comment (a-danae) [reply tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js:18]: Not sure if I got this one, mind explaining it further? Like, exporting the value of `config.get( 'addresses.customer.shipping' )` from `../../utils` and importing it here, instead of retrieving them directly from the [config file](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/config/test.json)?

File: tests/e2e/utils/flows.js [hunk 3]
```diff
@@ -397,6 +397,11 @@ export const merchantWCP = {
 	},
 
 	addNewPageCheckoutWCB: async () => {
+		// Set a User Agent different than the "puppeteer-debug wp-e2e-test" one we use
+		// so the "Add block" button isn't disabled during -dev tests.
+		page.setUserAgent(
```
Comment (a-danae) [inline tests/e2e/utils/flows.js:402]: @deepakpathania I didn't find a sample User-Agent that didn't describe an OS/browser that worked for the tests. Glad to go with a different approach.

File: tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js (hunk 2 above)
Comment (deepakpathania) [reply tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js:18]: Ahh, apologies for the confusing wording. I was thinking something along the lines of :
```javascript
 const ADDRESS_CONFIG = config.get( 'addresses');
 const CARDS_CONFIG      = config.get( 'cards' );
 ...
 const billingDetails = ADDRESS_CONFIG['customer']['shipping'];
 const declinedCard = CARD_CONFIG['declined'];
```

The idea was to reduce the number of individual `config.get` calls to access the config values in different tests by having the root-level imports as constants and then using them. WDYT?

File: tests/e2e/utils/flows.js (hunk 3 above)
Comment (deepakpathania) [reply tests/e2e/utils/flows.js:402]: I feel we could maybe move this to `jest-setup.js`, create a function for it and add that to the `beforeAll` block so that it applies to all test suite runs since this could be applicable for other tests as well. WDYT?

**Comment by deepakpathania** [comment]
>  I only pushed the fix for the tests under shopper-wc-blocks-checkout-purchase.spec.js

@a-danae Somehow these don't pass for me either locally with the latest changes you pushed, attaching screenshot for reference. Do they pass for you with these changes?

Screenshot 2021-12-02 at 5 19 44 PM

**Comment by a-danae** [comment]
> Do they pass for you with these changes?

Yeah, they do pass for me. I reset the environment yesterday and ran all the tests and the tests for WCB passed. Here's a screenshot of a run I just did of the WCB tests alone.
image

In your local site for the tests, does the WCB page with the link http://localhost:8084/checkout-wcb/ have the checkout block in its contents? Judging by the screenshot, sounds like it's not finding the email field in the checkout page.

File: tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js (hunk 2 above)
Comment (a-danae) [reply tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js:18]: Aha, got you now. Thanks for explaining it!

No prob on my end with adjusting it. But if you want another opinion, I think we better check about this with the ones who have been maintaining these tests for longer. I'm getting started with them.

I see we're directly using `config.get()` in many places and, in my opinion, that makes it clear at a glimpse where those values are coming from. I think that storing them in a variable and then using it would kind of obscure that. And I'm not sure how much of a value it'd provide. But that's just my 2c 🙂  I'd rather check with the devs that are more familiar with these tests.

**Comment by deepakpathania** [comment]
@a-danae Apologies for the back and forth, some issue with my local setup. Have reset everything and verified that the tests work fine now with the changes and fail on `develop`, screenshot for reference.

Screenshot 2021-12-03 at 12 02 17 PM

If you could just address this [user agent comment](https://github.com/Automattic/woocommerce-payments/pull/3277#discussion_r760869251), I feel this should be good to be merged. Thanks for your patience.

File: tests/e2e/utils/flows.js (hunk 3 above)
Comment (a-danae) [reply tests/e2e/utils/flows.js:402]: Here as well, I'd say to get a second opinion from someone who's more familiar with the tests than I am if you'd like to discuss that approach 🙂 

I think having it before the redirect to the blocks editor would be of less impact, I'm not sure about the consequences that having that User-Agent instead of having the default `puppeteer-debug wp-e2e-test` value could have in other tests. Looks like that's set in our [puppeteer-utils library](https://github.com/Automattic/puppeteer-utils/blob/master/src/setup-env.js#L16). Also, other tests are running fine with the default value, right? So, yep, not sure which path would be better. Let me know if we'd like to go that way and I can update it.

**Comment by a-danae** [comment]
> Have reset everything and verified that the tests work fine now with the changes and fail on develop, screenshot for reference.

@deepakpathania cool! My guess is that the WCB Checkout page was left without the checkout block because of the initial bug, thus the tests could never move past checking out. 

> If you could just address this user agent comment, I feel this should be good to be merged.

Replied there and asked in the channel as suggested. Thanks!

File: tests/e2e/utils/flows.js (hunk 3 above)
Comment (deepakpathania) [reply tests/e2e/utils/flows.js:402]: Discussing here: p1638884905038500-slack-C026J0AL8NS

File: tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js (hunk 2 above)
Comment (deepakpathania) [reply tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js:18]: Since this is unrelated to the change at hand, resolving this conversation, can open a separate issue for this post discussing with Solaris folks if they feel it makes sense.

File: tests/e2e/utils/flows.js (hunk 3 above)
Comment (a-danae) [reply tests/e2e/utils/flows.js]: Aand User-Agent updated for other tests in [0497e38](https://github.com/Automattic/woocommerce-payments/pull/3277/commits/0497e388b63146b1410826b2b93c668ebe868f3e).

I tried using the `beforeAll` for setting this but the User-Agent wasn't being updated for some reason. I tried this when we first started discussing this so I don't recall the details. I can give it another try if having it under `beforeAll` would be better than the current approach.

**Review by deepakpathania — APPROVED** [review]
LGTM. Thanks for all your hard work. :shipit:
