### PR TITLE
Fix PHPCS reports in account files

### LINKED ISSUE #8469: Account: fix WordPress.Security phpcs reports
Part of https://github.com/Automattic/woocommerce-payments/issues/8434

Check and fix reports in the following files:

* `includes/core/server/request/class-update-account.php`
* `includes/class-wc-payments-account.php`

### PR DESCRIPTION
**Pull request by dmallory42**
Fixes #8469

#### Testing instructions

* Checkout the branch `tweak/revert-phpcs-update-revert-pr`
* Open the `phpcs.xml.dist` file and temporarily remove the lines excluding any `WordPress.Security` sniffs.
* Run the following commands and observe the output:

```
./vendor/bin/phpcs --standard=phpcs.xml.dist --sniffs='WordPress.Security.EscapeOutput,WordPress.Security.ValidatedSanitizedInput' includes/core/server/request/class-update-account.php
```

```
./vendor/bin/phpcs --standard=phpcs.xml.dist --sniffs='WordPress.Security.EscapeOutput,WordPress.Security.ValidatedSanitizedInput' includes/class-wc-payments-account.php
```

For reference, here are the messages I observed running the command:

```

FILE: /Users/danielmallory/projects/wcpay/includes/core/server/request/class-update-account.php
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 61 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'. (WordPress.Security.EscapeOutput.ExceptionNotEscaped)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: /Users/danielmallory/projects/wcpay/includes/class-wc-payments-account.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 187 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'. (WordPress.Security.EscapeOutput.ExceptionNotEscaped)
-------------------------------------------------------------------------------------------------------------------------------------
```

* Confirm that this change makes sense and will fix the errors.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8498` or branch name `dev/8469-fix-phpcs-report` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=dev/8469-fix-phpcs-report) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 02be0e310987d2906c913b29b74da0ad39bc8e39
- Build time: 2024-03-27 11:58:53 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payments-account.php [hunk 1]
```diff
@@ -184,7 +184,7 @@ public function is_stripe_connected( bool $on_error = false ): bool {
 	public function try_is_stripe_connected(): bool {
 		$account = $this->get_cached_account_data();
 		if ( false === $account ) {
-			throw new Exception( __( 'Failed to detect connection status', 'woocommerce-payments' ) );
+			throw new Exception( esc_html__( 'Failed to detect connection status', 'woocommerce-payments' ) );
```
Comment (anu-rock) [inline includes/class-wc-payments-account.php:187]: Thanks for working on this quickly, but I wonder if HTML-safe escaping is really required here. As per the [method's docs](https://developer.wordpress.org/reference/functions/esc_html__/), doing so is useful when the translated string will be embedded in the page markup.

Comment (dmallory42) [reply includes/class-wc-payments-account.php:187]: Thanks for looking!

Since it doesn't harm to wrap it in. `esc_html`, I was following @marcinbot's suggestion on Slack: p1711452617673489/1711443600.104489-slack-CGGCLBN58

I think the message is one which _would_ be safe to return on the front-end if we chose to, so it seems approprate to wrap it. 

In fact I seem to remember seeing that message returned during the account connection in the past (although I've looked at the code to try and find where, so maybe it was my imagination! 😅 )

Comment (anu-rock) [reply includes/class-wc-payments-account.php:187]: Gotcha, sounds good.

**Review by anu-rock — APPROVED** [review]
LGTM :shipit:

**Review by mordeth — APPROVED** [review]
✅ LGTM!

**Comment by dmallory42** [comment]
Thanks for the reviews!
