### PR TITLE
Disable gateway when the currency is not supported in the country account

### LINKED ISSUE #2481: Disable gateway if using an unsupported currency
We should disable the WC Pay gateway if the store or customer is using a currency not [supported by Stripe](https://stripe.com/docs/currencies) to avoid customers from finding that out after checkout fails.

It might also be good to add an admin note indicating that the current currency is not supported.

### PR DESCRIPTION
**Pull request by daquinons**
Fixes #2481 

#### Changes proposed in this Pull Request

Disable gateway when the currency is not supported in the country account

- Adds methods in the Payment Gateway to disable it if the selected currency is not supported by Stripe, using the `presentment_currencies` inside of Account (requires 992-gh-Automattic/woocommerce-payments-server)
- Adds a notice in the admin view if the currency is not part of `presentment_currencies`.

After #2496 has been merged this PR is mostly a fallback, as the currencies are already filtered out using the same `presentment_currencies` in the Multi Currency selector.

#### Testing instructions

* Make [this method](https://github.com/Automattic/woocommerce-payments/blob/95ee60b6b7944be7909fa711593c4c654bef901e/includes/class-wc-payment-gateway-wcpay.php#L535) return false
* Go to checkout and see the payment form disabled
* Go to Payments settings and see the notice text.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -354,6 +354,7 @@ public function __construct(
 		add_action( 'woocommerce_update_options_payment_gateways_' . $this->id, [ $this, 'process_admin_options' ] );
 		add_action( 'admin_notices', [ $this, 'display_errors' ], 9999 );
 		add_action( 'woocommerce_woocommerce_payments_admin_notices', [ $this, 'display_test_mode_notice' ] );
+		add_action( 'woocommerce_woocommerce_payments_admin_notices', [ $this, 'display_not_supported_currency_notice' ] );
```
Comment (jessepearson) [inline includes/class-wc-payment-gateway-wcpay.php:357]: It may be better to add this notice to the admin as a whole and not just the payments page. Presently if they change the currency after setting up the gateway, they won't see the notice and their store will be broken.

File: includes/class-wc-payment-gateway-wcpay.php [hunk 2]
```diff
@@ -541,6 +561,25 @@ public function display_test_mode_notice() {
 		}
 	}
 
+	/**
+	 * Add notice explaining that the selected currency is not available.
+	 */
+	public function display_not_supported_currency_notice() {
```
Comment (jessepearson) [inline includes/class-wc-payment-gateway-wcpay.php:567]: If we change this to be displayed in the admin in general, we need to make sure to have a check here to make sure the user should be seeing the notice. An example of usage is here: https://github.com/Automattic/woocommerce-payments/blob/develop/includes/multi-currency/AdminNotices.php#L35-L37

```
		if ( ! current_user_can( 'manage_woocommerce' ) ) {
			return;
		}
```

**Review by jessepearson — CHANGES_REQUESTED** [review]
Looking good and works as described 😁 
Left a couple comments about the admin notice, let me know if you agree with where the notice should appear or not 👍

File: includes/class-wc-payment-gateway-wcpay.php (hunk 1 above)
Comment (daquinons) [reply includes/class-wc-payment-gateway-wcpay.php]: Thanks a lot for the suggestion! 😸 Totally on point 👍 

Changed in https://github.com/Automattic/woocommerce-payments/pull/2558/commits/36c42a038a07a152c29bb1706da2731d18d72e3e

File: includes/class-wc-payment-gateway-wcpay.php (hunk 2 above)
Comment (daquinons) [reply includes/class-wc-payment-gateway-wcpay.php:567]: Also added in https://github.com/Automattic/woocommerce-payments/pull/2558/commits/36c42a038a07a152c29bb1706da2731d18d72e3e

**Review by jessepearson — APPROVED** [review]
Thanks for the update, looks good! :shipit:
