### PR TITLE
Validate product data and subscription price data before sending requests to server

### LINKED ISSUE #3280: Avoid creating products in Stripe when we don't have the required args
### Describe the bug

There have been a couple of errors related to creating products in Stripe with some missing, required data. 

```
You passed an empty string for 'name'. We assume empty values are an attempt to unset a parameter; however 'name' cannot be unset. You should remove 'name' from your request or supply a non-empty value.
```

```
You passed an empty string for 'recurring[interval]'. We assume empty values are an attempt to unset a parameter; however 'recurring[interval]' cannot be unset. You should remove 'recurring[interval]' from your request or supply a non-empty value.
```
I haven't been able to replicate this second one. It relates to generating the price data so it may get removed eventually.  

### To Reproduce

1. Make sure to disable the WooCommerce Subscriptions plugin.
1. Go to Products > Add new 
2. Select **Simple subscription**
3. Add a description.
4. Leave the name blank
5. Enter a price of $0.
6. **Publish**

### Actual behavior

After following those steps you will get the error empty `'name'` error above. 

### Screenshots

Screen Shot 2021-11-03 at 3 04 05 pm

### Expected behavior

We should validate that we have all the required meta before attempting to create the subscription product in Stripe. 

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #3280 

#### Changes proposed in this Pull Request

1. I've removed most of the price ID handling from the product service class. This means: 
     - When creating and updating products we will now only send the product's name and description.
     - If a product has a price ID it will get archived if the product is deleted.
     - Untrashing a product will no longer reinstate (unarchive) the price. 
     - Price ID will remain stored in product meta until we decide to clean them up.
2. I've added a function to validate that we have the required product properties before creating/updating a product. 
   - Eg if a product doesn't have a name, we won't create a product in Stripe. This fixes the first error message mentioned on #3280 
3. I've added a function to validate the subscription data on checkout. If any of the required fields are missing or empty, we will throw an exception to prevent checkout and will no longer send that request off to server. This fixes the second error message mentioned on #3280

#### Testing instructions

**Product**

1. Go to **Product > Add new** from the admin dashboard.
2. Enter a product description, don't set any title, select Simple subscription as the type and hit publish.
3. Previously this would have resulted in a request to the server which would eventually fail. On this branch, it now gets caught before the request.

eg

```
INFO There was a problem updating the product #2164 in WC Pay: The product "name" is required.
```

**Subscription creation on checkout**

1. Purchase any standard subscription product via the checkout. You shouldn't get any errors. 
2. Add the following code snippet to your site.
3. Trying to checkout will result in an error notice preventing you from completing the checkout. 
4. The error message, in this case, is the exact same, we've just avoided sending invalid data to the server. 
5. Checking the `woocommerce-payments` log and you will find the following error.

```
INFO There was a problem creating the WCPay subscription. The subscription billing period cannot be any longer than one year. A billing period of "every 56 week(s)" was given.
``` 

```php
add_filter( 'woocommerce_subscription_get_billing_interval', function() {
	return 56;
} );
```

Make sure to remove that code snippet immediately after testing. It will turn all your subscriptions into "every 56 weeks/months/days" etc.

-------------------

- [x] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by james-allan** [comment]
I've just been running through some additional tests this morning and discovered that after trashing the product, it wasn't deleting the price ID and hash from the database. I've fixed that in a9a424b.

File: includes/subscriptions/class-wc-payments-subscription-service.php [hunk 1]
```diff
@@ -930,4 +932,51 @@ private function get_item_metadata( WC_Order_Item $item ) {
...
+			throw new Exception( 'The "items" arg is required to create the subscription.' );
+		}
+
+		foreach ( $subscription_data['items'] as $item_data ) {
+			$required_price_keys  = [ 'currency', 'product', 'unit_amount_decimal', 'recurring' ];
+			$required_period_keys = [ 'interval', 'interval_count' ];
+			$errors               = [];
+
+			foreach ( $required_price_keys as $required_key ) {
+				if ( empty( $item_data['price_data'][ $required_key ] ) ) {
```
Comment (aprea) [inline includes/subscriptions/class-wc-payments-subscription-service.php:958]: I think this will cause problems with a $0 subscription that have other costs associated with it.

**Steps to reproduce**
- Set up flat shipping to all countries (i.e. $10)
- Create a $0 subscription.
- As a shopper, add the product to the cart and navigate to checkout.
- Observe the subscription cost is $0 and shipping is $10.
- Attempt to purchase the subscription via WCPay card payment method.
- Observe the checkout error "There was a problem creating your subscription. Please try again or contact us for assistance."
- Observe the logs:

```
INFO There was a problem creating the WCPay subscription. The "unit_amount_decimal" line item properties are required to create the subscription.
```

I believe this would also happen for $0 subscriptions with a sign-up fee.

Could we use `! isset()` for `unit_amount_decimal'` and `empty()` for the other keys?

Comment (james-allan) [reply includes/subscriptions/class-wc-payments-subscription-service.php:962]: 😱 Oh good catch. I've replicated that and patched it with 498047e.

**Comment by james-allan** [comment]
It's only a log entry so doesn't matter too much but I just pushed up e7951fe to make sure the error message uses the correct singular or plural language. 

eg: 

```
INFO There was a problem creating the WCPay subscription. The "unit_amount_decimal", "currency", "product", "recurring" line item properties are required to create the subscription.
INFO There was a problem creating the WCPay subscription. The "unit_amount_decimal" line item property is required to create the subscription.
```

**Review by aprea — APPROVED** [review]
This LGTM ✅

I performed the following tests:

- Created a new subscriptions product with an empty product name.
- Confirmed the product was not created in Stripe.
- As a shopper, attempted to purchase the product.
- Received a checkout error and the following was present in the logs

```
INFO There was a problem creating the product #345 in WC Pay: The product "name" is required.
INFO There was a problem creating the WCPay subscription. The "product" line item properties are required to create the subscription.
```

Using the provided filter results in the expected error on checkout and corresponding log entry:

```
INFO There was a problem creating the WCPay subscription. The subscription billing period cannot be any longer than one year. A billing period of "every 56 month(s)" was given.
```

The following existing flows continue to work as expected:
- Purchase a $0 subscription with $10 shipping.
- Purchase a $10 subscription with $10 shipping.
- Updating a subscription product name in WP will update the corresponding subscription product in Stripe.
- Deleting a subscription product in WP will archive the corresponding subscription product in Stripe.

**Comment by james-allan** [comment]
Thanks for the review on this @aprea. Much appreciated. 🙂
