### PR TITLE
Fix for Express Checkout Element use with coupons

### LINKED ISSUE #9233: ECE w/ applied coupon error at checkout
### Describe the bug

When the ECE is being used and a coupon is applied and the customer clicks the ECE button (GPay/ApplePay), an error is thrown in the console and the customer cannot checkout with GPay/ApplePay.
The customer needs to refresh the page to make the UI unblock and checkout with another payment method.

### To Reproduce

- Create a coupon (e.g. 90% off)
- Add a product to the cart
- Go to the cart page
- Apply the coupon
- Attempt to use GooglePay/ApplePay

https://github.com/user-attachments/assets/20091830-f323-4c0b-a4cb-2f08b44e9aca

https://github.com/user-attachments/assets/0ad77cee-887e-4153-8f8e-e2a4a7e477d3

### Actual behavior

An error is thrown:

```
IntegrationError: The amount xxx is less than the total amount of the line items provided.
    at F (v3/?ver=3.0:1:36711)
    at v3/?ver=3.0:1:338245
    at v3/?ver=3.0:1:331691
F @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
Promise.then
N @ v3/?ver=3.0:1
resolve @ v3/?ver=3.0:1
resolve @ v3/?ver=3.0:1
eval @ index.js:268
(anonymous) @ v3/?ver=3.0:1
c._emit @ v3/?ver=3.0:1
c._emitEvent @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
c._emit @ v3/?ver=3.0:1
_handleMessage @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
(anonymous) @ v3/?ver=3.0:1
```

### Expected behavior

Customer should be able to checkout with the applied coupon with GPay/ApplePay

### Additional context

p1723041481419939-slack-C7U3Y3VMY

### PR DESCRIPTION
**Pull request by bborman22**
Fixes #9233 

#### Changes proposed in this Pull Request

It was reported to us that Google Pay and Apple Pay were not working when used with a coupon. This started happening after the conversion to use the Express Checkout Element (ECE). The same behavior did not cause an error with PaymentRequestButtons (PRB), so this is an additional check that has been added to the ECE implementation.

As described in the initial issue, the total payment amount was less than the sum of the line items. This was due to the fact that WooCommerce does not mark discount amounts as negative and so there was a mismatch on total amount being charged between what we provided to Stripe ECE vs the sum of the line items provided to Stripe's ECE.

To fix this, I identified the `total_discount` key on the line items returned from WC and in those cases turned the amount negative. I made this change in the centralized `normalizeLineItems` function so that it will apply to all actions and updates to the payment sheet.

#### Testing instructions

1. Create a store with a multiple coupon codes (one for Percentage Discount, Fixed Cart Discount, and Fixed Product Discount).
2. For the fixed product discount select a product you'll test with.
3. For one of the coupons (or a fourth coupon) mark Free Shipping with the coupon (this will involve providing a Free Shipping method in the tested shipping zone).

**Without this branch applied**
1. Add a product to the cart.
2. Go to the blocks checkout page and enter a coupon.
3. Confirm the coupon applied to correct discount.
4. Click on Google Pay.
5. Confirm that the payment sheet is not displayed and that there is a console error similar to: `The amount xxx is less than the total amount of the line items provided.`

**With this branch applied**
1. Add a product to the cart.
2. Go to the blocks checkout page and enter a coupon.
3. Confirm the coupon applied to correct discount.
4. Click on Google Pay.
5. Confirm the payment sheet opens with the correct amount.
6. Confirm payment and make sure the order goes through successfully.

Repeat the above steps with the branch applied on/with:
- Google Pay and Apple Pay
- Shortcode cart and Blocks cart
- Shortcode checkout and Blocks checkout
- With each of the three coupon types created above.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9234` or branch name `fix/9233-ece-coupons` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9233-ece-coupons) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: aef649e3e7b55a9e1502022288677b4cee3e2f06
- Build time: 2024-08-07 18:41:02 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by c-shultz** [comment]
I tested on Chrome and Safari with shortcode and Blocks checkout. I also did some exploratory testing around taxes (and displaying prices inclusive and exclusive of taxes). No errors were seen with and without the coupons applied.

**Review by c-shultz — CHANGES_REQUESTED** [review]
I found a corner case where it fails:
1. Add a product to cart
2. Apply fixed rate coupon that is great than item price

On the valiantly-prime.jurassic.ninja I used a $2 item with the 4off fixed discount. The resulting total is $10.00 for shipping only but the ECE fails 
image

**Comment by c-shultz** [comment]
The latest commit addresses the issue I saw 🎉

**Review by c-shultz — APPROVED** [review]
Testing OK now after the latest commit

File: client/express-checkout/utils/normalize.js [hunk 1]
```diff
@@ -7,14 +7,17 @@
...
  */
 export const normalizeLineItems = ( displayItems ) => {
-	return displayItems.map( ( displayItem ) =>
-		// The amount prop is already present on the item.
-		( {
-			...displayItem,
+	return displayItems.map( ( displayItem ) => {
+		let amount = displayItem?.amount ?? displayItem?.value;
+		if ( displayItem.key === 'total_discount' ) {
+			amount = -amount;
```
Comment (asumaran) [inline client/express-checkout/utils/normalize.js:13]: I wonder if the discount amount should come as a negative value from the server. That way, if another item that subtracts from the total is added, we won’t need to add another condition here.

**Review by asumaran — APPROVED** [review]
Tests as expected. I've only added a non-blocking comment for you @bborman22

File: client/express-checkout/utils/normalize.js (hunk 1 above)
Comment (bborman22) [reply client/express-checkout/utils/normalize.js:13]: I was wondering the same thing actually, what gave me pause is introducing a "new" pattern to the line / display items that get used. It seems everywhere else discount is described with a positive int. For example in the cart totals in WC core, the total_discount is stored as a positive int. I figured this approach is less risky for now, but like you said may need alterations if there is another line item that would need to be treated as a negative.

Comment (asumaran) [reply client/express-checkout/utils/normalize.js:13]: It makes sense, but in this case, it only applies to the object for display purposes – Stripe seem to use it though. The discount will continue to be handled as it is currently. Nevertheless we can handle later if we actually need it to be that way.
