### PR TITLE
Fix styling for enabled currencies components, cleaned up classnames.

### LINKED ISSUE #1920: Style customer multi-currency settings
PR with the settings is here: https://github.com/Automattic/woocommerce-payments/pull/1762

The React components need to be styled to match the designs specified in paJDYF-1gf-p2 . Screenshots are below.

Things to note: 
- "New settings" uses icons instead of edit/remove links, and those are already added.
- Issue created for exchange rate listing: https://github.com/Automattic/woocommerce-payments/issues/1923
- Add currency modal does not currently have a search function. https://github.com/Automattic/woocommerce-payments/issues/1924

Screen Shot 2021-05-26 at 10 22 19 PM
Screen Shot 2021-05-26 at 10 24 51 PM

### PR DESCRIPTION
**Pull request by jessepearson**
Fixes #1920

#### Changes proposed in this Pull Request

* Updates enabled currencies settings components to match styling of initial design.
* Clean up classnames and other markup.

#### Testing instructions

* Switch to the branch.
* Go to WooCommerce > Settings > Multi-Currency.
* Check that the Enabled Currencies list displays correctly.
* Click the Add Currencies button and check that the modal items display correctly.
* Click the Delete/Trash icon and and check that the model displays similar to the other items.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

File: client/multi-currency/enabled-currencies-list/modal-checkbox.js [hunk 1]
```diff
@@ -5,13 +5,13 @@
 import React from 'react';
 import { CheckboxControl } from '@wordpress/components';
 import { useCallback } from '@wordpress/element';
+import interpolateComponents from 'interpolate-components';
 
+// TODO: The currency.symbol may be a HTML element, so that needs to be fixed.
```
Comment (dmallory42) [inline client/multi-currency/enabled-currencies-list/modal-checkbox.js:10]: Just to confirm, am I right in thinking this is being done as part of #1922?

**Review by dmallory42 — APPROVED** [review]
Looks good to me, the styling looks great 🔥 and all looks good in the code. Left one comment but it's just to check we have an open issue for one of the TODOs. :)

File: client/multi-currency/enabled-currencies-list/modal-checkbox.js (hunk 1 above)
Comment (jessepearson) [reply client/multi-currency/enabled-currencies-list/modal-checkbox.js:10]: Yup, and the PR that addresses the issue removes that TODO: https://github.com/Automattic/woocommerce-payments/pull/1930/files#diff-993f704effe6480bba28b91407b5e87fbffd86a894528d7c108d142063d96255L10
