### PR TITLE
Fix Link button alignment in the Checkout block

### LINKED ISSUE #7929: Link by Stripe's `wcpay-stripelink-modal-trigger` button misaligned in Blocks checkout
### Describe the bug
When using Blocks checkout, the `wcpay-stripelink-modal-trigger` button is misaligned. It appears about 9px too high; as a result, it buts up against the top of the `wc-block-components-text-input` DIV — covering the border of the input field.

### To Reproduce

1. Activate Link by Stripe.
2. Ensure that the Checkout block is in use on the site.
3. Log into an account that already has an existing Link account (see https://woo.com/document/woopayments/payment-methods/link-by-stripe/#logged-in-user-experience)
4. Navigate to the checkout page.
5. Note that the `wcpay-stripelink-modal-trigger` button is too high.

### Actual behavior

When a logged in customer with an existing Link account navigates to the checkout page of a site using the Checkout block and WooPayments, the `wcpay-stripelink-modal-trigger` button is covers part of the email address input field (the `wc-block-components-text-input` DIV), which doesn't look very nice.

### Screenshots

Checkout block:
blocks checkout link by stripe

Shortcode checkout:
shortcode checkout link by stripe

### Expected behavior

The `wcpay-stripelink-modal-trigger` button is properly aligned on both shortcode and block checkout.

### PR DESCRIPTION
**Pull request by mdmoore**
Fixes #7929 

#### Changes proposed in this Pull Request

This ensures that the Stripe Link button is correctly aligned to the middle of the email input when viewing the Checkout block.

**Before**

**After**

#### Testing instructions

1. Activate Link by Stripe.
2. Ensure that the Checkout block is in use on the site.
3. Log into an account that already has an existing Link account (see https://woo.com/document/woopayments/payment-methods/link-by-stripe/#logged-in-user-experience)
4. Navigate to the checkout page.
5. Check that the Stripe Link button is vertically aligned to the middle on the email input

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7994` or branch name `fix/7929-link-button-alignment` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7929-link-button-alignment) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 6f6464eff140a76bc4411f0a0aa73f12478de503
- Build time: 2024-01-09 19:39:26 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/checkout/utils/upe.js [hunk 1]
```diff
@@ -322,7 +322,14 @@ export const blocksShowLinkButtonHandler = ( linkAutofill ) => {
...
 	stripeLinkButton.setAttribute( 'class', 'wcpay-stripelink-modal-trigger' );
-	stripeLinkButton.style.display = emailInput.value ? 'inline-block' : 'none';
+	stripeLinkButton.style.display = 'none';
+	if ( emailInput.value !== '' ) {
+		const linkButtonTop =
+			emailInput.offsetTop + ( emailInput.offsetHeight - 40 ) / 2;
+		stripeLinkButton.style.display = 'inline-block';
+		stripeLinkButton.style.top = `${ linkButtonTop }px`;
+	}
+
```
Comment (frosso) [inline client/checkout/utils/upe.js]: This seems to be working well! Have you considered using plain CSS for the positioning, instead of relying on JS?
I applied this CSS to the `button.wcpay-stripelink-modal-trigger` selector in `client/checkout/blocks/style.scss`, and it seems to be providing the same effect:
```css
    top: 50%;
    transform: translateY(-50%);
```

I thought of using plain CSS so that there would be less JS for the browser to execute 🤷

**Review by frosso — APPROVED** [review]
Changes are working well, just a minor suggestion

File: client/checkout/utils/upe.js (hunk 1 above)
Comment (mdmoore) [reply client/checkout/utils/upe.js]: Yeah, this is much better. Thank you for pointing it out! I had to add some specificity because the blocks checkout stylesheet is loaded on shortcode checkout which causes problems with the link button there.
