### PR TITLE
Better handling of failed payment_intent webhooks.

### LINKED ISSUE #3646: payment_intent.payment_failed intent webhook - make it ACH and BECS specific
Follow up to https://github.com/Automattic/woocommerce-payments/pull/3628

See p1642423688352800-slack-C01B8KNUYSW

We should avoid the situation we're in right now with the `payment_intent.succeeded` where the webhook changing the order status can lead to race conditions for payment methods it wasn't meant to be run on (as a backstory, we suspect that webhook was SEPA-only, but things were built up on top of it making it difficult to limit it to that method now).

So we should limit the processing of the `payment_intent.payment_failed` handler now, while it's still early, to avoid tricky problem reports in the future.

If we ever need that webhook to run in more scenarios, we can always extend the code with extra checks.

### PR DESCRIPTION
**Pull request by jessepearson**
Fixes #3646 

#### Changes proposed in this Pull Request

* Update the `process_webhook_payment_intent_failed` method.
  * Check to make sure the payment method type in the intent is a type we process failed intents for.
  * Check to make sure the payment method in the intent matches what is in the order. This is due to methods could leave the order as Pending Payment, which allows the customer to use a different method type to pay the order. We wouldn't want to allow the order to fail if it was already successful. Checking the order status alone doesn't help due to there are extensions to add order statuses. 
* Add `WC_Payments_Utils::compose_transaction_url` method, which was just copied from the main `WC_Payment_Gateway_WCPay` class.
* Add `WC_Payments_Utils::mark_payment_failed` method to mark a payment (order) as failed.
  * Creates note stating that the payment has failed, then adds any additional message passed to the method onto the note. 
  * Updates the `_intention_status` meta of the order to `failed`.
  * Updates the order status to Failed.
* Updated tests.

#### Testing instructions

* Tests should pass.

I found the easiest way to manually test is to use Postman, unless you have another method for sending in requests to the REST API.

* Use filter below to get around authentication, be sure to remove it afterwards.
* Set to POST to `https://YOURSITE/?rest_route=/wc/v3/payments/webhook`.
* Use the json below as the body of the post, updating where needed.
  * It's best to use an existing order, and get the payment intent and payment method ids out of it, then add those to the json data.
  * Set the order to Pending.
* After posting:
  * The order should be moved to Failed status.
  * There should be a note in the order that the payment failed with a link to the transactions, and it should state the account was not found.
  * There should be a note stating the order status changed from Pending to Failed.
  * Example screenshot is below.

filter:
```
add_filter( 'user_has_cap', function( $caps ) {
	$caps['manage_woocommerce'] = true;
	return $caps;
});
```

json:
```
{
    "type": "payment_intent.payment_failed",
    "data": {
        "object": {
            "id": "ADD_INTENT_ID_HERE",
            "object": "payment_intent",
            "charges": {
                "data": [
                    {
                        "failure_code": "no_account",
                        "payment_method": "ADD_PAYMENT_METHOD_ID_HERE",
                        "payment_method_details": {
                            "type": "us_bank_account"
                        }
                    }
                ]
            }
        }
    }
}
```

Screenshot on 2022-01-17 at 14-03-39

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) : _Add link here / 'QA Testing Not Applicable'_

### CODE REVIEW

File: includes/admin/class-wc-rest-payments-webhook-controller.php [hunk 1]
```diff
@@ -269,11 +269,27 @@ private function process_webhook_expired_authorization( $event_body ) {
 	 * @throws Invalid_Payment_Method_Exception When unable to resolve charge ID to order.
 	 */
 	private function process_webhook_payment_intent_failed( $event_body ) {
+		// Check to make sure we should process this according to the payment method.
+		$payment_method     = $this->get_payment_method_from_event( $event_body );
+		$actionable_methods = [
+			'us_bank_account',
+		];
```
Comment (ismaeldcom) [inline includes/admin/class-wc-rest-payments-webhook-controller.php:276]: What do you think about using `WCPay\Constants\Payment_Method` rather than hardcoded strings here?

File: includes/admin/class-wc-rest-payments-webhook-controller.php [hunk 2]
```diff
@@ -547,4 +563,25 @@ private function get_failure_message_from_event( $event_body ):string {
...
+	 *
+	 * @throws Rest_Request_Exception           Required parameters not found.
+	 *
+	 * @return array The payment method found, or null.
+	 */
+	private function get_payment_method_from_event( $event_body ) {
+		$event_data    = $this->read_rest_property( $event_body, 'data' );
+		$event_object  = $this->read_rest_property( $event_data, 'object' );
+		$event_charges = $this->read_rest_property( $event_object, 'charges' );
+		$charges_data  = $this->read_rest_property( $event_charges, 'data' );
```
Comment (marcinbot) [inline includes/admin/class-wc-rest-payments-webhook-controller.php:580]: I wonder if this could be made simpler with the `??` operator as well. We probably don't need to throw an exception if the caller function is going to return early anyway. Maybe if we simplify this to one line, we don't even need the `get_payment_method_from_event` function at all?

File: includes/admin/class-wc-rest-payments-webhook-controller.php (hunk 1 above)
Comment (jessepearson) [reply includes/admin/class-wc-rest-payments-webhook-controller.php:276]: Do you mean add more methods to the `Payment_Method` constants? If so, I think we can try that.

Comment (ismaeldcom) [reply includes/admin/class-wc-rest-payments-webhook-controller.php:276]: I already added BECS to it. But I mean to use the constant there rather than the id as a string.

Comment (jessepearson) [reply includes/admin/class-wc-rest-payments-webhook-controller.php]: Yup, that's what I meant, I just didn't say it clearly. Updated in https://github.com/Automattic/woocommerce-payments/pull/3650/commits/c9e696bd53ac8311f3d974e2e5baf9c564e36dbf

File: includes/admin/class-wc-rest-payments-webhook-controller.php (hunk 2 above)
Comment (jessepearson) [reply includes/admin/class-wc-rest-payments-webhook-controller.php]: I wasn't sure if we _needed_ to continue to use `read_rest_property` or not, but what you said about the early return makes sense. I've updated the code in https://github.com/Automattic/woocommerce-payments/pull/3650/commits/c9e696bd53ac8311f3d974e2e5baf9c564e36dbf

**Review by marcinbot — APPROVED** [review]
Looks good to me :shipit:

**Comment by htdat** [comment]
FYI. This PR has been available in WCPay 3.6.0 without going through manual stesp done by GlobalStep this week (Jan 18).
p1642611618163400-slack-C01BPL3ALGP
