### PR TITLE
Fix payment method title for Express Checkout Element orders

### LINKED ISSUE #9076: Fix payment method title for Express Checkout Element orders
### Describe the bug

When paying with Express Checkout Elements (`_wcpay_feature_stripe_ece` option set to `1`), this is how the order title looks like:

> Payment via Credit card / debit card (pi_...).

Whereas when paying with Payment Request Buttons (`_wcpay_feature_stripe_ece` option set to `0`), the order contains information about the specific wallet that was used:

> Payment via Apple Pay (WooPayments) (pi_...).

### To Reproduce

1. Enable ECE by setting the `_wcpay_feature_stripe_ece` option to 1.
2. As a shopper, navigate to a product page and checkout with Google Pay/Apple Pay.
3. As a merchant, navigate to **WooCommerce > Orders** and click the order you just created as a shopper.
4. Notice the order title mentions "Credit card / debit card".

### Expected behavior

There should be feature parity with PRBs, so the order titles must match.

### PR DESCRIPTION
**Pull request by ricardo**
Fixes #9076

#### Changes proposed in this Pull Request

- Add filter `woocommerce_gateway_title` to ECE implementation.
- Set payment method title for new orders through `woocommerce_checkout_order_processed`.
- Move and rename `add_order_meta`.
- Remove "Express Payment" pm title fallback.

#### Testing instructions

**Setup**

- Enable ECE by setting the `_wcpay_feature_stripe_ece` option to `1`.

**User checkout test**

1. As a shopper, use Safari to navigate to a product page and checkout with Apple Pay.
2. As a merchant, navigate to **WooCommerce > Orders** and click the order you just created as a shopper.
3. Ensure the payment method title is "Payment via Apple Pay (WooPayments)".
4. Repeat step 2, but checkout with Google Pay.
5. Ensure the payment method title is "Payment via Google Pay (WooPayments)".
6. Repeat the test with cart and checkout blocks.

**Pay for order test**

> [!NOTE]
> There's an open issue (#9048) where the order data is not being populated for pay for order checkouts, so the payment method title is not being rendered in the same way, but we can still make sure the payment method title is being saved correctly in the order meta.

1. As a merchant, navigate to **WooCommerce > Orders > Add order**.
2. Add any simple product item to the order and click "Create".
3. Open the "Customer payment page →" link.
4. Checkout using Google Pay.
5. As a merchant, refresh/open the "Edit order" page for this order.
6. Make sure you see a text "via Google Pay (WooPayments)" right after the "Paid" amount from the "Edit order" page.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9090` or branch name `fix/9076-payment-method-title-for-ece` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9076-payment-method-title-for-ece) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 1d04c2818699e43d899bd23745f03d77d505523f
- Build time: 2024-07-11 21:43:25 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/express-checkout/class-wc-payments-express-checkout-button-helper.php [hunk 1]
```diff
@@ -1033,6 +1053,39 @@ public function update_shipping_method( $shipping_methods ) {
...
+		if ( empty( $_POST['express_payment_type'] ) || ! isset( $_POST['payment_method'] ) || 'woocommerce_payments' !== $_POST['payment_method'] ) { // phpcs:ignore WordPress.Security.NonceVerification
+			return;
+		}
+
+		$express_payment_type   = wc_clean( wp_unslash( $_POST['express_payment_type'] ) ); // phpcs:ignore WordPress.Security.NonceVerification
+		$express_payment_titles = [
+			'apple_pay'  => 'Apple Pay',
+			'google_pay' => 'Google Pay',
+		];
+		$payment_method_title   = $express_payment_titles[ $express_payment_type ] ?? false;
```
Comment (ricardo) [inline includes/express-checkout/class-wc-payments-express-checkout-button-helper.php:1073]: @cesarcosta99 In `add_order_meta` there was a fallback title "Express Payment", which I believe was an adaptation of the legacy "Payment Request" title ([src](https://github.com/Automattic/woocommerce-payments/blob/78fba818fc3462ce4f475041a03cff0256ce2cad/includes/class-wc-payments-payment-request-button-handler.php#L752)), but I've removed it since Stripe no longer supports the fallback purple "Payment Request" button and other wallets should be predefined here.

**Comment by asumaran** [comment]
@ricardo will this work on the "Pay for order" page if ECE is used to pay?

**Comment by ricardo** [comment]
> will this work on the "Pay for order" page if ECE is used to pay?

@asumaran it will set the payment method order meta, but it won't be displayed at the top – see the screenshot in the testing instructions.

File: includes/express-checkout/class-wc-payments-express-checkout-button-helper.php [hunk 2]
```diff
@@ -329,6 +329,26 @@ public function get_product() {
...
+	/**
+	 * Used to get the order in admin edit page.
+	 *
+	 * @return WC_Order|WC_Order_Refund|bool
+	 */
+	public function get_current_order() {
+		global $theorder;
+		global $post;
+
+		if ( is_object( $theorder ) ) {
```
Comment (bborman22) [inline includes/express-checkout/class-wc-payments-express-checkout-button-helper.php:341]: Is there any value in checking the type of `$theorder` or `wc_get_order` here using something like `instanceof`? Or perhaps checking on the result of calling `get_current_order`? I wouldn't consider this a blocker as we have the `is_object` check in all these instances which would filter out the `bool` returned.

File: includes/express-checkout/class-wc-payments-express-checkout-button-helper.php (hunk 1 above)
Comment (bborman22) [reply includes/express-checkout/class-wc-payments-express-checkout-button-helper.php:1073]: I confirmed the fallback when this returns early is `Credit card / debit card` which is sufficient for a case where we couldn't determine the title successfully. 👍

**Review by bborman22 — APPROVED** [review]
I tested all the flows listed in both Safari and Chrome and found that the payment method title was correct in each instance. I tested out a few areas to confirm that the early returns still led to logical output and didn't lead to empty titles or things like that. I left one note about checkout object types, I don't think it's a blocker and may be overkill but wanted to mention it just in case. 

LGTM!

File: includes/express-checkout/class-wc-payments-express-checkout-button-helper.php (hunk 2 above)
Comment (ricardo) [reply includes/express-checkout/class-wc-payments-express-checkout-button-helper.php:341]: Oh I should have mentioned in the PR description, but this method in particular, was copied from the PRB integration ([src](https://github.com/Automattic/woocommerce-payments/blob/78fba818fc3462ce4f475041a03cff0256ce2cad/includes/class-wc-payments-payment-request-button-handler.php#L687-L700)). It was introduced more recently in #8150 but it has been validated and apparently has been working properly since then.

Based on that, we could keep it as is, unless you strongly prefer adding an extra check.

Comment (bborman22) [reply includes/express-checkout/class-wc-payments-express-checkout-button-helper.php:341]: Nope, that's totally acceptable to me! Thanks for the context on it!
