### PR TITLE
Align Payment Request pop-ups Pricing with Cart pricing display.

### LINKED ISSUE #4265: Prices for tax-inclusive products and shipping displaying oddly in payment request popups
### Describe the bug

If I have WC set to tax-inclusive pricing, but I try to pay via Apple/Google Pay, the tax is split out on to it's own line. This is probably confusing to customers, because it causes the product and shipping prices not to match what's on the product page, for example.

### To Reproduce

1. WC test site with WC Pay.
2. Enable Apple/Google Pay.
3. Enable tax-inclusive pricing.
4. Set a VAT-like tax rate of 20%
5. Set up a test product costing, for example, £25.95.
6. Set up a flat rate shipping for, say, £4.85.
7. Put the above item in your cart.
8. Try to pay with Apple Pay.

### Actual behavior

You'll see this:

image

The product price and shipping cost are technically accurate, and the total ends up being accurate as well, but this is potentially confusing to customers, since the product price shown here is different from what the customer just saw on the product page.

### Expected behavior

Ideally, Apple and Google Pay modals should obey how WC is formatting the prices. Something like: `$100.00 (incl. $XXX in tax)` or whatever.

5221483-zen

### PR DESCRIPTION
**Pull request by jessy-p**
Fixes #4265

#### Changes proposed in this Pull Request

Aligned the pricing on the Payment Request pop-ups to be inline with the cart pricing display, to avoid customer confusion.
 - Display the tax amount only if prices are not inclusive of tax
 - Add shipping tax amount if prices are not inclusive of tax
 
We are unable to include the `Excl. VAT` or `Incl. Tax` messages shown in the WooCommerce Cart as the Payment Request API will not allow sending text in the `amount` field. 

#### Testing instructions

**Specific**
In WooCommerce > Settings > Tax
- Check "I will enter I will enter prices inclusive of tax"
- Select "Display Prices" to "including tax".
- Set up a tax rate which applies to Shipping too.
- Validate the pricing displayed in Apple Pay and GPay pop-ups

**Generic**
In WooCommerce > Settings > Tax
- Set up different Tax configurations under WooCommerce > Settings > Tax
- Confirm that the pricing displayed in Apple Pay and GPay pop-ups are aligned with that shown on Cart.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions-for-WC-Payments-4.5.0#validate-pricing-display-on-payment-request-pop-ups)
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by jessy-p** [comment]
| Condition                                                           | Cart | Payment Request Pop-up (GPay) |
|---------------------------------------------------------------------|------|-------------------------------|
| I will enter prices exclusive of tax & display prices Excluding tax |     |                               |
| I will enter prices exclusive of tax & display prices Including tax |      |                               |
| I will enter prices inclusive of tax & display prices Including tax |      |                               |
| I will enter prices inclusive of tax & display prices Excluding tax |      |                               |

**Comment by jessy-p** [comment]
@aheckler  Testing results recorded above.

**Comment by aheckler** [comment]
@jessy-p Looks good! Just wanted to note here as well that this same issue affects the Stripe plugin, and was already recorded here: 

https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2087

Not sure if the fix can be ported over as-is, but might be worth looking into?

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 1]
```diff
@@ -1357,17 +1357,18 @@ protected function build_display_items( $itemized_display_items = false ) {
 		$items_total = wc_format_decimal( WC()->cart->cart_contents_total, WC()->cart->dp ) + $discounts;
 		$order_total = version_compare( WC_VERSION, '3.2', '<' ) ? wc_format_decimal( $items_total + $tax + $shipping - $discounts, WC()->cart->dp ) : WC()->cart->get_total( '' );
 
-		if ( wc_tax_enabled() ) {
+		if ( wc_tax_enabled() && 'incl' !== get_option( 'woocommerce_tax_display_cart' ) ) {
```
Comment (achyuthajoy) [inline includes/class-wc-payments-payment-request-button-handler.php:1360]: You might need to check whether `woocommerce_tax_display_shop` is inclusive of tax for handling express payments from product page.

**Review by achyuthajoy — DISMISSED** [review]
@jessy-p Here are the test results:

1. Using Google Pay from the product page, on the popup I'm seeing the product price exclusive of tax, and the tax line is missing. Shipping amount shows up as expected and the total amount is correct. Screenshot - https://d.pr/i/ygxa6p
2. Using Google Pay from the cart page & checkout page, everything looks ok. Shipping amount shows up as expected and the total amount is correct. Screenshot - https://d.pr/i/mJ76NS

Here are my WooCommerce Settings:

* Tax Settings - https://d.pr/i/OVt87D
* Tax Rates - https://d.pr/i/evOIBT
* Shipping - https://d.pr/i/eBDmZS

File: includes/class-wc-payments-payment-request-button-handler.php (hunk 1 above)
Comment (jessy-p) [reply includes/class-wc-payments-payment-request-button-handler.php:1362]: Resolved inconsistencies by using `woocommerce_tax_display_checkout` to control product price as well as tax line on the pop-up. Using different variables may lead to inconsistent calculations within the pop-up for merchants who set differing values between `woocommerce_tax_display_shop` and `woocommerce_tax_display_checkout`, even though that is not recommended.

File: includes/class-wc-payments-payment-request-button-handler.php [hunk 2]
```diff
@@ -1332,9 +1332,11 @@ protected function build_display_items( $itemized_display_items = false ) {
 
 				$product_name = $cart_item['data']->get_name();
 
+				$item_tax = wc_tax_enabled() && 'incl' !== get_option( 'woocommerce_tax_display_cart' ) ? 0 : $cart_item['line_subtotal_tax'];
```
Comment (zmaglica) [inline includes/class-wc-payments-payment-request-button-handler.php:1335]: Maybe you can move this piece of code: `wc_tax_enabled() && 'incl' !== get_option( 'woocommerce_tax_display_cart' )` into a separate function to prevent code duplication (check line 1362) which will make refactoring (if needed) in future easier.

It would also be nice to add check if `$cart_item['line_subtotal_tax']` exists before or write something like this

`$item_tax = wc_tax_enabled() && 'incl' !== get_option( 'woocommerce_tax_display_cart' ) ? 0 : ($cart_item['line_subtotal_tax']  ?? 0 ); `

Comment (jessy-p) [reply includes/class-wc-payments-payment-request-button-handler.php]: Done

**Review by zmaglica — APPROVED** [review]

File: includes/class-wc-payments-payment-request-button-handler.php (hunk 2 above)
Comment (jessy-p) [reply includes/class-wc-payments-payment-request-button-handler.php]: Done.
