### PR TITLE
fix: pay for order 3DS handling

### LINKED ISSUE #7788: Provide billing name and email on Pay-for-Order and Add Payment Method pages
### Describe the bug
Compared to the legacy card, legacy UPE & deferred intent creation UPE are not adding `name` and `email` to the `billing_address`. This leads to the customer name being empty in the transactions list.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29LQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a1296fc6a76e22bd9acb70f7f729d9d72b13bed/image.png)

### To Reproduce
1. Place order with a declined `4000000000000002` card
2. Navigate to `My account` -> `Orders` -> `Pay` and pay for the previously paid order
3. Open `Transactions` in the admin panel under `Payments -> Transactions` and confirm that `Customer` field is empty for this transaction's row

### Additional context
* [This implementation](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/classic/upe-deferred-intent-creation/payment-processing.js#L110-L138) should not check if the script is being run on the checkout page, but let script run on the pay-for-order and add-payment-method pages as well. Since billing fields can't be taken from the form on these pages, we should [fetch the fields from `wcpayCustomerData`](https://github.com/Automattic/woocommerce-payments/blob/6.8.0/client/checkout/classic/index.js#L50-L51) which comes from the back-end
* Check how it works [in the legacy card implementation](https://github.com/Automattic/woocommerce-payments/blob/6.8.0/client/checkout/classic/index.js#L356-L367), where [`generatePaymentMethodRequest`](https://github.com/Automattic/woocommerce-payments/blob/6.8.0/client/checkout/api/index.js#L140) sets [billing and address details](https://github.com/Automattic/woocommerce-payments/blob/6.8.0/client/checkout/api/index.js#L161-L196) by taking the name & email data from the `preparedCustomerData` which comes from the back-end for pay-for-order and add-payment-method pages
* This issue is assigned to the `low` priority since it's present in the legacy UPE and there haven't been any bug reports related to it.

### LINKED ISSUE #7799: Ensure consistent alignment of UI spinner with legacy card during 3DS processing on Pay-for-Order page
### Describe the bug
The deferred intent creation UPE needs to be slightly aligned with the way how legacy card solution handles the 3DS payments in the pay-for-order page UI.

At the moment
* there is no loading spinner when waiting for the 3DSv2 flow to be completed
* error message doesn't appear in case the payment isn't eventually authorized

> 💡 46848adef168bb418a3825e7496fd9e43ddf4244 fixes both points from above but it requires a bit more polishing to achieve better code re-usability

Here's how the first bullet point looks in practice for deferred UPE

https://github.com/Automattic/woocommerce-payments/assets/22319444/9feeaa2b-c276-475e-a0fa-daf130f5303c

While here's the same use case but with the legacy UPE

https://github.com/Automattic/woocommerce-payments/assets/22319444/61594f94-c2e5-480c-b616-5ce44e8bc5f5

### LINKED ISSUE #7871: Console error on pay for order page
### Describe the bug

On the "Pay for order" page, I noticed this console error:
Screenshot 2023-12-11 at 9 39 57 PM

I also noticed that the page refreshes when clicking the "Pay for order" button with a 3DS card - which might be related:

### To Reproduce

- Ensure you have multi-currency enabled
- In `wp-admin`, create a new order via the **WC > Orders > Add order** CTA
- Add a few items
- Save the order
- Click the "Customer payment page" link
Screenshot 2023-12-11 at 9 45 14 PM
- Use a 3DS card (might be optional)

### Actual behavior

Error appears in the console.
On "Pay for order" CTA click, page refreshes (but still allows for the payment)

### Expected behavior

No console error.
Ideally, also no page refresh.

### PR DESCRIPTION
**Pull request by frosso**
Fixes https://github.com/Automattic/woocommerce-payments/issues/7799
Fixes https://github.com/Automattic/woocommerce-payments/issues/7871
Fixes https://github.com/Automattic/woocommerce-payments/issues/7788

#### Testing instructions

* Create a manual order via the merchant's backend (in WooCommerce > Orders)
* Click the "Customer payment page" link on the newly created order
* Use a 3DS card & decline (`4000000000003220`) or use the "generic decline" card (`4000000000000002`)
* The error message should be displayed upon redirection
* Enter new card details, make a successful payment
* The details should be displayed in the merchant's backend, in Payments > Transactions
Screenshot 2024-01-11 at 6 27 36 PM

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8006` or branch name `fix/7799-pay-for-order-error-message` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7799-pay-for-order-error-message) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 079774f7613c43a495bc55509f4d72279102195e
- Build time: 2024-01-12 07:34:43 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payments-checkout.php [hunk 1]
```diff
@@ -277,15 +277,6 @@ public function get_payment_fields_js_config() {
...
 
-	/**
-	 * Checks if WooPay is enabled.
-	 *
-	 * @return bool - True if WooPay enabled, false otherwise.
-	 */
-	private function is_woopay_enabled() {
-		return WC_Payments_Features::is_woopay_eligible() && 'yes' === $this->gateway->get_option( 'platform_checkout', 'no' ) && WC_Payments_Features::is_woopay_express_checkout_enabled();
-	}
-
```
Comment (frosso) [inline includes/class-wc-payments-checkout.php:288]: This doesn't seem to be used anywhere anymore

File: client/checkout/classic/3ds-flow-handling.js [hunk 2]
```diff
@@ -22,37 +22,27 @@ const cleanupURL = () => {
 };
 
 export const showAuthenticationModalIfRequired = ( api ) => {
-	const url = window.location.href;
 	const paymentMethodId = document.querySelector( '#wcpay-payment-method' )
 		?.value;
 
 	const confirmation = api.confirmIntent(
-		url,
```
Comment (frosso) [inline client/checkout/classic/3ds-flow-handling.js:30]: I just inlined it, since it didn't matter whether it was a constant

File: client/checkout/classic/3ds-flow-handling.js [hunk 3]
```diff
@@ -22,37 +22,27 @@ const cleanupURL = () => {
...
+		window.location.href,
 		shouldSavePaymentPaymentMethod() ? paymentMethodId : null
 	);
 
 	// Boolean `true` means that there is nothing to confirm.
 	if ( confirmation === true ) {
-		return;
```
Comment (frosso) [inline client/checkout/classic/3ds-flow-handling.js:36]: I changed the function to return a promise, so that the caller could block/unblock the UI. This early return is ensuring that the return type is consistent.

File: client/checkout/utils/upe.js [hunk 4]
```diff
@@ -166,8 +166,8 @@ export const generateCheckoutEventNames = () => {
 		.join( ' ' );
 };
 
-export const appendPaymentMethodIdToForm = ( form, paymentMethodId ) => {
-	form.append(
+export const appendPaymentMethodIdToForm = ( $form, paymentMethodId ) => {
```
Comment (frosso) [inline client/checkout/utils/upe.js:169]: Ensuring consistent naming convention - prepending the `$` in the name of the `form` argument, since it's a jQuery object

File: client/checkout/utils/fingerprint.js [hunk 5]
```diff
@@ -27,14 +27,14 @@ export const getFingerprint = async () => {
 /**
  * Appends a hidden input with the user fingerprint to the checkout form.
  *
- * @param {Object} form        The jQuery Checkout form object.
+ * @param {Object} $form        The jQuery Checkout form object.
  * @param {string} fingerprint User fingerprint.
  */
-export const appendFingerprintInputToForm = ( form, fingerprint = '' ) => {
+export const appendFingerprintInputToForm = ( $form, fingerprint = '' ) => {
```
Comment (frosso) [inline client/checkout/utils/fingerprint.js:33]: Ensuring consistent naming convention - prepending the `$` in the name of the `form` argument, since it's a jQuery object

**Review by timur27 — APPROVED** [review]
@frosso great job with fixing three problems in one go and also providing some improvements here and there, really appreciate it! Code looks good and testing went successful so I'm approving and leaving testing details below: 

* I confirm https://github.com/Automattic/woocommerce-payments/issues/7799 is addressed as the UI blocks successfully while paying with 3DS payment method on the pay-for-order page
* https://github.com/Automattic/woocommerce-payments/issues/7871 is fixed as well as there's no console error on the pay for order page when BNPLs are enabled
* the transaction is fed with the customer details so https://github.com/Automattic/woocommerce-payments/issues/7788 is fixed as well


#### Screenshots for the last bullet point
image

image
