### PR TITLE
Fix/1587 giropay transaction page

### LINKED ISSUE #1587: Fix Giropay transaction page
The transaction page for a Giropay transaction has several JS errors preventing it from loading. This is identical to the [Sepa issue](https://github.com/Automattic/woocommerce-payments/issues/1472) and the fix can be built out based on the [Sepa fix](https://github.com/Automattic/woocommerce-payments/pull/1579).

The goal of this issue is to successfully display the transaction page for Giropay transactions.

### PR DESCRIPTION
**Pull request by bborman22**
Fixes #1587 

#### Changes proposed in this Pull Request

Fix Giropay Transaction Details Page

This PR addresses some JS issues that was preventing the transaction detail page from displaying for Giropay payments. The biggest difference between Giropay and the other implemented payment methods was the lack of a card number that fit into the `last4` pattern. Instead we are just provided a bank name and BIC. For readability I used the bank code (essentially a bank name abbreviation) in place of the last 4. This also meant conditionalizing the 4 bullets prefix on the last 4 display.

Otherwise, the change is straightforward and should cover the necessary details on a transaction.

#### Testing instructions

- Place an order using the Giropay payment method
- As admin, go into the order details page and click on the payment ID link (pi_xxxx)
- Able to view the payment transaction details for a Giropay transaction

Giropay-transaction

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

File: client/components/payment-method-details/index.js [hunk 1]
```diff
@@ -12,14 +13,19 @@ const PaymentMethodDetails = ( props ) => {
...
 		<span className="payment-method-details">
 			<span
 				className={ `payment-method__brand payment-method__brand--${ brand }` }
 			/>
-			&nbsp;••••&nbsp;
-			{ paymentMethod.last4 }
+			{ paymentMethod.last4 && (
+				<Fragment>&nbsp;&bull;&bull;&bull;&bull;&nbsp;</Fragment>
+			) }
+			{ paymentMethodAbbr }
```
Comment (frosso) [inline client/components/payment-method-details/index.js:28]: (minor) could be shortened without duplicating the check on `paymentMethod.last4` on L16 by
```suggestion
			{ paymentMethod.last4 ? (
				<Fragment>&nbsp;&bull;&bull;&bull;&bull;&nbsp; { paymentMethod.last4 }</Fragment>
			) : ( paymentMethod.bank_code ) }
```

File: client/payment-details/payment-method/giropay/index.js [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+	bankName: 'bank name placeholder',
+	bic: 'bic placeholder',
+	id: 'id placeholder',
+	name: 'name placeholder',
+	email: 'email placeholder',
+	formattedAddress: 'address placeholder',
+	country: 'country placeholder',
+};
+
+const GiropayDetails = ( { charge = {}, isLoading } ) => {
```
Comment (frosso) [inline client/payment-details/payment-method/giropay/index.js:51]: (minor) since there's already a check on `charge` on L53 there should be no need for `= {}`.
Or can `charge` be falsy otherwise? In that case I think we can change L53 from `charge && charge.payment_method_details` to `charge.payment_method_details`, since there's `= {}`

File: client/payment-details/payment-method/giropay/index.js [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+	const details =
+		charge && charge.payment_method_details
+			? formatPaymentMethodDetails( charge )
+			: paymentMethodPlaceholders;
+
+	// eslint-disable-next-line camelcase
```
Comment (frosso) [inline client/payment-details/payment-method/giropay/index.js:57]: Is this still needed?

File: client/payment-details/payment-method/index.js [hunk 4]
```diff
@@ -12,14 +12,19 @@ import { Card, CardBody, CardHeader } from '@wordpress/components';
 import Loadable from 'components/loadable';
 import CardDetails from './card';
 import SepaDetails from './sepa';
+import GiropayDetails from './giropay';
 
 const PaymentDetailsPaymentMethod = ( { charge = {}, isLoading } ) => {
-	let PaymentMethodDetails = SepaDetails;
```
Comment (frosso) [inline client/payment-details/payment-method/index.js:17]: Looks like before it was defaulting to `SepaDetails` when `charge.payment_method_details` or when `charge.payment_method_details.type` were falsy, now it's defaulting to `CardDetails` - is this safe?

**Review by frosso — APPROVED** [review]
Just a few minor questions/comments, changes look good 👍

File: client/payment-details/payment-method/index.js (hunk 4 above)
Comment (bborman22) [reply client/payment-details/payment-method/index.js:17]: So I was able to confirm that all three payment methods still worked with this change. The choice for default was arbitrary, but felt that given the history of card being the primary payment method before this, having it be the default made sense here? If there are concerns though it's no issue to change it back. @superdav42 would there be any concerns with swapping the default to card here?

Comment (frosso) [reply client/payment-details/payment-method/index.js:17]: > The choice for default was arbitrary, but felt that given the history of card being the primary payment method before this, having it be the default made sense here?

Got it, that makes sense, thanks! 👍

Comment (superdav42) [reply client/payment-details/payment-method/index.js:17]: Yea, no problems with changing the default to CardDetails.
I think a better pattern to use in this case is actually to not have a default but throw an exception that could be used to show a generic error when an unexpected type is encountered. I'm not sure if we have such exception handling in place but it'd be a good future enhancement. Merchants seeing a white page when an error occurs is never a good UX.

Comment (frosso) [reply client/payment-details/payment-method/index.js:17]: In that case [`componentDidCatch`](https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries) would probably be a good solution

File: client/payment-details/payment-method/giropay/index.js (hunk 2 above)
Comment (bborman22) [reply client/payment-details/payment-method/giropay/index.js:51]: I went with the second option to only check against `charge.payment_method_details`, thanks!

**Review by frosso — APPROVED** [review]
Still looks good

**Comment by bborman22** [comment]
Thanks for taking a look! I've cleaned up these few spots with the latest commit!
