### PR TITLE
Fix PHP Deprecated: Hook woocommerce_rest_api_option_permissions

### LINKED ISSUE #7864: PHP Deprecated:  Hook woocommerce_rest_api_option_permissions is deprecated since version 6.3.0
### Describe the bug

After the update to WooCommerce Payments 6.9.1, the following notice is triggered:

```
PHP Deprecated:  Hook woocommerce_rest_api_option_permissions is deprecated since version 6.3.0 with no alternative available. in /wordpress/core/6.4.2/wp-includes/functions.php on line 6031
```

### To Reproduce

1. Enable WP_DEBUG_LOG
2. Update WooCommerce Payments to version 6.9.1.
3. Debug logs reveal the notice

### Actual behavior
The notice is triggered after the update.

Most likely because of this: https://github.com/Automattic/woocommerce-payments/blob/6.9.0/includes/class-wc-payments.php#L581

Which has been deprecated by WooCommerce Admin here: https://github.com/woocommerce/woocommerce/blob/8.3.1/plugins/woocommerce/src/Admin/API/Options.php#L149

### Screenshots
Replicated:

Screenshot 2023-12-08 at 7 30 08 AM

### Expected behavior
We would migrate to the new version of that hook and the notice would not be triggered.

### Desktop (please complete the following information):

* OS: Sonoma
* Browser: Chrome

### PR DESCRIPTION
**Pull request by htdat**
Fixes #7864

## TODOs: 

- [x] Implement changes for other options. 
- [x] Remove the hook completely
- [x] Fix and add tests 
#### Changes proposed in this Pull Request

- Add a separate controller for endpoint: `/wp-json/wc/v3/payments/settings/{option_key}`
- Add `saveOption` in JS code so that we can send the direct REST API request to the endpoint above. This will replace `updateOptions` provided by Woo core, which uses the Woo core Options REST API. 

#### Testing instructions

* Follow to test the Fraud Protection Tour https://github.com/Automattic/woocommerce-payments/pull/10558

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10636` or branch name `fix/7864-deprecated-woocommerce_rest_api_option_permissions` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7864-deprecated-woocommerce_rest_api_option_permissions) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: ecbdedc02a0db39079b154696d1fc2669d10f541
- Build time: 2025-03-28 04:01:07 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/admin/class-wc-rest-payments-settings-option-controller.php [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+	}
+
+	/**
+	 * Verify access.
+	 *
+	 * @return bool
+	 */
+	public function check_permission(): bool {
+		return current_user_can( 'manage_woocommerce' );
+	}
```
Comment (RadoslavGeorgiev) [inline includes/admin/class-wc-rest-payments-settings-option-controller.php]: The parent controller already has the exact same permissions check.

File: includes/admin/class-wc-rest-payments-settings-option-controller.php [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+
+	/**
+	 * Update the option value.
+	 *
+	 * @param WP_REST_Request $request The request object.
+	 * @return WP_REST_Response
+	 */
+	public function update_option( WP_REST_Request $request ) {
+		$option_key = $request->get_param( 'option_key' );
+		$value      = $request->get_param( 'value' );
```
Comment (RadoslavGeorgiev) [inline includes/admin/class-wc-rest-payments-settings-option-controller.php]: I'm wondering whether we can force the value to either be a boolean, or an array with boolean values, based on the options that are currently being saved. 🤔

File: client/data/settings/actions.js [hunk 3]
```diff
@@ -281,3 +282,11 @@ export function* submitStripeBillingSubscriptionMigration() {
 		'scheduleStripeBillingMigration'
 	);
 }
+
+export function saveOption( optionKey, value ) {
+	directApiFetch( {
+		path: `${ NAMESPACE }/settings/${ optionKey }`,
+		method: 'post',
+		data: { value },
+	} ).catch( () => {} );
```
Comment (RadoslavGeorgiev) [inline client/data/settings/actions.js]: Does this empty catch mimic `updateOptions` from `wc/admin/options`?

I'd at least `console.error()` here.

Note: I realize that this might be PoC code.

**Review by RadoslavGeorgiev — COMMENTED** [review]
The approach looks great! 😍 

I actually like that we have a specific controller for this, rather than extending controllers from core that might or might not be meant for our needs.

File: includes/admin/class-wc-rest-payments-settings-option-controller.php [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+ */
+class WC_REST_Payments_Settings_Option_Controller extends WC_Payments_REST_Controller {
+
+	/**
+	 * List of allowed option keys that can be updated via the REST API.
+	 *
+	 * @var array
+	 */
+	private const ALLOWED_OPTIONS = [
+		'wcpay_frt_discover_banner_settings',
```
Comment (allie500) [inline includes/admin/class-wc-rest-payments-settings-option-controller.php]: You can remove this one. `wcpay_frt_discover_banner_settings` was removed today in PR #10635.

**Review by allie500 — COMMENTED** [review]
Thanks for working on this Dat! I left one inline comment for an option that was removed by another PR today. So we can remove that one.

File: includes/admin/class-wc-rest-payments-settings-option-controller.php (hunk 2 above)
Comment (htdat) [reply includes/admin/class-wc-rest-payments-settings-option-controller.php]: The most tricky ones are:

| Option Name | Value Format | Value Example |
|------------|--------------|---------------|
| `woocommerce_dismissed_todo_tasks`, `woocommerce_remind_me_later_todo_tasks`, `woocommerce_deleted_todo_tasks` | `array<string>` | `['reconnect-wpcom']` |
| `wcpay_capability_request_dismissed_notices` | `array<string, boolean>` | `['jcb' => true]` |
| `wcpay_duplicate_payment_method_notices_dismissed` | `array<string, array<string>>` | `['bancontact' => ['woocommerce_payments', 'another_plugin']` |

But the good thing is that they seem not really be used. I am not seeing any option of this site, for `_dimissed_`, at least, all current tasks have `isDimissable` with value `false` or `null` (equal to `false`).

https://github.com/Automattic/woocommerce-payments/pull/2787

Probably that we might have two endpoints to support for two use cases.

File: client/data/settings/actions.js (hunk 3 above)
Comment (htdat) [reply client/data/settings/actions.js]: Not yet, but we can dispatch error notices.

File: includes/admin/class-wc-rest-payments-settings-option-controller.php (hunk 2 above)
Comment (htdat) [reply includes/admin/class-wc-rest-payments-settings-option-controller.php]: I've reviewed more options and here how is their value format looks like: 

| Option Name | Value Format | Value Example |
|------------|--------------|---------------|
| `woocommerce_dismissed_todo_tasks`, `woocommerce_remind_me_later_todo_tasks`, `woocommerce_deleted_todo_tasks` | `array<string>` | `['reconnect-wpcom']` |
| `wcpay_capability_request_dismissed_notices` | `array<string, boolean>` | `['jcb' => true]` |
| `wcpay_duplicate_payment_method_notices_dismissed` | `array<string, array<string>>` | `['bancontact' => ['woocommerce_payments', 'another_plugin']` |

Given this nature, I think we might simply check values to be either `boolean` or `array`. WDYT?

Comment (RadoslavGeorgiev) [reply includes/admin/class-wc-rest-payments-settings-option-controller.php]: That works, as we need a quick solution.

A `switch` like this could make a ton of sense:

```php
switch ( $request->get_param( 'option_key' ) ) {
	case 'X':
	case 'Y':
		// validate boolean;
		break;
	
	case 'Z':
		// check for array with boolean values;
		break;
	
	default:
		throw new Exception( 'Please implement validation for ' . $request->get_param( 'option_key' ) );
}
```

However, given how hard it is to get the right modal/banner to appear, you'd need to spend about an hour to check that each option works. With 14 options, you'd need a day or two to make sure that all options are validated properly. Then the reviewer would need to do the same, and that's just not feasible at the moment.

Comment (htdat) [reply includes/admin/class-wc-rest-payments-settings-option-controller.php]: Addressed at 84029a02281dd755e8186b34986ebdb411cd1384

File: client/data/settings/actions.js (hunk 3 above)
Comment (htdat) [reply client/data/settings/actions.js]: Addressed 0d5d493344c59ede904847c0dd92a0f7aad16388

File: includes/admin/class-wc-rest-payments-settings-option-controller.php (hunk 4 above)
Comment (htdat) [reply includes/admin/class-wc-rest-payments-settings-option-controller.php]: Addressed dc2a9037858b80240c17a15d5644219345beb4fe

**Review by RadoslavGeorgiev — APPROVED** [review]
The changes look excellent!

Of course, I could not test all individual options, but the code changes make sense. I only tested the new Fraud Protection tools on a Jurassic Ninja site, and it worked as expected.

Maybe a second set of eyes (looking at you @allie500 🤣) would be a great sanity check. Otherwise :shipit:

File: includes/admin/class-wc-rest-payments-settings-option-controller.php [hunk 5]
```diff
@@ -0,0 +1,113 @@
...
+		'woocommerce_deleted_todo_tasks',
+		'wcpay_fraud_protection_welcome_tour_dismissed',
+		'wcpay_capability_request_dismissed_notices',
+		'wcpay_onboarding_eligibility_modal_dismissed',
+		'wcpay_connection_success_modal_dismissed',
+		'wcpay_next_deposit_notice_dismissed',
+		'wcpay_duplicate_payment_method_notices_dismissed',
+		'wcpay_exit_survey_dismissed',
+		'wcpay_instant_deposit_notice_dismissed',
+		'wcpay_date_format_notice_dismissed',
```
Comment (mgascam) [inline includes/admin/class-wc-rest-payments-settings-option-controller.php]: Can you remove the 'wcpay_date_format_notice_dismissed' option please. The notice that used this option was already [removed](https://github.com/Automattic/woocommerce-payments/pull/10129) but we missed this occurence. Thanks!

File: client/overview/modal/connection-success/index.tsx [hunk 6]
```diff
@@ -18,15 +18,12 @@ export const ConnectionSuccessModal = () => {
...
-	const { updateOptions } = useDispatch( 'wc/admin/options' );
 
 	const onDismiss = async () => {
 		setIsDismissed( true );
 
 		// Update the option to mark the modal as dismissed.
-		await updateOptions( {
-			wcpay_connection_success_modal_dismissed: true,
-		} );
+		await saveOption( 'wcpay_connection_success_modal_dismissed', true );
```
Comment (allie500) [inline client/overview/modal/connection-success/index.tsx]: Nitpick: We can remove `await` here.

File: client/overview/task-list/index.js [hunk 7]
```diff
@@ -52,9 +52,7 @@ const TaskList = ( { overviewTasksVisibility, tasks } ) => {
 		dismissedTasks.splice( dismissedTodoTasks.indexOf( key ), 1 );
 		setVisibleTasks( getVisibleTasks() );
 
-		await updateOptions( {
-			[ optionName ]: updatedDismissedTasks,
-		} );
+		await saveOption( optionName, updatedDismissedTasks );
```
Comment (allie500) [inline client/overview/task-list/index.js]: Nitpick: We can remove `await` here.

File: client/overview/task-list/index.js [hunk 8]
```diff
@@ -68,9 +66,7 @@ const TaskList = ( { overviewTasksVisibility, tasks } ) => {
 		dismissedTasks.push( key );
 		setVisibleTasks( getVisibleTasks() );
 
-		await updateOptions( {
-			[ optionName ]: [ ...dismissedTasks ],
-		} );
+		await saveOption( optionName, [ ...dismissedTasks ] );
```
Comment (allie500) [inline client/overview/task-list/index.js]: Nitpick: We can remove `await` here.

File: client/overview/task-list/index.js [hunk 9]
```diff
@@ -120,21 +116,20 @@ const TaskList = ( { overviewTasksVisibility, tasks } ) => {
 		delete remindMeLaterTodoTasks[ key ];
 		setVisibleTasks( getVisibleTasks() );
 
-		await updateOptions( {
-			woocommerce_remind_me_later_todo_tasks: updatedRemindMeLaterTasks,
-		} );
+		await saveOption(
```
Comment (allie500) [inline client/overview/task-list/index.js]: Nitpick: We can remove `await` here.

File: client/plugins-page/index.js [hunk 10]
```diff
@@ -41,9 +39,7 @@ const PluginsPage = () => {
 		const currentDate = new Date();
 
 		// Update modal dismissed option.
-		await updateOptions( {
-			wcpay_exit_survey_last_shown: currentDate,
-		} );
+		await saveOption( 'wcpay_exit_survey_last_shown', currentDate );
```
Comment (allie500) [inline client/plugins-page/index.js]: Nitpick: We can remove `await` here.

**Review by allie500 — APPROVED** [review]
Thanks for the comprehensive fix! I left some nitpicks regarding use of `await`. There's also an unused import of `useDispatch` on line 9 in `client/overview/modal/progressive-onboarding-eligibility/index.tsx` that we can remove.

I tested the `wcpay_fraud_protection_welcome_tour_dismissed` flow and it worked as expected. 

Aside from the `await` and unused import nitpicks, I'm approving the PR. 

:shipit:

File: includes/admin/class-wc-rest-payments-settings-option-controller.php (hunk 5 above)
Comment (htdat) [reply includes/admin/class-wc-rest-payments-settings-option-controller.php]: Addressed ecbdedc02a0db39079b154696d1fc2669d10f541

File: client/overview/modal/connection-success/index.tsx (hunk 6 above)
Comment (htdat) [reply client/overview/modal/connection-success/index.tsx]: Addressed ecbdedc02a0db39079b154696d1fc2669d10f541
