### PR TITLE
Fix for fatal error when saving changes on Multi-Currency page

### LINKED ISSUE #2180: [GlobalStep] "Fatal error: Uncaught Error" is triggered upon clicking "Save Changes" button on "Multi currency" screen.
## Bug Description:
"Fatal error: Uncaught Error" is triggered upon clicking "Save Changes" button on "Multi currency" screen.

## Environment:
Woocommerce Version : WooCommerce 5.4.1
WooCommerce Payments: v2.6.0-test-2

PC:
Windows 10, Mac 10.14.6
Chrome(Version 90.0.4430.93) 
Firefox(Version 88.0)
Safari: v13.1.1

## Pre-requisites:
1. Set _wcpay_feature_customer_multi_currency option in the wp_options table to 1. Or use the following snippet: update_option( '_wcpay_feature_customer_multi_currency', '1' ); in the Code Snippet plugin.

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete setup wizard using United States address as a store address and without selecting WC Payments on Business Details step.
1. Go to Plugins->Add New->Upload plugin.
1. Install and activate WooCommerce Payments plugin v2.6.0.
1. Go to Payments->Set up to trigger KYC flow.
1. Complete the KYC flow.
1. Go to Payment->Setting->Multi-currency.
1. Add Euro currency.
1. Click on "SaveChages" button.
1. Observe that "Fatal error: Uncaught Error" is triggered upon clicking "Save Changes" button on "Multi currency" screen.

## Actual Result:
"Fatal error: Uncaught Error" is triggered upon clicking "Save Changes" button on "Multi currency" screen.

## Expected Result:
User should be able to save chages successfully without any error.

## Video:

https://user-images.githubusercontent.com/41110392/122021137-03cd7980-cde3-11eb-9eff-6f7bca3dae4d.mp4

Woocommerce bugs uploading.

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WordPress address (URL): https://supreme-possum.jurassic.ninja
Site address (URL): https://supreme-possum.jurassic.ninja
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.18
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: wp_
Total Database Size: 2.82MB
Database Data Size: 1.41MB
Database Index Size: 1.41MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 0.39MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 6
post: 1
product: 19
product_variation: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.7.1
Code Snippets: by Code Snippets Pro – 2.14.1
Companion Plugin: by Osk – 1.18
WooCommerce Payments: by Automattic – 2.6.0-test-2
WooCommerce: by Automattic – 5.4.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 4
Oldest: 2021-06-15 06:54:24 +0000
Newest: 2021-06-15 08:16:31 +0000

### Status report information ###

Generated at: 2021-06-15 08:35:37 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by dmallory42**
Fixes #2180 

#### Changes proposed in this Pull Request

- Fixes a fatal error that occurs when clicking `Save Changes` on the main Multi-Currency page (with the currency list) by hiding the save changes button on this page.

#### Testing instructions

- Checkout this branch. Go to the main `Settings -> Multi Currency` page.
- Verify the `Save Changes` button is no longer there.
- Verify the `Save Changes` button is present on the "edit" page for a single currency.
- Verify the code changes make sense.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/multi-currency/class-settings.php [hunk 1]
```diff
@@ -382,11 +386,17 @@ public function save() {
 		// Save all settings through the settings API.
 		\WC_Admin_Settings::save_fields( $this->get_settings( $current_section ) );
 
-		// If the manual rate was blank, or zero, we set it to the automatic rate.
-		$manual_rate = get_option( $this->id . '_manual_rate_' . $current_section, false );
-		if ( ! $manual_rate || 0 >= $manual_rate || '' === $manual_rate ) {
-			$available_currencies = $this->multi_currency->get_available_currencies();
-			update_option( $this->id . '_manual_rate_' . $current_section, $available_currencies[ strtoupper( $current_section ) ]->get_rate() );
+		// If we are saving the settings for an individual currency, we have some additional logic.
+		if ( '' !== $current_section ) {
```
Comment (luizreis) [inline includes/multi-currency/class-settings.php:390]: Soon we'll also introduce the [`store`](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/multi-currency/class-settings.php#L104) section. Do you think we should also include a check for it here in case we forget to do it when enabling it?

**Review by luizreis — APPROVED** [review]
LGTM! I left a comment regarding a future section, but I'm pre-approving this. :shipit:

File: includes/multi-currency/class-settings.php (hunk 1 above)
Comment (dmallory42) [reply includes/multi-currency/class-settings.php]: Good idea! Updated in ccbeab3ff528540b1f30b5eb22a11749a2883f65.

Comment (luizreis) [reply includes/multi-currency/class-settings.php]: Awesome! :shipit:
