### PR TITLE
Fix charm pricing and rounding for non-decimal currencies

### LINKED ISSUE #7724: Multi-Currency issues with zero decimal currencies
### Describe the bug
When Multi-Currency was built we worked off of the belief that the [zero decimal currency list provided by Stripe](https://stripe.com/docs/currencies?presentment-currency=US#zero-decimal) were all of the currencies that operated without decimals, however, this is not the case. There are several other currencies that have zero decimal formatting that are not on this list. The primary reason for this list is for currencies that do not have to have the amount multiplied or divided by 100 when dealing with Stripe for transactional purposes:

> All API requests expect amounts to be provided in a currency’s smallest unit. For example, to charge 10 USD, provide an amount value of 1000 (that is, 1000 cents).
> For zero-decimal currencies, still provide amounts as an integer but without multiplying by 100. For example, to charge ¥500, provide an amount value of 500.

The problem is that we use this list in order to define formatting, charm, and rounding for currencies enabled via Multi-Currency. This means that currencies like TWD (New Taiwan dollar) may try to be formatted with two decimals in certain instances when they should be formatted (or rounded) with zero decimals.

The number of decimals for a currency is defined in the [`locale-info.php` file within WooCommerce core](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/locale-info.php), and this is what is used for most of the formatting in Woo Payments via the [`WC_Payments_Localization_Service` class](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-localization-service.php). This data should be taken into account for use with Multi-Currency, as it will provide the correct number of decimals to be used for a currency.

I also believe that Multi-Currency should move away from the "zero decimal" term and use something like "decimal places" instead, which will allow for a clearer definition of what the decimals are for.

### To Reproduce

> [!Note]
> The steps below reference TWD, but this is the case for any currency with zero decimals and is not on the Stripe defined list.

1. Navigate to WooCommerce > Settings > Multi-Currency.
2. Enable TWD / New Taiwan dollar.
3. Click _Manage_ to manage TWD.
4. Confirm that the Charm and Rounding options are what is shown for 2 decimal currencies like USD, EUR, GBP, etc.
5. Navigate to your store's front end and add an item to your cart.
6. Check out with that item and see the incorrect format for the total on the Order Received page.

### Screenshots
Multi-Currency's manage currency page:
Multi-Currency's manage currency page

Order received page:
Order received page

### PR DESCRIPTION
**Pull request by reykjalin**
Fixes #7724

# Changes proposed in this Pull Request

* Use `WC_Payments_Localization_Service` to determine the number of decimals for a given currency.
    * This means decimals are now based on information in WC Core.

# Testing instructions

> [!WARNING]
> Testing this PR requires a lot of repetitive work. You may want to set aside ~6 hours for the testing + breaks, and possibly split the testing into several sessions.

## Setup

1. Go to **WooCommerce &rarr; Settings &rarr; Multi-currency** and make sure you add one of each of the following types of currencies:
    1. A currency with decimals that's not the store currency (e.g. `USD`, `EUR`, `CAD`).
    2. A currency that has no decimals in either WooCommerce or Stripe (e.g. `JPY`).
    3. A currency that has decimals in Stripe, but no decimals in WooCommerce (e.g. `ISK`).

### Buy products in all those currencies

Start with your store currency and:

1. Add a simple product to your cart and go to the **Checkout** page.
2. Complete a payment with any success test card, e.g. `4242 4242 4242 4242`.
3. Note down the total amount charged.

image

4. Go to **wp-admin &rarr; WooPayments &rarr; Transactions** and make sure the amount charged is correct.

image

6. Go to **wp-admin &rarr; Orders**, find the order you just created, and make sure the amounts displayed in the order details are correct.

Repeat this for the 3 other currencies you configured in the **Setup** section.

### Subscriptions compatibility

Repeat the test from above with a simple subscription product. In other words:

1. Add a subscription product to your cart and go to the **Checkout** page.
2. Complete a payment with any success test card, e.g. `4242 4242 4242 4242`.
3. Note down the total amount charged.
4. Go to **wp-admin &rarr; WooPayments &rarr; Transactions** and make sure the amount charged is correct.
5. Go to **wp-admin &rarr; Orders**, find the order you just created, and make sure the amounts displayed in the order details are correct.
6. Go to **wp-admin &rarr; Subscriptions**, find the subscription you just created.
7. Select **Process Renewal** from the **Order actions** drop-down and click **Update**.

image

8. Go to **wp-admin &rarr; WooPayments &rarr; Transactions** and make sure the amount charged for the renewal order is correct.
9. Go to **wp-admin &rarr; Orders**, find the order for the subscription renewal, and make sure the amounts displayed in the order details are correct.

Then repeat for the 3 other currencies you configured in the **Setup** section.

### Configuration

For each of the currencies you added in the **Setup** section:

1. Go to **WooCommerce &rarr; Settings &rarr; Multi-currency** and select **Configure** for the currency you're testing.
2. Make sure the rounding and charm pricing options are correct:
    1. Rounding options:
        1. Currency with decimals in WC (e.g. `EUR`): 0.25, 0.50, 1.00, 5.00, 10.00.
        2. Currency with 0-decimals in WC (e.g. `JPY`): 1, 10, 25, 50, 100, 500, 1000.
    3. Charm pricing options:
        1. Currency with decimals in WC (e.g. `EUR`): -0.01, -0.05.
        2. Currency with 0-decimals in WC (e.g. `JPY`): -1, -5, -10, -20, -25, -50, -100.
3. Make sure different combinations of rounding and charm pricing options are shown correctly in the preview.

### Process payments

> [!NOTE]
> If you want to be extra thorough here you can test multiple combinations of rounding and charm pricing options for all the currencies, but I figured it'd be easier to test just 1 configuration per currency.

For each of the 4 currencies (store currency and the 3 extra currencies configured in **Setup**):

1. Configure your currencies such that each has different rounding and charm pricing options set:
    1. Example configuration:
        * Store currency (`USD`): no rounding, no charm pricing (the default setting).
        * Currency w/ decimals (`EUR`): Some rounding, no charm pricing.
        * Currency w/ no decimals in WC + Stripe (`JPY`): No rounding, some charm pricing.
        * Currency w/ no decimals in WC, decimals in Stripe (`ISK`): Some rounding, some charm pricing.
2. Repeat all the testing from above for simple and subscription products, i.e. simple product with all currencies and subscription product with all currencies.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8723` or branch name `fix/mccy-charm-and-rounding-for-non-decimal-currencies` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/mccy-charm-and-rounding-for-non-decimal-currencies) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 699c5e9468cef982b2ea2a8accb17848fa2c34a8
- Build time: 2024-05-07 01:19:28 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/multi-currency/Currency.php [hunk 1]
```diff
@@ -66,24 +66,32 @@ class Currency implements \JsonSerializable {
...
 
 		if ( get_woocommerce_currency() === $code ) {
 			$this->is_default = true;
 		}
 
-		if ( in_array( strtolower( $code ), WC_Payments_Utils::zero_decimal_currencies(), true ) ) {
-			$this->is_zero_decimal = true;
-		}
+		// Set zero-decimal style based on WC locale information.
+		$this->is_zero_decimal = 0 === $this->localization_service->get_currency_format( $code )['num_decimals'];
```
Comment (reykjalin) [inline includes/multi-currency/Currency.php:94]: This is the real meat of the change here. Instead of relying on our tailor-made list of "0-decimal currencies" based on Stripe's list we instead rely on the currency information defined by WC Core.

The rest of the changes are all reacting to the additional `$localization_service` parameter that's passed into the class constructor.

File: includes/multi-currency/Currency.php [hunk 2]
```diff
@@ -66,24 +66,32 @@ class Currency implements \JsonSerializable {
...
+	 * @param float                            $rate The conversion rate.
+	 * @param int|null                         $last_updated The time this currency was last updated.
 	 */
-	public function __construct( string $code = '', float $rate = 1.0, $last_updated = null ) {
-		$this->code = $code;
-		$this->rate = $rate;
+	public function __construct( WC_Payments_Localization_Service $localization_service, $code = '', float $rate = 1.0, $last_updated = null ) {
+		$this->localization_service = $localization_service;
+		$this->code                 = $code;
+		$this->rate                 = $rate;
```
Comment (reykjalin) [inline includes/multi-currency/Currency.php:87]: Even though it's possible to just instantiate the localization service via `new WC_Payments_Localization_Service();` I chose to pass the `$localization_service` to the constructor for 2 reasons:

1. It matches the general pattern we use when classes depend on services; and
2. There are a couple of tests that make mocking the localization service necessary, and it's much easier when the localization service is passed as a parameter to the constructor.

**Review by reykjalin — COMMENTED** [review]
I've added comments noting where the actual impactful changes are in this PR because the changes introduced _a lot_ of noise.

It'd be nice to make sure whoever reviews this checks over the tests to make sure I'm not doing anything wrong there, but those changes are just to:

1. Instantiating a localization service class; and
2. Providing that service to any `Currency` class instantiations.

No functionality in the tests was changed.

There were a couple tests that needed a more involved set of changes; `test-class-multi-currency.php` and `test-class-frontend-currencies.php`, but the changes still follow that same theme of making sure a localization service is available to `Currency` instances.

File: includes/multi-currency/Currency.php [hunk 3]
```diff
@@ -66,24 +66,32 @@ class Currency implements \JsonSerializable {
...
+	 */
+	private $localization_service;
+
 	/**
 	 * Constructor.
 	 *
-	 * @param string   $code Three letter currency code.
-	 * @param float    $rate The conversion rate.
-	 * @param int|null $last_updated The time this currency was last updated.
+	 * @param WC_Payments_Localization_Service $localization_service Three letter currency code.
```
Comment (cesarcosta99) [inline includes/multi-currency/Currency.php]: Fixing the argument description.

```suggestion
	 * @param WC_Payments_Localization_Service $localization_service Localization service instance.
```

**Review by cesarcosta99 — CHANGES_REQUESTED** [review]
Good work here! Changes look good and test well 💯 I only left a 🤏 request about an argument description.

- Buy products in all those currencies ✅ 
    - USD, EUR, JPY and ISK
- Subscriptions compatibility ✅ 
    - USD, EUR, JPY and ISK
- Make sure the rounding and charm pricing options are correct ✅ 
    - EUR, JPY and ISK
- Make sure different combinations of rounding and charm pricing options are shown correctly in the preview ✅ 
    - EUR, JPY and ISK 
- Process payments ✅
    - Buy simple product ✅ 
        - USD as default currency
        - EUR with some rounding and no charm pricing
        - JPY with no rounding and some charm pricing
        - ISK with some rounding and some charm pricing
    - Buy subscription product and process renewal ✅ 
        - USD as default currency
        - EUR with some rounding and no charm pricing
        - JPY with no rounding and some charm pricing
        - ISK with some rounding and some charm pricing

File: includes/multi-currency/Currency.php (hunk 3 above)
Comment (reykjalin) [reply includes/multi-currency/Currency.php]: Thank you for catching this, I've applied your suggested changes 💯

**Comment by reykjalin** [comment]
@cesarcosta99 I've triggered the "merge when ready" flow, so this should be merged upon your approval 🙂

**Review by cesarcosta99 — APPROVED** [review]
LGTM

**Comment by pierorocca** [comment]
Awesome work here @reykjalin.
