### PR TITLE
Change WooPay session route namespace

### LINKED ISSUE #9313: Direct Checkout not working with third-party cookies disabled
### Describe the bug
Direct checkout is not working for users without third-party cookies disabled.

### To Reproduce
**Setup**
- Merchant site running WooCommerce >= 9.2.1
- Customer has blocked third party cookies in their browser
- Customer is not logged in to merchant site
- Customer is logged in to WooPay

**Bug**
- As a customer add a product to cart
- Visit the cart page
- Open the developer tools > Network panel
- Click the Proceed to Checkout button
- Notice that you'll get forwarded to `woopaydomain/woopay/?checkout_redirect=1...`
- Notice that you'll get quickly forwarded back to the merchant site checkout page

This happens because customer is null [here](https://github.com/Automattic/woocommerce-payments/blob/ecb997675795ffaa11d879922591549c6edc2362/includes/woopay/class-woopay-session.php#L515)

https://github.com/user-attachments/assets/c3e51c85-e42a-4d79-88c8-b41cbbca75a6

### PR DESCRIPTION
**Pull request by alefesouza**
Fixes #9313

#### Changes proposed in this Pull Request

On https://github.com/woocommerce/woocommerce/pull/47704 introduced on WooCommerce 9.2 we are limiting loading some Store API routes only when the current route is from the `wc/store` route namespace, this made the WooPay session route stop working because it's loaded from the `wc/v3` namespace.

This PR fixes that by changing the WooPay session route namespace to `wc/store`.

This PR needs to be tested alongside https://github.com/Automattic/woopay/pull/2892.

#### Testing instructions

* Replace `WCPAY_VERSION_NUMBER` [here](https://github.com/Automattic/woocommerce-payments/blob/7713ed2708a6777c683c0d41fce0ff8b8c3c1504/includes/woopay/class-woopay-session.php#L469) and [here](https://github.com/Automattic/woocommerce-payments/blob/7713ed2708a6777c683c0d41fce0ff8b8c3c1504/includes/woopay/class-woopay-session.php#L680) with `8.2.0`.
* Follow https://github.com/Automattic/woocommerce-payments/issues/9313 reproduce instructions.
* Direct checkout should work as expected.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9317` or branch name `fix/woopay-direct-checkout-route-namespace` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/woopay-direct-checkout-route-namespace) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 7a73a700272542ac5beb9fa14d7e20482b58ac51
- Build time: 2024-08-28 19:56:06 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by leonardola — COMMENTED** [review]
Changes look good and work well. 

What if someone decides to change the namespace again in the future?
So what do you think about also hooking into [wc_rest_should_load_namespace](https://github.com/woocommerce/woocommerce/blob/d766b02a144f4116bcacba3f66363a9e2b50dd3f/plugins/woocommerce/includes/wc-rest-functions.php#L435) to make sure the namespace is loaded before calling any `/store` endpoints [like here](https://github.com/Automattic/woocommerce-payments/blob/ecb997675795ffaa11d879922591549c6edc2362/includes/woopay/class-woopay-session.php#L344)?
This filter will be included in a future Woo version but might make sense to already add it in this PR

**Comment by alefesouza** [comment]
> So what do you think about also hooking into [wc_rest_should_load_namespace](https://github.com/woocommerce/woocommerce/blob/d766b02a144f4116bcacba3f66363a9e2b50dd3f/plugins/woocommerce/includes/wc-rest-functions.php#L435) to make sure the namespace is loaded before calling any /store endpoints [like here](https://github.com/Automattic/woocommerce-payments/blob/ecb997675795ffaa11d879922591549c6edc2362/includes/woopay/class-woopay-session.php#L344)?

@leonardola It looks like [this PR](https://github.com/woocommerce/woocommerce/pull/50902) will be implemented on a WooCommerce patch release, maybe it worth waiting a little bit because if it's launched as a patch release we may not need to change the route namespace on the WCPay side, just apply the new filter, what do you think?

Also we need to wait the mentioned PR is merged to make sure it didn't change the filter.

**Comment by alefesouza** [comment]
> So what do you think about also hooking into [wc_rest_should_load_namespace](https://github.com/woocommerce/woocommerce/blob/d766b02a144f4116bcacba3f66363a9e2b50dd3f/plugins/woocommerce/includes/wc-rest-functions.php#L435) to make sure the namespace is loaded before calling any /store endpoints [like here](https://github.com/Automattic/woocommerce-payments/blob/ecb997675795ffaa11d879922591549c6edc2362/includes/woopay/class-woopay-session.php#L344)?

What if the namespace is not loaded? We still would not return the expected data on the `get_cart_data` method and other `/store` endpoints so we would end having the same error with or without this check.

**Comment by alefesouza** [comment]
On https://github.com/Automattic/woocommerce-payments/pull/9317/commits/9f1b4396336124c15372ca566a79d986a72ce8c9 and https://github.com/Automattic/woocommerce-payments/pull/9317/commits/fa371de1a81d2c83d98b5c29f73de35dbc7c2408 we are now ensuring the route namespaces will load when the request comes from a WooPay route.

**Comment by leonardola** [comment]
@alefesouza take a look at this https://github.com/woocommerce/woocommerce/pull/50902#discussion_r1730678128. Basically any endpoint that is not a Woo Core endpoint will load all namespaces. So we should not reuse the Woo endpoints but create our custom endpoint instead. 

I'm not sure what lead us to reuse endpoints but it would be good to check and if possible migrate every endpoint to a custom one to prevent future bugs as recommended by [WP Core](https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api.php?rgh-link-date=2024-08-26T05%3A18%3A04Z#L26).

**Comment by alefesouza** [comment]
@leonardola fixed on https://github.com/Automattic/woocommerce-payments/pull/9317/commits/10283d273a692b8c9788eb7af8a08c56b26d086e, it's working as expected outside the Store API namespaces.

File: includes/admin/class-wc-rest-woopay-session-controller.php [hunk 1]
```diff
@@ -21,14 +21,14 @@ class WC_REST_WooPay_Session_Controller extends WP_REST_Controller {
 	 *
 	 * @var string
 	 */
-	protected $namespace = 'wc/v3';
+	protected $namespace = 'wc/woopay';
```
Comment (leonardola) [inline includes/admin/class-wc-rest-woopay-session-controller.php]: Isn't it better change `wc` to `wc-pay` or something else so the namespace has nothing to do with Woo Core?

**Review by leonardola — APPROVED** [review]
Left a comment about the namespace still. 

Also let's make sure WooPay gets deployed to production before merging the WC Payments changes.

File: includes/admin/class-wc-rest-woopay-session-controller.php (hunk 1 above)
Comment (alefesouza) [reply includes/admin/class-wc-rest-woopay-session-controller.php]: Updated to `payments` on https://github.com/Automattic/woocommerce-payments/pull/9317/commits/7a73a700272542ac5beb9fa14d7e20482b58ac51 to keep consistency with other WCPay routes.

**Comment by alefesouza** [comment]
> Also let's make sure WooPay gets deployed to production before merging the WC Payments changes.

This should not be a problem as it will be released on the next WCPay release and WooPay will only call this endpoints when WCPay version is equal or greater than 8.2.

**Comment by ricardo** [comment]
@alefesouza @leonardola We probably need to change this as well: https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments-utils.php#L54
