### PR TITLE
Fix: Javascript not loading on order screens with HPOS enabled

### LINKED ISSUE #6967: Admin Order related javascript not enqueued on HPOS stores.
### Describe the bug

When HPOS is enabled, [order screen related javascript](https://github.com/Automattic/woocommerce-payments/blob/56e0e1ca6cf9a1f18baf49b4b27e1d24a4e0ffd3/client/order/index.js) is not loaded.

When using the default CPT order type, the `screen id` for order pages is `shop_order`. With HPOS enabled the `screen id` is `woocommerce_page_wc-orders`.

https://github.com/Automattic/woocommerce-payments/blob/98c291141b41f87213f480a4ce271260fef29fb8/includes/admin/class-wc-payments-admin.php#L695

This currently affects refund logic for WooPayments and dispute order notices #6373

### To Reproduce

1. Go to a WooCommerce > Orders 
2. Click on a WooPayments order
3. Click `Refund`
4. See `Refund $0.00 via WooPayments`

Screenshot 2023-08-10 at 12 23 41 PM

1. Enable HPOS.
2. Go back to previous order.
3. Click `Refund`
4. See unexpected `Refund Manually` button

image

### PR DESCRIPTION
**Pull request by brucealdridge**
Fixes #6967 

#### Changes proposed in this Pull Request

Order screen javascript is now enqueued on admin order pages when HPOS is enabled.

With HPOS, WooCommerce introduces a different way of rendering admin order screens. With CPT orders the screen id is `shop_order`. With HPOS enabled the screen id is `woocommerce_page_wc-orders`. This prevented the expected javascript from being loaded on page.

#### Testing instructions

1. Enable HPOS.
2. Click on a WooPayments order
3. Click `Refund`
4. The `Refund Manually` button should not be visible (this is removed with the javascript in `client/order/index.js`)

Screenshot 2023-08-10 at 12 23 41 PM

Additionally, multicurrency settings should now be visible on the order page with HPOS enabled.

```
<script>
   woocommerce_admin_meta_boxes.currency_format_num_decimals = 2;
   woocommerce_admin_meta_boxes.currency_format_decimal_sep = ',';
   woocommerce_admin_meta_boxes.currency_format_thousand_sep = '.';
   woocommerce_admin_meta_boxes.currency_format = '%v %s';
   woocommerce_admin_meta_boxes.rounding_precision = 2;
</script>
```

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6968` or branch name `fix/6967-order-screen-js` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6967-order-screen-js) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 2293e87da7f5a3260b3940498326ef78dbd03625
- Build time: 2023-08-11 01:40:13 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/admin/class-wc-payments-admin.php [hunk 1]
```diff
@@ -692,7 +692,7 @@ public function enqueue_payments_scripts() {
 		}
 
 		$screen = get_current_screen();
-		if ( 'shop_order' === $screen->id ) {
+		if ( in_array( $screen->id, [ 'shop_order', 'woocommerce_page_wc-orders' ], true ) ) {
 			$order = wc_get_order();
 
 			if ( WC_Payment_Gateway_WCPay::GATEWAY_ID === $order->get_payment_method() ) {
```
Comment (Jinksi) [inline includes/admin/class-wc-payments-admin.php]: This line is now throwing a fatal error on the Order list screen. This is because `$screen->id` equals `woocommerce_page_wc-orders` for both the list and individual order screens when HPOS is enabled and on the order list screen, `wc_get_order()` returns `false`.

```
 Fatal error: Uncaught Error: Call to a member function get_payment_method() on bool
```

Perhaps we can check for an order here:
```suggestion
			if ( $order && WC_Payment_Gateway_WCPay::GATEWAY_ID === $order->get_payment_method() ) {
```

**Review by Jinksi — CHANGES_REQUESTED** [review]
In testing, I discovered a fatal error that occurs as commented below.

On the single order screen, however, the dispute notice appears correctly 🏆 

I have not yet tested the impact of fixing multi-currency on the single order screen with HPOS enabled.

File: includes/admin/class-wc-payments-admin.php (hunk 1 above)
Comment (brucealdridge) [reply includes/admin/class-wc-payments-admin.php]: 💯 Good testing. I didn't spot that the orders listing had the same screen id and didn't test.
I was defensive for Multi-Currency but missed the check here. 🙇‍♂️

**Review by Jinksi — APPROVED** [review]
This tests well @brucealdridge. Note I have not tested related multi-currency flows and ask @Automattic/sigma to review these flows with a greater understanding.

**Before** with HPOS enabled, the dispute notice does not appear and the manual refund button is rendered.
image

image


**After** with HPOS enabled OR disabled, the dispute notice is rendered and the manual refund button is not rendered. ✅ 

image

image

2293e87 has resolved the error with the order list screen.

**Review by tpaksu — APPROVED** [review]
The changes make sense, and tests well. LGTM! 🚢 it! Thanks for working on this issue!
