### PR TITLE
Fixed the currency switcher on widgets admin page

### LINKED ISSUE #6010: [GlobalStep] "This block has encountered an error and cannot be previewed." message displayed for "Currency Switcher" block on "Appearance > Widget" page.
### Bug Description:
"This block has encountered an error and cannot be previewed." message displayed for "Currency Switcher" block on "Appearance > Widget" page.

### Environment:
Woocommerce Version: WooCommerce 7.5.1
WooCommerce Payments - 5.8.0-test-1
WordPress version: v6.2

PC:
Windows 10,
Chrome(Version 112.0.5615.50)
Firefox (Version 112.0)

### Steps To Reproduce:
1. Create any test site.
2. Install and activate all the required plugins.
4. Complete the setup.
5. In WP Admin, click on Appearance > Widgets page.
6. Add a new block to the sidebar by clicking the plus icon at the bottom of the existing sidebar widgets.
7. Search Currency Switcher Block Widget and select it.
8. Observe that, "This block has encountered an error and cannot be previewed." message displayed for "Currency Switcher" block

### Instruction Link:
https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#multi-currency-block-widget-for-currency-switcher

### Actual Result:
"This block has encountered an error and cannot be previewed." message displayed for "Currency Switcher" block on "Appearance > Widget" page.

### Expected Result:
"Currency Switcher" block should be displayed properly without any error message on "Appearance > Widget" page.

### Screenshot:

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wp_
Total Database Size: 7.39MB
Database Data Size: 5.18MB
Database Index Size: 2.21MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.17MB + Index: 0.20MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 3.20MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.41MB + Index: 0.42MB + Engine InnoDB
wp_posts: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 10
post: 2
product: 23
product_variation: 7
revision: 3
shop_coupon: 1
shop_order: 58
shop_order_refund: 8
shop_subscription: 18

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.12.1
Code Snippets: by Code Snippets Pro – 3.3.0
Companion Plugin: by Osk – 1.29
WooCommerce Payments: by Automattic – 5.8.0-test-1
WooCommerce: by Automattic – 7.5.1

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 5.1
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce Subscriptions: by WooCommerce – 5.0.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://insufficient-magpie.jurassic.ninja
Subscriptions-core Library Version: 5.5.0
Subscription Statuses: wc-pending: 1
wc-cancelled: 1
wc-active: 16

WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 16
wc-cancelled: 1
wc-pending: 1

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-13 09:36:17 +00:00
Options: ✔
Notes: 45
Onboarding: completed

### WooCommerce Payments ###

Version: 5.8.0-test-1
Connected to WPCOM: Yes
Blog ID: 217746070
Account ID: acct_1Mve04C64yGoEL4Z

### Action Scheduler ###

Canceled: 16
Oldest: 2023-04-11 10:19:59 +0000
Newest: 2023-04-12 09:19:47 +0000

Complete: 476
Oldest: 2023-04-11 09:36:29 +0000
Newest: 2023-04-12 06:35:31 +0000

Failed: 9
Oldest: 2023-04-11 10:10:19 +0000
Newest: 2023-04-12 09:38:15 +0000

Pending: 18
Oldest: 2023-04-13 09:38:15 +0000
Newest: 2023-07-11 14:19:36 +0000

### Status report information ###

Generated at: 2023-04-12 10:15:59 +00:00
`

</details>

### PR DESCRIPTION
**Pull request by leonardola**
Fixes #6010

#### Changes proposed in this Pull Request
This PR fixes the blocks currency switcher in the widgets admin

#### Testing instructions
- In WP Admin, click on Appearance > Widgets page.
- Add a new block to the sidebar by clicking the plus icon at the bottom of the existing sidebar widgets.
- Search Currency Switcher Block Widget and select it.
- Make sure the block loaded instead of showing "This block has encountered an error and cannot be previewed." message
-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6035` or branch name `fix/6010-currency-switcher-widget` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6010-currency-switcher-widget) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 92da85c41b03471e824d633ce6e252d0b13a5a6c
- Build time: 2023-04-25 20:43:57 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by a-danae — APPROVED** [review]
Tests well and looks good to me, thanks @leonardola !

My only concern was not checking whether `get_current_screen` returned null before accessing its `base` property. But it looks  safe because this method is hooked to `admin_enqueue_scripts`, which happens after the `current_screen` action.

File: includes/admin/class-wc-payments-admin.php [hunk 1]
```diff
@@ -447,10 +447,6 @@ public function add_payments_menu() {
 	public function register_payments_scripts() {
 		WC_Payments::register_script_with_dependencies( 'WCPAY_DASH_APP', 'dist/index' );
 
-		// Has on-boarding been disabled? Set the flag for use in the front-end so messages and notices can be altered
-		// as appropriate.
-		$on_boarding_disabled = WC_Payments_Account::is_on_boarding_disabled();
```
Comment (LCmry) [inline includes/admin/class-wc-payments-admin.php:452]: @leonardola just out of curiosity, why was this removed?

Comment (leonardola) [reply includes/admin/class-wc-payments-admin.php:452]: Because `$on_boarding_disabled` was not being used anywhere in this function. The function `WC_Payments_Account::is_on_boarding_disabled()` is being called directly in line 499.
