### PR TITLE
Do not allow guest users to buy subscriptions with WooPay Direct Checkout

### LINKED ISSUE #9791: WooPay Subscription error when using direct checkout
### Describe the bug

(copied from the WooPay repo, text by @malithsen)

Shopper should always be logged into the merchant site when purchasing a subscription via WooPay, however this requirement is bypassed when using Direct Checkout which can sometimes results in an order failure.

### To Reproduce

1. Create a new account in the merchant site.
2. Log out of the account.
3. In a separate tab create a WooPay account using the same email address used in step 1.
4. Go back to the merchant site, add a subscription product to the cart.
5. Go to the cart page.
6. Click on the Proceed to Checkout button.
7. You will be redirected to the WooPay checkout page.
8. Place order. 
9. Notice that the order fails and the payment gets auto-refunded.

This failure is because when processing the subscription, merchant site tries to create a new user for the email provided by WooPay but fails as there's already a user with that email.

### Actual behavior

Direct Checkout is enabled when shopper is logged out and is purchasing a subscription.

### Expected behavior

Direct Checkout should be disabled when the shopper is not logged in to merchant site and is purchasing a subscription.

### PR DESCRIPTION
**Pull request by alefesouza**
Fixes #9791

#### Changes proposed in this Pull Request

This PR fixes guest users being able to buy subscriptions using WooPay via Direct Checkout.

#### Testing instructions

* Login on WooPay.
* As a guest user on merchant site, add a subscription to the cart.
* Access the cart page on blocks checkout.
* Click the `Proceed to Checkout` button.
* You should not be redirected to WooPay.
* Access the cart page on classic checkout.
* Click the `Proceed to checkout` button.
* You should not be redirected to WooPay.
* Remove the subscriptions from the cart and add other type of product.
* Access the cart page on blocks checkout.
* Click the `Proceed to Checkout` button.
* You should be redirected to WooPay.
* Return to merchant site.
* Access the cart page on classic checkout.
* Click the `Proceed to checkout` button.
* You should be redirected to WooPay.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9792` or branch name `fix/woopay-direct-checkout-guest-subscriptions` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/woopay-direct-checkout-guest-subscriptions) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: ea1ce684e9b6aef5d90a2fd80304c7b3b6349f12
- Build time: 2025-01-16 13:21:59 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php [hunk 1]
```diff
@@ -196,6 +196,9 @@ public function ajax_get_shipping_options() {
 	public function ajax_get_cart_details() {
 		check_ajax_referer( 'wcpay-get-cart-details', 'security' );
 
+		// Process added gift cards.
+		add_filter( 'woocommerce_gc_disable_ui', '__return_false' );
```
Comment (alefesouza) [inline includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php]: While working on https://github.com/Automattic/woocommerce-payments/pull/9846 I noticed the express checkout buttons (Apple/Google Pay) were not getting hidden on classic checkout when the cart total get to 0 by adding gift cards, as the PR was closed I'm taking the opportunity of this PR to add this line and fix that.

Comment (hsingyuc) [reply includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php]: Can you provide test instructions?

File: includes/class-wc-payments.php [hunk 2]
```diff
@@ -1622,6 +1622,10 @@ function ( $container ) {
 	 * @return void
 	 */
 	public static function maybe_init_woopay_direct_checkout() {
+		if ( ! self::$woopay_util->should_enable_woopay_on_cart_or_checkout() ) {
+			return;
+		}
+
```
Comment (hsingyuc) [inline includes/class-wc-payments.php]: The code makes sense to me but I still can not reproduce the issue. Can you check my recording and see if anything I missed? Thank you!

https://github.com/user-attachments/assets/fb6f2d52-1844-400c-bedb-2d4f85b4e6db

**Comment by hsingyuc** [comment]
@alefesouza I can reproduce the issue if not in incognito. I'll approve this PR after testing `woocommerce_gc_disable_ui` filter.


https://github.com/user-attachments/assets/5ca6ed8d-e8d8-4094-ae7d-112a88f8ae81

**Comment by hsingyuc** [comment]
@alefesouza could you double check with your PR, can you still use direct checkout on simple product(not subscription)?

https://github.com/user-attachments/assets/c40db3ec-50dc-42f4-8507-475f56fbf5ff

**Comment by alefesouza** [comment]
> can you still use direct checkout on simple product(not subscription)?

@hsingyuc fixed on https://github.com/Automattic/woocommerce-payments/pull/9792/commits/5e270fbee3d6fc1a5b6eb8b6c20c27127618f896, the `setup_theme` hook is called too earl so we do not have information about the current page, moved to the `wp_footer` inside the `WC_Payments_WooPay_Direct_Checkout` class.

File: includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php (hunk 1 above)
Comment (alefesouza) [reply includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php]: @hsingyuc Testing instructions:

* Install Gift Cards.
* Create new Gift Card codes.
* Expose your site with Jurassic Tube or ngrok to enable Google/Apple Pay buttons.
* Add products to the cart.
* Access the classic checkout page.
* Add gift card codes until the total cart value reach 0.
* The Google/Apple Pay buttons should be hidden.

**Review by hsingyuc — COMMENTED** [review]
Should we also consider that if there's one simple product and one subscription in the cart, remove the subscription product and we should be redirectd to WooPay?


https://github.com/user-attachments/assets/a70a7ae5-644e-4627-b345-8357f5753993

**Comment by alefesouza** [comment]
> Should we also consider that if there's one simple product and one subscription in the cart, remove the subscription product and we should be redirectd to WooPay?

Currently the WooPay button also does not render when removing the subscription from the cart, this is better to be handled on another PR.

**Comment by alefesouza** [comment]
Removed the gift cards fix as since #10058 we are allowing Google/Apple Pay with $0 orders on shortcode checkout.

**Review by hsingyuc — COMMENTED** [review]
@alefesouza, could you test this branch again? Subscription product tests as expected but when I test simple product, I was still redirected to the Blocks checkout.

**Comment by alefesouza** [comment]
@hsingyuc for me it's working as expected, were you logged in while testing direct checkout?

**Review by leonardola — COMMENTED** [review]
It works as expected according to the testing instructions. 

But I still get forwarded to WooPay when I'm logged in to both WooPay and the merchant site. Is this expected?

Also removing the subscription from the cart while visiting the cart page does not get me forwarded to WooPay

If I add a regular product to the cart. Visit the cart page and add a subscription on another tab then click proceed to checkout, I get forwarded to WooPay. Is this ok?

When I'm visiting the subscription product page I can see the WooPay button and it does get me to WooPay. Is that expected?

**Comment by hsingyuc** [comment]
>@hsingyuc for me it's working as expected, were you logged in while testing direct checkout?

Yes. I was logged in to WooPay. I've tested again and the issue persist.

**Comment by alefesouza** [comment]
@leonardola 

> But I still get forwarded to WooPay when I'm logged in to both WooPay and the merchant site. Is this expected?

Yes, because logged in shoppers can buy subscriptions.

> Also removing the subscription from the cart while visiting the cart page does not get me forwarded to WooPay.

This also happens on `develop`, we can open work on that on another PR.

> If I add a regular product to the cart. Visit the cart page and add a subscription on another tab then click proceed to checkout, I get forwarded to WooPay. Is this ok?

I don't think we handle this scenario on any features, probably it happens with other express payment methods too, maybe we can open an issue for that.

> When I'm visiting the subscription product page I can see the WooPay button and it does get me to WooPay. Is that expected?

While logged in on merchant store this is expected.

**Comment by alefesouza** [comment]
> Yes. I was logged in to WooPay. I've tested again and the issue persist.

@hsingyuc did you check if it works on `develop`? Maybe [there's something](https://github.com/Automattic/woocommerce-payments/blob/d1624f805fe40aa4e384920427953109edc18ad4/includes/class-wc-payments-features.php#L255) preventing Direct Checkout to work.

File: includes/class-wc-payments-woopay-direct-checkout.php [hunk 3]
```diff
@@ -71,6 +73,12 @@ public function scripts() {
 			return;
 		}
 
+		$woopay_util = new WooPay_Utilities();
```
Comment (leonardola) [inline includes/class-wc-payments-woopay-direct-checkout.php]: We usually pass other classes objects in the constructor. This allows us to easily mock dependencies in tests. Is there a reason to not do that here?

Comment (alefesouza) [reply includes/class-wc-payments-woopay-direct-checkout.php]: Fixed on https://github.com/Automattic/woocommerce-payments/pull/9792/commits/08b14133dd96229a8763174d2256505d521dbc93.

**Comment by hsingyuc** [comment]
@alefesouza, direct checkout is enabled for me. I got empty cart error and maybe that's related. I'll leave this to Leo since he's reviewing it.

@leonardola Thank you for your help here!

**Review by leonardola — APPROVED** [review]
Works as expected
