### PR TITLE
Show total balance (pending + available) instead of pending balance

### LINKED ISSUE #8070: Show `total` balance instead of `pending` to reduce confusion when pending is negative
### Describe the bug
We currently show account balances as two numbers:

- `Available funds` - the amount of $ that is available to payout in a deposit, i.e. has cleared pending period
- `Pending funds` - the amount of $ from recent transactions that is still pending, and not available to pay out (yet)

At times these numbers can be confusing, especially when `Pending` is negative (usually temporarily). Here are some situations where this might apply:

- A deposit is in transit
- An instant deposit has been triggered recently
- Other situations due to refunds or dispute fees

When the pending balance is negative, this is concerning and can lead to support requests and confusion about the health of the account balance. 

To mitigate this, we could present account balance in a different way, that doesn't emphasise temporary negative pending balance:

- `Available funds` - as before
- `Total balance` - pending + available, roughly equivalent to TPV cashflow, the $ value in the account right now

In future projects we may revisit some UI relating to this, e.g. the overview screen in general, or showing risk reserve amounts (which can affect available funds for some accounts). This issue is tightly scoped to addressing the immediate pain point.

The goal of this bug is to change the UI element currently showing `Pending funds` to show `Total balance`.

### To Reproduce
TBC – I don't know reproduce steps off hand, feel free to update this section, thank you 🙇

### Screenshots
woo2

and this is the new design – in line with the new Payments Overview widget that team Fusion is working on:
Overview - Finance Overview – Balance

### Expected behavior
Show merchant account balance in a way that does not cause concern.

##### Additional context
This issue has been hotly discussed internally, and comes up in support regularly. 

pdjTHR-2Sz-p2 paJDYF-bY2-p2#comment-22689

### PR DESCRIPTION
**Pull request by shendy-a8c**
Fixes https://github.com/Automattic/woocommerce-payments/issues/8070

#### Changes proposed in this Pull Request

- Show total balance and available balance instead of available balance and pending balance.

Before:
Screenshot 2024-02-07 at 07 50 22

After:
Screenshot 2024-02-07 at 07 51 36

Total balance will show tooltip if it is negative.

Screenshot 2024-02-07 at 07 34 50

#### Testing instructions

* Open Payments > Overview page.
* With base branch, you will see available and pending balance.
* With PR branch, you will see total and available balance.
* Hard-code available and pending balance like how I accidentally committed here: https://github.com/Automattic/woocommerce-payments/pull/8140/commits/3c3373613c69032c4664d164d26f871d708b3c01. Set the value so total balance is negative, expects a tooltip next to total balance.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8140` or branch name `update/8070-total-balance` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/8070-total-balance) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b8d822cecf9917da52057485ddcd4fdd32e92211
- Build time: 2024-02-29 07:50:54 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by shendy-a8c** [comment]
Just to note, I also found that available balance can be negative while pending balance is positive. See pdjTHR-2Sz-p2#comment-3983. Currently, for such case, we don't show total balance.

**Review by brucealdridge — COMMENTED** [review]
I've had a play around with this PR and find it a little jarring that the information presented moves around unexpectedly.

Having `Total balance` / `Available balance` sometimes and other times `Available balance` / `Pending balance` seems confusing to me.

From the issue it sounds like we should always be presenting `Total` / `Available`.

**Comment by shendy-a8c** [comment]
> From the issue it sounds like we should always be presenting Total / Available.
Ugh... that makes more sense actually. Thank you for pointing that out, @brucealdridge.

I jumped in and assumed we only want to show total balance and available balance only when pending balance is negative by reading the issue's title:
> Show total balance instead of pending to reduce confusion when pending is negative

but now I see that it makes more sense to be read as:
> Show total balance instead of pending, to reduce confusion when pending is negative

I read it as:
> Show total balance instead of pending to reduce confusion, when pending is negative

Putting this PR back to `in progress`.

File: client/components/account-balances/index.tsx [hunk 1]
```diff
@@ -84,16 +84,16 @@ const AccountBalances: React.FC = () => {
 						className="wcpay-account-balances__balances"
 					>
 						<BalanceBlock
-							id={ `wcpay-account-balances-${ tab.currencyCode }-available` }
-							title={ fundLabelStrings.available }
-							amount={ tab.availableFunds }
+							id={ `wcpay-account-balances-${ tab.currencyCode }-total` }
+							title={ fundLabelStrings.total }
+							amount={ 0 }
```
Comment (shendy-a8c) [inline client/components/account-balances/index.tsx:90]: In loading state, total balance will be 0.

File: client/components/account-balances/index.tsx [hunk 2]
```diff
@@ -84,16 +84,16 @@ const AccountBalances: React.FC = () => {
...
 							currencyCode={ tab.currencyCode }
 							isLoading
 						/>
 						<BalanceBlock
-							id={ `wcpay-account-balances-${ tab.currencyCode }-pending` }
-							title={ fundLabelStrings.pending }
-							amount={ tab.pendingFunds }
+							id={ `wcpay-account-balances-${ tab.currencyCode }-available` }
+							title={ fundLabelStrings.available }
+							amount={ 0 }
```
Comment (shendy-a8c) [inline client/components/account-balances/index.tsx:97]: In loading state, available balance is 0.

**Comment by shendy-a8c** [comment]
Searching [woo docs for 'pending'](https://woo.com/search/?q=pending&collections=documentation), found [this page](https://woo.com/document/woopayments/deposits/deposit-schedule/) that will need updating after this PR is released.

Found this too https://woo.com/document/woopayments/deposits/scheduled-deposit-vs-instant-deposit/ but probably safe to keep.

**Comment by shendy-a8c** [comment]
Ready for another round of review.

**Comment by haszari** [comment]
@shendy-a8c  – shifting back to in progress, as there is design feedback from @rogermattic (  paJDYF-coS-p2#comment-23128 ):

Screenshot 2024-02-15 at 9 40 22 AM

@rogermattic - these tooltips previously linked out to docs. What do you think about including the existing `Learn more` docs links alongside the informative new help text in your design?

**Comment by rogermattic** [comment]
Absolutely! Sorry I forgot about it! I’ll add the links to these tooltips in the morning:)

**Comment by rogermattic** [comment]
Frame 1000006618
@haszari, this is the updated visual :) 

The design is here: o5NOD3EJaKSoILbvvZiAwU the prototype is also available in this file :)

**Comment by shendy-a8c** [comment]
Updated in https://github.com/Automattic/woocommerce-payments/pull/8140/commits/01f17732591a4e74c898a86eb10a0cd9a4feb21d.

Changes only around tooltip. Here's the tooltip behavior:

- When any of the balances (total or available) is negative:

Screenshot 2024-02-17 at 03 57 54

Link is https://woo.com/document/woopayments/fees-and-debits/account-showing-negative-balance/

- When total balance is not negative:

Screenshot 2024-02-17 at 04 42 00

Link is https://woo.com/document/woopayments/deposits/deposit-schedule/

- When available balance is not negative:

Screenshot 2024-02-17 at 04 43 47

Link is https://woo.com/document/woopayments/deposits/deposit-schedule/

File: client/components/account-balances/index.tsx [hunk 3]
```diff
@@ -130,129 +131,135 @@ const AccountBalances: React.FC = () => {
...
-									}
-								/>
-							}
-						/>
-					</Flex>
-					{ tab.instantBalance && tab.instantBalance.amount > 0 && (
+			{ ( tab: BalanceTabProps ) => {
+				const totalBalance = tab.availableFunds + tab.pendingFunds;
+
+				const negativeBalanceTooltipContent = interpolateComponents( {
```
Comment (shendy-a8c) [inline client/components/account-balances/index.tsx]: I assign the content of tooltip when balance is negative to a variable here because it's going to be used for total balance and available balance when either of them is negative.

**Comment by shendy-a8c** [comment]
Ready for review.

File: client/components/account-balances/index.tsx (hunk 2 above)
Comment (haszari) [reply client/components/account-balances/index.tsx:97]: In loading state merchant will see a grey box placeholder, so this `0` is all good (if it shows in UI could lead to questions).

Comment (haszari) [reply client/components/account-balances/index.tsx:97]: Screenshot 2024-02-19 at 1 34 05 PM

File: client/components/account-balances/index.tsx (hunk 3 above)
Comment (haszari) [reply client/components/account-balances/index.tsx]: The linked documentation, and the tooltip really only apply to total balance. 

We should carefully consider how we present the special-case negative balance tooltip.  It might need input from design. 

Here's my take:

- The (new) tooltips for total balance and available balance are always true and relevant. When balance is negative, that doesn't override the "total balance" tooltip.
- The negative balance info is a special case, and is most relevant for "total balance" – if total balance is persistently negative, we will withdraw funds from merchant account.

So I think we have two options:

- Don't show a special tooltip for negative balance (i.e. revert this behaviour, because our new tooltips are clear enough).
- OR
- When the merchant has a negative total balance, add the info about negative balance to the "total balance" tooltip.

Keen for thoughts from @rogermattic and @csmcneill …

File: client/components/account-balances/index.tsx [hunk 4]
```diff
@@ -130,129 +131,135 @@ const AccountBalances: React.FC = () => {
...
+								title={ fundLabelStrings.total }
+								amount={ totalBalance }
+								currencyCode={ tab.currencyCode }
+								tooltip={
+									<BalanceTooltip
+										label={ `${ fundLabelStrings.total } tooltip` }
+										maxWidth={
+											totalBalance < 0
+												? undefined
+												: '335px'
```
Comment (haszari) [inline client/components/account-balances/index.tsx]: Why are you adding a `maxWidth` prop? This seems overcomplicated, can we set a standard max-width on all tooltips via CSS?

If there is a special need to customise the max width for this tooltip only, I'd suggest using a class + regular CSS to override (since most of our styles use CSS cascade, rather than styles-in-js).

File: client/components/account-balances/index.tsx [hunk 5]
```diff
@@ -130,129 +131,135 @@ const AccountBalances: React.FC = () => {
...
+									/>
+								}
+							/>
+							<BalanceBlock
+								id={ `wcpay-account-balances-${ tab.currencyCode }-available` }
+								title={ fundLabelStrings.available }
+								amount={ tab.availableFunds }
+								currencyCode={ tab.currencyCode }
+								tooltip={
+									<BalanceTooltip
```
Comment (haszari) [inline client/components/account-balances/index.tsx]: Might be worth factoring out these into semantic tooltip components, e.g. `TotalBalanceTooltip` and `AvailableBalanceTooltip`. Then if there is some logic to fine-tune the content (e.g. add info about implications of a negative total balance), it's abstracted away from this top-level component.

Comment (haszari) [reply client/components/account-balances/index.tsx]: Side note – `BalanceTooltip` might not be adding much value, it's effectively a synonym / wrapper for `ClickToolTip`.

File: client/components/account-balances/strings.ts [hunk 6]
```diff
@@ -21,7 +21,7 @@ export const greetingStrings = {
 
 export const fundLabelStrings = {
 	available: __( 'Available funds', 'woocommerce-payments' ),
-	pending: __( 'Pending funds', 'woocommerce-payments' ),
+	total: __( 'Total balance', 'woocommerce-payments' ),
```
Comment (haszari) [inline client/components/account-balances/strings.ts:24]: Is it serving us to have these strings factored out of the component?

**Review by haszari — COMMENTED** [review]
This is overall looking good, though I have a few suggestions:

#### functionality / merchant facing
1. I think the two new tooltips should consistently display. If we keep the `negative balance` info, I think it should be included in the total balance tooltip (when applicable) – though I defer to product/design for this.
2. The tooltips look cramped – the line spacing is tight (compared to mockup). This might be a problem with base tooltip styles?

#### code/technical
- `maxWidth` - prefer using cascading styles (CSS only solution) for tweaking the visual look, is that an option here? And/or can we use a standard width for all tooltips.
- (low priority, comment on existing code) might be worth shifting to semantic tooltips for each use case - then can simplify the parent componet, and probably remove low-value `BalanceTooltip`.

File: client/components/account-balances/index.tsx (hunk 3 above)
Comment (shendy-a8c) [reply client/components/account-balances/index.tsx]: > The linked documentation, and the tooltip really only apply to total balance.

I see that the [docs](https://woo.com/document/woopayments/fees-and-debits/account-showing-negative-balance/) only refer to a generic 'balance' and not total balance, available balance, or pending balance, so I thought it's suitable to be used for any balance block that shows a negative number.

Note that available balance *can* be negative too, eg: pdjTHR-2Sz-p2#comment-3983

> When the merchant has a negative total balance, add the info about negative balance to the "total balance" tooltip.

I like the idea of combining the tooltip content instead of replacing.

Do we all agree @haszari  @rogermattic @csmcneill ?

File: client/components/account-balances/index.tsx (hunk 4 above)
Comment (shendy-a8c) [reply client/components/account-balances/index.tsx]: > This seems overcomplicated

I agree. Without drilling `maxWidth`, we'll end up with narrower tooltip.

Screenshot 2024-02-22 at 02 40 25

I actually prefer for more simple diff if we are OK with narrower tooltip like that.

Adding `maxWidth` was necessary because the [BalanceTooltip](https://github.com/Automattic/woocommerce-payments/blob/005f3317b6acea383670af322699de067775be63/client/components/account-balances/balance-tooltip.tsx#L18) renders [ClickTooltip](https://github.com/Automattic/woocommerce-payments/blob/005f3317b6acea383670af322699de067775be63/client/components/tooltip/index.tsx#L109) which renders [TooltipBase](https://github.com/Automattic/woocommerce-payments/blob/005f3317b6acea383670af322699de067775be63/client/components/tooltip/tooltip-base.tsx#L174) which [sets an inline `max-width`](https://github.com/Automattic/woocommerce-payments/blob/005f3317b6acea383670af322699de067775be63/client/components/tooltip/tooltip-base.tsx#L213) in a function that calculates tooltip position, window dimension etc, so it's pretty complex stuffs to modify.

File: client/components/account-balances/index.tsx (hunk 5 above)
Comment (shendy-a8c) [reply client/components/account-balances/index.tsx]: > Might be worth factoring out these into semantic tooltip components, e.g. TotalBalanceTooltip and AvailableBalanceTooltip.

Good idea. Will implement once we agree on https://github.com/Automattic/woocommerce-payments/pull/8140/files#r1498209420.

File: client/components/account-balances/strings.ts (hunk 6 above)
Comment (shendy-a8c) [reply client/components/account-balances/strings.ts:24]: There are 3 usages in `client/components/account-balances/index.tsx` so there is benefit of storing it as a 'constant' but not sure having a separate `strings.ts` is a good design.

I see for other component it's structured that way, having a `strings.ts`.

**Comment by shendy-a8c** [comment]
Instead of waiting for confirmation from design (read https://github.com/Automattic/woocommerce-payments/pull/8140#discussion_r1498209420), I went ahead and addressed @haszari's feedbacks.

Changes made:
- Make tooltip look more like the design
- Instead of showing different content when balance is negative, append that content to the tooltip.
- Make separate component of `TotalBalanceTooltip` and `AvailableBalanceTooltip` so the logic of the tooltip is not written in-line in `AccountBalances`.

Total balance tooltip and available balance tooltip when their amounts are not negative:

Screenshot 2024-02-24 at 09 02 54

Screenshot 2024-02-24 at 09 07 56

Total balance tooltip and available balance tooltip when their amounts are negative:

Screenshot 2024-02-24 at 09 02 21

Screenshot 2024-02-24 at 09 02 27

(I know those double 'Learn more's look weird but I put them in separate paragraphs to help)

This PR is ready for another round of review.

**Comment by rogermattic** [comment]
Hey @shendy-a8c! Thanks for working on those changes; it looks good with @haszari 's feedback and the revised logic for the negative balance case!

I made this mockup which would be a way to solve the "Learn more" weirdness :) Do you think this could work?

Screenshot 2024-02-25 at 12 34 45

**Comment by shendy-a8c** [comment]
Yes! That looks good @rogermattic. Thank you!

File: client/components/account-balances/index.tsx (hunk 4 above)
Comment (haszari) [reply client/components/account-balances/index.tsx]: > Adding maxWidth was necessary because the [BalanceTooltip](https://github.com/Automattic/woocommerce-payments/blob/005f3317b6acea383670af322699de067775be63/client/components/account-balances/balance-tooltip.tsx#L18) renders [ClickTooltip](https://github.com/Automattic/woocommerce-payments/blob/005f3317b6acea383670af322699de067775be63/client/components/tooltip/index.tsx#L109) which renders [TooltipBase](https://github.com/Automattic/woocommerce-payments/blob/005f3317b6acea383670af322699de067775be63/client/components/tooltip/tooltip-base.tsx#L174) which [sets an inline max-width](https://github.com/Automattic/woocommerce-payments/blob/005f3317b6acea383670af322699de067775be63/client/components/tooltip/tooltip-base.tsx#L213) in a function that calculates tooltip position, window dimension etc, so it's pretty complex stuffs to modify.

I see! That's pretty limiting, I wonder if `TooltipBase` needs to do that. Might be worth logging a (low priority) issue.

File: client/components/account-balances/balance-tooltip.tsx [hunk 7]
```diff
@@ -3,29 +3,165 @@
...
 	content,
+	maxWidth,
 } ) => {
 	return (
 		<ClickTooltip
 			content={ content }
 			className="wcpay-account-balances__balances__item__tooltip"
 			buttonIcon={ <HelpOutlineIcon /> }
 			buttonLabel={ label }
+			maxWidth={ maxWidth }
```
Comment (haszari) [inline client/components/account-balances/balance-tooltip.tsx]: I was suggesting to remove `BalanceTooltip` entirely, it doesn't add much value. The prop values it provides for would be more explicit directly inline in `TotalBalanceTooltip` and `AvailableBalanceTooltip`. 

No worries if it stays, not causing problems, but if some future engineer feels constrained by it my advice would be to remove.

File: client/components/account-balances/balance-tooltip.tsx [hunk 8]
```diff
@@ -3,29 +3,165 @@
...
+									/>
+								),
+							},
+						} ) }
+					</p>
+					<p>
+						{ balance < 0 &&
+							interpolateComponents( {
+								mixedString: __(
+									'Negative account balance? {{discoverWhyLink}}Discover why.{{/discoverWhyLink}}',
```
Comment (haszari) [inline client/components/account-balances/balance-tooltip.tsx:130]: To me `account balance` refers to the `total` balance, and that linked doc page is primarily about why a merchant's total (aka "account") balance is negative (typically: more refunds or disputes than sales).

I don't think showing this info in the pending balance will cause issues, but I'm not convinced it's necessary. When the pending balance is negative, I _think_ (?) this is usually temporary due to how payouts work (possibly specific to instant?), and we don't explain much about this scenario on the help page.

Curious for thoughts from @csmcneill who has more experience of negative balances in practice!

File: client/components/account-balances/strings.ts (hunk 6 above)
Comment (haszari) [reply client/components/account-balances/strings.ts:24]: I see this pattern is used in our code, but I'm not convinced – to me it makes the code less meaningful to extract the strings (and documentation links, etc). One of the wonderful things about react is you can look at the code/markup and understand what the component looks like and does. Moving strings to constants makes this a little harder, since the reader needs to look up each constant to see what the string is. So when I'm working on components that feel disconnected like this, I consider pulling string back in to make it easier to maintain and more self-contained.

Anyway, I'm just sharing my thoughts – no need to change this if it' working for you :)

File: client/components/account-balances/balance-tooltip.tsx [hunk 9]
```diff
@@ -3,29 +3,165 @@
...
 };
 
-export default BalanceTooltip;
+export const TotalBalanceTooltip: React.FC< TotalBalanceTooltipProps > = ( {
+	balance,
+} ) => {
+	return (
+		<BalanceTooltip
+			label={ `${ fundLabelStrings.total } tooltip` }
+			maxWidth={ '315px' }
```
Comment (haszari) [inline client/components/account-balances/balance-tooltip.tsx]: Is this maxWidth to ensure the equation (`Total balance = Available funds + Pending funds`) is not wrapped? Would be good to note that in the code, so future readers know why and can iterate on how we handle that constraint.

Comment (haszari) [reply client/components/account-balances/balance-tooltip.tsx]: > I actually prefer for more simple diff if we are OK with narrower tooltip like that.

Hmm, I guess we could render the equation on two lines like this:

```
Total balance = 
Available funds + Pending funds
```

Not sure if that's clear enough, curious for thoughts from @rogermattic (and on other ideas below).


> Adding maxWidth was necessary because the [BalanceTooltip](https://github.com/Automattic/woocommerce-payments/blob/005f3317b6acea383670af322699de067775be63/client/components/account-balances/balance-tooltip.tsx#L18) renders [ClickTooltip](https://github.com/Automattic/woocommerce-payments/blob/005f3317b6acea383670af322699de067775be63/client/components/tooltip/index.tsx#L109) which renders [TooltipBase](https://github.com/Automattic/woocommerce-payments/blob/005f3317b6acea383670af322699de067775be63/client/components/tooltip/tooltip-base.tsx#L174) which [sets an inline max-width](https://github.com/Automattic/woocommerce-payments/blob/005f3317b6acea383670af322699de067775be63/client/components/tooltip/tooltip-base.tsx#L213) in a function that calculates tooltip position, window dimension etc, so it's pretty complex stuffs to modify.

I see! That's frustrating – an example of where an earlier decision / detail limits our options. 

- Can we undo this ? In your opinion, does `TooltipBase` need to force a max width in inline style, could it move to css?
- Can we make the base tooltip width bigger (i.e. make all tooltips wider) to work better for our tooltip?
- If `TooltipBase` needs to force a width, could it use `minWidth`, allowing overriding to make things wider?

**Review by haszari — APPROVED** [review]
Added some more comments - there's still a few tradeoffs in the code, maybe we can make it better/more flexible while we're here.

None of my feedback is blocking – this is working well and looking good. Note I only tested one scenario (no negative balance).

File: client/components/account-balances/balance-block.tsx [hunk 10]
```diff
@@ -8,25 +8,30 @@ import * as React from 'react';
...
+ * @property {boolean} [isLoading]																			Optional. Whether the balance block is loading.
  */
 interface BalanceBlockProps {
 	id: string;
 	title: string;
 	currencyCode: string;
-	tooltip?: React.ReactElement< typeof BalanceTooltip >;
+	tooltip?: React.ReactElement<
+		typeof TotalBalanceTooltip | typeof AvailableBalanceTooltip
+	>;
```
Comment (haszari) [inline client/components/account-balances/balance-block.tsx]: Curious to hear @Jinksi 's thoughts on `BalanceBlock` component and strongly typing its props.

This feels like tight-coupling code smell to me:

- How strict do we need to be about the `tooltip` prop – e.g. can we require it to be a kind of tooltip, or a small bit of markup, or is it ok to just require that it's a renderable component (assuming that's possible in TypeScript)? 
- Is `BalanceBlock` and `BalanceBlockProps` serving us? It feels overly specific and tightly coupled to the outer block's needs. If we change how we display balances, we'll likely change `BalanceBlock` and strongly typed props. Would the code be worse if we inlined it all?

File: client/components/account-balances/balance-tooltip.tsx (hunk 7 above)
Comment (shendy-a8c) [reply client/components/account-balances/balance-tooltip.tsx]: Ah I missed that. Good point that `BalanceTooltip ` doesn't add much value. Removed in https://github.com/Automattic/woocommerce-payments/pull/8140/commits/d607985a091738d96aece19cf3a35e31ef985d06

File: client/components/account-balances/balance-tooltip.tsx (hunk 9 above)
Comment (shendy-a8c) [reply client/components/account-balances/balance-tooltip.tsx]: IMO, it looks good in one line.

> Would be good to note that in the code, so future readers know why and can iterate on how we handle that constraint.

Good call to put some description in a comment. Added comment in https://github.com/Automattic/woocommerce-payments/pull/8140/commits/d607985a091738d96aece19cf3a35e31ef985d06.

> In your opinion, does TooltipBase need to force a max width in inline style, could it move to css?

Can't tell for sure. I see that it's set and used in a `useEffect()` ([ref](https://github.com/Automattic/woocommerce-payments/blob/530783fe131414f5189259aed5dc862ad89f7d74/client/components/tooltip/tooltip-base.tsx#L256)).

> If TooltipBase needs to force a width, could it use minWidth, allowing overriding to make things wider?

IMO the current intention is to not let the tooltip content 'stretches' the tooltip without control. This is more important in narrow screen I think.

Changing `TooltipBase` needs to be done carefully as it might affect other UI and out of scope of this PR. Created https://github.com/Automattic/woocommerce-payments/issues/8269.

**Comment by shendy-a8c** [comment]
> None of my feedback is blocking

Thank you for the review, @haszari. I'll mark this PR as 'ready to merge' but will wait for other feedbacks before merging.

Any follow up can be done in a separate issue / PR.

File: client/components/account-balances/balance-tooltip.tsx (hunk 9 above)
Comment (rogermattic) [reply client/components/account-balances/balance-tooltip.tsx]: > Hmm, I guess we could render the equation on two lines like this:
> 
> ```
> Total balance = 
> Available funds + Pending funds
> ```
> 
> Not sure if that's clear enough, curious for thoughts from @rogermattic (and on other ideas below).
> 

I prefer it when it renders in a single line, BUT I don't think it is necessary as it reads OK when split into two lines.

File: client/components/account-balances/balance-tooltip.tsx (hunk 8 above)
Comment (csmcneill) [reply client/components/account-balances/balance-tooltip.tsx:130]: > When the pending balance is negative, I think (?) this is usually temporary due to how payouts work (possibly specific to instant?), and we don't explain much about this scenario on the help page.

That's my experience of it. I think that we can also include refunds and disputes in here, too, since those can also make an account go negative temporarily. If a balance is negative for an extended period of time, that's usually because we cannot debit the attached bank account or debit card.

I'm planning on including a new section in our document at https://woo.com/document/woopayments/deposits/deposit-schedule/#total-balance that focuses on the Total balance, what it means, and some nuances to keep an eye out for (e.g., it being lower than the available balance due to funds that are in flight).

File: client/components/account-balances/balance-block.tsx (hunk 10 above)
Comment (Jinksi) [reply client/components/account-balances/balance-block.tsx]: > How strict do we need to be about the tooltip prop

Yeh I agree, `React.ReactElement` would suffice. The duplication in JSDoc types can be removed too IMO. We can add descriptive comments to the TS declarations instead.

image



> Would the code be worse if we inlined it all?

I'd say it would be better to inline, since it is used only twice in a single file. Might be better to refactor in a separate PR though.

Comment (haszari) [reply client/components/account-balances/balance-block.tsx]: > Might be better to refactor in a separate PR though.

Totally, no need to bite off all this stuff now 🙌🏻

File: client/components/account-balances/balance-tooltip.tsx [hunk 11]
```diff
@@ -3,29 +3,147 @@
...
+						className="wcpay-account-balances__balances-total-balance-tooltip-notice"
+						isDismissible={ false }
+					>
+						{ __(
+							'Total balance = Available funds + Pending funds',
+							'woocommerce-payments'
+						) }
+					</InlineNotice>
+					<>
+						{ balance < 0 &&
```
Comment (naman03malhotra) [inline client/components/account-balances/balance-tooltip.tsx]: Nitpick: Maybe a good practice to extract it out and be more declarative
```js
const negativeBalance = balance < 0;
```

File: client/components/account-balances/index.tsx [hunk 12]
```diff
@@ -3,8 +3,7 @@
  */
 import * as React from 'react';
 import { Flex, TabPanel } from '@wordpress/components';
-import { __, sprintf } from '@wordpress/i18n';
-import interpolateComponents from '@automattic/interpolate-components';
+import { __ } from '@wordpress/i18n';
```
Comment (naman03malhotra) [inline client/components/account-balances/index.tsx]: Maybe we can remove this, not being used.

File: client/components/tooltip/style.scss [hunk 13]
```diff
@@ -73,7 +73,6 @@
 		&__tooltip {
 			// Specific styles for the click tooltip variant.
 			position: relative;
-			max-width: 292px;
```
Comment (naman03malhotra) [inline client/components/tooltip/style.scss:76]: Curious to as to why we moved it from styles to props?

File: client/components/account-balances/style.scss [hunk 14]
```diff
@@ -35,3 +35,29 @@
...
+		margin-bottom: 10px;
+
+		&.components-notice {
+			padding: 8px;
+		}
+
+		.components-notice__content {
+			font-size: 12px;
+			white-space: nowrap;
+			color: #054b7a;
```
Comment (naman03malhotra) [inline client/components/account-balances/style.scss]: Nitpick: do we have a color code for this already defined to be used?

File: client/components/account-balances/balance-tooltip.tsx [hunk 15]
```diff
@@ -3,29 +3,147 @@
...
-export default BalanceTooltip;
+export const AvailableBalanceTooltip: React.FC< AvailableBalanceTooltipProps > = ( {
+	balance,
+} ) => {
+	return (
+		<ClickTooltip
+			className="wcpay-account-balances__balances__item__tooltip"
+			buttonIcon={ <HelpOutlineIcon /> }
+			buttonLabel={ `${ fundLabelStrings.available } tooltip` }
+			maxWidth={ balance < 0 ? '280px' : undefined } // So that the negative balance sentence is not wrapped and looks like the design.
```
Comment (naman03malhotra) [inline client/components/account-balances/balance-tooltip.tsx]: Nitpick: Maybe to verbose to have this logic in the props, maybe we can extract it out?

**Review by naman03malhotra — COMMENTED** [review]
Great work 🎉 , left some nitpicks. Nothing that blocks this PR.

File: client/components/account-balances/balance-tooltip.tsx (hunk 11 above)
Comment (haszari) [reply client/components/account-balances/balance-tooltip.tsx]: Good point! Or even more explicit, `balanceIsNegative =` (or `isBalanceNegative`?)

File: client/components/account-balances/style.scss (hunk 14 above)
Comment (Jinksi) [reply client/components/account-balances/style.scss]:
```suggestion
			color: $wp-blue-70;
```

I think `$wp-blue-70` is the closest match, but haven't looked at Figma design.

image

Comment (naman03malhotra) [reply client/components/account-balances/style.scss]: @Jinksi can you please point me the file where all the CSS variables are defined?

File: client/components/tooltip/style.scss (hunk 13 above)
Comment (shendy-a8c) [reply client/components/tooltip/style.scss:76]: This CSS is overridden by `TooltipBase`'s in-line CSS, so it's unused and removed. We might set max-width using CSS class instead of in-line but since it will involve changing `TooltipBase` that is used by other UIs, I created https://github.com/Automattic/woocommerce-payments/issues/8269.

File: client/components/account-balances/balance-tooltip.tsx (hunk 15 above)
Comment (shendy-a8c) [reply client/components/account-balances/balance-tooltip.tsx]: Address in [0b9ab72](https://github.com/Automattic/woocommerce-payments/pull/8140/commits/0b9ab7207c8cabd7052b187c1b503a915d7174dc).

File: client/components/account-balances/style.scss (hunk 14 above)
Comment (shendy-a8c) [reply client/components/account-balances/style.scss]: > I think $wp-blue-70 is the closest match

Looks like it.

Asked further about this here: p1709146807215419-slack-C02BW3Z8SHK

File: client/components/account-balances/index.tsx (hunk 12 above)
Comment (shendy-a8c) [reply client/components/account-balances/index.tsx]: Good catch! Removed here https://github.com/Automattic/woocommerce-payments/pull/8140/commits/dcd7b5f2db3c6786ceed5904c167db43bd0b2878.

File: client/components/account-balances/balance-tooltip.tsx (hunk 11 above)
Comment (shendy-a8c) [reply client/components/account-balances/balance-tooltip.tsx]: Addressed here https://github.com/Automattic/woocommerce-payments/pull/8140/commits/0b9ab7207c8cabd7052b187c1b503a915d7174dc.

File: client/components/account-balances/balance-block.tsx (hunk 10 above)
Comment (shendy-a8c) [reply client/components/account-balances/balance-block.tsx]: Thank you for the suggestion, all! Addressed in https://github.com/Automattic/woocommerce-payments/pull/8140/commits/6f64549a8ab54035702903555bc74127bdca866e.

**Comment by shendy-a8c** [comment]
Thank you all for the feedback. I think I have addressed them all.

Let me know if there is anything else. I plan to merge this PR today at the latest tomorrow so it can make it before the code-freeze.

File: client/components/account-balances/style.scss (hunk 14 above)
Comment (Jinksi) [reply client/components/account-balances/style.scss]: https://github.com/Automattic/woocommerce-payments/blob/835df7f966da292b69e3a3b16fdfe41ce04a8611/client/stylesheets/abstracts/_colors.scss#L29

Also https://github.com/Automattic/color-studio/blob/master/dist/color-variables.scss are imported and used throughout WooPayments.

**Comment by Jinksi** [comment]
FYI: all E2E tests are failing due to #8291.
