### PR TITLE
Make custom fees show up correctly in settings tooltip, whenever applicable

### LINKED ISSUE #5255: Fees: details in a popup on setting page are not respecting custom fees
### Describe the bug

When custom fees are assigned to the merchants, the fee details in the popup reflect the base fee and not the custom one.
Screenshot from 2022-12-07 09-53-38

### To Reproduce

Assing a custom fee to the merchant, refresh the account cache, and look at details as per the screenshot. Note the base fee differences.

### Expected behavior

As an end-user, I expect to see the custom fee rates in the details.

### Additional context

n/a

### PR DESCRIPTION
**Pull request by nagpai**
Fixes #5255

#### Changes proposed in this Pull Request

The PR makes the tooltips across each payment method within WC Pay settings, show the correct applicable fees. If there is a negotiated custom fee, it will show the custom fee, else it will show the standard base rate. 

#### Screenshots

<details><summary>

##### Before

 </summary>

before

</details>
<details><summary>

##### After

</summary>

after

</details>

#### Testing instructions

1. Assign a custom fee to the merchant account 
2. Browse to `Payments > Settings` and mouse-over the fees pill against any payment methods, as shown in the screenshot. 
3. You should see the custom rates in the tooltip popup. 

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply) 

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: client/components/payment-methods-list/payment-method.js [hunk 1]
```diff
@@ -46,6 +46,7 @@ const PaymentMethod = ( {
 		return onUncheckClick( id );
 	};
 
+	//console.log( accountFees );
```
Comment (kalessil) [inline client/components/payment-methods-list/payment-method.js]: Dead code, can we drop this, please?

File: client/utils/account-fees.tsx [hunk 2]
```diff
@@ -86,17 +86,19 @@ export const getCurrentFee = (
 };
 
 export const formatMethodFeesTooltip = (
-	accountFees: FeeStructure | undefined
+	accountFees: FeeStructure
 ): JSX.Element => {
 	if ( ! accountFees ) return <></>;
+	// If there is a discount, use that instead of the base fee.
```
Comment (kalessil) [inline client/utils/account-fees.tsx]: We can skip this comment.

File: client/utils/account-fees.tsx [hunk 3]
```diff
@@ -86,17 +86,19 @@ export const getCurrentFee = (
...
+	const currentFee = getCurrentFee( accountFees );
```
Comment (kalessil) [inline client/utils/account-fees.tsx]: For clarity, can we rename this function to `getCurrentBaseFee`, please? And correspondingly, the local variable to `currentBaseFee`.

**Review by kalessil — CHANGES_REQUESTED** [review]
Looks good overall and tests well! Leaving some comments + pushing one more fix related to this tooltip.

File: client/components/payment-methods-list/payment-method.js (hunk 1 above)
Comment (nagpai) [reply client/components/payment-methods-list/payment-method.js]: Sorry about missing this one. I have [removed it](https://github.com/Automattic/woocommerce-payments/pull/5299/commits/2d8b5afb1599fc98fa4bb1c4651818d20acc4267#diff-23a1b15bc75d0f257ab6e00340f08eaa9280872e4f83949e6e847500000491f3) 

Commit - [1ec4acd](https://github.com/Automattic/woocommerce-payments/pull/5299/commits/1ec4acd531489ad3f58d1b99b79a875f498f4862)

File: client/utils/account-fees.tsx (hunk 2 above)
Comment (nagpai) [reply client/utils/account-fees.tsx]: Sure, I have removed [it here](https://github.com/Automattic/woocommerce-payments/pull/5299/commits/2d8b5afb1599fc98fa4bb1c4651818d20acc4267#diff-3287280562aa1d47c819215cb3d6cfca08ecf177711c1ad791ef2103cf5bf090L92)

Commit - [1ec4acd](https://github.com/Automattic/woocommerce-payments/pull/5299/commits/1ec4acd531489ad3f58d1b99b79a875f498f4862)

File: client/utils/account-fees.tsx (hunk 3 above)
Comment (nagpai) [reply client/utils/account-fees.tsx]: Sure, I have updated this and other references to `currentBaseFee`. That is indeed more descriptive. 

Commit - [1ec4acd](https://github.com/Automattic/woocommerce-payments/pull/5299/commits/1ec4acd531489ad3f58d1b99b79a875f498f4862)

**Review by kalessil — APPROVED** [review]

**Review by dmvrtx — APPROVED** [review]
Looks good from the coding part! Can't fully test at the moment though.

File: client/utils/account-fees.tsx [hunk 4]
```diff
@@ -77,7 +77,7 @@ const getFeeDescriptionString = ( fee: BaseFee ): string => {
 	return '';
 };
 
-export const getCurrentFee = (
+export const getCurrentBaseFee = (
```
Comment (mgascam) [inline client/utils/account-fees.tsx:80]: Maybe a nitpick. I find the name of this function a bit misleading. Looking at the return type it can return BaseFee or DiscountFee so I'd suggest changing its name to reflect that: `getCurrentBaseFeeOrDiscountFee`.

You could also argue that we have return types so we don't have to rely on function names to tell what a function will return. But in that case, I would leave it as before `getCurrentFee`.

**Review by mgascam — APPROVED** [review]
LGTM! I did code review only, no tests. I just left a comment related to naming. Please feel free to ignore it, since it may be coming from a lack of knowledge about how the structure of fees work at the moment.

File: client/utils/account-fees.tsx (hunk 4 above)
Comment (kalessil) [reply client/utils/account-fees.tsx:80]: This client part will need some updates as we finish migrating fees into DB. Hence we'll make another round of naming nitpicking.

Comment (nagpai) [reply client/utils/account-fees.tsx:80]: Thanks for pointing this out, Miguel. From what I spotted, as seen by the merchant in the settings page: 

1. When there is a discount rate available, The base fee is shown as the discounted price 
2. When there is no discount rate available, the base fee is shown as the default ( without discount override ). 

The merchant-facing label, in either case remains as `Base Fee`.  This is my understanding. Happy to revisit this if needed. Thanks for the review!
