### PR TITLE
Fix using CC token for wrong payment method

### LINKED ISSUE #1635: Don't use saved CC if different payment method is selected
Currently a customer's saved CC payment method will be used during checkout even if a different payment method was selected. I noticed this while adding the Giropay payment method. When the Giropay payment method is selected, but a saved card was preselected by default, it tries to complete the purchase with a Giropay intent with the saved card payment method (it appears, exact details may differ). If a different payment method is selected, only that methods tokens should be provided / checked.

**Steps to Reproduce**
- Create a saved credit card with a purchase.
- Enable Giropay
    - Set store currency to euro
    - Add _wcpay_feature_giropay to wp_options table with a value of 1
    - Enable Giropay by going to WooCommerce > Settings > Payments > Manage WooCommerce Payments (/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments) and using the checkbox at the bottom of the page.
- Add an item to cart and checkout
- Notice that saved credit card is selected by default
- Select Giropay payment method
- Click Place Order
- Receive error about different payment method for payment intent

https://d.pr/i/alps83

### PR DESCRIPTION
**Pull request by bborman22**
Fixes #1635 

#### Changes proposed in this Pull Request

Fix using CC token for wrong payment method

Previously the plugin would default to using the saved CC token during checkout if it existed, regardless of the payment method the customer chose. This PR fixes that issue by only looking for a token that matches the customer's selected payment method. The assumption that if a CC token is available then it should be used was accurate when there was only a single payment method, with the introduction of other payment methods this assumption is no longer accurate. This update now addresses that and will only look for tokens relevant to the payment method the customer chose.

This update also required updating some existing tests to include the `payment_method` key in the request to help with looking up the saved payment method token.

#### Testing instructions

- With a store using Euros and having multiple payment methods enabled (Giropay was the method focused on during testing)
- Perform a checkout using a credit card and save the credit card for future use during checkout
- Begin another checkout, confirm that the saved credit card is selected under the Credit card payment method
- Select Giropay and click Place Order
- Should be able to successfully checkout using Giropay while the saved card was still selected by default under Credit card

**Before**
https://d.pr/i/alps83

**After**
https://d.pr/i/xJ2LtX

-------------------

- [ ] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/class-payment-information.php [hunk 1]
```diff
@@ -237,14 +237,8 @@ public static function get_payment_method_from_request( array $request ): string
...
 	public static function get_token_from_request( array $request ) {
-		$payment_method = $request['payment_method'] ?? null;
-		if ( Sepa_Payment_Gateway::GATEWAY_ID === $payment_method ) {
-			$request_gateway_id = Sepa_Payment_Gateway::GATEWAY_ID;
-		} else {
-			$request_gateway_id = CC_Payment_Gateway::GATEWAY_ID;
-		}
-
-		$token_request_key = 'wc-' . $request_gateway_id . '-payment-token';
+		$payment_method    = $request['payment_method'] ?? null;
```
Comment (bborman22) [inline includes/class-payment-information.php:240]: Since the previous conditional was checking the equality of `payment_method` and `GATEWAY_ID` and then just using the `GATEWAY_ID`, I thought this would be more versatile as we add new payment methods rather than having several conditionals for each method to only assign the variable the `payment_method` value anyway. Since `null` resolves to empty string during concatenation, I thought this process was safe and the `isset` check will kick us out.

**Review by superdav42 — APPROVED** [review]
LGTM!
