### PR TITLE
Show last 4 digit credit card in subscriptions order's note when updating failed payment

### LINKED ISSUE #871: Payment method changed from "Credit card" to "Credit card"
It would be nice to display the last four digits of the cards in play. Otherwise this message isn't super helpful.

To reproduce, follow the steps in #832 for "Failed payment update"

Screen Shot 2020-08-28 at 1 45 01 PM

### PR DESCRIPTION
**Pull request by shendy-a8c**
Fixes #871

#### Changes proposed in this Pull Request

* Add filter hooks to ones defined in this 3908-gh-woocommerce/woocommerce-subscriptions .
* Get _old_ payment's last 4 digit from 2nd to last payment token because payment tokens are added in chronological order, so the old (failing) payment is the 2nd to last in that order's payment tokens array.
* Get _new_ payment's last 4 digit from last payment token or from request, depending whether user choose from a saved payment or a new payment.

#### Testing instructions

Follow these steps, [copied from PR#832](https://github.com/Automattic/woocommerce-payments/pull/832):
1. Place an order for a free-trial subscription product or update an existing subscription with an attachable but declined card, such as `4000000000000341`
2. Assert that the order or update is successful
4. Go to the subscriptions admin page and click on the subscription
5. Run the `Process renewal` action
6. Assert that the renewal fails
7. Go to My Account > Subscriptions and click on the subscription
8. Scroll down to the order list and click on Pay for the failed order
9. Insert another basic card details (or use a saved card) and update the failed order
10. Assert that the payment for the renewal order is successful
11. Go to the subscriptions admin page, click on the subscription and run the `Process renewal` action
13. Assert that the renewal used the card used in the failed renewal and that the transaction is listed in the WCPay transactions page 

Notice the order note of the subscription order will show:
```Payment method changed from “Credit card” to “Credit card” by the subscriber from their account page.```

With this fix, it should show:
Screen Shot 2020-12-07 at 08 48 58

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by shendy-a8c** [comment]
WIP:

- Unit test.

- Investigate why [E2E failed](https://travis-ci.com/github/Automattic/woocommerce-payments/jobs/455300719). Failed test is related to saved payment, which is related to my change.

**Comment by vbelolapotkov** [comment]
@shendy-a8c I tried to reproduce it but failed. Did you use dev version of subs for that?

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php [hunk 1]
```diff
@@ -380,4 +384,89 @@ public function render_custom_payment_meta_input( $subscription, $field_id, $fie
...
+		if ( $old_payment_method !== $new_payment_method ) {
+			return $old_payment_method_title;
+		}
+
+		$last_order_id = $subscription->get_last_order();
+		if ( ! $last_order_id ) {
+			return $old_payment_method_title;
+		}
+
+		$last_order = wc_get_order( $last_order_id );
```
Comment (vbelolapotkov) [inline includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:414]: I've tested things locally and see that new tokens are added to the subscription itself rather that to related orders. In this case taken token from last order might be incorrect.

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php [hunk 2]
```diff
@@ -380,4 +384,89 @@ public function render_custom_payment_meta_input( $subscription, $field_id, $fie
...
+		$token_ids  = $last_order->get_payment_tokens();
+		// since old payment must be the second to last saved payment...
+		if ( count( $token_ids ) < 2 ) {
+			return $old_payment_method_title;
+		}
+
+		$second_to_last_token_id = $token_ids[ count( $token_ids ) - 2 ];
+		$token                   = WC_Payment_Tokens::get( $second_to_last_token_id );
+		if ( ! $token || ! ( $token instanceof WC_Payment_Token_CC && method_exists( $token, 'get_last4' ) ) ) {
```
Comment (vbelolapotkov) [inline includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:423]: `get_last4` is defined for `WC_Payment_Token_CC` class so checking it existence is not necessary, isn't it?

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php [hunk 3]
```diff
@@ -380,4 +384,89 @@ public function render_custom_payment_meta_input( $subscription, $field_id, $fie
...
+			return $old_payment_method_title;
+		}
+
+		// translators: 1: payment method likely credit card, 2: last 4 digit.
+		return sprintf( __( '%1$s ending in %2$s', 'woocommerce-payments' ), $old_payment_method_title, $token->get_last4() );
```
Comment (vbelolapotkov) [inline includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:428]: 🤔 Hm, interesting. In case of two consecutive calls will we get `Credit Card` or `Credit Card ending in XXXX` for the second time as value for $old_payment_method_title? Did you test this case? Because now it looks like with the second change the old title will become `Credit Card ending in XXXX ending in XXXX`.

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php [hunk 4]
```diff
@@ -380,4 +384,89 @@ public function render_custom_payment_meta_input( $subscription, $field_id, $fie
...
+		if ( WC_Payment_Gateway_WCPay::GATEWAY_ID !== $new_payment_method ) {
+			return $new_payment_method_title;
+		}
+
+		$old_payment_method = $subscription->get_meta( '_old_payment_method' );
+
+		// if old and new payment method are different, no need to show specific.
+		if ( $new_payment_method !== $old_payment_method ) {
+			return $new_payment_method_title;
+		}
```
Comment (vbelolapotkov) [inline includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:450]: Same as above. Why old payment method should affect how we display title for the new one?

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php [hunk 5]
```diff
@@ -380,4 +384,89 @@ public function render_custom_payment_meta_input( $subscription, $field_id, $fie
...
+
+		$request = isset( $_POST ) ? $_POST : []; // phpcs:ignore WordPress.Security.NonceVerification.Missing
+		$token   = WCPay\Payment_Information::get_token_from_request( $request );
```
Comment (vbelolapotkov) [inline includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:453]: That looks a bit hacky. If I understand correctly new token should be already set on the subscription when the filter is applied, no?

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php [hunk 6]
```diff
@@ -380,4 +384,89 @@ public function render_custom_payment_meta_input( $subscription, $field_id, $fie
...
+		if ( $token && $token instanceof WC_Payment_Token_CC && method_exists( $token, 'get_last4' ) ) {
```
Comment (vbelolapotkov) [inline includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:454]: Same as above regarding `method_exists`. 
That line alse makes me feel we need to extract title composition from token to own method.

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php [hunk 7]
```diff
@@ -380,4 +384,89 @@ public function render_custom_payment_meta_input( $subscription, $field_id, $fie
...
+			// translators: 1: payment method likely credit card, 2: last 4 digit.
+			return sprintf( __( '%1$s ending in %2$s', 'woocommerce-payments' ), $new_payment_method_title, $token->get_last4() );
+		}
+
+		$payment_method_id = WCPay\Payment_Information::get_payment_method_from_request( $request );
```
Comment (vbelolapotkov) [inline includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:459]: What's the condition for this code path?

File: tests/helpers/class-wc-helper-subscription.php [hunk 8]
```diff
@@ -10,19 +10,34 @@
  *
  * This helper class should ONLY be used for unit tests!.
  */
-class WC_Subscription {
+class WC_Subscription extends WC_Order {
```
Comment (vbelolapotkov) [inline tests/helpers/class-wc-helper-subscription.php:13]: It's unclear what is the need for extending WC_Order, could you please share your thoughts?

File: tests/test-class-wc-payment-gateway-wcpay-subscriptions.php [hunk 9]
```diff
@@ -171,6 +171,93 @@ public function test_update_failing_payment_method_does_not_copy_method_if_token
...
+		$post_payment_method_parameter = 'wcpay-payment-method';
+
+		$_POST[ $post_payment_token_parameter ] = $token2->get_id();
+
+		$old_payment_method_title_modified = (string) apply_filters( 'woocommerce_subscription_note_old_payment_method_title', $old_payment_method_title, $old_payment_method, $subscription );
+		$new_payment_method_title_modified = (string) apply_filters( 'woocommerce_subscription_note_new_payment_method_title', $new_payment_method_title, $new_payment_method, $subscription );
+		$this->assertContains( $last4_1, $old_payment_method_title_modified );
+		$this->assertContains( $last4_2, $new_payment_method_title_modified );
+
+		// case 2: same payment method, different last 4, new payment is *not* saved. expect api call called once and both old and new title to be modified.
```
Comment (vbelolapotkov) [inline tests/test-class-wc-payment-gateway-wcpay-subscriptions.php:220]: 1. IMO it's better to create one test for each case.
2. IIRC payment method is always saved for subs, no?

File: tests/test-class-wc-payment-gateway-wcpay-subscriptions.php [hunk 10]
```diff
@@ -171,6 +171,93 @@ public function test_update_failing_payment_method_does_not_copy_method_if_token
...
+		$old_payment_method = 'non-wc-pay';
+		$new_payment_method = 'non-wc-pay';
+		$subscription->update_meta_data( '_old_payment_method', $old_payment_method );
+		$subscription->set_payment_method( $new_payment_method );
+		$old_payment_method_title_modified = (string) apply_filters( 'woocommerce_subscription_note_old_payment_method_title', $old_payment_method_title, $old_payment_method, $subscription );
+		$new_payment_method_title_modified = (string) apply_filters( 'woocommerce_subscription_note_new_payment_method_title', $new_payment_method_title, $new_payment_method, $subscription );
+		$this->assertEquals( $old_payment_method_title, $old_payment_method_title_modified );
+		$this->assertEquals( $new_payment_method_title, $new_payment_method_title_modified );
+
+		// case 4: different payment method. expect both old and new title not modified.
```
Comment (vbelolapotkov) [inline tests/test-class-wc-payment-gateway-wcpay-subscriptions.php:250]: Mentioned above, I'm not 100% sure about this cross GW case.

**Review by vbelolapotkov — CHANGES_REQUESTED** [review]
Hey @shendy-a8c ! Thanks for your work on this. I have some questions and thoughts, though, left them as comments below.

@luizreis fyi, while I was messing around with this PR I noticed that updating subscription from one saved payment method to another doesn't work for me neither in this branch nor in main. Do you know something about it?

**Comment by luizreis** [comment]
> @luizreis fyi, while I was messing around with this PR I noticed that updating subscription from one saved payment method to another doesn't work for me neither in this branch nor in main. Do you know something about it?

@vbelolapotkov - good catch! I haven't looked at it in detail, but it looks like [`these lines`](https://github.com/Automattic/woocommerce-payments/blob/master/includes/class-wc-payment-gateway-wcpay.php#L610-L613) are not getting called when using already saved cards. That's because the payment processing gets to [this line](https://github.com/Automattic/woocommerce-payments/blob/master/includes/class-wc-payment-gateway-wcpay.php#L556) and exits without ever calling `add_token_to_order`.

I quickly removed the [`return` statement](https://github.com/Automattic/woocommerce-payments/blob/master/includes/class-wc-payment-gateway-wcpay.php#L558-L561) and the customer saved payment method changes started working. I'm not sure if removing it would cause any type of side effects, so would you mind opening an issue so we can investigate it in more detail? It looks like we missed this use case when refactoring this method.

**Comment by vbelolapotkov** [comment]
> > @luizreis fyi, while I was messing around with this PR I noticed that updating subscription from one saved payment method to another doesn't work for me neither in this branch nor in main. Do you know something about it?
> 
> @vbelolapotkov - good catch! I haven't looked at it in detail, but it looks like [`these lines`](https://github.com/Automattic/woocommerce-payments/blob/master/includes/class-wc-payment-gateway-wcpay.php#L610-L613) are not getting called when using already saved cards. That's because the payment processing gets to [this line](https://github.com/Automattic/woocommerce-payments/blob/master/includes/class-wc-payment-gateway-wcpay.php#L556) and exits without ever calling `add_token_to_order`.
> 
> I removed the [`return` statement](https://github.com/Automattic/woocommerce-payments/blob/master/includes/class-wc-payment-gateway-wcpay.php#L558-L561) for a quick test, and the customer saved payment method changes started working. I'm not sure if removing it would cause any type of side effects, so would you mind opening an issue so we can investigate it in more detail? It looks like we missed this use case when refactoring this method.

Created #1185

File: changelog.txt [hunk 11]
```diff
@@ -6,6 +6,7 @@
 * Fix - Fix crash if there's a problem connecting to the server.
 * Fix - Store Stripe customer for test and live mode.
 * Add - Display fee structure in transaction timelines.
+* Update - Show last 4 digit credit card number in order note when payment method is updated on failed renewal subscription order.
```
[the remark this answers is not in the document]
Comment (shendy-a8c) [reply changelog.txt]: Done. I just rebased this branch onto trunk and add the changelog for 1.9.0 and to readme.txt.

**Comment by shendy-a8c** [comment]
> @shendy-a8c I tried to reproduce it but failed. Did you use dev version of subs for that?

@vbelolapotkov This PR depends on [woocommerce-subscriptions 3.0.12](https://github.com/woocommerce/woocommerce-subscriptions/releases/download/3.0.12/woocommerce-subscriptions.zip).

File: includes/class-wc-payment-gateway-wcpay.php [hunk 12]
```diff
@@ -1668,4 +1668,17 @@ public function disable() {
...
+	 *
+	 * @param string $payment_method_id Payment method ID.
+	 *
+	 * @return array Payment method details.
+	 *
+	 * @throws API_Exception If payment method does not exist.
+	 */
+	public function get_payment_method( $payment_method_id ) {
+		return $this->payments_api_client->get_payment_method( $payment_method_id );
+	}
```
[the remark this answers is not in the document]
Comment (shendy-a8c) [reply includes/class-wc-payment-gateway-wcpay.php:1702]: I need to [call it from here](https://github.com/Automattic/woocommerce-payments/pull/1148/files#diff-a5e8d94b5af9b7536f23cf436b4eef1fb76da3069f34a63b4cf35c46051e417bR461).

However, it does not have to be public `get_payment_method()`. It should be `protected`.
Also, another way without creating a method is if I change `$payments_api_client` to `protected`.
What do you think?

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php [hunk 13]
```diff
@@ -380,4 +384,89 @@ public function render_custom_payment_meta_input( $subscription, $field_id, $fie
...
+		if ( WC_Payment_Gateway_WCPay::GATEWAY_ID !== $old_payment_method ) {
+			return $old_payment_method_title;
+		}
+
+		$new_payment_method = $subscription->get_payment_method();
+
+		// if old and new payment method are different, no need to show specific.
+		if ( $old_payment_method !== $new_payment_method ) {
+			return $old_payment_method_title;
+		}
```
[the remark this answers is not in the document]
Comment (shendy-a8c) [reply includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:407]: I try to be conservative here, ie not adding payment specific (4 last digit) if old and new payment is different, for example credit card changed to check. Only when it's credit card changed to credit card then specifics are needed.
What do you think?

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php (hunk 2 above)
Comment (shendy-a8c) [reply includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:423]: Yes, you're right. Removing the `method_exists()` check.

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php (hunk 3 above)
Comment (shendy-a8c) [reply includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:428]: Hmm.. interesting..

I didn't test that case, but giving it a closer look, I don't think it will keep adding trailing string like that because [the output of this hook will not be stored in the subscription order's meta. It will be just used as part of the order note](https://github.com/woocommerce/woocommerce-subscriptions/blob/trunk/includes/class-wc-subscriptions-change-payment-gateway.php#L529-L534).

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php (hunk 4 above)
Comment (shendy-a8c) [reply includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:450]: Same answer. Being conservative and won't add specifics when not needed.

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php (hunk 7 above)
Comment (shendy-a8c) [reply includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:459]: This is when user chooses to pay with new payment method but does not choose to save the payment. Hence, `$token` is empty.

File: tests/helpers/class-wc-helper-subscription.php (hunk 8 above)
Comment (shendy-a8c) [reply tests/helpers/class-wc-helper-subscription.php]: Just trying to mimic the real [WC_Subscription](https://github.com/woocommerce/woocommerce-subscriptions/blob/trunk/includes/class-wc-subscription.php#L15).

Also, in my unit test, I try to do what [update_payment_method()](1148-gh-woocommerce/woocommerce-subscriptions/blob/trunk/includes/class-wc-subscriptions-change-payment-gateway.php#L497) does and there are calls to WC_Order methods like [update_meta_data()](https://github.com/Automattic/woocommerce-payments/pull/1148/files#diff-933977839629fb49196cf683653de08b29c2f319c0cc0edb91ecac15d1e747a6R205).
Now it makes me wonder, if that call would make database change and if so, how does that happen in unit test.

File: tests/test-class-wc-payment-gateway-wcpay-subscriptions.php (hunk 10 above)
Comment (shendy-a8c) [reply tests/test-class-wc-payment-gateway-wcpay-subscriptions.php]: What is GW?

I put answers above about the behaviour of old and new hook depends on new and old payment, respectively.
I assume that that business logic.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 12 above)
[the remark this answers is not in the document]
Comment (vbelolapotkov) [reply includes/class-wc-payment-gateway-wcpay.php]: Protected method just proxies the call and doesn't bring any additional value to the parent class, so in this case making `payments_api_client` protected makes more sense IMO.

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php (hunk 13 above)
[the remark this answers is not in the document]
Comment (vbelolapotkov) [reply includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:407]: It still valuable hint IMO. `Payment method changed from credit card ending in xxxx to check.`

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php [hunk 14]
```diff
@@ -380,4 +384,89 @@ public function render_custom_payment_meta_input( $subscription, $field_id, $fie
...
+		$last_order = wc_get_order( $last_order_id );
+		$token_ids  = $last_order->get_payment_tokens();
+		// since old payment must be the second to last saved payment...
+		if ( count( $token_ids ) < 2 ) {
+			return $old_payment_method_title;
+		}
+
+		$second_to_last_token_id = $token_ids[ count( $token_ids ) - 2 ];
+		$token                   = WC_Payment_Tokens::get( $second_to_last_token_id );
+		if ( ! $token || ! ( $token instanceof WC_Payment_Token_CC ) ) {
```
Comment (vbelolapotkov) [inline includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:423]: 🔍 nitpicking, I don't think brackets around instanceof check needed anymore.

File: tests/helpers/class-wc-helper-subscription.php (hunk 8 above)
Comment (vbelolapotkov) [reply tests/helpers/class-wc-helper-subscription.php]: You asked yourself a good question. If you take a look at other helper classes they have fake/mock implementations. Inheriting from production `WC_Order` is not correct approach.

File: tests/test-class-wc-payment-gateway-wcpay-subscriptions.php (hunk 10 above)
Comment (vbelolapotkov) [reply tests/test-class-wc-payment-gateway-wcpay-subscriptions.php]: sorry, GW = gateway.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 12 above)
[the remark this answers is not in the document]
Comment (shendy-a8c) [reply includes/class-wc-payment-gateway-wcpay.php]: Done.

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php (hunk 13 above)
[the remark this answers is not in the document]
Comment (shendy-a8c) [reply includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php]: Done. Decoupled the logic betweek old and new payment hook. Even though old and new payment method are different, still show last 4 digit.

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php (hunk 1 above)
Comment (shendy-a8c) [reply includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php]: Your comment here actually made me realized that I didn't think of the case where payment is changed on the subscriptions order. I tested payment change for the renewal order only. I will put more lengthy explanation below, also for knowledge transfer about this PR to @dmvrtx.

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php (hunk 4 above)
Comment (shendy-a8c) [reply includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php]: This is done per your suggestion, ie decoupling the hooks between old and new payment method, removing the check.

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php (hunk 5 above)
Comment (shendy-a8c) [reply includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php]: I agree it's hacky. I ended up using `Payment_Information` to improve.

File: tests/helpers/class-wc-helper-subscription.php (hunk 8 above)
Comment (shendy-a8c) [reply tests/helpers/class-wc-helper-subscription.php]: I have removed this part. I didn't finish the unit test part. Please help to finish the unit test, @dmvrtx. Thank you!

File: tests/test-class-wc-payment-gateway-wcpay-subscriptions.php (hunk 9 above)
Comment (shendy-a8c) [reply tests/test-class-wc-payment-gateway-wcpay-subscriptions.php]: > IMO it's better to create one test for each case.

I agree it's a good idea to breaking the unit tests into smaller parts. Please help to continue @dmvrtx .

> IIRC payment method is always saved for subs, no?

For failed renewal order, payment is saved in the subscriptions in `WC_Payment_Gateway_WCPay_Subscriptions_Compat::update_failing_payment_method()` which is called after the hook `woocommerce_subscription_note_old_payment_method_title` and `woocommerce_subscription_note_new_payment_method_title` hook, so the callback of those hooks should look at the renewal order instead of subscriptions order.

File: tests/test-class-wc-payment-gateway-wcpay-subscriptions.php (hunk 10 above)
Comment (shendy-a8c) [reply tests/test-class-wc-payment-gateway-wcpay-subscriptions.php]: Point taken. cross GW case has been removed.

**Comment by shendy-a8c** [comment]
@dmvrtx here are the key points of this PR.

Some background before we dive in:
- This PR depends on WooCommerce Subscriptions at least 3.0.12.
- Subscriptions order can have related orders. I call them renewal orders.

The goal is to show last 4 digit of credit card in the order note when there is payment change.
Payment change can happen in 2 flows:
1. Updating payment for failed payment of renewal order.
There are 3 cases to test for this flow.
- Case 1: After failed renewal order, pay with a saved payment.
- Case 2: After failed renewal order, pay with a new payment but do not choose to save the new payment.
- Case 3: After failed renewal order, pay with a new payment and choose to save the new payment.

Steps to test:
- Install WooCommerce Subscriptions at least version 3.0.12.
- Create free trial subs product.
- Purchase that subs product using credit card `4000000000000341` (can be saved but will fail when charged), so it will work when purchasing the subs order since no payment needed (it's a free trial) but for renewal, we will try to charge this card.
- Go to admin page > WooCommerce > Subscriptions > Open the newly purchased subs order > Choose `Process renewal` action.
- Confirm that renewal order will fail.
- From store, go to My account > Payment methods > add new payment method `4242424242424242`.
- My account > Subscriptions > open the subs order > go to the `Related orders` section and pay the failed renewal order.
- Depending on which case you want to test, you can pay with the saved `4242424242424242` payment, input a new payment without saving, or input a new payment and saving it.

<br />

2. Changing payment for subscriptions order.
There are 2 cases to test for this flow.
- Case 4: Change payment with another saved payment.
- Case 5: Change payment with a new payment.

Steps to test:
- Install WooCommerce Subscriptions at least version 3.0.12.
- Create subs product (does not have to be free trial but the same subs product from the first flow works too).
- Purchase that subs product using credit card `4242424242424242`.
- My account > Subscriptions > open the subs order > Change payment.
- Depending on which case you want to test, you can change payment with another saved payment or input a new payment.
Important note: since case 4 requires you to change payment to another saved payment and at the time of I write this, `trunk` won't let you do that unless [PR 1288](https://github.com/Automattic/woocommerce-payments/pull/1288) has been merged. You can still test by applying PR 1288 changes locally. That's what I did while testing.


About my approach.
IMO, the big chunk of this PR is about how to get the last 4 digit for each cases.
- To get the last 4 digit of the old payment
  - If we're at flow 1, old payment must be the 2nd to last payment tokens of the renewal order because the last payment token must be the successful / new payment method.
  - If we're at flow 2, same like above, but we're looking at the subs order instead of the renewal order.
- To get the last digit of the new payment
  - Utilize `Payment_Information` to check whether user chooses a saved payment, new payment and wants to save it, or new payment but does not want to save it.
Also please note that in case of flow 1, the `woocommerce_subscription_note_old_payment_method_title` and `woocommerce_subscription_note_new_payment_method_title` hooks are called before new payment is saved in subs order. Successful payment token of the renewal order is saved to the subs order at the later stage `WC_Payment_Gateway_WCPay_Subscriptions_Compat::update_failing_payment_method()` which is the callback of the hook `woocommerce_subscription_failing_payment_method_updated_woocommerce_payments`.

Hopefully my explanation is clear enough and it makes it easier for you to pick it up from here. What is not done:
- Robust testing.
- Unit tests.

File: tests/helpers/class-wc-helper-subscription.php (hunk 8 above)
Comment (dmvrtx) [reply tests/helpers/class-wc-helper-subscription.php]: Interestingly, I see the test cases creating `WC_Order` istances as needed and then working with `update_meta_data()`.

Comment (dmvrtx) [reply tests/helpers/class-wc-helper-subscription.php]: I found a mock class for `WC_Data` under WooCommerce repo. For now I copied it under the `tests/helpers` path but I wonder if there is a better way to re-use it.

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php (hunk 1 above)
Comment (dmvrtx) [reply includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php]: I reviewed the flows and indeed found one branch that was not properly tested. I updated the test suite to trigger that branch and everything looks well.

**Comment by dmvrtx** [comment]
@shendy-a8c, thanks a lot for a work on this issue 🙌. I only refactored the test suite to create a bite-sized test cases and ensured coverage of all code branches.

**Review by kalessil — APPROVED** [review]
LGTM, :shipit:
