### PR TITLE
Fix incorrect payment intent status check in cancel authorization API endpoint.

### LINKED ISSUE #7149: Cancel authorization API endpoint will return an error response on successful cancel.
### Describe the bug
When authorization is canceled, the cancel authorization API will return an error response. The reason for that lies in this [line](https://github.com/Automattic/woocommerce-payments/blob/bfb391c9557cfcaaf15016787f2e6f9ddf51496f/includes/admin/class-wc-rest-payments-orders-controller.php#L502) where incorrect payment intent status is used.

### To Reproduce

1. Make sure to have uncaptured authorization or payment intent.
2. Execute the following API endpoint:` payments/orders/ORDER_ID/cancel_authorization` and pass payment_intent_id in the body of request.
3. Error is shown, but the authorization is canceled.

### Actual behavior
A success response should be returned.

### PR DESCRIPTION
**Pull request by zmaglica**
Fixes #7149

#### Changes proposed in this Pull Request

The incorrect payment intent status was utilized, leading to an error response rather than a successful one.

#### Testing instructions

1. Make sure to have uncaptured authorization or payment intent.
2. Execute the following API endpoint: payments/orders/ORDER_ID/cancel_authorization and pass payment_intent_id in the body of request.
3. 200 status code is returned.
-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Review by naman03malhotra — COMMENTED** [review]
Change looks good @zmaglica, thanks for working on it and creating a separate issue. Do we have any tests associated with this change that you plan to add?

File: includes/admin/class-wc-rest-payments-orders-controller.php [hunk 1]
```diff
@@ -499,7 +499,7 @@ public function cancel_authorization( WP_REST_Request $request ) {
 
 			$result = $this->gateway->cancel_authorization( $order );
 
-			if ( Intent_Status::SUCCEEDED !== $result['status'] ) {
+			if ( Intent_Status::CANCELED !== $result['status'] ) {
```
Comment (naman03malhotra) [inline includes/admin/class-wc-rest-payments-orders-controller.php:502]: Changelog file is missing

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7150` or branch name `fix/7149-fix-cancel-authorization-flaky-error-response` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7149-fix-cancel-authorization-flaky-error-response) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: cd7e34e83c2847787edd86de1c3ed9c27d69f9d4
- Build time: 2023-09-07 15:05:43 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/admin/class-wc-rest-payments-orders-controller.php (hunk 1 above)
Comment (zmaglica) [reply includes/admin/class-wc-rest-payments-orders-controller.php:502]: Added here: https://github.com/Automattic/woocommerce-payments/pull/7150/commits/3b2f6e0da41695585f33ae8cd715699e7969eaa9

**Comment by zmaglica** [comment]
> Change looks good @zmaglica, thanks for working on it and creating a separate issue. Do we have any tests associated with this change that you plan to add?

Added here: https://github.com/Automattic/woocommerce-payments/pull/7150/commits/cd7e34e83c2847787edd86de1c3ed9c27d69f9d4

**Review by htdat — APPROVED** [review]
Thanks for working on this @zmaglica! Pre-approve this PR. 

@eduardoumpierre  - it would be great if you can test this issue in your site too to confirm it's working as expected. I am looking further in the code using this endpoint `cancel_authorization`, it seems it's used together with the Fraud check to display the `CancelAuthorizationButton` component in the transaction detail page. 
https://github.com/Automattic/woocommerce-payments/blob/83f6905673a9891821bac870367a46560a7ebdc3/client/payment-details/summary/index.tsx#L295-L297

**Review by eduardoumpierre — APPROVED** [review]
I followed the testing instructions and it worked as expected – it fixed the bad response. The change makes sense and it's covered by tests.

Thanks for working on this @zmaglica! LGTM :shipit: 

@htdat Regarding the `CancelAuthorizationButton` logic, it is currently inaccessible for the merchants, as the review feature was removed from FRT phase 1. We can test it by forcing the application to understand the order as it is held for review, which can be done by applying the diff below.

```diff
diff --git a/client/utils/charge/index.ts b/client/utils/charge/index.ts
index 2690279e2..7c3e7ff7d 100755
--- a/client/utils/charge/index.ts
+++ b/client/utils/charge/index.ts
@@ -65,6 +65,8 @@ export const isOnHoldByFraudTools = (
 	charge?: Charge,
 	paymentIntent?: PaymentIntent
 ): boolean => {
+	return true;
+
 	const fraudMetaBoxType = getFraudMetaBoxType( charge, paymentIntent );
 
 	if ( ! fraudMetaBoxType ) {
```
