### PR TITLE
Trim whitespace on the statement descriptor

### LINKED ISSUE #957: Statement descriptor validation does not trim the whitespace
To reproduce:
* Try to update your statement to something like `     abcd     ` - note the leading and trailing whitespace
* Get an error `Failed to update Statement descriptor. Error: The statement descriptor must be at least 5 characters. ...` rather than a nicely formatted message

### PR DESCRIPTION
**Pull request by marcinbot**
Fixes #957 

#### Changes proposed in this Pull Request

* Trim the whitespace and add unit tests

#### Testing instructions

* In the settings page:
* Try updating the statement descriptor to `aaa` prefixed or suffixed with spaces, so the overall length is between 5 and 22
  * You should get an error notice beginning with `Customer bank statement is invalid. Statement should be between 5 and 22 characters long...`
  * The descriptor shouldn't save
* Try updating the statement descriptor to `aaaaa` prefixed or suffixed with spaces as long as the length is less than 5
  * The descriptor should save, but the whitespace should be removed

cc @kalessil 

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)

### CODE REVIEW

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -906,6 +906,7 @@ private function update_statement_descriptor( $statement_descriptor ) {
 	public function validate_account_statement_descriptor_field( $key, $value ) {
 		// Since the value is escaped, and we are saving in a place that does not require escaping, apply stripslashes.
 		$value = stripslashes( $value );
+		$value = trim( $value );
```
Comment (kalessil) [inline includes/class-wc-payment-gateway-wcpay.php:909]: I personally prefer to use one-liners in similar cases: it's simple core functions, so the meaning is straightforward and we have less code to get thru.

File: tests/test-class-wc-payment-gateway-wcpay.php [hunk 2]
```diff
@@ -579,6 +580,7 @@ public function account_statement_descriptor_validation_provider() {
 			'no_gt'          => [ false, 'WCPay>dev' ],
 			'req_latin'      => [ false, 'дескриптор' ],
 			'req_letter'     => [ false, '123456' ],
+			'trim_too_short' => [ false, '  aaa    ' ],
```
Comment (kalessil) [inline tests/test-class-wc-payment-gateway-wcpay.php:583]: :+1:

**Review by kalessil — APPROVED** [review]

File: includes/class-wc-payment-gateway-wcpay.php (hunk 1 above)
Comment (marcinbot) [reply includes/class-wc-payment-gateway-wcpay.php]: Makes sense. Usually we try to avoid "clever code", but in this case it doesn't make much difference, as you said. Changed in fff3a1c
