### PR TITLE
Fix losing cart contents during the login at checkout

### LINKED ISSUE #7992: Cart contents lost on login at checkout - plugin incompatibility
### Describe the bug
When other plugins are active which make requests on behalf of the shopper (i.e. using their cookies), cart contents can be lost when logging in at checkout.

### To Reproduce
Add the following snippet to the bottom of `woocommerce-payments.php`:
```
function do_api_call_w_cookies_on_wp_login() {
	$url = rest_url();
	
	$args = array(
		'cookies'   => $_COOKIE,
		'blocking'  => false,
		'timeout'   => 0.01,
		'sslverify' => apply_filters( 'https_local_ssl_verify', false ),
	);

	$result = wp_remote_get( $url, $args );
}

add_action( 'wp_login',  'do_api_call_w_cookies_on_wp_login' );
```

This simulates another plugin making a request, with the session cookies, during login.

1. Ensure "Allow customers to log into an existing account during checkout" is enabled at WooCommerce > Settings > Accounts & Privacy
2. Ensure you're not logged into the store (or use a private browser session)
3. Add an item to your cart and go to the checkout page
4. Use the `Returning customer? Click here to login` option and login
5. The cart will now be empty

### Actual behavior
Logging in at checkout should not clear the cart.

### Expected behavior
It should be possible to login and checkout with whatever products were in the cart.

### Additional context
The issue appears to have been introduced by this PR (https://github.com/Automattic/woocommerce-payments/pull/819), which handles the use case of creating a new account during a 3DS checkout. The specific line causing us a problem in this particular case is [here](https://github.com/Automattic/woocommerce-payments/blob/a88fb8725e13b60ca30bb3e5ad975bb8083adfa0/includes/class-wc-payment-gateway-wcpay.php#L523).

A possible fix might be to try and be more specific and limit the manipulation of the cookies to only requests attempting to do account creation and a 3DS checkout? At the moment we run the fix in all cases.

For extra context, this issue was discovered as part of an investigation into a Jetpack Sync issue, but since it can be reproduced in isolation, and it could theoretically be an issue for other plugins, it makes sense to fix it in WooPayments (p9dueE-7zI-p2).

### PR DESCRIPTION
**Pull request by htdat**
Fixes #7992

### Changes proposed in this Pull Request

Narrow down to specific conditions when the `WC_Payment_Gateway_WCPay::set_cookie_on_current_request` filter is applied. 

- During a checkout process request. `WOOCOMMERCE_CHECKOUT` is an indicator for this request, which is supported in both classic and block checkouts. 
- A new account is created during this process. Ensure that action `woocommerce_created_customer` is called out at least one time. This is also supported in both classic and block checkouts. This check also supports multi cases of creating a new account during the checkout process request: optional or automatic account creation (for a checkout including a subscription product). 

Why not using the condition of 3DS? 

- This can be only possible to know after sending the request of creating payment intent. It's [somewhere here in the code](https://github.com/Automattic/woocommerce-payments/blob/c9078890fc0f2394d6c097c90bad2fb5717fe3d1/includes/class-wc-payment-gateway-wcpay.php#L1741-L1764). We can inject a filter around this code, but it will complicate the code a lot.
- Another important factor is that the process of creating a new account is run before the payment process. Therefore, until we know a payment requiring 3DS, it's too late. 

#### Testing instructions

- Ensure to add the snippet mentioned in this issue: https://github.com/Automattic/woocommerce-payments/issues/7992 . It's possible to use  plugin Code Snippet for this purpose, otherwise, just add this snippet to the bottom of the main file `woocommerce-payments.php`.
- Test 1: follow `To Reproduce` https://github.com/Automattic/woocommerce-payments/issues/7992
- Expectation test 1: the cart is persisted. 
- Test 2: follow manual instruction testings in https://github.com/Automattic/woocommerce-payments/pull/819
- Expectation test 2: 3DS payment is run through without any issue. 

Ideally, these flows would be tested for both types of checkout: block and classic.

*

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8084` or branch name `fix/7992-lost-cart-content` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7992-lost-cart-content) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 508e551c67d7662ce9ff6f0b842f63e430c11150
- Build time: 2024-01-30 02:54:16 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by htdat** [comment]
👋 Hi all, I've added multiple people to reviewing and testing this PR as it can help solve multiple relevant issues:

- https://github.com/woocommerce/woocommerce/issues/34464
- https://github.com/Automattic/woocommerce-payments/issues/5491 

In case you're not aware, this comment https://github.com/Automattic/woocommerce-payments/pull/8084#issuecomment-1908223319 explains how to test this PR without a dev environment.

**Comment by pierorocca** [comment]
This will be a terrific fix. I could see how this would be super frustrating. Losing your cart contents is the worst. :)

**Review by naman03malhotra — COMMENTED** [review]
I tried replicating the bug with the mentioned instructions. I added the snippet at the bottom of the `woocommerce-payments.php` file

But somehow after login in, my cart remains intact, am I missing something?
https://github.com/Automattic/woocommerce-payments/assets/15019298/3bb2a272-078a-4ec4-9818-aeee08e3ba05

**Comment by htdat** [comment]
@naman03malhotra - you may try clearing your cart when you logged in an account. And then, logging out, add a new product, try log in again. 

My best guess is that your logged-in user had the same product before you logged in.

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -663,11 +663,14 @@ private function get_request_payment_data( \WP_REST_Request $request ) {
 
 	/**
 	 * Proceed with current request using new login session (to ensure consistent nonce).
+	 * Only apply during the checkout process with the account creation.
 	 *
 	 * @param string $cookie New cookie value.
 	 */
 	public function set_cookie_on_current_request( $cookie ) {
-		$_COOKIE[ LOGGED_IN_COOKIE ] = $cookie;
+		if ( defined( 'WOOCOMMERCE_CHECKOUT' ) && WOOCOMMERCE_CHECKOUT && did_action( 'woocommerce_created_customer' ) > 0 ) {
```
Comment (naman03malhotra) [inline includes/class-wc-payment-gateway-wcpay.php:671]: >did_action( 'woocommerce_created_customer' )

Does that mean it will still happen for users who will create a new account?

**Review by naman03malhotra — COMMENTED** [review]
I am facing another issue while testing probably unrelated to this:

New account I am creating on WC, it shows invalid credentials while login in


https://github.com/Automattic/woocommerce-payments/assets/15019298/32f9772b-41cf-469c-91a6-a1af7883dbf6

**Review by KarlisJ — APPROVED** [review]
Managed to reproduce the issue and asserted that testing instructions passes for both blocks and classic checkout.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 1 above)
Comment (htdat) [reply includes/class-wc-payment-gateway-wcpay.php:671]: No, this `did_action` only matters when shoppers submit the checkout request with the option of creating a new account. The flow having issue, as mentioned in #7992, is with the log-in flow for an existing user.

**Comment by htdat** [comment]
> Managed to reproduce the issue and asserted that testing instructions passes for both blocks and classic checkout.

Thanks for the review, @KarlisJ! 

> I tried replicating the bug with the mentioned instructions. I added the snippet at the bottom of the `woocommerce-payments.php` file

@naman03malhotra - The issue is with the localhost. I debugged a bit but could not figure out exactly why. It's just that the `wp_get_remote` request in the snippet returns invalid data. I would suggest using a JN site instead. Sorry about that. I myself tested on a Pressable site, and could not replicate the issue on my Docker install.

**Review by RadoslavGeorgiev — APPROVED** [review]
Works like a charm! :shipit: 

Initially, I suggested this approach (limiting the effect of `set_cookie_on_current_request` to the checkout) to narrow down the situations when it would create a conflict. While testing the PR, I realize that the cart would never be lost this way! 🎉

**Comment by htdat** [comment]
ℹ️ FYI. Current E2E test failures for:
- WC - latest | subscriptions - shopper
- WC - latest | wcpay - shopper

These failures are happening with other PRs too. They seem relevant with Woo core 8.5.2 released last Friday ([changeset on WPorg](https://plugins.trac.wordpress.org/changeset/3026961/). Checking p1706588825046929-slack-CGGCLBN58

File: includes/class-wc-payment-gateway-wcpay.php (hunk 1 above)
Comment (naman03malhotra) [reply includes/class-wc-payment-gateway-wcpay.php:671]: >The flow having issue, as mentioned in https://github.com/Automattic/woocommerce-payments/issues/7992, is with the log-in flow for an existing user.

Can we double check, if that's the case? And log a separate issue for that flow?

Comment (RadoslavGeorgiev) [reply includes/class-wc-payment-gateway-wcpay.php:671]: @naman03malhotra there is no need for a separate issue, this PR handles both flows.

Comment (naman03malhotra) [reply includes/class-wc-payment-gateway-wcpay.php:671]: I mean, does it also happen when a shopper creates a new account while checkout? So I was talking about that flow.

Comment (RadoslavGeorgiev) [reply includes/class-wc-payment-gateway-wcpay.php:671]: Yes, the main purpose here is to only replace the cookie when a shopper chooses to create an account during checkout, rather than every time one logs in or registers. This way, the cart will remain untouched.

During the checkout registration, the cart contents are already moved into the order, so losing them is not an issue.

Comment (htdat) [reply includes/class-wc-payment-gateway-wcpay.php:671]: > During the checkout registration, the cart contents are already moved into the order, so losing them is not an issue.

Thanks @RadoslavGeorgiev for this answer.

**Review by csmcneill — COMMENTED** [review]
I tested this out on my AT site via Jetpack Beta. It works great!

1. Accessed the site as a guest.
2. Added products to my cart.
3. Navigated to the checkout page.
4. Logged in — and the cart persisted after log in.
5. Removed products from the cart.
6. Logged out.
7. Deactivated Jetpack Beta.
8. Repeated steps 1–3.
9. Logged in — and the cart was empty as this PR was not in use on my site.

Great job. Very excited for this fix!

**Comment by pierorocca** [comment]
I don't have a dev site to test this yet. Would be great to test this with WooPay involved:

1. Shop on store and add product to cart
2. Click Woopay button and initiate a WooPay checkout
3. Click "checkout as guest"
4. Login and observe cart contents are not cleared
5. Check out with WooPay again and observe cart contents are as expected

**Comment by htdat** [comment]
@pierorocca - I tried to test the flow suggested by you but I got some blockers: 

- If I don't log in to a shopper account in my merchant testing site, I can not see the WooPay button as mentioned in your step 2. 
- If I have already logged in, this step conflicts with your step 4.

Anyway, you can use `Jetpack Beta` to test this feature as mentioned here https://github.com/Automattic/woocommerce-payments/pull/8084#issuecomment-1908223319

**Comment by bborman22** [comment]
Just wanted to confirm I was able to test the flow with WooPay. 

> If I don't log in to a shopper account in my merchant testing site, I can not see the WooPay button as mentioned in your step 2.

@htdat When you experienced this it may have been with a subscription product in the cart. With subscription products, WooPay is only offered if the shopper is already logged into the merchant store.

I tested the flows with WooPay on a simple product, digital product, and subscription product without issue. For simple and digital I followed @pierorocca's steps. With the subscription product the flow was:
- Add subscription to cart
- Confirm no WooPay at cart or checkout
- Login to merchant store from checkout page
- See WooPay button now
- Able to checkout using WooPay

I also tested the other flows mentioned here in blocks and shortcode checkout without issue after being able to replicate the issue on `develop` since I was already in here. LGTM!
