### PR TITLE
Disable Stripe Billing Subscriptions while in Subscriptions staging mode

### LINKED ISSUE #6316: Subscription status changes and other features on staging sites impact the live site
### Describe the bug

When a store is in [staging mode](https://woocommerce.com/document/subscriptions-handles-staging-sites/), subscription status changes are sent to WC Pay servers. This typically results in:

- the subscription being put on-hold during the renewal process on the staging site. 
    - this is because the subscription is manual on the staging site so a renewal order is created and the subscription goes on-hold during the renewal process.
- as a result the Stripe billing subscription is put on hold (paused).
- the live site still thinks the subscription is active and so awaits renewal order webhooks, but they never get sent. 

> **Warning**
> **This is the most likely cause of inexplicably paused subscriptions**

What's more, other Stripe billing related requests are also sent from staging sites which may have some impact the live site. For example, Stripe billing product related requests. Product updates and deletes on a staging site propagate to the WC Pay live Stripe account and so could impact the live site.

> **Note**
> Product price changes don't have any impact because subscription prices are taken from the order and subscription at the time of purchase.

### To Reproduce

1. Purchase a subscription using WC Pay subscriptions (Stripe billing)
2. Mimic your site being in staging mode: 
   - alter your `wc_subscriptions_siteurl` option. eg add an extra character so it no longer matches your site URL.
3. Go to **Tools > Scheduled Actions**
4. Search for the subscription ID. 
5. Run the scheduled payment action for the subscription
6. Go to the edit subscription screen for the subscription you purchased note that the subscription is on-hold and there's a pending renewal order.
7. Find the subscription in your Stripe dashboard and notice the it is paused. 

image

### Actual behavior

Stripe billing requests related to WCPay 

### Expected behavior

Staging sites shouldn't impact live data like this. It's common for agencies, or developers to set up duplicate sites for their customers to enable them to test things on. For a staging site to be communicating with the live WCPay account and for it to impact the live account is not intended. 

We need to work out what the experience is for staging sites. Is stripe billing functionality completely disabled, do we just act as if these stripe billing subscriptions are tokenised wc pay subscriptions?

In the end, staging sites shouldn't be communicating with the live site in any way.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #6316

#### Changes proposed in this Pull Request

When a site is in staging mode, we don't want subscription changes on that staging (dev) site to communicate with the WC Pay server and potentially impact live account data.

Prior to this PR, it was possible that a duplicate site could send subscription-related requests to the WC Pay server, for those requests to be actioned, and then for the live store to be impacted by those changes. 

The most common outcome was as follows:

1. Subscriptions on the staging site are treated as manual due to the duplicate site logic which turns all subscriptions on staging sites into manual subscriptions. 
2. When the scheduled actions for those subscriptions would run, the subscription would go on-hold. 
3. The WC Pay Subscriptions code would hook into this status transition and communicate with Stripe that this subscription was put on-hold. 
4. Stripe would pause the subscription and all future renewals would essentially halt. 

This PR addresses this by:

1. Making sure that we don't hook onto any subscription-status change actions on staging sites. This will prevent subscriptions which change status on duplicate sites from sending corresponding requests to server, essentially acting on behalf of the live site. 
2. All subscription-product related actions have also been disabled. Prior to this, if an admin changed the product name or description, or deleted the product, this would impact the products at Stripe which are used by the live site.  
3. All subscription-related webhooks are also disabled. If a staging site somehow receives a subscription `invoice.upcoming`, `invoice.paid`, or `invoice.failed` webhook, it won't process it. Staging sites should not receive webhooks (they should be forwarded to the live site URL), however this is necessary because our webhook handling can lead to responses. ie we can pause subscriptions at Stripe if we process a `invoice.upcoming` and if the subscription in WooCommerce is cancelled. 
4. Crucially, I've updated the `is_wcpay_subscription()` function to ensure that it returns `false` on staging sites. A lot of our WCPay Subscription logic is built on this check. If we make sure that wcpay subscriptions aren't treated as wcpay subscriptions on staging sites, they should behave like tokenised wc pay subscriptions and avoid a lot of Stripe billing interactions. 
5. Updating `WC_Payments_Invoice_Service` so it won't hook onto any callback and fire off server requests based on order status changes. If an unpaid subscription-related order was marked as processing or complete on a staging site, that would have fired off a request to server to mark the invoice as paid, and activate the subscription. This shouldn't occur on staging sites. 

- I've left the `WC_Payments_Subscription_Change_Payment_Method_Handler` unchanged bar a minor change. This class doesn't do anything except change urls, button text and display a notice when the user clicks the change payment method button. As long as we don't act on the actual changing of the payment method, we should be fine. This will need to tested. 

#### Testing instructions

- Testing the [wcpay subscription critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) should be done. 
- Every WCPay Subscription flow should be tested as if the site is live mode.
- Every flow should then be tested in staging mode. 
- The flows to test are: 
   1. **Products**
      - Create a subscription product.
      - Delete a product
      - Update a product's name.  
   3. **Subscriptions**
       - Purchase a subscription.
       - Suspend a subscription
       - Activate a subscription. 
       - Cancel a subscription.
       - Change a subscription payment method. 
   4. **Renewals**
       - Process successful renewals. 
       - Fail renewals
       - Pay for failed renewals.
       - Run subscription scheduled actions. 
           - On staging this will create pending renewal orders, as long as this doesn't impact the subscription in the Stripe dashboard, this is expected. 
           - While in live mode, running the scheduled action will do nothing. 

**Between each test check that no changes have propagated to the Stripe account while in staging mode. Note that some flows might even be disabled on the staging environment.**

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6344` or branch name `disable-stripe-billing-while-staging` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=disable-stripe-billing-while-staging) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: db05024effb3834b3520d060184fe5316c43ce9d
- Build time: 2023-06-02 06:30:52 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/subscriptions/class-wc-payments-subscriptions-event-handler.php [hunk 1]
```diff
@@ -55,10 +55,22 @@ public function __construct( WC_Payments_Invoice_Service $invoice_service, WC_Pa
 	public function handle_invoice_upcoming( array $body ) {
 		$event_object          = $this->get_event_property( $body, [ 'data', 'object' ] );
 		$wcpay_subscription_id = $this->get_event_property( $event_object, 'subscription' );
-		$wcpay_customer_id     = $this->get_event_property( $event_object, 'customer' );
```
Comment (james-allan) [inline includes/subscriptions/class-wc-payments-subscriptions-event-handler.php:58]: you'll notice that this `$wcpay_customer_id` has been removed. It wasn't being used.

File: includes/subscriptions/class-wc-payments-subscriptions-event-handler.php [hunk 2]
```diff
@@ -175,12 +200,25 @@ public function handle_invoice_payment_failed( array $body ) {
...
+			$this->log_skipped_webhook_due_to_staging( 'invoice.payment_failed', $wcpay_subscription_id );
+			return;
+		}
+
+		$wcpay_invoice_id = $this->get_event_property( $event_object, 'id' );
+		$attempts         = (int) $this->get_event_property( $event_object, 'attempt_count' );
+		$subscription     = WC_Payments_Subscription_Service::get_subscription_from_wcpay_subscription_id( $wcpay_subscription_id );
 
 		if ( ! $subscription ) {
-			throw new Invalid_Webhook_Data_Exception( __( 'Cannot find subscription for the incoming "invoice.upcoming" event.', 'woocommerce-payments' ) );
```
Comment (james-allan) [inline includes/subscriptions/class-wc-payments-subscriptions-event-handler.php:183]: This was a copy paste fail in the existing code. This function handles `invoice.payment_failed` events, not `invoice.upcoming`.

**Comment by mattallan** [comment]
I've performed code review and I'm confident in the changes coming in this PR.
Here are the tests I ran:

### Live Mode

- [x] Create a subscription product
- [x] Update subscription object
- [x] Delete subscription product - confirmed archived in Stripe
- [x] Untrash subscription product - confirmed unarchived in Stripe
- [x] Purchase subscription - Confirm created in Stripe
- [x] Change payment method
- [x] Suspend subscription - Confirm paused in Stripe
- [x] Reactivate subscription - Confirm active in Stripe
- [x] Cancel a subscription - Confirm updated in Stripe
- [x] Process a subscription renewal with billing clocks
- [x] Process a failed renewal with billing clocks
- [x] Pay for the failed renewal

### Staging Mode

- [x] Creating a subscription product does not created it in Stripe
- [x] Updating an existing wcpay product doesn't update it in Stripe
- [x] Deleting an existing subscription product does not archive it in Stripe
- [x] Untrashing a subscription product has no effect
- [x] New Subscription
  - [x] Confirm no subscription is created in Stripe
  - [x] Confirm cancelling, suspending does nothing
  - [x] Process a manual renewal
  - [x] Pay for the manual renewal
- [x] Existing WCPay subscriptions created in Live Mode
  - [x] Suspending subscription does not suspend in Stripe
  - [x] Cancelling subscription does not cancel in Stripe

**Comment by james-allan** [comment]
I ran similar tests for testing each core Stripe Billing flow in live mode to confirm this doesn't have any impact on live sites, and confirmed that subscription actions after a site is switched into staging mode has no impact on the subscription record in Stripe.

## Flows
### Live mode 🟢 
   1. **Products**
      - [x] Create a subscription product
      - [x] Trash a product
      - [x] Update a product's name.
      - [x] Untrash product
   3. **Subscriptions**
       - [x] Purchase a subscription.
       - [x] Suspend a subscription
       - [x] Activate a subscription. 
       - [x] Cancel a subscription.
       - [x] Change a subscription payment method. 
   4. **Renewals**
       - [x] Process successful renewals
       - [x] Fail renewals
       - [x] Pay for failed renewals.
       - [x] Run subscription scheduled actions. 
           - On staging this will create pending renewal orders, as long as this doesn't impact the subscription in the Stripe dashboard, this is expected. 
           - While in live mode, running the scheduled action will do nothing. 

After running these tests while in live mode I switched the site into staging mode

### Staging mode 🔴 
   1. **Products**
      - [x] Create a subscription product
          - 👍 _No product created_
      - [x] Trash a product
          - 👍 _not archived_ 
      - [x] Update a product's name.
          - 👍 editing a product that was previously created while in live mode had no impact on the product in the Stripe dashboard.
      - [x] Untrash product
          - Did nothing given the product wasn't trashed to begin with.
   3. **Subscriptions**
       - [x] Purchase a subscription.
          - Resulting subscription is essentially a manual subscription with WCPay as the payment method. No subscription is created in Stripe.  
       - [x] Suspend a previously created Stripe billing subscription
       - [x] Activate a subscription. 
           - No change in Stripe
       - [x] Cancel a subscription.
           - No change in Stripe
       - [x] Change a subscription payment method. 
           - 👍  No change
   4. **Renewals**
       - [x] Run subscription scheduled actions. 
           - 👍 While in staging mode this will create pending renewal orders, it hasn't suspended the subscription in the Stripe dashboard, this is expected.

File: tests/unit/subscriptions/test-class-wc-payments-subscription-change-payment-method.php [hunk 3]
```diff
@@ -46,6 +46,7 @@ public function test_update_subscription_change_payment_button() {
 		// The update_subscription_change_payment_button function attempts to call WC_Subscription->get_checkout_payment_url(). To avoid errors mock that function's return.
 		$mock_subscription->checkout_payment_url = 'example.com';
 		$mock_subscription->update_meta_data( WC_Payments_Subscription_Service::SUBSCRIPTION_ID_META_KEY, 'sub_test123' );
+		$mock_subscription->set_payment_method( WC_Payment_Gateway_WCPay::GATEWAY_ID );
```
Comment (james-allan) [inline tests/unit/subscriptions/test-class-wc-payments-subscription-change-payment-method.php:49]: Because I changed `WC_Payments_Subscription_Change_Payment_Method_Handler::does_subscription_need_payment_updated()` to use `WC_Payments_Subscription_Service::is_wcpay_subscription( $subscription )` I had to make sure I set the subscription's payment method to WC Payments. 


Previously the logic just checked if the stripe billing`sub_` ID meta was set, whereas `is_wcpay_subscription()` also checks the the subscription's payment method. 

To me this tightens the logic in a way that makes more sense. We shouldn't be overriding these change payment URLs if the subscription's payment method is no longer wcpay.

**Review by mattallan — APPROVED** [review]

**Review by mattallan — APPROVED** [review]

**Comment by haszari** [comment]
🙌🏻
