### PR TITLE
In-Person Payments: fix an error in store location endpoint when blog name is empty

### LINKED ISSUE #4305: Terminal location creation fails if site title missing
### Describe the bug

The `payments/terminal/locations` endpoint uses the site title for the `display_name` property for the location. If the site has no  title, attempting to get the store terminal location fails with the following error from Stripe:

> Error: You passed an empty string for 'display_name'. We assume empty values are an attempt to unset a parameter; however 'display_name' cannot be unset. You should remove 'display_name' from your request or supply a non-empty value.

We should instead fallback to a non-empty identifier (e.g. the site URL).

### To Reproduce

- In **Settings > General**, set the **Site Title** field to empty and then **Save Changes**.
- Make a `GET` request to `/wp-json/wc/v3/payments/terminal/locations/store`.
- See the above error.

### Actual behavior

API returns an error.

### Expected behavior

Terminal location is returned.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

pdfdoF-QQ-p2

### PR DESCRIPTION
**Pull request by kalessil**
Fixes #4305 

#### Changes proposed in this Pull Request

Re-work location name generation towards a more reliable approach.

#### Testing instructions

* Change blog name in WordPress settings
* Follow test instructions from https://github.com/Automattic/woocommerce-payments/pull/2830

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: includes/admin/class-wc-rest-payments-terminal-locations-controller.php [hunk 1]
```diff
@@ -144,18 +144,19 @@ public function get_store_location( $request ) {
 
 		try {
 			// Check the existing locations to see if one of them matches the store.
-			$name = get_bloginfo();
+			// Originally we picked `get_bloginfo` for generating names, but later switched to `site_url` for max immutability.
+			$possible_names = [ get_bloginfo(), site_url() ];
```
Comment (kidinov) [inline includes/admin/class-wc-rest-payments-terminal-locations-controller.php:148]: if `site_url()` returns something like `https://www.example.com`, then maybe for better readability for the merchants to make it `example.com`? Also, can it be that stripe doesn't allow special symbols here?

Otherwise logic looks good to me! Thank you 🙏

Comment (kalessil) [reply includes/admin/class-wc-rest-payments-terminal-locations-controller.php]: Good proposal and even less mutability! Addressed in cde996b82a24d9f387bc603667ead6074a659e7a.

**Review by dpaun1985 — APPROVED** [review]
LGTM!
