### PR TITLE
Filtering billing details from order based on checkout fields

### LINKED ISSUE #8352: Subscriptions without some billing details will not renew after updating to 7.3.0
### Describe the bug

If a merchant removes some billing fields (e.g., billing address, country) from the checkout page, the subscriptions would be successfully created and renew without issue prior to 7.3.0.

However, after updating to 7.3.0, these same subscription renewals will fail, and the order notes indicate the following error:

```
Error: You passed an empty string for 'billing_details[address][country]'. We assume empty values are an attempt to unset a parameter; however 'billing_details[address][country]' cannot be unset. You should remove 'billing_details[address][country]' from your request or supply a non-empty value.
```

### To Reproduce

1. Create a simple subscription product
2. Install WooPayments 7.1.0 (7.2.0 may work here, but I didn't test this)
4. Install [Checkout Field Editor](https://woo.com/products/woocommerce-checkout-field-editor/?aff=10486&cid=1131038)
5. Remove all billing fields except ZIP code, email, and first/last name
6. Purchase a subscription via shortcode checkout (CFE is not compatible with the checkout block)
7. Update to WooPayments 7.3.0
8. Process a renewal by running the `woocommerce_scheduled_subscription_payment` hook in the action scheduler.
9. The renewal will fail

### Actual behavior

A renewal fails if there is incomplete billing information provided. However, this only occurs with 7.3.0 active, so it might be related to https://github.com/Automattic/woocommerce-payments/pull/8226

### Screenshots

CleanShot 2024-03-07 at 18 39 48

### Expected behavior

Since subscriptions renewing with incomplete billing information worked before 7.3.0, maybe it should work in 7.3.0 and beyond — even though [we advise against removing core billing fields](https://arc.net/l/quote/ewtwsbww).

### Additional context

p1709858821739469-slack-C7U3Y3VMY
7855095-zen

### PR DESCRIPTION
**Pull request by gpressutto5**
Fixes #8352

#### Changes proposed in this Pull Request

In #8226 we started updating the billing address every time a saved payment method was used.
Later, in #8257, we stopped filtering the billing fields we send to prevent an issue where fields that were previously set would not update to empty.
This PR updates `get_billing_details_from_order` to return only the fields present in checkout to prevent sending required fields, such as Country, as empty.

#### Testing instructions

1. Create a simple subscription product
3. Install [Checkout Field Editor](https://woo.com/products/woocommerce-checkout-field-editor/?aff=10486&cid=1131038)
4. Remove all billing fields except ZIP code, email, and first/last name
5. Purchase a subscription via shortcode checkout (CFE is not compatible with the checkout block)
7. Process a renewal by running the woocommerce_scheduled_subscription_payment hook in the action scheduler.
8. The renewal should work

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8459` or branch name `fix-subscription-billing-fields` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix-subscription-billing-fields) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 345f63fca89a49e84c6642cdbca38d3e7d9a47a1
- Build time: 2024-03-26 00:46:55 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payments-utils.php [hunk 1]
```diff
@@ -338,26 +338,39 @@ public static function map_search_orders_to_charge_ids( $search ) {
...
-				'country'     => $order->get_billing_country(),
-				'line1'       => $order->get_billing_address_1(),
-				'line2'       => $order->get_billing_address_2(),
-				'postal_code' => $order->get_billing_postcode(),
-				'state'       => $order->get_billing_state(),
-			],
-			'email'   => $order->get_billing_email(),
-			'name'    => trim( $order->get_formatted_billing_full_name() ),
-			'phone'   => $order->get_billing_phone(),
+		$billing_fields       = array_keys( wc()->checkout()->get_checkout_fields( 'billing' ) );
```
Comment (FangedParakeet) [inline includes/class-wc-payments-utils.php]:
```suggestion
		$billing_fields       = array_keys( WC()->checkout()->get_checkout_fields( 'billing' ) );
```
I know that PHP will treat them the same, but thoughts about using the capitalised version of this global function, as it's named in WooCommerce, just for consistency with other places in the codebase where this function is used?

File: includes/class-wc-payments-utils.php [hunk 2]
```diff
@@ -338,26 +338,39 @@ public static function map_search_orders_to_charge_ids( $search ) {
...
+			} elseif ( isset( $field_to_key[ $field ] ) ) {
+				$billing_details[ $field_to_key[ $field ] ] = $order->{"get_{$field}"}();
+			}
+		}
+
+		if ( in_array( 'billing_first_name', $billing_fields, true ) && in_array( 'billing_last_name', $billing_fields, true ) ) {
+			$billing_details['name'] = trim( $order->get_formatted_billing_full_name() );
+		}
 
 		return array_filter( $billing_details );
```
Comment (FangedParakeet) [inline includes/class-wc-payments-utils.php]:
```suggestion
		foreach ( $billing_fields as $field ) {
			if ( isset( $address_field_to_key[ $field ] ) ) {
				$billing_details['address'][ $address_field_to_key[ $field ] ] = $order->{"get_{$field}"}();
			} elseif ( isset( $field_to_key[ $field ] ) ) {
				$billing_details[ $field_to_key[ $field ] ] = $order->{"get_{$field}"}();
			}
		}

		if ( in_array( 'billing_first_name', $billing_fields, true ) && in_array( 'billing_last_name', $billing_fields, true ) ) {
			$billing_details['name'] = trim( $order->get_formatted_billing_full_name() );
		}

		return $billing_details;
```
I'm just considering the implementation here and am interested to hear your thoughts. It's a minor point, but do we still need to call `array_filter` on the result here? Can the `address`, `billing_email`, `billing_phone`, or `name` properties ever be empty if the keys are present in the resulting `$billing_details` array? I'm not sure how much power third-party plugins have to remove any and all required fields or to make required fields no longer required, so perhaps my suggestion is baseless. It's a mostly insignificant optimisation, but just wondering if you'd be able to assuage my doubts here.

**Review by FangedParakeet — COMMENTED** [review]
Changes look decent so far, though I still need to test the functionality a little more thoroughly: just leaving a few minor musings that I had in the meantime, in case they might be worthy of mention.

File: includes/class-wc-payments-utils.php (hunk 2 above)
Comment (gpressutto5) [reply includes/class-wc-payments-utils.php]: You're right, I missed that!

**Review by FangedParakeet — APPROVED** [review]
Thanks for the little changes! Tested subscriptions with checkout fields removed and the renewals processed successfully. Also, tested a few regular checkout flows--regular checkouts, saved payment methods, pay for order--just to ensure no breaking changes might be lurking in here, but everything appears to be working as expected.

LGTM! 🚢
