### PR TITLE
Use the filter param in server-side disputes CSV export

### LINKED ISSUE #9987: Server-side CSV export in Disputes does not use filter field
### Describe the bug
When there are > 25 disputes in `Needs Response` status and the Disputes page is loaded with "Needs Response" filter, the CSV export  contains all the disputes and not just the ones in Needs Response status. 
i.e. Filtering does not work for server side async export is used for Disputes

### To Reproduce
- Ensure you have >25 disputes in `Needs Response` status and few other disputes as well
- Load the Payments > Disputes which by default loads with `Needs Response` filter
- Click on download button.
- Note that export type used is async (export will be emailed to you) and the CSV contains both Needs Response and other status disputes.

### Actual behavior
The async export CSV contains all disputes

### Expected behavior
Page was loaded with filter, so only the filtered rows should be exported

### Additional context
- If number of rows less than 25, browser based CSV export is used, which works as expected
- Discovered while working on #9764 which made the issue more obvious as browser based export was removed.

### PR DESCRIPTION
**Pull request by jessy-p**
Fixes #9987 

Filtering for `awaiting_response` was implemented separately for `useDisputes` and `useDisputesSummary` and missing for `getDisputesCSV`, causing the bug where the CSV was not filtered.

#### Changes proposed in this Pull Request

- Consolidated filtering for `awaiting_response` in `formatQueryFilters`
- Removed the duplicate code and params from `hooks.ts`
- Added `filter` param to `getDisputesCSV`

#### Testing instructions

- Check that the Disputes listing on Payments > Disputes filters correctly for `Needs Response` and advanced filters.
- Ensure that the summary is updated.
- Bug from #9987 should be fixed.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9988` or branch name `fix/9987-filter-csv-disputes` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9987-filter-csv-disputes) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: d106f2f8e125c71e8ddd3267ea329171ce4b42aa
- Build time: 2024-12-18 18:36:27 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/data/disputes/resolvers.js [hunk 1]
```diff
@@ -38,11 +39,18 @@ const formatQueryFilters = ( query ) => ( {
...
 
 export function getDisputesCSV( query ) {
+	const queryWithSearch = {
+		...query,
+		search:
+			query.filter === 'awaiting_response'
+				? disputeAwaitingResponseStatuses
+				: query.search,
+	};
+
```
Comment (Jinksi) [inline client/data/disputes/resolvers.js]: 💭 it might be better for consistency to apply this in a single place for all `/disputes/`,`/disputes/download`,`/disputes/summary` API requests – I think `formatQueryFilters` in this file would be suitable since it is also where we are modifying the query in other ways.

```diff
const formatQueryFilters = ( query ) => ( {
	user_email: query.userEmail,
	match: query.match,
	store_currency_is: query.storeCurrencyIs,
	date_before: formatDateValue( query.dateBefore, true ),
	date_after: formatDateValue( query.dateAfter ),
	date_between: query.dateBetween && [
		formatDateValue( query.dateBetween[ 0 ] ),
		formatDateValue( query.dateBetween[ 1 ], true ),
	],
-	search: query.search,
+ // If `awaiting_response` filter is present, use the `search` query to select only those disputes awaiting a response.
+ search:
+		query.filter === 'awaiting_response'
+			? disputeAwaitingResponseStatuses
+			: query.search,
	status_is: query.statusIs,
	status_is_not: query.statusIsNot,
	locale: query.locale,
} );
```

This would then mean we can apply the same filtering to all requests, reducing the chance of inconsistency bugs like the one we're solving in this PR.

We implemented (or really, I did, if looking at `git blame`) the following `awaiting_response` filtering in the `useDisputes` hook, which can be removed if we apply this logic across to all "dispute list" requests. We'd have to do some extra testing to make sure we don't break those endpoints, but it would be worth it IMO.

https://github.com/Automattic/woocommerce-payments/blob/a89f43447c41e2ac74c018357019523f1a024c36/client/data/disputes/hooks.ts#L101-L104

Comment (Jinksi) [reply client/data/disputes/resolvers.js]: Not to say your solution doesn't work, by the way! But it will mean we are applying this logic in different places for different endpoints (`/disputes/`, `/disputes/download`, `/disputes/summary`).

Comment (jessy-p) [reply client/data/disputes/resolvers.js]: Thanks for the review @Jinksi, I've consolidated the code into `formatQueryFilters`

**Comment by nagpai** [comment]
### Manual test

✅  - Manual test passes

I have 22 disputes on my test site. I enforced the code to always do endpoint export for the purpose of testing.

* I was able to replicate the bug on the `develop` branch - All disputes are exported even when there is a filter of  `Needs Response`. 
* On checking out this branch, I now see only `needs_response` and `warning_needs_response` status disputes getting exported, as expected and required.

File: client/data/disputes/hooks.ts [hunk 2]
```diff
@@ -158,16 +152,12 @@ export const useDisputesSummary = ( {
 	filter,
 	status_is: statusIs,
 	status_is_not: statusIsNot,
+	search,
```
Comment (nagpai) [inline client/data/disputes/hooks.ts]: Linter shows `search` as defined and not used. We may remove this.

**Review by nagpai — APPROVED** [review]
Code changes look fine and good to ship. One small linter comment about undefined var to be removed.

File: client/data/disputes/hooks.ts (hunk 2 above)
Comment (jessy-p) [reply client/data/disputes/hooks.ts]: Fixed

**Review by Jinksi — APPROVED** [review]
🌟 Thanks for applying this filter consistently across the `/disputes`, `/disputes/summary`, `/disputes/download` endpoints.

The disputes list view filtering works as expected for the:
* `Needs response` filter ✅
* `Advanced` filter ✅
* no filter ✅

CSV exporting is also working as intended ✅
