### PR TITLE
Fix: Use a filter instead of an action hook to properly wait for payment request button updates

### LINKED ISSUE #9000: Tokenized PRB shortcode cart total update is delayed
### Describe the bug

On the shortcode cart, after updating cart totals(quantity change, coupon, etc.) then subsequently clicking the PRB to open the payment interface, there is a delay before the total updates to the correct total. The old total is briefly displayed.

The delay occurs due to the [`updateCustomer` call](https://github.com/Automattic/woocommerce-payments/blob/a63d3b90c66df54f1b0395f478e206a9f36bca44/client/tokenized-payment-request/payment-request.js#L246) that happens when the payment interface opens for the first time after initialization. Because we have to re-initialize the PRB when cart totals update, that event will fire on the first button click after totals have updated. `cartData` needs to be updated also, when [cart totals update](https://github.com/Automattic/woocommerce-payments/blob/aac2f270fa282260326e5dc0677c80fed23353b3/client/tokenized-payment-request/index.js#L76), most likely via the  `wcpay.payment-request.update-button-data` hook. Something like this: 

```
$( document.body ).on( 'updated_cart_totals', async () => {
	doAction( 'wcpay.payment-request.update-button-data' );
	await waitForAction( 'wcpay.payment-request.update-button-data' );
	wooPaymentsPaymentRequest.init();
} );
```

### To Reproduce

1. Enable the "Enable Cart-Token implementation for PRBs" flag in your dev tools
2. Add a product to the cart
3. Visit the cart page
4. Update the item quantity and click update cart
5. Click the PRB and notice the pre-update total is briefly displayed before the correct total is displayed

### Actual behavior

The payment interface briefly displays an incorrect total before updating to the correct total.

### Screenshots

See the video [here](https://github.com/Automattic/woocommerce-payments/pull/8891#pullrequestreview-2124397374).

### Expected behavior

After clicking the PRB, the total displayed in the payment interface should be correct.

### Additional context

https://github.com/Automattic/woocommerce-payments/pull/8891#pullrequestreview-2124397374

### PR DESCRIPTION
**Pull request by danielmx-dev**
Fixes #9000

#### Changes proposed in this Pull Request

Currently, an there's an action that will be run when we need to update the PRB data (e.g. the cart totals) called `'wcpay.payment-request.update-button-data'`. Once the data is refreshed, we need to reinitialize the PRB component. 

In order to make sure that these steps happen in the correct order, a helper function called `waitForAction` was implemented; however, after some debugging I found out that this function is not working as expected, given that it relies on the `doingAction` function from `@wordpress/hooks` which doesn't have asynchronous support.

This PR performs the following changes:

1. Remove `waitForData` and instead use filters for `'wcpay.payment-request.update-button-data'`. If we combine the filters with async/await (Promises), we should be able to achieve the desired result without having to add asynchronous support to `@wordpress/hooks`.
2. Add the fix suggested in the description of #9000, but instead use the new filter-based mechanism. This fixes the problem with the delayed totals update.

#### Testing instructions
Pre-requisite: Enable the "Enable Cart-Token implementation for PRBs" flag in your dev tools

##### Classic Cart
1. Add a product to the cart.
2. Visit the cart page.
4. Click the PRB. the correct totals should be displayed.
5. Update the item quantity and click update cart.
6. Click the PRB. the new totals should be displayed
**Note**: You can also look at the video posted [here](https://github.com/Automattic/woocommerce-payments/pull/8891#pullrequestreview-2124397374) to see the behavior without the fix.

##### Product Page
1. Go to a "Variable Product" page.
2. Choose one of the variations. Don't add to cart.
4. Click the PRB, the correct total should be displayed.
8. Choose a different variation (that has a different price). Don't add to cart.
9. Click the PRB, the correct total should be displayed.
10. Update the product quantity. Don't add to cart.
11. Click the PRB, the correct total should be displayed.

##### Classic Checkout
1. Add a product to the cart.
2. Visit the checkout page.
3. Click the PRB. the correct totals should be displayed.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9022` or branch name `fix/9000-tokenized-prb-shortcode-cart-total-delayed` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9000-tokenized-prb-shortcode-cart-total-delayed) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 5627c5c32335cf7f227c5c6e8219867b470392dd
- Build time: 2024-07-02 14:54:33 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/tokenized-payment-request/index.js [hunk 1]
```diff
@@ -72,12 +72,19 @@ jQuery( ( $ ) => {
...
 	} );
 
 	// We need to refresh payment request data when total is updated.
-	$( document.body ).on( 'updated_checkout', () => {
-		doAction( 'wcpay.payment-request.update-button-data' );
+	$( document.body ).on( 'updated_checkout', async () => {
+		await applyFilters(
+			'wcpay.payment-request.update-button-data',
+			Promise.resolve()
+		);
```
Comment (danielmx-dev) [inline client/tokenized-payment-request/index.js:88]: Converting this to async await doesn't do much here, but I changed it just to keep it consistent.

**Review by brettshumaker — APPROVED** [review]
This is working well for me! 👍
