### PR TITLE
Fix so that resubscribe prices are not converted a second time

### LINKED ISSUE #2353: Subscription cost is converted again when resubscribing
Subscriptions are cancelled in many ways, but from there the store customer is able to resubscribe under My Account > Subscriptions. When doing so, the cost of the subscription is converted again, similar to early renewals. 

Replication steps:

1. Purchase a subscription.
2. Go to WooCommerce > Subscriptions in the admin.
3. Hover the new subscription and click Cancel, once the page refreshes hover again and choose Cancel Now.
4. Navigate to My Account > Subscriptions, and then click View for the cancelled subscription.
5. Click the Resubscribe button, and the subscription added to the cart will have the price converted a second time.

This should be able to be fixed in a similar fashion as in https://github.com/Automattic/woocommerce-payments/pull/2318

### PR DESCRIPTION
**Pull request by jessepearson**
Fixes #2353

#### Changes proposed in this Pull Request

* `cart_contains_resubscribe` checks ti see if there is a resubscribe found in the cart.
* `is_product_subscription_type_in_cart` replaces `is_product_subscription_renewal` to check to see if the product being converted is of the type passed in the cart. 
* Force/override the selected currency if there is a resubscribe in the cart. Use the subscription's currency.
* Disable widget(s) if there's a resubscribe in the cart.
* Do not convert the price in the cart if there's a resubscribe in the cart.
* Updated tests accordingly.

#### Testing instructions

1. Purchase a subscription.
2. Go to WooCommerce > Subscriptions in the admin.
3. Hover the new subscription and click Cancel, once the page refreshes hover again and choose Cancel Now.
4. Navigate to My Account > Subscriptions, and then click View for the cancelled subscription.
5. Click the Resubscribe button, and the subscription added to the cart will have the correct price.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/multi-currency/Compatibility.php [hunk 1]
```diff
@@ -62,15 +72,18 @@ public function should_hide_widgets(): bool {
...
+				|| $this->is_product_subscription_type_in_cart( $product, 'resubscribe' ) ) {
+				$calls = [
+					'WC_Cart_Totals->calculate_item_totals',
+					'WC_Cart->get_product_subtotal',
+					'wc_get_price_excluding_tax',
+					'wc_get_price_including_tax',
+				];
+				if ( $this->utils->is_call_in_backtrace( $calls ) ) {
+					return false;
+				}
```
Comment (luizreis) [inline includes/multi-currency/Compatibility.php:86]: What do you think of reducing the indentation level here by inverting the ifs? Would it make this easier to read? I haven't tried this, and it might not make much sense here, so I'll defer it to you 😄

File: tests/unit/multi-currency/test-class-compatibility.php [hunk 2]
```diff
@@ -51,11 +51,19 @@ public function test_override_selected_currency_return_true() {
 
 	public function test_should_hide_widgets_return_false() {
 		$this->mock_wcs_cart_contains_renewal( false );
+		$this->mock_wcs_cart_contains_resubscribe( false );
 		$this->assertFalse( $this->compatibility->should_hide_widgets() );
 	}
 
-	public function test_should_hide_widgets_return_true() {
+	public function test_should_hide_widgets_return_true_test_1() {
```
Comment (luizreis) [inline tests/unit/multi-currency/test-class-compatibility.php:58]: What do you think about naming these tests `test_should_hide_widgets_return_true_when_renewal_in_cart` and `test_should_hide_widgets_return_true_when_resubscribe_in_cart`?

**Review by luizreis — APPROVED** [review]
Thanks for working on this @jessepearson. It works really well! I left a couple of comments, but this is already in great shape, so I'm pre-approving it! :shipit:

File: includes/multi-currency/Compatibility.php (hunk 1 above)
Comment (jessepearson) [reply includes/multi-currency/Compatibility.php:86]: Inverting the if for the product and adding an early return does make it easier to read: 

```
	public function should_convert_product_price( $product = null ): bool {
		if ( ! $product ) {
			return true;
		}

		// Check for subscription renewal or resubscribe.
		if ( $this->is_product_subscription_type_in_cart( $product, 'renewal' )
			|| $this->is_product_subscription_type_in_cart( $product, 'resubscribe' ) ) {
			$calls = [
				'WC_Cart_Totals->calculate_item_totals',
				'WC_Cart->get_product_subtotal',
				'wc_get_price_excluding_tax',
				'wc_get_price_including_tax',
			];
			if ( $this->utils->is_call_in_backtrace( $calls ) ) {
				return false;
			}
		}

		return true;
	}
```

I _think_ further nesting could be removed by changing:

```
		if ( $this->is_product_subscription_type_in_cart( $product, 'renewal' )
			|| $this->is_product_subscription_type_in_cart( $product, 'resubscribe' ) ) {
				...
```

to this

```
		if ( ! $this->is_product_subscription_type_in_cart( $product, 'renewal' )
			&& ! $this->is_product_subscription_type_in_cart( $product, 'resubscribe' ) ) {
				return true;
```

Is that what you were thinking?

Comment (jessepearson) [reply includes/multi-currency/Compatibility.php]: Just noting, I updated to the first chunk here in https://github.com/Automattic/woocommerce-payments/pull/2367/commits/8d55540622e6a1b5f52c9ff1b2d876e2fa137fc3

File: tests/unit/multi-currency/test-class-compatibility.php (hunk 2 above)
Comment (jessepearson) [reply tests/unit/multi-currency/test-class-compatibility.php]: This is where my lack of experience gets me, I did the same in #2318 (which was before this PR) due to the number of tests that were so similar, and carried through to this PR with the same. Thanks for the suggestions, I've updated them in https://github.com/Automattic/woocommerce-payments/pull/2367/commits/8d55540622e6a1b5f52c9ff1b2d876e2fa137fc3

File: includes/multi-currency/Compatibility.php (hunk 1 above)
Comment (luizreis) [reply includes/multi-currency/Compatibility.php]: Awesome! I like how it looks like after removing the `$product` check nesting 🔥. If you find that the second change is not that beneficial we could leave it like it is right now and merge this PR. 🚀
