### PR TITLE
Fix the checkout in IE11

### LINKED ISSUE #821: Internet Explorer 11 incompatibility: Unable to enter in credit card details
I had a user in 23278560-hc (follow up in 3221933-zen who reported that the fields to enter in credit card details are missing in Internet Explorer 11. I tested this with Browserstack and was able to confirm it:

checkout
*Full link: https://d.pr/i/qq0dfc*

### PR DESCRIPTION
**Pull request by DanReyLop**
Fixes #821

#### Changes proposed in this Pull Request

In this PR, I added the `wcpay-checkout.js` script to our Webpack + Babel build system. That means that JS syntax unsupported in IE11 will be transpiled and just work. Going commit-by-commit:
- https://github.com/Automattic/woocommerce-payments/commit/1bd9281eecc283f6f13912d644e23cb6a58f88e1 Move the script and CSS files to the build system.
- https://github.com/Automattic/woocommerce-payments/commit/2dec2d19aefbe3dcfc76bbb99c36aadd4581e4de Removed a property access that's not supported on IE11. Babel can't protect us from everything.
- https://github.com/Automattic/woocommerce-payments/commit/ee2f7bbfda911bf3825ec0d719db790626a138c8 https://github.com/Automattic/woocommerce-payments/commit/78acf1af10f70cae50768749fcd89a28f1a432fa made the checkout script a bit more compliant with our "modern" code style.

I realized how stuborn I've been about not wanting to add the checkout to the Webpack+Babel pipeline. My reasoning was _"on the frontend, every KB counts, specially in something as mission-critical as the checkout. Webpack+Babel will add too much bloat"_. Which made sense, but here's the kicker: **We aren't running the minifier on `/assets/js/`**. So, the hand-crafted `wcpay-checkout.js` file was around `15KB`. Now that it goes through the whole Webpack+Babel contraption, it's **6.5KB**. Of course, applying the minifier **and** not running Webpack+Babel would give us something even smaller than that, but at that point it's just diminishing returns.

So, by adding the checkout to the build pipeline, it's actually getting smaller. And we won't need to worry about using JS syntax that's "too modern" for IE11. Win-win.

#### Testing instructions

I tested the checkout on a [Windows 7 VM with IE11 installed](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/), but you don't have to. You could just check that nothing broke in Chrome or whatever modern browser you use. Test cases:
- Pay with an SCA card.
- Pay with a regular card.
- Pay with a saved card.

Props @luizreis for doing the legwork on this issue!

### CODE REVIEW

File: client/checkout/index.js [hunk 1]
```diff
@@ -393,24 +396,24 @@ jQuery( function ( $ ) {
...
 			/^#wcpay-confirm-pi:(.+):(.+):(.+)$/
 		);
 
 		if ( ! partials ) {
 			return;
 		}
 
-		var orderPayIndex = document.location.href.indexOf( 'order-pay' );
-		var isOrderPage = orderPayIndex > -1;
+		const orderPayIndex = document.location.href.indexOf( 'order-pay' );
```
Comment (luizreis) [inline client/checkout/index.js:407]: I know this change is not part of this PR and that modern browsers map `document.location` to `window.location`, but I think it would be nice to use `window.location` here to conform with how we use it in other places. What do you think?

File: client/checkout/index.js [hunk 2]
```diff
@@ -500,8 +503,8 @@ jQuery( function ( $ ) {
 	maybeShowAuthenticationModal();
 
 	// Handle hash change - used when authenticating payment with SCA on checkout page.
-	window.addEventListener( 'hashchange', function ( event ) {
-		if ( 0 < event.newURL.indexOf( '#wcpay-confirm-pi' ) ) {
+	window.addEventListener( 'hashchange', function () {
+		if ( 0 < window.location.hash.startsWith( '#wcpay-confirm-pi' ) ) {
```
Comment (luizreis) [inline client/checkout/index.js:507]: This is probably not a concern, but the previous code would match `#wcpay-confirm-pi` even if it wasn't the first string in the hash (e.g. `#somestring#wcpay-confirm-pi`), while the new one wouldn't.

It's unlikely that we'll need to add two parts to the hash, but do you think it would be worth it to search for `#wcpay-confirm-pi` in the entire hash instead of just its beginning?

If we stick to `startsWith`, I think it would be better to remove the `0 < ` comparison, as `startsWith` returns a boolean instead of the index of the occurrence.

**Review by luizreis — CHANGES_REQUESTED** [review]
Thanks for submitting this PR @DanReyLop! I like that we're running this script through our Webpack+Babel pipeline. It will be useful to avoid regressions on IE11 in the future.

I left a couple of comments, and once we've resolved them, this should be in good shape to be shipped.

File: client/checkout/index.js (hunk 2 above)
Comment (DanReyLop) [reply client/checkout/index.js]: > the previous code would match #wcpay-confirm-pi even if it wasn't the first string in the hash (e.g. #somestring#wcpay-confirm-pi), while the new one wouldn't.

That's not a problem. [Here](https://github.com/Automattic/woocommerce-payments/blob/af28be94392cf414f203f15271535155525f4c6a/assets/js/wcpay-checkout.js#L396-L398) the URL to "redirect to" is built, there's no way for that URL to contain anything other than `#wcpay-confirm-pi...` in the hash. Also, [here](https://github.com/Automattic/woocommerce-payments/blob/af28be94392cf414f203f15271535155525f4c6a/assets/js/wcpay-checkout.js#L396-L398) there's a RegExp that's matching the whole hash, so the assumption that there's nothing else in the hash is already backed in.

> If we stick to startsWith, I think it would be better to remove the 0 < comparison, as startsWith returns a boolean instead of the index of the occurrence.

Oh, good catch! Of course it still works, because JavaScript 😂  Fixed in https://github.com/Automattic/woocommerce-payments/pull/902/commits/5be2767f7e3fbb657839564e212b0e8bb69b2cb5

File: client/checkout/index.js (hunk 1 above)
Comment (DanReyLop) [reply client/checkout/index.js]: Absolutely, I hadn't even noticed it. I checked and there are no other usages of `document.location`. Fixed in https://github.com/Automattic/woocommerce-payments/pull/902/commits/5be2767f7e3fbb657839564e212b0e8bb69b2cb5

File: client/checkout/index.js (hunk 2 above)
Comment (luizreis) [reply client/checkout/index.js]: > That's not a problem. Here the URL to "redirect to" is built, there's no way for that URL to contain anything other than #wcpay-confirm-pi... in the hash. Also, here there's a RegExp that's matching the whole hash, so the assumption that there's nothing else in the hash is already backed in.

Makes sense. Thanks for clarifying it!

> Of course it still works, because JavaScript 😂

😆  - [because JavaScript](https://img.devrant.com/devrant/rant/r_1795923_nJRoc.jpg)

Comment (DanReyLop) [reply client/checkout/index.js]: hahahahaha that meme is great!
