### PR TITLE
Fix changing payment from saved payment for subscriptions order.

### LINKED ISSUE #1185: Subscription payment method cannot be changed to the saved card
To reproduce:

1. Purchase subscription product.
2. Go to My account > Add one more payment method.
3. Go to My account > Subscription > Purchased subscription.
4. Try to change payment method to saved on step 2. 
5. Success message is displayed but payment method is not changed.

@luizreis made some good assumptions in the https://github.com/Automattic/woocommerce-payments/pull/1148#issuecomment-750410406

TODO: 

- [ ] Fix the issue
- [ ] Cover with unit/integration tests
- [ ] Add E2E test

### PR DESCRIPTION
**Pull request by shendy-a8c**
Fixes #1185

#### Changes proposed in this Pull Request

- Add a flag in Payment_Information to mark whether we are changing payment for subscriptions order or not.
- The bug is because when changing payment method using saved payment, we end up [in this if block](https://github.com/Automattic/woocommerce-payments/pull/1288/files#diff-bcfd303d507c33a27671935e724ee64d0df30ff2a18bb6ef4c94f28d48190124R575) and `add_token_to_order()` is not called, so we call `add_token_to_order()` and add order note to fix.

#### Testing instructions

Shamelessly copied from [1185](https://github.com/Automattic/woocommerce-payments/issues/1185).
1. Purchase subscription product.
2. Go to My account > Add one more payment method.
3. Go to My account > Subscription > Purchased subscription.
4. Try to change payment method to saved on step 2.
5. Success message is displayed but payment method is not changed. With this branch, payment method should be changed successfully.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php [hunk 1]
```diff
@@ -84,7 +84,8 @@ private function is_changing_payment_method_for_subscription() {
 	 * @return Payment_Information An object, which describes the payment.
 	 */
 	protected function prepare_payment_information( $order ) {
-		if ( ! wcs_order_contains_subscription( $order->get_id() ) && ! $this->is_changing_payment_method_for_subscription() ) {
+		$is_changing_payment = $this->is_changing_payment_method_for_subscription();
+		if ( ! wcs_order_contains_subscription( $order->get_id() ) && ! $is_changing_payment ) {
```
Comment (kalessil) [inline includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php:88]: Can we move `! $is_changing_payment` at first place in this condition - to make code a little bit lazier =)

**Review by kalessil — CHANGES_REQUESTED** [review]

File: includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php (hunk 1 above)
Comment (shendy-a8c) [reply includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php]: Lazy is good! Done.

**Review by kalessil — APPROVED** [review]
LGTM, :shipit:
