### PR TITLE
Tidy tracks events for "create subscription product" flow

### LINKED ISSUE #3460: Tracks event not sent consistently: `wcadmin_wcpay_subscriptions_account_not_connected_publish_products`
### Describe the bug
Follow up to #3449.

One of the events is not firing consistently: `wcadmin_wcpay_subscriptions_account_not_connected_publish_products`. 

#### Prerequisites
* WC Subscriptions is **not** installed / active.
* Fresh site where WCPay onboarding is **not completed** or enable `Force the plugin to act as disconnected from WCPay` setting in WCPay Dev Utils.
* Enable tracking under `WC settings > Advanced > WooCommerce.com` (/wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com).

#### Reproduce steps
* Navigate to `Products → Add New`.
* Add product name and switch the product type to "Simple subscription".
* Add subscription price.
* Click `Publish`.
* Wait for the page request to complete.
* Observe the "One more step..." modal appears and the product remains in the draft status.
* Click the "Finish setup" button.
* Complete the WCPay onboarding.
* Observe you are redirected back to the product edit page.
* Observe the product is now published.
   - The tracks event should fire some time after here. 
* Observe the toast notification "Thank you for setting up WooCommerce Payments! We’ve published your first subscription product.".

Note: tracks events can be viewed in `Network` tab in browser tools, as requests for a `gif` image file with request params for event name and props.

### Actual behavior
The event doesn't fire consistently.

### PR DESCRIPTION
**Pull request by haszari**
Fixes #3460

## Changes proposed in this Pull Request
This PR makes some changes to tracks events that fire during product creation flow.

Removed one event: `wcpay_subscriptions_account_not_connected_publish_products`. This event is not needed right now, and is not reliable. Side note: not sure why it's not firing reliably. Might be due to caching, as event is fired server side, or the event may be fired too late to be reliably enqueued in page render for client side send to track service.

Added one event: `wcpay_subscriptions_account_not_connected_product_modal_view`. This event fires in the client side when the modal is rendered (i.e. shown to user).  I've refactored the modal content to a new component, as this event needs to be fired from a mount effect; the main modal component has logic for `isOpen` state.

This is a follow up to #3449.

### Prerequisites
* WC Subscriptions is **not** installed / active.
* Fresh site where WCPay onboarding is **not completed** or enable `Force the plugin to act as disconnected from WCPay` setting in WCPay Dev Utils.
* Enable tracking under `WC settings > Advanced > WooCommerce.com` (/wp-admin/admin.php?page=wc-settings&tab=advanced&section=woocommerce_com).

### Reproduce steps
* Navigate to `Products → Add New`.
* Add product name and switch the product type to "Simple subscription".
* Add subscription price.
* Click `Publish`.
* Wait for the page request to complete.
* Observe the "One more step..." modal appears and the product remains in the draft status.
   * **Confirm `wcpay_subscriptions_account_not_connected_product_modal_view` event is fired consistently when the modal is displayed.**
* Click the "Finish setup" button.
* Complete the WCPay onboarding.
* Observe you are redirected back to the product edit page.
* Observe the product is now published.
   * Confirm `wcpay_subscriptions_account_not_connected_publish_products` is not fired.
* Observe the toast notification "Thank you for setting up WooCommerce Payments! We’ve published your first subscription product.".
  * Confirm related tracks events for modal dismiss and finish setup are working correctly (after minor refactor).

Experiment reloading the page and editing different products, confirm events are only fired when appropriate.

Note: tracks events can be viewed in `Network` tab in browser tools, as requests for a `t.gif` image file with request params for event name and props.

Screen Shot 2021-12-22 at 10 07 22 AM

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply) n/a - this change is tracking only and should have zero impact
- [x] Covered with tests (or have a good reason not to test in description ☝️) n/a - tracks events are verified elsewhere
- [x] Tested on mobile (or does not apply) n/a

**Post merge**

- [x] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply) n/a

### CODE REVIEW

**Comment by haszari** [comment]
Note for reviewers – once this PR is reviewed and finalised, I'll follow up with a PR to register the changes to the tracks events.

**Comment by haszari** [comment]
@shendy-a8c I've added this to WCPay 3.5 milestone, but happy to bump it to WCPay 3.6 - no urgency here.

File: client/subscription-product-onboarding/modal.js [hunk 1]
```diff
@@ -57,6 +57,11 @@ const SubscriptionProductOnboardingModal = () => {
 		return null;
 	}
 
+	wcpayTracks.recordEvent(
+		wcpayTracks.events
+			.SUBSCRIPTIONS_ACCOUNT_NOT_CONNECTED_PRODUCT_MODAL_VIEW
+	);
```
Comment (aprea) [inline client/subscription-product-onboarding/modal.js:63]: Hey @haszari, we probably want to move this logic into a new [effect](https://reactjs.org/docs/hooks-effect.html).

Example here → https://github.com/Automattic/woocommerce-payments/blob/3817794/client/subscriptions-empty-state/index.js#L106-L113

Comment (haszari) [reply client/subscription-product-onboarding/modal.js]: Good point, thanks for catching that! I agree, this should be wrapped in an effect so it fires only once, [i.e. a "mount" effect](https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects).

Fixed in this commit: e4df890d4ca81cb665dcddc1933581b63fd4f09a

Note to do this I needed to factor out the modal content into a new component, and add the mount effect there. That was necessary because the event should only fire if `isOpen`, and conditionals and effects don't mix. Let me know if there's a better way to do this :)

**Review by aprea — APPROVED** [review]
Tested this on a fresh JN site, LGTM ✅

**Comment by haszari** [comment]
Thanks @aprea ! Merging :)
