### PR TITLE
[BNPL site messaging] Fix Country informed as empty for logged-out user

### LINKED ISSUE #6630: [BNPL Site Messaging] Country informed as empty for logged-out user
### To Reproduce

1. Make sure that Affirm or Afterpay are available in your test site.
2. As a non-logged-in user, visit the product details page
3. Check the error
### Actual behavior

1. The BNPL site messaging block is not displayed
2. The country field in `wcpayStripeSiteMessaging` configuration object is empty.
3. There's an error in the browser's console
Screenshot 2023-06-29 at 17 29 47

### Expected behavior

1. The BNPL site messaging block is displayed
2. The country field in `wcpayStripeSiteMessaging` configuration object is set to the store's country.
3. No error in browser console

### PR DESCRIPTION
**Pull request by mgascam**
Fixes #6630 

#### Changes proposed in this Pull Request

Refactor the country fallback to avoid country set as empty when the customer billing address is not set.

#### Testing instructions

1. Make sure that Affirm or Afterpay are available in your test site.
2. As a non-logged-in user, visit the product details page
3. Check that the BNPL site messaging block is displayed
4. Check that the country field in `wcpayStripeSiteMessaging` configuration object is set to the store's country.
5. This error is not shown in browser console
Screenshot 2023-06-29 at 17 29 47

*

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6631` or branch name `fix/6630-bnpl-site-messaging-country-informed-as-empty-for-logged-out-user` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6630-bnpl-site-messaging-country-informed-as-empty-for-logged-out-user) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 998d8d0df0194d8e9668263feb64183954e1241d
- Build time: 2023-06-30 14:53:49 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by KarlisJ** [comment]
Code changes look good, but I fail to see the messaging element in my shop. Is there a specific setup that I have to complete?

**Comment by mgascam** [comment]
> Code changes look good, but I fail to see the messaging element in my shop. Is there a specific setup that I have to complete?

Thanks @KarlisJ. Nothing specific apart from having Affirm & Afterpay enabled in the store. Do you see any error in the console? Can you check what is the `country` value in the `wcpayStripeSiteMessaging` config object (it can be accessed in the browser console)

File: includes/class-wc-payments-payment-method-messaging-element.php [hunk 1]
```diff
@@ -50,11 +50,8 @@ public function init(): string {
 		global $product;
 		$price           = $product->get_price();
 		$currency_code   = get_woocommerce_currency();
-		$billing_country = WC()->countries->get_base_country();
-
-		if ( WC()->customer ) {
-			$billing_country = WC()->customer->get_billing_country(); // Use the customer's billing country if available.
-		}
+		$base_country    = WC()->countries->get_base_country();
```
Comment (kalessil) [inline includes/class-wc-payments-payment-method-messaging-element.php]: Is that store country? If so, please rename the variable.

**Review by kalessil — APPROVED** [review]
Pre-approving.

File: includes/class-wc-payments-payment-method-messaging-element.php (hunk 1 above)
Comment (mgascam) [reply includes/class-wc-payments-payment-method-messaging-element.php]: Renamed in [b1fab5a](https://github.com/Automattic/woocommerce-payments/pull/6631/commits/b1fab5ad49878346aa3c5ff84f6f16293b93e9c6) thanks!
