### PR TITLE
Fix reverse WPCOM url in Safe Mode

### LINKED ISSUE #8025: Safe Mode Message Showing Origin Name in Reverse.
### Describe the bug
When the 'Safe Mode' appears for merchants that are changing the domain, the origin domain is appearing in reverse in the message

### Screenshots

woocomerce bug

Screen Shot 2024-01-15 at 2 19 25 PM

### Expected behavior

The origin domain name should appear correctly in the message

### Additional context

Tickets:
 - 7589094-zd
- 7589228-zd

### PR DESCRIPTION
**Pull request by oaratovskyi**
Fixes #8025 

#### Changes proposed in this Pull Request

* Added `WC_Payments_Utils::reverse_url_if_trailing_slash()`
* Use this function in Jetpack Safe Mode notice logic to fix WPCOM url. Jetpack returns reversed url to us in some cases

#### Testing instructions

* Check out the branch `8025/fix-safe-mode-message-reverse-host`
* Go to http://localhost:8082/wp-admin/admin.php?page=jetpack-debug-tools
* Enable Identity Crisis Simulation Utility
* Enable IDC simulation in http://localhost:8082/wp-admin/admin.php?page=idc-simulator, set Spoof URL http://host.docker.internal
* Run `ngrok http 8082` locally
* Visit your https://xxx.ngrok-free.app/wp-admin/admin.php?page=idc-simulator and see the notice
image
* Remove the function `WC_Payments_Utils::reverse_url_if_trailing_slash()` in  https://github.com/Automattic/woocommerce-payments/blob/0e4d7e071bac454c551560bdecc7936f81b31805/woocommerce-payments.php#L337-L337 to see how it looks like without the fix

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [x] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _'QA Testing Not Applicable'_
- [x] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [x] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8033` or branch name `8025/fix-safe-mode-message-reverse-host` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=8025/fix-safe-mode-message-reverse-host) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 951b9f57a55aa4a88400454e09d672a9fcf30df5
- Build time: 2024-01-19 14:05:41 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Review by ismaeldcom — APPROVED** [review]
The new code makes sense and testing instructions work as expected. Thanks for finding a way to solve this tradeoff 🙂

**Review by vladolaru — COMMENTED** [review]
@oaratovskyi Thanks for working on this.

I am little doubtful on the path chosen though because it feels prone to issues as it relies on the slash being at the beginning (a weak signal).

Looking at the Jetpack IDC library [logic](https://github.com/Automattic/jetpack-identity-crisis/blob/trunk/src/class-identity-crisis.php#L470), they reverse the WPCOM URLs that are saved in the  `sync_error_idc` transient. We query that transient-stored data  through `$urls = Automattic\Jetpack\Identity_Crisis::get_mismatched_urls();`

 According to the Jetpack IDC library [logic](https://github.com/Automattic/jetpack-identity-crisis/blob/trunk/src/class-identity-crisis.php#L97), the `wpcom_url` is always saved reversed. As a consequence, we should always re-reverse it.

As an added safety we could use `Automattic\Jetpack\Identity_Crisis::check_identity_crisis()` to get the stored data and do the same check as [here](https://github.com/Automattic/jetpack-identity-crisis/blob/trunk/src/class-identity-crisis.php#L471).

I've left a change suggestion (https://github.com/Automattic/woocommerce-payments/pull/8033/files#r1458920065).

WDYT?

File: woocommerce-payments.php [hunk 1]
```diff
@@ -333,7 +334,7 @@ function wcpay_get_jetpack_idc_custom_content(): array {
 	$urls = Automattic\Jetpack\Identity_Crisis::get_mismatched_urls();
 	if ( false !== $urls ) {
 		$current_url = untrailingslashit( $urls['current_url'] );
-		$wpcom_url   = untrailingslashit( $urls['wpcom_url'] );
+		$wpcom_url   = untrailingslashit( WC_Payments_Utils::reverse_url_if_trailing_slash( $urls['wpcom_url'] ) );
```
Comment (vladolaru) [inline woocommerce-payments.php]:
```suggestion
       /**
        * Undo the reverse the Jetpack IDC library is doing since we want to display the URL.
        * @see https://github.com/Automattic/jetpack-identity-crisis/blob/trunk/src/class-identity-crisis.php#L471
        */
        $idc_sync_error = Automattic\Jetpack\Identity_Crisis::check_identity_crisis();
        if ( is_array( $idc_sync_error ) && ! empty( $idc_sync_error['reversed_url'] ) ) {
			$urls['wpcom_url'] = strrev( $urls['wpcom_url'] );
		}
		$wpcom_url   = untrailingslashit( $urls['wpcom_url'] );
```

Comment (vladolaru) [reply woocommerce-payments.php]: @ismaeldcom WDYT?

Comment (ismaeldcom) [reply woocommerce-payments.php]: This solution looks better, but as I mentioned in Slack this morning, all we can do is patch a hacky solution. The real solution should be done on the Jetpack side.

Comment (oaratovskyi) [reply woocommerce-payments.php]: Thanks @vladolaru ! This solution looks safer, I'll try if it works locally 👍

Comment (oaratovskyi) [reply woocommerce-payments.php]: @vladolaru great solution, works like a charm! Done in https://github.com/Automattic/woocommerce-payments/pull/8033/commits/3a1d38fa33d94d4368cddf8622e2d6904a7d919e

**Review by vladolaru — APPROVED** [review]
Thanks for embracing a simpler solution, Oleks! Everything looks good!
