### PR TITLE
Fix race condition when processing webhooks

### LINKED ISSUE #3345: Stock reduced twice with one payment
### Describe the bug

On occasion, stock is being reduced twice for a single order/payment, as discussed in this [WordPress.org thread](https://wordpress.org/support/topic/duplicate-stock-reduction-from-one-payment/).

### To Reproduce

This is sporadic so difficult to reproduce. It's potentially a race condition between webhooks and something else handling the order status - checkout logic perhaps?

At a complete guess for steps to reproduce, adding a delay between checkout processing the order may allow the webhook to consistently update it first, and it will be interesting to see if that causes it.

A code review of the stock reduction may be a better way to diagnose the cause. As one customer mentioned via ZenDesk:

> In `class-wc-payment-gateway-wcpay.php` I can see that you use wc_reduce_stock_levels when the stock gets reduced. Maybe it would be wise and solve the problem when you first check if stock has been reduced already and use wc_maybe_reduce_stock_levels instead?

### Actual behavior

Stock is reduced twice. Order note shows the order is switched twice from “Pending” to “Processing” too - example screenshot next.

### Screenshots

2dQOJB

### Expected behavior

Stock is reduced only once. Order status is only updated once.

### Additional context

* [WordPress.org forum thread](https://wordpress.org/support/topic/duplicate-stock-reduction-from-one-payment/)
* Ticket 4439221-zd-woothemes
* P2 for a customer affected: pcJe93-1o-p2#comment-612 - this P2 also explains why this is being prioritized high.

### PR DESCRIPTION
**Pull request by malithsen**
When the intent success webhook is received while processing the original request, it may result in duplicate `payment_complete` calls due to a race condition. This causes `woocommerce_order_status_processing` hook to fire twice resulting in duplicated emails, status change notes, and stock reductions.
Status checks introduced in #3287 alleviate the problem but race conditions still happen in the following scenario

1. Initial order processing starts. `process_payment()`->`process_payment_for_order`->`attach_intent_info_to_order`->`order->payment_complete`.
2. In parallel, `payment_intent.succeeded` webhook is received and we call `process_webhook_payment_intent_succeeded` -> `order->payment_complete`
3. Before we could update the order status to `processing` within the first `payment_complete` call, we pass through [this](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/admin/class-wc-rest-payments-webhook-controller.php#L304) status check introduced in #3287

Fixes #3345 

#### Changes proposed in this Pull Request

This change proposes mutexing `payment_complete` calls. A lock is placed before calling `payment_complete` in both above instances, which stops further processing if another attempt is made before unlocking or within five minutes of the initial call. Same approach is being used in [Stripe Gateway](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/trunk/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L1505) to get around similar concurrency issues

#### Testing instructions

1. Listen to webhooks. `npm run listen` in your local server.
2. Enable UPE
3. To simulate the race condition, put a conditional `sleep` in woocommerce core `payment_complete` function. So that `payment_complete` invoked by webhook starts but doesn't change the status until the other request completes.
<details>
<summary> This is what I used </summary>

```
	public function payment_complete( $transaction_id = '' ) {
		if ( ! empty( $transaction_id ) ) {
			sleep(10);
		}
		if ( ! $this->get_id() ) { // Order must exist.
			return false;
		}

		try {
                .........
```
</details>

4. Notice that duplicated status changes in `develop` branch and no only one status change in this PR's branch

#### Additional Context

Previous attempt: https://github.com/Automattic/woocommerce-payments/pull/3399

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

File: includes/class-wc-payments-utils.php [hunk 1]
```diff
@@ -583,4 +583,37 @@ public static function get_cached_minimum_amount( $currency ) {
 		$cached = get_transient( 'wcpay_minimum_amount_' . strtolower( $currency ) );
 		return (int) $cached ? (int) $cached : null;
 	}
+
+	/**
+	 * Locks an order for payment intent processing for 5 minutes.
+	 *
+	 * @param WC_Order $order  The order that is being paid.
+	 * @param string   $intent_id The id of the intent that is being processed.
+	 * @return bool            A flag that indicates whether the order is already locked.
```
Comment (chickenn00dle) [inline includes/class-wc-payments-utils.php:592]: Remove spacing or align descriptions.

File: includes/class-wc-payments-utils.php [hunk 2]
```diff
@@ -583,4 +583,37 @@ public static function get_cached_minimum_amount( $currency ) {
...
+
+		// Block the process if the same intent is already being handled.
+		if ( '-1' === $processing || ( isset( $intent_id ) && $processing === $intent_id ) ) {
+			return true;
+		}
+
+		// Save the new intent as a transient, eventually overwriting another one.
+		set_transient( $transient_name, empty( $intent_id ) ? '-1' : $intent_id, 5 * MINUTE_IN_SECONDS );
+
+		return false;
```
Comment (chickenn00dle) [inline includes/class-wc-payments-utils.php:607]: It seems a bit counterintuitive to me to return false after successfully locking, and true when locking fails. At least in the context of calling a method named `lock_order_payment`. 

It might be helpful if we either:

- rename this method to make it more clear that it is both checking and locking, or
- separate the checking functionality from the locking functionality

**Review by chickenn00dle — CHANGES_REQUESTED** [review]
Nice work @malithsen 👍 

I tested and this fixes the duplicate status note issue.

I just had two small comments, then this looks like it is good to go.

File: includes/admin/class-wc-rest-payments-webhook-controller.php [hunk 3]
```diff
@@ -301,15 +301,16 @@ private function process_webhook_payment_intent_succeeded( $event_body ) {
 		// Get an updated set of order properties to avoid race conditions when the server sends the paid webhook before we've finished processing the original payment request.
 		$order->get_data_store()->read( $order );
 
-		// prevent parallel order processing attempts.
-		if ( WC_Payments_Utils::lock_order_payment( $order, $intent_id ) ) {
+		if ( $order->has_status( [ 'processing', 'completed' ] ) ) {
```
Comment (malithsen) [inline includes/admin/class-wc-rest-payments-webhook-controller.php:304]: This check is no longer needed with locks introduced in this PR but in some cases, this would allow us to bail early without having to place locks, so decided to keep it.

File: includes/class-wc-payments-utils.php (hunk 2 above)
Comment (malithsen) [reply includes/class-wc-payments-utils.php]: Agree on return values @chickenn00dle 
I couldn't think of a situation where we'd want to check for a lock without immediately placing the lock, so was initially leaning against splitting `lock_order_payment`. But then again, coming up with a clearer function name was more difficult, so decided to go with splitting the function 😄 
This is adjusted in https://github.com/Automattic/woocommerce-payments/pull/3520/commits/d4ee61156db4327ce654916c7d7f75800984d07c

File: includes/class-wc-payments-utils.php (hunk 1 above)
Comment (malithsen) [reply includes/class-wc-payments-utils.php]: Fixed in https://github.com/Automattic/woocommerce-payments/pull/3520/commits/d4ee61156db4327ce654916c7d7f75800984d07c

**Review by chickenn00dle — APPROVED** [review]

**Comment by chickenn00dle** [comment]
Thanks for addressing the feedback @malithsen 

This LGTM 👍

**Comment by malithsen** [comment]
Hi @james-allan as Axiom is still getting familiar with WCPay, we request an additional review from another team. Since it looks like you're familiar with this issue, I added you as a reviewer. Please let me know if I should assign it to someone else instead.

File: includes/admin/class-wc-rest-payments-webhook-controller.php [hunk 4]
```diff
@@ -301,9 +301,18 @@ private function process_webhook_payment_intent_succeeded( $event_body ) {
 		// Get an updated set of order properties to avoid race conditions when the server sends the paid webhook before we've finished processing the original payment request.
 		$order->get_data_store()->read( $order );
 
-		if ( ! $order->has_status( [ 'processing', 'completed' ] ) ) {
-			$order->payment_complete();
+		if ( $order->has_status( [ 'processing', 'completed' ] ) ) {
+			return;
 		}
+
+		// prevent parallel order processing attempts.
```
Comment (james-allan) [inline includes/admin/class-wc-rest-payments-webhook-controller.php:308]:
```suggestion
		// Prevent parallel order processing attempts.
```

Tiniest of nitpicks here.

File: includes/admin/class-wc-rest-payments-webhook-controller.php [hunk 5]
```diff
@@ -301,9 +301,18 @@ private function process_webhook_payment_intent_succeeded( $event_body ) {
 		// Get an updated set of order properties to avoid race conditions when the server sends the paid webhook before we've finished processing the original payment request.
 		$order->get_data_store()->read( $order );
```
Comment (james-allan) [inline includes/admin/class-wc-rest-payments-webhook-controller.php:302]: I'm wondering if we can get rid of this now or do you think it's still valuable? Originally I added this right before the status check so we get the most recent up to date status incase it was processed via a different request already. If we're going to be locking the order via a transient, then that might not be needed anymore.

Comment (james-allan) [reply includes/admin/class-wc-rest-payments-webhook-controller.php:302]: I just realised this question might tie into your reasoning behind keeping the status check below.

**Comment by james-allan** [comment]
The changes look good to me @malithsen. I left a question and a tiny, tiny suggestion. :)

**Review by james-allan — CHANGES_REQUESTED** [review]

File: includes/admin/class-wc-rest-payments-webhook-controller.php (hunk 5 above)
Comment (malithsen) [reply includes/admin/class-wc-rest-payments-webhook-controller.php:302]: > I just realised this question might tie into your reasoning behind keeping the status check below.

That's correct, I don't have a strong opinion against removing the status check and associated code, opted to keep it as an additional check that bails out a little early. I also don't know whether the extra read has a measurable impact on performance. Happy to get rid of it if you think it has a negative impact :)

File: includes/admin/class-wc-rest-payments-webhook-controller.php (hunk 4 above)
Comment (malithsen) [reply includes/admin/class-wc-rest-payments-webhook-controller.php]: Updated in https://github.com/Automattic/woocommerce-payments/pull/3520/commits/caed1c36cabe9c5b2dc7b351ac9a317602ccd12a. Thanks!

File: includes/admin/class-wc-rest-payments-webhook-controller.php (hunk 5 above)
Comment (james-allan) [reply includes/admin/class-wc-rest-payments-webhook-controller.php:302]: yeah that's all good. 

I don't think it has a measurable impact. There are a lot of order reads that happen in each request so this would be very minor in the grand scheme of things. I also cannot simulate potential scenarios where this would be good, bad or indifferent. Happy to err on the side of caution and keep it. :)

**Comment by malithsen** [comment]
Hi @james-allan Thanks for the review. Can you please approve if this is all good now :)

**Review by james-allan — APPROVED** [review]

**Comment by james-allan** [comment]
> Hi @james-allan Thanks for the review. Can you please approve if this is all good now :)

Sorry I missed this. Approved now :)
