### PR TITLE
Reporting: Fix spelling of `Payments` to `Payment`

### LINKED ISSUE #8629: [Task] - Fix spelling `Payments` to `Payment`
Within the `Payment activity widget` reporting project code, there were instances of `Payment` being written as `Payments` ( e.g. `Payments activity widget` , `Total payments volume`).  It was clarified that `Payment` ( singular ) aligns with better grammar and industry. 

We need to reword `Payments` as `Payment` where applicable. 

### Additional context
p1712902420879839-slack-C06BBFTF6EM

Related Server PR : https://github.com/Automattic/woocommerce-payments-server/pull/5146

### PR DESCRIPTION
**Pull request by nagpai**
Fixes #8629 

#### Changes proposed in this Pull Request

Change the spelling of `Payments` to `Payment` ( singular ), to align with industry lingo and grammar. 

#### Testing instructions
* Visual - The Payment activity widget should look and work exactly how it did, with the expected spelling change.
* All existing unit tests should pass.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8630` or branch name `update/rename-payment-activity-singular` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/rename-payment-activity-singular) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: cfc0d70fbaa892e02aac86e28bab0edcd51c81b5
- Build time: 2024-04-17 06:07:08 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: changelog/update-rename-payment-activity-singular [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: update
+
+Update: Fixed spelling of `Payments` to `Payment`. Changes are behind a feature flag.
```
Comment (shendy-a8c) [inline changelog/update-rename-payment-activity-singular]: IMO, since code has not been released yet, any modification to it does not need a visible changelog, so this should be just a comment that will not generate a changelog entry.

**Review by shendy-a8c — APPROVED** [review]
Looks good.
- I checked that UI does not have any 'payments'.
- No build error.
- Tests are all green.
- Ran `find client -iname '*payments*'` and found no files related to reporting with 'payments'.

I have minor comment about changelog. Approving for now.

Also, need to inform the others @Automattic/helix so we're all aligned with this commitment to use singular term of 'payment' instead of payments in the existing open and future PRs.

File: changelog/update-rename-payment-activity-singular (hunk 1 above)
Comment (haszari) [reply changelog/update-rename-payment-activity-singular]: I agree, this change should be covered by changelog item for the feature (behind flag).

File: client/components/payment-activity/payment-activity-data.tsx [hunk 2]
```diff
@@ -76,8 +76,8 @@ const PaymentsActivityData: React.FC = () => {
 						type_is: 'refund',
 					} ) }
 				/>
-				<PaymentsDataTile
-					id="wcpay-payments-data-highlights__disputes"
+				<PaymentDataTile
+					id="wcpay-payment-data-highlights__disputes"
```
Comment (haszari) [inline client/components/payment-activity/payment-activity-data.tsx:80]: I ❤️ the way you've corrected this in all the under-the-hood places too (CSS classes, variable names etc) 🙌🏻

File: changelog/update-rename-payment-activity-singular (hunk 1 above)
Comment (nagpai) [reply changelog/update-rename-payment-activity-singular]: @shendy-a8c  - Sorry about a silly question here. When we say `this should be just a comment`,  can you give me an example? Do I remove this changelog file, or probably say `Comment: This related to PR #--- and contains some minor spelling corrections on top of it`. I want to be sure I am doing this correctly.

File: client/components/payment-activity/payment-activity-data.tsx (hunk 2 above)
Comment (nagpai) [reply client/components/payment-activity/payment-activity-data.tsx:80]: Thanks, @haszari 🙌 . There is one more change to rename `total_payments_volume` on the server side, for which I will create a low priority issue and assign it to myself. It will require a very small but simultaneous change on the server and in the client. I will discuss this with the team regarding the best time and way to do it, and have it actioned.

**Comment by nagpai** [comment]
~I will merge this PR after accounting for changes within #8589~

Got some good directions from @jessy-p . Merging this first, since #8559 has some more work to be completed.

File: client/components/payment-activity/payment-activity-data.tsx (hunk 2 above)
Comment (nagpai) [reply client/components/payment-activity/payment-activity-data.tsx:80]: I have the PR on the server ready :) - https://github.com/Automattic/woocommerce-payments-server/pull/5146 

I have pushed the related changes for client on this PR too 
https://github.com/Automattic/woocommerce-payments/pull/8630/commits/1d586031ae3e76888042afabded4b98d0ef39ce2

File: changelog/update-rename-payment-activity-singular (hunk 1 above)
Comment (shendy-a8c) [reply changelog/update-rename-payment-activity-singular]: Sorry for being ambiguous.

> or probably say Comment: This related to PR #--- and contains some minor spelling corrections on top of it.

☝️ This is what I meant.

Here's how I usually did it:
```
% npm run changelog

> woocommerce-payments@7.4.0 changelog
> ./vendor/bin/changelogger add

Name your changelog file [default: add-8519-reporting-api-to-component] > abc
Significance of the change, in the style of semantic versioning.
  [patch] Backwards-compatible bug fixes.
  [minor] Added (or deprecated) functionality in a backwards-compatible manner.
  [major] Broke backwards compatibility in some way.
 > patch
Type of change.
  [add   ] Add
  [fix   ] Fix
  [update] Update
  [dev   ] Dev
 > dev
Changelog entry. May be left empty if this change is particularly insignificant.
 > 
You omitted the changelog entry, which is fine. But please comment as to why no entry is needed.
 > type test comment here
```

Comment (nagpai) [reply changelog/update-rename-payment-activity-singular]: Ah! Thanks for explaining this in detail, @shendy-a8c 🙏! I never reached the comment prompt on the npm run changelog :D . It is very clear now!
