### PR TITLE
fix: enable first-party auth for stores with adapted extensions

### LINKED ISSUE #9370: Enable first party auth for stores running adapted extensions
### Describe the bug
Currently any store that installs the [WooCommerce Points and Rewards](https://woocommerce.com/products/woocommerce-points-and-rewards/) or [WooCommerce Gift Cards](https://woocommerce.com/products/gift-cards/) plugins will get the First Party checkout disabled. Meaning that their customers will see an OTP modal before getting forwarded to WooPay.

After the latest changes I believe that both extensions fully work with the First Party Flow.

I've run some quick tests and those extensions seemed to work as expected. I did see point being accumulated and being used and gift cards were sent and could be used on new purchases.

### To Reproduce
- Change [this line](https://github.com/Automattic/woocommerce-payments-server/blob/5b0af019232ea8d3ab797efc1eef38e41fec8105/server/wp-content/rest-api-plugins/endpoints/wcpay/woopay/class-woopay-controller.php#L55) in your server to:
``` 
$adapted_extensions      = [ "woocommerce-points-and-rewards", "woocommerce-gift-cards" ];
```
- On your merchant site manually run the `validate_incompatible_extensions` scheduled action
- This will update the list of extensions that only work with the OTP flow
- On your merchant site Install Points and Rewards and/or Gift Cards
- This will execute [this function](https://github.com/Automattic/woocommerce-payments/blob/163b12207971cd2ed674ee6da8af1bb4544145bf/includes/woopay/class-woopay-scheduler.php#L117) which will disable the First Party Flow
- As a shopper add a product to your cart and checkout using the WooPay button
- The OTP modal will show up

### Expected behavior
Both extensions should not disable the WooPay First Party Flow and should work via this flow just as they work now with the OTP flow.

### Context
This is how those extensions got added to the Direct Checkout flow
2692-gh-Automattic/woopay

### PR DESCRIPTION
**Pull request by pierorocca**
The WooPay scheduler was disabling first-party auth whenever adapted extensions (Points & Rewards, Gift Cards) were active. These extensions are compatible with the first-party flow — they have their own email verification logic and the WooPay server already handles their data securely for unverified users.

This removes the first-party auth flag toggling from the scheduler and adds a one-time migration on plugin update to delete the stale option, letting it fall back to its default of enabled.

Fixes: https://github.com/Automattic/woocommerce-payments/issues/9370

Fixes: https://github.com/Automattic/woopay/issues/2216

#### Testing instructions

Local Dev Testing -> https://github.com/Automattic/woocommerce-payments/pull/11385#issuecomment-3941586060

### Testing

1. Set `_wcpay_feature_woopay_first_party_auth` to `0` and enable adapted extensions
2. Trigger the daily scheduler — verify the flag is **not** changed (scheduler no longer manages it)
3. Simulate a plugin update (`do_action('woocommerce_woocommerce_payments_updated')`) — verify the option is deleted
4. Confirm the WooPay **Button** checkout uses first-party auth flow (no OTP modal) on a store with Points & Rewards or Gift Cards active

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

https://github.com/user-attachments/assets/fedf0942-82b6-4055-95bf-2cef9cd5067c

### CODE REVIEW

**Comment by pierorocca** [comment]
## Detailed Rationale

### The Problem

When merchants install adapted extensions (WooCommerce Points & Rewards or Gift Cards), the `WooPay_Scheduler::update_enabled_adapted_extensions()` method unconditionally sets `_wcpay_feature_woopay_first_party_auth` to `0`. This disables the first-party auth flow for **all** customers on that store, forcing them through the third-party OTP modal — even though these extensions are fully compatible with first-party checkout.

### Why Adapted Extensions Don't Need to Block First-Party Auth

"Adapted" extensions are plugins that have been specifically integrated to work with WooPay. They have their own email verification mechanisms that operate independently of the auth flow:

- **Points & Rewards**: Sets `should_verify_email = true` only when the user has redeemable points and is a guest. The WooPay server zeros out `points_available` for unverified emails (`BlocksIntegration.php:247`), preventing data leakage.
- **Gift Cards**: Sets `should_verify_email = true` only when the guest user has a positive gift card balance on the merchant store.

In both cases, the WooPay server already provides OTP nonces for **in-checkout** email verification when needed (`BlocksIntegration.php:252-261`). This works regardless of whether the session was established via first-party auth or OTP.

### The Session Data Flow is Already Auth-Agnostic

The adapted extensions data pipeline is identical between both auth flows:

1. **Merchant** → calls `get_init_session_request()` which populates `adapted_extensions` and `extension_data`
2. **WooPay server** → `SessionController.php:268` stores adapted extensions in session
3. **Checkout rendering** → `BlocksIntegration.php:240-261` reads from session, passes to frontend, and provides email verification nonces when needed

No code changes are needed on the WooPay server side — the infrastructure already supports first-party auth with adapted extensions.

### What This PR Changes

1. **Removes the first-party auth flag toggling** from `update_enabled_adapted_extensions()` — the scheduler no longer disables first-party auth when adapted extensions are active.

2. **Adds a one-time migration** (`remove_first_party_auth_flag_on_update`) hooked into `woocommerce_woocommerce_payments_updated` — this deletes the stale `_wcpay_feature_woopay_first_party_auth` option on existing stores that were previously affected. The option defaults to `'1'` (enabled) when absent, so deleting it restores correct behavior.

This follows the same pattern as the existing `remove_legacy_schedule_action_name_on_update` migration.

### Testing

1. Set `_wcpay_feature_woopay_first_party_auth` to `0` and enable adapted extensions
2. Trigger the daily scheduler — verify the flag is **not** changed (scheduler no longer manages it)
3. Simulate a plugin update (`do_action('woocommerce_woocommerce_payments_updated')`) — verify the option is deleted
4. Confirm the WooPay checkout uses first-party auth flow (no OTP modal) on a store with Points & Rewards or Gift Cards active

**Comment by pierorocca** [comment]
## Local Testing Instructions

Since the `get_woopay_compatibility` API returns empty in local dev, use these manual steps to verify the fix.

### Test 1: Adapted extensions no longer disable first-party auth

```bash
# Set first-party auth to enabled
docker exec woopay_wordpress wp option update _wcpay_feature_woopay_first_party_auth 1 --allow-root

# Call update_enabled_adapted_extensions directly and verify it doesn't touch first-party auth
docker exec woopay_wordpress wp eval '
$scheduler = new \WCPay\WooPay\WooPay_Scheduler(\WC_Payments::get_payments_api_client());
$scheduler->update_enabled_adapted_extensions(
    ["woocommerce-gift-cards/woocommerce-gift-cards.php"],
    ["woocommerce-gift-cards"]
);
echo "_wcpay_feature_woopay_first_party_auth = " . get_option("_wcpay_feature_woopay_first_party_auth", "not set") . "\n";
echo "woopay_enabled_adapted_extensions = " . json_encode(get_option("woopay_enabled_adapted_extensions", [])) . "\n";
' --allow-root
```

**Expected:** `_wcpay_feature_woopay_first_party_auth = 1` (unchanged), `woopay_enabled_adapted_extensions = ["woocommerce-gift-cards"]`

### Test 2: Migration cleans up stores stuck with first-party auth disabled

```bash
# Simulate a store stuck with first-party auth disabled by the old scheduler
docker exec woopay_wordpress wp option update _wcpay_feature_woopay_first_party_auth 0 --allow-root

# Run the one-time migration method
docker exec woopay_wordpress wp eval '
$scheduler = new \WCPay\WooPay\WooPay_Scheduler(\WC_Payments::get_payments_api_client());
$scheduler->remove_first_party_auth_flag_on_update();
echo "_wcpay_feature_woopay_first_party_auth = " . var_export(get_option("_wcpay_feature_woopay_first_party_auth"), true) . "\n";
' --allow-root
```

**Expected:** `_wcpay_feature_woopay_first_party_auth = false` (option deleted, falls back to default `1` / enabled)

### Test 3: End-to-end checkout (optional)

1. Set `_wcpay_feature_woopay_first_party_auth` to `1`
2. Set `woopay_enabled_adapted_extensions` to `["woocommerce-gift-cards"]`
3. Go through a WooPay checkout on localhost
4. Verify you get the **iframe-based** first-party auth flow instead of the OTP modal

**Comment by pierorocca** [comment]
## Addressing Copilot feedback

All three low-confidence suggestions have been addressed in b7f53adfa:

**1. Unused `pre_option_active_plugins` filter in test (line 244)**
Removed the filter setup and teardown. Since `update_enabled_adapted_extensions()` takes an explicit `$active_plugins` parameter, the mocked option was never read.

**2. Missing default fallback assertion in migration test (line 266)**
Added `$this->assertEquals( '1', get_option( '_wcpay_feature_woopay_first_party_auth', '1' ) )` to verify that after deletion, reading the option with the default `'1'` returns the expected enabled value.

**3. Hard-coded option name string (line 90)**
Replaced `'_wcpay_feature_woopay_first_party_auth'` with `\WC_Payments_Features::WOOPAY_FIRST_PARTY_AUTH_FLAG_NAME` to keep the flag name centralized and avoid drift.

**Comment by rtio** [comment]
Can we not tag people directly? Use `Automattic/gamma` instead. Also, is this PR ready for review? This is marked as draft. I have removed the reviewers, when the PR is ready please use `Automattic/gamma` or `Automattic/chronos`

**Comment by pierorocca** [comment]
Thanks for the education @rtio. It's ready for review. I missed this one. Lower priority on this over pressing work.

**Comment by pierorocca** [comment]
## 🤖 Automated Review Report

**Date:** 2026-03-06 | **Commits:** `52883f0`, `e0e6095`, `b7f53ad`

### Overall Verdict: REQUEST CHANGES

The change is clean and well-scoped — it removes an outdated feature-flag toggle and adds a one-time migration. One convention issue in the test file should be addressed before merge; several test coverage improvements are recommended.

---

### Architecture Compliance — FLAG

- **[FLAG] Magic string in tests instead of constant** — `tests/unit/woopay/class-woopay-scheduler-test.php:240,245,253,258,259`. Both new test methods use the raw string `'_wcpay_feature_woopay_first_party_auth'` while production code correctly references `\WC_Payments_Features::WOOPAY_FIRST_PARTY_AUTH_FLAG_NAME`. If the constant value changes, tests would silently operate on a stale key.
- **[INFO]** Test class extends `WP_UnitTestCase` instead of `WCPAY_UnitTestCase` — pre-existing issue, not introduced by this PR.
- **[PASS]** Migration hook uses `woocommerce_woocommerce_payments_updated` — standard pattern.
- **[PASS]** Production code uses the constant correctly.
- **[PASS]** Removal from `update_enabled_adapted_extensions` is clean and narrowly scoped.
- **[PASS]** No payment flow layer violations.
- **[PASS]** Changelog entry is correct.

---

### Security — PASS

- **[Low]** `delete_option()` silently removes the auth flag without logging the previous value. Consider adding `Logger::info()` for audit trail.
- **[Info]** `woocommerce_woocommerce_payments_updated` is a WooCommerce lifecycle hook — CSRF/nonce not applicable.
- **[Info]** Default value verified: `is_woopay_first_party_auth_enabled()` returns `'1' === get_option(..., '1')`, so deletion correctly defaults to enabled.

---

### Performance — PASS

- **[Positive]** Eliminated redundant `update_option()` on every daily cron tick, plugin activation, and deactivation.
- **[Positive]** Replacement is a single `delete_option()` on plugin update — rare, admin-only, zero checkout impact.
- **[Positive]** Removes option from autoloaded set, reducing bootstrap payload.

---

### Test Coverage — FLAG

**Coverage:** 1 modified production file, 1 test file updated with 2 new tests.

**Missing tests:**
1. Hook registration not verified — no `has_action()` assertion for `remove_first_party_auth_flag_on_update`.
2. Option-already-absent case — no test for stores never affected by old scheduler.
3. Option previously set to `0` — test pre-sets to `1`, but `0` is the real migration scenario.

**Quality issue:** Redundant assertion `assertEquals('1', get_option(..., '1'))` only proves WordPress core behavior, not scheduler behavior.

---

### Required Changes

1. **Use constant in tests** — Replace raw `'_wcpay_feature_woopay_first_party_auth'` with `\WC_Payments_Features::WOOPAY_FIRST_PARTY_AUTH_FLAG_NAME` in both new test methods.

### Suggestions (Non-blocking)

1. Migrate `WooPay_Scheduler_Test` to extend `WCPAY_UnitTestCase` (pre-existing, could be separate PR).
2. Add test for hook registration in `init()`.
3. Add test with option pre-set to `0` to prove `update_enabled_adapted_extensions` no longer writes to the flag.
4. Remove the redundant `assertEquals('1', get_option(..., '1'))` assertion.
5. Consider logging the flag deletion for audit trail.

**Comment by pierorocca** [comment]
## Review findings addressed in `66c75de`

| # | Finding | Action |
|---|---------|--------|
| 1 | Magic string in tests instead of constant | Fixed — replaced with `WC_Payments_Features::WOOPAY_FIRST_PARTY_AUTH_FLAG_NAME` |
| 2 | Missing test for option pre-set to `0` (real migration scenario) | Fixed — added `test_adapted_extensions_do_not_reenable_first_party_auth` |
| 3 | Missing hook registration test | Fixed — added `test_init_registers_remove_first_party_auth_flag_hook` |
| 4 | Redundant assertion testing WordPress core behavior | Fixed — simplified to `assertSame( false, get_option(...) )` |

File: includes/woopay/class-woopay-scheduler.php [hunk 1]
```diff
@@ -48,6 +48,7 @@ public function init() {
 		add_action( 'activated_plugin', [ $this, 'show_warning_when_incompatible_extension_is_enabled' ] );
 		add_action( 'deactivated_plugin', [ $this, 'hide_warning_when_incompatible_extension_is_disabled' ] );
 		add_action( 'woocommerce_woocommerce_payments_updated', [ $this, 'remove_legacy_schedule_action_name_on_update' ] );
+		add_action( 'woocommerce_woocommerce_payments_updated', [ $this, 'remove_first_party_auth_flag_on_update' ] );
```
Comment (htdat) [inline includes/woopay/class-woopay-scheduler.php:51]: We do not need this action for every update. Instead, we can completely remove feature flag `WOOPAY_FIRST_PARTY_AUTH_FLAG_NAME`

**Review by htdat — APPROVED** [review]
I reviewed the PR as well as check the git history https://gist.github.com/htdat/1b1bf32e5854cb3fe1678981d1f404fb 

Confirm that with this PR, the adapted extensions, such as Points & Rewards, Gift Cards, will not disable the first-party auth.

Instead, I have only one comment above to further remove this feature flag https://github.com/Automattic/woocommerce-payments/pull/11385#discussion_r2905476919. I applied this commit 41976dffa6dc425d7a659adcfc29ad59c59d6836 for that purpose

File: includes/woopay/class-woopay-scheduler.php (hunk 1 above)
Comment (htdat) [reply includes/woopay/class-woopay-scheduler.php:51]: Fixed with 41976dffa6dc425d7a659adcfc29ad59c59d6836
