### PR TITLE
Fix flash of WooCommerce Payments gateway title name.

### LINKED ISSUE #2891: Hide incorrect default payment gateway title on page load
### Describe the bug

> We’ve received feedback from a user who claims that the UPE is displayed as WooCommerce Payments on checkout. 
> 
> "Changing the payment gateway name to \“Woocommerce Payments\” is confusing my customers who think they need to  have a woocommerce account to pay with this method. Please change it or allow us to change it."

If there's a single payment method enabled, the gateway is titled after the name of that payment method; if there are multiple methods enabled, we title the gateway "Popular payment methods". However, we need to filter enabled payment methods by currency first to figure out which payment methods are enabled, so while that is happening, there is a brief flicker state, where the title uses the default value from the gateway's title property.

A WC payment gateway has two title properties: `method_title` and `title.` `method_title` is the main title, while `title` is a subtitle and the title at checkout. 

Payment gateway titles in settings
_Payment gateway titles in settings_

If `method_title` and `title` have the same value, that subtitle gets hidden. This is the existing and desired functionality for this title and consequently the default checkout title takes this value ("WooCommerce Payments").

Hidden gateway title
_Gateway title/subtitle is hidden_

The goal here is to hide this temporary gateway title until we have the correct value, after checking whether multiple payment methods are enabled. This cannot be triggered by JS, because the gateway title appears before any of our scripts are queued and loaded in the page. Consequently, I think the only way this can be achieved is to hide the element with CSS. Below is an example of what that would look like.

Hiding gateway title
_Using CSS to hide gateway title while preloading_

I have created a draft PR at #2892, which shows an example of how this could be implemented. However, due to the way that webpack scripts and stylesheets are loaded, the UPE gateway and legacy gateway share the same stylesheets. We need to hide the gateway title when the UPE is enabled, but we must not hide it when the legacy gateway is enabled. This is not yet resolved in the aforementioned gateway, since the SCSS file that hides the gateway title is loaded for both payment gateways. 

### To Reproduce

1. Enable UPE and visit checkout.
2. Notice that while payment gateway is in preloading state, while initial payment intent is being created, gateway is titled "WooCommerce Payments".
3. User should ideally not ever see "WooCommerce Payments" at checkout.

### Actual behavior

User briefly sees "WooCommerce Payments" as UPE gateway title, while gateway is in preloading state.

### Expected behavior

User should never see "WooCommerce Payments" as a gateway title at checkout.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

Relevant Slack thread: p1630332366014100-slack-C02BHNRN6R1

### PR DESCRIPTION
**Pull request by jessepearson**
Fixes #2891 

#### Changes proposed in this Pull Request

* Add filter for `woocommerce_gateway_title` to call `maybe_filter_gateway_title`.
* `maybe_filter_gateway_title` checks to see if it's our gateway and default title being used, if so it then assigns the new title with the value of `checkout_title` (Popular payment methods). From there it checks to see if there is 1 available method, and it will assign that method's title if so. If there are 0 methods available, it assigns the `card` method's title.

#### Testing instructions

* Make sure UPE is enabled.
* Add card and 1 other UPE method.
* Add item to cart and go to checkout.
* Use Multi-Currency widget and set currency to EUR.
* When the page reloads, the `Popular payment methods` title should show for the payment method, without a flash of WooCommerce Payments.
* Go to Payments > Settings and remove the card method, leaving a UPE method.
* Go back to checkout.
* When the page reloads, the payment title should show the name of the method you selected, without a flash of WooCommerce Payments.
* Go to Payments > Settings and add the card method back also leaving a UPE method.
* Go back to checkout.
* Use Multi-Currency widget and set currency to USD.
* When the page reloads, the `Credit card / debit card` title should show for the payment method, without a flash of WooCommerce Payments. Other UPE method should not be available.

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

**Comment by jessepearson** [comment]
@FangedParakeet Do you think this will work for the flash of WooCommerce Payments issue?

File: includes/payment-methods/class-upe-payment-gateway.php [hunk 1]
```diff
@@ -835,6 +839,30 @@ public function clear_upe_appearance_transient() {
...
+	/**
+	 * Sets the title on checkout correctly before the title is displayed.
+	 *
+	 * @param {string} $title The title of the gateway being filtered.
+	 * @param {string} $id    The id of the gateway being filtered.
+	 *
+	 * @return string Filtered gateway title.
+	 */
+	public function maybe_filter_gateway_title( $title, $id ) {
+		if ( self::GATEWAY_ID === $id && $this->title === $title ) {
```
Comment (FangedParakeet) [inline includes/payment-methods/class-upe-payment-gateway.php:851]: This check for `$this->title === $title` is probably a little redundant, but eh, better safe than sorry, I suppose!

**Review by FangedParakeet — APPROVED** [review]
Nice one! I tried a million uglier ways to accomplish this before that were all much less successful than this one. I should've known better to go hunting for a hook: I think this is definitely the best solution to dynamically title the payment gateway. Glad we can finally bury this issue in the dirt.

LGTM, approved.

File: includes/payment-methods/class-upe-payment-gateway.php (hunk 1 above)
Comment (jessepearson) [reply includes/payment-methods/class-upe-payment-gateway.php:851]: Ya, I thought about others that might be using the filter, or if the string is translated, etc, and I didn't want to override an override.

File: includes/payment-methods/class-upe-payment-gateway.php [hunk 2]
```diff
@@ -875,6 +879,30 @@ public function clear_upe_appearance_transient() {
 		delete_transient( self::UPE_APPEARANCE_TRANSIENT );
 	}
 
+	/**
+	 * Sets the title on checkout correctly before the title is displayed.
+	 *
+	 * @param {string} $title The title of the gateway being filtered.
```
Comment (dmallory42) [inline includes/payment-methods/class-upe-payment-gateway.php:885]: Nitpick: The format for docblocks is slightly different from what I've seen elsewhere in the codebase, perhaps we should update it here to ensure it is standardised? This is what I normally see (the only difference being the lack of `{ }` surrounding the type. I think that may be a JS convention!

```
* @param string $title The title of the gateway being filtered
```

**Review by dmallory42 — APPROVED** [review]
LGTM and works as described! 🚢 

Added a few small nitpicks but nothing to stop this being approved!

File: includes/payment-methods/class-upe-payment-gateway.php (hunk 2 above)
Comment (jessepearson) [reply includes/payment-methods/class-upe-payment-gateway.php]: I noticed the different format and copied it rather than asking about if they should be changed. Thanks for the nitpick, I just updated them. https://github.com/Automattic/woocommerce-payments/pull/3335/commits/fa7b2f00c0132107d75941442de0565889424af7
