### PR TITLE
Fixes Empty Alert When Refunding Authorization Charge

### LINKED ISSUE #741: Empty alert and stripe url in order note on attempting to refund an authorization
If you attempt to refund an authorization (Refund $X via WooCommerce Payments), you get the following:

empty-alert

stripe-url-in-order-note

We should probably not attempt to refund authorizations, direct the user to cancel them via order actions in that alert instead (and avoid the order note with the stripe url as a result)

### PR DESCRIPTION
**Pull request by dmallory42**
Fixes #741 

#### Changes proposed in this Pull Request

* Update to the `process_refund` logic to do a check to see if an order has not yet been charged (if it is still in authorization stage). If this is the case, instead of doing the refund, redirect the user to instead cancel the order via the 'Order actions' menu.

#### Testing instructions

* Navigate to `Payments -> Settings` and turn 'Manual Capture' **on**.
* As a customer, make a test order (it doesn't matter what is ordered).
* Navigate to `WooCommerce -> Orders` and click into the order that was created.
* Click the 'Refund' button, then 'Refund via WooCommerce'.
* On `trunk`, an empty alert should appear and an Order Note with the error message should be created. On this branch, an alert should pop up informing the user an authorization cannot be refunded, and directing them to the order actions menu should appear, and no note should be created.

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -761,6 +761,11 @@ public function process_refund( $order_id, $amount = null, $reason = '' ) {
 			return false;
 		}
 
+		// If this order is not authorized yet, don't try and refund it. Instead, return an appropriate error message.
+		if ( 'requires_capture' === $order->get_meta( '_intention_status', true ) ) {
+			return new WP_Error( 'on-hold-payment', "As this payment is currently on-hold and has not been charged yet, it is not possible to refund this order. To cancel this order, use the 'Cancel Authorization' option in the 'Order Actions' drop-down menu." );
```
Comment (dmallory42) [inline includes/class-wc-payment-gateway-wcpay.php:766]: I wasn't sure on the best wording for this error message, so if anyone has any suggestions they'd be appreciated! :)

Comment (shendy-a8c) [reply includes/class-wc-payment-gateway-wcpay.php:762]: Good start!

Here are my feedbacks:
- I think 'on hold' is the status of the order, not the payment. If my assumption is correct, then the error code might be better to be `uncaptured-payment`.
- I think it's better to use the term 'authorized' and 'captured' because the option from the settings page is called 'Manual capture', so the user would know what's going on if we use that term. The order note also emphasizes those two terms.
- The user reaches this point because they want to make a refund (could be partial, could be in full amount) and that does not always mean they want to cancel the order. In the case where they want to make partial refund, it might be best to direct them to capture the payment first and then refund. For full refund, suggest to cancel authorization.
- Wrap the string with `__()` for localization. As an example, [you can find from the same file](https://github.com/Automattic/woocommerce-payments/pull/1192/files#diff-bcfd303d507c33a27671935e724ee64d0df30ff2a18bb6ef4c94f28d48190124R792-R793).

I'm not sure what the text copy should be, but if I have to come up with one, I'd use this:
```
This payment is not captured yet. To proceed with a refund, from 'Order Actions', either 'Capture charge' or 'Cancel authorization'.
```

**Review by shendy-a8c — CHANGES_REQUESTED** [review]

File: includes/class-wc-payment-gateway-wcpay.php [hunk 2]
```diff
@@ -757,6 +757,11 @@ public function process_refund( $order_id, $amount = null, $reason = '' ) {
 			return false;
 		}
 
+		// If this order is not authorized yet, don't try and refund it. Instead, return an appropriate error message.
```
[the remark this answers is not in the document]
Comment (dmallory42) [reply includes/class-wc-payment-gateway-wcpay.php:760]: Yup! You're correct, thanks for spotting that, need to make sure the wording is consistent.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 1 above)
Comment (dmallory42) [reply includes/class-wc-payment-gateway-wcpay.php:762]: Thanks @shendy-a8c for the great feedback.

> I think 'on hold' is the status of the order, not the payment. If my assumption is correct, then the error code might be better to be uncaptured-payment.

Agreed, that makes more sense.

> I think it's better to use the term 'authorized' and 'captured' because the option from the settings page is called 'Manual capture', so the user would know what's going on if we use that term. The order note also emphasizes those two terms.

That sounds good to me to make it more consistent.

> The user reaches this point because they want to make a refund (could be partial, could be in full amount) and that does not always mean they want to cancel the order. In the case where they want to make partial refund, it might be best to direct them to capture the payment first and then refund. For full refund, suggest to cancel authorization.

True. I would assume that most of the time a user would be confused if they are trying to refund an order which is authorized but not yet captured (they may not understand what this means). Perhaps it would be worth also looking at our documentation and making sure that we have some discussion about what this means and when to do a refund vs when to cancel an order?

> Wrap the string with __() for localization. As an example, you can find from the same file.

Thanks! Will do.

Also, your suggested text copy looks good to me. I will implement that for now unless there are any further comments from the team. 👍 

Also need to work out why the E2E tests failed, so I'll take another pass at this on Monday and make those changes. Thanks again!

Comment (dmallory42) [reply includes/class-wc-payment-gateway-wcpay.php]: Updated with these changes now. :)

**Comment by dmallory42** [comment]
One thing I wanted to ask for feedback on is the wording of the message that will appear when the user tries to refund an authorization.

After initial feedback from @shendy-a8c I re-worded it to account for both use cases, one is when a user wants to just cancel the order, and the other is when a user is trying to do a partial refund. For the first case, they should use the 'cancel authorization' option from the "Order Actions" dropdown. For the second case, the user may not realise the order hasn't actually been charged yet. If this is the case, they should charge the order, then refund partially via the refund workflow.

This is what I've currently got as the message:

"This payment is not captured yet. To cancel this order, please go to 'Order Actions' > 'Cancel Authorization'. To proceed with a refund, please go to 'Order Actions' > 'Capture charge' to charge the payment card, and then trigger a refund via the 'Refund' button."

Open to any suggestions/improvements on this. Thanks!

**Review by shendy-a8c — APPROVED** [review]
LGTM!

**Comment by dechov** [comment]
I just ran into an empty alert in the same spot but a different scenario: attempting refund after a dispute (using `4000000000000259` test card, in my case) – would the changes here address that case at all? If not, then we can open a separate issue for empty alerts.

**Comment by dmallory42** [comment]
Hey @dechov, thanks for mentioning that scenario. I just tested, and I was expecting that although the error you mentioned wouldn't be caught by the conditional logic implemented, the change that was made to fix the returning of error messages in Stripe as part of this PR would at least return the error message correctly. However, it seems that is not the case so we will need to open an issue to fix the empty alert issue for all Stripe errors.

**Comment by shendy-a8c** [comment]
I did some digging.

To fix the empty alert once and for all for refund, I believe [here, instead of $e->getCode(), it should be $e->get_error_code()](https://github.com/Automattic/woocommerce-payments/pull/1192/files#diff-bcfd303d507c33a27671935e724ee64d0df30ff2a18bb6ef4c94f28d48190124R791), or even better, to either have a separate catch block for `API_Exception` or just change the
```} catch ( Exception $e ) {```
to
```} catch ( API_Exception $e ) {```
because `$this->payments_api_client->refund_charge()` throws `API_Exception` only.
With that change, error message from the server will be bubbled up to the alert modal, something like this:
Screen Shot 2021-01-14 at 23 46 10


Having said all that, this PR indeed fixes #741 and it makes sense to create a separate issue to fix the empty error modal for any other case when issuing a refund.

The change [on this line](https://github.com/Automattic/woocommerce-payments/pull/1192/files#diff-bcfd303d507c33a27671935e724ee64d0df30ff2a18bb6ef4c94f28d48190124R791) does not contribute to the fix for #741 though.

**Comment by shendy-a8c** [comment]
Created #1203.

**Comment by dmallory42** [comment]
Thanks for digging into that @shendy-a8c , and great catch on using `$e->get_error_code()` instead of `$e->getCode()`! 

I'm going to go ahead and merge this issue since it addresses #741, and the new issue you made can be used to address the generic case of empty alert modals.
