### PR TITLE
Fix: Unable to access Subscription details when purchased via SEPA Direct Debit

### LINKED ISSUE #3442: Unable to access Subscription details when purchased via SEPA Direct Debit
### Describe the bug
When a new subscription is purchased using SEPA Direct Debit, a merchant is unable to access the subscription details via WooCommerce > Subscription because it generates a fatal error, and the console shows a 500 error.

### To Reproduce

1. Create a subscription with [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038)
2. Enable SEPA Direct Debit as a payment option.
3. Purchase the subscription in step 1 with [a test account number](https://stripe.com/docs/testing#sepa-direct-debit).
4. Navigate to WooCommerce > Subscriptions and select the subscription purchased in step 3.

### Actual behavior
1. The subscription details do not all load properly, and you'll see a 500 error in the console.
2. You'll receive an email that a fatal error occurred on the site, and this error will show up in the fatal error logs:

```
2021-11-29T17:11:09+00:00 CRITICAL Uncaught Error: Call to undefined method WC_Payment_Token_WCPay_SEPA::get_card_type() in /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php:2374
Stack trace:
#0 [internal function]: WC_Payment_Gateway_WCPay->{closure}(Object(WC_Payment_Token_WCPay_SEPA))
#1 /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php(2382): array_map(Object(Closure), Array)
#2 /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php(483): WC_Payment_Gateway_WCPay->get_user_formatted_tokens_array(140558371)
#3 /wordpress/core/5.8.2/wp-includes/class-wp-hook.php(305): WC_Payment_Gateway_WCPay->render_custom_payment_meta_input(Object(WC_Subscription), '_payment_method...', '3')
#4 /wordpress/core/5.8.2/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#5 /wordpress/core/5.8.2/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-change-payment-method-admin.php(83): do_action('woocommerce_sub...', Object(WC_Subscription), '_payment_method...', '3', Array)
#7 /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php(202): WCS_Change_Payment_Method_Admin::display_fields(Object(WC_Subscription))
#8 /wordpress/core/5.8.2/wp-admin/includes/template.php(1395): WCS_Meta_Box_Subscription_Data::output(Object(WP_Post), Array)
#9 /wordpress/core/5.8.2/wp-admin/edit-form-advanced.php(688): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post))
#10 /wordpress/core/5.8.2/wp-admin/post.php(206): require('/wordpress/core...')
#11 {main}
  thrown in /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php on line 2374
```

### Screenshots
Markup on 2021-11-29 at 11:20:15

### Expected behavior
Merchants should be able to access a subscription purchased with SEPA Direct Debit without fatal errors or a 500 error.

### Desktop (please complete the following information):

* OS: macOS 12.0.1
* Browser: Chrome
* Version: 96.0.4664.55 (Official Build) (x86_64)

### Additional context
Reported in 32523474-hc / 4554412-zen

* WooCommerce Subscriptions: by WooCommerce – 3.1.6
* WooCommerce Payments: by Automattic – 3.3.0
* WooCommerce: by Automattic – 5.9.0

### PR DESCRIPTION
**Pull request by htdat**
Fixes #3442

#### Changes proposed in this Pull Request

I removed the problematic methods/properties from `get_user_formatted_tokens_array` due to two reasons: 

1. These methods/properties exist in `WC_Payment_Token_CC` while they do not in `WC_Payment_Token_WCPay_SEPA`. The remaining ones are available in `WC_Payment_Token`. 

2. They are not used in the two consumers of this method `get_user_formatted_tokens_array`: 

2a, [First](https://github.com/Automattic/woocommerce-payments/blob/8f140393a3f964659b373275b762855413e6016a/includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php#L481-L482) - only `tokenId` and `displayName` are used. 

2b, [Second](https://github.com/Automattic/woocommerce-payments/blob/8f140393a3f964659b373275b762855413e6016a/includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php#L436-L436) - `wcpaySubscriptionEdit` global var is generated then used in [this JS file](https://github.com/Automattic/woocommerce-payments/blob/8f140393a3f964659b373275b762855413e6016a/client/subscription-edit-page.js#L1-L1). But then only `tokenId` and `displayName` are used.

Another approach is to use `method_exists` check these methods and conditionally return their values or just return an empty string. But it's not clean and necessary IMO.

#### Testing instructions

* Follow up the `Reproduce` section in #3442.
* Expectation: no error, and the Subscription Edit page displays normally.
* If possible, test with both WooComemmerce Subscriptions and WCPay Subscription built-in feature. 

-------------------

- [x] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

### CODE REVIEW

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -2609,14 +2609,10 @@ protected function get_user_formatted_tokens_array( $user_id ) {
 			]
 		);
 		return array_map(
-			static function ( WC_Payment_Token_CC $token ): array {
+			static function ( WC_Payment_Token $token ): array {
```
Comment (htdat) [inline includes/class-wc-payment-gateway-wcpay.php:2612]: Reason: The return type of `WC_Payment_Tokens::get_tokens` is `WC_Payment_Token[]`.

`$tokens` here are the inheritances of `WC_Payment_Token` including both `WC_Payment_Token_CC` and `WC_Payment_Token_WCPay_SEPA`.

**Review by brucealdridge — APPROVED** [review]
LGTM.  Nice bonus that we can delete a couple of lines!

**Comment by htdat** [comment]
Thanks @brucealdridge! 

Added the test instruction here.
https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions-for-WC-Payments-3.5.0#be-able-to-access-subscription-details-when-purchased-via-sepa-direct-debit
