### PR TITLE
Fix Add Payment method for SEPA by sending mandate data on intent.

### LINKED ISSUE #1538: Fix Add payment method on My Account for SEPA
Using the branch https://github.com/Automattic/woocommerce-payments/compare/sepa/1441-sepa-classic when you enter the test IBAN number and click on 'Add Payment Method', there is an error and the SEPA payment is not added:

`Missing required param: billing_details[name].`

SEPAAddPaymentError

You should be able to add a SEPA direct debit payment.

### PR DESCRIPTION
**Pull request by brezocordero**
Fixes #1538 

#### Changes proposed in this Pull Request

This PR adds mandate data on setup intent so that we can save SEPA payment methods.

#### Testing instructions

* With the option _wcpay_feature_sepa = 1 and SEPA payment enabled
* Go to My Account > Add Payment method
* Click on SEPA Direct Debit and enter the test account
* Click on Add Payment Method. Check there is no error and the payment is saved.
* Place an order using the saved Payment Method.
* Check the payment information is correct in the order.
* Check out the payment details on Stripe dashboard. Verify the Payment method is SEPA and the owner data are the name and email of customer.
* Check Add CC Payment Method still works.

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

### CODE REVIEW

**Comment by harriswong** [comment]
👀

File: includes/wc-payment-api/class-wc-payments-api-client.php [hunk 1]
```diff
@@ -302,6 +302,15 @@ public function create_and_confirm_setup_intent( $payment_method_id, $customer_i
...
 			$request['payment_method_types'] = [ Payment_Method::CARD, Payment_Method::SEPA ];
+			$request['mandate_data']         = [
+				'customer_acceptance' => [
+					'type'   => 'online',
+					'online' => [
+						'ip_address' => WC_Geolocation::get_ip_address(),
+						'user_agent' => $_SERVER['HTTP_USER_AGENT'] ?? $this->user_agent, //phpcs:ignore WordPress.Security.ValidatedSanitizedInput
+					],
+				],
+			];
```
Comment (harriswong) [inline includes/wc-payment-api/class-wc-payments-api-client.php:313]: Maybe we should add a test in `tests/unit/wc-payment-api/test-class-wc-payments-api-client.php` just in case. Thoughts?

Comment (brezocordero) [reply includes/wc-payment-api/class-wc-payments-api-client.php:313]: I agree.
We don't have any tests either for the function `create_and_confirm_intention` where we also added code for SEPA. I will take a look at that one too.

Comment (brezocordero) [reply includes/wc-payment-api/class-wc-payments-api-client.php:313]: @harriswong I added a test for `create_and_confirm_setup_intent`
The feature flag makes it sort of temporary because we will have to update the test when we remove it.
The check for the flag is on a static function and I had to update the option on the DB for the test.
Because of the flag, I didn't add another test for `create_and_confirm_intention`.

**Review by harriswong — APPROVED** [review]
LGTM 👍 

- Tested adding cc/SEPA card from "My Account" `my-account/payment-methods/`
- Tested removing cc/SEPA card from "My Account" `my-account/payment-methods/`
- Tested disabling SEPA via WCPay settings `wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments`. After it's disabled, I can still see the saved SEPA card. I suppose this could be another issue if this is a problem. 
- Tested checkout with saved card.
