### PR TITLE
Fix settings rendering on the Advanced Fraud Protection page

### LINKED ISSUE #8747: Advanced fraud protection erroneously suggests changes may not be saved
### Describe the bug

When editing the advanced fraud protection settings, there is a warning modal that appears when navigating away from the page:

```
[siteurl] says

There are unsaved changes on this page. Are you sure you want to leave and discard the unsaved changes?
```

And selecting the `Back to Payments Settings` button produces a similar modal with different copy:

```
Leave site?

Changes you made may not be saved.
```

This modal appears even if no changes were made or the changes were saved. In my limited testing, I couldn't get this message to _not_ appear.

### To Reproduce

1. Enable advanced fraud protection.
2. Edit the advanced settings.
3. Make no changes.
4. Attempt to navigate to another page.
5. Note that you receive the warning modal.

Also: 
1. Enable advanced fraud protection.
2. Edit the advanced settings.
3. Adjust one of the settings.
4. Select `Save Changes`.
5. Select `Back to Payments Settings`.
6. Note that you receive the warning modal.

### Actual behavior

There is a warning that changes may not be saved even if no changes were made or changes have been saved. This is unnecessary and adds confusion. 

### Screenshots

CleanShot 2024-04-30 at 21 06 19

CleanShot 2024-04-30 at 21 00 16

### Expected behavior

If there are no pending changes, this warning should not be present.

### Additional context

Tested in versions 7.5.3 and 7.6.0-test-2.

### LINKED ISSUE #9520: Advanced fraud protection page does not render the settings correctly
### Describe the bug

The settings on the Advanced Fraud Protection page are not being rendered/populated as expected. The data is stored correctly when the changes are saved, but it fails to display it in the UI.

### To Reproduce

1. Go to **Payments > Settings** and scroll to the **Fraud protection** section
2. Check the **Advanced** option and click on its action button
3. Scroll to the **Purchase Price Threshold** section and enable filtering
4. Save the changes
5. Refresh the page
6. The **Purchase Price Threshold** section will be empty/unchecked

### Expected behavior

1. The fraud protection changes should be reflected in the UI after saving them and refreshing the page

### PR DESCRIPTION
**Pull request by eduardoumpierre**
Fixes #9520 
Fixes #8747 

#### Changes proposed in this Pull Request

This PR aims to fix the Advanced Fraud Protection page that wasn't rendering the settings as expected, which also impacted the confirmation modal before leaving the page.

The approach used was to remove any code that was changing the `protectionSettingsUI` object directly and the global `useEffects`, to have specific `handleChange` functions for each form field. This makes the code simpler and adds immutability to the protection settings data.

#### Testing instructions

**Before checking out to this branch:**
* Checkout to `develop` and also update it `git pull`
* Build your client `npm run start`
* Go to **Payments > Settings** and scroll to the **Fraud protection** section
* Check the **Advanced** option and click on its action button
* Scroll to the **Purchase Price Threshold** section and enable filtering
* Save the changes and refresh the page
* The **Purchase Price Threshold** section will be empty/unchecked
* Without changing anything in the form, try to navigate out of the page by clicking on any menu item
* You should receive a confirmation alert about unsaved changes

Screenshot 2024-10-04 at 16 26 45

**Test this branch**
* Checkout to this branch
* Build your client `npm run start`
* Go to **Payments > Settings** and scroll to the **Fraud protection** section
* Check the **Advanced** option and click on its action button
* Scroll to the **Purchase Price Threshold** section and enable filtering
  * If you had already saved in the previous test, this section should already be enabled
* Save the changes and refresh the page
* The **Purchase Price Threshold** section should still be enabled and have the values you added to it
* Without changing anything in the form, try to navigate out of the page by clicking on any menu item
* You **should not** receive a confirmation alert about unsaved changes
* Go back to the Advanced Fraud Protection page
* Change anything in the form and, without changing the changes, try to navigate out of the page again
* You **should** receive the confirmation alert about unsaved changes
* Undo the changes and try to navigate out of the page again
* You **should not** receive a confirmation alert about unsaved changes

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9521` or branch name `fix/9520-advanced-fraud-protection-settings` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9520-advanced-fraud-protection-settings) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 1a7d3e1587917a57ad94092e851abae89fcc638e
- Build time: 2024-10-04 19:42:51 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/settings/fraud-protection/advanced-settings/cards/order-items-threshold.tsx [hunk 1]
```diff
@@ -48,40 +40,29 @@ const OrderItemsThresholdCustomForm: React.FC< OrderItemsThresholdCustomFormProp
 		[ protectionSettingsUI, setting ]
 	);
 
-	const minItemsTemp = parseInt( settingUI.min_items + '', 10 );
-	const maxItemsTemp = parseInt( settingUI.max_items + '', 10 );
+	const minItems = parseInt( settingUI?.min_items + '', 10 );
+	const maxItems = parseInt( settingUI?.max_items + '', 10 );
```
Comment (ismaeldcom) [inline client/settings/fraud-protection/advanced-settings/cards/order-items-threshold.tsx:44]: Not related to the PR, just out of curiosity, wouldn't be better to use `Number` here? It will remove the need to cast to string and use a radix.

**Review by ismaeldcom — APPROVED** [review]
Thanks for taking care of this, the code is more readable now without the useEffects, and less prone to errors. I prefer how you implemented the `handleInputChange` methods to be reusable and remove boilerplate code.

It works as expected, let's 🚢  it!

File: client/settings/fraud-protection/advanced-settings/cards/order-items-threshold.tsx (hunk 1 above)
Comment (eduardoumpierre) [reply client/settings/fraud-protection/advanced-settings/cards/order-items-threshold.tsx:44]: Yes, I think it would be better to use `Number` here instead of the multiple `parseInt`, but I'd be more comfortable having it in a different PR. I can open an enhancement issue to address that. It could even be something that we do on cooldown weeks. What do you think?

Comment (ismaeldcom) [reply client/settings/fraud-protection/advanced-settings/cards/order-items-threshold.tsx:44]: Yep, definitely something to explore on a cooldown or similar 🙂
