### PR TITLE
Show Express Checkout button previews in editor

### LINKED ISSUE #10043: Express Payment button not visibile on the Cart template
### Describe the bug
When visiting the Page: Cart template, the button for express payment is not visible in the Cart block

### To Reproduce

1. Go to Appearance > Editor > Templates > Page: Cart
2. Click on 'Edit'
3. Scroll down to the bottom of the template
4. Notice the express payment buttons aren't available

### Actual behavior
The buttons are visible when navigating to the block via the Post editor. Admin > Pages > Cart

### Screenshots
**Page: Cart template**
Image

**Cart Page**
Image
 

### Expected behavior
The express payment buttons should show in the editor for the template as well

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### PR DESCRIPTION
**Pull request by danielmx-dev**
Fixes #10043

#### Changes proposed in this Pull Request

When visiting the Page: Cart template, the button for express payment is not visible in the Cart block. When debugging this further, I noticed that when using the template editor, the contents were rendered inside an iframe, which Gutenberg does by design: https://github.com/WordPress/gutenberg/pull/25775

When the Stripe iframe is located inside the FSE iframe, no callbacks are executed and the payment buttons are never loaded (even if the conditions to render the buttons are met). This is not a problem with the page editor since, in my testing, that editor does not use an iframe to render the contents of the page, so the buttons load as expected.

In this PR I'm proposing to establish a timeout, if the elementsReady callback is never called, we render fallback buttons using the APIs provided by Google Pay (the Pay javascript library and https://developers.google.com/pay/api/web/guides/brand-guidelines ) and ApplePay (proprietary CSS rules only available in Safari https://developer.apple.com/documentation/apple_pay_on_the_web/displaying_apple_pay_buttons_using_css).

The downside of this approach is that, if more express payment methods are added, we'd need to implement a way to render the buttons ourselves. An alternative would be to just show placeholder buttons and don't worry too much about the styling, but please let me know what do you think.

#### Testing instructions

* Make sure you are using the Cart block in your designated Cart page (The designated Cart page is configured in WooCommerce  > Settings > Advanced > Page setup).
* Edit the cart page in the Pages editor.
* In a new tab, using the twenty-twenty four theme, go to Appearance > Editor > Templates and then edit the Page: Cart template.

Previous Result:
In the page editor, the supported Express Checkout buttons are rendered
image

In the template editor no buttons are rendered, and there's only a blank space:
image

Current Result (using this branch):
The Page editor remains the same, and buttons are rendered:
image

The Template editor now renders the express payment buttons:
image

### Regression Testing:
Express Payment method should still work as expected for making purchases in the Product, Cart, and Checkout pages.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10141` or branch name `fix/show-preview-for-express-checkout-buttons-in-editor` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/show-preview-for-express-checkout-buttons-in-editor) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 8426805ad851070ad5fac5ea73d952c1a2465b36
- Build time: 2025-02-28 09:46:50 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/tokenized-express-checkout/blocks/components/express-checkout-component.js [hunk 1]
```diff
@@ -118,29 +125,53 @@ const ExpressCheckoutComponent = ( {
...
+		}
+
+		const handle = setTimeout( () => {
+			if ( ! onElementsReadyCalled.current ) {
+				setShowFallbackButton( true );
+			}
+		}, FALLBACK_BUTTON_WAIT_TIME );
+
+		return () => clearTimeout( handle );
+	}, [ isPreview, onElementsReadyCalled ] );
```
Comment (frosso) [inline client/tokenized-express-checkout/blocks/components/express-checkout-component.js]:
```suggestion
	}, [ isPreview ] );
```

The value returned by `useRef` shouldn't be a hook dependency.

File: client/tokenized-express-checkout/blocks/components/express-checkout-component.js [hunk 2]
```diff
@@ -118,29 +125,53 @@ const ExpressCheckoutComponent = ( {
...
 	};
 
-	// The Cart & Checkout blocks provide unified styles across all buttons,
-	// which should override the extension specific settings.
-	const withBlockOverride = () => {
-		const override = {};
-		if ( typeof buttonAttributes !== 'undefined' ) {
-			override.buttonHeight = Number( buttonAttributes.height );
-		}
+	const checkoutElementOptions = useMemo( () => {
```
Comment (frosso) [inline client/tokenized-express-checkout/blocks/components/express-checkout-component.js]: I'm not sure `useMemo` is too useful, in this scenario. It seems that the memoized value would be discarded at each re-render, regardless.

`buttonOptions` comes from [the `useExpressCheckout` hook](https://github.com/Automattic/woocommerce-payments/blob/b0874750e42fb849a49d0b61190d4db236a1414e/client/tokenized-express-checkout/blocks/hooks/use-express-checkout.js#L36). And, in turn, it is computed by [the `getExpressCheckoutButtonStyleSettings()` utility](https://github.com/Automattic/woocommerce-payments/blob/30e1c14084bcad388b9306a13db0cbbe178d453a/client/tokenized-express-checkout/utils/index.ts#L117C14-L117C51).

The `getExpressCheckoutButtonStyleSettings` utility [returns a new object each time it is invoked](https://github.com/Automattic/woocommerce-payments/blob/30e1c14084bcad388b9306a13db0cbbe178d453a/client/tokenized-express-checkout/utils/index.ts#L150-L178).

So, `buttonOptions` will have a new in-memory reference each time the hook/utility is invoked, making `useMemo` also execute each time the `ExpressCheckoutComponent` component re-renders.

I noticed that `buttonAttributes` prop is also re-computed at each re-render: https://github.com/woocommerce/woocommerce/blob/3fced787bf20112dae420cb97b3da617a929b7de/plugins/woocommerce-blocks/assets/js/blocks/cart-checkout-shared/payment-methods/express-payment-methods.tsx#L33-L38

Is there a specific scenario you were thinking `useMemo` would have been useful in this component?

File: client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js [hunk 3]
```diff
@@ -0,0 +1,112 @@
+/**
+ * External dependencies
+ */
+import { useEffect, useMemo, useRef } from 'react';
+
+/**
+ * Internal dependencies
+ */
+import { getExpressCheckoutButtonAppearance } from 'wcpay/express-checkout/utils';
```
Comment (frosso) [inline client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js]: Since this file is within the `tokenized-express-checkout`, it's best to include the functions from that directory, rather than the `express-checkout` directory (which doesn't include "tokenized" cart changes).

Otherwise the bundles are going to get mixed, and there might be modifications in the "tokenized" functions that wouldn't be considered.

```suggestion
import { getExpressCheckoutButtonAppearance } from '../../utils';
```

File: client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+
+const ExpressCheckoutButtonPreview = ( {
+	expressPaymentMethod,
+	options,
+	buttonAttributes,
+} ) => {
+	const appearance = useMemo(
+		() => getExpressCheckoutButtonAppearance( buttonAttributes ),
+		[ buttonAttributes ]
+	);
```
Comment (frosso) [inline client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js]: Similar observation as the one I made in `ExpressCheckoutComponent` - is there a scenario where this `useMemo` would be useful?

File: client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js [hunk 5]
```diff
@@ -0,0 +1,112 @@
...
+	const ref = useRef( null );
```
Comment (frosso) [inline client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js]: Would it be possible to use a less generic `ref` name for this variable?
It looks like it's used for the GooglePlay's container - maybe `googlePlayContainerRef` or `googlePlayWrapperRef`?

File: client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js [hunk 6]
```diff
@@ -0,0 +1,112 @@
...
+					buttonType: 'plain',
+					buttonColor,
+					buttonRadius: parseFloat( borderRadius ),
+					buttonSizeMode: 'fill',
+					onClick: () => {},
+				} );
+				ref.current.appendChild( button );
+			} )();
+		}
+	}, [ ref, theme, expressPaymentMethod, borderRadius ] );
```
Comment (frosso) [inline client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js]:
```suggestion
	}, [ theme, expressPaymentMethod, borderRadius ] );
```

Return values from `useRef`s shouldn't be used as part of hook dependencies.

File: client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js [hunk 7]
```diff
@@ -0,0 +1,112 @@
...
+
+	useEffect( () => {
+		ref.current
+			?.querySelector( 'button' )
+			?.style?.setProperty( 'border-radius', borderRadius );
+	}, [ ref, borderRadius ] );
```
Comment (frosso) [inline client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js]:
```suggestion
	}, [ borderRadius ] );
```

File: client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js [hunk 8]
```diff
@@ -0,0 +1,112 @@
...
+	const theme = options.buttonTheme[ expressPaymentMethod ];
+	const borderRadius = appearance.variables.borderRadius;
+
+	useEffect( () => {
+		if (
+			ref.current &&
+			expressPaymentMethod === 'googlePay' &&
+			! renderGooglePayButtonPromise.current
+		) {
+			renderGooglePayButtonPromise.current = ( async () => {
```
Comment (frosso) [inline client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js]: I'm curious about the assignment of this function to `renderGooglePayButtonPromise.current` - could we have gotten away with just assigning a flag to indicate if the loading had been called?

i.e.: something like this:

```diff
diff --git a/client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js b/client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js
index b612e0202..1fce7c0d4 100644
--- a/client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js
+++ b/client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js
@@ -18,7 +18,7 @@ const ExpressCheckoutButtonPreview = ( {
 		[ buttonAttributes ]
 	);
 	const ref = useRef( null );
-	const renderGooglePayButtonPromise = useRef( null );
+	const hasStartedLoadingGooglePlayButton = useRef( false );
 
 	const theme = options.buttonTheme[ expressPaymentMethod ];
 	const borderRadius = appearance.variables.borderRadius;
@@ -27,9 +27,10 @@ const ExpressCheckoutButtonPreview = ( {
 		if (
 			ref.current &&
 			expressPaymentMethod === 'googlePay' &&
-			! renderGooglePayButtonPromise.current
+			! hasStartedLoadingGooglePlayButton.current
 		) {
-			renderGooglePayButtonPromise.current = ( async () => {
+			hasStartedLoadingGooglePlayButton.current = true;
+			( async () => {
 				const targetDocument = ref.current.ownerDocument;
 				const targetWindow = targetDocument.defaultView;
 				if ( ! targetWindow.google?.payments?.api?.PaymentsClient ) {

```

**Review by frosso — COMMENTED** [review]
A few comments about memoization and dependencies I thought would be worth pointing out.

The fallback works well 👍 which makes me wonder - should we just use this fallback in preview mode, without worrying about the Stripe "preview" (which is not really a "preview")?

File: client/tokenized-express-checkout/blocks/components/express-checkout-component.js (hunk 2 above)
Comment (danielmx-dev) [reply client/tokenized-express-checkout/blocks/components/express-checkout-component.js]: This was leftover from when why was trying another approach. I'll remove the `useMemo` usage.

File: client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js (hunk 4 above)
Comment (danielmx-dev) [reply client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js]: In this scenario I did it to avoid recalculating the border radius with every render, but the savings are probably negligible, I'll just remove it and see how it performs.

**Comment by danielmx-dev** [comment]
> The fallback works well 👍 which makes me wonder - should we just use this fallback in preview mode, without worrying about the Stripe "preview" (which is not really a "preview")?

My initial reasoning was to always try using Stripe first to provide a Preview as close as possible to the live experience; however, at least from my testing, the appearance in both are really close, so it's probably fine to use the new component in all previews.

File: client/tokenized-express-checkout/blocks/components/express-checkout-component.js [hunk 9]
```diff
@@ -131,16 +132,25 @@ const ExpressCheckoutComponent = ( {
 		};
 	};
 
+	const checkoutElementOptions = {
+		...withBlockOverride(),
+		...adjustButtonHeights( withBlockOverride(), expressPaymentMethod ),
+		...getPaymentMethodsOverride( expressPaymentMethod ),
+	};
+
+	if ( isPreview ) {
```
Comment (frosso) [inline client/tokenized-express-checkout/blocks/components/express-checkout-component.js]: Now that `isPreview` is used in this scenario, I think we can also remove the conditional assignment of the `onClickHandler`

```diff
diff --git a/client/tokenized-express-checkout/blocks/components/express-checkout-component.js b/client/tokenized-express-checkout/blocks/components/express-checkout-component.js
index 84a53e284..0ed67fa18 100644
--- a/client/tokenized-express-checkout/blocks/components/express-checkout-component.js
+++ b/client/tokenized-express-checkout/blocks/components/express-checkout-component.js
@@ -94,7 +94,6 @@ const ExpressCheckoutComponent = ( {
 		onClose,
 		setExpressPaymentError,
 	} );
-	const onClickHandler = ! isPreview ? onButtonClick : () => {};
 	const onShippingAddressChange = ( event ) =>
 		shippingAddressChangeHandler( event, elements );
 
@@ -151,7 +150,7 @@ const ExpressCheckoutComponent = ( {
 	return (
 		<ExpressCheckoutElement
 			options={ checkoutElementOptions }
-			onClick={ onClickHandler }
+			onClick={ onButtonClick }
 			onConfirm={ onConfirm }
 			onReady={ onElementsReady }
 			onCancel={ onCancel }
```

File: client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js [hunk 10]
```diff
@@ -0,0 +1,119 @@
...
+ * External dependencies
+ */
+import { useEffect, useRef } from 'react';
+
+/**
+ * Internal dependencies
+ */
+import { getExpressCheckoutButtonAppearance } from '../../utils';
+
+const ExpressCheckoutButtonPreview = ( {
```
Comment (frosso) [inline client/tokenized-express-checkout/blocks/components/express-checkout-button-preview.js]: (very optional) since this component contains effects that only apply to the GooglePay button preview, what do you think about separating the previews into two components with their own specific logic?

I'm thinking something like this:

```js
const ApplePayButtonPreview = ( { options, buttonAttributes } ) => {
	// applePay specific logic

	return (
		<div>
			<button
				type="button"
				id="express-checkout-button-preview-applePay"
				className="express-checkout-button-preview"
				style={ buttonStyle }
			/>
		</div>
	);
};

const GooglePayButtonPreview = ( { options, buttonAttributes } ) => {
	// googlePay specific logic & hooks
	
	useEffect( () => {
		// ...
	}, [] );

	useEffect( () => {
		// ...
	}, [ ] );

	return (
		<div
			ref={ googlePlayContainerRef }
			style={ {
				height: `${ options.buttonHeight }px`,
				width: '100%',
			} }
		/>
	);
};

const ExpressCheckoutButtonPreview = ( {
	expressPaymentMethod,
	options,
	buttonAttributes,
} ) => {
	if ( expressPaymentMethod === 'googlePay' ) {
		return (
			<GooglePayButtonPreview
				options={ options }
				buttonAttributes={ buttonAttributes }
			/>
		);
	}

	if ( expressPaymentMethod === 'applePay' ) {
		return (
			<ApplePayButtonPreview
				options={ options }
				buttonAttributes={ buttonAttributes }
			/>
		);
	}

	return null;
};

export default ExpressCheckoutButtonPreview;
```

Let me know what you think!

**Review by frosso — APPROVED** [review]
Excellent work! Thank you for entertaining my suggestions.
I added a _very_ optional suggestion to simplify the body of the `ExpressCheckoutButtonPreview` component.

Now that we have `ExpressCheckoutButtonPreview`, I am even questioning whether `ExpressCheckoutButtonPreview` should be rendered within `ExpressCheckoutComponent`. In the `edit` property of `tokenizedExpressCheckoutElementApplePay`/`tokenizedExpressCheckoutElementGooglePay` we could just render `ExpressCheckoutButtonPreview` and get rid of the whole `isPreview` prop 🤷 but I'm guessing that would be too many changes in this PR.

Regardless, this already fixes the main issue 👍

**Review by frosso — APPROVED** [review]
Still looking good, thank you for all the changes! :shipit:

**Comment by danielmx-dev** [comment]
@frosso Based in [this comment](https://github.com/Automattic/woocommerce-payments/issues/10043#issuecomment-2620327145), I added one more commit to avoid using the Preview component if a new express payment method gets added in the future and doesn't have an implementation yet. https://github.com/Automattic/woocommerce-payments/pull/10141/commits/f26c0ad1426bb154bcf5b0c83567d6d5418587d0

**Comment by frosso** [comment]
Sounds good, thank you @danielmx-dev . Looks like a minor change 👍 it would have been fine to also add that in the future, if we needed to implement those methods :D

**Comment by danielmx-dev** [comment]
@frosso It looks like we'll finally move forward with this solution. I have re-requested your review since I copied the solution to non-tokenized ECE as well.

**Review by frosso — APPROVED** [review]
Changes in the tokenized express checkout seem in line 👍 

Checked cart & checkout pages in the editor, still working well:
Screenshot 2025-02-28 at 10 49 25 AM
Screenshot 2025-02-28 at 10 49 13 AM

As opposed to `develop`:
Screenshot 2025-02-28 at 10 48 50 AM
Screenshot 2025-02-28 at 10 48 46 AM

Placing the order from block-based cart/checkout still works.

:shipit:
