### PR TITLE
Fix currency negative sign position on JS rendered amounts

### LINKED ISSUE #6700: Currency symbol and negative indicator ordering need localized?
When I'm using WooCommerce Payments with USD as my store currency, negative amounts (such as the Fees column under Payments > Transactions) are shown as `$-50.00`. 

Screenshot taken on 2023-07-06 at 19 33 10 UTC@2x

However, in the U.S., the currency symbol is usually after the negative sign, e.g. `-$50.00`.

A straw poll of U.S. a12s in Slack agrees: p1688671462030829-slack-C1Y86QPAQ

Is there some way we can "localize" the display of negative amounts so that it doesn't appear odd for a merchant, depending on their country?
```[tasklist]
### Tasks
- [x] Update CLDR data to v41.3
- [x] Add negativity types to the i18n files for each currency
- [x] Add frontend currency formatter
- [ ] Remove currency negativity sign modification code
```

### PR DESCRIPTION
**Pull request by tpaksu**
Fixes #6700

#### Changes proposed in this Pull Request

This fixes the discrepancy between JS rendered negative amounts versus PHP rendered amounts with putting the negative sign in front of the rendered amount including the currency code.  JS side was rendering the amount with putting the currency code before the negative amount because of `sprintf`, whereas PHP was converting the price to positive and prepending the negativity sign after `sprintf` ([link](https://github.com/woocommerce/woocommerce/blob/7768ef5b5c08c063bf8270387eb2bc9963eb0beb/plugins/woocommerce/includes/wc-formatting-functions.php#L611-L612)). Used the same approach on the JS side to fix the difference in rendering.

This equalizes the negative format application for those three places:

- [#](https://github.com/woocommerce/woocommerce/blob/7768ef5b5c08c063bf8270387eb2bc9963eb0beb/plugins/woocommerce/includes/wc-formatting-functions.php#L611-L612) Core `wc_price` formatting of negative amounts
- [#](https://github.com/Automattic/woocommerce-payments/pull/7935/files#diff-fdf97bb0bd6043ee97d2ab4f058059c59d2b7173a076398fe8441824dc7b5e35) Removes the extra mod for fee formatter
- [#](https://github.com/Automattic/woocommerce-payments/pull/7935/files#diff-d6d2898493a58a1d7c4e36bdfc2edbab82b2d1241a7d81f7988f68f20f75c513) Moves the negative amount handling outside the sprintf call

#### Testing instructions

* Checkout this branch, build the client assets with `npm run build:client`
* Go to Payments > Transactions screen and see the fees are rendered with negative sign in front of the whole representation, not after the currency symbol.
* Sell something and do a refund
* See that the refund prices are shown correctly with the negative sign before the currency sign.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7935` or branch name `fix/6700-remove-currency-sign-modification-code` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/6700-remove-currency-sign-modification-code) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 5985c289f382db41cb1ef53aa18c67150f507def
- Build time: 2023-12-20 13:15:09 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/utils/currency/index.js [hunk 1]
```diff
@@ -119,19 +119,38 @@ export const formatCurrency = (
...
 	}
 
+	const isNegative = amount < 0;
+	const positiveAmount = isNegative ? -1 * amount : amount;
 	const currency = getCurrency( currencyCode, baseCurrencyCode );
 
 	if ( currency === null ) {
-		return composeFallbackCurrency( amount, currencyCode, isZeroDecimal );
+		return (
+			( isNegative ? '-' : '' ) +
```
Comment (eduardoumpierre) [inline client/utils/currency/index.js]: **Non-blocking:** What do you think about moving this sign logic to a variable? We can reuse it on lines 139 and 146 as well.

**Review by eduardoumpierre — APPROVED** [review]
I followed the testing instructions and it worked as expected. The code is clear and the tests were updated.

image

I left a suggestion as a non-blocking comment.

Thanks for working on this one! LGTM!

File: client/utils/currency/index.js (hunk 1 above)
Comment (tpaksu) [reply client/utils/currency/index.js]: Yea, I did that but I didn't push it, because it still had the repetition of the `prefix` variable I set. But yea, if you thought the same, I'll push it now. 🦅

Comment (tpaksu) [reply client/utils/currency/index.js]: Addressed in [5985c28](https://github.com/Automattic/woocommerce-payments/pull/7935/commits/5985c289f382db41cb1ef53aa18c67150f507def).
