### PR TITLE
hotfix: fallback to the checkout gateway in case main gateway isn't initialized

### LINKED ISSUE #7128: Call to a member function should_use_stripe_platform_on_checkout_page() on null
6705304-zen

Merchant is seeing the below error from WooPayments. Opening this for tracking more such issues.

```

Error Details
=============
An error of type E_ERROR was caused in line 179 of the file public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-checkout.php. 
Error message: Uncaught Error: Call to a member function should_use_stripe_platform_on_checkout_page() on null in public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-checkout.php:179
Stack trace:
#0 public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-upe-checkout.php(146): WCPay\WC_Payments_Checkout->get_payment_fields_js_config()
#1 public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-blocks-payment-method.php(101): WCPay\WC_Payments_UPE_Checkout->get_payment_fields_js_config()
#2 public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/PaymentMethodRegistry.php(62): WC_Payments_Blocks_Payment_Method->get_payment_method_data()
#3 public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Api.php(93): Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->get_all_registered_script_data()
#4 public_html/wp-includes/class-wp-hook.php(310): Automattic\WooCommerce\Blocks\Payments\Api->add_payment_method_script_data()
#5 public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#6 public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/MiniCart.php(200): do_action()
#8 public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractBlock.php(100): Automattic\WooCommerce\Blocks\BlockTypes\MiniCart->enqueue_data()
#9 public_html/wp-includes/class-wp-hook.php(310): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_editor_assets()
#10 public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#11 public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#12 public_html/wp-admin/edit-form-blocks.php(272): do_action()
#13 public_html/wp-admin/post.php(187): require('/home/u70418726...')
#14 {main}
  thrown

```

### PR DESCRIPTION
**Pull request by timur27**
Fixes https://github.com/Automattic/woocommerce-payments/issues/7128

#### Changes proposed in this Pull Request
This PR introduces the countermeasure against handling non-initialized registered card gateway. Some time ago, https://github.com/Automattic/woocommerce-payments/pull/6828 started to fetch `should_use_stripe_platform_on_checkout_page`'s value from the `WC_Payments::get_registered_card_gateway()`.  As per 6705304-zd-a8c, it turns out that this variable is not initialized under certain circumstances which are unknown at the moment. The change in this PR is just an additional prevention mechanism against fatal errors users might experience.

Prior to https://github.com/Automattic/woocommerce-payments/pull/6828, `$this->gateway` was used for checking if `should_use_stripe_platform_on_checkout_page()`. So this change shouldn't introduce any regression.

#### Testing instructions
Checkout `develop`
1. Modify [this line](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments.php#L773) to `return null;` to simulate the behavior. 
2. Navigate to the wp-admin -> Pages -> Add new
3. Confirm the error identical to the below appears

```
An error of type E_ERROR was caused in line 179 of the file /home/u704187269/domains/[ennetbody.ch/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-checkout.php](http://ennetbody.ch/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-checkout.php). Error message: Uncaught Error: Call to a member function should_use_stripe_platform_on_checkout_page() on null in /home/u704187269/domains/[ennetbody.ch/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-checkout.php:179](http://ennetbody.ch/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-checkout.php:179)
Stack trace:
0-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-upe-checkout.php(146)](http://ennetbody.ch/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-upe-checkout.php(146)): WCPay\WC_Payments_Checkout->get_payment_fields_js_config()
1-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-blocks-payment-method.php(101)](http://ennetbody.ch/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-blocks-payment-method.php(101)): WCPay\WC_Payments_UPE_Checkout->get_payment_fields_js_config()
2-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/PaymentMethodRegistry.php(62)](http://ennetbody.ch/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/PaymentMethodRegistry.php(62)): WC_Payments_Blocks_Payment_Method->get_payment_method_data()
3-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Api.php(93)](http://ennetbody.ch/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Api.php(93)): Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->get_all_registered_script_data()
4-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-includes/class-wp-hook.php(310)](http://ennetbody.ch/public_html/wp-includes/class-wp-hook.php(310)): Automattic\WooCommerce\Blocks\Payments\Api->add_payment_method_script_data()
5-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-includes/class-wp-hook.php(334)](http://ennetbody.ch/public_html/wp-includes/class-wp-hook.php(334)): WP_Hook->apply_filters()
6-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-includes/plugin.php(517)](http://ennetbody.ch/public_html/wp-includes/plugin.php(517)): WP_Hook->do_action()
7-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/MiniCart.php(200)](http://ennetbody.ch/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/MiniCart.php(200)): do_action()
8-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractBlock.php(100)](http://ennetbody.ch/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractBlock.php(100)): Automattic\WooCommerce\Blocks\BlockTypes\MiniCart->enqueue_data()
9-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-includes/class-wp-hook.php(310)](http://ennetbody.ch/public_html/wp-includes/class-wp-hook.php(310)): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_editor_assets()
10-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-includes/class-wp-hook.php(334)](http://ennetbody.ch/public_html/wp-includes/class-wp-hook.php(334)): WP_Hook->apply_filters()
11-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-includes/plugin.php(517)](http://ennetbody.ch/public_html/wp-includes/plugin.php(517)): WP_Hook->do_action()
12-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-admin/edit-form-blocks.php(272)](http://ennetbody.ch/public_html/wp-admin/edit-form-blocks.php(272)): do_action()
13-zd-a8c /home/u704187269/domains/[ennetbody.ch/public_html/wp-admin/post.php(187)](http://ennetbody.ch/public_html/wp-admin/post.php(187)): require('/home/u70418726...')
14-zd-a8c {main}
  thrown
```

4. Checkout `hotifix/non-initialized-gateway` branch
5. Refresh the page and confirm that the error is gone
6. Perform a payment through shortcode checkout & Blocks checkout as sanity check.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7133` or branch name `hotifix/non-initialized-gateway` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=hotifix/non-initialized-gateway) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 32c607e1b86d481546de3aadd99994476d7a7307
- Build time: 2023-09-05 11:56:23 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/class-wc-payments-checkout.php [hunk 1]
```diff
@@ -161,6 +161,9 @@ public function get_payment_fields_js_config() {
 		// Needed to init the hooks.
 		WC_Checkout::instance();
 
+		// The registered card gateway is more reliable than $this->gateway, but if it isn't available for any reason, fall back to the gateway provided to this checkout class.
+		$gateway = WC_Payments::get_registered_card_gateway() ? WC_Payments::get_registered_card_gateway() : $this->gateway;
```
Comment (jbordonado) [inline includes/class-wc-payments-checkout.php]:
```suggestion
		$gateway = WC_Payments::get_registered_card_gateway() ?? $this->gateway;
```

Would the null coalescing operator work directly?

Comment (timur27) [reply includes/class-wc-payments-checkout.php]: Great tip, thanks! 32c607e1b86d481546de3aadd99994476d7a7307

**Review by frosso — APPROVED** [review]
Changes read well, while we're investigating the reasoning behind why it's not initialized.

**Review by zmaglica — APPROVED** [review]
