### PR TITLE
Prevent sending shopper emails when disputes are closed

### LINKED ISSUE #7928: Shoppers receive "order complete" emails when a dispute is closed
### Description

When a dispute is opened, the order is automatically placed in on-hold [here](https://github.com/Automattic/woocommerce-payments/blob/dfd571b3be849ad135a32e44014d31f5135322ae/includes/class-wc-payments-order-service.php#L297) and when the dispute is closed, the order is marked as complete [here](https://github.com/Automattic/woocommerce-payments/blob/dfd571b3be849ad135a32e44014d31f5135322ae/includes/class-wc-payments-order-service.php#L333) (where there is a TODO regarding order status).

This retriggers the order completed email. If the order was completed before the dispute was opened, the customer will, on closure of the dispute, receive the email a second time.

## How to reproduce

- Ensure you can see order emails (as shopper). I did this by using a test store (sandbox mode) on Pressable hosting. Could also set up MailHog in local docker environment.
- Purchase something using a [dispute test card](https://stripe.com/docs/testing#disputes). I used `4000000000002685` (triggers `not received` dispute).
- Close the dispute. I closed by [submitting test `winning_evidence`](https://stripe.com/docs/testing#evidence).
- Observe the email received by the shopper - `Your [STORE] order is now complete` (triggered by the dispute close webhook).

### Suggestions for fix

This could be resolved by a filter that would allow a merchant to apply custom statuses to the order, preventing such problems as duplicated emails.

The underlying problem here is that we are using order status for tracking disputes, and this is not directly supported by WooCommerce core (as I understand it). There have been other issues about using a custom status for dispute. May require coordination with core to fix this, though there may be a way to defensively mitigate in WooPayments plugin.

### Related issues (disputed status) & work in progress

- #526
- #714  
- #727

### Additional context

This request comes as a result of https://github.com/Automattic/woocommerce-payments/issues/7885 where the merchant is receiving multiple inquiries triggered by return requests in the Klarna app.

### PR DESCRIPTION
**Pull request by brucealdridge**
Fixes #7928 

#### Changes proposed in this Pull Request

When a dispute is created, WooPayments will mark the order as [`on-hold`](https://github.com/Automattic/woocommerce-payments/blob/ec9334e450440ae03c0afff251a090114d5d02e0/includes/class-wc-payments-order-service.php#L323). When the dispute is closed, the order is marked as `completed` or `refunded` depending on the dispute [`status`](https://github.com/Automattic/woocommerce-payments/blob/ec9334e450440ae03c0afff251a090114d5d02e0/includes/class-wc-payments-order-service.php#L353). 

The changing of the status to either `refunded` or `completed` triggers WooCommerce to send an email.

| `refunded` email | `completed` email |
|--------|--------|
| image | image | 

In both cases, these emails should not be sent. In the case of `completed` the shopper will be confused as to why they are receiving the email. 

For `refunded` there are some benefits to still sending the email as it will let the shopper know that they are being refunded. However, as this refund is handled by Stripe and the shoppers' bank there may be a delay in receiving it. It is best to allow the shoppers' bank to communicate the dispute outcome.

This PR adds a filter to block these emails from being sent as the order status is being changed.  This will fix the immediate issue of emails being sent.

Long-term, disputes should have custom statuses. See #8306

##### Setup
- Ensure you can see order emails (as shopper). e.g MailHog in local docker environment.
- Purchase something using a [dispute test card](https://stripe.com/docs/testing#disputes). I used `4000000000002685` (triggers `not received` dispute).

##### Order complete emails 
- Close the dispute. I closed by [submitting test `winning_evidence`](https://stripe.com/docs/testing#evidence).
- Email should not be sent to the shopper - `Your [STORE] order is now complete`

##### Order refunded emails 
- Close the dispute, by accepting the dispute or [submitting test `losing_evidence`](https://stripe.com/docs/testing#evidence).
- Email should not be sent to the shopper - `Your [STORE] order has been refunded `

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: includes/class-wc-payments-order-service.php [hunk 1]
```diff
@@ -345,6 +345,11 @@ public function mark_payment_dispute_closed( $order, $charge_id, $status ) {
 			return;
 		}
 
+
+		// Order `completed` and `refunded` emails should both be blocked when disputes are closed.
+		add_filter( 'woocommerce_email_enabled_customer_completed_order', '__return_false' );
+		add_filter( 'woocommerce_email_enabled_customer_refunded_order', '__return_false' );
```
Comment (brucealdridge) [inline includes/class-wc-payments-order-service.php:350]: I considered only adding the specific filters inside the `if`, but it seemed more readable to me to add and remove both at the same time.

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8308` or branch name `fix/7928-prevent-sending-order-complete-emails` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7928-prevent-sending-order-complete-emails) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 0a4df3ca369b4c09d05fdbc559c68daa8aa08bf2
- Build time: 2024-03-04 04:22:39 UTC

_Note: the build is updated when a new commit is pushed to this PR._

**Comment by nagpai** [comment]
#### Manual test

##### Without patch 
* Placed a test order with a dispute test card
* Closed the dispute on dashboard by challenging dispute and with `winning_evidence` in `Additional details`  field
* Used Mail Log Plugin and was able to see an email triggered - `Your <site name> order is now complete` 

##### With Patch 
* Followed the first two steps same as above, to create and close a test dispute
* There was no `Order complete` email sent this time
✅  - Patch works successfully

#### Code feedback
* The code changes are pretty straightforward and look good.

**Review by nagpai — APPROVED** [review]
Check detailed comment with manual test findings. Looks good.
