### PR TITLE
Temporarily disables custom field detection notices

### LINKED ISSUE #8752: Calling woocommerce_checkout_fields on settings pages resulting in conflicts with other plugins
### Describe the bug
The `woocommerce_checkout_fields` filter is called on the WooPayments settings page, which can lead to conflicts with plugins that modify the checkout. The outcome is a failure of the WooPayments settings page. 

This has resulted in a conflict with one of our plugins, which we are fixing on our side, but it may benefit the broader Woo community to review this handling in WooPayments as well as the failure is triggered by the checkout fields being filtered for unrelated reasons. 

### To Reproduce

To replicate:

- Activate WooPayments (current version 7.5.3), test credentials are fine
- Activate Aweber, connect it to Aweber (current version 4.0.3) - note: plugin will resolve this in 4.0.4 or later
- Go to the WooPayments settings page [and see this error](https://share.kwp.to/v/iGWpJvZs2FpxOClSmvad)
- For an additional error, attempt to save settings and [see this](https://share.kwp.to/v/ktlModdJ7XO5A2YVrGps)

Note: the frontend experience appears to continue to work just fine, and the issue appears to be specific to the settings page.

### Actual behavior
The settings page fails to load any data, which appears to be a pre-setup state

### Expected behavior
The settings page loads normally 

### Desktop (please complete the following information):
* OS: MacOS 13.6.6 (22G630)
* Browser Chrome
* Version 124.0.6367.93

### Additional context

Backtrace: 
```
 require(‘wp-blog-header.php’), wp, WP->main, WP->parse_request, do_action_ref_array(‘parse_request’), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, WC_REST_Payments_Settings_Controller->get_settings, WC_REST_Payments_Settings_Controller->should_show_express_checkout_incompatibility_notice, apply_filters(‘woocommerce_checkout_fields’), WP_Hook->apply_filters, WC_Aweber_Checkout->checkout_fields
```

### PR DESCRIPTION
**Pull request by FangedParakeet**
Fixes #8752 

#### Changes proposed in this Pull Request

This PR temporarily disables custom checkout field detection notices in payments settings. The purpose of this feature was to detect when custom checkout fields might be present at checkout that could cause errors with express checkout payment methods. The notice would warn admins that their EPMs might not work as expected while these custom fields are present on the checkout.

Notice
_This notice_

However, this detection worked by checking whether any plugin was hooking into either `woocommerce_billing_fields`, `woocommerce_shipping_fields`, or `woocommerce_checkout_fields`. These filters could be used for benign reasons without altering the checkout in a way that might break EPM functionality, but this would still trigger the warning.

Moreover, since our implementation called `apply_filter` on these checkout hooks from the admin, this caused errors with plugins that hooked into this filter with checkout-specific functionality that would not work in the admin (described in #8752).

Due to these excessive false positives and other errors, we have decided to temporarily disable this feature, in view of exploring a client-side custom field detection mechanism instead. Consequently, when this issue is merged, we should probably reopen #8299, where we can develop a longer term solution for this problem.

Note that this PR only ensures that the notice will no longer appear. I am leaving the client-side code in place, because we plan to revisit this functionality and hopefully will be able to reuse those components created in #8339. 

#### Testing instructions

1. Before pulling this PR, on `develop`, activate a plugin that adds or removes custom fields to the checkout. Here is a snippet that I used to simulate this.

```php
function add_shipping_phone_field( $fields ) {
	$defaults = array(
		'label'        => __( 'Phone', 'woocommerce-services' ),
		'type'         => 'tel',
		'required'     => false,
		'class'        => array( 'form-row-wide' ),
		'clear'        => true,
		'validate'     => array( 'phone' ),
		'autocomplete' => 'tel',
	);
	$field = isset( $fields['shipping_phone'] )
		? array_merge( $defaults, $fields['shipping_phone'] )
		: $defaults;
	$fields['shipping_phone'] = $field;
	return $fields;
}

add_filter( 'woocommerce_shipping_fields', 'add_shipping_phone_field' );
```

This filter basically just replaces the shipping phone field with itself (this was borrowed from a similar application in Woo Shipping), so it will not affect any EPM functionality, but it will still trigger the warning notice as a false positive.

2. Visit Payments settings and confirm that the notice appears.
3. Pull the changes in this PR and revisit Payments settings and confirm that the notice no longer appears.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9329` or branch name `chore/disable-custom-checkout-field-detection` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=chore/disable-custom-checkout-field-detection) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9dacbf10fbf4c2cc800cde3a396803b086cda3c8
- Build time: 2024-08-27 04:49:36 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: includes/admin/class-wc-rest-payments-settings-controller.php [hunk 1]
```diff
@@ -513,7 +513,6 @@ public function get_settings(): WP_REST_Response {
 				'is_card_present_eligible'               => $this->wcpay_gateway->is_card_present_eligible() && isset( WC()->payment_gateways()->get_available_payment_gateways()['cod'] ),
 				'is_woopay_enabled'                      => 'yes' === $this->wcpay_gateway->get_option( 'platform_checkout' ),
 				'show_woopay_incompatibility_notice'     => get_option( 'woopay_invalid_extension_found', false ),
-				'show_express_checkout_incompatibility_notice' => $this->should_show_express_checkout_incompatibility_notice(),
```
Comment (frosso) [inline includes/admin/class-wc-rest-payments-settings-controller.php:516]: > Note that this PR only ensures that the notice will no longer appear. I am leaving the client-side code in place, because we plan to revisit this functionality and hopefully will be able to reuse those components created in https://github.com/Automattic/woocommerce-payments/pull/8339.

I get it that the client-side can be repurposes, but I don't think I agree that we should keep its dead code in the codebase.
The `getShowExpressCheckoutIncompatibilityNotice()` selector, `useExpressCheckoutShowIncompatibilityNotice()` hook, and all their usages would just become obsolete.
Pulling them back would just be a matter of reverting these changes + modifying their functionality.

Keeping the code would introduce unnecessary clutter and create potential maintenance issues.

I understand that it's nice that the front-end code could keep living, but the uncertainty of when it would be re-introduced + the simplicity of eliminating it at this time + the uncertainty of whether it will keep working properly once we try to re-utilize it makes me lean towards eliminating all the dead code with this PR.

**Review by frosso — APPROVED** [review]
This PR serves the purpose of hiding the notice, but I would recommend cleaning up the codebase from its dead code.

**Review by frosso — APPROVED** [review]
Thank you for entertaining my suggestion! :shipit:
