### PR TITLE
fix: Stripe Link autofill on checkout

### LINKED ISSUE #6881: Stripe Link autofill does not update fields in blocks checkout
### Describe the bug

The Link express checkout method functions by identifying a user from their email, authenticating them via OTP, and then manually autofilling the billing and shipping input fields at checkout. To autofill these fields, Stripe returns an `autofill` event to the Stripe Link autofill instance containing the user's address details and we provide the location of the inputs that need to be completed.

In the blocks checkout, this event is captured successfully and the fields visually appear to be filled. However, the state does not seem to update and if we submit the form--without any further interaction with the checkout--we will be told that the fields are empty. Updating any of the fields manually at checkout will update the state and enable the form to be submitted. 

### To Reproduce

1. Enable Stripe Link payment and disable WooPay. This can be achieved by either enabling the legacy, split, or deferred intent UPE.
2. Go to blocks checkout. Ensure all inputs are empty.
3. Enter email address registered with Stripe Link. Authenticate via OTP and select autofill button.
4. Notice that input fields are satisfyingly completed.
5. Select "Place order". Notice that an unsatisfying error will appear stating that billing fields cannot be empty.
6. Edit any billing field manually and then select "Place order" again. Notice that checkout will now satisfactorily complete.

### Actual behavior

I cannot complete checkout after autofilling billing fields with Stripe Link.

### Expected behavior

I would like autofilled fields to be correctly completed, so that I can complete the checkout.

### Desktop (please complete the following information):

* OS: Any
* Browser [e.g. chrome, safari]: Any
* Version [e.g. 22]: `develop`

### Smartphone (please complete the following information):

* Device: Any
* OS: Any
* Browser: Any
* Version [e.g. 22]: `develop`

### Additional context

#6391

### LINKED ISSUE #8019: Stripe Link autofill does not update fields shortcode checkout values
### Describe the bug

The shortcode checkout isn't working well with the Stripe Link autofill.
The shortcode checkout might use the `select2` (depending on the theme - but it is using `select2` by default), and the change of the value doesn't affect the "state" select.

On a "normal" user checkout flow, changing the "Country" field might render a different element for the "state" field (from text field to select - or vice-versa).
Also on a "normal" user checkout flow, I see rates changing (because of different shipping rates).

With Stripe Link, I am not seeing this behavior.

It's worth mentioning that the behavior occurs when a different "country" field is used by Stripe Link.

### To Reproduce

- Enable Stripe Link payment and disable WooPay
- Go to shortcode checkout. Ensure all inputs are empty
- Select a different country from the one saved in your existing Stripe Link account (e.g.: "Armenia" - which uses a text field for its "state")
- Enter email address registered with Stripe Link. Authenticate via OTP and select the autofill button

### Actual behavior

- Shipping rates aren't updated
- State/Country is updated

### Expected behavior

- Selecting a Stripe Link address updates the "state" select
- Selecting a Stripe Link address updates the shipping rates

### Additional context

Noticed while working here: https://github.com/Automattic/woocommerce-payments/issues/6881

### PR DESCRIPTION
**Pull request by frosso**
Fixes https://github.com/Automattic/woocommerce-payments/issues/6881
Fixes https://github.com/Automattic/woocommerce-payments/issues/8019

#### Changes proposed in this Pull Request

Ensuring that Stripe Link correctly autofills blocks & shortcode checkout.
Ensuring that country/state dropdowns and text fields are correctly updated on autofill.
Refactored the implementation to fill both billing and shipping addresses with one function.

#### Testing instructions

Perform the same testing on both blocks and shortcode checkout

- As a merchant, ensure Stripe Link is enabled in the site's WooPayments settings
- As a merchant, ensure "card" is enabled at checkout
- As a customer, ensure you're using "US" as a currency
- As a customer, add items to the cart
- As a customer, go to checkout
- As a customer, ensure you have "Credit Card/Debit Card" as a selected payment method
- As a customer, select a country that uses a non-select state field (e.g.: "Yemen")
- As a customer, click the "Stripe Link" button appearing next to the email field
- Click "autofill"
- Stripe Link billing/shipping values should be autofilled

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: client/checkout/classic/payment-processing.js [hunk 1]
```diff
@@ -135,26 +135,36 @@ function createStripePaymentMethod(
 				...params.billing_details,
 				name:
 					`${
-						document.querySelector( '#billing_first_name' )
```
Comment (frosso) [inline client/checkout/classic/payment-processing.js:138]: Refactored to that the element names from the `SHORTCODE_BILLING_ADDRESS_FIELDS` constant are used.

File: client/checkout/constants.js [hunk 2]
```diff
@@ -35,42 +35,22 @@ export function getPaymentMethodsConstants() {
 	];
 }
 
-export const BLOCKS_SHIPPING_ADDRESS_FIELDS = {
```
Comment (frosso) [inline client/checkout/constants.js:38]: Not used anymore

File: client/checkout/constants.js [hunk 3]
```diff
@@ -35,42 +35,22 @@ export function getPaymentMethodsConstants() {
...
-	line1: 'shipping-address_1',
-	line2: 'shipping-address_2',
-	city: 'shipping-city',
-	state: 'components-form-token-input-1',
```
Comment (frosso) [inline client/checkout/constants.js:42]: This selector didn't work well for countries that have a text field for their "state"/"province"/"county"

File: client/checkout/constants.js [hunk 4]
```diff
@@ -35,42 +35,22 @@ export function getPaymentMethodsConstants() {
...
-	postal_code: 'shipping-postcode',
-	country: 'components-form-token-input-0',
-	first_name: 'shipping-first_name',
-	last_name: 'shipping-last_name',
-};
-export const BLOCKS_BILLING_ADDRESS_FIELDS = {
-	line1: 'billing-address_1',
-	line2: 'billing-address_2',
-	city: 'billing-city',
-	state: 'components-form-token-input-3',
```
Comment (frosso) [inline client/checkout/constants.js:52]: This selector didn't work well for countries that have a text field for their "state"/"province"/"county"

File: client/checkout/constants.js [hunk 5]
```diff
@@ -35,42 +35,22 @@ export function getPaymentMethodsConstants() {
...
-	line1: 'shipping-address_1',
-	line2: 'shipping-address_2',
-	city: 'shipping-city',
-	state: 'components-form-token-input-1',
-	postal_code: 'shipping-postcode',
-	country: 'components-form-token-input-0',
-	first_name: 'shipping-first_name',
-	last_name: 'shipping-last_name',
-};
-export const BLOCKS_BILLING_ADDRESS_FIELDS = {
```
Comment (frosso) [inline client/checkout/constants.js:48]: Not used anymore

File: client/checkout/utils/upe.js [hunk 6]
```diff
@@ -200,28 +200,20 @@ export function isUsingSavedPaymentMethod( paymentMethodType ) {
...
+		select( WC_STORE_CART ).getCustomerData()
+	);
 	const {
 		setShippingAddress,
 		setBillingData,
 		setBillingAddress,
 	} = useDispatch( WC_STORE_CART );
 
 	return {
-		isInitialized,
```
Comment (frosso) [inline client/checkout/utils/upe.js:217]: Not used anywhere

File: client/checkout/utils/upe.js [hunk 7]
```diff
@@ -200,28 +200,20 @@ export function isUsingSavedPaymentMethod( paymentMethodType ) {
...
-		billingData: customerData.billingData,
 		// Backward compatibility billingData/billingAddress
-		billingAddress: customerData.billingAddress,
-		shippingAddress: customerData.shippingAddress,
```
Comment (frosso) [inline client/checkout/utils/upe.js:221]: Not used anywhere

File: client/checkout/utils/upe.js [hunk 8]
```diff
@@ -200,28 +200,20 @@ export function isUsingSavedPaymentMethod( paymentMethodType ) {
...
-		setBillingData,
```
Comment (frosso) [inline client/checkout/utils/upe.js:222]: Not used anywhere

**Comment by botwoo** [comment]
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8021` or branch name `fix/6881-stripe-link-blocks-checkout-refactor` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/6881-stripe-link-blocks-checkout-refactor) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b29595ee67ce3844893e0179c286aa40356cbac5
- Build time: 2024-01-17 09:19:31 UTC

_Note: the build is updated when a new commit is pushed to this PR._

File: client/checkout/stripe-link/index.js [hunk 9]
```diff
@@ -1,133 +1,45 @@
-const showLinkButton = ( linkAutofill ) => {
```
Comment (frosso) [inline client/checkout/stripe-link/index.js:1]: This has been moved to the `client/checkout/classic/payment-processing.js`, since it was specific to the shortcode checkout

File: client/checkout/blocks/payment-processor.js [hunk 10]
```diff
@@ -74,66 +70,64 @@ const PaymentProcessor = ( {
...
+		setBillingAddress,
+	} = useCustomerData();
 
 	useEffect( () => {
 		if ( isLinkEnabled( paymentMethodsConfig ) ) {
 			enableStripeLinkPaymentMethod( {
 				api: api,
 				elements: elements,
 				emailId: 'email',
-				fill_field_method: ( address, nodeId, key ) => {
```
Comment (frosso) [inline client/checkout/blocks/payment-processor.js:86]: Moved from the implementation that was sending individual fields for autofill, to an implementation that sends the complete address for autofill.

It looks like the original implementation was coming from : https://stripe.com/docs/payments/link/autofill-modal#launch-modal

But unfortunately, there were a few issues with it:
- the address "pieces" weren't in line with the WooCommerce core naming convention (hence the addition of the `transformStripeLinkAddress` function
- the `fill_field_method` had issues with determining whether the field was a billing or shipping address - so the `setAddress` check was made for each field
- the `fill_field_method` method was having issues with countries using a non-select "state"/"province" field
- the logic to "split" the name into first/last name was duplicated across shipping and billing address

So I thought that a single `onAutofill` function (which accepts already WC-compatible billing/shipping addresses) to handle all scenarios was going to be more apt to the WC implementation

**Review by mdmoore — APPROVED** [review]
This tests well in shortcode and blocks checkout and all of the changes look good. Nice refactor and cleanup! 🚢
