### PR TITLE
hide capture charge and cancel authorization on status complete/processing

### LINKED ISSUE #4789: [Authorizations] Updating order status to `Processing` before Capturing - Cannot refund order.
### Describe the bug

You can capture payment after setting the order status to processing. However:

* This does not add confirmation about the amount captured in order notes. 
* This also does not let you refund the order

### To Reproduce

1. Enable authorization
2. Create order in the frontend  (don’t capture the charge)
3. Change the order status to `Processing`
4. Capture charge now
5. Notice that order notes is not updated with confirmation about the capture:

    

6. Attempt to capture the order multiple times. No update on the order itself. 
7. On Stripe, you can see that attempt to capture failed since cannot be captured since it is already captured:

    
8. Access _Payments > Transactions_ to confirm that the order is indeed captured:
    
9. Notice that you cannot refund the order from the order details page even though it is successfully captured

    

### Actual behavior

* No confirmation about the captured amount
* Unable to refund the order

### Expected behavior

If the order status is updated to processing before capturing the charge, order notes should still confirm the captured amount if it was successfully captured, and it should let merchants refund the captured amount.

### Desktop (please complete the following information):

* OS: [e.g. iOS]: N/A
* Browser [e.g. chrome, safari]: N/A
* Version [e.g. 22]: N/A

### Additional context

Reported in 5575478-zen

### PR DESCRIPTION
**Pull request by dpaun1985**
Fixes #4789 

For a shop that has capture later option enabled, the merchant can change the order status from 'On hold' to Processing/ Complete. This could mean that the merchant already received the payment from another source.  If the order is already completed, it makes no sense to charge the client twice, and we need to hide the charge options from the order.

**Original issue:** merchant updated the order to a complete status, and after that tried to capture the charge. The capture was charged, but no logs were added to the order since it had a complete status. This led to a misleading of the merchant. 

#### Changes proposed in this Pull Request
Hide Capture charge and cancel authorization options for an order, when the merchant manually changes the status from 'On Hold' to 'Processing'/'Completed'. 

#### Testing instructions

* Go to `Woocommerce -> Settings -> Payments` and under 'Transactions' section enable `Issue an authorization on checkout, and capture later` for the shop
* Create an order 
* Change the order status from 'On Hold' to 'Processing' . Do NOT capture the charge
* The `Capture charge` and`Cancel authorization` should not be shown.  

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

### CODE REVIEW

File: includes/class-wc-payment-gateway-wcpay.php [hunk 1]
```diff
@@ -2097,6 +2097,17 @@ public function add_order_actions( $actions ) {
 			return $actions;
 		}
 
+		// if order is already completed, we shouldn't capture the charge anymore.
+		if (
+			in_array(
+				$theorder->get_status(),
+				[ WC_Payments_Order_Service::STATUS_PROCESSING, WC_Payments_Order_Service::STATUS_COMPLETED ],
```
Comment (kalessil) [inline includes/class-wc-payment-gateway-wcpay.php]: The hard coded list is not friendly to 3rd party extensions - the statuses can be overridden by `woocommerce_order_is_paid_statuses` hook. Consider using `wc_get_is_paid_statuses` function instead.

**Review by kalessil — CHANGES_REQUESTED** [review]

File: includes/class-wc-payment-gateway-wcpay.php (hunk 1 above)
Comment (dpaun1985) [reply includes/class-wc-payment-gateway-wcpay.php]: fixed in [8f955ce](https://github.com/Automattic/woocommerce-payments/pull/5285/commits/8f955cea51219f79877bffd9b553491bc7b2a940)

File: includes/class-wc-payment-gateway-wcpay.php [hunk 2]
```diff
@@ -2097,6 +2097,17 @@ public function add_order_actions( $actions ) {
 			return $actions;
 		}
 
+		// if order is already completed, we shouldn't capture the charge anymore.
```
Comment (kalessil) [inline includes/class-wc-payment-gateway-wcpay.php:2100]: Thanks for placing the comment!

File: includes/class-wc-payment-gateway-wcpay.php [hunk 3]
```diff
@@ -2097,6 +2097,17 @@ public function add_order_actions( $actions ) {
...
+		if (
```
Comment (kalessil) [inline includes/class-wc-payment-gateway-wcpay.php]: Can we put `if ( ... ) {` on one line, please?

**Review by kalessil — APPROVED** [review]
LGTM! Note, I did code review only - no testing.

File: includes/class-wc-payments-order-service.php [hunk 4]
```diff
@@ -17,11 +17,12 @@ class WC_Payments_Order_Service {
...
-	const STATUS_COMPLETED = 'completed';
-	const STATUS_FAILED    = 'failed';
-	const STATUS_ON_HOLD   = 'on-hold';
-	const STATUS_PENDING   = 'pending';
+	const STATUS_CANCELLED  = 'cancelled';
+	const STATUS_COMPLETED  = 'completed';
+	const STATUS_FAILED     = 'failed';
+	const STATUS_ON_HOLD    = 'on-hold';
+	const STATUS_PENDING    = 'pending';
+	const STATUS_PROCESSING = 'processing';
```
Comment (kalessil) [inline includes/class-wc-payments-order-service.php]: Are those states correlating with WooCommerce core constants?

Comment (dpaun1985) [reply includes/class-wc-payments-order-service.php]: the statuses relay to the order status, but since I won't use the constants anymore, I will undo the changes in this file.

File: includes/class-wc-payment-gateway-wcpay.php (hunk 3 above)
Comment (dpaun1985) [reply includes/class-wc-payment-gateway-wcpay.php]: fixed in [222979d](https://github.com/Automattic/woocommerce-payments/pull/5285/commits/222979d301077252af3e6c02e12c16703d6851aa). thx

File: includes/class-wc-payments-order-service.php (hunk 4 above)
Comment (kalessil) [reply includes/class-wc-payments-order-service.php]: :+1:, mind creating a new low-priority issue (for a coll-down week, perhaps) to review and perhaps migrate the WooCommerce Payments codebase on WooCommerce core constants?

Comment (kalessil) [reply includes/class-wc-payments-order-service.php]: Pre-condition for such migration is that constants from the core are including all of the values from this specific place.

Comment (dpaun1985) [reply includes/class-wc-payments-order-service.php]: created an [issue](https://github.com/Automattic/woocommerce-payments/issues/5286) for this. Thank you!

Comment (kalessil) [reply includes/class-wc-payments-order-service.php]: Thanks!

**Review by elazzabi — APPROVED** [review]
LGTM!

Question: This removes the button, but if I understand correctly, this can still happen if we send a direct API call. Should we block it at the API level too?

**Comment by dpaun1985** [comment]
> Question: This removes the button, but if I understand correctly, this can still happen if we send a direct API call. Should we block it at the API level too?

The action is made via a POST action, not an API call. I expect that having nonce in the form, there will not be any security issues. 
However, if you consider, we can double-check also when the charge action is fired. What do you think @elazzabi  ?

File: changelog/fix-4789-status-processing-before-capture [hunk 5]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
+Type: fix
+
+Hide capture charge and cancel authorization options on order when order is completed
```
Comment (anu-rock) [inline changelog/fix-4789-status-processing-before-capture]: Nitpick:

```suggestion
Hide "capture charge" and "cancel authorization" actions on order details page when order status is processing or completed.
```

**Review by anu-rock — COMMENTED** [review]
The code changes LGTM and are aligned with the proposed solution of hiding authorization-related actions on the Order Details page.

My testing also confirms that it works.

* **On hold → Processing** - auth actions hidden ✅ 
* **Processing → On hold** - auth actions visible again ✅ 
* **On hold → Completed** - auth actions hidden ✅ 
* **Completed → On hold** - auth actions visible again ✅ 

However, even after marking an order as completed, it's still possible to capture it through its corresponding Payment Details page (Payments → Transactions).

@mgascam @kalessil - Should we deal with the above in a separate issue?
